### ISSUE TITLE
util_tests/test_LockDirectory failure running tests in WSL guest

### ISSUE THREAD

**Issue by naesar** [bitcoin/bitcoin#14219] opened 2018-09-14 12:09 UTC
Please I need some help with this. Trying to this on Ubuntu 18.04

```
$ make check && sudo make install
Making check in src
make[1]: Entering directory '/usr/src/bitcoin/src'
make[2]: Entering directory '/usr/src/bitcoin/src'
make[3]: Entering directory '/usr/src/bitcoin'
make[3]: Leaving directory '/usr/src/bitcoin'
make  check-TESTS check-local
make[3]: Entering directory '/usr/src/bitcoin/src'
make[4]: Entering directory '/usr/src/bitcoin/src'
make[5]: Entering directory '/usr/src/bitcoin'
make[5]: Leaving directory '/usr/src/bitcoin'
FAIL: test/test_bitcoin
PASS: qt/test/test_bitcoin-qt
============================================================================
Testsuite summary for Bitcoin Core 0.16.2
============================================================================
# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to https://github.com/bitcoin/bitcoin/issues
============================================================================
Makefile:9587: recipe for target 'test-suite.log' failed
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory '/usr/src/bitcoin/src'
Makefile:9693: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory '/usr/src/bitcoin/src'
Makefile:9799: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/usr/src/bitcoin/src'
Makefile:9480: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/usr/src/bitcoin/src'
Makefile:747: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```

**Comment by MarcoFalke** [comment] 2018-09-14 12:30
Please upload `src/test-suite.log`

**Comment by naesar** [comment] 2018-09-14 12:35
$ more src/test-suite.log
=============================================
   Bitcoin Core 0.16.2: src/test-suite.log
=============================================

# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test/test_bitcoin
=======================

Running 276 test cases...
test/util_tests.cpp(695): error: in "util_tests/test_LockDirectory": check (bool)ch == false has failed [true != false]
test/util_tests.cpp(708): error: in "util_tests/test_LockDirectory": check LockDirectory(dirname, lockname, true) == false has failed [true != false]
Running 276 test cases...

*** 2 failures are detected in the test module "Bitcoin Test Suite"
FAIL test/test_bitcoin (exit status: 201)

**Comment by MarcoFalke** [comment] 2018-09-14 12:45
Can you reproduce this issue in some way or provide details on how your setup looks like?

**Comment by naesar** [comment] 2018-09-14 12:59
Ubuntu 18.04, running on windows 10, as a Linux subsystem.
this is a history of commands so far, hope it helps...
![2](https://user-images.githubusercontent.com/28754098/45551615-6b1b0100-b826-11e8-9a2b-f033c5d0eae0.PNG)

**Comment by MarcoFalke** [comment] 2018-09-14 13:05
Do you want to cross compile to windows and run on the host or run bitcoind only in the WSL guest?

**Comment by naesar** [comment] 2018-09-14 13:09
in the WSL guest.

**Comment by MarcoFalke** [comment] 2018-09-14 13:11
Tagging with Windows, since this appears to be WSL specific.

**Comment by ken2812221** [comment] 2018-09-15 09:54
Can confirm this happens on WSL with clang and gcc.

**Comment by ken2812221** [comment] 2018-09-15 18:04
Maybe related Microsoft/WSL#1927

**Comment by sipsorcery** [comment] 2018-09-21 20:35
@naesar did you do a `cd depends` prior to the `make HOST=x86_64-w64-mingw32` command? It's missing from your bash history.

You should not need to install the dependencies manually using `apt-get install libboost-system` etc. If you do it indicates the dependencies were not correctly installed using the provided make configuration.

**Comment by MarcoFalke** [comment] 2020-05-08 23:16
See #18700

**Comment by billygarrison** [comment] 2020-06-27 15:04
Supposedly `make check` is not supported in WSL: https://github.com/bitcoin/bitcoin/issues/13207#issuecomment-388022752

You can run some tests (not sure if it is equivalent to `make check` or not, can anyone comment?) by opening the Windows Command Prompt and running `test_bitcoin.exe`, which will be in whatever location you used as `DESTDIR` in your `make install` command.

**Closed** 2020-06-27 15:06 UTC
Labels: Windows
