### ISSUE TITLE
 Bitcoin-Qt freezes on startup

### ISSUE THREAD

**Issue by QPotato** [bitcoin/bitcoin#16417] opened 2019-07-18 18:37 UTC
Describe the issue:
--------------------------
Bitcoin-Qt freezes on start-up, giving two transparent windows. I suspect it's related to my system clock changing (more details below). This means the issue is not caused by the Bitcoin Core software but, I'm submitting it anyway because the error could maybe be catched and handled more graciously. Even crashing in a secure way would be better: when this happens I'm kinda scared to kill the process and mess the blockchain. 

What behaviour did you expect?
------------------------------------------
Bitcoin-Qt should start normally.

What was the actual behavior (provide screenshots if the issue is GUI-related)?
-----------------------------------------------------------------------------------------------------------
The program freezes giving a transparent Bitcoin Core window and another transparent Bitcoin - Warning window. Screenshot for reference:
![Screenshot_2019-07-18 Screenshot at 2019-07-18 14-52-13 png (PNG Image, 1920 × 1080 pixels) - Scaled (86%)](https://user-images.githubusercontent.com/18300485/61480532-8d147100-a96c-11e9-9487-86cd3e84dfb5.png)

How reliably can you reproduce the issue, what are the steps to do so?
------------------------------------------------------------------------------------------------
When I start my computer on linux after I've been using windows (it's dual boot), the OS changes the system clock seconds after entering the desktop, syncing with some internet time server.  Around 30% of the times, this produces the issue. I suspect the time change in the middle of the initialization makes the software freak out.

It should also occur with any other kind of use that makes the system clock change inmediatly after boot but I mention this details because I think it's a very common use case. I think I could try to manually reproduce the error consistently by changing the system clock on the BIOS if needed.

What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)?
------------------------------------------------------------------------------------------------------------------------------
I believe I installed it from my package manager. It was either that or downloaded from website.

What type of machine are you observing the error on (OS/CPU and disk type)?
----------------------------------------------------------------------------------------------------------
uname -a says: Linux [removed host name] .0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

For the GUI-related issue on Linux provide names and versions of a distro, a desktop environment and a graphical shell (if relevant).
------------------------------------------------------------------------------------------------------------------------------------
Linux Mint 19
Mate 64-bit

Any extra information that might be useful in the debugging process.
--------------------------------------------------------------------------------------------
Logs confirm it's clock related: 
https://pastebin.com/ni7bWgL9

I understand that this issue occurs in very very specific circunstances and it's ok if fixing it is not a priority. If you consider this to be important and it could use a fix, I would be happy to try to investigate it further and submit a PR.

Thanks for reading and for the hard work mantaining this.

**Comment by hebasto** [comment] 2019-07-19 10:37
@QPotato Could you clarify: does a crash happen _after_ the splash screen?

**Comment by MarcoFalke** [comment] 2019-07-19 14:33
It looks like a deadlock because the modal dialog is blocking the GUI?

**Comment by QPotato** [comment] 2019-07-19 16:16
> @QPotato Could you clarify: does a crash happen _after_ the splash screen?
Yes, it's after the splash screen. The two dead dialogs in the screenshot are the main window with the balances, menus and all that and a warning dialog.


> It looks like a deadlock because the modal dialog is blocking the GUI?
I does look like a deadlock.
Any idea wich locks could be causing the problem? Any source file I could look into?


Also, killing the program and restarting was safe. No blockchain resync needed.

**Comment by hebasto** [comment] 2019-07-19 18:13
Cannot reproduce the issue: the warning window does not cause a deadlock.

**Comment by QPotato** [comment] 2019-07-20 20:26
I'm trying to get a more reliable and deterministic way to reproduce the issue. I will comment here if I find one.

**Comment by promag** [comment] 2019-07-23 10:16
@QPotato are you able to reproduce? Can you try with the following patch
```diff
--- a/src/qt/sendcoinsdialog.cpp
+++ b/src/qt/sendcoinsdialog.cpp
@@ -439,7 +439,6 @@ SendCoinsEntry *SendCoinsDialog::addEntry()
     entry->clear();
     entry->setFocus();
     ui->scrollAreaWidgetContents->resize(ui->scrollAreaWidgetContents->sizeHint());
-    qApp->processEvents();
     QScrollBar* bar = ui->scrollArea->verticalScrollBar();
     if(bar)
         bar->setSliderPosition(bar->maximum());
```

**Comment by QPotato** [comment] 2019-07-28 00:17
> @QPotato are you able to reproduce? Can you try with the following patch
> 
> ```diff
> --- a/src/qt/sendcoinsdialog.cpp
> +++ b/src/qt/sendcoinsdialog.cpp
> @@ -439,7 +439,6 @@ SendCoinsEntry *SendCoinsDialog::addEntry()
>      entry->clear();
>      entry->setFocus();
>      ui->scrollAreaWidgetContents->resize(ui->scrollAreaWidgetContents->sizeHint());
> -    qApp->processEvents();
>      QScrollBar* bar = ui->scrollArea->verticalScrollBar();
>      if(bar)
>          bar->setSliderPosition(bar->maximum());
> ```

Working on it. I'll try the patch.

**Comment by fanquake** [comment] 2019-08-04 05:52
@QPotato How did you go testing that patch?

**Comment by QPotato** [comment] 2019-08-04 19:32
> @QPotato How did you go testing that patch?

I finally managed to reproduce the issue consistently.
The node needs to be sufficiently behind on synchronization (some hours is enough) and the system clock wrong. Then, it will start syncing just fine and then crash when the OS changes the time while still syncing.
It also happens with the patch applied.

**Comment by hebasto** [comment] 2019-08-10 11:21
@QPotato 
> I finally managed to reproduce the issue consistently.
The node needs to be sufficiently behind on synchronization (some hours is enough) and the system clock wrong. Then, it will start syncing just fine and then crash when the OS changes the time while still syncing.

Cannot reproduce the issue on Linux Mint 19.2.
During testing my logs contain info about the system clock adjustment:
```
2019-08-10T11:04:12Z Using obfuscation key for /home/hebasto/.bitcoin/testnet3/blocks/index: 0000000000000000
2019-08-10T05:04:15Z LoadBlockIndexDB: last block file = 166
```

In your log I can see a similar change just after a warning message:
```
2019-07-18T14:40:35Z Warning: Please check that your computer's date and time are correct! If your clock is wrong, Bitcoin Core will not work properly.
2019-07-18T17:40:48Z socket sending timeout: 10818s
```

Do I understand correctly that this is a moment when your Linux adjusted the system clock?

**Comment by hebasto** [comment] 2019-08-10 11:24
@QPotato 
Does `bitcoind` behave well in similar circumstances?

**Comment by bitcoinblazer6621** [comment] 2019-08-11 00:32
almost the same issue here.... just upgraded running debian 10...

bitcoin-qt loads the splash screen, verifys the chain and then freezes at the splash screen once the chain is verified and it says done loading.... upgraded by simply copying the new bin files to the old in /usr/local/bin

**Comment by QPotato** [comment] 2019-08-16 17:11
> @QPotato
> Does `bitcoind` behave well in similar circumstances?

Just tested it. `bitcoind` behaves well.

**Comment by promag** [comment] 2019-11-11 22:45
Please assign this to me.

**Comment by hebasto** [comment] 2021-03-25 20:49
A possible reason of the bug: https://github.com/bitcoin/bitcoin/issues/18953#issuecomment-807455467

**Comment by pinheadmz** [comment] 2023-04-27 14:02
This is no longer an issue in recent versions of Bitcoin Core. We'll close it for now, please feel free to add additional comments or open a new issue if you think that would be helpful.

**Closed by pinheadmz** 2023-04-27 14:02 UTC
Labels: GUI, Linux/Unix
