### ISSUE TITLE
Window size renders bitcoin-qt inoperable on 5120x1440

### ISSUE THREAD

**Issue by fsparv** [bitcoin/bitcoin#21442] opened 2021-03-15 14:22 UTC
**Expected behavior**

bitcoin-qt should open at a size that fits within the screen in a timely manner

**Actual behavior**

After a long pause a window several times LARGER than my 5120x1440 screen opens and obscures the entire screen. It is not possible to resize this window and the program is rendered useless, the only option available is quit.

![image](https://user-images.githubusercontent.com/1226061/111165873-e7b50480-8575-11eb-878d-e6b2cd925719.png)

**To reproduce**

1. Download, unpack tarball, 
2. run bin/bitcoin-qt (I think I ran it from the bin directory, not sure).
3. Download transaction history (hundreds of GB, several hours)
4. Decide not to create a wallet, close bitcoin-qt
5. reboot computer (probably not important but it did happen)

Now the following steps reproduce 100%
1. run bin/bitocoin-qt

**System information**
Ubuntu 18.04, GNOME
![image](https://user-images.githubusercontent.com/1226061/111166978-0962bb80-8577-11eb-8857-9a1880a3034e.png)

Probably irrelevant:
Threadripper 1950x cpu
48GB RAM
Samsung 1TB 970 pro nvme drive (all above conducted on mount point on 2nd drive, not system drive, System drive is a 1TB samsung 960 pro)

This seems possibly similar to https://github.com/bit-team/backintime/issues/1124 though I have not observed no console output or logging with bitcoin-qt

**Comment by fsparv** [comment] 2021-03-15 14:28
Note, reducing screen resolution to 2560x1440 via Picture -by- Picture feature (sets the monitor to expect 2 inputs of half size, leading to right half of screen blank with "no signal") allows opening normally

**Comment by fsparv** [comment] 2021-03-15 14:34
Once using the workaround I found a button to display logs, and found these which resembel the backintime bug
````
2021-03-15T14:29:32Z Bitcoin Core version v0.21.0 (release build)
2021-03-15T14:29:32Z Qt 5.9.8 (static), plugin=xcb (static)
2021-03-15T14:29:32Z System: Ubuntu 18.04.5 LTS, x86_64-little_endian-lp64
2021-03-15T14:29:32Z Screen: DP-0 4x1, pixel ratio=1355.0
2021-03-15T14:29:32Z GUI: QPainter::begin: Paint device returned engine == 0, type: 2
2021-03-15T14:29:32Z GUI: QPainter::setPen: Painter not active
2021-03-15T14:29:32Z GUI: QPainter::setFont: Painter not active
2021-03-15T14:29:32Z GUI: QPainter::fontMetrics: Painter not active
2021-03-15T14:29:58Z GUI: QPainter::setFont: Painter not active
2021-03-15T14:29:58Z GUI: QPainter::fontMetrics: Painter not active
2021-03-15T14:29:58Z GUI: QPainter::setFont: Painter not active
2021-03-15T14:29:58Z GUI: QPainter::fontMetrics: Painter not active
2021-03-15T14:30:02Z GUI: QPainter::setFont: Painter not active
2021-03-15T14:30:02Z GUI: QPainter::end: Painter not active, aborted
````

**Comment by jarolrod** [comment] 2021-03-15 14:37
@fsparv Hey 👋, sorry to hear the GUI is not working for you. We have a repo dedicated for the GUI: https://github.com/bitcoin-core/gui. Any future issues should be opened there.

This is actually a duplicate of: https://github.com/bitcoin-core/gui/issues/175

Thanks for bringing this to our attention. This is a serious bug that will require some investigation.

**Closed** 2021-03-15 14:40 UTC
Labels: Bug

**Comment by shaun-ba** [comment] 2021-08-19 15:55
@jarolrod If so why is this closed and my original issue not investigated or fixed by now?

I've just launched 0.21.1 and it's still the same, totally unusable on my multiple monitor setup.

This is the only software I've ever run on this setup with such an issue, surely this is a simple fix??

**Comment by hebasto** [comment] 2021-08-19 16:07
@shaun-ba 

> why is this closed and my original issue not investigated or fixed by now?

Because 

> This is actually a duplicate of: [bitcoin-core/gui#175](https://github.com/bitcoin-core/gui/issues/175)

---

> This is the only software I've ever run on this setup with such an issue, surely this is a simple fix??

Yes, this could be a simple fix. But the issue is hardware specific, and it is required to have this specific hardware disposable to a developer to investigate the issue and fix it.
