### ISSUE TITLE
Tray icon in wrong location and missing menu integration in Unity on Ubunutu 14.04 LTS after upgrade to 0.13.1

### ISSUE THREAD

**Issue by linkp** [bitcoin/bitcoin#9038] opened 2016-10-28 22:08 UTC
### Describe the issue

Tray icon appearing in upper left of screen instead of in Unity notification area after upgrading from 0.13.0. Menu integration with Unity fails leaving application without standard menus.
#### If so, please list the steps to reproduce below:
1. Upgrade from 0.13.0 to 0.13.1 using Bitcoin PPA
2. Launch Bitcoin
3. Tray icon appears in wrong place and application window has no menus in Unity menu bar.
### Expected behaviour

Tray icon should appear in system notification area and menus should appear in Unity menu bar.
### Actual behaviour

Tray icon appears in upper left of window on top of Unity menu bar. Standard menus are missing.
### Screenshots.

With appmenu-qt5 installed
![appmenu-qt5](https://cloud.githubusercontent.com/assets/3360118/19823839/5a8445ec-9d28-11e6-9f68-b74a83b5ce87.png)

Without appmenu-qt5 installed
![no-appmenu-qt5](https://cloud.githubusercontent.com/assets/3360118/19823840/5a8470da-9d28-11e6-8864-faa984eb6b5f.png)
### What version of bitcoin-core are you using?

http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu trusty main #Bitcoin PPA
bitcoin-qt:amd64/trusty 0.13.1-trusty1 uptodate
bitcoind:amd64/trusty 0.13.1-trusty1 uptodate
### Machine specs:
- OS: Ubuntu 14.04.5 LTS
- CPU: Intel(R) Core(TM) i5 CPU M 520  @ 2.40GHz
- RAM: 7.8G (8G)
- Disk size: 158G
- Disk Type (HD/SDD): SSD

**Comment by TheBlueMatt** [comment] 2016-10-28 22:13
Note that this is likely a qt5 issue, as 0.13-ppa used qt4.

**Comment by vcatao** [comment] 2016-10-30 18:56
My icon is actually gone (in Ubuntu's top bar).
When I try to start it from the dash/launcher, it says Bitcoin is already on (but I cannot have access to the window, due to the missing icon in the top bar).

I have to close the process through the gnome-system-monitor and start it again.

**Comment by vcatao** [comment] 2016-10-30 19:00
> Note that this is likely a qt5 issue, as 0.13-ppa used qt4.

Bitcoin says it uses Qt 5.5.1
Go to **Help / About Qt** and see for yourself ("This program uses Qt version 5.5.1.").

**Comment by achow101** [comment] 2016-10-31 04:17
Try the solution here: https://github.com/bitcoin/bitcoin/issues/7497#issuecomment-182341185

**Comment by linkp** [comment] 2016-10-31 14:40
Removing appmenu-qt5 did not resolve it. See the screenshots in my initial report for examples both with and without appmenu-qt5 installed.

**Comment by TheBlueMatt** [comment] 2016-10-31 15:33
Pushed new 0.13.1 versions to the ppa which reverted to using qt4. Can y'all re-test when updates to version 0.13.1-*2 are available (probably in a half hour or so).

**Comment by laanwj** [comment] 2016-10-31 15:50
Looks like a duplicate of #8043. This has been a known issue for a while. I expect it to be an upstream issue in Qt, or at least Ubuntu's Qt.

**Comment by linkp** [comment] 2016-10-31 15:59
The symptoms are different. I have a tray icon. It just appears in the wrong place. My tray icon menus also work, unlike the screenshot included #8043.

I do expect the root cause is related, however.

**Comment by talklittle** [comment] 2016-10-31 17:42
Confirmed that new update 0.13.1-xenial2 fixes the problem.

(Ubuntu 16.04.1. Bitcoin Core 0.13.1 caused the tray icon to disappear entirely.)

**Comment by vcatao** [comment] 2016-10-31 18:44
> Confirmed that new update 0.13.1-xenial2 fixes the problem.

Indeed, it is fixed. I'm on 16.04 Xenial, and I have the tray icon again. Also, previously, removing appmenu-qt5 fixed, but my installed theme stopped working properly.
Now, with the last upgrade, bitcoin-qt is working again, no package had to be removed, and my gnome theme is working too.

**Comment by linkp** [comment] 2016-10-31 19:11
Symptoms resolved on Trusty with 0.13.1-trusty2

**Comment by laanwj** [comment] 2016-11-03 09:50
Closing, as issues (apparently with PPA) are resolved.

**Closed** 2016-11-03 09:50 UTC
Labels: GUI, Linux/Unix, Upstream

**Comment by TheBlueMatt** [comment] 2016-11-03 12:27
It would be nice to get this fixed (if there is anything we can do about it) so that the POA can migrate to qt5 instead of being stuck on qt4.

**Comment by laanwj** [comment] 2016-11-03 12:38
The only thing we could do about this is (optionally) link against Ubuntu's tray driver and use that directly instead of QTrayIcon. This would then be aimed at the PPA (and people building manually on Ubuntu) only. I've looked at this at some point but it's not really something I intend to spend a lot of time on.

The other option would is to wait for upstream to get their act together (as this will affects any qt5 application w/ tray). This is my preference, but could take a while. Or for tray icons as a UI concept to die out.

**Comment by TheBlueMatt** [comment] 2016-11-03 12:57
Hum, ok :/ Given that tray icons seem to be dying out maybe we should just move that direction.

**Comment by laanwj** [comment] 2017-04-06 10:36
Looks like [the end of life for Unity](http://www.omgubuntu.co.uk/2017/04/ubuntu-18-04-ship-gnome-desktop-not-unity) is also approaching. That would fix the tray icon issue too, I guess.
