### ISSUE TITLE
Non-boolean const value in && expression.

### ISSUE THREAD

**Issue by kallewoof** [bitcoin/bitcoin#20693] opened 2020-12-18 06:01 UTC
Chances are high people know about this already, but this code really does look broken:

```C++
wallet/scriptpubkeyman.cpp: In member function ‘virtual bool LegacyScriptPubKeyMan::Upgrade(int, bilingual_str&)’:
wallet/scriptpubkeyman.cpp:456:55: warning: logical ‘and’ applied to non-boolean constant [-Wlogical-op]
  456 |     if (m_storage.CanSupportFeature(FEATURE_HD_SPLIT) && CHDChain::VERSION_HD_CHAIN_SPLIT) {
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Especially considering we do things like this:
```C++
    newHdChain.nVersion = m_storage.CanSupportFeature(FEATURE_HD_SPLIT) ? CHDChain::VERSION_HD_CHAIN_SPLIT : CHDChain::VERSION_HD_BASE;
```
which will trigger the above if case for both cases, since both are non-zero.

Maybe this code is just dead and thus this doesn't matter?

**Comment by sipa** [comment] 2020-12-18 06:08
I think this was fixed in #19986.

**Comment by kristapsk** [comment] 2020-12-18 06:08
Duplicate of #19912, fixed by #19986. No? I don't see code above on a current master.

**Comment by MarcoFalke** [comment] 2020-12-18 06:10
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?

**Closed by MarcoFalke** 2020-12-18 06:10 UTC
Labels: Bug

**Comment by kallewoof** [comment] 2020-12-18 06:53
Aha! I saw this in a working branch which was not on latest master. Thanks!
