### ISSUE TITLE
ci: `AssertionError: 1759238429.9936483` <= 1759238430 in `wallet_encryption.py --descriptors`

### ISSUE THREAD

**Issue by w0xlt** [bitcoin/bitcoin#25758] opened 2022-07-31 05:57 UTC
`Win64 native [vs2022]` CI check in  https://github.com/bitcoin/bitcoin/pull/25747 generated the error:

```
183/246 - wallet_encryption.py --descriptors failed, Duration: 7 s
stdout:
2022-07-31T03:33:43.922000Z TestFramework (INFO): Initializing test directory C:\Users\ContainerAdministrator\AppData\Local\Temp\test_runner_₿_🏃_20220731_024158\wallet_encryption_65
2022-07-31T03:33:49.648000Z TestFramework (INFO): Check a timeout less than the limit
2022-07-31T03:33:49.821000Z TestFramework (INFO): Check a timeout greater than the limit
2022-07-31T03:33:49.993000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 133, in main
    self.run_test()
  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\wallet_encryption.py", line 93, in run_test
    assert_greater_than(expected_time_with_buffer, actual_time)
  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\util.py", line 57, in assert_greater_than
    raise AssertionError("%s <= %s" % (str(thing1), str(thing2)))
AssertionError: 1759238429.9936483 <= 1759238430
```

The error seems related to floating point precision `AssertionError: 1759238429.9936483 <= 1759238430` or something intermittent.

https://cirrus-ci.com/task/5935928832163840

**Comment by fanquake** [comment] 2022-07-31 10:46
Duplicate of #25482.

**Closed by fanquake** 2022-07-31 10:46 UTC
