### ISSUE TITLE
-fallbackfee should apply to estimatesmartfee

### ISSUE THREAD

**Issue by kylezs** [bitcoin/bitcoin#27415] opened 2023-04-04 00:50 UTC
### Please describe the feature you'd like to see added.

`-fallback` fee is used by `sendtoaddress` to provide a fallback fee when sending transactions. However, this does not apply to `estimatesmartfee`, which still returns the error.

### Is your feature related to a problem, if so please describe it.

The reason for this is because it's difficult to test client applications on regtest, that would use `estimatesmartfee` on mainnet, but because it requires a lot of transactions before `estimatesmartfee` to work, it's difficult. This related stack exchange question has had a bit of interest:
https://bitcoin.stackexchange.com/questions/89607/how-can-i-force-estimatesmartfee-to-return-estimates-on-regtest

### Describe the solution you'd like

See above.

### Describe any alternatives you've considered

- A separate flag would also work, like `fallbackestimatefee`

**Comment by willcl-ark** [comment] 2023-04-05 21:49
@kylezs Could you program your test to use the `--fallbackfee` if it recieves the error in reponse, or as Antoine reponded to you there fill up your test mempool so that `estimatesmartfee` works as intended?

Accessing `--fallbackfee` from within the fee estimation rpc involves importing a lot of wallet code which woudl be preferable to avoid...

**Comment by kylezs** [comment] 2023-05-02 15:36
> What's the problem with just doing error handling, and manually applying your own fallback fee? Faking a result is another layer of confusion imo

Because a -fallback fee already exists. Why can't it exist for other use cases?

**Comment by kylezs** [comment] 2023-06-02 07:22
> If your test isn't concerned with the fee estimator's exact behavior, as @instagibbs says, you can mock it or load a placeholder fee_estimates.dat file to populate the estimator with data.

This might be the way to go, is there one that exists that can be downloaded and loaded in? I don't really mind what the exact behaviour of the estimator is.

**Comment by instagibbs** [comment] 2023-06-02 13:39
Any long-running node has them if the node has ever restarted. I just grabbed one locally when needed.

**Comment by instagibbs** [comment] 2023-06-02 13:46
https://github.com/bitcoin/bitcoin/pull/27622 might want to keep an eye on this though, I think we should probably have a flag allowing any age of file, exposed on regtest/hidden only?

**Comment by glozow** [comment] 2023-06-02 14:32
I'm going to close this particular request as I think it's clear we shouldn't add a fallback feerate for the estimator.
Will keep in mind the importance of being able to easily load a fee_estimates.dat for testing. Thanks very much for your feedback @kylezs!

**Closed by glozow** 2023-06-02 14:32 UTC
Labels: TX fees and policy, Questions and Help

**Comment by kylezs** [comment] 2023-06-02 14:36
Sounds good. Cheers!
