### ISSUE TITLE
getrawtransaction for outputs with multiple addresses

### ISSUE THREAD

**Issue by gbeced** [bitcoin/bitcoin#5805] opened 2015-02-19 13:54 UTC
I noted that starting with v0.10.1 the behavior of getrawtransaction when there are multiple addresses in one output has changed.

For example:
```
getrawtransaction 7657d78f1b69c875d475fe6521db5be03162a861893c462b1a335ebbb10db530 1
```

used to return 2 addresses for the 2nd output

```
{
"value" : 0.00007800,
"n" : 1,
"scriptPubKey" : {
"asm" : "1 040286a47e8b11624c510881521b73a02929b9615d219100300c651771c0cf46c04b14cfa790e3f66940d11b5ab3d8ae81a3577473fbd36e2fc2b3d69e91d9af62 1c434e54525052545900000000000000000004ebdf00000015d7a1850000000000 2 OP_CHECKMULTISIG",
"hex" : "5141040286a47e8b11624c510881521b73a02929b9615d219100300c651771c0cf46c04b14cfa790e3f66940d11b5ab3d8ae81a3577473fbd36e2fc2b3d69e91d9af62211c434e54525052545900000000000000000004ebdf00000015d7a185000000000052ae",
"reqSigs" : 1,
"type" : "multisig",
"addresses" : [
"1Po1oXMCWobE6kxWr8rJEP1SRq71JSD3t4",
"1HT7xU2Ngenf7D4yocz2SAcnNLW7rK8d4E"
]
}
}
```

but now it returns only one address:

```
{
"value" : 0.00007800,
"n" : 1,
"scriptPubKey" : {
"asm" : "1 040286a47e8b11624c510881521b73a02929b9615d219100300c651771c0cf46c04b14cfa790e3f66940d11b5ab3d8ae81a3577473fbd36e2fc2b3d69e91d9af62 1c434e54525052545900000000000000000004ebdf00000015d7a1850000000000 2 OP_CHECKMULTISIG",
"hex" : "5141040286a47e8b11624c510881521b73a02929b9615d219100300c651771c0cf46c04b14cfa790e3f66940d11b5ab3d8ae81a3577473fbd36e2fc2b3d69e91d9af62211c434e54525052545900000000000000000004ebdf00000015d7a185000000000052ae",
"reqSigs" : 1,
"type" : "multisig",
"addresses" : [
"1Po1oXMCWobE6kxWr8rJEP1SRq71JSD3t4"
]
}
}
```

**Comment by dexX7** [comment] 2015-02-20 21:35
@gbeced: the payload:
```
1c434e54525052545900000000000000000004ebdf00000015d7a1850000000000
```
... is not a valid public key. 0.9 still converted it into an address, but 0.10 does not.

**Comment by gbeced** [comment] 2015-02-21 03:25
Would you know if this is related to the changes in CPubKey::IsFullyValid to use secp256k1_ecdsa_verify ?
Thanks

**Comment by gbeced** [comment] 2015-02-21 03:26
I meant secp256k1_ecdsa_pubkey_verify.

**Comment by dexX7** [comment] 2015-02-21 14:58
@gbeced: this one is to "blame":

Don't return an address for invalid pubkeys: https://github.com/bitcoin/bitcoin/commit/9d7cd4c598edfff12f1f80629c9149b3f1cf75a6
And this is related to this topic: https://github.com/bitcoin/bitcoin/pull/5247

**Comment by paveljanik** [comment] 2015-10-01 19:33
As this is a feature, not a bug, can you please close the issue? Thank you.

**Closed** 2015-10-02 01:32 UTC
