### ISSUE TITLE
Official bitcoin.conf documentation

### ISSUE THREAD

**Issue by eriksank** [bitcoin/bitcoin#7733] opened 2016-03-22 08:33 UTC
I have been looking everywhere (bitcoin.org and here at github) for the official documentation for the `bitcoin.conf` file. I could not find it, though. Does this documentation exist?

I am especially interested in the documentation for the `blocknotify` and `walletnotify` fields.

When do they trigger? In my impression, `blocknotify` triggers for every block, but I am not sure about `walletnotify`. Does it trigger for every transaction, or only for transactions mentioning addresses from the wallet? Sometimes it seems to even trigger twice for the same transaction hash.

Are `blocknotify` or `walletnotify` affected in any way by addresses imported through the `importaddress` RPC function?

**Comment by jonasschnelli** [comment] 2016-03-22 08:43
Some people recently discussed this on IRC and a possible solution would be to place a sample `bitcoin.conf` during the initial datadir creation. The sample `bitcoin.conf` could contain (#commented out) all relevant options with some explanations.

It could also be stored under a different filename (`bitcoin.sample.con`) (some people might say the bitcoin.conf should only be created/controlled by the package maintainers).

**Comment by achow101** [comment] 2016-03-22 21:28
There is documentation on it on the wiki at https://en.bitcoin.it/wiki/Running_Bitcoin#Bitcoin.conf_Configuration_File but I think it would also be a good idea to have a sample bitcoin.conf file included in the install.

**Comment by eriksank** [comment] 2016-03-23 06:46
https://en.bitcoin.it/wiki/Running_Bitcoin#Bitcoin.conf_Configuration_File
```
-walletnotify=<cmd> 	Execute command when a wallet transaction changes (%s in cmd is replaced by TxID) 
```
Does this mean: transactions mentioning just wallet addresses or does it also cover imported addresses? There does not seem to be a notification option that would notify for 'any' address (regardless whether it is in the wallet or not)?

**Comment by sipa** [comment] 2016-03-23 06:55
An imported address is considered to be a wallet address.

-walletnotify will run the command whenever 1) the transaction is first
seen (usually when unconfirmed) 2) the transaction is seen in a block.

**Comment by laanwj** [comment] 2016-03-23 10:51
I think you can safely remove 'bitcoin.conf' from the issue title. The project doesn't have any official user documentation at all. (nor anyone volunteering to write such.)

As usually with open source projects you need to be someone more crafty to find documentation resources. There are some though:

- The developer documentation (guide and reference) on bitcoin.org comes closest to this: https://bitcoin.org/en/developer-documentation. They are excellently written by @harding et al.
- As mentioned, the wiki.
- For specific questions (such as about `walletnotify` and `blocknotify`) you should use the stack exchange: https://bitcoin.stackexchange.com/

**Comment by MarcoFalke** [comment] 2016-03-23 23:59
Just to mention for completeness: There is an unmaintained `.conf` in [/contrib/debian/examples/bitcoin.conf](https://github.com/bitcoin/bitcoin/blob/ad57b310bac44a7e470cf66276421f2bbc61b1f0/contrib/debian/examples/bitcoin.conf)

**Comment by laanwj** [comment] 2016-06-22 10:55
Nothing left to be done here, closing.

**Closed by laanwj** 2016-06-22 10:55 UTC
Labels: Docs and Output, Feature

**Comment by sapph1re** [comment] 2020-05-05 06:07
So as I can see, the issue is closed, and there is a sample [bitcoin.conf](https://github.com/bitcoin/bitcoin/blob/master/share/examples/bitcoin.conf) in the repo with helpful comments, but blocknotify & walletnotify are not even mentioned there? Wouldn't it make sense to mention them?

**Comment by MarcoFalke** [comment] 2020-05-05 10:37
You can get documentation with `bitcoind -?`

**Comment by MarcoFalke** [comment] 2020-05-05 10:38
or with the manpages, of course
