### ISSUE TITLE
Bitcoin core crash on windows 10

### ISSUE THREAD

**Issue by lasseleegaard** [bitcoin/bitcoin#7036] opened 2015-11-17 01:58 UTC
Bitcoin core  v 0.11.2 crashes immidiately after start on fresh install on windows 10.
Reboot and reinstall of client made no difference.

![bitcoin crash](https://cloud.githubusercontent.com/assets/1957078/11200481/d5d1efc8-8cd6-11e5-85c0-7252c5cf82e2.PNG)

**Comment by fanquake** [comment] 2015-11-17 02:28
Was v0.11.0/v0.11.1 running fine before you installed v0.11.2?

**Comment by lasseleegaard** [comment] 2015-11-17 02:31
Dont know. This is a completely new install. Have not had bitcoin core
installed before

-- 
-Lasse-

On 17. nov. 2015, at 03.29, Michael Ford <notifications@github.com> wrote:

Was v0.11.0/v0.11.1 running fine before you installed v0.11.2?

On Tuesday, November 17, 2015, Lasse Leegaard <notifications@github.com>
wrote:

> Bitcoin core v 0.11.2 crashes immidiately after start on fresh install on
> windows 10.
> Reboot and reinstall of client made no difference.
>
> [image: bitcoin crash]
> <
https://cloud.githubusercontent.com/assets/1957078/11200481/d5d1efc8-8cd6-11e5-85c0-7252c5cf82e2.PNG
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitcoin/bitcoin/issues/7036>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/bitcoin/bitcoin/issues/7036#issuecomment-157246984>.

**Comment by MarcoFalke** [comment] 2015-11-17 07:36
@lasseleegaard  Could you try to locate the debug.log ( https://en.bitcoin.it/wiki/Data_directory#Windows ) and upload the relevant part or the full debug.log?

**Comment by lasseleegaard** [comment] 2015-11-17 12:24
Hi,

The folder is there, but it is empty.

-Lasse-

**Comment by laanwj** [comment] 2015-11-19 14:22
Is the data directory that you selected on first run perhaps inaccessible for your user?

**Comment by lasseleegaard** [comment] 2015-11-19 14:56
I didnt select a data directory myself.
I chose the default installation directory.

I assume I have access to my own %APPDATA%

-- 
-Lasse-

On 19. nov. 2015, at 15.24, Wladimir J. van der Laan <
notifications@github.com> wrote:

Is the data directory that you selected on first run perhaps inaccessible
for your user?

—
Reply to this email directly or view it on GitHub
<https://github.com/bitcoin/bitcoin/issues/7036#issuecomment-158071490>.

**Comment by laanwj** [comment] 2015-11-19 15:44
Ok. Was the only reason I could think of why it would crash *before* writing to debug.log.

Do you have non-ASCII characters in your username? Should normally not be an issue but maybe in special cases.

You could try placing the datadir somewhere else by passing `-choosedatadir` as command line argument.

**Comment by lasseleegaard** [comment] 2015-11-19 20:04
Hep!

I tried a few different locations and tried creating the folder before I
started bitcoin and tried removing the folder before starting bitcoin.
It helped. What worked was having the folder NOT be there before starting
the program and then it would start up and start syncing.

Thanks for the assistance.

-Lasse-

On Thu, Nov 19, 2015 at 4:45 PM Wladimir J. van der Laan <
notifications@github.com> wrote:

> Ok. Was the only reason I could think of why it would crash *before*
> writing to debug.log.
>
> Do you have non-ASCII characters in your username? Should normally not be
> an issue but maybe in special cases.
>
> You could try placing the datadir somewhere else by passing -choosedatadir
> as command line argument.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitcoin/bitcoin/issues/7036#issuecomment-158095278>.
>
-- 
-- 
-Lasse-

**Comment by MarcoFalke** [comment] 2015-11-19 20:19
@lasseleegaard Good to hear. If this resolved your problem, please close the issue on GitHub.

**Closed** 2015-11-19 22:31 UTC
Labels: Windows

**Comment by laanwj** [comment] 2015-11-20 07:34
Strange. Good that you eventually got it to work.

**Comment by rebroad** [comment] 2016-02-16 20:33
@lasseleegaard I would argue bitcoin-qt should be able to cope with this situation though, and therefore this issue ought to stay open until it does.

**Comment by MarcoFalke** [comment] 2016-02-26 07:56
I can't reproduce on Fedora.
