### ISSUE TITLE
Windows crashes for -wallet=你好

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#13754] opened 2018-07-24 15:55 UTC
Invalid characters for a wallet name, e.g. `bitcoin-qt -wallet=你好` used to result in an error like this

<img width="494" alt="schermafbeelding 2018-07-24 om 17 46 37" src="https://user-images.githubusercontent.com/10217/43150553-7bdf598a-8f6a-11e8-8972-44c311a57e56.png">

But now it just crashes:

<img width="509" alt="schermafbeelding 2018-07-24 om 17 43 26" src="https://user-images.githubusercontent.com/10217/43150605-9cf32192-8f6a-11e8-9333-87d074c8dd35.png">

I didn't do a `git bisect`, but it broke somewhere this year :-)

**Comment by achow101** [comment] 2018-07-24 16:05
Reported in #13103 and possible fix in #13426

**Comment by Sjors** [comment] 2018-07-24 17:11
@achow101 this is worse than what led to 13426:

> -wallet=d:\錢包 does works

It doesn't work at all (for me).

But perhaps that PR makes this problem go away too. Will test later.

**Comment by ken2812221** [comment] 2018-07-24 23:04
I don't think this can be fixed by #13426, our bdb api does not support unicode on Windows.

**Comment by Sjors** [comment] 2018-07-25 08:21
For the scope of this ticket, I'm happy if unicode wallet names throw an error message, instead of crashing. That's assuming this was always the case, because otherwise users get locked out of old wallets.

I think unicode already works on my machine (a6f00ce66f):
<img width="787" alt="schermafbeelding 2018-07-25 om 10 17 04" src="https://user-images.githubusercontent.com/10217/43188222-e7c34fce-8ff3-11e8-97b8-dea53cd43291.png">

It's just passing characters in at launch that seems broken.

Although it won't let me add such characters to bitcoin.conf either:
<img width="652" alt="schermafbeelding 2018-07-25 om 10 19 17" src="https://user-images.githubusercontent.com/10217/43188428-56d1fdac-8ff4-11e8-9a03-fc3cdbf30a75.png">

After save:
<img width="254" alt="after save" src="https://user-images.githubusercontent.com/10217/43188457-6d3f1412-8ff4-11e8-9ea3-607e408c284f.png">

This might be expect behavior; at least Windows clearly warns against doing this.

**Comment by Sjors** [comment] 2018-07-25 09:30
Just tried #13426 and it also crashes (rather than throw an error).

**Comment by Sjors** [comment] 2018-07-25 09:53
Actually it's more complicated. As the page @ken2812221 links to points out, there are applications that don't support Unicode, and for those Windows can switch the language (system wide). That probably includes the shel, the launch-from-search feature I used and the ANSI encoded file Notepad complained about.

It's a bit hard to find in Windows 10, maybe this helps:
<img width="1277" alt="schermafbeelding 2018-07-25 om 11 44 39" src="https://user-images.githubusercontent.com/10217/43193385-2d63ef46-9000-11e8-8dd1-6f28ff7227cf.png">

Don't worry, this will not change your entire desktop into Mandarin. But now you can do this without a crash:

<img width="431" alt="schermafbeelding 2018-07-25 om 11 47 06" src="https://user-images.githubusercontent.com/10217/43193525-89405d86-9000-11e8-9e41-4040db8d3cd6.png">

This neatly creates the wallet:
<img width="340" alt="schermafbeelding 2018-07-25 om 11 50 47" src="https://user-images.githubusercontent.com/10217/43193707-061e47aa-9001-11e8-9543-a243ff843407.png">

But the RPC gets confused:
<img width="746" alt="though" src="https://user-images.githubusercontent.com/10217/43193717-0d931858-9001-11e8-91c5-7d527ea931cc.png">

And that's where #13426 shows its magic:
<img width="401" alt="schermafbeelding 2018-07-25 om 11 53 13" src="https://user-images.githubusercontent.com/10217/43193865-616b3bae-9001-11e8-8e81-d590a08d3233.png">

**Comment by MarcoFalke** [comment] 2018-08-01 15:51
Confirmed that the issue still exists on current master. Also with an assertion hit:

![screenshot from 2018-08-01 11-45-47](https://user-images.githubusercontent.com/6399679/43532661-222c55b0-9581-11e8-9994-91168fe46241.png)

**Comment by MarcoFalke** [comment] 2018-08-03 12:50
This seems to be the cause: https://github.com/bitcoin/bitcoin/commit/26c06f24e5dcc32a7599abb8d670d22993c82bc2#diff-3b23ce4d86903a432863cfb3a1f1e547L238

I am not sure how to fix this, since I can't see the exception that is thrown on this file name.

We might just add to the release notes that windows users should only use ascii-filenames that are valid under windows?

**Comment by Sjors** [comment] 2018-08-03 17:24
Sounds like that second check shouldn't have been removed. Maybe we can put it back, but only apply `SanitizeString` the filename component of the path?

**Comment by ken2812221** [comment] 2018-08-03 19:41
`SanitizeString` seem to make the wallet filename be ASCII only. Do we want to do that?

**Comment by Sjors** [comment] 2018-08-03 19:58
If it was that way before, that seems safest. We can allow UTF-8 names in your PR.

**Comment by Sjors** [comment] 2018-08-03 20:01
Oh wait, I think that commit is already in 0.16? Then we can't put the constraint back because that could lock out wallets.

**Comment by MarcoFalke** [comment] 2018-08-03 20:10
No, it wasn't backported IIRC.

**Closed** 2018-08-09 12:06 UTC
Labels: Wallet, Windows
