### ISSUE TITLE
Assertion failed! rpcwallet.cpp Line 3838

### ISSUE THREAD

**Issue by mrbabtc** [bitcoin/bitcoin#18944] opened 2020-05-11 12:31 UTC
Im on W10 x64 using the GUI.
I'm syncing, the wallet is key disabled and it has 30k address watch only, all these are segwit p2sh.
When I execute the rpc command `getaddressesbylabel ""` I get the following error message
![image](https://user-images.githubusercontent.com/58831694/81561737-08b33480-936a-11ea-841b-bd3536cb8cce.png)

If I click Anular , bitcoin core crash
If I click Omitir I get the rpc response:
`{
  "": {
    "purpose": "unknown"
  },
  "": {
    "purpose": "unknown"
  }
}`

**Comment by jonasschnelli** [comment] 2020-05-11 12:41
It looks like you have duplicated addresses in your wallet.

```
// CWallet::mapAddressBook is not expected to contain duplicate
// address strings, but build a separate set as a precaution just in
// case it does.
bool unique = addresses.emplace(address).second;
```

How did you import the addresses/scripts?

**Comment by MarcoFalke** [comment] 2020-05-11 12:44
For reference, this is the code:

https://github.com/bitcoin/bitcoin/blob/v0.19.1/src/wallet/rpcwallet.cpp#L3828-L3845

**Comment by mrbabtc** [comment] 2020-05-11 13:58
> It looks like you have duplicated addresses in your wallet.
> 
> ```
> // CWallet::mapAddressBook is not expected to contain duplicate
> // address strings, but build a separate set as a precaution just in
> // case it does.
> bool unique = addresses.emplace(address).second;
> ```
> 
> How did you import the addresses/scripts?

W

> It looks like you have duplicated addresses in your wallet.
> 
> ```
> // CWallet::mapAddressBook is not expected to contain duplicate
> // address strings, but build a separate set as a precaution just in
> // case it does.
> bool unique = addresses.emplace(address).second;
> ```
> 
> How did you import the addresses/scripts?

I import it with importMulti , but maybe I import it some duplicates, how I could check it?
Anyways, shouldn't be possible to import again the same privkey/address

**Comment by ryanofsky** [comment] 2020-05-11 14:51
Looking at the code https://github.com/bitcoin/bitcoin/issues/18944#issuecomment-626678678, it seems like this should only happen if there are two CTxDestination objects that don't compare equal but do have the same EncodeDestination string representation. Am I misreading or is the something known to happen?

**Comment by mrbabtc** [comment] 2020-05-11 15:51
I created a new wallet with these 30k address and I can correctly run the rpc command, but IDK why could be repeated address or keys in a wallet file created with same bitcoin core

**Comment by MarcoFalke** [comment] 2020-05-11 17:45
@ryanofsky This happens at least in the case of two malformed `WitnessUnknown` and/or a `CTxNoDestination`, right?

**Comment by MarcoFalke** [comment] 2020-05-11 17:45
All of them map to an empty string

**Comment by MarcoFalke** [comment] 2020-05-14 12:41
Though, it should be impossible to import malformed WitnessUnknown, see #18974

**Comment by MarcoFalke** [comment] 2020-05-14 15:01
Could this be caused by a corrupted bdb file?

**Comment by pinheadmz** [comment] 2023-04-27 13:54
This is no longer an issue in recent versions of Bitcoin Core. We'll close it for now, please feel free to add additional comments or open a new issue if you think that would be helpful.

**Closed by pinheadmz** 2023-04-27 13:54 UTC
Labels: Bug, Wallet, RPC/REST/ZMQ
