### ISSUE TITLE
Peer is still banned, allthough ban endtime has been reached

### ISSUE THREAD

**Issue by wodry** [bitcoin/bitcoin#11612] opened 2017-11-05 16:59 UTC
### Peer is still banned, allthough ban endtime has been reached

Here the log line of the banned peer:

`2017-11-04 16:12:03 Misbehaving: 212.203.47.xxx:61681 peer=56085 (0 -> 100) BAN THRESHOLD EXCEEDED`

In the debug connection window, the peer shows up as banned, with the ban endtime of 2017-11-05 17:12:03 CET, see screenshot (marked blue peer).

Then today, 2017-11-05 around 10 o clock CET, I stopped bitcoind 0.15.0.1, replaced the binaries with 0.15.1rc1 and started bitcoind again.

Now, as the time of the screenshot is 17:40 CET, the ban endtime had been reached, but the peer does still show up as banned.

Edit: Situation unchanged at 20:46 CET.

### Expected behaviour
Peer disappears from the "Banned peers" list, when ban endtime has been reached.

### Actual behaviour
Peer does not disappear from the "Banned peers" list, allthough ban endtime has been reached and exceeded.

### Screenshots.
![bildschirmfoto](https://user-images.githubusercontent.com/8447873/32416947-f2e0129a-c251-11e7-9c92-528f0ff3ae5d.png)

### What version of bitcoin-core are you using?
0.15.0.1 / 0.15.1rc1

### Machine specs:
Linux amd64

**Comment by wodry** [comment] 2017-11-05 21:19
If it should be technically possible, I would suggest to add the endtime of the ban to the according debug.log ban message, e.g.

`YYYY-MM-DD HH:MM:SS Misbehaving: 1.2.3.4:12345 peer=1234 (0 -> 100) BAN THRESHOLD EXCEEDED. Peer banned until YYYY-MM-DD HH:MM:SS`

**Comment by jonasschnelli** [comment] 2017-11-06 02:25
`CConnman::DumpData()` is called every 15 mins which is the only call that can sweep (clean) the ban-list (expect of an active ban/unban).
But your offset looks like you have a delta of 28 minutes.... 
The problem is that the periodic sweep call does not update the UI.
Your peer was probably unbanned already (the UI was not up to date).
Working on a fix...

**Comment by TheBlueMatt** [comment] 2017-11-06 02:27
Does #11457 change the behavior here? (@theuni).

**Comment by jonasschnelli** [comment] 2017-11-06 02:34
I don't think it's fixed in #11457 because the missing signal call in SweepBanned() is also missing there...

**Comment by wodry** [comment] 2017-11-06 04:43
I can confirm, that while both peers still show up as banned as the screenshot shows, the output of the rpc call `listbanned` is `[]`, so I guess there is actually no banned peer.

> Your peer was probably unbanned already (the UI was not up to date).

BTW what about logging a ban release in the debug.log? Like `Peer x released from ban.` I did not find a message like this for the formerly banned IP, only the ban itself ("Threshold exceeded") and then some  lines `connection from <banned IP:port> dropped (banned)`.

**Comment by theuni** [comment] 2017-11-07 19:02
Yes, I don't think #11457 changes this behavior (it's intended to not change any behavior, really).

@wodry SweepBanned() does log something like that, so you should be able to see this once the bug is fixed.

**Comment by Victorsueca** [comment] 2017-11-09 10:42
This has happened to me too, the listbanned RPC shows an empty list, which suggest that the issue is within the GUI. Restarting bitcoin core or using Right click > Unban on any node on the GUI seem to refresh the list and fix it.

**Closed** 2017-12-15 09:44 UTC
Labels: P2P
