### ISSUE TITLE
Error: specified data directory "\\IP.Ad.re.ss\release\Folder"does not exist

### ISSUE THREAD

**Issue by card0384** [bitcoin/bitcoin#25868] opened 2022-08-18 19:33 UTC
I have the entire Bitcoin installation on a storage share. From \\IP.Ad.re.ss\release\Folder\bitcoin-qt.exe i have a shortcut on my Desktop to start it and in registry HKEY_CURRENT_USER\Software\Bitcoin\Bitcoin-Qt\strDataDir is  \\IP.Ad.re.ss\release\Folder. This has worked well for several years. The last working version for me was bitcoin-0.21.1-win64. I have now updated to version bitcoin-23.0-win64. 
At startup, the error comes from the title. After copying back version bitcoin-0.21.1-win64 it works again immediately.
I use Windows 11 22H2 - including all updates with Core I3 8100T and 10GB RAM.

the release is on a QNAP. The release itself works because the bitcoin-qt.exe is also started by the same.
I am using bitcoin-core from bitcoin-23.0-win64.zip website

debug.log writes nothing to its error - only the dialog box on start bitcoin-qt in version 23.0 win64

Many Thanks for fixing it.
card0384

**Comment by fanquake** [comment] 2022-09-02 10:15
@sipsorcery any thoughts here?

**Comment by hebasto** [comment] 2022-09-02 11:20
Looks like the issue is related to Windows native format implementation of [`QSettings`](https://doc.qt.io/qt-5/qsettings.html)...

**Comment by card0384** [comment] 2022-09-02 11:33
Unfortunately I can't do anything with it - I use the ready-made bitcoin-qt.exe and it always ran without problems.

**Comment by sipsorcery** [comment] 2022-09-02 18:28
@card0384 maybe it'd be worth mapping a network drive to your Qnap and using that instead of the UNC path? That might make Qt happier.

**Comment by card0384** [comment] 2022-09-21 12:12
Thank you very much for the tip, could you please restore the functionality in the next releases so that bitcoin.exe can be started directly from the network drive again? Many Thanks

**Comment by willcl-ark** [comment] 2024-04-10 15:21
@ryanofsky are you working on this?

**Comment by willcl-ark** [comment] 2024-10-14 15:56
Closing this as it has not had any activity in a while. If you are interested in continuing discussion on this, or you feel that it is sufficiently important, please leave a comment so that it can be reopened.

**Closed by willcl-ark** 2024-10-14 15:56 UTC
Labels: Bug, Windows

**Comment by ryanofsky** [comment] 2024-10-16 09:43
re: https://github.com/bitcoin/bitcoin/issues/25868#issuecomment-1235378136

> Looks like the issue is related to Windows native format implementation of [`QSettings`](https://doc.qt.io/qt-5/qsettings.html)...

@hebasto do you remember what this comment is referring to? I don't see how the qsettings implementation would affect this, since the setting seems like it is read successfully.

re: https://github.com/bitcoin/bitcoin/issues/25868#issuecomment-1476482356

> I wonder if this is related to #27246 and fixed by #27273 ?

I think this problem is probably not related to those issues, because the error message 'Error: specified data directory "\\IP.Ad.re.ss\release\Folder"does not exist'" indicates Bitcoin is checking the right folder, so must be reading the setting, but for some reason it is not finding the folder. In current code and in 0.21 this error is triggered when the `CheckDataDirOption` function fails, which in 0.21 was checking `fs::is_directory(fs::system_complete(datadir))` and in current code is checking `fs::is_directory(fs::absolute(datadir))`. These really should be equivalent, so it is unclear what causes the bug.

The described behavior does sound like a bug if it is still happening.
