### ISSUE TITLE
Intermittent CI failure: p2p_compactblocks.py - wait_until() failed

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#21963] opened 2021-05-16 18:06 UTC
Intermittent CI failure in `p2p_compactblocks.py`:

```
 test  2021-05-15T12:59:56.247000Z TestFramework.p2p (DEBUG): Received message from 127.0.0.1:16352: msg_ping(nonce=7cb20024846796fe) 
 test  2021-05-15T12:59:56.247000Z TestFramework.p2p (DEBUG): Send message to 127.0.0.1:16352: msg_pong(nonce=7cb20024846796fe) 
 node0 2021-05-15T12:59:56.249511Z [msghand] [net_processing.cpp:2339] [ProcessMessage] received: pong (8 bytes) peer=0 
 node0 2021-05-15T12:59:56.249898Z [msghand] [net_processing.cpp:2339] [ProcessMessage] received: pong (8 bytes) peer=1 
 test  2021-05-15T12:59:56.351000Z TestFramework.p2p (DEBUG): Received message from 127.0.0.1:16352: msg_ping(nonce=7a8ccde9e7d59f55) 
 test  2021-05-15T12:59:56.351000Z TestFramework.p2p (DEBUG): Send message to 127.0.0.1:16352: msg_pong(nonce=7a8ccde9e7d59f55) 
 node0 2021-05-15T12:59:56.351164Z [msghand] [net.cpp:2968] [PushMessage] sending ping (8 bytes) peer=2 
 node0 2021-05-15T12:59:56.359345Z [msghand] [net_processing.cpp:2339] [ProcessMessage] received: pong (8 bytes) peer=2 
 node0 2021-05-15T12:59:56.765182Z [scheduler] [random.cpp:523] [SeedPeriodic] Feeding 32769 bytes of dynamic environment data into RNG 
 node0 2021-05-15T13:00:56.928013Z [scheduler] [random.cpp:523] [SeedPeriodic] Feeding 32774 bytes of dynamic environment data into RNG 
 test  2021-05-15T13:01:09.354000Z TestFramework.utils (ERROR): wait_until() failed. Predicate: '''' 
                                           def test_function():
                                               if check_connected:
                                                   assert self.is_connected
                                               return test_function_in()
                                   '''
 test  2021-05-15T13:01:09.366000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 128, in main
                                       self.run_test()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/p2p_compactblocks.py", line 844, in run_test
                                       self.test_end_to_end_block_relay([self.segwit_node, self.old_node])
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/p2p_compactblocks.py", line 675, in test_end_to_end_block_relay
                                       l.wait_until(lambda: "cmpctblock" in l.last_message, timeout=30)
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/p2p.py", line 450, in wait_until
                                       wait_until_helper(test_function, timeout=timeout, lock=p2p_lock, timeout_factor=self.timeout_factor)
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 261, in wait_until_helper
                                       raise AssertionError("Predicate {} not true after {} seconds".format(predicate_source, timeout))
                                   AssertionError: Predicate ''''
                                           def test_function():
                                               if check_connected:
                                                   assert self.is_connected
                                               return test_function_in()
                                   ''' not true after 1200.0 seconds
…
p2p_compactblocks.py                               | ✖ Failed  | 1278 s
```

See Cirrus CI log for details: https://cirrus-ci.com/task/4959275735842816

**Comment by fanquake** [comment] 2021-05-17 00:35
Looks like a duplicate of #21535.

**Closed by fanquake** 2021-05-17 00:35 UTC
Labels: Bug
