### ISSUE TITLE
Oversize transaction: Coin selection ignoring large unspent, coalescing small unspents

### ISSUE THREAD

**Issue by jbreher** [bitcoin/bitcoin#3631] opened 2014-02-05 17:53 UTC
Through discussion on forum, I am led to believe that QT should should endeavor to use unspent outputs large enough to keep transaction below threshold that would incur additional transaction fee. This does not seem to be working for me. Please see

https://bitcointalk.org/index.php?topic=449385.msg4946463#msg4946463

for evidence of large unspent, able to cover entire transaciton, and

https://blockchain.info/tx/966b82abb713551355342c6764db56b57e28cb8eafbb823de530f2fc9b306d74?show_adv=true

for how the transaction was made up of seven small unspents instead.

Bitcoin-QT v0.8.6-beta on OS X 10.7.5

**Comment by laanwj** [comment] 2016-02-16 15:17
Duplicate of "coin selection code does very badly in some cases #1643"

**Closed by laanwj** 2016-02-16 15:17 UTC
Labels: Bug, Wallet
