### ISSUE TITLE
[POC] [RFC] build: Separate GUI application build system

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#24911] opened 2022-04-18 19:06 UTC
There is an inherent contradiction between (a) Bitcoin Core build system and (b) Bitcoin Core GUI build system.

Bitcoin Core:
- strives to minimize dependencies for security reasons
- adds new features without introducing new build dependencies (as usual)

Bitcoin Core GUI:
- new features (e.g., QR-code reader, QML-based UI, OpenGL support, Wayland support) usually do introduce new build dependencies

---

A concept of the separated GUI build system is here: https://github.com/hebasto/bitcoin-qtw/commits/220418-add-core-subtree

One could test it as follows:
```sh
$ ./autogen.sh
$ ./configure --disable-fuzz-binary --disable-tests --disable-bench --without-utils --without-daemon --without-libs
$ make
$ ./src/qt/bitcoin-qt
```

The suggested approach uses this repository as a _subtree_.

Pros:
- ability to drop GUI-related stuff from this repo
- ability to use alternative build system for the current Qt Widget based GUI (e.g., use CMake which allows to adopt Qt6 more seamless, even without upstream support of `*.pc` files)
- ability to develop alternative UI frameworks (e.g., Qt Quick based GUI; fwiw, keeping [QML GUI project](https://github.com/bitcoin-core/gui-qml) synchronized to this repo preserving commit history goes out of hands due to the shared build system)

Cons:
- a GUI repo becomes a completely separated one, not like current https://github.com/bitcoin-core/gui
- the release process requires to be modified to handle GUI binaries from a separated repo

**Comment by JeremyRubin** [comment] 2022-04-18 19:12
concept ack

**Comment by Angel04ek** [comment] 2022-04-19 03:58
Я 5ерозумы¾ю

**Comment by jarolrod** [comment] 2022-04-19 06:26
This is less of "separate GUI application build system" and more of "seperate the gui into a new source tree"

Nevertheless, concept ack dependent on documented release process changes that keeps accessibility to the GUI as it is now (especially when grabbing the dmg or exe from bitcoincore.org); a part of bitcoin core.                                               

otherwise, concept nack. bitcoin core packages together in a coherent package the tools one needs to participate as a node in the network as well as 'store' bitcoin. The GUI plays a big role in both, especially with non-devs.

See: https://github.com/bitcoin/bitcoin/pull/19071

> When a user downloads Bitcoin Core from our website (or another package manager) they expect the GUI to be included. This should not change (at least not as a result of splitting up the GUI into another project).
>
> Similarly, when building Bitcoin Core, the gui should still be built when --with-gui is specified.

Making a note of the IRC discussion that accompanied moving the gui into a monotree repo: https://www.erisian.com.au/bitcoin-core-dev/log-2020-05-28.html#l-406

The discussion includes little nuggets like this:
> 2020-05-28T19:47:22  MarcoFalke: the gui made me contribute to Core

**Comment by w0xlt** [comment] 2022-04-20 07:00
Concept ACK. I think it makes the concepts more organized.
The `bitcoin/bitcoin` project does the same with `bitcoin-core/secp256k1`.

**Comment by sipa** [comment] 2022-04-20 14:37
I believe that separating projects into separate repositories is only a good idea if there is a well-defined stable interface between them. Otherwise, you run into difficulties whenever changes to the boundary between the two need to be made, like lockstep commits and the synchronization overhead between the two projects - exactly what separating them likely was intended to avoid.

I don't know to what extent that is the case with the GUI at this point, however.

**Comment by ryanofsky** [comment] 2022-04-20 15:11
I can't figure out what is being proposed. What are the steps that will be taken? Description seems vague and https://github.com/hebasto/bitcoin-qtw/commits/220418-add-core-subtree just seems to show file renames

**Comment by hebasto** [comment] 2022-04-20 15:15
> I can't figure out what is being proposed. What are the steps that will be taken? Description seems vague and https://github.com/hebasto/bitcoin-qtw/commits/220418-add-core-subtree just seems to show file renames

1. Split `qt` subdir into its own repo --  https://github.com/hebasto/bitcoin-qtw/wiki/1.-Splitting-the-'qt'-subfolder-out-from-the-Bitcoin-Core-repository
2. In a new repo use this one, i.e., `bitcon/bitcoin` as a subtree.

**Comment by MarcoFalke** [comment] 2022-04-20 15:20
I agree with sipa that a separate GUI *build system* is large a separate issue from a separate GUI *repo*.

Instead of proposing both, it might be better to start with listing problems and goals, and then pick the solution that fits best.

**Comment by hebasto** [comment] 2022-04-20 15:28
> it might be better to start with listing problems and goals, and then pick the solution that fits best.

Repeating [myself](https://github.com/bitcoin/bitcoin/issues/24911#issue-1207349974):

> Bitcoin Core:
> 
>    * strives to minimize dependencies for security reasons
> 
>    * adds new features without introducing new build dependencies (as usual)
> 
> 
> Bitcoin Core GUI:
> 
>    * new features (e.g., QR-code reader, QML-based UI, OpenGL support, Wayland support) usually do introduce new build dependencies

The main problem -- What is a wide accepted by developers in this repo way to introduce new GUI-specific features which usually require new build dependencies?

**Comment by ryanofsky** [comment] 2022-04-20 15:31
Thanks for the more detailed description! (https://github.com/bitcoin/bitcoin/issues/24911#issuecomment-1104053117).

Concept ~0 for me, since I don't work very heavily with the build system, and I think people who do work more on build issues are in a better position to decide what their preferences are.

I do now understand why this issue is proposing separating the build system and repositories both at the same time. With the changes you described to the build system which make make bitcoin-qt build depend on the bitcoind build, it would make no sense to keep dead bitcoin-qt stuff inside the bitcoind repository.

**Comment by MarcoFalke** [comment] 2022-04-20 15:49
It looks like this thread might be a response to https://github.com/bitcoin/bitcoin/pull/22708#issuecomment-1100861599 ?

If yes, I don't think introducing a new build system or moving stuff from this repo into another repo is a solution. After all we still need to have the code in this repo to run the guix build and produce the gui binaries, so it seems easiest to put whatever needs to be done inside this repo.

I think the design goals of Bitcoin Core should also (on a best effort basis) be applied to the GUI. So if you want to introduce a new GUI feature and it seems useful, it should be added here. If it doesn't seem useful, it probably shouldn't be added, neither here or in a separate repo or separate build system.

**Comment by fanquake** [comment] 2022-08-12 11:19
> The main problem -- What is a widely accepted by developers in this repo way to introduce new GUI-specific features which usually require new build dependencies?
> There is an inherent contradiction between (a) Bitcoin Core build system and (b) Bitcoin Core GUI build system.

I don't think there is a widely accepted way, because adding new features to the GUI is a rarity, and, as you've outlined in the op, what you want to do is at odds with our thesis of minimizing dependencies/third party code, and ultimately, the number of (unrelated to bitcoin) concerns we have to deal with in this repository.

As I outlined in this comment, https://github.com/bitcoin/bitcoin/pull/22708#issuecomment-1100861599, without any coherent GUI plan, I'm not sure what to do. However I'm pretty certain the answer isn't to keep adding new dependencies and support for more features (to the GUI).

I agree with Marcos comments here: https://github.com/bitcoin/bitcoin/issues/24911#issuecomment-1104091542, shifting things to a new repo doesn't really solve anything as long as this project is still building and releasing these binaries to end users.

**Comment by fanquake** [comment] 2023-02-24 11:05
Closing for now, as I don't think there is anything actionable here. We aren't going to add new dependencies any time soon, if ever, and we aren't going to shuffle code/directories around (the linked branch) in this repository to facilitate easier rebasing in an experimental gui-fork.

**Closed by fanquake** 2023-02-24 11:05 UTC
Labels: Brainstorming, GUI, Build system
