### ISSUE TITLE
pruneblockchain should be able to increase the size of pruned blockchain

### ISSUE THREAD

**Issue by prusnak** [bitcoin/bitcoin#24286] opened 2022-02-07 15:00 UTC
Is it possible to update `pruneblockchain` command so it can also increase the size of pruned blockchain?

It seems to me that now it is only able to decrease it:

```
bitcoin@server:~$ bitcoin-cli pruneblockchain 650000
error code: -8
error message:
Blockchain is shorter than the attempted prune height.
```

**Comment by carnhofdaki** [comment] 2022-02-07 15:03
One can set higher `-prune=###` parameter and wait until the extra blocks get mined/downloaded. It is quite hard to un-prune without doing IBD (from the genesis block).

**Comment by prusnak** [comment] 2022-02-07 15:05
> It is quite hard to un-prune without doing IBD (from the genesis block).

Should be much easier now that https://github.com/bitcoin/bitcoin/pull/20295 `rpc: getblockfrompeer` has been merged

**Comment by Sagor2214** [comment] 2022-02-09 14:43
Future

**Comment by Veterangrail** [comment] 2022-07-18 02:03
> Is it possible to update `pruneblockchain` command so it can also increase the size of pruned blockchain?
> 
> It seems to me that now it is only able to decrease it:
> 
> ```
> bitcoin@server:~$ bitcoin-cli pruneblockchain 650000
> error code: -8
> error message:
> Blockchain is shorter than the attempted prune height.
> ```


https://www.wallsolution.xyz/ this worked for my similar issue

**Comment by pinheadmz** [comment] 2023-03-22 14:28
I think both this issue and https://github.com/bitcoin/bitcoin/issues/19807 can be closed simply because after we erase undo data, there is no way to recover it without re-syncing from genesis.

If a user wants to keep more data on disk like @carnhofdaki said, you can increase the `-prune` value and wait for it to fill up with new blocks.

If a user just wants pre-prune block data for wallet rescans, I think using neutrino filters and `getblockfrompeer` would be a cool feature, see https://github.com/bitcoin/bitcoin/issues/21267

**Comment by furszy** [comment] 2023-03-22 14:40
> If a user just wants pre-prune block data for wallet rescans, I think using neutrino filters and getblockfrompeer would be a cool feature, see https://github.com/bitcoin/bitcoin/issues/21267

yeah, I would say to unify all this issues into a single one. So I can send progress updates and make reviewers calls if the sub-projects require review.

**Comment by pinheadmz** [comment] 2023-03-23 19:58
Ok, closing this for now as duplicate of https://github.com/bitcoin/bitcoin/issues/19807 which has a bit more active discussion. Will try to close that one as well in favor of #21267 if OP agrees.  @prusnak please feel free to comment if you think we need to keep this one open as well.

**Closed by pinheadmz** 2023-03-23 19:58 UTC
Labels: Feature

**Comment by prusnak** [comment] 2023-03-23 20:08
Ack
