### ISSUE TITLE
Policy: Reduce Default Max Mempool Size to 50 MB

### ISSUE THREAD

**Issue by DesWurstes** [bitcoin/bitcoin#20990] opened 2021-01-22 20:40 UTC
Hello, I would like to start a discussion about this snippet:

https://github.com/bitcoin/bitcoin/blob/4a540683ec40393d6369da1a9e02e45614db936d/src/policy/policy.h#L31-L32

Note that the limit of 300 MB was probably added as a DoS protection. I wish that this limit were reduced as explained below:

Not every wallet supports RBF and it is very easy to make a transaction with a too-low fee. The problem is, after 14 days, the transaction is not dropped. Someone constantly republishes all low-fee transactions to an extent that you may forget about the 14-day limit. Other than CPFP, there is nothing to do in this case, but to wait until the mempool is cleared.

What I suggest doing is, not letting transactions who can't make it into a block in 2 weeks to be dropped. 50 MB seems reasonable to me (Because most likely a transaction in the 51st MB won't be confirmed soon)

My arguments:
- Mempool is a temporary place for transactions waiting to be included in a block. If we don't expect them to be in a block soon, they don't belong to Mempool.
- If a transaction has a fee rate that is lower than the first 50 MB's, it is more beneficial for the user to be able to replace it with a better transaction and relay the newer one.
- It is too easy to abuse and bypass the 14-day limit by re-pushing transactions, and transaction acceleration services directly profit from this. Hence the low-fee transactions are stuck until they're confirmed (unless CPFP)
- It's unlikely that low fee transactions are intended to be used in 0-conf payments.
- This doesn't affect mining pools' profits: They can set `-maxmempool=3000` and if a newer transaction with a higher fee is not published, they could still mine the low-fee transaction. In fact, this would increase their profits since the average fee rate would increase with this.

So, this is about standardness of being able to update a hopeless transaction.

Any thoughts? Waiting for 300 MB before starting to drop transactions is ridiculous. And if your transaction is in the 299th (or 99th) MB, that's worse than having set an even lower fee. We need to remove the merit of *transactions that reach the 300MB limit*.

**Comment by MarcoFalke** [comment] 2021-01-23 05:53
> 50 MB seems reasonable to me (Because most likely a transaction in the 51st MB won't be confirmed soon)

The mempool has an overhead (maybe 2x), so this will be less than 25 blocks (~250 minutes) worth of txs.

> This doesn't affect mining pools' profits

It does. If the whole network has a limit of 50MB and a wallet has no direct connection to a mining pool, there is no way to send a tx that would be accepted by a 3000MB mempool.

**Comment by decryp2kanon** [comment] 2021-01-23 06:32
NACK, 50mb is too low IMHO

**Comment by DesWurstes** [comment] 2021-01-23 08:41
OK, how about 100 MB?

> > This doesn't affect mining pools' profits
>
> If the whole network has a limit of 50MB and a wallet has no direct connection to a mining pool, there is no way to send a tx that would be accepted by a 3000MB mempool.

The scenario is this: The 50 MB mempool is not full, the user publishes a transaction, the tx is kicked out of the mempool, then the miner can still keep that tx in their mempool, or replace it with a higher fee one if a newer one is broadcast.

**Comment by prusnak** [comment] 2021-01-23 11:58
> It is too easy to abuse and bypass the 14-day limit by re-pushing transactions

Your proposition does not help to get rid of the cause of the problem.

**Comment by DesWurstes** [comment] 2021-01-23 12:46
@prusnak It does, against a permanent stay in the mempool, if we rather not accept the tx to the mempool, we would be giving the user a second chance to transaction with a higher fee.

Adding an `nSequence` bit with the meaning of "if the lock time has passed long since, the transaction shouldn't be considered standard and not relayed" would also equally work. Would you prefer this proposal?

**Comment by ViralTaco** [comment] 2021-01-29 05:29
It's reasonably sized. It can accommodate high inflows of transactions. 
The idea is still very much to mine a block on average every 10 minutes. 
That hasn't changed. The number of daily transactions isn't exactly at an all time low. 
I agree that the fee structure is aging. I disagree that the solution would be to reject transactions. 
If anything that would be an incentive for miners to only pick up transactions with very high fees. 
The difficulty mechanism was always assuming a somewhat natural growth of hash power.
We reached the point where the processing power is wasted because no better system has been engineered. 

It's not an easy problem to solve. I'd like to help with it but I won't ever do it alone and the echo I've had from core devs seems to be "if it ain't broke don't fix it" (ironically the same reason why banks still use IBM mainframes). 
I digress. I think it's a bad idea, the limit would be hit nearly every day.

**Comment by benthecarman** [comment] 2021-01-29 10:44
NACK

**Comment by MarcoFalke** [comment] 2021-01-29 10:48
Closing for now due to controversy

**Closed by MarcoFalke** 2021-01-29 10:48 UTC
