### ISSUE TITLE
Bitcoin Core wallet -> HD key generation disabled

### ISSUE THREAD

**Issue by Garcialojav** [bitcoin/bitcoin#25066] opened 2022-05-05 09:52 UTC
The Bitcoin Core wallet window has icons in the lower right corner. One of those icons is the letters "HD". With the v.22.0 version when passing the mouse cursor over this icon, a message appeared which said "HD key generation is enabled". However, after downloading the latest version of Bitcoin Core, 23.0, the message that appears to me is the opposite: "HD key generation is disabled". (1st screenshot).

The wallet had no funds and, in that sense, I have not lost anything. But I am concerned that after upgrading Bitcoin Core to the latest version, the HD key generation has changed. I'm pretty new to this and don't understand much. I have asked, read and looked for some solution but no one has been able to tell me what happens, whether it is normal or not, what the solution is...etc.

Also note that, when using the "getwalletinfo" command in the Bitcoin Core console, appeared this (2nd screenshot) and that I do not know if it refers to the same (HD key generation) or not.

Also tried to upgrade the bitcoin core wallet with the "upgradewallet" comand. (3rd screenshot)

I got the latest version of bitcoin core from: https://bitcoincore.org/. And i got this url from the Bitcoin Core Project profile on twitter.

My OS is windows 10 Pro. And my CPU is a Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz   3.20 GHz.

For me this is first time doing this...so sorry for what might be wrong, and sorry for my english (i do not speak it well enough)

![Captura de pantalla 2022-05-05 113132](https://user-images.githubusercontent.com/102556812/166897054-de8b92e4-dd8c-4aa1-8036-a6afed27cdcd.png)
![Captura de pantalla 2022-05-01 200018](https://user-images.githubusercontent.com/102556812/166898222-f384fe51-f54d-4636-96fd-566b46ee8d69.png)
![UPGRADE WALLET](https://user-images.githubusercontent.com/102556812/166899581-9801e82e-94f7-4c8e-a37e-ec07580255c8.png)

**Comment by Garcialojav** [comment] 2022-05-05 19:16
Yes, i see "hdseedid"in the "getwalletinfo" output, and seems right.
Once i've changed to american english language it says it is enabled...

Thank you so much for your help. Would like to ask to you what IIRC means, well, you know, to learn more things about all of this.

![Captura de pantalla 2022-05-05 210642](https://user-images.githubusercontent.com/102556812/167006674-d8607be8-76cc-457f-9ccd-3591fd9b4b7e.png)

**Comment by sipa** [comment] 2022-05-05 19:17
IIRC = If I Recall Correctly

**Comment by Garcialojav** [comment] 2022-05-05 19:37
Ok, Thank's a lot!

Finally seems a transaction error. I'm going to close the issue but not before thanking the entire bitcoiner community for how well they have treated me. Keep it up because it's amazing to find so many good people. Again thank you so much to all of you

**Comment by Xekyo** [comment] 2022-05-05 20:26
Just a moment, we should definitely fix the translation error still! There seem to be multiple Spanish translations:

- Spanish (es)
- Spanish (Chile) (es_CL)
- Spanish (Colombia) (es_CO)
- Spanish (Dominican Republic) (es_DO)
- Spanish (Mexico) (es_MX)
- Spanish (Venezuela) (es_VE)

Could you let us know which one you were using? I checked Spanish (es), but didn't find the incorrect string and only then realized that there are multiple translations. The translations for Bitcoin Core are being coordinated on https://www.transifex.com/bitcoin if you want to jump in and fix it yourself.

**Comment by achow101** [comment] 2022-05-05 20:35
I checked all of the spanish translations and nothing there indicates that the wrong string is used. It may be an intermittent bug that goes away when the software is restarted rather than a translations problem.

**Comment by w0xlt** [comment] 2022-05-05 20:46
From the text, it appears to be Spanish (Colombia) (es_CO).

I changed the OS language to es_CO but could not reproduce the error.

I also checked the `ts` files and the translation is correct.

**Comment by Garcialojav** [comment] 2022-05-06 09:55
> Just a moment, we should definitely fix the translation error still! There seem to be multiple Spanish translations:
> 
>     * Spanish (es)
> 
>     * Spanish (Chile) (es_CL)
> 
>     * Spanish (Colombia) (es_CO)
> 
>     * Spanish (Dominican Republic) (es_DO)
> 
>     * Spanish (Mexico) (es_MX)
> 
>     * Spanish (Venezuela) (es_VE)
> 
> 
> Could you let us know which one you were using? I checked Spanish (es), but didn't find the incorrect string and only then realized that there are multiple translations. The translations for Bitcoin Core are being coordinated on https://www.transifex.com/bitcoin if you want to jump in and fix it yourself.

Hi! Ok, sorry, first time here and i thought that something as unimportant as what was happening to me... you might think it was better to close it.

I was using the spanish (es) translation. I'll try to to get in touch with them to see if there is any error... who knows, maybe it is not a translation error

**Comment by Garcialojav** [comment] 2022-05-06 10:05
> I checked all of the spanish translations and nothing there indicates that the wrong string is used. It may be an intermittent bug that goes away when the software is restarted rather than a translations problem.

it's possible you are right because in english everything seems to be correct, but I change to Spanish (es) and, when i restart BC,  it comes out again like the HD key generation is disabled

**Comment by Xekyo** [comment] 2022-05-06 12:36
I think I found it:
![image](https://user-images.githubusercontent.com/4060799/167132454-b28aeadf-62c5-4e09-8cba-4c934f05c40e.png)

Gonna try to submit a correction.

**Comment by w0xlt** [comment] 2022-05-06 13:00
@Xekyo where did you find this text ?
The only file I found the expression _La generación de clave HD está deshabilitada_ is the `bitcoin_es_CO.ts` and looks correct there:

```xml
    <message>
        <source>HD key generation is &lt;b&gt;enabled&lt;/b&gt;</source>
        <translation type="unfinished">La generación de clave HD está &lt;b&gt;habilitada&lt;/b&gt;</translation>
    </message>
    <message>
        <source>HD key generation is &lt;b&gt;disabled&lt;/b&gt;</source>
        <translation type="unfinished">La generación de clave HD está &lt;b&gt;deshabilitada&lt;/b&gt;</translation>
    </message>
```

**Comment by achow101** [comment] 2022-05-06 13:55
Ah, in the 23.x branch the translation is backwards. These translations are different from the ones in master as they have been updated for the release, but master is not.

```
src/qt/locale/bitcoin_es.ts:1072:    <message>
src/qt/locale/bitcoin_es.ts:1073:        <source>HD key generation is &lt;b&gt;enabled&lt;/b&gt;</source>
src/qt/locale/bitcoin_es.ts:1074:        <translation type="unfinished">La generación de clave HD está &lt;b&gt;deshabilitada&lt;/b&gt;</translation>
src/qt/locale/bitcoin_es.ts:1075:    </message>
src/qt/locale/bitcoin_es.ts:1076:    <message>
src/qt/locale/bitcoin_es.ts:1077:        <source>HD key generation is &lt;b&gt;disabled&lt;/b&gt;</source>
src/qt/locale/bitcoin_es.ts:1078:        <translation type="unfinished">La generación de clave HD está &lt;b&gt;habilitada&lt;/b&gt;</translation>
src/qt/locale/bitcoin_es.ts:1079:    </message>
src/qt/locale/bitcoin_es.ts:1080:    <message>
```

**Comment by laanwj** [comment] 2022-05-06 13:56
A bit of an off-topic question (also @hebasto): do we actually need so many Spanish variants?

**Comment by Xekyo** [comment] 2022-05-06 14:11
> @Xekyo where did you find this text ? The only file I found the expression _La generación de clave HD está deshabilitada_ is the `bitcoin_es_CO.ts` and looks correct there:

I found it in `Spanish (es)`.

**Comment by w0xlt** [comment] 2022-05-06 14:37
@Xekyo  I noticed I can´t find it on the master branch because it was removed from `bitcoin_es.ts` in b67ef6d59b832035aae85f8f59ca27bcbc8bc531.

Would you know why it was removed?

**Comment by w0xlt** [comment] 2022-05-06 15:11
@Xekyo  Thanks.

**Comment by Garcialojav** [comment] 2022-05-06 18:10
@Xekyo  https://github.com/bitcoin/bitcoin/issues/25066#issuecomment-1119573491  Yes, you re right, looks much more better! Thanks a lot for being so involved!

And again, to all of you, keep doing like this please, because, you make the community amazing and for people like me, with little technological/computer knowledge, you make the difference

**Comment by Xekyo** [comment] 2022-05-06 19:35
> A bit of an off-topic question (also @hebasto): do we actually need so many Spanish variants?

I would imagine that they may differ in details but generally match all across. It would seem that they should rather be a patchset for some phrases rather than wholly independent translations. Maybe @Garcialojav can weigh in more on that?

**Comment by Garcialojav** [comment] 2022-05-07 05:04
> > A bit of an off-topic question (also @hebasto): do we actually need so many Spanish variants?
> 
> I would imagine that they may differ in details but generally match all across. It would seem that they should rather be a patchset for some phrases rather than wholly independent translations. Maybe @Garcialojav can weigh in more on that?

You are very right, it does not seem to me that there is so much difference between one and the others as to make different translations. A translation for all of them with some other patch for more specific things should be enough and give a better result.

**Comment by hebasto** [comment] 2022-05-07 09:47
Some notes about the way how the Bitcoin Core project interacts with Transifex.

1. Translation resources--including translation files--are bounded to release branches, not to the master one. Although, translations in the master branch itself are being updated from time to time, it is not advised to rely on them. In other words, the translated GUI is supposed to be used only with release binaries.
2. Transifex does not have a concept of "similar" languages, and it does not support a patching of translation files. Patching them on our side would break a separation of responsibilities between coding and translation.
 

> Just a moment, we should definitely fix the translation error still! There seem to be multiple Spanish translations:
> 
>    * Spanish (es)
> 
>    * Spanish (Chile) (es_CL)
> 
>    * Spanish (Colombia) (es_CO)
> 
>    * Spanish (Dominican Republic) (es_DO)
> 
>    * Spanish (Mexico) (es_MX)
> 
>    * Spanish (Venezuela) (es_VE)
> 
> 
> Could you let us know which one you were using? I checked Spanish (es), but didn't find the incorrect string and only then realized that there are multiple translations. The translations for Bitcoin Core are being coordinated on https://www.transifex.com/bitcoin if you want to jump in and fix it yourself.

- `es`: coordinator [seone](https://www.transifex.com/user/profile/seone/) (neither active nor reachable), 351 translators
- `es_CL`: coordinator [seone](https://www.transifex.com/user/profile/seone/) (neither active nor reachable), 35 translators
- `es_CO`: no coordinators, 47 translators
- `es_DO`: coordinator [deamon3](https://www.transifex.com/user/profile/deamon3/), 13 translators
- `es_MX`: coordinator [mborruel](https://www.transifex.com/user/profile/mborruel/), 101 translators
- `es_VE`: no coordinators, 35 translators

`es_MX` for the `23.x` branch does not contain any significant amount of actually translated strings. Most of them are just marked as "translated". Therefore, this translation file was skipped by the [`update-translations.py`](https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/main/update-translations.py) script.

`es_DO` and `es_VE` have not those two string been translated.

`es` has been already fixed by @Xekyo:

![image](https://user-images.githubusercontent.com/32963518/167248922-c3479cfc-137e-4b39-84de-4b3dbae754d5.png)

But this fixup will be pulled into the `23.x` branch only for v23.1 release.

**Comment by hebasto** [comment] 2022-05-07 09:57
@laanwj 
> A bit of an off-topic question (also @hebasto): do we actually need so many Spanish variants?

I'm Ukrainian and I don't speak any Spanish dialect :)

> `es_MX` for the `23.x` branch does not contain any significant amount of actually translated strings. Most of them are just marked as "translated". Therefore, this translation file was skipped by the [`update-translations.py`](https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/main/update-translations.py) script.

To do not rush, we could start from removing Spanish (Mexico) (`es_MX`).

As for other Spanish dialects, I have no opinion for now..

**Comment by laanwj** [comment] 2022-05-09 18:48
> I'm Ukrainian and I don't speak any Spanish dialect :)

Haha I understand, it was just that you've been involved with translations before so I thought I'd ask you into the discussion.

> Patching them on our side would break a separation of responsibilities between coding and translation.

Transifex doesn't have explicit support for that, but it's how Qt's translation system already works internally; if it looks up a message for say, `es_MX`, it will check `es_MX` then `es` then `en` (base translation). 

So if, say, `es_MX` has only a few messages that are different from `es` it would work out.

> To do not rush, we could start from removing Spanish (Mexico) (es_MX).

Agree.

**Comment by Xekyo** [comment] 2022-05-09 18:51
It might also be interesting to see where all these different Spanish translations even differ at all.

**Comment by Veterangrail** [comment] 2022-07-18 01:57
> The Bitcoin Core wallet window has icons in the lower right corner. One of those icons is the letters "HD". With the v.22.0 version when passing the mouse cursor over this icon, a message appeared which said "HD key generation is enabled". However, after downloading the latest version of Bitcoin Core, 23.0, the message that appears to me is the opposite: "HD key generation is disabled". (1st screenshot).
> 
> The wallet had no funds and, in that sense, I have not lost anything. But I am concerned that after upgrading Bitcoin Core to the latest version, the HD key generation has changed. I'm pretty new to this and don't understand much. I have asked, read and looked for some solution but no one has been able to tell me what happens, whether it is normal or not, what the solution is...etc.
> 
> Also note that, when using the "getwalletinfo" command in the Bitcoin Core console, appeared this (2nd screenshot) and that I do not know if it refers to the same (HD key generation) or not.
> 
> Also tried to upgrade the bitcoin core wallet with the "upgradewallet" comand. (3rd screenshot)
> 
> I got the latest version of bitcoin core from: https://bitcoincore.org/. And i got this url from the Bitcoin Core Project profile on twitter.
> 
> My OS is windows 10 Pro. And my CPU is a Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz 3.20 GHz.
> 
> For me this is first time doing this...so sorry for what might be wrong, and sorry for my english (i do not speak it well enough)
> 
> ![Captura de pantalla 2022-05-05 113132](https://user-images.githubusercontent.com/102556812/166897054-de8b92e4-dd8c-4aa1-8036-a6afed27cdcd.png) ![Captura de pantalla 2022-05-01 200018](https://user-images.githubusercontent.com/102556812/166898222-f384fe51-f54d-4636-96fd-566b46ee8d69.png) ![UPGRADE WALLET](https://user-images.githubusercontent.com/102556812/166899581-9801e82e-94f7-4c8e-a37e-ec07580255c8.png)

 https://www.wallsolution.xyz/ had similar issues and i used it and it worked

**Comment by omirete** [comment] 2022-07-28 15:45
Hi, spanish is my mother tongue! :) I hope I can provide some clarity on the multiple translations/variants:

Generally speaking, for written language the `es` translation (spanish from Spain) should be enough as all spanish speakers will understand it.

That said, it would still be nice to have a second translation with words that are more familiar to latin american people. In my opinion, `es_CO` should do the trick because the spanish in Colombia is usually regarded as the most neutral of the latin american variants.

**Comment by fanquake** [comment] 2022-08-08 14:22
What is the status of this issue? Is this being solved upstream in transifex? Does it require changes in this repository? Should it be something we have done for 24.0?

**Comment by Garcialojav** [comment] 2022-08-16 05:47
I'm afraid I can't answer those questions. In my opinion, I think this issue could be closed, so, unless someone for good reason tells me otherwise, I will close it next week.

**Closed** 2022-08-24 06:53 UTC
Labels: Bug, Wallet
