### ISSUE TITLE
Peers don't appear to be unbanned automatically

### ISSUE THREAD

**Issue by PRabahy** [bitcoin/bitcoin#7377] opened 2016-01-19 03:49 UTC
I'm running 0.12RC1 and tested banning a peer from the GUI. That worked properly, but after an hour passed the peer is still showing up in the banned list.

![banned](https://cloud.githubusercontent.com/assets/429961/12409176/ab6108a6-be35-11e5-869a-d31eb09fdc3a.PNG)

**Comment by PRabahy** [comment] 2016-01-20 00:19
I restarted my node and the Banned peer had gotten cleared out.

**Comment by jonasschnelli** [comment] 2016-01-20 09:10
Thanks for reporting.
There are cases where banned nodes still are listed in the table together with the correct "banned until" timestamp. I guess this behavior is okay.
IIRC we don't use a watch-thread to save some resources.

**Comment by laanwj** [comment] 2016-01-20 12:42
You don't need a thread, but some kind of notification toward the GUI would be nice.
Very low priority though, as it is working, just a visual issue.

**Comment by jonasschnelli** [comment] 2016-01-20 13:22
The question is, which event should be (miss)used for updating the `banTableModel`. Unbanning a node is not an real-event (because it's caused by time). We could update the list every 10 seconds... but as said, I don't want to waste a timer for this visual glitch.

**Comment by MarcoFalke** [comment] 2020-05-08 18:29
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.

**Closed by MarcoFalke** 2020-05-08 18:29 UTC
Labels: GUI, P2P
