### ISSUE TITLE
Coin selection, CreateTransaction, MAX_STANDARD_TX_SIZE

### ISSUE THREAD

**Issue by dexX7** [bitcoin/bitcoin#5782] opened 2015-02-10 10:35 UTC
While regtesting with [bitcoin-spock](https://github.com/msgilligan/bitcoin-spock) I noticed at some point the transaction creation via `sendtoaddress -> CreateTransaction()` fails, because the created transaction is larger than `MAX_STANDARD_TX_SIZE`.

During the process a lot of raw transactions are created, which have smallish outputs and when then using `sendtoaddress`, it appears to attempt to create a transaction that spends too many of those dust-ish outputs.

The transaction to create does not have many outputs, but it looks like it's caused by the coin selection, which selects too many inputs. Testing was done with a 0.9 branch, but on the first glimpse I believe this issue is as well be present in 0.10. If this is a known issue, and if there is already a guard against this behavior, I'd be happy about a hint.

Sorry in advance, I do not have a test script to reproduce this issue in an isolated manner. A potential fix would probably require to adjust the coin selection, so that it selects a combination of coins, which, in addition to the size of the rest of the transaction, is still smaller than the limit.

**Comment by laanwj** [comment] 2015-02-10 11:01
There have been some modifications to coin selection algorithm, maybe they improve things, see e.g. #4906

**Comment by dexX7** [comment] 2015-02-11 01:18
Thanks for the link! Unfortunally it doesn't seem to be related, but this issue is certainly something that probably won't appear outside of a testing environment. I created a test for it nevertheless:

https://github.com/dexX7/bitcoin/blob/qa-coin-selection-limit/qa/rpc-tests/coinselection_size_limit.py

The problem is that the coin selection doesn't relate to the transaction size at all. I came up with three scenarios, all failing at the moment:

Scenario 1:
 - The actor starts with 1x 50.0 BTC and 1000x 0.05 BTC (100.0 BTC total) unspent outputs
 - Then tries to spend 49.5 BTC
 - The 50.0 BTC output should be selected, because the transaction would otherwise be too large
 
Scenario 2:
 - The actor starts with 500x 0.1 BTC and 1000x 0.05 BTC (100.0 BTC total) unspent outputs
 - Then tries to spend 49.5 BTC
 - A combination of coins should be selected, such that the created transaction is not too large
 
Scenario 3 (available as RPC test):
 - The actor starts with 1x 50.0 BTC, 500x 0.1 BTC and 1000x 0.05 BTC (150.0 BTC total) unspent outputs
 - Then tries to spend 49.5 BTC
 - A combination of coins should be selected, such that the created transaction is not too large

For each scenario at least one solution exists, where a combination of coins results in a transaction that has a size of less than `MAX_STANDARD_TX_SIZE`.

**Comment by MarcoFalke** [comment] 2018-04-29 13:11
Is this a duplicate of  #1643?

**Comment by dexX7** [comment] 2018-04-29 23:25
@MarcoFalke: looks like both issues tackle coin selection, while @dooglus' is about minimizing fees, mine is about making sure the transaction creation doesn't fail to begin with. Though optimizing fees also results in small transactions.

What's on top: there isn't a check during coin selection, whether the transaction is still within MAX_STANDARD_TX_SIZE.

**Closed** 2022-12-06 17:09 UTC
Labels: Wallet
