### ISSUE TITLE
[wallet] Node process hangs after SIGINT

### ISSUE THREAD

**Issue by naumenkogs** [bitcoin/bitcoin#18517] opened 2020-04-03 16:05 UTC
I noticed it while testing current master (f0d6487e290761a4fb03798240a351b5fddfdb38).
The node is in IBD: ``2020-04-03T15:23:06Z Synchronizing blockheaders, height: 69998 (~12.07%)``
And I'm using Ubuntu 16.04.
I will be happy to let someone willing to see it into the VM I'm using and provide instructions to reproduce.

Here's how I compiled it:
``./configure --with-incompatible-bdb PYTHONPATH= --disable-shared --with-pic --enable-benchmark=no --with-bignum=no --enable-module-recovery --disable-jni --disable-shared --with-pic --enable-benchmark=no --with-bignum=no --enable-module-recovery --disable-jni --no-create --no-recursion``

Steps to reproduce (it happens every time I repeat this sequence):
1. src/bitcoind
2. wait til see first message ``New outbound peer connected: version``
3. click Ctrl+ C (afaik this is SIGINT)
4. The process stuck with these logs at the end:
```
2020-04-03T15:23:12Z Synchronizing blockheaders, height: 73998 (~12.73%)
^C2020-04-03T15:23:13Z P2P peers available. Skipped DNS seeding.
2020-04-03T15:23:13Z dnsseed thread exit
2020-04-03T15:23:13Z tor: Thread interrupt
2020-04-03T15:23:13Z Shutdown: In progress...
2020-04-03T15:23:13Z torcontrol thread exit
2020-04-03T15:23:13Z addcon thread exit
2020-04-03T15:23:13Z net thread exit
2020-04-03T15:23:13Z msghand thread exit
2020-04-03T15:23:15Z opencon thread exit
2020-04-03T15:23:15Z scheduler thread exit
2020-04-03T15:23:15Z Dumped mempool: 4e-06s to copy, 0.002802s to dump
2020-04-03T15:23:15Z FlushStateToDisk: write coins cache to disk (0 coins, 0kB) started
2020-04-03T15:23:15Z FlushStateToDisk: write coins cache to disk (0 coins, 0kB) completed (0.00s)
2020-04-03T15:23:15Z FlushStateToDisk: write coins cache to disk (0 coins, 0kB) started
2020-04-03T15:23:15Z FlushStateToDisk: write coins cache to disk (0 coins, 0kB) completed (0.00s)
```
5. Wait for several minutes, nothing happens.
6. Try kill $PID, doesn't do anything
7. Finally, do kill -9 $PID to get rid of the process

So, the process doesn't take much CPU (0.4%), and gdb says it's 2 threads: 
```
  Id   Target Id                                     Frame
* 1    Thread 0x7fd51d48a740 (LWP 31824) "b-shutoff" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  2    Thread 0x7fd507fff700 (LWP 31834) "bitcoind"  pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
```
Backtrace is [here](https://gist.github.com/naumenkogs/ea101c19f4e39f47d8324d3b9046be5b).

Thanks to @vasild for letting me know how to call all that gdb stuff :)

**Comment by MarcoFalke** [comment] 2020-04-03 16:49
Please upload the backtrace.txt to github. 0bin does not open for me.

**Comment by naumenkogs** [comment] 2020-04-03 16:52
@MarcoFalke done!

**Comment by MarcoFalke** [comment] 2020-04-03 16:58
The backtrace now has only one thread :thinking: How is it possible that it still writes logs?

**Comment by naumenkogs** [comment] 2020-04-03 17:02
>The backtrace now has only one thread 🤔 How is it possible that it still writes logs?

To be clear, this is a new backtrace :)
Sometimes it has 1, sometimes it has 2 threads after all.

**Comment by ryanofsky** [comment] 2020-04-03 19:32
From the stack trace, this is almost definitely caused by ab31b9d6fe7b39713682e3f52d11238dbe042c16 from #18338. [`UnloadWallet`](https://github.com/bitcoin/bitcoin/blob/c8971547d9c9460fcbec6f54888df83f002c3dfd/src/wallet/wallet.cpp#L143) is waiting forever for the shared_ptr reference count to be released, and apparently it doesn't happen in the Ctrl-C shutdown sequence

**Comment by naumenkogs** [comment] 2020-04-03 20:20
@ryanofsky you are correct. Before this commit all good, after this commit the problem occurs.

**Comment by promag** [comment] 2020-04-03 20:57
@naumenkogs can't reproduce. It always quit, mainnet, testnet, regtest, with multiple wallets.. Have you done a make clean?

**Comment by naumenkogs** [comment] 2020-04-03 21:03
@promag yes, I did make clean. I also never touch wallet in my tests or anything. And I run mainnet here.

**Comment by ryanofsky** [comment] 2020-04-03 21:40
I wonder if boost version might be a variable. Maybe different versions of the boost signals library are storing and calling the callback functions (with embedded shared_ptrs) differently.

**Comment by promag** [comment] 2020-04-04 02:17
Please detail your dependencies and compiler so we can try to reproduce.

**Comment by promag** [comment] 2020-04-04 02:19
Also, does it quit fine with stop RPC? And does it hang with unloadwallet RPC - see the log for "release wallet" or something like that.

**Comment by naumenkogs** [comment] 2020-04-04 02:25
@promag 
gcc version 9.2.1 20191102
BOOST 1.58

What else is relevant?

**Comment by naumenkogs** [comment] 2020-04-04 02:35
I just noticed it starts with a lot of CPU (30%), but slowly releases it by 0.5% every second, stopping at 0.4.

It also hangs when I do ``src/bitcoin-cli stop``. 
Unload wallet call takes forever to execute (like more than 10 seconds, but I can wait for more if needed).
I'll just repeat that I'm happy to let you in my VM if that makes life easier :)

**Comment by promag** [comment] 2020-04-04 09:27
Does it hang if you run with `-nowallet`?

> I'll just repeat that I'm happy to let you in my VM if that makes life easier :)

Sure, if I can't reproduce here.

**Comment by promag** [comment] 2020-04-04 10:17
@naumenkogs FYI I've managed to reproduce the problem, in bionic I've downloaded boost 1.58.0 source and also installled same gcc version. Running with `-nowallet` quits fine.

**Comment by promag** [comment] 2020-04-04 10:39
@ryanofsky `use_count()` of wallet shared pointer doesn't change after https://github.com/bitcoin/bitcoin/blob/c8971547d9c9460fcbec6f54888df83f002c3dfd/src/wallet/wallet.cpp#L66-L67

**Comment by promag** [comment] 2020-04-04 11:09
Some interesting boost signals2 changes after 1.58

https://github.com/boostorg/signals2/commit/a305f0b2c16d778601f20a3624f38f94e9c22ab0#diff-c210ca6e90d2fa78a266ca37d16de6da

https://github.com/boostorg/signals2/commit/c22312b86c906368eb2ed0d5e95bfcf467d69785#diff-c210ca6e90d2fa78a266ca37d16de6da

**Comment by naumenkogs** [comment] 2020-04-04 12:27
@promag 
>Running with -nowallet quits fine.

I confirm!

**Comment by promag** [comment] 2020-04-04 14:18
Will push fix, thanks for reporting!

**Comment by ryanofsky** [comment] 2020-04-04 16:13
Just dropping boost here could fix this. Would be useful to test with #18524:

```bash
git fetch https://github.com/bitcoin/bitcoin pull/18524/head
git cherry-pick FETCH_HEAD
```

**Comment by naumenkogs** [comment] 2020-04-04 16:38
@ryanofsky I confirm that #18524 solves the problem.

**Comment by hebasto** [comment] 2020-04-04 19:04
> Steps to reproduce (it happens every time I repeat this sequence):
> 
>    1. src/bitcoind
> 
>    2. wait til see first message `New outbound peer connected: version`
> 
>    3. click Ctrl+ C (afaik this is SIGINT)
> 
>    4. The process stuck with these logs at the end:
> 
>    5. Wait for several minutes, nothing happens.
> 
>    6. Try kill $PID, doesn't do anything
> 
>    7. Finally, do kill -9 $PID to get rid of the process

Confirm the bug on Ubuntu 16.04.6 LTS.

**Comment by ryanofsky** [comment] 2020-04-06 15:37
#18524 (now merged) should fix this issue. The PR description says it's a refactor, but it's only a refactor for new versions of boost (>=1.59). With an old version of boost it changes behavior and fixes this bug.

**Closed** 2020-04-06 15:38 UTC
Labels: Bug
