### ISSUE TITLE
Export a watch wallet only (with descriptors and without private keys) for an air gap setup

### ISSUE THREAD

**Issue by Tracachang** [bitcoin/bitcoin#24829] opened 2022-04-11 20:05 UTC
**Is your feature request related to a problem? Please describe.**

For long time I've seen users looking for a way to do an air gap setup with Bitcoin Core, since there were no easy way people tend to go with other solutions such as armory, electrum which offers an easy and friendly way to do it.

Since Bitcoin Core v 22.0 and with the command  listdescriptors it can be done easily:

OFFLINE PC - Create a wallet with descriptors=true, export descriptors with "listdescriptors".
ONLINE PC - Create a wallet without privatekeys, descriptors=true, and importdescriptors to have a functional watch only wallet for receiving funds and create unsigned transactions.

**Describe the solution you'd like**

Instead of creating two wallets, one offline and a watch only and manually have to export/import descriptors, the wallet containing the private keys could offer an option like "exportwatchonly" that would generate a "watch_wallet.dat" without private keys and all descriptors already imported. Making very easy and user friendly the process to create an air gap setup.

**Comment by pinheadmz** [comment] 2023-03-28 18:38
I was able to do what you want to do with a few bash commands (see below).

I suppose we could add arguments `-file <path/to/file>` to both `listdescriptors` and `importdescriptors` that would make this even easier...?


```sh
$ bccli -regtest createwallet original
{
  "name": "original",
  "warning": ""
}

$ bccli -regtest listdescriptors | jq .descriptors -c >> ~/Desktop/watchonly.json
$ bccli -regtest -named createwallet wallet_name=watchonly disable_private_keys=true
{
  "name": "watchonly",
  "warning": ""
}

$ bccli -regtest -rpcwallet=watchonly importdescriptors $(cat ~/Desktop/watchonly.json)
[
  {
    "success": true
  },
  {
    "success": true
  },
  {
    "success": true
  },
  {
    "success": true
  },
  {
    "success": true
  },
  {
    "success": true
  },
  {
    "success": true
  },
  {
    "success": true
  }
]
```

**Comment by Tracachang** [comment] 2023-03-28 22:06
> I was able to do what you want to do with a few bash commands (see below).
> 
> I suppose we could add arguments `-file <path/to/file>` to both `listdescriptors` and `importdescriptors` that would make this even easier...?

Yes, that would be great.

**Comment by Tracachang** [comment] 2023-03-29 17:09
@pinheadmz 

I have followed all the steps using the bash commands from your answer and I am unable to create a receiving taproot address from the GUI (it does not show bech2m but it shows both base58 (legacy & p2sh-segwit and bech32) if I select the watch_wallet, however if I select the "original_wallet" it appears in GUI all 4 including bech32m.

In any case, from console I can `getnewaddress "test" "bech32m"` and it works but for some reason not on GUI.

**Comment by pinheadmz** [comment] 2023-03-31 14:32
Hm, seems to work for me on master branch. The taproot addresses are identical from each wallet.

![Screen Shot 2023-03-31 at 10 29 57 AM](https://user-images.githubusercontent.com/2084648/229149164-f4a2a474-5b86-4b11-b702-3a0b1418fbf8.png)
![Screen Shot 2023-03-31 at 10 29 42 AM](https://user-images.githubusercontent.com/2084648/229149166-d3e584b0-3d10-4fc3-aab6-533a5eba5013.png)

**Comment by Tracachang** [comment] 2023-04-07 19:51
> Hm, seems to work for me on master branch. The taproot addresses are identical from each wallet.

Did not try the master branch, I am on v.24.0.1

**Comment by pinheadmz** [comment] 2023-04-12 19:00
Ok I just pulled v24.0.1 and repeated steps with CLI and GUI, same outcome -- are you still unable to do this?

**Comment by Tracachang** [comment] 2023-04-12 19:22
> Ok I just pulled v24.0.1 and repeated steps with CLI and GUI, same outcome -- are you still unable to do this?

Just tried again following this commands and I am still unable to see taproot in GUI

```
$ bitcoin-cli createwallet original
{
  "name": "original",
  "warning": ""
}

$ bitcoin-cli -rpcwallet=original listdescriptors | jq .descriptors -c >> ~/Desktop/watchonly.json
$ bitcoin-cli -named createwallet wallet_name=watchonly disable_private_keys=true
{
  "name": "watchonly_original",
  "warning": ""
}

$ bitcoin-cli -rpcwallet=watchonly importdescriptors $(cat ~/Desktop/watchonly.json)
[
  {
    "success": true
  },
  {
    "success": true
  },
  {
    "success": true
  },
  {
    "success": true
  },
  {
    "success": true
  },
  {
    "success": true
  },
  {
    "success": true
  },
  {
    "success": true
  }
]


```

**Comment by pinheadmz** [comment] 2023-04-12 19:34
> Just tried again following this commands and I am still unable to see taproot in GUI

at all? or just in the watch-only wallet?

**Comment by Tracachang** [comment] 2023-04-22 13:27
> > Just tried again following this commands and I am still unable to see taproot in GUI
> 
> at all? or just in the watch-only wallet?

Just on GUI with the watch-only wallet, but on console using watch-only I can create taproot receiving addresses.

**Comment by pinheadmz** [comment] 2023-05-01 17:54
@Tracachang We're going to close this issue as "won't fix" for now. I'm going to follow up in https://github.com/bitcoin/bitcoin/issues/9492 where I see you've already chimed in. I think a simple doc outlining the list/import descriptor commands I commented above and using PSBT for signing would be the most valuable.

As far as the missing taproot addresses in the GUI you've reported - that could be opened as a new issue if you can provide steps to reproduce it with the latest release of Bitcoin Core or master branch (I was unable to reproduce personally)

**Closed by pinheadmz** 2023-05-01 17:54 UTC
Labels: Feature

**Comment by Meru852** [comment] 2023-05-02 00:56
some one please help me to finish this script i made cause i can't get the true balance of running tx.


from bitcoinaddress import *

while True:
   wallet=Wallet()
   print(wallet)
