### ISSUE TITLE
build: make translate not working correctly on macOS

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#16891] opened 2019-09-17 04:12 UTC
While reviewing #16882 I noticed that `make translate` doesn't seem to be working completely correctly on macOS. It doesn't generate the changes to `src/qt/bitcoinstrings.cpp`. `xgettext` is available and picked up by `./configure`.

I tested on a Debian system instead, and everything work fine there (reproduces the changes in #16882), so I assume it's some macOS quirk.

**Comment by D4nte** [comment] 2019-10-06 11:16
My findings so far: gettext is not invoked when doing `make translate` on Mac os.
This is because [this task](https://github.com/bitcoin/bitcoin/blob/7b701fef58f627956d597817a1f9422edd890cdc/src/Makefile.qt.include#L356) is not being triggered.

On Ubuntu:
```
$ make translate
  GEN      qt/bitcoinstrings.cpp
  GEN      translate
[...]
```

On Mac:
```
$ make translate
  GEN      translate
```

**Comment by D4nte** [comment] 2019-10-06 11:49
I was able to reproduce on ubuntu too:

Running `make -d`:
```
   Finished prerequisites of target file `qt/bitcoinstrings.cpp'.
   Prerequisite `addrdb.cpp' is older than target `qt/bitcoinstrings.cpp'.
...
   Prerequisite `wallet/wallet.cpp' is older than target `qt/bitcoinstrings.cpp'.
...
  No need to remake target `qt/bitcoinstrings.cpp'.
```

`wallet/wallet.cpp` is correctly checked.

I was able to reproduce because I ran the command a first time, then reverted the changes with `git checkout` and reverted again.

At this stage, I believe the issue may be related to the order on which the files are written when cloning or checking out the repository locally. I will need to spend more time looking at the filesystem stats for the files and understand how make decides what file is older than a target (mtime?) and whether this information is suppose to be preserved in git.

In any case, as `qt/bitcoinstrings.cpp` is a generated file AND being checked in, I believe the best practice is to include it in `.PHONY`.

**Comment by D4nte** [comment] 2019-10-06 20:17
Git is not supposed to preserve mtime https://git.wiki.kernel.org/index.php/ContentLimitations

**Comment by MarcoFalke** [comment] 2019-10-06 20:41
Are the maintainer scripts supposed to be working on non-ubuntu? I think it is fine to not support macOS

**Comment by D4nte** [comment] 2019-10-07 05:07
> Are the maintainer scripts supposed to be working on non-ubuntu? I think it is fine to not support macOS

According to my investigation this is not mac specific but due to the fact that a generated file is checked in yet not to be generated everytime a pre-requisite file is changed.

**Closed** 2019-10-08 12:08 UTC
Labels: Build system, good first issue
