### ISSUE TITLE
Falsely triggered "check your network connection" error while catching up. 

### ISSUE THREAD

**Issue by chronicbitcoin** [bitcoin/bitcoin#6251] opened 2015-06-08 04:57 UTC
One of my nodes on master was catching up with the block chain (~200 blocks behind) and triggered the following error, which remained even after maintaining sync with the network for a few hours. Misfiring is understandable, leaving it lingering after catching up feels a little buggy. Error was cleared after a restart.

```
{
...
  "blocks": 359934,
...
  "connections": 8,
...
  "errors": "WARNING: check your network connection, 0 blocks received in the last 4 hours (24 expected)"
}
```

**Comment by laanwj** [comment] 2015-06-08 07:57
Thanks for reporting. There seems to be an issue with the computation causing it to trigger more often than intended, also reported in #5947.

@gavinandresen can you take a look?

We should probably disable this on the 0.11 branch and rc2 until it's fixed.

**Comment by laanwj** [comment] 2015-06-08 08:03
Another problem reported by @gmaxwell on IRC:
```
<gmaxwell> I'm getting a spurrious
<gmaxwell> "errors" : "WARNING: check your network connection, 0 blocks received in the last 4 hours (24 expected)"
<gmaxwell> on testnet with 0.11
<gmaxwell> the blocks on the tip of testnet are actually somewhat in the future
<gmaxwell> wumpus: in the case I gave it just made no sense. e.g. claimed 0 blocks when in fact there had been many.
```

**Comment by Diapolo** [comment] 2015-06-08 11:58
@laanwj Just asking (without looking at the code) is this warning also displayed in the GUI at all?

**Comment by gavinandresen** [comment] 2015-06-08 14:57
I'll make some time to try to reproduce. The fix is probably to look at timestamps on the best headers-only chain (instead of the main chain).

**Comment by laanwj** [comment] 2015-06-15 08:33
Should be fixed by #6256

**Comment by vegard** [comment] 2015-08-17 13:29
I get the exact same error after initial sync using latest git master (586a2925), `debug.log` shows last UpdateTip was just ~30 seconds ago (and it's been fully synced for at least 6 hours). Do I open a new ticket?

**Comment by unsystemizer** [comment] 2015-12-06 07:56
Same here on version 0.11.2 and I see this quite often which is why I finally decided to report it.

@Diapolo, yes, the warning also shows in `bitcoin-cli getinfo` output although the blockchain is very up to date (shows the latest block which is as recent as 8 minutes ago).

![image](https://cloud.githubusercontent.com/assets/13134193/11612353/67eab052-9c31-11e5-85c2-4303e5d76441.png)

**Comment by laanwj** [comment] 2015-12-07 12:32
I think @gmaxwell reported this problem as well recently on IRC after laptop came back from sleep. Looks like the error doesn't go away when the problem goes away. Reopening.

**Comment by l0rb** [comment] 2018-07-04 07:34
This seems to be still unfixed. Once triggered the warning never disappears.

**Comment by MarcoFalke** [comment] 2018-07-10 11:52
@l0rb What version are you running. This was removed in #8275

**Closed by MarcoFalke** 2018-07-10 11:52 UTC
Labels: P2P
