### ISSUE TITLE
Restore UI notifications and -walletnotify behavior for block conflicted transactions

### ISSUE THREAD

**Issue by jnewbery** [bitcoin/bitcoin#18325] opened 2020-03-11 22:46 UTC
UI notifications and the `-walletnotify` process should be triggered for wallet transactions that are conflicted out of the mempool by a newly connected block.

We broke this in #9240, reported it in #9479 and fixed it in #9371.

We inadvertently broke it again in  #16624 (Sep 2019 commit 7e89994) by removing the call to `SyncTransaction()` for transactions that are conflicted out of the mempool when a block is connected.

I think the fix is just to restore the call to `SyncTransaction()` for transactions that are conflicted out of the mempool. Could we also call `SyncTransaction()` for _any_ transaction that is removed from the mempool (and fires `TransactionRemovedFromMempool`)?

h/t to @ryanofsky for spotting this.
@ariard - any thoughts about just reverting 7e89994?

**Comment by ryanofsky** [comment] 2020-03-12 21:20
> @ariard - any thoughts about just reverting 7e89994?

I guess this isn't possible if we merge #17477, but as the PR description suggests, "Now that we have a `TransactionRemovedFromMempool` callback", maybe we would call `SyncTransaction` from there

**Comment by jnewbery** [comment] 2020-03-12 21:32
> maybe we would call SyncTransaction from there

Yes, but probably just for `CONFLICT` transactions, to match previous behavior. We've never notified for transactions removed from the mempool for expiry, replacement, etc.

**Comment by ariard** [comment] 2020-03-16 01:22
@jnewbery if I open a new PR to revert what do you think will get merged first between it and #17477+new commit calling `SyncTransaction` ? I'll add the test long-time promised for this case :)

**Comment by MarcoFalke** [comment] 2020-03-16 18:28
Instead of breaking this every 4 years, a test might be good to avoid it. If nobody beats me to it, I might write one.

Also, this seems like a bugfix that should go into 0.20.0?

**Comment by jnewbery** [comment] 2020-03-17 18:36
I don't know whether #17477 can go in now that we're in feature freeze, but as @MarcoFalke says, fixing this bug could still get in for 0.20.

I'm happy to rebase 17477 on a fix for this.

> Instead of breaking this every 4 years, a test might be good to avoid it. If nobody beats me to it, I might write one.

Concept ACK!

**Comment by ryanofsky** [comment] 2020-03-31 16:46
> We inadvertently broke it again in #16624 (Sep 2019 commit [7e89994](https://github.com/bitcoin/bitcoin/commit/7e89994133725125dddbfa8d45484e3b9ed51c6e))

In terms of releases, 0.19 was the first version to include that commit, so the behavior's been broken since then and maybe gone unnoticed.

**Comment by ariard** [comment] 2020-04-01 02:32
Likely we need to pass the eviction reason in `TransactionsRemovedFromMempool` to dissociate between EXPIRY,REORG and CONFLICT on the wallet side.

> UI notifications and the -walletnotify process should be triggered for wallet transactions that are conflicted out of the mempool by a newly connected block.

@jnewbery conflicts should already be notified when they concern a transaction or its children already tracked by the wallet (either spending from us, or paying us). The broken case IIRC is about a non-connected tx, unconfirmed txB is paying us from an unconfirmed txA which doesn't involve us. If txA gets conflicted we won't see it in `BlockConnected`. Or did you see another uncovered case by testing ?

**Comment by ryanofsky** [comment] 2020-04-01 02:39
> conflicts should already be notified when they concern a transaction or its children already tracked by the wallet (either spending from us, or paying us)

Could you explain this more? Where would this happen if TransactionsRemovedFromMempool doesn't call SyncTransaction?

**Comment by ryanofsky** [comment] 2020-04-01 02:43
I guess the MarkConflicted loop in AddToWalletIfInvolvingMe could trigger this, but it doesn't seem to currently do external notifications.

**Comment by jnewbery** [comment] 2020-04-02 14:01
> conflicts should already be notified when they concern a transaction or its children already tracked by the wallet (either spending from us, or paying us)

How? UI and external process notifications happen inside `AddToWallet()` (here: https://github.com/bitcoin/bitcoin/blob/b83565625e32b22395e28c1965b2e42fc17f04d7/src/wallet/wallet.cpp#L844 and here: https://github.com/bitcoin/bitcoin/blob/b83565625e32b22395e28c1965b2e42fc17f04d7/src/wallet/wallet.cpp#L862). `AddToWallet()` doesn't get called for conflicted transactions.

**Comment by ariard** [comment] 2020-04-11 23:52
@jnewbery Ah yes I meaned `CWalletTx::Confirmation` should be alright thanks to the `MarkConflicted` but we care about UI notifications here. See #18600 for further discussion :)

**Comment by MarcoFalke** [comment] 2020-05-15 12:03
> Sep 2019 commit 7e89994

So this is broken in all 0.19.* releases? Given that the bugfix is still "waiting for author", I went ahead and moved this back to 0.20.1

**Comment by ryanofsky** [comment] 2020-05-15 13:50
> > Sep 2019 commit [7e89994](https://github.com/bitcoin/bitcoin/commit/7e89994133725125dddbfa8d45484e3b9ed51c6e)
> 
> So this is broken in all 0.19.* releases?

Yes, behavior's been the same since  #16624. I implemented a minimal fix in #18982 to just restore previous behavior while #18600 explores better approaches.

**Closed** 2020-06-02 22:12 UTC
Labels: Bug, Wallet
