### ISSUE TITLE
Alerting blockchain reorgs

### ISSUE THREAD

**Issue by AlisterMaclin** [bitcoin/bitcoin#14915] opened 2018-12-10 18:53 UTC
Suggestion: add a **optional** possibility to notify user about chain reorganizing
(a) as a feature of GUI client (alert)
(b) as a feature of daemon (executing external program)

Discussion is here: https://bitcointalk.org/index.php?topic=5078692.0

**Comment by promag** [comment] 2018-12-12 16:13
a) not sure why it is relevant for the GUI. What would be the use case there?
b) useful for monitoring/stats?

**Comment by WetPuppyKisses** [comment] 2018-12-14 16:13
Could be implemented both in the GUI, but under an "advance monitoring setting" or something and in the daemon as a programmable watchdog

**Comment by pinheadmz** [comment] 2023-04-12 19:57
NACK, I don't think there is a really great use for this for most users. Reorgs are currently very rare and when they happen they are 1 block at most. The GUI should and does show users if their transactions are unconfirmed, that should be the most important thing. As for (b) an advanced user can use `-blocknotify` and some external script to detect that more than one block at the same height has been processed.

**Comment by pinheadmz** [comment] 2023-06-02 14:55
I think it's safe to close this as won't-fix for the reasons stated above. Pull requests are always welcome!

**Closed by pinheadmz** 2023-06-02 14:55 UTC
Labels: Brainstorming
