### ISSUE TITLE
Return fee in `getrawtransaction`

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#23264] opened 2021-10-12 06:18 UTC
Similar to how the fee is returned in `getblock` (#18771), it should be returned in `getrawtransaction`.

#### Useful skills:

Understanding of undo data, the RPC interface and the functional tests.

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by KenCox94** [comment] 2021-10-12 18:28
I'd love to take a look at this.

**Comment by meshcollider** [comment] 2021-10-14 10:27
@KenCox94 if you need any pointers, please don't hesitate to ask here or on IRC #bitcoin-core-dev :)

**Comment by viniciusdepadua** [comment] 2021-11-06 05:20
Is this issue still open? Could I help?

**Comment by fanquake** [comment] 2021-11-06 05:22
This is being worked on in #23319. You could help by reviewing that PR.

**Comment by Mdasgor** [comment] 2021-11-07 18:55
#23267

**Comment by PATOOCTOBER15** [comment] 2021-11-09 22:12
HELLO. I NEED TO KNOW IF I COULD RECOVER MY BITCOINS TRANSFERRED 4 DAYS AGO TO A WRONG EWALLET AND THE PROBLEM OR ISSUE IS THAT I DO NOT KNOW THE PERSON NOR THE PLATFORM WHERE MY MONEY GOT !!!!  SO IS THERE A WAY AS TO NOTIFY TO THE DESTINATARY OF THE ISSUE AND THAT HE WRONGLY RECEIVED A MONEY THAT DID NOT BELONG TO HIM??? THESE WERE 500 USD I SENT TO ANOTHER EWALLET AND SO THAT MONEY IS NOT BELONGING TO THIS WRONG EWALLET??  THE PROBLEM IS THAT THE REAL DESTINATARY TOLD ME  HE HAD CHANGED HIS EWALLET BUT I KNEW THIS AFTER HAVING ALREADY SENT THE BITCOINS TO A WRONG OR NOT CORRESPONDING BITCOIN ADDRESS???

**Comment by wangzemchd** [comment] 2021-11-18 09:59
> 与`getblock`( #18771 ) 中费用的返还方式类似，应在 中返还`getrawtransaction`。
> 
> #### 有用的技能：
> 了解撤销数据、RPC 接口和功能测试。
> 
> #### 想解决这个问题吗？
> 有关贡献的指导，请在打开拉取请求之前阅读[CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md)。

我有个疑惑、安全性

**Comment by Blockchairburqaa** [comment] 2021-11-23 20:35
dougEfresh:23264-fee-getrawtransaction

**Comment by Blockchairburqaa** [comment] 2021-11-23 20:35
Blockchain 232674

**Comment by Blockchairburqaa** [comment] 2021-11-23 20:36
Blockchain#242674

**Comment by TeresaHodges764** [comment] 2022-03-10 10:33
I put in money in an investment company with high hopes of making more Ps for myself but to my disappointment, when it was time to make a withdrawal it became an issue they started asking for tax fee, withdrawal fee and lots more. I was recommended to JIMFUNDSRECOVERY  @  CONSULTANT d0t COM where I filed a complaint and I was able to get my money after meeting certain requirements. Thumbs Up guys

**Closed** 2022-12-13 23:09 UTC
Labels: Feature, RPC/REST/ZMQ, good first issue
