### ISSUE TITLE
depends: Some fallback downloads are missing

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#22556] opened 2021-07-26 12:49 UTC
```
$ wget https://bitcoincore.org/depends-sources/miniupnpc-2.2.2.tar.gz
--2021-07-26 15:44:33--  https://bitcoincore.org/depends-sources/miniupnpc-2.2.2.tar.gz
Resolving bitcoincore.org (bitcoincore.org)... 198.251.83.116, 107.191.99.5
Connecting to bitcoincore.org (bitcoincore.org)|198.251.83.116|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-07-26 15:44:34 ERROR 404: Not Found.

```

```
$ wget https://bitcoincore.org/depends-sources/capnproto-c++-0.7.0.tar.gz
--2021-07-26 15:41:57--  https://bitcoincore.org/depends-sources/capnproto-c++-0.7.0.tar.gz
Resolving bitcoincore.org (bitcoincore.org)... 107.191.99.5, 198.251.83.116
Connecting to bitcoincore.org (bitcoincore.org)|107.191.99.5|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-07-26 15:41:58 ERROR 404: Not Found.

```

Did not test all of dependencies though.

---

UPDATE: [This](https://github.com/hebasto/artefacts/blob/master/check-fallback-downloads.sh) script allows to verify all downloads.

**Comment by hebasto** [comment] 2021-07-26 12:50
cc @laanwj

**Comment by jarolrod** [comment] 2021-07-28 02:54
from my testing the following are also missing:

native_mac_alias-v2.2.0
qtbase-everywhere-src-5.12.11
qttranslations-everywhere-src-5.12.11.tar.xz
qttools-everywhere-src-5.12.11.tar.xz

**Comment by MarcoFalke** [comment] 2022-02-01 13:39
See also https://github.com/bitcoin-core/bitcoincore.org/issues/782

**Comment by theuni** [comment] 2022-02-01 15:40
Grr, thanks, I'll take a look at why this isn't syncing (again).

**Comment by theuni** [comment] 2022-02-01 21:42
Ok, there are a few things going on.

- `make download` wasn't running with MULTIPROCESS=1, so it wasn't pulling in the multiprocess deps. I've now added it.

- Some wgets are failing because of a cert problem (expired letsencrypt) on the server.

- verify-commits.py is failing on the server and locally for me as well. @MarcoFalke it's been a while since I've messed with any of the verify stuff, maybe there's something I'm missing? 

For now I've manually uploaded all of the missing files mentioned above.

**Comment by MarcoFalke** [comment] 2022-02-02 07:54
Keys regularly get their expiry extended, so you'll need to fetch the latest from a keyserver before running verify-commits. See also commit c702d1fefddcbd8c6465d3dc330fde235d03337e

**Comment by theuni** [comment] 2022-02-02 15:34
@MarcoFalke Thanks for the tip, that was indeed the issue :)

I had successfully received keys from a bunch of other keyservers, but pulling from `keys.openpgp.org` fails on the server. Pulling from there works for me locally (and now so does verify-commits), so I'm guessing the problem with the server receiving keys is related to the other current ssl misconfiguration problem. I'll keep poking at this.

**Comment by hebasto** [comment] 2022-02-02 17:23
> Edit: once this is fixed, I'll work on moving the sync script into git so that it's not untouchable voodoo :)

:+1:

**Comment by fanquake** [comment] 2022-07-29 11:40
Is this still an issue, and if so, which downloads are still missing?

**Comment by hebasto** [comment] 2022-07-29 16:10
> Did not test all of dependencies though.

[This](https://github.com/hebasto/artefacts/blob/master/check-fallback-downloads.sh) script allows to verify all downloads.

For now, the only one fails -- `clang+llvm-10.0.1-aarch64-linux-gnu.tar.xz`:
```
$ wget https://bitcoincore.org/depends-sources/clang+llvm-10.0.1-aarch64-linux-gnu.tar.xz
--2022-07-29 17:04:44--  https://bitcoincore.org/depends-sources/clang+llvm-10.0.1-aarch64-linux-gnu.tar.xz
Resolving bitcoincore.org (bitcoincore.org)... 107.191.99.5, 198.251.83.116
Connecting to bitcoincore.org (bitcoincore.org)|107.191.99.5|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-07-29 17:04:45 ERROR 404: Not Found.

```

**Comment by MarcoFalke** [comment] 2022-07-30 07:32
> [This](https://github.com/hebasto/artefacts/blob/master/check-fallback-downloads.sh) script allows to verify all downloads.

It might be easier to modify `make download` to only check the fallback URL

**Comment by fanquake** [comment] 2022-08-10 14:30
Going to close this as done for now. I think future issues can be opened against https://github.com/bitcoin-core/bitcoincore.org. This is not a bug in Bitcoin Core.

**Closed by fanquake** 2022-08-10 14:30 UTC
Labels: Build system
