### ISSUE TITLE
./configure error: No working boost sleep implementation found 

### ISSUE THREAD

**Issue by chromebanana** [bitcoin/bitcoin#12591] opened 2018-03-03 18:22 UTC
OS: macOS 10.12.3
bitcoin v0.16.0 (master)

I have been following the instructions in build-osx.md to configure Bitcoin Core Build

Brew is up to date and all the recommended packages installed
./autogen.sh is successful but ./configure returns this error:

>  error: No working boost sleep implementation found 

I have reviewed earlier disccusions of this very issue but I'm not able to fix this problem on my machine. 

Can anybody help?

config.log here
https://pastebin.com/m4Rez3nr

**Comment by headhunter911** [comment] 2018-03-03 23:38
What is the boost version?

**Comment by chromebanana** [comment] 2018-03-04 12:39
boost 1.66.0

**Comment by headhunter911** [comment] 2018-03-04 17:14
did you brew link boost before running configure?

**Comment by chromebanana** [comment] 2018-03-05 10:45
yep already linked, i also tried unlinking/relinking

**Comment by fanquake** [comment] 2018-03-06 18:44
@chromebanana Looks like you have brew installed in a custom directory? 
That's probably the issue, as boost is not the only dependency that can't be found. 
Have you tried passing the location of dependencies to ./configure ?

**Comment by fanquake** [comment] 2018-03-14 14:16
Closing for now, please re-open/followup if required.

**Closed by fanquake** 2018-03-14 14:16 UTC
Labels: MacOSX

**Comment by reedho** [comment] 2018-03-21 07:33
@chromebanana I have the some problem, with some luck today, finally got `./configure` finish without error with `CXXFLAGS="-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk"`

YMMV.

**Comment by chromebanana** [comment] 2018-03-22 16:11
@fanquake @reedho thanks for your help. My mac has actually died (2011 is a long time ago:( )
Going to continue bitcoin exploration on a Linux machine. Will return here if/when needed.

Cheers

**Comment by suryakss** [comment] 2018-12-27 14:45
> OS: macOS 10.12.3
> bitcoin v0.16.0 (master)
> 
> I have been following the instructions in build-osx.md to configure Bitcoin Core Build
> 
> Brew is up to date and all the recommended packages installed
> ./autogen.sh is successful but ./configure returns this error:
> 
> > error: No working boost sleep implementation found
> 
> I have reviewed earlier disccusions of this very issue but I'm not able to fix this problem on my machine.
> 
> Can anybody help?
> 
> config.log here
> https://pastebin.com/m4Rez3nr

**What worked for me:** 

`$brew unlink boost
$brew link --overwrite boost@1.57 --force
`
// I used --force because boost is keg-only.
/* Also, I had to use --overwrite so that over 1000 symlinks would be created compared to the normal link command (brew link boost@1.57 --force), which would, unfortunately, create only around 300-500 symlinks. */

**Comment by reedho** [comment] 2018-12-29 02:51
A while back, i found the problem was caused by there are some .h files in /usr/local/include from package installed manually (or probably from old brew packages) clash with system's time* header files. 

These kind of problem just disappear after i clean up the "Unexpected header files" from `brew doctor` output.

HTH.
