### ISSUE TITLE
"Error opening block database" after regular startup. Works again once after each fresh install.

### ISSUE THREAD

**Issue by Compunologist** [bitcoin/bitcoin#9454] opened 2017-01-01 20:13 UTC
Happy New Year everybody!

### Describe the issue

I have installed Bitcoin Core (64-bit) and changed the data directory to one on my NAS. I ran Bitcoin Core and after 2 days of synchronizing the Bitcoin Core window shows "Up to date". The program exits without any problems.

After each following regular startup however Bitcoin Core (64-bit) reports "Error opening block database. Do your want to rebuild the block database now?" and I have to abort the operation.

When I install Bitcoin Core again and choose to "Run Bitcoin Core (64-bit)" everything works again, including the already synchronized blocks.

#### If so, please list the steps to reproduce below:
1. Start Bitcoin Core
2. Message: "Error opening block database. Do your want to rebuild the block database now?"

![error opening block database do your want to rebuild the block database now - 2017-01-01 19_33_06-bitcoin](https://cloud.githubusercontent.com/assets/20874837/21582591/a3646d50-d05e-11e6-8f8a-33c9167ba96a.png)

3. Run the Bitcoin Core installer again: "bitcoin-0.13.1-win64-setup.exe"
4. Choose "Run Bitcoin Core (64-bit)", everything works again

![2017-01-01 20_54_08-bitcoin core - wallet](https://cloud.githubusercontent.com/assets/20874837/21582761/b9ed3d0c-d065-11e6-988b-e9b82b665cd2.jpg)

### What version of bitcoin-core are you using?
Bitcoin Core version v0.13.1 (64-bit)

### Machine specs:
- OS: Windows 10 Pro
- CPU: Intel Core i7
- RAM: 8.00 GB
- Disk size: 256GB & 4TB
- Disk Type (HD/SDD): SSD & HD

### Any extra information that might be useful in the debugging process.
This is how the debug.log looks like when the error occurs:
[Bitcoin debug_not working on regular startup.txt](https://github.com/bitcoin/bitcoin/files/680159/Bitcoin.debug_not.working.on.regular.startup.txt)

This is how the debug.log looks like after a reinstall with Bitcoin Core correctly running:
[Bitcoin debug_working again after fresh install.txt](https://github.com/bitcoin/bitcoin/files/680160/Bitcoin.debug_working.again.after.fresh.install.txt)

**Comment by MarcoFalke** [comment] 2017-01-01 21:02
Relevant highlights from debug.log:

```
2017-01-01 18:33:00 GUI: "registerShutdownBlockReason: Successfully registered: Bitcoin Core didn't yet exit safely..."
[...]
2017-01-01 18:33:01 Opening LevelDB in \\diskstation\incoming\Bitcoin\blocks\index
2017-01-01 18:33:01 IO error: C:\Program Files\Bitcoin\\diskstation\incoming\Bitcoin\blocks\index\LOCK: Could not lock file.

**Comment by unsystemizer** [comment] 2017-01-02 06:28
NAS? Has Bitcoin on Windows ever supported SMB? I don't think it did.
Furthermore, https://github.com/bitcoin/bitcoin/issues/3641#issuecomment-35256537

**Comment by jonasschnelli** [comment] 2017-01-03 07:58
Duplicate of https://github.com/bitcoin/bitcoin/issues/9157. Closing

**Closed by jonasschnelli** 2017-01-03 07:58 UTC
Labels: Utils and libraries, Windows

**Comment by KavehR** [comment] 2018-03-31 09:49
Had the same kind of issue on a mapped drive over my NAS, where Bitcoin Core did not finish synchronizing and was not starting anymore, throwing "Error opening block database". The client was just aborting whether choosing OK for rebuild or abort..

I launched again the Bitcoin Core installation setup, and it installed as if it was the first time.
The good news is that when the setup finished the installation and launched Bitcoin Core, the client started again synchronizing from where it left, without me re-defining my previous path on my NAS, as if the program used the previous preferences stored somewhere.

Not sure what was preventing Bitcoin Core from running again, but re-installing it solved the issue without having to re-synchronize the whole blockchain.
