### ISSUE TITLE
Qt Splash Screen is deleted (and accesses wallet) after Shutdown() (and wallets are deleted).

### ISSUE THREAD

**Issue by TheBlueMatt** [bitcoin/bitcoin#12372] opened 2018-02-06 22:55 UTC
In trying to debug #12337 I added a sleep at the end of AppInitMain() to simulate being able to close the application late in the AppInitMain() process. If I close the splash screen at this point, I get a reliable crash when the splashs screen is deleted as it tries to disconnect itself from the wallet ShowProgress signal after Shutdown() has been called and the wallet has been deleted.

**Comment by MarcoFalke** [comment] 2018-02-07 03:10
@TheBlueMatt Are you sure this is something with the wallet?

I think the issue is that the shutdown process has started in `requestShutdown`, but initialize will happily continue with `initializeResult` and start threads late in the shutdown progess. Deleting this running thread will crash the application according to the qt docs:
https://github.com/qt/qtbase/blob/e5033a5c9b769815112e922d0b224af860afd219/src/corelib/thread/qthread.cpp#L412-L415

**Comment by MarcoFalke** [comment] 2018-02-07 03:11
Potentially I am talking about a different issue.

**Comment by laanwj** [comment] 2018-02-07 09:35
Should be fixed by #12374.

**Closed** 2018-02-08 07:54 UTC
Labels: GUI
