### ISSUE TITLE
General discussion on review process, impact on consensus compatible forks, noisy comments

### ISSUE THREAD

**Issue by michaelfolkson** [bitcoin/bitcoin#25177] opened 2022-05-20 13:32 UTC
There are a few broader issues being bundled into the discussion on the now merged PR #25153 which are leading to some noise and what I consider some inappropriate and uninformed Approach NACKs. I do think these issues warrant further discussion but they are not specific to that particular PR.

> If by more work, you mean, it might make it more difficult for you to maintain Knots, which maintains build options and code that we have removed, then yes, that's possible. However Bitcoin Core isn't making engineering/maintainence decisions based on whether or not they are benficial for forks of this codebase.

I do think Core should factor in the impact of changes to consensus compatible forks such as Knots. It is only one factor of many but I don't see consensus compatible forks as an irrelevance (especially in the light of motivations of Core subprojects like libbitcoinkernel). Long term I consider consensus compatible forks as an escape latch if a group of maintainers/contributors were ever to go rogue and start merging in things to Core with malicious intentions. To be clear I don't think this is happening here nor do I think this will happen anytime soon but I would be very uncomfortable with a future where it became increasingly difficult to maintain a consensus compatible fork of Core.

> Its not necessary to follow the history and sometimes common sense is enough to review a pull request. Particularly after reading such tweet from a respected core developer: https://nitter.net/LukeDashjr/status/1527427645025136641

There are billions of people who can write "Approach NACK" and then parrot what Luke has said without any understanding of the context of prior Core PRs or the challenges of maintaining a consensus compatible fork of Core. This is noise. Hence for future conversations on broader issues that aren't specific to a PR I'd ask you to discuss it on IRC, open an issue etc rather than adding noise to the review of a PR with an uninformed Approach NACK. The review process doesn't work if we start getting billions of parrot NACKs and they somehow have to be factored into the merge decision.

> I think it's overall an improvement to method naming. But I do agree this got merged way too quickly, especially for something that impacts 32 files.

I agree. When there is a technically informed NACK from a maintainer of a consensus compatible fork (and long term contributor to Core) I think at the very least more long term contributors (ideally with contextual understanding of previous PRs) should look at it before it is merged. Ignoring that NACK and merging with a single ACK within 3 days of the PR being opened does not seem like a solid review process to me.

**Comment by hebasto** [comment] 2022-05-20 14:17
> I do think Core should factor in the impact of changes to consensus compatible forks such as Knots. It is only one factor of many but I don't see consensus compatible forks as an irrelevance (especially in the light of motivations of Core subprojects like libbitcoinkernel).

Correct, `libbitcoinkernel` by design assumes to be reused as a library. But Bitcoin Core shouldn't care about code compatibility with any other bitcoin client. It just creates unneeded engineering burden in this repo.

**Comment by 1440000bytes** [comment] 2022-05-20 14:25
![6gvwih](https://user-images.githubusercontent.com/94559964/169547053-e2f2a201-0670-4be2-8cc1-3653b90f6669.gif)

> There are billions of people who can write "Approach NACK" and then parrot what Luke has said without any understanding of the context of prior Core PRs or the challenges of maintaining a consensus compatible fork of Core. This is noise. Hence for future conversations on broader issues that aren't specific to a PR I'd ask you to discuss it on IRC, open an issue etc rather than adding noise to the review of a PR with an uninformed Approach NACK. The review process doesn't work if we start getting billions of parrot NACKs and they somehow have to be factored into the merge decision.

I have the understanding of things being discussed in https://github.com/bitcoin/bitcoin/pull/25153 and do not agree with the way pull request was merged. I do not care if you consider some reviews as noise and it won't affect my reviews.

**Comment by michaelfolkson** [comment] 2022-05-20 15:20
> But Bitcoin Core shouldn't care about code compatibility with any other bitcoin client.

This strikes me as opinionated and I'd be interested if other maintainers and long term contributors share this view. You are effectively arguing that there shouldn't be an escape latch.

e.g. "Long term I consider consensus compatible forks as an escape latch if a group of maintainers/contributors were ever to go rogue and start merging in things to Core with malicious intentions."

Your viewpoint seems to suggest that if Core was ever corrupted with its current dominance on the network and the perception of it being the reference client then Bitcoin would go down with the Core ship. You wouldn't care if it was impossible to maintain a fork of Core as that was never a consideration.

**Comment by hebasto** [comment] 2022-05-20 15:24
> You are effectively arguing that there shouldn't be an escape latch.

No, I am not.

**Comment by michaelfolkson** [comment] 2022-05-20 15:27
Ok sorry, I don't understand your position then. Should Core care whether it is impossible (or extremely difficult) to maintain a consensus compatible fork of Core or should it not? If it shouldn't care that seems to be arguing that there shouldn't be a Core escape latch (for now at least). Hopefully libbitcoinkernel will fulfil its aims and makes this less of a concern.

**Comment by luke-jr** [comment] 2022-05-20 18:49
>I would be very uncomfortable with a future where it became increasingly difficult to maintain a consensus compatible fork of Core.

This is already the case in the present. Bitcoin Core's approaches often almost seem _designed_ to make maintaining derivatives unnecessarily difficult.

>But Bitcoin Core shouldn't care about code compatibility with any other bitcoin client. It just creates unneeded engineering burden in this repo.

Repos don't do engineering. People do.

It's one thing to say "I'm not going to go out of the way to avoid breaking X", it's another to then go out of the way *to* break it when there's no benefit to doing so.

I can continue to provide the minimal patchwork needed to build with standard UniValue before #25153 (which is a best practice, desired and used by people who want Core, not just Knots), but continuing to do so afterward becomes impractical. Since it provides no upsides (unlike #25095 which addresses a real issue), and only breaks compatibility, it should be reverted.

**Comment by michaelfolkson** [comment] 2022-05-20 19:40
This needs the input of some other long term contributors and/or maintainers then. As far as I can work out 3 maintainers believe Core derivatives/consensus compatible forks of Core should be completely ignored and shouldn't factor into Core merge decisions to any extent whatsoever. Understandably Luke is unhappy with that as the maintainer of Knots.

**Comment by achow101** [comment] 2022-05-20 19:55
I agree that compatibility with software forks (of any sort) should not be a factor considered when merging things. Hell, we barely consider that for backporting things for our own older releases. In fact, in the past, we have done large breaking refactors specifically right after the branching of a release even though doing so makes it explicitly harder to make backports.

I don't think it makes a whole lot of sense for us to try to maintain compatibility with upstream UniValue. It doesn't appear to be maintained at all, and we have had it as a subtree for years already.

**Comment by kristapsk** [comment] 2022-05-20 21:04
I also think #25153 was merged too fast when there was NACK from @luke-jr with reasoning (does not mean that I'm for or against specific change myself).

**Comment by MarcoFalke** [comment] 2022-05-21 07:51
I don't think 25153 should be reverted in any case. If we decide to support forked repos that want to support system univalue it should be done properly with something like https://github.com/bitcoin/bitcoin/pull/25153#issuecomment-1132618613 . If we decide against that, then it shouldn't be reverted obviously.

Personally I don't care if 25153 is reverted or not, but I think this whole discussion might be a bit exaggerated. 25153 is a scripted-diff that will run in a few milliseconds. It should take less than 2 minutes for any forked repos to write an inverse scripted-diff which can be executed in the same few milliseconds on any branch they wish to execute it on.

**Comment by MarcoFalke** [comment] 2022-05-21 07:54
Closing for now, as this issue is open-ended, but feel free to continue discussion. Also, happy to re-open if someone thinks this is useful.

**Closed by MarcoFalke** 2022-05-21 07:54 UTC
Labels: Brainstorming

**Comment by luke-jr** [comment] 2022-05-21 08:36
>If we decide to support forked repos that want to support system univalue it should be done properly with something like #25153 (comment) . If we decide against that, then it shouldn't be reverted obviously.

While I obviously prefer fully supporting system univalue, it doesn't have to be all-or-nothing. Only breaking compatibility *as necessary* (eg #25095) allows people to patch those few cases. Going out of the way to break it everywhere unnecessarily (#25153) has no upside, and just makes it impractical for *anyone* to support.

>It should take less than 2 minutes for any forked repos to write an inverse scripted-diff which can be executed in the same few milliseconds on any branch they wish to execute it on.

This isn't sanely distributable or applyable in standard .patch format, and even if one made a giant patch, it would break to combine it with any other modifications.

**Comment by luke-jr** [comment] 2022-06-05 11:38
Why hasn't #25153 been reverted yet?

**Comment by ryanofsky** [comment] 2022-06-05 12:10
> This isn't sanely distributable or applyable in standard .patch format, and even if one made a giant patch, it would break to combine it with any other modifications.

I still think the original sin is [forking the univalue library without renaming it](https://github.com/bitcoin/bitcoin/pull/22646#issuecomment-894163012) so now there are two libraries with the same name, incompatible, with different maintainers and support channels. IMO the best solution would be to rename `libunivalue.a` to `libbitcoin_json.a`, add a comment giving credit and thanks to the original authors, and move on from this.

**Comment by MarcoFalke** [comment] 2022-06-05 15:12
> Why hasn't #25153 been reverted yet?

Because no one created a pull request for it yet. And since the pull request doesn't exists, no one has reviewed it either.

> sin is https://github.com/bitcoin/bitcoin/pull/22646#issuecomment-894163012

It was renamed to `univalue-subtree`, see https://github.com/bitcoin-core/univalue-subtree
