### ISSUE TITLE
Remove bolt-on accounting system

### ISSUE THREAD

**Issue by jgarzik** [bitcoin/bitcoin#3816] opened 2014-03-07 17:24 UTC
The recent malleability issues exposed some cases not covered by the accounting system.  Rather than fix it, the consensus seems to lean towards scrapping the accounting system entirely, and returning to a system where keys may have labels (or tags, as I prefer to call them).

The accounting system can easily result in negative or odd balances if misused or misunderstood, which has happened in the field.  Use of raw tx API or direct spends exacerbates this.  Users are used to seemingly-odd practices of transferring imaginary money from a dummy account, to eliminate a negative number in some cases.

Practically speaking, this seems likely to be a large, incompatible change to RPC.  This implies
- other incompatible RPC changes are possible
- the following line in rpcserver.cpp should be updated along standard REST API versioning conventions, changing the standard URI path from "/" to "/v2/" or somesuch.

```
        if (strURI != "/") {
```

**Comment by jtimon** [comment] 2015-01-03 14:49
Although I agree that a new rpc interface for a separated wallet is the way to go long term, I'm not convinced that a smaller redesign (maybe just moving to int satoshis and getting rid of accounts) it's a waste of time.
There's at least 3 things that will require significant refactoring work that I believe go before separating the wallet: moving transaction consensus validation (to be used by libconsensus), moving the p2p protocol messages and as much policy-related code as possible out of main.
From those 3 things, it seems to me that something like #4646 (moving p2p messages out of main) is specially important for separating the wallet.
Maybe the first step is separating it in different binaries.
Say, instead of having --disable-wallet, that could be the default for bitcoind, and then have a bitcoind-wallet and bitcoin-client-wallet. Maybe always build bitcoin-qt with wallet.
Then at some point separate the repos (maybe bitcoin core becomes a subrepository of bitcoin-wallet ?). I don't know, maybe this belongs to another issue...
My point is, without having a roadmap for the wallet separation, postponing any changes to the rpc interface seems like an unnecessary burden. Simplifying or deleting some rpc calls can actually be good for the separation even if bigger changes are going to happen after the separation.

I would be in favor of declaring accounts deprecated for 0.10 and removing them for 0.11, for example, even if the wallet only gets fully separated by 0.12 or 0.13.

**Comment by benjyz** [comment] 2015-10-28 18:29
AFAIK accounting was removed and this issue is resolved.

**Comment by luke-jr** [comment] 2015-10-28 22:18
It has been marked deprecated, but not yet removed.

**Comment by pstratem** [comment] 2015-12-29 01:53
@luke-jr it's now been (nearly) a full year since the rpc calls were marked as DEPRECATED

I propose that the rpc calls be disabled in the release after 0.12.0 unless a configuration option is set

Then removed entirely in the next release (major or minor).

**Comment by jonasschnelli** [comment] 2015-12-29 07:27
IMO a better option would be to add a second wallet implementation (could be very similar to the existing one / copy of the existing sources in /wallet). The new implementation could be a combination of a new wallet backend format (logdb), the bip32 patch and a multiwallet support.

I guess the maintenance effort would be acceptable.

**Comment by dooglus** [comment] 2015-12-29 11:09
@jgarzik Re "The recent malleability issues exposed some cases not covered by the accounting system" in OP, do you have any details of these cases?

Neither https://en.bitcoin.it/wiki/Help:Accounts_explained nor https://en.bitcoin.it/wiki/Transaction_Malleability mention the problems, and I've also failed to find mention of the problems by searching on Google.

**Comment by mikegogulski** [comment] 2016-03-02 20:59
Replying to @pstratem on https://github.com/bitcoin/bitcoin/issues/3816#issuecomment-167695545

I have several services which depend on the account feature. Yes, it's buggy, but I'm aware of the bugs and don't rely on it for things that would trigger the bugs.

If we're going back to labels, that's fine, but there should be a major release with labels as aliases for accounts before accounts disappear entirely.

Replying to @laanwj on https://github.com/bitcoin/bitcoin/issues/3816#issuecomment-37047766

* Deprecate the move RPC command and any account ledger usage
* Deprecate the use of the account argument in sendmany and sendfrom as well as getbalance
* Deprecate the following:
  * getreceivedbyaccount
  * listreceivedbyaccount

I need most of these capabilities. Can't they be retained and just operate on labels instead?

**Comment by benjyz** [comment] 2016-03-03 07:48
@mikegogulski Bitcoin is not a good accounting system in the following sense.

Account here should mean mapping human ID to Bitcoin ID in some way. Usually that involves some trust or custodian relationship, between account holder and custodian. The custodian holds money for the account holder. In Bitcoin usually there is no such relationship. Trusted third parties are avoided altogether. The account system as it existed is merely a labelling system. Just attaching some string to a key is trivial - that's not the problem of accounting. So what used to be "accounts" has nothing to do with accounts in the sense of somebody holding money for another person. That's what a bank account is, and one can debate whether Bitcoin web-wallets are like banks or not.

Bitcoin has some very limited facilities to manage trust - a combination of multi-sig and escrow e.g. But for many applications it is very complicated, so that in the last 3 years almost no progress has been made for advanced applications. It is related to the underlying economic model. 

There is a deeper reason nobody has implemented a proper layer to do accounting on top of Bitcoin - nobody in the Bitcoin (-core) project believes its necessary or interesting. I'd expect this to be the case in the future. Ironically Bitcoin (-core) favours scaling solutions which would involve a custodian relationship of some kind, and some members have founded a company which offer services and products in this area.

**Comment by mikegogulski** [comment] 2016-03-03 11:48
@benjyz Thanks for your reply.

You're absolutely right. Bitcoin Core's wallet isn't a good accounting system, nor should it attempt to be one. I fully agree. Anyone who needs a good accounting system as you describe *must* implement their own solution. There's no sense in thinking Core's developers should develop an interest in formal accounting :)

However, the functionality provided by accounts today, while broken from a perspective of "is it a good accounting system or not", has been in Core for a very long time. I've depended on it since 2011, when it was still labels instead of accounts, and, the way I'm using it, it's never let me down.

Check this out:
```
$ ls -l cron.php
-rw-r--r-- 1 mike mike 2154 Aug  5  2013 cron.php
$ grep 'c->' cron.php
    $arr = $c->listreceivedbyaddress(10, false);
      $c->sendtoaddress($destaddr, $residue);
      $c->setaccount($rcvd["address"], "");
      //$c->setlabel($rcvd["address"], "");
```

That's code from a service I've been running for five years, and that I haven't had to change in the past 2.5 years. And as you can see, it originally used labels, until they were replaced by "accounts".

The specific methods I need are:

* getnewaddress(label)
* setlabel(address)
* listreceivedbyaddress, with label information
* listlabels
* move(...)

If I can't have those, my I'll be forced into either staying with an old version of Core (never good, because CVEs) or expending a lot of effort implementing a database application that talks to the wallet in order to retain the functionality I've gotten from Core since time immemorial (ok, not that long, but still! :) ).

Is it too much to ask to retain remove these (renamed) wallet methods?

**Comment by benjyz** [comment] 2016-03-03 12:17
@mikegogulski if C is holding money for A, say 42 BTC, in terms of Bitcoin, that is equivalent with C owning 42 BTC. It was introduced after the 2009 release and was a mere afterthought to Bitcoin's operation. The word accounts and accounting is completely misleading. Accounts is a concept that comes from banking, and Bitcoin doesn't allow for banking. Bitcoin removed all trust entirely, and its very hard or impossible to build trust-relationships on top. If you hold money for others, in terms of Bitcoin's model you're doing it wrong. In particular matching human ID to money has another problem - traditional law and nation states see themselves as the watchdog of financial transactions. In terms of traditional law its not even clear that holding Bitcoin as money is "legal". Because if it were legal the question is why I can't pay my taxes in Bitcoin or send it to a bank.

There are better ways to do this with multi-sig, HD wallets, green-addresses, time-lock contracts, ColoredCoins, etc. I've been working on related problems for years, but don't expect "core" to understand any of these issues or cater to users. If that were the case we wouldn't have millions of people using Bitcoin in the "wrong" way via web-wallets and exchanges. And all of this doesn't even touch on the problem that Bitcoin was designed around users running nodes themselves.

**Comment by laanwj** [comment] 2016-03-03 13:13
> @luke-jr it's now been (nearly) a full year since the rpc calls were marked as DEPRECATED
> I propose that the rpc calls be disabled in the release after 0.12.0 unless a configuration option is set
> Then removed entirely in the next release (major or minor).

At some point this will have to be done, but I don't think there is a good migration path yet for users of the account system, so this feature pretty much exists in limbo for now.

> There is a deeper reason nobody has implemented a proper layer to do accounting on top of Bitcoin - nobody in the Bitcoin (-core) project believes its necessary or interesting

I doubt you will find anyone that disagrees that accounting is *necessary*.

But yes AFAIK no one is working on an open source external replacement. There are tons of proprietary implementations, which are specific to how a certain company does accounting.

**Comment by mikegogulski** [comment] 2016-03-04 04:24
@benjyz I know all that. Your comment doesn't address anything I said. Not helpful.

**Comment by dooglus** [comment] 2016-03-05 22:35
@mikegogulski I find myself in the same place as you. I rely on:

* `getaddressesbyaccount` and `getaccountaddress` to provide deposit addresses for users
* `listaccounts` and `move` to detect new deposits (using `move` to move processed deposits to a non-user account, so they don't show up again next time I run `listaccounts`)
* `getbalance` to check whether the user has any deposits with less than 6 confirmations

These methods appear to work very well for me. I'm aware that the accounting system is confusing and badly named, but it provides functionality which is hard to find elsewhere.

I wouldn't care if the word 'account' was replaced by 'label' in all the RPC calls. I would mind if the RPC calls were removed.

**Comment by kladivo** [comment] 2016-03-06 23:11
@dooglus: Nice to see you here. Thanks for the input.

I'm doing basically the same thing with `listaccounts` and `move`, I reckon. I would be very happy to replace my use of those commands with some capability that would cause the wallet to emit a formatted HTTPS GET request every time the wallet balance changes -- though I suspect that making the wallet both an RPC producer as well as consumer is too much to ask for.

**Comment by dooglus** [comment] 2016-03-07 02:09
@kladivo I like that `listaccounts` lets me specify a number of confirmations:

    List account balances for 6 or more confirmations
    > bitcoin-cli listaccounts 6

I don't want to know every time the balance changes. I don't want to know about a deposit at all until it has 6 confirmations. Until then it's possible for the number of confirmations to go up and down as reorgs happen. I like how I don't have to care about that if I use `listaccounts` - it hides all that complexity from me. I thought it handled maleability too, but @jgarzik's cryptic comment in the OP of this thread suggests it might not. I [asked for further details](https://github.com/bitcoin/bitcoin/issues/3816#issuecomment-167766437) but got no response so I'm not sure if there's really an outstanding issue or not.

**Comment by Bereiche54** [comment] 2016-03-15 19:48
Accounting, Financial, Tax
Accounting, financial and tax for the rest of us
 
 
Browse:Home2008SeptemberBolt-On Software Within ERP System and Enterprise Software
ACCOUNTINGACCOUNTING TECH-UPDATETECH-TIPSTOOLS-SPREADSHEET
BOLT-ON SOFTWARE WITHIN ERP SYSTEM AND ENTERPRISE SOFTWARE
   
This is the name given to software that’s “outside of the main enterprise software suite or legacy system”, typically coming from a third-party software supplier. Companies usually add bolt-on to the main system to perform specific functions because the existing Enterprise Software or legacy systems don’t do them well or don’t do them at all. Many bolt-on software packages are considered “best of breed” because they are seen as so superior to their counterpart modules within the Enterprise System suite.


 
Davenport, in his book on Enterprise Systems II identifies supply chain support tools for demand and supply planning, plant scheduling, and logistics systems as being primary candidates for bolt-on:

Given the existence of best-of-breed packaged solutions in so many of these areas, the favored approach for most firms has been to go with a major vendor for core ES and then bolt on supply chain software developed by multiple other vendors.
 

Downsides to bolt-on include a degradation in the ability of enterprise system to integrate information and process, the need for additional files not linked to the central database, the effort required to integrate the bolt-on, and a maintenance task over time as changes occur to the enterprise system and/or to the bolt-on. These negatives are not insignificant, and we feel that bolt-on should be used judiciously and only when clearly needed.

The good news is that bolt-on typically do provide users with a superior tool (If not, why use a bolt-on?). Sometimes these packages are brought forward from the legacy environment and get bolted onto the new enterprise software, because it’s so obviously the right thing to do for the users. More on this in a bit…

When we talk about pockets of excellence, most bolt-on we’ve seen in ERP environments come in 3 (three) typical categories:

Resource planning enablers – This is the type of thing we’ve just been talking about: getting outside software (for Master Scheduling, MRP, etc.) and plugging it in to your existing system.
Front-end/back end – These are applications that focus on the front end of the resource planning process (sales forecasting, Sales & Operations Planning, vendor-managed inventories) or back end, such as finite scheduling packages for the plants. Bolt-on generally cause the least difficulty when they’re at the front or the back. For example, there are several excellent forecasting packages on the market, which do a far better job than most ES vendor’s offerings. For companies where forecasting is a problem—and there are more than a few of these—a forecasting bolt-on might make a lot of sense.
Supply chain optimization/advanced planning systems – This category of packages attempts a better fine-tuning of the detailed demand–supply relationships addressed by master scheduling, Material Requirements Planning, and so forth. When used properly, these packages typically can do a superior job. Through advanced logic and strong simulation capabilities, they can give superior recommendations to demand managers, planners, and schedulers regarding the best fit between customer demands and resource utilization.
 

In summary, bolt-on can be quite valuable, but they come at a cost—not only in dollars of course, but in loss of integration and increase in maintenance. Using them indiscriminately will cause more trouble than they’re worth. Using them on a very specific basis, to do a superior job in one or another given function, is frequently the way to go.

 

Selecting Bolt-on Software For ERP Company

Here are some thoughts about selecting bolt-on software, whether it is a resource planning enabler, a front-end or back-end module, or a supply chain optimization package (These may also have relevance in selecting an ES for those of you who’ll be doing a combined ERP/ES project) Here goes:

Don’t be premature – Some companies’ first exposure to a given set of software is through the software salesman who sells them the package. Often, these people regret having made the purchase after they have gone to early education and learned about ERP and its better tools. The right way is to learn about ERP first, and get the software shortly after the company has made an informed decision and commitment to ERP.
Don’t procrastinate – This isn’t as contradictory as it sounds. Don’t make the mistake of trying to find the perfect software package. That’s like searching for the Holy Grail or the perfect wave. There is no best software package. The correct approach, after learning about ERP and deciding to do it, is to decide which bolt-on packages, if any, you’ll need for phase I. Go after those and get a good workable set of software. Then repeat the process for phase II. It’s important to move through these selection phases with deliberate haste, so the company can get on with implementing ERP and getting paybacks.
Don’t pioneer. People who get too far out in front, pioneers, often get arrows in their backs. This certainly applies to software for ERP. Why buy untested, unproven software? You have enough change underway with people systems to worry about software glitches. Insist on seeing the package working in a company that operates at a Class A or high Class B level. If the prospective software supplier can’t name a Class A or B user of their product, we recommend that you look elsewhere.
Save the pockets of excellence. Many companies do some things very well. An example of this would be a company with an excellent shop floor or work unit control system, but little else. The computer part of this system may have been programmed in-house, and may contain some excellent features for the users. Let’s assume that the supply chain software package selected by this company contains a shop floor control module that’s workable, but not as good as the current system. This company should not blindly replace its superior system with the new, inferior one. Save the good stuff. Don’t throw the baby out with the bath water.


TAGS:
ACCOUNTING SOFTWAREACCOUNTING TECH-UPDATEBOLT-ON SOFTWAREBOLT-ON SOFTWARE SELECTIONBOLT-ON SOFTWARE WITHIN ERP SYSTEM AND ENTERISE SOFTWARENTERPRISE SOFTWAREERPES
NEXT POST
COST/BENEFIT ANALYSIS Of ERP Implementation
PREVIOUS POST
Enterprise Software Selection, Configuration and Enhancement, On Going Support
 Lie Dharma Putra
About Author
Lie Dharma Putra

Putra is a CPA. His last position, in the corporate world, was a controller for a corporation in Costa Mesa, CA. After spending 15 years as a nine-to-five employee, he decided to serve more companies, families and even individuals, as a trusted business advisor. He blogs about accounting, finance and tax, during his spare time, and helps accounting students (around the globe) to understand the subject matter easier , faster. Follow him on twitter @LieDharmaPutra or add him to your circle at Google Plus Lie+
 Twitter
 Facebook
 Google
RELATED POSTS

What Constitutes Accounting Software?
Useful Business Forms, Calculators, Tools and Templates
Accounting Equation [to] Accounts Receivable Turnover
2 COMMENTS

ROSE
Feb 21, 2009 at 4:33 am	— Reply
who are those companies that supply bolt on software??

PUTRA
Feb 21, 2009 at 6:25 am	— Reply
Hi Rose,

They are plenty in the internet marketplace. you can browse them with a keyphrase: “bolt-on softwares” or “bolt-on softwares for ERP” for more targeted search result. Though the challenge is not where to find them [as I said, they are plenty], but “which bolt-on software is best suit your need”. A more worth considering approach [although it could cost you more] is to call and ask a professional developer to make it one for you.

Have a good weekend Rose!
Leave a reply

Your email address will not be published. Required fields are marked *




Name (required)


E-Mail (required)


Website

SUBMIT COMMENT


Search
 

 
Are you looking for easy accounting tutorial? Established since 2007, Accounting-Financial-Tax.com hosts more than 1300 articles (still growing), and has helped millions accounting student, teacher, junior accountants and small business owners, worldwide.
Advertise Here
ACCOUNTING PAPER
MOST POPULAR

48
Accounting For Lease: Operating and Capital Lease
47
Accounting For Property Plant And Equipment [IAS 16]
36
How To Calculate And Record Depreciation [of Fixed Asset]
36
Prior Period Adjustment [With Case Examples]
33
Deferred Income Taxes [Deferred Tax Liabilities]

**Comment by BamaStangGuy** [comment] 2016-05-19 09:56
We also make heavy use of the accounts system and are not looking forward to our options that are out there right now. Going to be expensive and time consuming to move to a MySQL Bitcoin bridge to handle this.

**Comment by jtimon** [comment] 2016-05-20 11:52
Maybe documenting a more sane alternative for the current users would be useful before removing the feature?
If they don't like that, they can always maintain their own fork that restores the old accounting system, but we really should stop maintaining this feature in master.

**Comment by BamaStangGuy** [comment] 2016-05-20 23:50
We are going to start working on our own PHP/MySQL method of replacing the account feature but that isn't going to happen overnight.

**Comment by luke-jr** [comment] 2016-05-21 03:40
Nobody expected you to do anything overnight. This has been publicly on the table for over 2 years now - that's plenty of time. Furthermore, nobody can force you to upgrade your wallet once accounting is in fact removed, so you're not really being rushed to do it "overnight" in the current state either.

**Comment by BamaStangGuy** [comment] 2016-05-21 03:48
Sorry, but the documentation we used to build our site mentioned absolutely no where that this was being considered for removal much less just deprecated. The only reason I found out about this is because I was researching the negative balance issue. 

Where would you go to find information about bitcoind and bitcoin-cli and see that this was being deprecated?

**Comment by luke-jr** [comment] 2016-05-21 03:52
"Deprecated" implies "being considered for removal"... (also, the negative balance thing is by design a feature of accounting, not an issue - so if it comes as a surprise I wonder on the reliability of whatever docs you used)

The accounting RPC methods have been marked in bitcoind's internal documentation (bitcoin-cli help <command>) for a number of releases now, and were mentioned as such in the release notes for at least the first release deprecating them.

**Comment by avatarscape** [comment] 2017-03-05 04:46
Sorry to gravedig this issue. I've noticed that all of the accounting features have been marked as deprecated and marked for removal; Personally I'm fine with many of them disappearing such as SendFrom, GetBalance etc as I can implement these myself when they're eventually removed.

The thing which concerns me is that, short of storing _every single generated address_ in my own database and mapping it against an account ID, I won't be able to determine when a payment has been sent to one of the generated addresses. I've read that the label feature (I assume the same one that's present in the Receive tab of BitcoinQt) could be the replacement; is there any update on this? If so what RPC functions would be updated to support the label feature?

**Comment by pstratem** [comment] 2017-03-05 05:16
> storing every single generated address in my own database and mapping it against an account ID

You should be doing exactly that. (invoice id more correctly, but close enough probably).

**Comment by avatarscape** [comment] 2017-03-05 05:46
> You should be doing exactly that. (invoice id more correctly, but close enough probably).

Doing BIP32 key generation on my application itself now so that I can keep the application database backup size minimal, then just adding the generated receive addresses as watch addresses in Bitcoin Core. 

Just wondering, how many public keys can the bitcoin core client watch without falling to pieces? To my understanding the biggest scalability "hit" is when a new block is received.

**Comment by laanwj** [comment] 2017-03-05 10:06
> is there any update on this? If so what RPC functions would be updated to support the label feature?

Yes, see here: https://github.com/bitcoin/bitcoin/pull/7729

**Comment by gusarov** [comment] 2017-10-14 21:19
For new software I'm not comfortable to use anything deprecated, but there is still nothing related to labels in 0.14.2
Am I right that the only proper way for today is just 'getnewaddress' without parameter and saving this to my db for the user that is associated with this address?

**Comment by jnewbery** [comment] 2018-04-11 19:11
Suggest we close this since it's very old and unwieldly. This issue contains useful historic context, but concrete actions to remove the 'account' API can be tracked in #12952.

**Closed** 2018-04-11 19:18 UTC
Labels: Brainstorming, Wallet

**Comment by int03h** [comment] 2018-04-11 19:36
Yeah. I think much water has flowed under this bridge.  I see from #12952 it's still not deprecated, but at least the intent to deprecate is formally stated.  New implementations will be at your own perl. Good enough for me.
