### ISSUE TITLE
Block directory cannot be a "junction" on windows

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#6495] opened 2015-07-30 21:00 UTC
In Windows, bitcoin-qt fails when the "blocks" directory (or any other directories, for that matter) is a junction to a directory. It fails to detect that it exists, tries to create it, and the create fails.

**Comment by dcousens** [comment] 2015-07-31 05:23
On Linux I also saw odd behaviour,  if the `datadir` doesn't exist,  it dumps all files in the directory above (chainstate, etc) then exits.

**Comment by laanwj** [comment] 2015-07-31 14:21
Non-support for junctions on windows is a known issue. For some reason one cannot just treat them as directories like Unix symlinks.

**Comment by casey** [comment] 2015-07-31 15:07
@dcousens I couldn't reproduce the behavior that you mentioned. I created /tmp/foo, and then ran 'bitcoin-qt -datadir=/tmp/foo/bar', afterwards /tmp/foo was still empty. Can you come up with steps to reproduce, and then open another issue? (since this one seems to be unrelated)

**Comment by MarcoFalke** [comment] 2020-04-27 00:27
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.

**Closed by MarcoFalke** 2020-04-27 00:27 UTC
Labels: Block storage, Windows
