### ISSUE TITLE
Integrate Child Pays For Parent into the fee calculator

### ISSUE THREAD

**Issue by praxeology-guy** [bitcoin/bitcoin#9864] opened 2017-02-26 07:42 UTC
Add "Fee also pays for unconfirmed parents" option.  Maybe only show it if coin control is enabled... but I sure hate disappearing UI so I am not going to recommend that.

**Comment by Sjors** [comment] 2018-03-16 15:14
Concept ACK

**Comment by MarcoFalke** [comment] 2020-05-08 19:24
Duplicate of #9645?

**Closed by MarcoFalke** 2020-05-08 19:24 UTC
Labels: GUI, TX fees and policy
