### ISSUE TITLE
Bitcoin Core 0.10 freezing and disconnecting during synchronization

### ISSUE THREAD

**Issue by MrKrzYch00** [bitcoin/bitcoin#5851] opened 2015-03-03 11:20 UTC
Background:
- Running Bitcoin Core 0.10 x64 on Windows 8.1
- txindex is enabled
- first synchronization

Problem:
Bitcoin Core 0.10 is constantly freezing during synchronization, especially on newer blocks losing connections and making RPC unresponsive. This happens when Bitcoin Core uses more than one thread to analyse downloaded blocks (occurs more often when the height is higher - uses more threads then).

Expencted Results:
GUI and RPC server should still response to user inputs or at least should not lose connections to other Bitcoin peers.

**Comment by laanwj** [comment] 2015-05-18 09:00
I've also noticed this. There seems to be heavy lock contention during some of the synchronization phases. This causes e.g. RPC to react slowly.

**Comment by laanwj** [comment] 2015-05-29 06:56
Made a little progress on finding out why the GUI hangs during intensive catch-up phases. Indeed, `cs_main` is held for a longer time. The GUI does not wait on `cs_main` during normal operation, however when it receives a new transaction

    2015-05-29 06:48:46 AddToWallet xxx  new

It will try to get the transaction information from the wallet in `qt/transactiontablemodel.cpp:130`, which takes both a `cs_main` and wallet lock. It can stay stuck there for minutes at a time. A possible solution is to copy the relevant data in the notification function.

This is fighting symptoms, however, but will lead to a more responsive UI. The root cause would be mitigated by changing `ActivateBestChain`/`ActivateBestChainStep`/`ConnectTip` logic to release the cs_main lock between attaching blocks.

**Comment by sipa** [comment] 2015-05-29 14:38
ActivateBestChain releases cs_main between blocks, except during a reorg,
to avoid exposing a worse state than before.

**Comment by jonasschnelli** [comment] 2015-07-01 06:52
I think the `cs_main` LOCK at `qt/transactiontablemodel.cpp:130` can be avoided.

While re-writing most parts of the `CWalletTx` i think the problematic points are `CWalletTx::GetCredit()` mainly the `GetBlocksToMaturity()` which needs the chainActive (lock on cs_main) to get the current height. But only for coinbase wtxs.

The rest of `decomposeTransaction()` needs no cs_main locking IMO.

**Comment by sipa** [comment] 2015-07-01 12:41
Probably makes sense to store a copy of the best chain's tip CBlockIndex* pointer in the CWallet object, and update it through a signal mechanism. Credit/confirmation querying can then use the cached version instead of needing a lock every time

**Comment by jonasschnelli** [comment] 2015-07-01 13:06
Yes. This would be a good way.
The new wallet does interact over a extra interface with main/mempool (https://github.com/jonasschnelli/bitcoin/blob/2015/05/corewallet/src/corewallet/coreinterface.cpp). This would be a starting point for optimizing locks and later separation into a own process.

**Comment by btcdrak** [comment] 2015-07-08 19:46
@MrKrzYch00 could you test if the problem still exists in the `0.11`?

**Comment by MrKrzYch00** [comment] 2015-07-08 20:58
I will give it a try after I build myself newest commit. My latest build bases on d0a10c1959176eb40c0ec47a56de00820c59066d , which, I'm pretty sure, was still slowing down RPC (when I was 15h behind and run my PHP script to manually connect to selected IPs, after 3rd connection it started to response very sluggish). However to confirm loosing connections I would need to re-download block chain (I think?).

Also to be 100% sure I would need to note that I have one small error when building with gcc 4.9.4 (20150630 - prerelease; windows mingw) on /leveldb/util/env_win.cc file which tells me that _beginthread is undefined until I compile the file manually while omitting D_REENTRANT. Not sure what causes it and if it could have any impact on tests being correct... btw. my build is x64, uses Ofast and AVX instruction set tuning (including all dependencies, with one exception being O3 due to Ofast failing).

**Comment by MrKrzYch00** [comment] 2015-07-17 18:07
![bitcoin_core_first_synchronisation](https://cloud.githubusercontent.com/assets/11292594/8753863/51225d52-2cbf-11e5-935c-63d7ed4ba6b5.png)

^ this is what happens when Bitcoin Core is checking blocks, the ping times raise a lot. My speed is ~1.5MB/s download and ~70KB/s upload (bytes).

I will provide more detailed text log with php script I'm running to get current height, num of connections and time it took to get reply with this data from bitcoin core during first synchronization.

**Comment by MrKrzYch00** [comment] 2015-07-18 14:58
Full log at: http://4my.eu/first_synchronization_log.txt
PHP-CLI script run for testing: http://4my.eu/bitcoin_core_test.txt

Using 2GB db cache, build with: Ofast, AVX and core i7 tuning, without debug.
Running on core i7-3630QM 2.7Ghz, 8GB RAM. ~1.5MB/s download, ~70KB/s upload.

Started with 38 connections, dropped to 14 soon after (guess to network lag) and finally ended with 8. So I think it's not that bad, however, response times from RPC were exceeding 60s sometimes - two commands total as seen in php script.

**Comment by 2083236893** [comment] 2015-07-21 15:03
@laanwj That also happens if you load an old wallet file and trigger a rescan, it will take longer than the ping message timeout and on completion all peers will have dropped you. Not an issue under any circumstance but it might explain why I've seen peers on the network not responding to messages occasionally.

**Comment by jonasschnelli** [comment] 2015-11-27 10:37
Partially addresses in #7112. Still, AddToWallet needs better lock handling.

**Comment by Giszmo** [comment] 2015-12-02 20:08
Running bitcoin-qt v0.11.2 I run into "Activating best chain…" with high CPU load for 20 minutes on slow machine.

Not sure if relevant: I wanted to "quickly" do a transaction but 0.11.1 crashed, making a re-index necessary. I downloaded 0.11.2 meanwhile, orderly interrupted the re-index to let the latest version take over after 10% progress. It then ran into "system shutting down due to CPU@100°C" or so. Now all I get is indefinite(?) "Activating best chain". I did the kill -9 and started bitcoin-qt, only to run into this again.

Also I understood that incoming transaction trigger this lock? I switched off wifi of that machine, to not get those.

**Comment by jonasschnelli** [comment] 2015-12-03 10:08
@Giszmo: mind re-testing this issue after https://github.com/bitcoin/bitcoin/pull/7112 has been merged? (compile or https://bitcoin.jonasschnelli.ch/nightlybuilds)

**Comment by Giszmo** [comment] 2015-12-03 14:31
@jonasschnelli sorry but I'd be glad if my primary wallet gave me back my access to my funds asap. Syncing since yesterday and without a clue why it had to re-download 8GB so far. 50% to go.

If 11.3 has the fix and you can tell me how to test, I could do that with a backup or something but else, with this machine I'm a bit paranoid to get only signed software near it.

**Comment by jonasschnelli** [comment] 2015-12-03 14:56
@Giszmo: Sure. That is wise (and I would do the same). Maybe try compile bitcoin-core by yourself? It's not that hard (check the docs/ section).

**Comment by laanwj** [comment] 2015-12-03 15:01
> Running bitcoin-qt v0.11.2 I run into "Activating best chain…" with high CPU load for 20 minutes on slow machine.

"Activating best chain..." can take a long time in some cases, see also #7038. It processes the backlog of  blocks. It should always finish eventually, though. Kill -9 will only set back progress.

I don't think #7112 helps here. Sure, it makes GUI-core interaction somewhat more fluid, but high CPU during initial sync is normal (lot of verification work - with `-par=X` you can change the number of verification threads, reduce the load at expense of speed).

**Comment by rebroad** [comment] 2016-11-24 12:47
I frequently see my node being disconnected from all peers during IBD as ProcessMessages() doesn't get a chance to run for over 20 minutes frequently.

**Comment by laanwj** [comment] 2016-11-24 13:10
Yes, that's still the same issue.
Though the cs_main lock does get released, this does not guarantee other processes will be able to get it (or at least, often enough to make useful progress).

**Closed** 2018-03-07 19:33 UTC
Labels: Bug, GUI, P2P, UTXO Db and Indexes
