### ISSUE TITLE
Comparison tool successor?

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#4545] opened 2014-07-16 17:16 UTC
The current comparison tool tests network behavior that is too specific - in particular, it seems hard to adapt it to headers-first (which in some cases does not fetch blocks in the same order, e.g. because it already knows that it's invalid through the header, even though at every point it should have the same best block) - correct me if I'm wrong, @TheBlueMatt.

One of the reasons is that the current comparison both incorporates the scenario of comparisons to run, and the logic to compare it to (BitcoinJ full node code). This makes it hard to adapt.

I propose writing a tool that does nothing but implement a testing scenario, and run it against 2 bitcoind's in parallel: an old trusted version, and the new version to be tested, and compares whether at every point in time (after synchronizing through a ping/ping) they agree on the best chain.

This could be as simple as a python node with an associated block database and block header tree, that can answer getdata/getheaders/getblocks, and runs through a scripted scenario, but doesn't do any validation itself.

**Comment by laanwj** [comment] 2015-12-08 12:35
Motivated by discussion in #7093:
Now that #5981 is merged we have our own internal P2P testing framework.
How is it along to replacing the blocktester?
It is putting up a maintenance bottleneck.

**Comment by droark** [comment] 2016-04-09 00:38
Hello. Just FYI, I ended up poking around the Core code recently and saw the comparison tool. While poking around and trying to troubleshoot some stuff, I discovered that [comparison tool support seems to have been dropped from the forthcoming v0.14](https://github.com/bitcoinj/bitcoinj/commit/1eaf05cacf35ebdf8e716eb84f0d5d0c051b3398). For that matter, v0.13.6 doesn't work without a [one-line fix](https://github.com/bitcoinj/bitcoinj/issues/1236#issuecomment-202777012), and even then, I've seen an intermittent DB error that I can't reproduce right now.

Anyway, I just wanted to add that here in case this is still on anybody's radar. My Java experience is limited, and it sounds like nobody's really happy with the tool anyway, so I'm really not the right person to tackle this project. Besides, I don't think there will be a v0.13.7 release, so as things stand, the tool is completely broken.

**Comment by laanwj** [comment] 2016-04-09 07:32
Thanks for the information @droark.
IMO, we should just drop it too.

**Comment by laanwj** [comment] 2016-04-14 13:21
Seems I'll just have to set a deadline: I'm going to remove use of the unmaintained java-based comparison framework after the 0.13 branch-off (projected  2016-06-06, see #7679). I hope the Python framework will be a full replacement by then, but as this is holding up progress in other areas, that will not affect the decision.

**Comment by MarcoFalke** [comment] 2016-05-01 09:53
Does anyone know at what point (line in code) travis fetches the bitcoinj.jar? Or is it somewhere cached?

Also, did anyone check if the test actually test something? I.e. fail on assertion errors, etc.?

If they don't and no one knows how to fix, we can remove them right now. Because the only thing they'd be doing then, is slowing down travis.

**Comment by sipa** [comment] 2016-05-01 09:56
I believe the last update to the comparison tool was for headers-first
synchronization. We did a simple test back then, opening 4 PRs that
intentionally introduced consensus bugs, and the tool indeed found them.

**Comment by MarcoFalke** [comment] 2016-05-01 10:25
Ah, found them: https://github.com/bitcoin/bitcoin/pull/5006#issuecomment-57386200

**Comment by MarcoFalke** [comment] 2016-06-15 14:09
Changed milestone to 0.14.

**Comment by MarcoFalke** [comment] 2016-09-27 19:28
#8227 should be revived before 0.14.0, other than this, I think the issue can be closed.

**Closed by MarcoFalke** 2016-09-27 19:28 UTC
Labels: Brainstorming, Tests
