### ISSUE TITLE
Why is build_msvc separate from the doc folder? 

### ISSUE THREAD

**Issue by Jhingun1** [bitcoin/bitcoin#18773] opened 2020-04-26 14:09 UTC
Is your feature request related to a problem? Please describe.

As a new contributor, I was confused thinking that the build_msvc folder was the only source of build setup instructions.

Describe the solution you'd like

I think that moving the build_msvc README.md and related file set to the doc folder would make the setup process much clearer with all the options in one place.

Describe alternatives you've considered

Instead of moving build_msvc, retitling the doc folder to make it visually explicit that it contains build instructions would also be effective.

Additional context

**Comment by hebasto** [comment] 2020-04-26 14:23
Is it a duplicate of #18658?

**Closed** 2020-04-26 14:35 UTC
Labels: Feature
