### ISSUE TITLE
BIP155 CJDNS address with length 187 (should be 16)

### ISSUE THREAD

**Issue by AlonsoJara** [bitcoin/bitcoin#25874] opened 2022-08-19 15:04 UTC
Bitcoin Status Error. I receive the following log: 
```bash
022-08-18T17:27:38Z Shutdown: done
2022-08-18T17:27:38Z scheduler thread exit
2022-08-18T17:27:38Z Shutdown: In progress...
2022-08-18T17:27:38Z Error: Invalid or corrupt peers.dat (BIP155 CJDNS address with length 187 (should be 16): iostream error). If you believe this is a bug, please report it to https://github.com/bitcoin/bitcoin/issues. As a workaround, you can move the file ("/home/bitcoin/.bitcoin/peers.dat") out of the way (rename, move, or delete) to have a new one created on the next start.
```

**Comment by fanquake** [comment] 2022-08-19 15:21
cc @vasild @jonatack

**Comment by MarcoFalke** [comment] 2022-08-19 15:36
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?

**Comment by jonatack** [comment] 2022-08-19 17:41
Support for CJDNS was merged in November 2021 and released in Bitcoin Core v23 (the most recent release), and I don't recall any (expected) changes to our CJDNS support since the v23 release. 

`BIP155 CJDNS address with length <x> (should be <y>)` is an error you would see if your node deserializes an invalid CJDNS address from a peer.

However, `Invalid or corrupt peers.dat (<reason>)` would be invoked at bitcoind startup when loading the addresses from peers.dat, not at shutdown.

I run a node for testing purposes that usually serves all our networks (clearnet, tor, i2p, and cjdns) and always has a few CJDNS peer connections but haven't yet encountered this error in the wild.

- I presume you saw this on mainnet? Apart from this, were you seeing valid connections with CJDNS peers? (you can check while your node is running using `bitcoin-cli -netinfo 4` or  `bitcoin-cli getpeerinfo`).

- Was it with the v23 release (binary or built from source?), or current master, or?

- Which version of CJDNS are you running (`cjdns --version`)?

**Comment by mzumsande** [comment] 2022-08-19 18:04
> However, Invalid or corrupt peers.dat (<reason>) would be invoked at bitcoind startup when loading the addresses from peers.dat, not at shutdown.

That's probably what happened here, the shutdown was caused by an invalid peers.dat at startup, resulting in an early shutdown - it's just that if multiple log messages have the exact same timestamp ("2022-08-18T17:27:38Z"), the order can be mixed up.

**Comment by MarcoFalke** [comment] 2022-08-19 18:13
> the order can be mixed up

Can you add a reference to your claim? Locally I get the right order:

```
2022-08-19T18:11:32Z init message: Loading P2P addresses…
2022-08-19T18:11:32Z Error: Invalid or corrupt peers.dat ([...]
2022-08-19T18:11:43Z Shutdown: In progress...
2022-08-19T18:11:43Z scheduler thread exit
2022-08-19T18:11:43Z Shutdown: done

**Comment by mzumsande** [comment] 2022-08-19 18:23
> Can you add a reference to your claim? 

I'm pretty sure I encountered this phenomenon on rare occasions in the past when looking at logs, but I don't have any reference unfortunately, so this may also be bad memory/an oversight. In your example, there are two different timestamps (2022-08-19T18:11:32Z and 2022-08-19T18:11:43Z).

**Comment by jonatack** [comment] 2022-08-19 18:30
Hm, it shouldn't be possible for a peer to corrupt the peers.dat by sending us an invalid address (which would be a bug). Maybe a disk corruption error or the node didn't shutdown properly?

**Comment by MarcoFalke** [comment] 2022-08-19 18:31
> there are two different timestamps 

Thanks, edited.

For reference, logging has a lock, which is held until the timestamped log message is fully written and flushed. See https://github.com/bitcoin/bitcoin/blob/6b56873b41974ced7aad87a4b38abe360c34eed3/src/logging.cpp#L371

Obviously if this may no longer hold if the logs are post-processed outside of vanilla Bitcoin Core.

**Comment by MarcoFalke** [comment] 2022-08-20 06:44
Closing for now due to lack of details. Can be reopened once they are there.

**Closed by MarcoFalke** 2022-08-20 06:44 UTC
Labels: P2P, Waiting for author
