### ISSUE TITLE
shutdown throws lock error

### ISSUE THREAD

**Issue by jgarzik** [bitcoin/bitcoin#2777] opened 2013-06-19 15:51 UTC
During a short run (start, network sync, stop) of bitcoind on Linux Ubuntu 13, this was thrown on the console,
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost::lock_error
```

And this is the last few lines of the debug log,
```
2013-06-19 15:47:55 trying connection 190.2.27.221:8333 lastseen=4.7hrs
2013-06-19 15:47:55 CTxMemPool::accept() : accepted 254d03e64db83bb0ad17e8435f4c5a7932028305789c30642fafb52f6ca20b2a (poolsz 30)
2013-06-19 15:47:57 received getdata (2 invsz)
2013-06-19 15:47:59 ThreadRPCServer method=stop
2013-06-19 15:47:59 addcon thread interrupt
2013-06-19 15:47:59 dumpaddr thread stop
2013-06-19 15:47:59 msghand thread interrupt
2013-06-19 15:47:59 Flush(false)
2013-06-19 15:47:59 wallet.dat refcount=0
2013-06-19 15:47:59 wallet.dat checkpoint
2013-06-19 15:47:59 wallet.dat detach
2013-06-19 15:47:59 wallet.dat closed
2013-06-19 15:47:59 DBFlush(false) ended              10ms
2013-06-19 15:47:59 StopNode()
2013-06-19 15:47:59 net thread interrupt
2013-06-19 15:47:59 Flushed 14271 addresses to peers.dat  35ms
2013-06-19 15:47:59 Committing 33219 changed transactions to coin database...
2013-06-19 15:48:00 Flush(true)
2013-06-19 15:48:00 wallet.dat refcount=0
2013-06-19 15:48:00 wallet.dat checkpoint
2013-06-19 15:48:00 wallet.dat detach
2013-06-19 15:48:00 wallet.dat closed
2013-06-19 15:48:00 DBFlush(true) ended               7ms
2013-06-19 15:48:00 connection timeout
```

The connection timeout following DBFlush seems unusual.

**Comment by laanwj** [comment] 2015-05-16 07:40
This does not have enough information for debugging, and I never managed to reproduce this. Due to frequent changes in the shutdown/init sequence I'm also unsure if it's still relevant, so closing this issue.

**Closed by laanwj** 2015-05-16 07:40 UTC
Labels: Bug, Priority Low
