### ISSUE TITLE
Sync pruned blockchain

### ISSUE THREAD

**Issue by XfedeX** [bitcoin/bitcoin#24229] opened 2022-02-01 15:39 UTC
**Is your feature request related to a problem? Please describe.**
Syncing Bitcoin can take tens or hundreds of hours. This is annoying especially if you are a developer and want to use BitcoinCore's RPC API.

**Describe the solution you'd like**
Adding a "sync pruned blocks" feature would be cool. It would for example allow you to only download the part of the blockchain you actually need. The cryptocurrency Monero has already got this feature.

**Comment by MarcoFalke** [comment] 2022-02-01 15:42
Duplicate of #15606 ?

**Closed by MarcoFalke** 2022-02-01 15:42 UTC
Labels: Feature
