### ISSUE TITLE
make deploy on Mac error

### ISSUE THREAD

**Issue by s-matthew-english** [bitcoin/bitcoin#9411] opened 2016-12-23 03:49 UTC
I ran 'make deploy' 

and I got the following error:

/Library/Developer/CommandLineTools/usr/bin/make -C src qt/bitcoin-qt
make[2]: `libsecp256k1.la' is up to date.
/usr/bin/python2.7 ./contrib/macdeploy/macdeployqtplus Bitcoin-Qt.app -add-qt-tr da,de,es,hu,ru,uk,zh_CN,zh_TW -translations-dir= -dmg -fancy ./contrib/macdeploy/fancy.plist -verbose 2 -volname Bitcoin-Core
Error: Could not find background picture at "background.tiff" or "./contrib/macdeploy/background.tiff"
make: *** [Bitcoin-Core.dmg] Error 1

**Comment by fanquake** [comment] 2016-12-23 06:10
Duplicate of #8120

**Closed by fanquake** 2016-12-23 06:10 UTC

**Comment by MarcoFalke** [comment] 2016-12-23 13:35
@s-matthew-english You could try #9412 to see if it fixes your problem.
