### ISSUE TITLE
(Ubuntu xenial armhf) fatal error in "psbt_updater_test": memory access violation at address: 0xd503e0e4: no mapping at fault address

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#15062] opened 2018-12-30 05:52 UTC
Triggered by Ubuntu PPA building for xenial distro / armhf platform.

https://launchpadlibrarian.net/404142197/buildlog_ubuntu-xenial-armhf.bitcoin_0.17.1-xenial1_BUILDING.txt.gz

**Comment by MarcoFalke** [comment] 2019-05-23 20:21
Could this be caused by the gcc compiler bug?

**Comment by MarcoFalke** [comment] 2019-05-23 20:21
Can you reproduce? Is this fixed on master?

**Closed** 2020-04-26 15:19 UTC
Labels: Linux/Unix

**Comment by MarcoFalke** [comment] 2020-05-11 22:34
For reference, I can reproduce, but I don't have any tools armhf gdb or valgrind to debug this. I suspect the issue is in bdb or the cross compiler.
