### ISSUE TITLE
Make on windows not working

### ISSUE THREAD

**Issue by MattyAB** [bitcoin/bitcoin#10856] opened 2017-07-17 20:51 UTC
1. Install Ubuntu for Windows [as stated in this post](https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md)
2. Run
`~sudo apt-get install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl
~sudo apt-get install g++-mingw-w64-x86-64 mingw-w64-x86-64-dev
~cd depends
~make HOST=x86_64-w64-mingw32`
3. At the last command, it gives an error.

### Expected behaviour
The make command functioning properly

### Actual behaviour
The make throws an error.

### Screenshots.
![image](https://user-images.githubusercontent.com/14000942/28289094-44c60fda-6b39-11e7-82c7-e892b641d01c.png)

### What version of bitcoin-core are you using?
Commit no. 0b01935

### Machine specs:
PC:
- OS: Windows 10
- CPU: i7 6700
- RAM: 6GB
- SSD storing OS: 250GB
- HDD storing clone of this repo: 3TB

Laptop:
- OS: Windows 10
- CPU: i5 3210M
- RAM: 6GB
- Disk size: 250GB
- Disk Type: SSD

I ran this with both my computers, and the error was the same on both. The specs of each are listed above.

**Comment by Matt90o** [comment] 2017-07-21 10:10
If you use `sudo make` the problem with the syntax error will be solved.

You will encounter a different problem, namely that automake-1.14 is not installed, even though a newer version is installed.

**Comment by laanwj** [comment] 2017-07-21 13:31
This issue is a duplicate of #10269.

**Comment by TheBlueMatt** [comment] 2017-07-23 16:12
Given all the bugs filed/issues related to "Ubuntu on Windows", I think we should just explicitly not support it at this point and if someone shows up who wants to support it, then we can reconsider. For now it seems like at every turn there are fresh bugs in this stuff, and until Microsoft gets their act together, you're better off just building natively on Windows MSVC.

**Comment by MattyAB** [comment] 2017-07-23 16:21
Yep, fair enough. I didn't actually know it was possible to build it on MSVC, I'll have a look into that. Is there any documentation for building Bitcoin on MSVC? If not, I'll see if I can get it working and then write a guide.

**Comment by brianmcmichael** [comment] 2017-07-24 13:47
I was able to build binaries on WSL using #10889 and #10899 

I'm willing to help debug Win10 issues as they arise in my off-hours.

**Comment by TheBlueMatt** [comment] 2017-07-25 19:51
@brianmcmichael awesome, thanks!

**Comment by laanwj** [comment] 2017-07-27 12:03
> you're better off just building natively on Windows MSVC.

That's a lot of work! You'll have to effectively make your own build system, and there might even be code changes necessary (unsure if that's still the case).

Cross-compiling from Ubuntu 14.04 (non-Ubuntu-on-windows) is still the recommended, and easiest way.

**Comment by sunnyday845** [comment] 2017-08-16 07:42
Hi,
New dev here, tried compiling and got here after errors. Wanted to weigh in and say that this...

> Cross-compiling from Ubuntu 14.04 (non-Ubuntu-on-windows) is still the recommended, and easiest way, and also how releases get built.

... should be in /doc/build-windows.md until the situation changes. Right now, to a newcomer, WSL is referenced as a supported tool for building on Windows.

Thanks!

**Comment by fanquake** [comment] 2017-08-19 06:10
Closing as a duplicate of #10269. Can any further comments please be made in that thread.

**Closed by fanquake** 2017-08-19 06:10 UTC
Labels: Windows
