### ISSUE TITLE
[RPC] Bug: RPC Batching does not work with more than 1 multi wallet 

### ISSUE THREAD

**Issue by NicolasDorier** [bitcoin/bitcoin#11257] opened 2017-09-06 14:08 UTC
***UPDATE:***

Turns out the issue was caused not by testnet, but by having 2 wallets @ryanofsky found out !

----------

Step to reproduce:

This work on regtest just fine:
```
bitcoind -wallet=test -regtest -rpcpassword=abc -rpcuser=abc
```

Try to make a batch RPC request to /wallet/test:

```
[{"jsonrpc":"1.0","id":1,"method":"getbalance","params":["*"]}]
```
You get the expected result.

However; same things with testnet:
```
bitcoind -wallet=test -testnet -rpcpassword=abc -rpcuser=abc
```

Result:

"Wallet file not specified (must request wallet RPC through /wallet/<filename> uri-path)."

This problem is limited to batched RPC request on testnet as just making the exact same request without the '[' and ']' works fine. It works also fine on regtest, which is crazy. I will look into later.

**Comment by sipa** [comment] 2017-09-06 15:06
Very strange! Does it work if you use the wallet URL?

**Comment by ryanofsky** [comment] 2017-09-06 20:34
Seems to be a bug in JSONRPCExecOne. It is creating a request object without assigning a url.

**Comment by sipa** [comment] 2017-09-06 20:54
Is this a 0.15.0 issue?

**Comment by ryanofsky** [comment] 2017-09-07 14:07
> Is this a 0.15.0 issue?

Actually, I'm not sure the bug I see in JSONRPCExecOne is the same one Nicolas is reporting. The bug in JSONRPCExecOne (which is only called for batch requests and not single requests) is that is that request uri field is not filled, so if more than one wallet file is loaded, "Wallet file not specified" errors will trigger when a wallet RPC is called. This is a bug in 0.15, but not a regression because previous releases did not support loading multiple wallets.

Nicolas's issue is more confusing because despite multiwallet being mentioned in issue title, steps to reproduce only show bitcoind being started with a single -wallet argument. Also, strangely the bug happens with testnet but not regtest.

**Comment by NicolasDorier** [comment] 2017-09-10 06:03
Sorry I was in holidays @ryanofsky . This bug came into a "production" testnet. I confirm that my bitcoind has two wallets.

**Comment by NicolasDorier** [comment] 2017-09-10 06:29
@sipa yes, 0.15.0 issue. Hopefully ryanosky's fix can make it in time. Testing it now.

**Comment by NicolasDorier** [comment] 2017-09-10 07:17
Tested, fixed by https://github.com/bitcoin/bitcoin/pull/11277

**Comment by sipa** [comment] 2017-09-10 07:27
Please don't close issues until the fix is actually merged.

**Closed** 2017-10-12 12:55 UTC
Labels: RPC/REST/ZMQ
