### ISSUE TITLE
Windows crash on startup

### ISSUE THREAD

**Issue by PRabahy** [bitcoin/bitcoin#6665] opened 2015-09-12 17:24 UTC
I did a right click --> exit on the taskbar icon. Once bitcoin-qt shutdown, I started it back up. Almost immediately I got an appcrash.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	bitcoin-qt.exe
  Application Version:	0.11.0.0
  Application Timestamp:	556ba080
  Fault Module Name:	bitcoin-qt.exe
  Fault Module Version:	0.11.0.0
  Fault Module Timestamp:	556ba080
  Exception Code:	c0000005
  Exception Offset:	0000000000abc4d2
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	2e60
  Additional Information 2:	2e60cd2844e589782c7983814009aa95
  Additional Information 3:	cb3c
  Additional Information 4:	cb3ce40cda913d380bce5af3e4ccb325

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

2015-09-12 17:14:26 Bitcoin version v0.11.0 (2015-07-10 19:23:55 +0200)
2015-09-12 17:14:26 Using OpenSSL version OpenSSL 1.0.1k 8 Jan 2015
2015-09-12 17:14:26 Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2015-09-12 17:14:26 Default data directory C:\Users\PRabahy\AppData\Roaming\Bitcoin
2015-09-12 17:14:26 Using data directory C:\Users\PRabahy\AppData\Roaming\Bitcoin
2015-09-12 17:14:26 Using config file C:\Users\PRabahy\AppData\Roaming\Bitcoin\bitcoin.conf
2015-09-12 17:14:26 Using at most 125 connections (2048 file descriptors available)
2015-09-12 17:14:26 Using 4 threads for script verification
2015-09-12 17:14:26 scheduler thread start
2015-09-12 17:14:26 Binding RPC on address ::1 port 8332 (IPv4+IPv6 bind any: 0)
2015-09-12 17:14:26 Binding RPC on address 127.0.0.1 port 8332 (IPv4+IPv6 bind any: 0)
2015-09-12 17:14:26 Bound to [::]:8333
2015-09-12 17:14:26 Bound to 0.0.0.0:8333
2015-09-12 17:14:26 Cache configuration:
2015-09-12 17:14:26 * Using 2.0MiB for block index database
2015-09-12 17:14:26 * Using 70.0MiB for chain state database
2015-09-12 17:14:26 * Using 178.0MiB for in-memory UTXO set
2015-09-12 17:14:26 init message: Loading block index...
2015-09-12 17:14:26 Opening LevelDB in C:\Users\PRabahy\AppData\Roaming\Bitcoin\blocks\index
2015-09-12 17:14:26 Opened LevelDB successfully
2015-09-12 17:14:26 Opening LevelDB in C:\Users\PRabahy\AppData\Roaming\Bitcoin\chainstate
2015-09-12 17:14:27 Opened LevelDB successfully
2015-09-12 17:14:32 LoadBlockIndexDB: last block file = 336
2015-09-12 17:14:32 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=87, size=56824117, heights=374128...374213, time=2015-09-12...2015-09-12)
2015-09-12 17:14:32 Checking all blk files are present...
2015-09-12 17:14:33 LoadBlockIndexDB: transaction index disabled
2015-09-12 17:14:33 LoadBlockIndexDB: hashBestChain=00000000000000000187cd2133b220cecc6ddb1036ec336e6e2c1f3a3e366075 height=374213 date=2015-09-12 17:01:40 progress=0.999990
2015-09-12 17:14:33 init message: Verifying blocks...
2015-09-12 17:14:33 Verifying last 288 blocks at level 3
2015-09-12 17:14:50 No coin database inconsistencies in last 25 blocks (24803 transactions)
2015-09-12 17:14:50  block index           23755ms
2015-09-12 17:14:50 Wallet disabled!
2015-09-12 17:14:50 init message: Activating best chain...
2015-09-12 17:14:50 mapBlockIndex.size() = 374694
2015-09-12 17:14:50 nBestHeight = 374213
2015-09-12 17:14:50 setKeyPool.size() = 0
2015-09-12 17:14:50 mapWallet.size() = 0
2015-09-12 17:14:50 mapAddressBook.size() = 0
2015-09-12 17:14:50 init message: Loading addresses...
2015-09-12 17:14:50 Loaded 66115 addresses from peers.dat  226ms
2015-09-12 17:14:50 dnsseed thread start
2015-09-12 17:14:50 net thread start
2015-09-12 17:14:50 upnp thread start
2015-09-12 17:14:50 addcon thread start
2015-09-12 17:14:50 opencon thread start
2015-09-12 17:14:50 init message: Done loading
2015-09-12 17:14:50 msghand thread start
2015-09-12 17:14:50 GUI: PaymentServer::LoadRootCAs: Loaded  36  root certificates 
2015-09-12 17:22:10 GUI: void QWindowsClipboard::propagateClipboardMessage(UINT, WPARAM, LPARAM) const: Cowardly refusing to send clipboard message to hung application...
2015-09-12 17:22:10 Loading addresses from DNS seeds (could take a while)
2015-09-12 17:22:10 GUI: void QWindowsClipboard::propagateClipboardMessage(UINT, WPARAM, LPARAM) const: Cowardly refusing to send clipboard message to hung application...

The time break between 17:14:50 and 17:22:10 is when I had the appcrash screen open.

**Comment by PRabahy** [comment] 2015-09-12 18:11
I forgot, just starting it again after the crash fixed the issue.

**Comment by jonasschnelli** [comment] 2015-09-12 20:53
Could be a upstream issue: https://bugreports.qt.io/browse/QTBUG-33492
Couldn't reproduce on my Windows 7.

**Comment by Rav3nPL** [comment] 2015-09-18 09:47
Try run it witch --debug to see more stuff in log

**Comment by PRabahy** [comment] 2015-09-18 16:18
I can't reproduce it, so I don't think --debug will help.

**Comment by laanwj** [comment] 2015-10-20 13:35
CLosing this, it is weird, but there is not enough information to troubleshoot it and you're not able to reproduce it.

**Closed by laanwj** 2015-10-20 13:35 UTC
Labels: Windows
