### ISSUE TITLE
autogen.sh error: possibly undefined macro: PKG_CONFIG_LIBDIR

### ISSUE THREAD

**Issue by SlimXin** [bitcoin/bitcoin#6432] opened 2015-07-14 07:49 UTC
configure.ac:894: error: possibly undefined macro: PKG_CONFIG_LIBDIR

**Comment by laanwj** [comment] 2015-07-17 19:47
Sounds like you need to install pkgconfig.

**Comment by sapeish** [comment] 2015-07-27 19:13
I have the same issue on CentOS 6.6 and `pkgconfig` is already installed: `pkgconfig-0.23-9.1.el6.x86_64 already installed and latest version`

**Comment by Klakurka** [comment] 2015-10-12 20:23
I still run into this same issue on the latest master.

I'm running CentOS 6.7. pkgconfig is installed.

**Comment by paveljanik** [comment] 2015-10-25 07:46
Can you please paste full `autogen.sh` and `configure` output?

**Comment by laanwj** [comment] 2015-10-26 12:06
Yes, need the line number, it can't be 864 anymore. Also need output of:
```
autoconf --version
automake --version
m4 --version
```

I guess it's triggered by this, but don't ask me what it does (looks like a no-op):
```
PKGCONFIG_LIBDIR_TEMP="$PKG_CONFIG_LIBDIR"
unset PKG_CONFIG_LIBDIR
PKG_CONFIG_LIBDIR="$PKGCONFIG_LIBDIR_TEMP"
````
@theuni can you take a look? Don't know what CentOS does differently.

**Comment by theuni** [comment] 2015-10-27 04:46
The behavior is a bit kludgy, but that's there to un-export PKG_CONFIG_LIBDIR, since we export it for OSX (to help with finding brew paths). Exporting a new var breaks autoconf's caching because the env looks different before/after, and that causes all kinds of wonky problems.

No clue why this would upset CentOS. I suppose we could guard that path so that we only unset what we ourselves export.

**Comment by theuni** [comment] 2015-10-27 04:49
The above comment was assuming those lines were causing the issue. I'd say it's more likely that CentOS doesn't ship the pkgconfig m4 like other distros do, or pkg-config is too old.

**Comment by Klakurka** [comment] 2015-10-28 03:42
autogen.sh output:

    libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
    libtoolize: copying file `build-aux/ltmain.sh'
    libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `build-aux/m4'.
    libtoolize: copying file `build-aux/m4/libtool.m4'
    libtoolize: copying file `build-aux/m4/ltoptions.m4'
    libtoolize: copying file `build-aux/m4/ltsugar.m4'
    libtoolize: copying file `build-aux/m4/ltversion.m4'
    libtoolize: copying file `build-aux/m4/lt~obsolete.m4'
    libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
    libtoolize: copying file `build-aux/ltmain.sh'
    libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `build-aux/m4'.
    libtoolize: copying file `build-aux/m4/libtool.m4'
    libtoolize: copying file `build-aux/m4/ltoptions.m4'
    libtoolize: copying file `build-aux/m4/ltsugar.m4'
    libtoolize: copying file `build-aux/m4/ltversion.m4'
    libtoolize: copying file `build-aux/m4/lt~obsolete.m4'
    libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
    libtoolize: copying file `build-aux/ltmain.sh'
    libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `build-aux/m4'.
    libtoolize: copying file `build-aux/m4/libtool.m4'
    libtoolize: copying file `build-aux/m4/ltoptions.m4'
    libtoolize: copying file `build-aux/m4/ltsugar.m4'
    libtoolize: copying file `build-aux/m4/ltversion.m4'
    libtoolize: copying file `build-aux/m4/lt~obsolete.m4'
    configure.ac:939: error: possibly undefined macro: PKG_CONFIG_LIBDIR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
    autoreconf: /usr/bin/autoconf failed with exit status: 1

autoconf --version:

    autoconf (GNU Autoconf) 2.63
    Copyright (C) 2008 Free Software Foundation, Inc.
    License GPLv2+: GNU GPL version 2 or later
    <http://gnu.org/licenses/old-licenses/gpl-2.0.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    
    Written by David J. MacKenzie and Akim Demaille.

automake --version:

    automake (GNU automake) 1.11.1
    Copyright (C) 2009 Free Software Foundation, Inc.
    License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

    Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.

m4 --version:

    m4 (GNU M4) 1.4.13
    Copyright (C) 2009 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    
    Written by Rene' Seindal.

Let me know if you need anything else.

**Comment by MarcoFalke** [comment] 2015-11-11 20:57
Can reproduce what @Klakurka said on cbf9609 and CentOS release 6.7 (Final):

```
configure.ac:957: error: possibly undefined macro: PKG_CONFIG_LIBDIR
```
Which is this line: https://github.com/bitcoin/bitcoin/blob/cbf9609c71c6dca6efac8504dc9bd82f6b205cc9/configure.ac#L957

Not sure but this diff seems to work around. 


```diff
diff --git a/configure.ac b/configure.ac
index e8aea90..ec25aca 100644
--- a/configure.ac
+++ b/configure.ac
@@ -954,9 +954,9 @@ PKGCONFIG_PATH_TEMP="$PKG_CONFIG_PATH"
 unset PKG_CONFIG_PATH
 PKG_CONFIG_PATH="$PKGCONFIG_PATH_TEMP"
 
-PKGCONFIG_LIBDIR_TEMP="$PKG_CONFIG_LIBDIR"
-unset PKG_CONFIG_LIBDIR
-PKG_CONFIG_LIBDIR="$PKGCONFIG_LIBDIR_TEMP"
+#PKGCONFIG_LIBDIR_TEMP="$PKG_CONFIG_LIBDIR"
+#unset PKG_CONFIG_LIBDIR
+#PKG_CONFIG_LIBDIR="$PKGCONFIG_LIBDIR_TEMP"
 
 ac_configure_args="${ac_configure_args} --disable-shared --with-pic --with-bign
 AC_CONFIG_SUBDIRS([src/secp256k1 src/univalue])
```

(Couldn't go further because configure complains about

```
checking for EVENT... no
configure: error: libevent not found.
```

even though 

```
Package libevent-devel-1.4.13-4.el6.x86_64 already installed and latest version
Package libevent-doc-1.4.13-4.el6.noarch already installed and latest version
Package libevent-headers-1.4.13-4.el6.noarch already installed and latest version
Package libevent-1.4.13-4.el6.x86_64 already installed and latest version
```

)

**Comment by laanwj** [comment] 2015-11-12 08:29
I remember having a similar issue to what @MarcoFalke was having at some point, also worked around it by commenting out those lines. Some versions don't like this define-undefine dance.

**Comment by theuni** [comment] 2015-11-12 08:46
Ok, I'll hide that so it's osx only.

**Comment by yangllsdev** [comment] 2016-03-16 06:06
hi every god:
    i meet the same issue, when i compile bitcoin core 0.12 on centos 6.5
    my env just like @MarcoFalke 

    if i comment that 3 lines   ./autogen.sh is ok , but will not found libevent when config
    can u tell me how to solv this @theuni @laanwj

**Comment by yangllsdev** [comment] 2016-03-16 08:21
@MarcoFalke , does it work when you use libevent2.0
libevent also can not found when i do that

**Comment by yangllsdev** [comment] 2016-03-16 09:06
it does not work when commenting those lines
because it can not found libevent when config ... ...   even if use libevent2.0

config  error
checking for EVENT... no
configure: error: libevent not found.


can you give some better suggestion

my env
centos 6.5 + bitcoin core 0.12

**Comment by yangllsdev** [comment] 2016-03-16 09:07
it does not work when commenting those lines
because it can not found libevent when config ... ... even if use libevent2.0

config error
checking for EVENT... no
configure: error: libevent not found.

can you give some better suggestion

my env
centos 6.5 + bitcoin core 0.1

@theuni  @laanwj

**Comment by yangllsdev** [comment] 2016-03-16 09:08
it does not work when commenting those lines
because it can not found libevent when config ... ... even if use libevent2.0

config error
checking for EVENT... no
configure: error: libevent not found.

can you give some better suggestion

my env
centos 6.5 + bitcoin core 0.12

@theuni @laanwj

**Comment by laanwj** [comment] 2016-03-16 09:12
@yangllsdev if it is a different problem please open a new issue instead of commenting on this one, that's considered rude.

You certainly need libevent 2.0+. But It looks to me that you have only the shared library installed and not the development headers. If you do have the libevent headers (`event.h`, `evhttp.h` etc) on your system and it doesn't detect them, please open a new issue.

**Comment by yangllsdev** [comment] 2016-03-16 11:56
@laanwj 
thanks 
i will try agin tomorrow
thanks it is useful

**Comment by Zenitur** [comment] 2016-10-03 09:17
Confirm on SLES 11

**Comment by marzzz21** [comment] 2016-12-06 00:58
I'm receiving errors installing Version 0.5.0 on CentOS 7.2. It gives me this error:

https://gist.github.com/anonymous/1edd73d34ad0e7b537e902da6ba3cfe1

Tried installing glib, didn't help though.

**Comment by laanwj** [comment] 2016-12-06 05:29
Version 0.5.0 that's a typo right?

**Comment by marzzz21** [comment] 2016-12-06 05:32
Oh shoot, yeah, I've posted it all wrong, I apologize, let me remove that one.

**Comment by kuzyakiev** [comment] 2017-11-12 12:41
Have the same issue on CentOS 6.5 && bitcoin v0.15.1
autogen.sh output:
```
build-aux/m4/libtool.m4:1022: _LT_SYS_MODULE_PATH_AIX is expanded from...
build-aux/m4/libtool.m4:4161: _LT_LINKER_SHLIBS is expanded from...
build-aux/m4/libtool.m4:5236: _LT_LANG_C_CONFIG is expanded from...
build-aux/m4/libtool.m4:138: _LT_SETUP is expanded from...
build-aux/m4/libtool.m4:67: LT_INIT is expanded from...
configure.ac:78: the top level
configure.ac:78: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
build-aux/m4/libtool.m4:4161: _LT_LINKER_SHLIBS is expanded from...
build-aux/m4/libtool.m4:5236: _LT_LANG_C_CONFIG is expanded from...
build-aux/m4/libtool.m4:138: _LT_SETUP is expanded from...
build-aux/m4/libtool.m4:67: LT_INIT is expanded from...
configure.ac:78: the top level
configure.ac:78: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
build-aux/m4/libtool.m4:1022: _LT_SYS_MODULE_PATH_AIX is expanded from...
build-aux/m4/libtool.m4:5343: _LT_LANG_CXX_CONFIG is expanded from...
build-aux/m4/libtool.m4:785: _LT_LANG is expanded from...
build-aux/m4/libtool.m4:768: LT_LANG is expanded from...
build-aux/m4/libtool.m4:796: _LT_LANG_DEFAULT_CONFIG is expanded from...
build-aux/m4/libtool.m4:138: _LT_SETUP is expanded from...
build-aux/m4/libtool.m4:67: LT_INIT is expanded from...
configure.ac:78: the top level
configure.ac:1257: error: possibly undefined macro: PKG_CONFIG_LIBDIR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/bin/autoconf failed with exit status: 1
```
autoconf --version
```
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

automake --version
```
automake (GNU automake) 1.11.1
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

m4 --version
```
m4 (GNU M4) 1.4.13
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Rene' Seindal.
```

**Comment by kuzyakiev** [comment] 2017-11-12 12:45
Fixed with: https://github.com/bitcoin/bitcoin/issues/6602#issuecomment-136290383

**Closed** 2017-11-13 12:01 UTC
Labels: Build system
