### ISSUE TITLE
RC2 Exits After Initialization

### ISSUE THREAD

**Issue by xyzzy099** [bitcoin/bitcoin#11171] opened 2017-08-27 14:55 UTC
I installed RC2 on my Windows7 box, and it exits shortly after initialization consistently.  The debug log contents look OK, with the only errors contained in the snippet below:
---

2017-08-27 14:00:58 GUI: PaymentServer::LoadRootCAs: Loaded  56  root certifica
es
2017-08-27 14:00:58 tor: Error connecting to Tor control socket
2017-08-27 14:00:58 tor: Not connected to Tor control port 127.0.0.1:9051, tryi
g to reconnect
2017-08-27 14:00:58 GUI: TransactionTablePriv::refreshWallet
2017-08-27 14:00:59 trying connection 79.195.178.192:8333 lastseen=366.6hrs
2017-08-27 14:00:59 Added connection peer=0
2017-08-27 14:01:00 tor: Error connecting to Tor control socket
2017-08-27 14:01:00 tor: Not connected to Tor control port 127.0.0.1:9051, tryi
g to reconnect
2017-08-27 14:01:03 tor: Error connecting to Tor control socket
2017-08-27 14:01:03 tor: Not connected to Tor control port 127.0.0.1:9051, tryi
g to reconnect
2017-08-27 14:01:04 connection to 79.195.178.192:8333 timeout
2017-08-27 14:01:04 trying connection 81.163.206.173:8333 lastseen=175.4hrs
2017-08-27 14:01:04 connection from 213.5.31.38:54224 accepted
2017-08-27 14:01:04 Added connection peer=1
2017-08-27 14:01:04 connection from 52.192.180.114:40814 accepted
2017-08-27 14:01:04 connection from 54.191.174.46:38180 dropped (banned)
2017-08-27 14:01:04 received: version (106 bytes) peer=1
2017-08-27 14:01:04 sending version (102 bytes) peer=1
2017-08-27 14:01:04 send version message: version 70015, blocks=482210, us=[::]
0, peer=1
2017-08-27 14:01:04 sending verack (0 bytes) peer=1
2017-08-27 14:01:04 receive version message: /bitcoin-seeder:0.01/: version 600
0, blocks=350000, us=73.119.168.246:8333, peer=1
2017-08-27 14:01:04 added time data, samples 2, offset -209 (-3 minutes)
2017-08-27 14:01:04 sending alert (168 bytes) peer=1
2017-08-27 14:01:05 received: verack (0 bytes) peer=1
2017-08-27 14:01:05 sending ping (0 bytes) peer=1
2017-08-27 14:01:05 socket closed
2017-08-27 14:01:05 disconnecting peer=1

**Comment by xyzzy099** [comment] 2017-08-29 10:24
For the record, I just installed RC3 and it exhibits the same problem.

**Comment by achow101** [comment] 2017-08-29 19:32
Please post the entire debug.log file. The snippet provided does not give anything meaningful.

**Comment by xyzzy099** [comment] 2017-08-29 19:58
Below is the entire debug output from my latest attempt to start rc3:

2017-08-29 19:37:52 Bitcoin version v0.15.0rc3
2017-08-29 19:37:52 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2017-08-29 19:37:52 Assuming ancestors of block 0000000000000000003b9ce759c2a087d52abc4266f8f4ebd6d768b89defa50a have valid signatures.
2017-08-29 19:37:52 Using the 'standard' SHA256 implementation
2017-08-29 19:37:53 RandAddSeedPerfmon: 240344 bytes
2017-08-29 19:37:53 GUI: requestInitialize : Requesting initialize
2017-08-29 19:37:53 GUI: initialize : Running initialization in thread
2017-08-29 19:37:53 Default data directory C:\Users\djm\AppData\Roaming\Bitcoin
2017-08-29 19:37:53 Using data directory F:\Bitcoin
2017-08-29 19:37:53 GUI: "registerShutdownBlockReason: Successfully registered: Bitcoin Core didn't yet exit safely..."
2017-08-29 19:37:53 Using config file F:\Bitcoin\bitcoin.conf
2017-08-29 19:37:53 Using at most 125 automatic connections (2048 file descriptors available)
2017-08-29 19:37:53 Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
2017-08-29 19:37:53 Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
2017-08-29 19:37:53 Using 4 threads for script verification
2017-08-29 19:37:53 scheduler thread start
2017-08-29 19:37:53 Allowing HTTP connections from: 127.0.0.0/8 ::1/128 10.0.0.0/24 
2017-08-29 19:37:53 Binding RPC on address :: port 8332
2017-08-29 19:37:53 Binding RPC on address 0.0.0.0 port 8332
2017-08-29 19:37:53 Initialized HTTP server
2017-08-29 19:37:53 HTTP: creating work queue of depth 16
2017-08-29 19:37:53 Starting RPC
2017-08-29 19:37:53 Starting HTTP RPC server
2017-08-29 19:37:53 Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcuser for rpcauth auth generation.
2017-08-29 19:37:53 Registering HTTP handler for / (exactmatch 1)
2017-08-29 19:37:53 Registering HTTP handler for /wallet/ (exactmatch 0)
2017-08-29 19:37:53 Starting HTTP server
2017-08-29 19:37:53 HTTP: starting 4 worker threads
2017-08-29 19:37:53 Entering http event loop
2017-08-29 19:37:53 init message: Verifying wallet(s)...
2017-08-29 19:37:53 Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2017-08-29 19:37:53 Using wallet wallet.dat
2017-08-29 19:37:53 CDBEnv::Open: LogDir=F:\Bitcoin\database ErrorFile=F:\Bitcoin\db.log
2017-08-29 19:37:53 Cache configuration:
2017-08-29 19:37:53 * Using 2.0MiB for block index database
2017-08-29 19:37:53 * Using 8.0MiB for chain state database
2017-08-29 19:37:53 * Using 290.0MiB for in-memory UTXO set (plus up to 286.1MiB of unused mempool space)
2017-08-29 19:37:53 init message: Loading block index...
2017-08-29 19:37:53 Opening LevelDB in F:\Bitcoin\blocks\index
2017-08-29 19:37:53 Recovering log #548
2017-08-29 19:37:53 Level-0 table #550: started
2017-08-29 19:37:53 Level-0 table #550: 179 bytes OK
2017-08-29 19:37:53 Delete type=0 #548
2017-08-29 19:37:53 Delete type=3 #546
2017-08-29 19:37:53 Opened LevelDB successfully
2017-08-29 19:37:53 Using obfuscation key for F:\Bitcoin\blocks\index: 0000000000000000
2017-08-29 19:37:58 LoadBlockIndexDB: last block file = 979
2017-08-29 19:37:58 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=28, size=27978569, heights=482183...482210, time=2017-08-27...2017-08-27)
2017-08-29 19:37:58 Checking all blk files are present...
2017-08-29 19:37:59 LoadBlockIndexDB: transaction index disabled
2017-08-29 19:37:59 Opening LevelDB in F:\Bitcoin\chainstate
2017-08-29 19:37:59 Recovering log #871312
2017-08-29 19:37:59 Level-0 table #871322: started
2017-08-29 19:37:59 Level-0 table #871322: 308 bytes OK
2017-08-29 19:37:59 Delete type=2 #870302
2017-08-29 19:37:59 Delete type=2 #870303
2017-08-29 19:37:59 Delete type=2 #870304
2017-08-29 19:37:59 Delete type=2 #870305
2017-08-29 19:37:59 Delete type=2 #870306
2017-08-29 19:37:59 Delete type=2 #870311
2017-08-29 19:37:59 Delete type=0 #871312
2017-08-29 19:37:59 Delete type=3 #871310
2017-08-29 19:37:59 Opened LevelDB successfully
2017-08-29 19:37:59 Using obfuscation key for F:\Bitcoin\chainstate: c15290b8f7b37d9d
2017-08-29 19:37:59 Loaded best chain: hashBestChain=000000000000000000e725b7df7ae4d183a9146f9ac3a0eb0ecd1aa0b152abda height=482210 date=2017-08-27 13:31:20 progress=0.997589
2017-08-29 19:37:59 init message: Rewinding blocks...
2017-08-29 19:38:00 Writing final batch of 0.00 MiB
2017-08-29 19:38:00 Committed 0 changed transaction outputs (out of 0) to coin database...
2017-08-29 19:38:00 init message: Verifying blocks...
2017-08-29 19:38:00 Verifying last 6 blocks at level 3
2017-08-29 19:38:00 [0%]...Compacting 1@0 + 1@1 files
2017-08-29 19:38:00 Generated table #871324@0: 1 keys, 207 bytes
2017-08-29 19:38:00 Compacted 1@0 + 1@1 files => 207 bytes
2017-08-29 19:38:00 compacted to: files[ 0 1 45 252 1025 0 0 ]
2017-08-29 19:38:00 Delete type=2 #871313
2017-08-29 19:38:00 Delete type=2 #871322
2017-08-29 19:38:01 [16%]...[33%]...[50%]...[66%]...[83%]...[99%]...Expanding@3 1+1 (2176269+2175089 bytes) to 5+1 (10877150+2175089 bytes)
2017-08-29 19:38:04 Compacting 5@3 + 1@4 files
2017-08-29 19:38:04 [DONE].
2017-08-29 19:38:04 No coin database inconsistencies in last 7 blocks (10964 transactions)
2017-08-29 19:38:04  block index           11290ms
2017-08-29 19:38:04 Reading estimates: 98 buckets counting confirms up to 25 blocks
2017-08-29 19:38:04 init message: Loading wallet...
2017-08-29 19:38:04 Generated table #871325@3: 38554 keys, 2174677 bytes
2017-08-29 19:38:04 Generated table #871326@3: 39065 keys, 2175256 bytes
2017-08-29 19:38:04 nFileVersion = 150000
2017-08-29 19:38:04 Keys: 0 plaintext, 228 encrypted, 0 w/ metadata, 228 total
2017-08-29 19:38:04  wallet                  220ms
2017-08-29 19:38:04 setKeyPool.size() = 97
2017-08-29 19:38:04 mapWallet.size() = 633
2017-08-29 19:38:04 mapAddressBook.size() = 33
2017-08-29 19:38:04 mapBlockIndex.size() = 482235
2017-08-29 19:38:04 nBestHeight = 482210
2017-08-29 19:38:04 torcontrol thread start
2017-08-29 19:38:04 AddLocal([2601:190:580:93ac::559f]:8333,1)
2017-08-29 19:38:04 Discover: djm-PC - 2601:190:580:93ac::559f
2017-08-29 19:38:04 AddLocal([2601:190:580:93ac:b502:1772:28c5:87ea]:8333,1)
2017-08-29 19:38:04 Discover: djm-PC - 2601:190:580:93ac:b502:1772:28c5:87ea
2017-08-29 19:38:04 AddLocal([2601:190:580:93ac:c4:120b:881e:39d3]:8333,1)
2017-08-29 19:38:04 Discover: djm-PC - 2601:190:580:93ac:c4:120b:881e:39d3
2017-08-29 19:38:04 Bound to [::]:8333
2017-08-29 19:38:04 Bound to 0.0.0.0:8333
2017-08-29 19:38:04 init message: Loading P2P addresses...
2017-08-29 19:38:04 Generated table #871327@3: 39070 keys, 2174944 bytes
2017-08-29 19:38:05 Generated table #871328@3: 39113 keys, 2175622 bytes
2017-08-29 19:38:05 Generated table #871329@3: 39444 keys, 2176163 bytes
2017-08-29 19:38:05 Generated table #871330@3: 38780 keys, 2175602 bytes
2017-08-29 19:38:05 Compacted 5@3 + 1@4 files => 13052264 bytes
2017-08-29 19:38:05 compacted to: files[ 0 1 45 247 1030 0 0 ]
2017-08-29 19:38:05 Delete type=2 #869962
2017-08-29 19:38:05 Delete type=2 #869963
2017-08-29 19:38:05 Delete type=2 #869964
2017-08-29 19:38:05 Delete type=2 #869965
2017-08-29 19:38:05 Delete type=2 #869966
2017-08-29 19:38:05 Delete type=2 #869971
2017-08-29 19:38:05 Loaded 68037 addresses from peers.dat  361ms
2017-08-29 19:38:05 init message: Loading banlist...
2017-08-29 19:38:05 ERROR: DeserializeFileDB: Failed to open file F:\Bitcoin\banlist.dat
2017-08-29 19:38:05 Invalid or missing banlist.dat; recreating
2017-08-29 19:38:05 Flushed 0 banned node ips/subnets to banlist.dat  10ms
2017-08-29 19:38:05 init message: Starting network threads...
2017-08-29 19:38:05 net thread start
2017-08-29 19:38:05 addcon thread start
2017-08-29 19:38:05 init message: Done loading
2017-08-29 19:38:05 opencon thread start
2017-08-29 19:38:05 dnsseed thread start
2017-08-29 19:38:05 msghand thread start
2017-08-29 19:38:05 GUI: initializeResult : Initialization result:  true
2017-08-29 19:38:05 GUI: Platform customization: "windows"
2017-08-29 19:38:05 GUI: "ReportInvalidCertificate: Payment server found an invalid certificate: " "01" ("Microsoft Authenticode(tm) Root Authority") () ()
2017-08-29 19:38:05 GUI: "ReportInvalidCertificate: Payment server found an invalid certificate: " "01" () () ("Copyright (c) 1997 Microsoft Corp.", "Microsoft Time Stamping Service Root", "Microsoft Corporation")
2017-08-29 19:38:05 GUI: "ReportInvalidCertificate: Payment server found an invalid certificate: " "4a:19:d2:38:8c:82:59:1c:a5:5d:73:5f:15:5d:dc:a3" () () ("NO LIABILITY ACCEPTED, (c)97 VeriSign, Inc.", "VeriSign Time Stamping Service Root", "VeriSign, Inc.")
2017-08-29 19:38:05 GUI: "ReportInvalidCertificate: Payment server found an invalid certificate: " "3f:8b:c8:b5:fc:9f:b2:96:43:b5:69:d6:6c:42:e1:44" ("Microsoft Root Certificate Authority 2011") () ()
2017-08-29 19:38:05 GUI: "ReportInvalidCertificate: Payment server found an invalid certificate: " "03:c7:8f:37:db:92:28:df:3c:bb:1a:ad:82:fa:67:10" () () ("VeriSign Commercial Software Publishers CA")
2017-08-29 19:38:05 GUI: PaymentServer::LoadRootCAs: Loaded  56  root certificates
2017-08-29 19:38:05 GUI: TransactionTablePriv::refreshWallet
2017-08-29 19:38:05 trying connection 172.104.78.159:8333 lastseen=57.2hrs
2017-08-29 19:38:05 tor: Error connecting to Tor control socket
2017-08-29 19:38:05 tor: Not connected to Tor control port 127.0.0.1:9051, trying to reconnect
2017-08-29 19:38:06 Added connection peer=0
2017-08-29 19:38:06 sending version (102 bytes) peer=0
2017-08-29 19:38:06 send version message: version 70015, blocks=482210, us=[::]:0, peer=0
2017-08-29 19:38:06 received: version (102 bytes) peer=0
2017-08-29 19:38:06 sending verack (0 bytes) peer=0
2017-08-29 19:38:06 sending getaddr (0 bytes) peer=0
2017-08-29 19:38:06 receive version message: /Satoshi:0.14.1/: version 70015, blocks=482519, us=73.119.168.246:6576, peer=0
2017-08-29 19:38:06 added time data, samples 2, offset -205 (-3 minutes)
2017-08-29 19:38:06 received: verack (0 bytes) peer=0
2017-08-29 19:38:06 sending sendheaders (0 bytes) peer=0
2017-08-29 19:38:06 sending sendcmpct (9 bytes) peer=0
2017-08-29 19:38:06 sending sendcmpct (9 bytes) peer=0
2017-08-29 19:38:06 sending ping (8 bytes) peer=0
2017-08-29 19:38:06 received: sendheaders (0 bytes) peer=0
2017-08-29 19:38:06 initial getheaders (482209) to peer=0 (startheight:482519)
2017-08-29 19:38:06 sending getheaders (997 bytes) peer=0
2017-08-29 19:38:06 sending feefilter (8 bytes) peer=0
2017-08-29 19:38:06 received: sendcmpct (9 bytes) peer=0
2017-08-29 19:38:06 received: sendcmpct (9 bytes) peer=0
2017-08-29 19:38:06 received: ping (8 bytes) peer=0
2017-08-29 19:38:06 sending pong (8 bytes) peer=0
2017-08-29 19:38:06 received: addr (31 bytes) peer=0
2017-08-29 19:38:06 trying connection 176.9.133.154:8333 lastseen=59.8hrs
2017-08-29 19:38:07 received: getheaders (997 bytes) peer=0
2017-08-29 19:38:07 Ignoring getheaders from peer=0 because node is in initial block download
2017-08-29 19:38:07 received: feefilter (8 bytes) peer=0
2017-08-29 19:38:07 received: feefilter of 0.00001000 BTC/kB from peer=0
2017-08-29 19:38:07 received: pong (8 bytes) peer=0
2017-08-29 19:38:07 Added connection peer=1
2017-08-29 19:38:07 sending version (102 bytes) peer=1
2017-08-29 19:38:07 send version message: version 70015, blocks=482210, us=[::]:0, peer=1
2017-08-29 19:38:07 trying connection 81.92.107.72:8333 lastseen=142.2hrs
2017-08-29 19:38:07 received: headers (25113 bytes) peer=0

**Comment by MeshCollider** [comment] 2017-08-30 00:34
The issue won't be contained in debug.log if its crashing with like a segfault, won't log anything to the debug log during the crash, which looks like might be the case here because the log just ends abruptly, maybe try running in gdb? https://gist.github.com/laanwj/29bc141fb8d10608651c

**Comment by xyzzy099** [comment] 2017-08-30 01:23
Well, I can confirm that bitcoind.exe does NOT appear to crash - this seems to be an issue only with bitcoin-qt.exe.

Sadly, it does not appear to be possible for me to debug this binary with either of the GDBs I have installed - CygWin and MinGW.  Both report that the file is not a recognized executable format.

It does appear to be a segfault error, I think - if I start bitcoin-qt from the command line, it will restart continuously after each initialization.

**Comment by MeshCollider** [comment] 2017-08-30 02:07
Any crash messages? Wonder if this is related to 9683 and 9883

**Comment by xyzzy099** [comment] 2017-08-30 15:38
No crash messages, nothing ever gets printed on STDOUT - but looking at the windows logs shows that the error is definitely an access violation, so probably a null pointer thing.  I am going to try to install a debugger on windows that I can use to attach to the process and see if I can figure out what's going on as soon as I get a chance.

**Comment by MeshCollider** [comment] 2017-08-30 20:52
Also please try launching with `bitcoin-qt.exe --resetguisettings` and see if that works

**Comment by xyzzy099** [comment] 2017-08-30 22:52
Wow!  Running with '-resetguisettings' fixed the problem!  Thanks :)

**Comment by Guillerbr** [comment] 2017-08-31 00:01
Good

**Comment by MeshCollider** [comment] 2017-08-31 03:27
@jonasschnelli looks like this was the same problem as #7869 again then, have you got anywhere with the cause?

**Comment by achow101** [comment] 2017-08-31 19:36
@xyzzy099 Did you have multiple monitors? If so, did you disconnect one monitor before you started Bitcoin Core?

**Comment by xyzzy099** [comment] 2017-08-31 21:51
I did not have multiple monitors - but I have accessed the machine in question remotely (which windows, I believe, may see as another monitor), and have stopped/started Bitcoin-qt via the remote session.  As an additional data point, when I was still running 0.14.2 I noticed that the Bitcoin-qt window had started to always open in the extreme lower right-hand of the screen consistently, which is not default behavior, and persisted in opening in that location no matter where the window was when I closed it.  Maybe meaningless, but I thought I should mention it since it seemed odd to me at the time.

**Comment by xyzzy099** [comment] 2017-08-31 21:54
Additionally, I should mention that, at least in my case, the window was definitely NOT opening off-screen.  The client was crashing with a memory  access violation consistently,

**Comment by achow101** [comment] 2017-08-31 23:07
Since `-resetguisettings` fixed the problem for you, that means that there is a problem with how we handle the settings. Either your settings were messed up which caused a bug, or there is a bug with how our settings work.

**Comment by achow101** [comment] 2017-08-31 23:25
@xyzzy099 Do you have any windows logs of the crash that show a memory access violation?

**Comment by xyzzy099** [comment] 2017-08-31 23:47
Yep.  Lots of them, just like this one:

Faulting application name: bitcoin-qt.exe, version: 0.15.0.0, time stamp: 0x59a3d3e7
Faulting module name: bitcoin-qt.exe, version: 0.15.0.0, time stamp: 0x59a3d3e7
**Exception code: 0xc0000005**
Fault offset: 0x00000000010c4fea
Faulting process id: 0xc68
Faulting application start time: 0x01d3214403924c25
Faulting application path: C:\Program Files\Bitcoin\bitcoin-qt.exe
Faulting module path: C:\Program Files\Bitcoin\bitcoin-qt.exe
Report Id: 4a8de077-8d37-11e7-ae98-2cd05adc2cb3

**Comment by xyzzy099** [comment] 2017-08-31 23:51
For completeness, I should add that in some of the log entries the "faulting module path" is " C:\Windows\SYSTEM32\ntdll.dll".

**Comment by achow101** [comment] 2017-09-01 00:49
I've been looking into this much more just now, and I found something interesting. So normally we should see this line: `GUI: PaymentServer::initNetManager: No active proxy server found.` (or similar, slightly different with a SOCKS proxy enabled, but same beginning part) in your debug.log with `-debug`, but we don't see that here. That debug line is part of this function: https://github.com/bitcoin/bitcoin/blob/master/src/qt/paymentserver.cpp#L363 which is called here: https://github.com/bitcoin/bitcoin/blob/master/src/qt/bitcoin.cpp#L520 at the end of GUI initialization, right after the splashscreen disappears. The function happens ~100 milliseconds after the splashscreen disappears. However we don't see that debug line, which means that the function must have bailed out or crashed. This indicates to me that it must have bailed out here: https://github.com/bitcoin/bitcoin/blob/master/src/qt/paymentserver.cpp#L366 which means that `optionsModel` is null or one of the following lines had the memory access violation: https://github.com/bitcoin/bitcoin/blob/master/src/qt/paymentserver.cpp#L371 and https://github.com/bitcoin/bitcoin/blob/master/src/qt/paymentserver.cpp#L376. I suspect it may be with the `getproxysettings` call. Still investigating, but meanwhile, I found a different bug which I will open an issue/fix later.

**Comment by sipa** [comment] 2017-09-01 06:41
Reopening under the assumption that this is not solved.

**Comment by wostl** [comment] 2017-09-11 07:57
I have a similar crash bug on Windows 10 64 with 0.15-rc3.
The splashscreen comes up, says verifying blocks and some other things and then crashes while saying "loading". My blockchain is on an HDD which constantly produces read noise even when crashed, as long as I kill the task.

**Comment by MeshCollider** [comment] 2017-09-11 10:58
@wostl please open a separate issue with a bit more info, its hard to tell whether that is the same issue or not :)

**Comment by wostl** [comment] 2017-09-14 16:53
"-resetguisettings" fixed the crashbug for me too (bitcoin-0.15.0-win64).

**Comment by achow101** [comment] 2017-09-14 17:30
For anyone who comes across this in the future, please post your GUI settings before doing `-resetguisettings` so that I can analyze them to see what is causing in the problem. On Windows, the GUI settings are found in the registry. On linux, they should be in `~/.config/Bitcoin/Bitcoin-Qt.conf`.

**Comment by laanwj** [comment] 2017-09-14 17:33
The registry key in windows is `HKEY_CURRENT_USER\Bitcoin\Bitcoin-Qt`. Just export everything below it, there's nothing sensitive.

**Comment by wostl** [comment] 2017-09-14 18:00
I upgraded from 0.14.2-uasfsegwit1.0 to 0.15.0-rc3, and then to 0.15.0. Both 0.15.0 crashed on the splash screen just before the GUI used to appear. Tray icon was already there.

I know that my cache settings were raised (to either 2 or 4GB). UPNP and incoming connections were set.

**Comment by laanwj** [comment] 2017-09-14 18:02
@wostl did you have a proxy set?

**Comment by wostl** [comment] 2017-09-14 18:27
Definitely no proxy.

**Comment by fanquake** [comment] 2017-10-07 02:55
Closing, should be fixed by #11335.

**Closed by fanquake** 2017-10-07 02:55 UTC
Labels: Windows
