### ISSUE TITLE
Importing an address that you have sent to does not update the corresponding transactions 

### ISSUE THREAD

**Issue by benthecarman** [bitcoin/bitcoin#15498] opened 2019-02-28 02:20 UTC
I sent from address X to address Y.  I already had X as a watch only address but not Y.  After the transaction was confirmed it my node did not change the transaction from a "sent to" to a "payment to yourself" and needed to restart Bitcoin Core to see the change.

**Comment by promag** [comment] 2019-03-23 00:28
Please tag GUI.

Looks like the following isn't updated:
https://github.com/bitcoin/bitcoin/blob/6cf81b01b48e871a35072dd08e7735c3ba42528c/src/qt/transactionrecord.h#L118

**Comment by MarcoFalke** [comment] 2020-05-11 23:38
Duplicate of #11477 ?

**Comment by hebasto** [comment] 2022-08-05 09:31
Moved to bitcoin-core/gui#641.

**Closed by hebasto** 2022-08-05 09:31 UTC
Labels: GUI
