### ISSUE TITLE
test: failure in interface_usdt_validation.py 

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#25764] opened 2022-08-01 12:19 UTC
https://cirrus-ci.com/task/5553601580892160?logs=ci#L4244:
```bash
 test  2022-08-01T12:14:24.104000Z TestFramework (INFO): handle_blockconnected(): ConnectedBlock(hash=2f97f65fda63aba081bf2867f7f99657c39436306c4aed3c899264b8bde7c5ab height=202, transactions=1, inputs=1, sigops=0, duration=517) 
 test  2022-08-01T12:14:24.104000Z TestFramework (INFO): handle_blockconnected(): ConnectedBlock(hash=54d4bd414e5de85cee4dc5f1e7bcf4e358cf6e7ce556647debe2e9d007459ec7 height=201, transactions=1, inputs=1, sigops=0, duration=338) 
 test  2022-08-01T12:14:24.148000Z TestFramework (INFO): check that we traced 2 blocks 
 test  2022-08-01T12:14:24.149000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 133, in main
                                       self.run_test()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/interface_usdt_validation.py", line 131, in run_test
                                       assert_equal(BLOCKS_EXPECTED, blocks_checked)
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 52, in assert_equal
                                       raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
                                   AssertionError: not(2 == 0)
```

**Comment by 0xB10C** [comment] 2022-08-04 15:19
I'll look into this.

**Comment by theStack** [comment] 2022-08-05 10:29
Another run with this assertion (`assert_equal(BLOCKS_EXPECTED, blocks_checked)`) failing: https://cirrus-ci.com/task/4529853595648000?logs=ci#L4233

**Comment by 0xB10C** [comment] 2022-08-06 10:45
Some notes for now: 

- I can't reproduce this locally. It might be a timing thing. Will further test in the CI runner.
- I first though increasing the timeout could help. https://github.com/bitcoin/bitcoin/blob/b1a2021f78099c17360dc2179cbcb948059b5969/test/functional/interface_usdt_validation.py#L127 However, the logs show that `handle_blockconnected()` is `correctly` being called twice, which means the timeout is fine.
- I'm not sure why [incrementing](https://github.com/bitcoin/bitcoin/blob/b1a2021f78099c17360dc2179cbcb948059b5969/test/functional/interface_usdt_validation.py#L116) `blocks_checked` in `handle_blockconnected()` sometimes has no effect on the value checked in the [assert](https://github.com/bitcoin/bitcoin/blob/master/test/functional/interface_usdt_validation.py#L131).

**Comment by 0xB10C** [comment] 2022-08-06 10:53
It's clear when looking at the stderr output, e.g. as attached in https://github.com/bitcoin/bitcoin/issues/25793. It seems like the order of block_connected events isn't something we should rely on in the tests.

**Closed** 2022-08-10 12:05 UTC
Labels: Bug, Tests
