### ISSUE TITLE
Mempool saving should save the current mempoolminfee

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#9258] opened 2016-12-01 19:07 UTC
For the same consistency improvements across restart, Mempool saving should save the current mempoolminfee.  (opening so it isn't forgotten again)

**Comment by sdaftuar** [comment] 2016-12-01 19:09
duplicate of #9103?

**Comment by sipa** [comment] 2016-12-01 20:01
Closing as duplicate of #9103.

**Closed by sipa** 2016-12-01 20:01 UTC
