### ISSUE TITLE
a problem of my bitcoin-core

### ISSUE THREAD

**Issue by areur3ady** [bitcoin/bitcoin#8300] opened 2016-07-03 09:14 UTC
My BTC wallet was `bitcoin core ver. 0.12.1`

After sending my BTC to another address, and waiting for two days status was 0 confirmation, maybe be because the transaction fee was not enough,

So I found a solution from google, `-salvagewallet`, then it seemed to work

But today I try to send my BTC again, after I insert my pass-phrase, a window show up which says

`assertion failed program:C:\........bitcore-qt.exe file:wallet/crypter.cpp,line 190 expression: false`

if click ignore button, it says pass-phrase incorrect.

if click retry, it says runtime error.

don't know how to solve this problem
captured the image here[https://i.stack.imgur.com/OCoLN.jpg](url)

**Comment by MarcoFalke** [comment] 2016-07-03 10:17
`-salvagewallet` is know to cause problems such as #7379 or  #7647. I am assuming you are backing up the wallet.dat regularly so you can always restore to the most recent backup to be fine.


Otherwise you should make sure to shut down bitcoin core, maybe reboot your windows machine just to be save and then backup any wallet.* files from the data dir to external storage.

**Comment by MarcoFalke** [comment] 2016-07-03 10:26
And with regard to your initial problem: Unfortunately we have not yet released a version which supports bump-fee to raise the fee of an unconfirmed transaction according to BIP 125.

Anyway, I am assuming your transaction is not BIP-125-replacable, so you'd have to raise the fee by double spending your unconfirmed transaction. This is conceptually trivial to do, but no user friendly method exists as of today. It is easy to get something wrong and lose bitcoins accidentally. Thus, I think it is better to not provide support for this in this issue tracker.

**Comment by areur3ady** [comment] 2016-07-03 11:55
@MarcoFalke thx first.
i am a newbie, i did not backup before. i know that's necessary, but did not do it.
By removing all wallet.* file out, i have a new clean wallet and a new wallet.dat. i can encrypt this new wallet,and no problem. But no BTC in this wallet.
If replace new wallet.dat by the old one, BTC come back , and problem come back. 

Now checking on the blockchain.info, no record of the 0 confirmation transaction, last time i checked(before i did `-salvagewallet`),  there was a record. Does it meams ,transaction was canceled successfully?

**Comment by MarcoFalke** [comment] 2016-07-03 12:06
>  i am a newbie, i did not backup before. i know that's necessary, but did not do it.

There should also be a `wallet.(timestamp).bak`, which hopefully equals to your old `wallet.dat`.

>  and problem come back. 

According to https://github.com/bitcoin/bitcoin/blob/080457c4ee97e38aa8e59de89bf3d78d1de142aa/src/wallet/crypter.cpp#L189 The wallet is probably corrupted: Some keys decrypt but not all.

**Comment by MarcoFalke** [comment] 2016-07-03 14:02
The bak file ideally is your previous wallet.dat file (just a different name) Make sure to create a secure copy of it.

You can then rename it to wallet.dat (Also backup the current wallet.dat) and you have your previous wallet. After you load this wallet, the node will rebroadcast the transaction because it is not yet confirmed, so you better not connect to the network...

**Comment by areur3ady** [comment] 2016-07-04 09:57
@MarcoFalke May I ask about If restoring to a previous version of wallet.dat, the passphrase will be restored to the previous one too?

beside, still waiting for the transaction to be confirmed.

**Comment by MarcoFalke** [comment] 2016-07-04 09:59
> @MarcoFalke May I ask about If restoring to a previous version of wallet.dat, the passphrase will be restored to the previous one too?

Yes

**Comment by MarcoFalke** [comment] 2016-07-04 10:01
> beside, still waiting for the transaction to be confirmed.

You can create a replacement transaction offline with createrawtransaction (be careful about the fees etc.) and then push it when you are sure everything is correct and the receiver knows what is happening.

**Comment by jonasschnelli** [comment] 2016-07-07 15:22
@areur3ady: could you please update the issue title (use a more precise title) or close the issue if it has been resolved?

**Comment by MarcoFalke** [comment] 2016-07-07 18:06
@jonasschnelli The issue was caused by running salvagewallet on an encrypted wallet. I don't think it is consistently possible to reproduce but might be worth to look into some day...

**Comment by ofry** [comment] 2016-07-07 19:53
I have same issue with unconfirmed transactions too.

**Comment by laanwj** [comment] 2016-07-08 06:30
Closing this issue, it seems to have been resolved.

Problems with unconfirmed transactions should not be reported here. Transactions need enough fee to confirm, and in the end this is up to miners to pick up your transaction, this is not a software issue.

Replace-By-Fee and Child-Pays-For-Parent functionality is being worked on, which will allow bouncing the fee of transactions that don't confirm.

**Closed by laanwj** 2016-07-08 06:30 UTC
Labels: Wallet

**Comment by areur3ady** [comment] 2016-07-09 10:20
@MarcoFalke problem resolved. thanks a lot.

**Comment by Ewan-S** [comment] 2016-07-10 15:32
Could you explain how you've fixed this please areur3ady? I face the same issue.

**Comment by Ewan-S** [comment] 2016-07-10 15:33
Could you explain how you've fixed this please areur3ady? I face the same issue currently on the release version.

**Comment by ZhiweiWang** [comment] 2016-08-07 12:07
@Ewan-S Try bitcoin 0.9.3 may sovle this problem.
