### ISSUE TITLE
Bech32 address not provided when creating a new receiving address

### ISSUE THREAD

**Issue by MatthewLM** [bitcoin/bitcoin#19446] opened 2020-07-04 17:00 UTC
**Expected behavior**

I go to the Receive tab, ensuring that "Generate native segwit (Bech32) address" is selected. I fill the label as "Test Bech32" and then click "Create new receiving address". I expect the address to be a bech32 address

**Actual behavior**

The address is a p2pkh address.

![20200704_174715_bitcoin_no_work](https://user-images.githubusercontent.com/1679965/86517144-87829600-be1e-11ea-937e-b2725eaea523.png)

**To reproduce**

On my own wallet this is reproducible according to the steps above each time.

**System information**

v0.20.0 from bitcoin.org/en/bitcoin-core/ (The issue was present in 0.19.0 too)

Linux Debian 4.19.118-2+deb10u1 (x86-64) HDD
KDE plasmashell 5.14.5

This is using a pre-HD wallet

**Comment by sipa** [comment] 2020-07-04 17:04
Is this a wallet created before v0.5.0?

**Comment by MatthewLM** [comment] 2020-07-04 17:16
Yes, I believe the wallet was created before v0.5.0.

**Comment by sipa** [comment] 2020-07-04 17:41
This is probably the result of the keys in your wallet's keypool being uncompressed. Such keys can't be used in segwit addresses.

**Comment by MatthewLM** [comment] 2020-07-04 17:58
Thanks, that makes sense. I imagined that newer versions would create compressed keys even if there are unused keys in an older wallet. I suppose using `-upgradewallet` would resolve this issue? I'll take a look in the next few days and see if the issue is resolved.

I think it would good to have some warning to users of old wallets that they need to upgrade the wallet to use bech32.

**Comment by MarcoFalke** [comment] 2020-07-04 18:20
Btw, `getwalletinfo` gives you the wallet version and the keypool size (which you might have to drain)

Duplicate of #16178

**Closed by MarcoFalke** 2020-07-04 18:20 UTC
Labels: Bug

**Comment by MatthewLM** [comment] 2020-07-06 14:04
@MarcoFalke @sipa Thanks for your help though there is an issue with using `-upgradewallet`: `Error: DeriveNewSeed: AddKeyPubKey failed`. I imagine the upgrade will fail for encrypted wallets as according to #14422 and that I'll need to wait for the new `upgradewallet` RPC method which shall be coming in 0.21.0?

**Comment by mattpopovich** [comment] 2020-07-26 23:01
> @MarcoFalke @sipa Thanks for your help though there is an issue with using `-upgradewallet`: `Error: DeriveNewSeed: AddKeyPubKey failed`. I imagine the upgrade will fail for encrypted wallets as according to #14422 and that I'll need to wait for the new `upgradewallet` RPC method which shall be coming in 0.21.0?

@MatthewLM I can confirm that #14422 fixed the `Error: DeriveNewSeed: AddKeyPubKey failed` issue for my wallet. The new `upgradewallet` RPC also worked for me. Visit my comment [here](https://github.com/bitcoin/bitcoin/issues/14422#issuecomment-664051272) for more info.
