### ISSUE TITLE
testcase segfaults on gcc 5.1.1 on DragonFlyBSD

### ISSUE THREAD

**Issue by sinetek** [bitcoin/bitcoin#6070] opened 2015-04-27 00:35 UTC
sinetek@blkstar% ./test_bitcoin 
Running 144 test cases...
terminate called after throwing an instance of 'boost::system_error'
Illegal instruction (core dumped)

Investigating.

**Comment by sinetek** [comment] 2015-04-27 01:19
CXXLD    test/test_bitcoin
/usr/lib/gcc50/libssp.so: warning: warning: this program uses gets(), which is unsafe.
gmake  check-TESTS check-local
gmake[3]: Entering directory '/home/sinetek/dev/bitcoin/src'
gmake[4]: Entering directory '/home/sinetek/dev/bitcoin/src'
*** stack smashing detected ***:  terminated
Segmentation fault (core dumped)
FAIL: test/test_bitcoin
============================================================================
Testsuite summary for Bitcoin Core 0.10.99
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to info@bitcoin.org
============================================================================
Makefile:6444: recipe for target 'test-suite.log' failed
gmake[4]: *** [test-suite.log] Error 1
gmake[4]: Leaving directory '/home/sinetek/dev/bitcoin/src'
Makefile:6550: recipe for target 'check-TESTS' failed
gmake[3]: *** [check-TESTS] Error 2
gmake[3]: Leaving directory '/home/sinetek/dev/bitcoin/src'
Makefile:6656: recipe for target 'check-am' failed
gmake[2]: *** [check-am] Error 2
gmake[2]: Leaving directory '/home/sinetek/dev/bitcoin/src'
Makefile:6337: recipe for target 'check-recursive' failed
gmake[1]: *** [check-recursive] Error 1
gmake[1]: Leaving directory '/home/sinetek/dev/bitcoin/src'
Makefile:626: recipe for target 'check-recursive' failed
gmake: *** [check-recursive] Error 1
sinetek@blkstar%

**Comment by theuni** [comment] 2015-04-28 14:03
Is boost also built with gcc 5.1?

**Comment by theuni** [comment] 2015-04-28 15:26
Confirmed that funky things happen when mixing boost built with gcc4 and bitcoin built with gcc5. In my case, bitcoin fails to link.

I suspect this is due to the libstdc++ string abi change. For now, since all projects are likely going to begin running into this situation, I'd file this under "unsupported config". We'll see how distros solve this.

**Comment by sinetek** [comment] 2015-04-28 20:58
Yes, that does seem like the most plausible explanation, now that you mention it.

**Comment by laanwj** [comment] 2015-05-15 17:02
Closing this. Any conflict between code built with gcc4 and gcc5 is a distribution issue.

**Closed by laanwj** 2015-05-15 17:02 UTC
