### ISSUE TITLE
bitcoin-cli: error: couldn't connect to server: EOF reached (code 1)

### ISSUE THREAD

**Issue by BitWaspBitWasp** [bitcoin/bitcoin#10763] opened 2017-07-07 12:31 UTC
sometimes I have the problem(Debian):

# bitcoin-cli listtransactions
error: couldn't connect to server: EOF reached (code 1)
(make sure server is running and you are connecting to the correct RPC port)

How can I fix it ?

**Comment by achow101** [comment] 2017-07-28 20:13
This error happens when bitcoin-cli is unable to connect to the RPC server. Make sure the rpc server is running (bitcoind runs it automatically, with bitcoin-qt, you need the `server=`1 option in your bitcoin.conf file.

**Comment by Start2Bitcoin** [comment] 2018-09-17 21:50
I have the same issue here, while the option server=1 is confirmed in bitcoin.conf file

**Comment by constantinedev** [comment] 2019-04-28 04:38
I have the same problem

**Comment by generalsnout** [comment] 2020-03-19 21:37
How do you edit the bitcoin-cli file?

**Comment by kiminuo** [comment] 2020-06-19 07:41
We have a test machine with Windows 10 and we can confirm that the bug is present in Bitcoin Core 0.19.1 and Bitcoin Core 0.20.0.

Additionally, we know:

* Restart of the daemon does not help to solve the problem (it helps for like 30 seconds and RPC responds for that time being).
* Restart of the machine helps (until it breaks again).
* The bug affects both Qt and daemon.
* There is no useful information in debug.log.
* Node works as expected other than this issue.
* Normally, it takes several weeks until the bug presents itself.

Note: We had Bitcoin Core 0.19.1 running, found the bug, tried to upgrade to avoid the bug but to no avail.

**Comment by SsNipeR1** [comment] 2021-03-21 19:35
It's not fixed in 2021!!!! @bitcoin

**Comment by milkcoke** [comment] 2021-11-15 02:50
## Cause
Maybe you didn't kill all bitcoind process.
so you can't start bitcoind **since another `bitcoind` daemon is already running state** 

You can check it below command

```bash
$ netstat -tnlp
```


## Solution
Kill them all.

#### Case 1. Could find **PID/Program** name
ex) `30375/bitcoind`
```bash
$ kill -9 [PID-of-bitcoind]
```

#### Case 2. Not found **PID/Program** of `bitcoind`

```bash
$ pkill bitcoind
```


---

### start daemon again
```bash
$ bitcoind --datadir=[path-of-data]
```

**Comment by fanquake** [comment] 2022-08-15 09:28
> Normally, it takes several weeks until the bug presents itself.

Re-closing this. Without any concrete steps to reproduce this issue, I'm not sure there's anything we can do here.

**Closed by fanquake** 2022-08-15 09:28 UTC
Labels: Utils/log/libs
