### ISSUE TITLE
ci, error: bitcoind should have exited within 2400s with expected error Error opening block database.

### ISSUE THREAD

**Issue by w0xlt** [bitcoin/bitcoin#23717] opened 2021-12-08 21:07 UTC
Cirrus CI threw the error below in [PR](https://github.com/bitcoin-core/gui/pull/471) .
The error is not reproducible on my machine, where the same test (feature_init.py ) runs successfully.

Link: https://cirrus-ci.com/task/5656508366061568?logs=ci#L3955

```
 test  2021-12-08T20:17:43.635000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_node.py", line 512, in assert_start_raises_init_error
                                       ret = self.process.wait(timeout=self.rpc_timeout)
                                     File "/usr/lib64/python3.6/subprocess.py", line 1469, in wait
                                       raise TimeoutExpired(self.args, timeout)
                                   subprocess.TimeoutExpired: Command '['/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/src/bitcoind', '-datadir=/tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_\u20bf_🏃_20211208_192215/feature_init_39/node0', '-logtimemicros', '-debug', '-debugexclude=libevent', '-debugexclude=leveldb', '-uacomment=testnode0', '-logthreadnames', '-logsourcelocations']' timed out after 2400 seconds
                                   During handling of the above exception, another exception occurred:
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 132, in main
                                       self.run_test()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/feature_init.py", line 172, in run_test
                                       match=ErrorMatch.PARTIAL_REGEX,
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_node.py", line 542, in assert_start_raises_init_error
                                       self._raise_assertion_error(assert_msg)
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_node.py", line 167, in _raise_assertion_error
                                       raise AssertionError(self._node_msg(msg))
                                   AssertionError: [node 0] bitcoind should have exited within 2400s with expected error Error opening block database.
 test  2021-12-08T20:17:43.638000Z TestFramework (DEBUG): Closing down network thread 
 test  2021-12-08T20:17:43.689000Z TestFramework (INFO): Stopping nodes 
 test  2021-12-08T20:17:43.689000Z TestFramework (WARNING): Not cleaning up dir /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20211208_192215/feature_init_39 
 test  2021-12-08T20:17:43.689000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20211208_192215/feature_init_39/test_framework.log 
 test  2021-12-08T20:17:43.690000Z TestFramework (ERROR): 
 test  2021-12-08T20:17:43.690000Z TestFramework (ERROR): Hint: Call /tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/combine_logs.py '/tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20211208_192215/feature_init_39' to consolidate all logs 
 test  2021-12-08T20:17:43.691000Z TestFramework (ERROR): 
 test  2021-12-08T20:17:43.691000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log. 
 test  2021-12-08T20:17:43.691000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues 
 test  2021-12-08T20:17:43.691000Z TestFramework (ERROR): 
....
rpc_bind.py --ipv6                                 | ○ Skipped | 0 s
wallet_upgradewallet.py --legacy-wallet            | ○ Skipped | 0 s
feature_init.py                                    | ✖ Failed  | 2431 s
```

**Comment by fanquake** [comment] 2021-12-08 22:37
Duplicate of #23646.

**Closed** 2021-12-08 22:37 UTC
Labels: Bug
