### ISSUE TITLE
Bitcoind not compiling on MacOS 10.15.5

### ISSUE THREAD

**Issue by y471n** [bitcoin/bitcoin#19510] opened 2020-07-14 05:29 UTC
I followed the instructions on `./docs/build-osx.md` but `make` command results in the following error:

```
qt/trafficgraphwidget.cpp:55:13: error: member access into incomplete type 'QPainterPath'
        path.moveTo(x, YMARGIN + h);
            ^
/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qmatrix.h:54:7: note: forward declaration of 'QPainterPath'
class QPainterPath;
      ^
qt/trafficgraphwidget.cpp:59:17: error: member access into incomplete type 'QPainterPath'
            path.lineTo(x, y);
                ^
/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qmatrix.h:54:7: note: forward declaration of 'QPainterPath'
class QPainterPath;
      ^
qt/trafficgraphwidget.cpp:61:13: error: member access into incomplete type 'QPainterPath'
        path.lineTo(x, YMARGIN + h);
            ^
/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qmatrix.h:54:7: note: forward declaration of 'QPainterPath'
class QPainterPath;
      ^
qt/trafficgraphwidget.cpp:109:22: error: variable has incomplete type 'QPainterPath'
        QPainterPath p;
                     ^
/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qmatrix.h:54:7: note: forward declaration of 'QPainterPath'
class QPainterPath;
      ^
qt/trafficgraphwidget.cpp:116:22: error: variable has incomplete type 'QPainterPath'
        QPainterPath p;
                     ^
/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qmatrix.h:54:7: note: forward declaration of 'QPainterPath'
class QPainterPath;
      ^
5 errors generated.
make[2]: *** [qt/libbitcoinqt_a-trafficgraphwidget.o] Error 1
make[1]: *** [all-recursive] Error 1
```

**Comment by fanquake** [comment] 2020-07-14 05:31
Which branch are you compiling? This issue has been fixed in master, and the fix has been backported to the 0.20 branch (so it will be part of the upcoming 0.20.1 release).

**Comment by y471n** [comment] 2020-07-14 07:04
This was on `v0.19.1rc2` version.

**Comment by fanquake** [comment] 2020-07-14 07:13
> This was on v0.19.1rc2 version.

Ok. The change required to fix the issue is #19097. I'll include that to be backported to `0.19` in #19025. In the mean time, you can apply the one-line patch from #19097 before compiling. I'd also suggest using the `0.19.1` tag rather than the rc.

**Comment by fanquake** [comment] 2020-07-15 03:28
I've added https://github.com/bitcoin/bitcoin/pull/19025/commits/b7e16a82c99768494afb000dd19e308f306a89c3 to #19025.

**Comment by fanquake** [comment] 2020-08-13 07:23
Closing as #19025 has been merged. You can now use the 0.19 branch, and a 0.19.2 release will be available in future.

**Closed by fanquake** 2020-08-13 07:23 UTC
Labels: macOS
