### ISSUE TITLE
gettransaction blockindex does not return height of block that includes transaction

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin/bitcoin#7532] opened 2016-02-13 21:27 UTC
This transaction definitely did not get confirmed in block 634! 

Is the documentation incorrect?

https://bitcoin.org/en/developer-reference#gettransaction

or...

https://github.com/bitcoin/bitcoin/blob/62f2d769e45043c1f262ed45babb70fe237ad2bb/src/wallet/rpcwallet.cpp#L1724

...or I am seriously misunderstanding the object returned by this RPC call?

```
$ gettransaction ef27b4d74497780096b466164e90ac12b1b7bd695246d4b1b232195ed168782e

  {
    "account": "",
    "address": "1DjDpiQaWtTeK4vLFqUH9G3ZkQF2oaxmap",
    "category": "receive",
    "amount": 0.00258000,
    "label": "",
    "vout": 0,
    "confirmations": 7,
    "blockhash": "000000000000000000ca6aa53efc2b89b82eca3e2dfcd942951e2b3fdfae6e67",
    "blockindex": 634,
    "blocktime": 1455395504,
    "txid": "ef27b4d74497780096b466164e90ac12b1b7bd695246d4b1b232195ed168782e",
    "walletconflicts": [
    ],
    "time": 1455394848,
    "timereceived": 1455394848,
    "bip125-replaceable": "no"
  }
```

**Comment by sipa** [comment] 2016-02-13 21:28
It's the position of the transaction in the block. To know the height at
which it confirmed, look at the confirmations.

**Comment by pinheadmz** [comment] 2016-02-13 21:41
Ok. Developer guide is wrong and bitcoind help is a little confusing. Maybe I'll make a few little PRs

**Comment by laanwj** [comment] 2016-02-15 12:39
Seems to work as intended, closing

**Closed by laanwj** 2016-02-15 12:39 UTC
