### ISSUE TITLE
Slow Sync & 2 GUI bugs

### ISSUE THREAD

**Issue by MyS5Droid** [bitcoin/bitcoin#12514] opened 2018-02-23 02:02 UTC
Slow Initial Sync - Every time I open the client (0.15.1 - 64 Bit) it is slow to sync and the network shows 50% of the time it does nothing. Also I suspect my 16-26 peers are not sending data, and suggest peer limit variable so it can be increased at will.

**Possibly related to https://github.com/bitcoin/bitcoin/pull/11560**

Fast Initial Sync - constant data transfer (download) and enough peers so that there is always peers sending data

![btc_slo_net](https://user-images.githubusercontent.com/16307383/36573340-6bd75296-180e-11e8-9910-f7ac02111aef.png)

Download core client from GH and install it, open it.

AMD Phenom X1100T BLACK 6 core processor, 16 GB ram, 1 x 2TB HDD, 1 x 2TB HSSD (Hybrid SSD)

- LONG breaks in network transfer
- Too few peers (IMO, which is why need peer variable)
- Network window looses data every time the time slider is changed... It should adjust and show the current data in the new time frame. And make it track with the debug window closed.
- Port is forwarded (and seen from outside - connections in and out)
- **nice -n -20 bitcoin-qt** does not help
- 6000 DBCache not help
- Added bunch of nodes/seednodes/connects
- **Still have to make sure the userdir is on the HSSD (I confuse the drive manufacturers sometimes)**

**Config:**
server=1
daemon=1

**Debug.log - unable to fit under maximum for every pastebin website in sight :-/**

Thanks for your help :)

**Comment by MyS5Droid** [comment] 2018-02-23 02:08
And more data on the 30 minute timeframe. I will change it now, loose that data and watch it for an hour... ![btc_slo_net2](https://user-images.githubusercontent.com/16307383/36574591-6ea5f918-1814-11e8-92b3-b315c22cfe80.png)
Just a shot of how many users I usually have- I suspect most or all of them are stopping sending data. Suggest adding a "peerlimit" variable so peer limit can be adjusted.
![btc_slo_net3](https://user-images.githubusercontent.com/16307383/36574592-6ed6aca2-1814-11e8-9a5a-446457396e90.png)

**Comment by MyS5Droid** [comment] 2018-02-23 03:55
UPDATE:

I started a compile of a git  clone of the source, and it just completed... Turns out I was not using the HSSD so I moved it to the HSSD, and ran it, and it resync'd the already downloaded part lightning fast, and then I looked at debug window, and peers just kept on climbing higher and higher... I got over 150 peers!

I looked at the version number and it is still the same, maybe a patch was applied or this is a snapshot and version number not yet updated.

I closed  the client, ran the make install, and now I think I should be good...

Thanks all :)

**Comment by MyS5Droid** [comment] 2018-02-23 04:27
Update: I ran **sudo nice -n -10 sudo -u MYUSERNAME bitcoin-qt -data-dir=/path/to/.bitcoin/ -reindex-chainstate**

Now the niceness is changing properly, and the average % per hour doubled.

I think  a combination of things fixed it, the recompile with git clone, moving to HSSD, upping dbcache to 6K, and fixing the niceness to work.

Unfortunately I still have to start back from 0% for the millionth timebut the network stream looks constant :)

**Comment by MyS5Droid** [comment] 2018-02-23 07:03
It appears that... _maybe_ it is fixed... But there seems to be a bug in updating this little modal-like box here, it shows I only 11% but looking at the progress bar at bottom I am clearly at least 50%
![must_be_bug](https://user-images.githubusercontent.com/16307383/36582009-a7e3fe04-183d-11e8-8a38-6a02f4795319.png)

Also there is a bug in the network slider.

This issue is fixed as of a combination of the above methods

**Comment by MyS5Droid** [comment] 2018-02-23 07:28
![nevermind](https://user-images.githubusercontent.com/16307383/36582858-1e84d88c-1841-11e8-9a63-a0dfb583f1a3.png)

I'm a computer programmer and I can understand why a regular person would be frustrated with this... I am frustrated with this...

**Comment by MyS5Droid** [comment] 2018-02-23 18:57
Fail:
![btc_broken](https://user-images.githubusercontent.com/16307383/36611185-acab9740-18a0-11e8-9241-d393379cd247.png)

So the peers/connections drop off and data transfer to 0.

I am closing the wallet, but it has taken so far 1 hour to close ("shutting down, please no close")

I will re-open it again without the reindex option, and hopefully I retain my %age

Help would be appreciated...

**Comment by MyS5Droid** [comment] 2018-02-23 20:53
Crap.... It finished reindexing but data/peers is now 0![btc_broken](https://user-images.githubusercontent.com/16307383/36616368-7de503e0-18b1-11e8-8ba9-f36576bc1615.png)

I closed the wallet and have been waiting for this "do not shut down" window to close for 3-4 hours now... I don't want to close it and have to start back from 0 all over again...

Waiting it out I guess...

**Comment by MyS5Droid** [comment] 2018-02-24 01:07
**Confirmed Working**
I am not sure whether it was the update made in relation to https://github.com/bitcoin/bitcoin/pull/11560 or the changes that I made, or both... But I have solved my problem! Summary of changes for those experiencing the same issue is below.

Proof I am now nearly done downloading the blockchain:
![btc_working](https://user-images.githubusercontent.com/16307383/36623707-e012a1d0-18d4-11e8-9e16-e32dd0b22fd9.png)

**STEPS TO FIX IF YOU EXPERIENCE SAME ISSUE:**

1) Move your /home/user/.bitcoin folder to your best/fastest hard drive.
    - SSD (Solid State) is obviously best choice
    - HSSD (Hybrid Solid State) is second choice
    - HDD (Regular HDD - IDE/SATA - NON SSD) is LAST choice

2) Open Bitcoin-QT with the following command:
    - sudo nice -n -20 sudo -u MYUSERNAME bitcoin-qt -data-dir=/path/to/my/hssd/.bitcoin/ &

3) Wait for download - monitor peer count / network transfer in the debug window (help -> debug)

4) If the peer count drops to 0 and/or the network transfer drops, close Bitcoin but WAIT for the window to disappear - I waited 6 hours for it to disappear. It is basically saving it's state, and if you quit it looses track of where it was. If this happens, close bitcoin-qt, wait 6 hours minimum for window to close, and open it again.


**IF YOU CRASHED OR CLOSED THE WINDOW that says not to close it, you can reindex the data on disk by performing the following:**

1) Run Bitcoin with reindex: sudo nice -n -20 sudo -u MYUSERNAME bitcoin-qt -data-dir=/path/to/my/hssd/.bitcoin/ -reindex-chainstate &

2) Once completed, it may resume downloading Blockchain, OR it may stop all-together (0 peers, 0 data)

3) If it completes and does NOT resume downloading, close Bitcoin-QT again, WAIT AGAIN for window to close

4) Run Bitcoin without reindex: sudo nice -n -20 sudo -u MYUSERNAME bitcoin-qt -data-dir=/path/to/my/hssd/.bitcoin/ &

I hope anyone else has the same success as me, and that this information is helpful. Message me or post here if you need help with this issue.

Thanks to MyS5Droid for the help, and the developers for their hard work in this project!

**Comment by ReneFroger** [comment] 2018-03-04 14:56
Thanks for your detailed report!

Could you close this issue, and report a new short concise bug report which you focus on one bug? It makes easier for everyone to get a good overview what the issue is.

**Closed** 2018-03-22 20:13 UTC
