### ISSUE TITLE
Not able to load multiple wallet more than X number of wallet from RPC

### ISSUE THREAD

**Issue by adneerav** [bitcoin/bitcoin#15017] opened 2018-12-21 14:21 UTC
Hello

I am using Bitcoin core for the multiple wallet functionality. All the wallet access and things I am doing using RPC.

Issue : 
I  am not able to load wallet more than 240(may b depends on system or db limit,Please correct me if I am wrong).

How can I increase the size of the DB or limit so I can load multiple wallet more compare to current limit.

Or is there any way where I can load multiple wallet more compare to current ?

Daemon getting stopped after 240 wallets.

What  I've tried  so far ?
I've added below things by creating DB_CONFIG file in datadirectory 
`set_lk_max_lockers 400000`
`set_lg_regionmax 1048576`

Reference link of above  : https://bitcoin.stackexchange.com/a/70737

**Result** same issue 

If anyone face this type of issue please share or guide on this.

**Comment by promag** [comment] 2019-11-07 16:45
Do you still have the issue with latest release?

Also, looks like all wallets are in the same Berkeley DB environment. Is that a requirement?

**Comment by adneerav** [comment] 2019-11-11 14:44
Hello @promag 

I've tried with latest release(Branch : master)  and build the core ,cli and all.

I kept observing memory utilization by creating , loading and unloading 100 wallets.
Below are the screenshots of memory utilization ( `free -m` )


### **Step 1 (Before Creating or loading any wallet)** :



**_Before creating wallet memory usage states are as below (createwallet by default loading wallets)_**

![Before_loading_wallet](https://user-images.githubusercontent.com/10827664/68592750-d196c000-04b9-11ea-8662-68778c9174ba.png)

---------------------------------------------------------------------------------------------------------

###  **Step 2 (After creating or loaded 100 wallets):** 


**_After creating(loaded wallet) memory utilization states are as below (also check `bitcoin-cli listwallets` and in response its showing all 100 wallets are in response as a loaded wallet)_**

![After_loading_100_wallet](https://user-images.githubusercontent.com/10827664/68592867-19b5e280-04ba-11ea-92d3-fed886554329.png)

**`lsof -p `pidof bitcoind` `**

above command shows all 100 loaded details and processes in this step(after creating wallet) and memory usage increases.

---------------------------------------------------------------------------------------------------------

### **Step 3 (After unloading all loaded wallets(100 wallets):**


After unloading all loaded 100 wallets memory utilization are almost same as loaded wallet. (`bitcoin-cli listwallets` showing all wallets as unloaded empty jsonarray response) .

![After_unloading_100_wallets](https://user-images.githubusercontent.com/10827664/68593032-816c2d80-04ba-11ea-8571-7dbf3f87334a.png)

**`lsof -p `pidof bitcoind` `**
Above command not showing any wallets loaded in steps(after unloading wallet) But memory usage are almost same like loaded wallet, so I guess its not releasing memory

---------------------------------------------------------------------------------------------------------

Based on above test I found still RAM usage is same even after unloading wallet.I've tried with 300+ wallets also but the result were same.

Core and cli built as per mentioned step on [this link](https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#to-build)

 command and config file has below configuration

```
rpcuser=bitcoin
rpcpassword=bitcoinrpcpassword
rpcport=2051
mempoolexpiry=2
daemon=1
rpcworkqueue=128
rpcthreads=128
rpctimeout=220
```

Note : I've removed DB_CONFIG file and all extra setup and tested this things. As I've not found any major change with this DB_CONFIG configuration.

If anyone face this issue and resolved please help/guide me to resolve this.

**Comment by promag** [comment] 2019-11-11 14:52
https://github.com/bitcoin/bitcoin/issues/15017#issuecomment-551163817

Please reply to this. 

> so I guess its not releasing memory

I'm sure someone can explain this better but memory management doesn't work that way - memory isn't claimed after `free()` or `delete`.

Have you tried load -> unload -> load -> ... if there's a leak then the memory should grow consistently.

**Comment by adneerav** [comment] 2019-11-11 15:03
@promag 

> Have you tried load -> unload -> load -> ... if there's a leak then the memory should grow consistently.

Yes, tested above scenario. load -> unload -> load 

Result : memory usage are almost same when i loaded first time not grown too much.

So is it like by unloading wallet will never release memory ?

daemon core stop and start is the only solution to release the memory ?

**Comment by promag** [comment] 2019-11-11 15:06
See this http://www.thecrowned.org/c-delete-operator-really-frees-memory

**Comment by adneerav** [comment] 2019-11-11 15:17
thanks for the link  @promag 

So is there any way where I can increase the limit for loading multiple wallet ?

**Comment by promag** [comment] 2019-11-11 15:27
> Also, looks like all wallets are in the same Berkeley DB environment. Is that a requirement?

In https://bitcoin.stackexchange.com/questions/70734/bitcoin-core-multi-wallet-limit-to-333-wallets/70737#70737 you say that multiple wallets are configured as
```
wallet=wallet-1.dat
```
Can you list the contents of `<datadir>/regtest/wallets` (if regtest, otherwise adjust the path for your case)?

**Comment by adneerav** [comment] 2019-11-11 15:36
@promag  I am loading and unloading wallet using RPC not using configuration file.

Testing with mainnet and path for the wallets is `.bitcoin/wallets`

**Comment by promag** [comment] 2019-11-11 15:39
Where are the wallets?

**Comment by adneerav** [comment] 2019-11-11 15:48
All 1 to 100 wallets are in wallets dir

**Comment by adneerav** [comment] 2019-11-12 05:36
@promag 

**_`.bitcoin` directory_** 

![Screenshot from 2019-11-12 11-03-56](https://user-images.githubusercontent.com/10827664/68644837-3e529e80-053c-11ea-8f19-683dd910a3c2.png)



**_wallets folder contains all the wallets which are created using RPC_**

![Screenshot from 2019-11-12 11-05-45](https://user-images.githubusercontent.com/10827664/68644886-69d58900-053c-11ea-9483-aa1a9fa02bd5.png)

**Comment by willcl-ark** [comment] 2022-11-24 21:33
@adneerav Is this still an issue for you? I have just tried to reproduce this using v24.0 and was unable to make bitcoind crash creating and loading 241 legacy (non-descriptor) BDB wallets. While creating the wallets memory usage increased from 127MB to 5958MB, but bitcoind remained stable.

![-t-15017_001](https://user-images.githubusercontent.com/6606587/203864480-d8f0d53e-2820-4905-96c9-0451b6bfd9ea.png)

I then unloaded all wallets which dropped memory usage back to 188MB, before reloading them via rpc using a loop in fish shell:

```
$ for wallet in (exa $pwd)
      /home/will/src/bitcoin/src/bitcoin-cli -signet loadwallet /tmp/15017/$wallet
      sleep 0.5
  end
```

...which also did not crash bitcoind.

![-t-15017_002](https://user-images.githubusercontent.com/6606587/203865427-c4de2355-ac0f-4a62-a57d-4254dee9abdc.png)

Is there something that you are doing differently to me?

I did not change the following settings from default which I notice you tried.

```
rpcworkqueue=128
rpcthreads=128
rpctimeout=220
```

**Comment by willcl-ark** [comment] 2023-03-27 09:40
@adneerav As there has been no update on this since 2019 (aside from my own follow-up) and I was unable to reproduce this issue with the current version of Bitcoin Core, I'm going to close this for now.

Feel free to comment here if you are still experiencing this problem and want this re-opened to be investigated again.

**Closed by willcl-ark** 2023-03-27 09:40 UTC
Labels: RPC/REST/ZMQ
