### ISSUE TITLE
'minrelaytxfee' option not covered by tests, listed in Debugging/Testing options

### ISSUE THREAD

**Issue by ftrader** [bitcoin/bitcoin#8953] opened 2016-10-18 11:40 UTC
The 'minrelaytxfee' option is described in the 'Fee filtering' section of the 0.13.0 release notes
(https://bitcoincore.org/en/2016/08/23/release-0.13.0) as

> For several years now, Bitcoin Core nodes have used a minimum relay fee rate to help determine what unconfirmed transactions they’ll process, relay, and store in their individual memory pools. Each node gets to decide its own minimum relay fee rate, and if they receive a transaction whose fee rate is below that limit, they don’t add it to their memory pools or relay it to their other peers (although another mechanism called transaction priority historically allowed some transactions that pay a low fee to be accepted into mempools and relayed).

This makes it appear as a fully supported feature, however, it is listed under 'Debugging/Testing options' when the `--help` option is used, and there seems to be no dedicated regression test for it.

From what I can tell it is used in abandonconflict.py, but its functionality is not specifically covered by any unit or regression tests.
### Can you reliably reproduce the issue?

Yes, this applies to 0.13.0 release and 0.13.1 development (current 0.13 branch)
#### Steps to reproduce:
1. run `bitcoind --help`
2. observe where the option 'minrelaytxfee' is listed 
3. inspect the tests under 'qa' and 'src/test'
### Expected behaviour
- existence of at least a 'qa' test specifically covering the option (range of values, checking that it works as described)
- listing of the option under some non-'Debugging/Testing' group such as 'Node relay options', 'Wallet options' or general 'Options'
### Actual behaviour
- 'minrelaytxfee' option is listed under 'Debugging/Testing options', suggesting it is experimental
- 'minrelaytxfee' is used for a side effect in abandonconflict.py
### What version of bitcoin-core are you using?

Official 0.13.0 binary, as well as verified in source code of v0.13.0 tag (commit a402396dce64c42ea73535b7dde4a9164d430438) and current 0.13 branch commit 907c314057b09f1565840237b29a1bd607623ccd .

**Comment by MarcoFalke** [comment] 2016-10-18 12:11
Thanks for raising the issue but the problem is more general and not just limited to `-minrelaytxfee`.
We don't even have smoke tests for every rpc, let alone command line args.


If you are interested in writing a python test for transaction relay policy, make sure it is easy to adjust in case priority gets removed. Moreover, note that there is also a transaction pool min fee, which adjusts when you hit the memory limit in the transaction pool. So for a transaction to be relayed by your node, it must satisfy (priority relay OR minrelaytxfee) AND (transaction pool min fee).

**Comment by jeffrade** [comment] 2017-12-28 22:51
I think we can close this issue.  Once #12001 is merged, `minrelaytxfee ` will be covered in [test/functional/wallet.py](https://github.com/bitcoin/bitcoin/pull/12001/files#diff-cf3e9e3e89528993974616b106b2e560R40)

**Comment by fanquake** [comment] 2017-12-28 23:33
@jeffrade Edit the PR text in #12001 to include "Fixes #8953" and this issue will be automatically closed when that PR is merged.

**Comment by jeffrade** [comment] 2017-12-28 23:45
@fanquake Just updated (sorry, wasn't aware of this feature).  Thank you!

**Comment by MarcoFalke** [comment] 2017-12-29 11:15
@jeffrade Thanks for looking at this. I left a suggestion on your pull so that both -- min relay tx fee *and* mempool min fee -- are tested.

**Closed** 2018-01-04 08:23 UTC
Labels: good first issue, Tests
