### ISSUE TITLE
minrelaytxfee=0 should be allowed for testnet/regtest

### ISSUE THREAD

**Issue by rustyrussell** [bitcoin/bitcoin#9935] opened 2017-03-07 05:23 UTC
### Describe the issue

The lightning spec test vectors include varying transaction fee values, including edge cases like 0.  But this is untestable on bitcoin-core.

#### If so, please list the steps to reproduce below:
1. Add minrelaytxfee=0 to bitcoin.conf
2. Run bitcoind.

### Expected behaviour

No more failing priority for my zero-fee transaction.

### Actual behaviour

Error: Invalid amount for -minrelaytxfee=<amount>: '0'

### What version of bitcoin-core are you using?
Bitcoin Core Daemon version v0.13.99.0-9346f84

### Machine specs:
- OS: Linux
- CPU: Yes
- RAM: Yes

**Comment by MarcoFalke** [comment] 2017-03-07 09:05
Closing as duplicate of #2673

**Closed by MarcoFalke** 2017-03-07 09:05 UTC

**Comment by laanwj** [comment] 2017-03-07 09:56
Also important to mention, as @marcofalke wrote in #2673:

> One of the commits in  #9602 solves this issue.
