### ISSUE TITLE
--descriptor functional tests not working on osx

### ISSUE THREAD

**Issue by sidhujag** [bitcoin/bitcoin#20296] opened 2020-11-03 22:09 UTC
I worked off of master and ran tests based on 95bde34a7186edb559efeeea7f2fbc0fbdd06273 and found that some descriptor tests are failing (not intermittent) on my laptop.

My machine:
late 2019 macbook pro i9 2.4ghz 32gb ram 10.15.7 Catalina. New build, just installed dependencies. No other softwares other than Github, IDE's.

stack trace on feature_nulldummy.py --descriptor (base test passes):

`Traceback (most recent call last):
  File "/Users/jagsidhu/Documents/GitHub/bitcoin/test/functional/test_framework/test_framework.py", line 126, in main
    self.run_test()
  File "/Users/jagsidhu/Documents/GitHub/bitcoin/test/functional/feature_nulldummy.py", line 71, in run_test
    self.nodes[0].generate(427)  # Block 429
  File "/Users/jagsidhu/Documents/GitHub/bitcoin/test/functional/test_framework/test_node.py", line 298, in generate
    return self.generatetoaddress(nblocks=nblocks, address=self.get_deterministic_priv_key().address, maxtries=maxtries)
  File "/Users/jagsidhu/Documents/GitHub/bitcoin/test/functional/test_framework/coverage.py", line 47, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/Users/jagsidhu/Documents/GitHub/bitcoin/test/functional/test_framework/authproxy.py", line 144, in __call__
    response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))
  File "/Users/jagsidhu/Documents/GitHub/bitcoin/test/functional/test_framework/authproxy.py", line 108, in _request
    return self._get_response()
  File "/Users/jagsidhu/Documents/GitHub/bitcoin/test/functional/test_framework/authproxy.py", line 170, in _get_response
    raise JSONRPCException({
test_framework.authproxy.JSONRPCException: 'generatetoaddress' RPC took longer than 30.000000 seconds. Consider using larger timeout for calls that take longer to return. (-344)
2020-11-03T20:47:10.431000Z TestFramework (INFO): Stopping nodes`

errors: 
feature_nulldummy.py --descriptors               | ✖ Failed  | 100 s
rpc_createmultisig.py --descriptors              | ✖ Failed  | 1878 s
wallet_basic.py --descriptors                    | ✖ Failed  | 114 s
wallet_create_tx.py --descriptors                | ✖ Failed  | 95 s
wallet_descriptor.py --descriptors               | ✖ Failed  | 106 s
wallet_groups.py --descriptors                   | ✖ Failed  | 225 s
wallet_importprunedfunds.py --descriptors        | ✖ Failed  | 1718 s

ALL                                              | ✖ Failed  | 18065 s (accumulated) 
Runtime: 4601 s

**Comment by fanquake** [comment] 2020-11-03 23:44
Thanks for reporting, however this is a duplicate of #20183. You should be able to set a `--timeout-factor` and get them passing. Otherwise, lets continue discussion in that issue.

**Closed by fanquake** 2020-11-03 23:44 UTC
Labels: Bug
