### ISSUE TITLE
My bitcoin core money synchronized to December 31, 2013 was stuck, then synchronization can no longer update, how to solve?

### ISSUE THREAD

**Issue by xianglanlan** [bitcoin/bitcoin#10354] opened 2017-05-08 06:20 UTC
![20170506003453](https://cloud.githubusercontent.com/assets/28524124/25792494/7a0be48e-33f9-11e7-83bb-120e7e2cc6b8.png)

**Comment by xianglanlan** [comment] 2017-05-08 12:53
My bitcoin core wallet synchronized to December 31, 2013 was stuck, then synchronization can no longer update, how to solve?

**Comment by MarcoFalke** [comment] 2017-05-08 13:05
Please check your debug.log for possible causes; Alternatively you can upload it here.

You can find the debug.log in your [data dir](https://en.bitcoin.it/wiki/Data_directory#Default_Location).

**Comment by fanquake** [comment] 2017-05-08 13:22
Closing of duplicate of #10356, which has slightly more info.

**Closed by fanquake** 2017-05-08 13:22 UTC
