### ISSUE TITLE
zmq: shutdown/abort when configured with invalid addresses

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#15198] opened 2019-01-18 09:08 UTC
Follow up from #15168.

If a single `zmq` notification is configured with an invalid address, initialisation fails, however bitcoind continues running:
```
src/bitcoind -zmqpubhashblock=tcp://127.0.0.1::28332 -debug=zmq
....
2019-01-18T08:55:28Z BerkeleyEnvironment::Open: LogDir=/Users/xxx/Library/Application Support/Bitcoin/wallets/database ErrorFile=/Users/xxx/Library/Application Support/Bitcoin/wallets/db.log
2019-01-18T08:55:28Z zmq: version 4.2.5
2019-01-18T08:55:28Z zmq: Initialize notification interface
2019-01-18T08:55:28Z zmq: Outbound message high water mark for pubhashblock at tcp://127.0.0.1::28332 is 1000
2019-01-18T08:55:28Z zmq: Error: Failed to bind address, errno=Operation not supported by device
2019-01-18T08:55:28Z zmq: Notifier pubhashblock failed (address = tcp://127.0.0.1::28332)
2019-01-18T08:55:28Z zmq: Shutdown notification interface
2019-01-18T08:55:28Z zmq: Shutdown notifier pubhashblock at tcp://127.0.0.1::28332
2019-01-18T08:55:28Z Cache configuration:
```

If two `zmq` notifications are passed, and the first address is invalid, `bitcoind` aborts:
```
src/bitcoind -zmqpubhashblock=tcp://127.0.0.1::28332 -zmqpubrawtx=tcp://127.0.0.1:28332 -debug=zmq
......
2019-01-18T09:01:13Z BerkeleyEnvironment::Open: LogDir=/Users/xxx/Library/Application Support/Bitcoin/wallets/database ErrorFile=/Users/xxx/Library/Application Support/Bitcoin/wallets/db.log
2019-01-18T09:01:13Z zmq: version 4.2.5
2019-01-18T09:01:13Z zmq: Initialize notification interface
2019-01-18T09:01:13Z zmq: Outbound message high water mark for pubhashblock at tcp://127.0.0.1::28332 is 1000
2019-01-18T09:01:13Z zmq: Error: Failed to bind address, errno=Operation not supported by device
2019-01-18T09:01:13Z zmq: Notifier pubhashblock failed (address = tcp://127.0.0.1::28332)
2019-01-18T09:01:13Z zmq: Shutdown notification interface
2019-01-18T09:01:13Z zmq: Shutdown notifier pubhashblock at tcp://127.0.0.1::28332
2019-01-18T09:01:13Z zmq: Shutdown notifier pubrawtx at tcp://127.0.0.1:28332
Assertion failed: (psocket), function Shutdown, file zmq/zmqpublishnotifier.cpp, line 114.
Abort trap: 6
```

**Comment by promag** [comment] 2019-01-28 19:18
And the expected behavior is to exit cleanly with some status error?

**Comment by mruddy** [comment] 2020-04-21 19:51
i noticed this while testing #18309. specifically, i noticed that zmq initialization would fail when one of the addresses is ipv6 since we don't set the ZMQ_IPV6 socket option: http://api.zeromq.org/4-0:zmq-setsockopt

**Comment by n-thumann** [comment] 2021-05-24 21:47
This should be fixed in https://github.com/bitcoin/bitcoin/pull/17445 and can be closed, doesn't it?

**Closed** 2021-05-25 05:06 UTC
Labels: RPC/REST/ZMQ
