### ISSUE TITLE
walletutil build fails

### ISSUE THREAD

**Issue by jakubtrnka** [bitcoin/bitcoin#18049] opened 2020-02-01 10:54 UTC
Rebuild of Bitcoin core fails after system upgrade - specifically after `boost` library upgrade to version 1.72.0 on ArchLinux.

**Expected behavior**

**Actual behavior**
```
  CXX      wallet/libbitcoin_wallet_a-walletutil.o
wallet/walletutil.cpp: In function ‘std::vector<boost::filesystem::path> ListWalletDir()’:
wallet/walletutil.cpp:77:23: error: ‘class boost::filesystem::recursive_directory_iterator’ has no member named ‘level’
   77 |         } else if (it.level() == 0 && it->symlink_status().type() == fs::regular_file && IsBerkeleyBtree(it->path())) {
      |                       ^~~~~
make[2]: *** [Makefile:9093: wallet/libbitcoin_wallet_a-walletutil.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/kuba/Apps/bitcoin/src'
make[1]: *** [Makefile:13764: all-recursive] Error 1
make[1]: Leaving directory '/home/kuba/Apps/bitcoin/src'
make: *** [Makefile:773: all-recursive] Error 1

```

**To reproduce**
```
./autogeh.sh
contrib/install_db4.sh `pwd`
export BDB_PREFIX='/home/kuba/Apps/bitcoin/db4'
./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include"
make -j6
```

**System information**
Arch linux, system update on Feb 1 (boost lib upgraded from 1.71 to 1.72)
Bitcoin Core v0.19.0.1

**Patch that fixes this**
```
diff --git a/src/wallet/walletutil.cpp b/src/wallet/walletutil.cpp
index 04c2407a8..ead24cd7c 100644
--- a/src/wallet/walletutil.cpp
+++ b/src/wallet/walletutil.cpp
@@ -74,7 +74,7 @@ std::vector<fs::path> ListWalletDir()
         if (it->status().type() == fs::directory_file && IsBerkeleyBtree(it->path() / "wallet.dat")) {
             // Found a directory which contains wallet.dat btree file, add it as a wallet.
             paths.emplace_back(path);
-        } else if (it.level() == 0 && it->symlink_status().type() == fs::regular_file && IsBerkeleyBtree(it->path())) {
+        } else if (it.depth() == 0 && it->symlink_status().type() == fs::regular_file && IsBerkeleyBtree(it->path())) {
             if (it->path().filename() == "wallet.dat") {
                 // Found top-level wallet.dat btree file, add top level directory ""
                 // as a wallet.
```

**Comment by fanquake** [comment] 2020-02-01 10:56
This is a duplicate of #17973 and #17856. It's fixed in master, and the fix will be released with 0.19.1.

**Closed by fanquake** 2020-02-01 10:56 UTC
Labels: Bug
