### ISSUE TITLE
Display fee per bytes instead of kilobytes or allow customizing this

### ISSUE THREAD

**Issue by streamofstars** [bitcoin/bitcoin#11661] opened 2017-11-11 13:36 UTC
I believe the transaction fee section of the Send window should display fees in BTC per byte (B) not per kilobyte (kB). Most fee calculator websites provide data in Bytes not in kilobytes (eg. https://bitcoinfees.earn.com/). Currently users can change currency units (BTC, mBTC, uBTC) but not data units. Recalculating automatically from kB to B is simple. Manually, it is easy to make a stupid mistake and either pay terribly too much fee or far below the required amount. If developers have their reasons to keep data units in kB please at least allow users to customize that in Settings as it has been done for Bitcoin units.

As of 2017-11-11 I am using Bitcoin Core version v0.15.0.0-g3751912e8e (64-bit) from official PPA for Ubuntu.

**Comment by invariant** [comment] 2017-11-11 16:05
Possibly duplicate of #11564

**Comment by KibbledJiveElkZoo** [comment] 2017-11-13 06:35
I am in favor of having the option of entering the transaction fee in satoshis per virtual size byte.

**Comment by Sjors** [comment] 2017-12-06 13:08
Duplicate of #11564 as @invariant points out.

**Comment by jnewbery** [comment] 2018-03-30 14:05
Closing as a duplicate

**Closed by jnewbery** 2018-03-30 14:05 UTC
Labels: GUI
