### ISSUE TITLE
Cross Compilation not working

### ISSUE THREAD

**Issue by njbrown09** [bitcoin/bitcoin#10306] opened 2017-05-01 16:01 UTC
im trying to cross compile windows bitcoin-qt.exe on ubuntu. When i try to run it on windows, it just goes "Bitcoin-qt stopped working". Im on windows 10 64bit

**Comment by fanquake** [comment] 2017-05-02 05:42
Looks like a duplicate of #8732.

**Comment by Pantau123** [comment] 2017-05-13 19:16
I have the following error when i want to compile it
`xxxxx@DESKTOP:/mnt/e/Projects/bitcoin/depends$ make HOST=x86_64-w64-mingw32
Fetching ccache-3.3.4.tar.bz2 from https://samba.org/ftp/ccache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   261  100   261    0     0    589      0 --:--:-- --:--:-- --:--:--   589
100  341k  100  341k    0     0   325k      0  0:00:01  0:00:01 --:--:-- 5349k
/mnt/e/Projects/bitcoin/depends/work/download/native_ccache-3.3.4/ccache-3.3.4.tar.bz2.temp: OK
Extracting native_ccache...
/mnt/e/Projects/bitcoin/depends/sources/ccache-3.3.4.tar.bz2: OK
Preprocessing native_ccache...
Configuring native_ccache...
/bin/sh: 1: Syntax error: "(" unexpected
funcs.mk:242: die Regel für Ziel „/mnt/e/Projects/bitcoin/depends/work/build/x86_64-w64-mingw32/native_ccache/3.3.4-6ba1
8ce3292/./.stamp_configured“ scheiterte
make: *** [/mnt/e/Projects/bitcoin/depends/work/build/x86_64-w64-mingw32/native_ccache/3.3.4-6ba18ce3292/./.stamp_config
ured] Fehler 2`

**Closed** 2017-08-13 02:30 UTC
Labels: Build system, Windows
