### ISSUE TITLE
macOS reports error on shutdown of GUI

### ISSUE THREAD

**Issue by xjmzx** [bitcoin/bitcoin#26490] opened 2022-11-11 13:34 UTC
macOS reports error on shutdown of GUI. "Bitcoin Core quit unexpectedly..." Although this may be hardware related , memory and cpu load seem normal (screenshots and logs attached.)

**Expected behavior**

Application closes without error message.

**Actual behavior**

Application quits (and restarts without error or corruption of data) but message persists.

**To reproduce**

The error message seems to persist every time under normal conditions, (closing the application invokes the message "Bitcoin Core is shutting down, do not shut down the computer until this window has disappeared" Then opens fine on relaunch.

**System information**

Bitcoin Core           23.0.0
Version:               23.0.0 (23.0.0)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]

OS Version:            macOS 13.0 (22A380)

[log2022-11-11.txt](https://github.com/bitcoin/bitcoin/files/9990546/log2022-11-11.txt)
<img width="280" alt="Screenshot 2022-11-11 at 20 51 52" src="https://user-images.githubusercontent.com/1854925/201350529-5164f0ad-3781-4849-8914-09ddc8f760e2.png">
<img width="631" alt="Screenshot 2022-11-11 at 21 24 41" src="https://user-images.githubusercontent.com/1854925/201350606-918c0588-9f7f-4304-a7eb-fbca54ad3f7f.png">
<img width="615" alt="Screenshot 2022-11-11 at 21 24 48" src="https://user-images.githubusercontent.com/1854925/201350618-3e7d2e65-7fb8-4c7d-9651-a77c0a11b56a.png">

**Comment by hebasto** [comment] 2022-11-11 14:35
@xjmzx 

> Bitcoin Core 23.0.0

Is it reproducible with the latest v24.rc3 or rc4? If so, what are exact steps to reproduce the issue?

**Comment by daniel-andradec** [comment] 2022-11-11 16:21
I have exactly the same problem, I guess it started happening after macOS Ventura update. Currently I've got macOS 13.0.1, the latest version. Running on an Intel MA.

**Comment by xjmzx** [comment] 2022-11-11 16:44
@hebasto Was v23.0.0 installed with homebrew.
Compiling release candidate, will test and get back.

**Comment by daniel-andradec** [comment] 2022-11-11 16:50
I can't test it right now, but I can do it later if needed. I guess @xjmzx testing will be enough for now, since the issue is exactly the same.

**Comment by xjmzx** [comment] 2022-11-11 17:28
@hebasto Compiled v24.0rc4 and same error occured. 
The error occurs on choosing either menu > Quit Bitcoin Core, or command + q.
Looking at other operations, the chain is fully synced to tip, peers are connected.
I waited for a while on second close with menu > quit.

logs..

2022-11-11T17:25:21Z [rpc] Interrupting RPC
2022-11-11T17:25:21Z [rpc] Stopping RPC
2022-11-11T17:25:21Z [rpc] RPC stopped.
2022-11-11T17:25:21Z [rpc] Interrupting HTTP RPC server
2022-11-11T17:25:21Z tor: Thread interrupt
2022-11-11T17:25:21Z i2paccept thread exit
2022-11-11T17:25:21Z Shutdown: In progress...
2022-11-11T17:25:21Z opencon thread exit
2022-11-11T17:25:21Z addcon thread exit
2022-11-11T17:25:21Z torcontrol thread exit
2022-11-11T17:25:21Z [rpc] Stopping HTTP RPC server
2022-11-11T17:25:21Z net thread exit
2022-11-11T17:25:21Z msghand thread exit
2022-11-11T17:25:22Z DumpAnchors: Flush 2 outbound block-relay-only peer addresses to anchors.dat started
2022-11-11T17:25:22Z DumpAnchors: Flush 2 outbound block-relay-only peer addresses to anchors.dat completed (0.02s)
2022-11-11T17:25:22Z scheduler thread exit
2022-11-11T17:25:24Z [wallet/...] Releasing wallet
2022-11-11T17:25:24Z [wallet/...] Releasing wallet
2022-11-11T17:25:24Z [wallet/...] Releasing wallet
2022-11-11T17:25:24Z [wallet/...] Releasing wallet
2022-11-11T17:25:24Z [wallet/...] Releasing wallet
2022-11-11T17:25:24Z [wallet/...] Releasing wallet
2022-11-11T17:25:24Z [wallet/...] Releasing wallet
2022-11-11T17:25:24Z [wallet/...] Releasing wallet
2022-11-11T17:25:24Z [specter/...] Releasing wallet
2022-11-11T17:25:24Z [specter/...] Releasing wallet
2022-11-11T17:25:24Z [specter/...] Releasing wallet
2022-11-11T17:25:24Z [sparrow] Releasing wallet
2022-11-11T17:25:24Z [wallet/...] Releasing wallet
2022-11-11T17:25:24Z [sparrow] Releasing wallet
2022-11-11T17:25:24Z [wallet/...] Releasing wallet
2022-11-11T17:25:24Z [...] Releasing wallet
2022-11-11T17:25:24Z [specter/...] Releasing wallet
2022-11-11T17:25:25Z [jm_wallet] Releasing wallet
2022-11-11T17:25:25Z [default wallet] Releasing wallet
2022-11-11T17:25:25Z Shutdown: done

There's a fair few wallet files. Filenames are omitted [...] 
Will check back tomorrow in case you need any further info.

**Comment by hebasto** [comment] 2022-11-11 19:18
Does closing all wallets prior to shutting down help?

**Comment by daniel-andradec** [comment] 2022-11-11 19:20
I never have a wallet open, so it may not have anything to do with it.

**Comment by xjmzx** [comment] 2022-11-12 02:05
I took out all but one of the wallets which gave the expected warning that they are missing. Then closed after synced fully. Same result I'm afraid.

macOS 13.0 (22A380)

**Comment by xjmzx** [comment] 2022-11-12 06:39
Oddly, I just successfully closed the application without error :/

**Comment by Blessme102** [comment] 2022-11-12 10:31
@hebasto Please I just got bitcoin core software installed on my MacBook but it can't be opened
<img width="328" alt="Screenshot 2022-11-12 at 05 28 33" src="https://user-images.githubusercontent.com/118021354/201470073-853d4bf5-652c-4e5a-bd6f-dee4b34b89eb.png">

**Comment by kouloumos** [comment] 2022-11-12 10:37
> hebasto Please I just got bitcoin core software installed on my MacBook but it can't be opened 

@Blessme102 what you are reporting seems unrelated to this issue but please check https://github.com/bitcoin/bitcoin/issues/24140 for the issue you are describing. Your issue is probably related to https://github.com/bitcoin/bitcoin/issues/15774.

**Comment by Blessme102** [comment] 2022-11-12 10:40
@kouloumos  Okay. thanks

**Comment by jarolrod** [comment] 2022-11-15 15:18
@john-moffett your commit seems to resolve the issue, mind opening up a pr in the gui repo?

**Comment by john-moffett** [comment] 2022-11-15 15:30
@jarolrod I think there's actually a cleaner way to fix it than the one I already committed. I'll open a PR with that new method on the GUI repo within a couple hours. 

The problem is that the menu bar subscribes to `QApplication` notifications, one of which gets sent after the main window (along with the menu bar) gets destroyed, but before the `QApplication` gets destroyed. My first solution was to unsubscribe to all of the notifications in the main window's destructor, but that's somewhat brittle. A better solution would have the subscription cancelled automatically when the main window is destroyed, which would happen if you pass in a context to the `connect` function that subscribes to the signals.

**Closed** 2022-11-17 14:30 UTC
Labels: Bug, GUI, macOS

**Comment by mateusgalasso** [comment] 2022-11-17 21:27
the error  continuous for me
Some solution?

**Comment by john-moffett** [comment] 2022-11-17 21:32
@mateusgalasso  Can you attach a log like the original poster did?

**Comment by mateusgalasso** [comment] 2022-11-17 21:51
> @mateusgalasso Can you attach a log like the original poster did?

2022-11-17T21:50:20Z UpdateTip: new best=0000000000000383ad5eae5815f5b65d3e102e79b22cdece2d2867f9d9cfd27c height=142625 version=0x00000001 log2_work=66.343656 tx=1373977 date='2011-08-26T05:26:05Z' progress=0.001763 cache=61.8MiB(454071txo)
2022-11-17T21:50:20Z UpdateTip: new best=0000000000000324fc4102f1f309ef23790ebfa7279b0df7ee466e90452436c7 height=142626 version=0x00000001 log2_work=66.343776 tx=1373982 date='2011-08-26T05:26:21Z' progress=0.001763 cache=61.8MiB(454076txo)
2022-11-17T21:50:20Z UpdateTip: new best=00000000000007664fadff938474752a43f16b6f9304398ed4729c6e28da1e93 height=142627 version=0x00000001 log2_work=66.343895 tx=1373984 date='2011-08-26T05:27:07Z' progress=0.001763 cache=61.8MiB(454078txo)
2022-11-17T21:50:20Z UpdateTip: new best=00000000000001c570b945541100c0ff0a04449475fafcd8c3d237d4e61b4a39 height=142628 version=0x00000001 log2_work=66.344015 tx=1374015 date='2011-08-26T05:39:35Z' progress=0.001763 cache=61.8MiB(454089txo)
2022-11-17T21:50:20Z UpdateTip: new best=00000000000009004852481fe4afd6214d089f10f43bd52579c002fdf152f903 height=142629 version=0x00000001 log2_work=66.344134 tx=1374018 date='2011-08-26T05:40:34Z' progress=0.001763 cache=61.8MiB(454211txo)
2022-11-17T21:50:20Z UpdateTip: new best=00000000000007580a916d619dc909037682ab851b5529c7e5afbf6270520030 height=142630 version=0x00000001 log2_work=66.344254 tx=1374129 date='2011-08-26T06:02:09Z' progress=0.001763 cache=61.8MiB(454288txo)
2022-11-17T21:50:20Z UpdateTip: new best=00000000000003c721370f17203829f945491e36a7a38a28c7e97bdcc00d68cd height=142631 version=0x00000001 log2_work=66.344373 tx=1374174 date='2011-08-26T06:12:55Z' progress=0.001763 cache=61.8MiB(454424txo)
2022-11-17T21:50:20Z FileCommit: fcntl F_FULLFSYNC failed: 25
2022-11-17T21:50:20Z ERROR: Flush: failed to commit file 3
2022-11-17T21:50:20Z *** Flushing block file to disk failed. This is likely the result of an I/O error.
2022-11-17T21:50:20Z Error: A fatal internal error occurred, see debug.log for details

**Comment by hebasto** [comment] 2022-11-18 15:04
@mateusgalasso 
> The data directory is on external SSD, that is ok?

https://github.com/bitcoin/bitcoin/issues/26530#issuecomment-1320141605

**Comment by daniel-andradec** [comment] 2022-11-24 18:33
Hi, I've just updated to v24, and this issue was not solved. Was the fix supposed to be on this version? Using the same computer I said above. Thanks!

**Comment by hebasto** [comment] 2022-11-24 22:56
> Hi, I've just updated to the latest v24 release, and this issue was not solved. Was the fix supposed to be on this version? Using the same computer I said above. Thanks!

The [fix](https://github.com/bitcoin-core/gui/pull/680) was [backported](https://github.com/bitcoin/bitcoin/pull/26523) to the 24.x branch and it will be a part of the next minor or patch release (not the recent [v24.0](https://github.com/bitcoin/bitcoin/releases/tag/v24.0)).

**Comment by daniel-andradec** [comment] 2022-11-24 22:59
> > Hi, I've just updated to the latest v24 release, and this issue was not solved. Was the fix supposed to be on this version? Using the same computer I said above. Thanks!
> 
> 
> 
> The [fix](https://github.com/bitcoin-core/gui/pull/680) was [backported](https://github.com/bitcoin/bitcoin/pull/26523) to the 24.x branch and it will be a part of the next minor or patch release (not the recent [v24.0](https://github.com/bitcoin/bitcoin/releases/tag/v24.0)).

Ok! Thank you!

**Comment by asylejmani** [comment] 2022-12-06 21:19
@hebasto I created a new issue [here](https://github.com/bitcoin/bitcoin/issues/26650) about:

> 2022-11-17T21:50:20Z FileCommit: fcntl F_FULLFSYNC failed: 25

as I still see the same issue both via GUI and CLI in MacOS Ventura! Cheers!

**Comment by asylejmani** [comment] 2022-12-06 21:30
@sipa I don't have 24.0.1 as I don't compile it myself (should start doing it though), but looking at this this [issue](https://github.com/bitcoin/bitcoin/issues/26455) the one I created is already closed as it turns out to be a Ventura issue instead! I'm gonna try the 13.1 public beta

**Comment by asylejmani** [comment] 2022-12-06 21:35
No worries, maybe I was also wrong to point it here too but I was addressing hebasto in a comment above somewhere, saying:

> Mind submitting a new issue?
