### ISSUE TITLE
exponential slowdown while reindexing / importing

### ISSUE THREAD

**Issue by smurfix** [bitcoin/bitcoin#7271] opened 2016-01-01 19:26 UTC
I have client 0.11.2 (32-bit Linux, fresh download). I'm reindexing after a crash, or re-importing the blcokchain, doesn't matter.
The problem: at first it zipped along quite fast, but now I'm at block 300000 and it takes 3sec to process a single block.

If this slowdown continues I expect the full blockchain to be imported some time after the sun blows up in a couple billion years, so I assume there must be a  problem somewhere.

I found one strange message in the debug log:
```
2016-01-01 18:49:20 Leaving block file 133: CBlockFileInfo(blocks=0, size=0, heights=0...0, time=1970-01-01...1970-01-01
```
no idea whether that's related to my problem.

**Comment by sipa** [comment] 2016-01-01 20:20
The reason is that before the last checkpoint, signatures are not verified.
Once you cross that point, they are, so you suddenly notice a slowdown at
that point.

In 0.12, signature verification is made several times faster, so the impact
should be reduced.

The message about an empty file is a known problem, but not dangerous.

**Comment by smurfix** [comment] 2016-01-01 23:12
Thank you. So I guess I'll get the 0.12 branch and build that.

**Comment by jonasschnelli** [comment] 2016-01-04 08:10
Closing. Seems to be the expected behavior and not an issue.

**Closed by jonasschnelli** 2016-01-04 08:10 UTC
