### ISSUE TITLE
[QT] - Send-all Button

### ISSUE THREAD

**Issue by laudaa** [bitcoin/bitcoin#11033] opened 2017-08-11 20:14 UTC
I think that a send-all button, which shouldn't be hard to implement, would be beneficial to the GUI. Generally, when people consolidate UTXO (for example) they select a number of inputs and then copy paste the full amount (or manually type it) into the amount field before sending. This is somewhat inconvenient, and other wallets (e.g. Copay, Mycelium) have this feature already.

Thanks.

**Comment by jonasschnelli** [comment] 2017-08-12 09:57
The current way (enter full available amount) and select "subtract fee from amount" is IMO relatively easy.
An extra button "send all" would do exactly that (type in the available balance and select the SFFA checkbox).
Could be handy though not sure...

**Comment by laudaa** [comment] 2017-08-12 19:17
The current way that it is set up is easy for sure, but it has an inconvenient and redundant step for a frequent action whilst the wallet should be aiming for ease of use/simplicity in that regard. The reasons for which I am suggesting it is that:
1) I find it inconvenient considering the number of times that I've done this, and I think others feel the same way.
2) I've noticed the feature implemented in other wallets (previously mentioned), and am quite fond of it.

**Comment by aunyks** [comment] 2017-08-15 21:05
@laudaa Just to be clear, this "Send-All Button" would completely empty the wallet right?

**Comment by laudaa** [comment] 2017-08-16 18:24
@aunyks If there were no inputs selected (coin control), then it would pull the total wallet balance. If there were inputs selected, then it would pull the total value of those inputs.

**Comment by laanwj** [comment] 2017-08-17 20:37
I'd like this feature too. I'm not sure what is exactly how you propose to offer this in the GUI but FWIW personally I'd prefer a button that fills in the total amount of all selected utxos in "amount" and auto-selects "subtract fee from amount" above an alternative send button.
This makes it immediately and intuitively clear what happens when the user clicks it.

**Comment by laanwj** [comment] 2017-08-17 20:38
The biggest challenge here is probably how to add this without creating an ugly wart big button in the GUI. Some subtle icon or such.

**Comment by promag** [comment] 2017-08-17 21:05
Concept ACK.

BTW should the same feature be available thru RPC? Like an alias for all instead of an amount?

**Comment by promag** [comment] 2017-08-18 07:31
> fills in the total amount of all selected utxos in "amount" and auto-selects "subtract fee from amount"

@laanwj that's not "atomic":
- can fail if meanwhile some utxo is spent
- can leave balance if meanwhile an utxo is new.

Should "send all button" prevent multiple recipients?

Or should the "send all button" be in each recipient and when activated it sets `recipient_amount = balance - sum_other_recipient_amounts` and check "subtract fee from amount"?

**Comment by laanwj** [comment] 2017-08-18 09:41
> @laanwj that's not "atomic":

That's exactly why I prefer it that way. Say, you get a large payment the last microsecond and that would make you reconsider whether you really want to send everything away. I would see it more as "send everything I know about now".
As for "can fail if meanwhile some utxo is spent", well, a user shouldn't be spending anything while using the wallet GUI.

**Comment by MeshCollider** [comment] 2017-08-19 00:29
>The biggest challenge here is probably how to add this without creating an ugly wart big button in the GUI. Some subtle icon or such.

What about just clicking on the `Balance: X.XXXXXXXX BTC` on the bottom right of the screen to do it? Or is that not clear enough. Also then the issue is dealing with multiple recipients like @promag mentioned

**Comment by laanwj** [comment] 2017-08-19 06:04
> What about just clicking on the Balance: X.XXXXXXXX BTC on the bottom right of the screen to do it?

Would be an idea, though I don't think it updates to the right amount available when coin control is used and inputs are selected manually? I don't think so at least.

**Comment by jaybny** [comment] 2017-10-19 19:08
I can tackle this one

**Comment by achow101** [comment] 2017-10-19 19:14
@jaybny This is already being done in both #11316 and #11098, I don't think we need a third alternative. It would be better for you to review either of those two (or both) and leave comments and suggestions.

**Comment by promag** [comment] 2017-10-19 19:16
@jaybny there are 2 proposals already, care to review those first?

**Comment by jaybny** [comment] 2017-10-19 21:29
sure.. im still working on compiling bitcoin with the gui.. how can we see which issues are being worked on? i only picked this because of the "good for first issue" tag.. and because ive been working with qt recently

**Comment by achow101** [comment] 2017-10-19 21:32
@jaybny Generally threads that fix a problem will reference the issue that is being fixed. If you look up earlier in this thread, you will see "This was referenced on <..>". You can then click on the PR or Issue that referenced this issue and see what they are doing and whether they fix this issue. If you don't see those, then the issue probably does not have an open PR to handle it. You can search through the list of open PRs to see if one is handling it but did not reference the issue.

**Comment by jaybny** [comment] 2017-10-19 21:37
this is prob offtopic, but a PR is issued when you start on a fix or when your done and ready to merge?

**Comment by MeshCollider** [comment] 2017-10-20 04:37
@jaybny you can make a PR whenever you want, but usually you would choose to open one when its ready yes, otherwise you would write WIP (work in progress) in the title

**Comment by promag** [comment] 2017-11-11 01:35
@MarcoFalke close?

**Comment by laudaa** [comment] 2017-11-11 06:04
Yes, close this. Nicely done.

**Comment by MeshCollider** [comment] 2017-11-11 06:18
@laudaa you should be able to close this yourself since you made the issue :)

**Closed** 2017-11-11 07:27 UTC
Labels: good first issue, GUI
