### ISSUE TITLE
ci error: `interface_usdt_validation.py` fails

### ISSUE THREAD

**Issue by w0xlt** [bitcoin/bitcoin#25801] opened 2022-08-08 01:33 UTC
One of CI checks in #25616 fails:
https://cirrus-ci.com/task/6722929781112832?logs=ci#L3954

```
2022-08-08T00:57:43.281000Z TestFramework (INFO): handle_blockconnected(): ConnectedBlock(hash=1e25ca1f62b4117a20995652ca8ebba755a779290935c4eb3fc1f121048cab4d height=201, transactions=1, inputs=1, sigops=0, duration=296)
2022-08-08T00:57:43.317000Z TestFramework (INFO): check that we traced 2 blocks
2022-08-08T00:57:43.317000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 133, in main
    self.run_test()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/interface_usdt_validation.py", line 131, in run_test
    assert_equal(BLOCKS_EXPECTED, blocks_checked)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 56, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(2 == 0)
```

I cannot reproduce this error on my machine. The test works as expected.

**Comment by fanquake** [comment] 2022-08-08 05:59
Dupe of #25764.

**Closed** 2022-08-08 06:00 UTC
