### ISSUE TITLE
travis failure in p2p-segwit.py not(b'bad-txns-vout-negative' == b'bad-witness-nonstandard')

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#11953] opened 2017-12-19 21:38 UTC
This keeps popping up from time to time on travis. The relevant log excerpt:

```
2017-12-19 17:52:57.940000 TestFramework (INFO): Testing detection of non-standard P2WSH witness
2017-12-19 17:52:58.710000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "./test/functional/test_framework/test_framework.py", line 118, in main
    self.run_test()
  File "./test/functional/p2p-segwit.py", line 1943, in run_test
    self.test_non_standard_witness()
  File "./test/functional/p2p-segwit.py", line 1827, in test_non_standard_witness
    test_transaction_acceptance(self.nodes[1].rpc, self.std_node, p2wsh_txs[0], True, False, b'bad-witness-nonstandard')
  File "./test/functional/p2p-segwit.py", line 48, in test_transaction_acceptance
    assert_equal(p2p.last_message["reject"].reason, reason)
  File "./test/functional/test_framework/util.py", line 38, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(b'bad-txns-vout-negative' == b'bad-witness-nonstandard')
```

Most recent example: https://travis-ci.org/bitcoin/bitcoin/jobs/318711688

**Comment by laanwj** [comment] 2018-01-11 13:24
Is this a duplicate of #11696?

**Closed** 2018-01-11 13:48 UTC
Labels: Tests

**Comment by MarcoFalke** [comment] 2018-01-11 13:51
No, I don't think it is a duplicate.
