### ISSUE TITLE
unconfirmedbalance shows fake amount (50.xxxxx btcs)

### ISSUE THREAD

**Issue by BitcoinUser2016** [bitcoin/bitcoin#7690] opened 2016-03-15 01:14 UTC
Hi,

I run a bitcoin server which have acting strange the latest 3-4 days. For some reason the unconfirmed balance when running bitcoin-cli getunconfirmedbalance shows up as 50.589243 BTC which of course isn't true.

How do I reset this? Why did this occur? Tried both v0.12 and v0.12.99, same problem.

Thanks in advance,
Nori

**Comment by kirkalx** [comment] 2016-03-15 07:10
Are you sure the value is wrong? What sort of result are you expecting?

**Comment by MarcoFalke** [comment] 2016-03-15 11:19
Did you try `listunspent 0` to see if there is anything suspicious.

**Comment by BitcoinUser2016** [comment] 2016-03-15 12:30
Yes, 100%. I mean. I've never had this problem before in a year and the volume of btc is exactly the same. It's been stuck at 255+ BTC for about 5 days now all of a sudden. And there is no way 255 BTC is incoming to an adress. Or that they havent been confirmed by now. When it first happened listtransactions didn't list a big tranasction incoming either.

For example: When someone sends 1 BTC getunconfirmedbalance will show as 256 BTC and then go down to 255 BTC again once its confirmed.

Yes MarcoFalke, Iv'e tried it. The weird thing about this command is that it lists lots of "confirmations: 0"-transactions which already have thousands of confirmations. Some dated 2015 with over 25.000+ confirmations and still says "confirmations: 0". Like this one: 
https://www.blocktrail.com/BTC/address/16F4Bzkk6xaFktqSopACKn18rCRWCWgdW3/transactions
    "txid": "a34a18358937a5b9a9fff8281491de57a9c7942217d43bb469eef5d5113d50fc",
    "vout": 1,
    "address": "16F4Bzkk6xaFktqSopACKn18rCRWCWgdW3",
    "account": "usedaddress",
    "scriptPubKey": "76a91439811d6af01a4337137356cb88488f9f1b6348ed88ac",
    "amount": 0.23509566,
    "confirmations": 0,
    "spendable": true
This one shouldn't be there at all, right?

It all started around 3 days after I've upgraded from 0.11 to 0.12. My wallet is around 230 MB. Should I do rescan/reindex? I rather not since it takes lots of time ;(

**Comment by MarcoFalke** [comment] 2016-03-15 12:37
Conflicted transactions count toward the unconfirmed balance, IIRC.

**Comment by sipa** [comment] 2016-03-15 12:41
That transaction is a double spend that did not make it into the block
chain. 0.12 deals differently with those; see the release notes for more
information.

Running with -rescan once will fix the problem, by explicitly marking it as
conflicting with the block chain. After that, you can choose to remove such
transactions from the wallet with `abandontransaction`.

**Comment by BitcoinUser2016** [comment] 2016-03-15 12:47
Forgot to thank you all for your help guys.

How and why does a transraction become conflicted? And how could this happen in a minute? Because I remember checking the confirmed balance 30 mins or so prior to this. And suddenly it started saying 255.359391 BTC+. 

Will do a rescan then. Any idea how long this can take?
Also: Is it dangerous to keep running my bitcoind while having these "issues"?

**Comment by sipa** [comment] 2016-03-15 12:56
You always had these conflicting transactions in your wallet. Up to 0.11
they were just not counted towards your balance, as a heuristic was
determining they couldn't be accepted (they were not accepted into your own
mempool). Due to the large changes that the mempool underwent in 0.12, that
heuristic is no longer usable, so the wallet now tracks conflicts by
itself. A rescan will let your wallet go through history and gather that
information.

**Comment by BitcoinUser2016** [comment] 2016-03-15 13:00
Thanks!!

**Comment by laanwj** [comment] 2016-03-16 11:43
Closing this issue as it seems resolved (and you changed the title to something weird).
Let me know if this is a mistake.

**Comment by bittylicious** [comment] 2016-03-17 14:21
I recognise this is closed, but we have the same issue here and abandontransaction doesn't seem to work. Here's my command output

```
bitcoin-cli listunspent 0

...
  {
    "txid": "ad440fbf8773975ac9b7df26346b6b419c4cfa7db150a760e2ceed8897fbe514",
    "vout": 0,
    "address": "19Sx4Duc7EqwfgfvD9DpZtnoqcJjBDZVdF",
    "account": "accountname",
    "scriptPubKey": "76a9145ca95d06a78e31b7a7b095dde2546e9fb2698be688ac",
    "amount": 7.99900000,
    "confirmations": 0,
    "spendable": true
  }, 
...

bitcoin-cli abandontransaction "ad440fbf8773975ac9b7df26346b6b419c4cfa7db150a760e2ceed8897fbe514"

bitcoin-cli listunspent 0

...
  {
    "txid": "ad440fbf8773975ac9b7df26346b6b419c4cfa7db150a760e2ceed8897fbe514",
    "vout": 0,
    "address": "19Sx4Duc7EqwfgfvD9DpZtnoqcJjBDZVdF",
    "account": "BL Seller 140",
    "scriptPubKey": "76a9145ca95d06a78e31b7a7b095dde2546e9fb2698be688ac",
    "amount": 7.99900000,
    "confirmations": 0,
    "spendable": true
  }, 
...
```

The transaction remains in listunspent, and the balance of 'getbalance "*" 0' remains the same. I confirm that I have run -rescan already on this wallet.

Any ideas what could be going on here? It's remained in this state at least for 8 hours so far.

**Comment by laanwj** [comment] 2016-03-17 14:31
@morcos ^ Abandontransaction returns nothing, but still it seems that the transaction is not abandoned, any idea how to further troubleshoot this?

**Comment by morcos** [comment] 2016-03-17 15:38
issue identified, working on a fix

**Comment by morcos** [comment] 2016-03-18 14:55
@bittylicious #7715 should fix your issue.  `getbalance "" 0` and `getbalance "*" 0` are unreliable and are not fixed.  But you can use `getbalance` and `getunconfirmedbalance`.  `listunspent` should also be fixed.

**Closed** 2016-03-23 14:09 UTC
Labels: Wallet

**Comment by BitcoinUser2016** [comment] 2016-04-30 00:19
@morcos Wow, I am truly impressed by your commitment. Ever since I created this thread (and the weeks before that) I had to accept that I will always see a buggy unconfirmedbalance for some reason. Nor did a rescan or reindex work which was a pity since it took quite some time to redownload the blockchain. So, by coincidence I read the changelog for the latest version 0.12.1 and I saw this thread embedded. 

Haha TL;DR: Thanks for solving this!!! I now have 0.000000 as unconfirmed balance because of your fix :D Finally!!! Keep up the good work guys. What you do for this community is truly amazing. Much love to you all. Take care!

**Comment by Mralan** [comment] 2018-12-15 12:19
> Hi,
> 
> I run a bitcoin server which have acting strange the latest 3-4 days. For some reason the unconfirmed balance when running bitcoin-cli getunconfirmedbalance shows up as 50.589243 BTC which of course isn't true.
> 
> How do I reset this? Why did this occur? Tried both v0.12 and v0.12.99, same problem.
> 
> Thanks in advance,
> Nori
 c


> Yes. I've never had this problem before. The volume is exactly the same. It's been stuck at 50+ bitcoins for about 5 days now. There is no way 50 bitcoins have been sent to my wallet.
> 
> For example: When someone sends 1 bitcoins getunconfirmedbalance will show as 51 BTC and then go down to 5 BTC again once its confirmed.
> 
> Yes. Iv'e tried listunspent. Lists lots of transactions saying "confirmations: 0" which already have thousands of confirmations. Some dated 2015 with over 25.000+ confirmations and still says "confirmations: 0". Like this one:
> https://www.blocktrail.com/BTC/address/16F4Bzkk6xaFktqSopACKn18rCRWCWgdW3/transactions
> "txid": "a34a18358937a5b9a9fff8281491de57a9c7942217d43bb469eef5d5113d50fc",
> "vout": 1,
> "address": "16F4Bzkk6xaFktqSopACKn18rCRWCWgdW3",
> "account": "usedaddress",
> "scriptPubKey": "76a91439811d6af01a4337137356cb88488f9f1b6348ed88ac",
> "amount": 0.23509566,
> "confirmations": 0,
> "spendable": true
> 
> It all started around 3 days after I've upgraded from 0.11 to 0.12. My wallet is around 20 MB. Should I rescan?
 Can we chat in whatapp click on the link  https://wa.me/16096762510

**Comment by markaw67** [comment] 2018-12-26 03:48
You had better be sure you can prove that that balance was fake.I happen to no that it wasn't and why would someone question someone else's information without consulting with the owner first makes sense doesn't it yes it does.

**Comment by borisdon32** [comment] 2018-12-26 08:33
Please I'm in need of a fake generator . That can send coins to your block chain and it will show up and later disappear
