### ISSUE TITLE
Crashes.  ntdll.dll issue

### ISSUE THREAD

**Issue by boondogger** [bitcoin/bitcoin#8130] opened 2016-06-01 01:23 UTC
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	bitcoin-qt.exe
  Application Version:	0.12.1.0
  Application Timestamp:	5685c180
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.3.9600.17936
  Fault Module Timestamp:	55a68e0c
  Exception Code:	c0000005
  Exception Offset:	0000000000054ac1
  OS Version:	6.3.9600.2.0.0.768.101
  Locale ID:	4105
win7/64

**Comment by jonasschnelli** [comment] 2016-06-02 09:15
Could you give us some more information?
1) reproducible? If so, steps to reproduce
2) debug.log
3) official binary / self compiled?
4) Amount of RAM, Disk-Type?

**Comment by boondogger** [comment] 2016-06-02 19:12
1.  Bitcoinqt.exe3. Official.4.8GB ram  plus 1TB ssd 850  samsung pro
Debug.log?   How do i get on win8?

-------- Original message --------

**Comment by jonasschnelli** [comment] 2016-06-04 14:02
@boondogger https://en.bitcoin.it/wiki/Data_directory

**Comment by laanwj** [comment] 2016-06-06 13:38
Seems a repeat of #7593

**Comment by fanquake** [comment] 2016-06-22 07:17
@boondogger Can you provide any more information here? Otherwise it seems this can be closed as a dupe of #7593

**Comment by fanquake** [comment] 2016-10-09 12:48
Closing this as a duplicate of #7593

**Closed by fanquake** 2016-10-09 12:48 UTC
Labels: Windows

**Comment by d3spwn** [comment] 2017-11-06 12:06
I had the same issue. Turned out to be an issue with my memory (or other hardware?). MemTest86 found many errors. I solved it by moving the memory module to another slot on the motherboard.
