### ISSUE TITLE
Client crashes while synchronising blocks: Assertion failed: (nIds != nNew), function Serialize, file ./addrman.h, line 320.

### ISSUE THREAD

**Issue by stefek99** [bitcoin/bitcoin#11454] opened 2017-10-05 09:08 UTC
I'm starting Bitcoin client, it verifies the blocks and crashes:

* Yesterday crash: https://pastebin.com/smmA9bym
* Restarted machine, Today's crash: https://pastebin.com/b9QpUMPZ

Rather than sending to Apple sending to you.

Thank you

**Comment by MeshCollider** [comment] 2017-10-05 10:08
Could you please post the contents of your debug.log file?

**Comment by MarcoFalke** [comment] 2017-10-05 11:24
I assume this will be fixed in the upcoming 0.15.1.

Cf. pull #11252 and issue #11409

**Comment by stefek99** [comment] 2017-10-05 13:00
@MeshCollider `debug.log` is 10MB - here is the link - https://we.tl/q2XkAThlK4 - valid for 7 days.

**Comment by TheBlueMatt** [comment] 2017-10-05 21:33
Almost certainly a duplicate of #11409, fixed in 0.15.1 as @MarcoFalke says. Should be closed (we dont normally keep issues open which are fixed in master).

**Comment by fanquake** [comment] 2017-10-06 01:04
Closing as a duplicate of #11409, should have been fixed in #11252.

**Closed by fanquake** 2017-10-06 01:04 UTC
Labels: MacOSX

**Comment by stefek99** [comment] 2017-10-06 15:21
Any quick fix?

Or shall I remove everything and start from scratch?

**Comment by MarcoFalke** [comment] 2017-10-06 15:25
The workaround is described here: https://github.com/bitcoin/bitcoin/issues/11409#issuecomment-332661072

> A quick fix for you, if you're still crashing, is to simply delete your peers.dat.

**Comment by stefek99** [comment] 2017-10-14 19:21
Deleted `peers.dat` - stuck on `Done loading` :/

![screen shot 2017-10-14 at 16 50 00](https://user-images.githubusercontent.com/249703/31578644-29bc713c-b11d-11e7-89e9-09a77d8b35fa.png)

**Comment by TheBlueMatt** [comment] 2017-10-14 20:03
@stefek99 what does the end of your debug.log say (last 10 or 20 lines), how long did you wait for it to finish loading, and is it CPU/disk-pegged or is it actually hung.

**Comment by stefek99** [comment] 2017-10-16 12:11
### 11:00

![screen shot 2017-10-16 at 10 49 06](https://user-images.githubusercontent.com/249703/31611165-e26f9a50-b272-11e7-93e1-4e3ea6f9a422.png)

_(restarted Bitcoin Core)_

### 13:00

![screen shot 2017-10-16 at 13 02 22](https://user-images.githubusercontent.com/249703/31611189-0394f996-b273-11e7-8754-402a4c4263c0.png)

My internet is rather slow anyway, I'll go to some other place with much faster connection, start from scratch, leave it overnight...

---

Have you ever considered creating a .torrent bundle?

I'm pretty sure the underlying protocol of synchronisation is torrent based anyway.

Idea would be to create monthly / quarterly `init packs` - I do this via uTorrent and then Bitcoin Core pulls only the last couple of weeks...

You do the sanity check :)

**Comment by TheBlueMatt** [comment] 2017-10-16 19:03
What does the end of your debug.log look like? Is it possible your node rejected the chain?

**Comment by stefek99** [comment] 2017-10-16 21:36
Related: creating 1TB on TrueCrypt container on the same HDD.

I decided to let TrueCrypt do the job.

No CPU / HDD interference.

I'll continue with the blockchain in several hours.

This is the end of debug.log:


```
2017-10-15 11:59:27 init message: Rewinding blocks...
2017-10-15 11:59:29 init message: Verifying blocks...
2017-10-15 11:59:29 Verifying last 6 blocks at level 3
2017-10-15 11:59:29 [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
2017-10-15 15:30:48 No coin database inconsistencies in last 7 blocks (9477 transactions)
2017-10-15 15:30:48  block index        12765072ms
2017-10-15 15:30:49 init message: Loading wallet...
2017-10-15 15:30:49 nFileVersion = 150001
2017-10-15 15:30:49 Keys: 2002 plaintext, 0 encrypted, 2002 w/ metadata, 2002 total
2017-10-15 15:30:49  wallet                  715ms
2017-10-15 15:30:49 setKeyPool.size() = 2000
2017-10-15 15:30:49 mapWallet.size() = 0
2017-10-15 15:30:49 mapAddressBook.size() = 1
2017-10-15 15:30:49 mapBlockIndex.size() = 489839
2017-10-15 15:30:49 nBestHeight = 419901
2017-10-15 15:30:49 torcontrol thread start
2017-10-15 15:30:49 AddLocal([2a00:23c3:511a:301:c3c:4408:d9c5:7e0b]:8333,1)
2017-10-15 15:30:49 Discover: IPv6 en0: 2a00:23c3:511a:301:c3c:4408:d9c5:7e0b
2017-10-15 15:30:49 AddLocal([2a00:23c3:511a:301:ac70:137a:75b3:289d]:8333,1)
2017-10-15 15:30:49 Discover: IPv6 en0: 2a00:23c3:511a:301:ac70:137a:75b3:289d
2017-10-15 15:30:49 Bound to [::]:8333
2017-10-15 15:30:49 Bound to 0.0.0.0:8333
2017-10-15 15:30:49 init message: Loading P2P addresses...
2017-10-15 15:30:49 ERROR: DeserializeFileDB: Failed to open file /Volumes/Seagate Backup Plus Drive/Blockchain/Bitcoin/peers.dat
2017-10-15 15:30:49 Invalid or missing peers.dat; recreating
2017-10-15 15:30:50 init message: Loading banlist...
2017-10-15 15:30:50 init message: Starting network threads...
2017-10-15 15:30:50 net thread start
2017-10-15 15:30:50 dnsseed thread start
2017-10-15 15:30:50 Loading addresses from DNS seeds (could take a while)
2017-10-15 15:30:50 addcon thread start
2017-10-15 15:30:50 opencon thread start
2017-10-15 15:30:50 msghand thread start
2017-10-15 15:30:50 init message: Done loading
2017-10-15 15:30:53 209 addresses found from DNS seeds
2017-10-15 15:30:53 dnsseed thread exit
2017-10-15 15:31:01 UpdateTip: new best=000000000000000003d62e30462b38ee58ed8cc286b2b81e66d7b80529356761 height=419902 version=0x20000000 log2_work=84.958172 tx=141268033 date='2016-07-09 00:43:20' progress=0.536687 cache=0.8MiB(6302txo)
2017-10-15 15:31:01 GUI: Platform customization: "macosx"
2017-10-15 15:31:01 ProcessMessages(version, 102 bytes) FAILED peer=0
2017-10-15 15:31:02 GUI: PaymentServer::LoadRootCAs: Loaded  167  root certificates
2017-10-15 15:32:23 UpdateTip: new best=0000000000000000041a4df4af6563c7d8a6509c79f12498626015db89d1ceca height=419903 version=0x20000000 log2_work=84.958207 tx=141268847 date='2016-07-09 00:51:00' progress=0.536689 cache=1.2MiB(9027txo)
2017-10-15 15:32:23 UpdateTip: new best=000000000000000001073970c6019db4978060737cbd9e2c256e84dce51d8e3f height=419904 version=0x20000000 log2_work=84.958242 tx=141268848 date='2016-07-09 00:49:36' progress=0.536689 cache=1.2MiB(9028txo)
2017-10-15 15:35:14 Pre-allocating up to position 0x700000 in rev00566.dat
2017-10-15 15:35:14 UpdateTip: new best=000000000000000003c987c5250cc3c47c826ee1cf8ed55fadc83e667c0fc23e height=419905 version=0x20000000 log2_work=84.958277 tx=141269268 date='2016-07-09 00:50:50' progress=0.536690 cache=2.0MiB(14733txo)
2017-10-15 15:35:16 UpdateTip: new best=000000000000000004366074e0e75d9a3b44316b474026259eeed1a5863b6176 height=419906 version=0x20000000 log2_work=84.958312 tx=141269293 date='2016-07-09 00:51:19' progress=0.536690 cache=2.0MiB(14798txo)
2017-10-15 15:36:16 version handshake timeout from 3
2017-10-15 15:36:53 UpdateTip: new best=00000000000000000084ba8940b6033b39207d90e7a0e70e6c5eefa86f24cba9 height=419907 version=0x20000000 log2_work=84.958348 tx=141270371 date='2016-07-09 00:58:08' progress=0.536693 cache=2.3MiB(17412txo)
2017-10-15 15:39:24 UpdateTip: new best=000000000000000001873dd6df18ff52d8ad0088fe5c8a07d34b9b1db9bce3e7 height=419908 version=0x20000000 log2_work=84.958383 tx=141273058 date='2016-07-09 01:20:36' progress=0.536702 cache=3.3MiB(25429txo)
2017-10-15 15:39:24 receive version message: /Satoshi:0.15.0/: version 70015, blocks=489978, us=[2a00:23c3:511a:301:ac70:137a:75b3:289d]:50626, peer=3
2017-10-15 15:40:23 UpdateTip: new best=00000000000000000164ae4dfe06184133fbcd106236b6ae8af5fe14bdd414b5 height=419909 version=0x20000000 log2_work=84.958418 tx=141273900 date='2016-07-09 01:24:54' progress=0.536705 cache=3.8MiB(27872txo)
2017-10-15 15:40:26 UpdateTip: new best=000000000000000004fe6ae4f8da914fd3bf1bb6412a9b3c2114a26b68307dad height=419910 version=0x20000000 log2_work=84.958453 tx=141273991 date='2016-07-09 01:25:28' progress=0.536706 cache=3.8MiB(28039txo)
2017-10-15 15:40:29 version handshake timeout from 6
2017-10-15 15:41:21 UpdateTip: new best=000000000000000002b1c1e1712f429aeb0dda0b74eaf4c0ca63078a86336e56 height=419911 version=0x20000000 log2_work=84.958488 tx=141275100 date='2016-07-09 01:33:27' progress=0.536709 cache=4.2MiB(31369txo)
2017-10-15 15:41:21 receive version message: /Satoshi:0.14.2/UASF-Segwit:1.0(BIP148)/: version 70015, blocks=489980, us=81.147.170.180:50636, peer=6
2017-10-15 15:41:25 version handshake timeout from 7
2017-10-15 15:41:28 version handshake timeout from 8
2017-10-15 15:42:46 UpdateTip: new best=000000000000000002bba96ceda392d94d8a08f07fc6c8871bd5eaf0db58962c height=419912 version=0x20000000 log2_work=84.958524 tx=141276845 date='2016-07-09 01:43:52' progress=0.536716 cache=4.7MiB(34969txo)
2017-10-15 15:43:43 UpdateTip: new best=0000000000000000018be42f46597a0e997cdecef50027a0d745341d7c18ae9d height=419913 version=0x20000000 log2_work=84.958559 tx=141277427 date='2016-07-09 01:47:55' progress=0.536717 cache=4.8MiB(36269txo)
2017-10-15 15:45:23 UpdateTip: new best=000000000000000000d967ee29f7b91a62b00c8ed18b96c99ae9b6dbbc15fca6 height=419914 version=0x20000000 log2_work=84.958594 tx=141278454 date='2016-07-09 01:55:34' progress=0.536721 cache=5.0MiB(38148txo)
2017-10-15 15:45:23 version handshake timeout from 10
2017-10-15 15:51:09 UpdateTip: new best=00000000000000000522cd53f7bb74654b39dc95e16f4af26e2eaf3aa6fd7c8b height=419915 version=0x20000000 log2_work=84.958629 tx=141280394 date='2016-07-09 02:14:02' progress=0.536726 cache=5.6MiB(42978txo)
2017-10-15 15:51:09 socket recv error Connection reset by peer (54)
2017-10-15 15:54:44 UpdateTip: new best=00000000000000000444ae3580ed0c776276c80b4fd2b3dc37e605e60e352aad height=419916 version=0x20000000 log2_work=84.958664 tx=141281266 date='2016-07-09 02:20:14' progress=0.536728 cache=6.0MiB(45744txo)
2017-10-15 16:05:14 UpdateTip: new best=00000000000000000157c86ce131eab63f7bc597104cd9fec96d34138b4b3203 height=419917 version=0x20000000 log2_work=84.958699 tx=141284235 date='2016-07-09 03:05:53' progress=0.536735 cache=7.3MiB(53160txo)
2017-10-15 16:05:14 socket send error Broken pipe (32)
2017-10-15 16:05:14 socket recv error Connection reset by peer (54)
2017-10-15 16:12:44 UpdateTip: new best=000000000000000000737a5e8b6a43fe80091e686f16ec470253fb6468dc1702 height=419918 version=0x20000000 log2_work=84.958735 tx=141286552 date='2016-07-09 03:18:53' progress=0.536741 cache=8.0MiB(58975txo)
2017-10-15 16:23:05 UpdateTip: new best=0000000000000000032c33c85ade38b1e521fc278779cf04385b9d451d9222f2 height=419919 version=0x20000000 log2_work=84.95877 tx=141288203 date='2016-07-09 03:24:43' progress=0.536743 cache=8.6MiB(64153txo)
2017-10-15 16:32:09 UpdateTip: new best=000000000000000003e024246ebad59bc422a07ace4365875fbe33ce4636e10d height=419920 version=0x20000000 log2_work=84.958805 tx=141289133 date='2016-07-09 03:31:01' progress=0.536744 cache=9.0MiB(67404txo)
2017-10-15 16:34:22 GUI: QNSView mouseDragged: Internal mouse button tracking invalid (missing Qt::LeftButton)
2017-10-15 16:37:13 UpdateTip: new best=0000000000000000003b1896a79cc6d2e131a79715fce40fd59c6372bdaf0773 height=419921 version=0x20000000 log2_work=84.95884 tx=141289917 date='2016-07-09 03:37:19' progress=0.536745 cache=9.2MiB(68770txo)
2017-10-15 16:48:38 Pre-allocating up to position 0x800000 in rev00566.dat
2017-10-15 16:48:38 UpdateTip: new best=0000000000000000032ba4f95d39b86b2cc24c27e3c0d3201070945faf890e0d height=419922 version=0x20000000 log2_work=84.958875 tx=141292450 date='2016-07-09 04:03:00' progress=0.536750 cache=10.0MiB(75369txo)
2017-10-15 16:48:38 socket send error Broken pipe (32)
2017-10-15 16:58:34 UpdateTip: new best=000000000000000002503d1d60bbcd4f4800432193f564eb6bc6fa4d7eb3c7d1 height=419923 version=0x20000000 log2_work=84.95891 tx=141293554 date='2016-07-09 04:07:50' progress=0.536750 cache=10.4MiB(78896txo)
2017-10-15 17:05:35 UpdateTip: new best=000000000000000001b90d85b341522315801c050817d9e4a9a417a28a57f03b height=419924 version=0x20000000 log2_work=84.958946 tx=141294698 date='2016-07-09 04:17:16' progress=0.536752 cache=10.8MiB(82045txo)
2017-10-15 17:10:46 UpdateTip: new best=000000000000000002a3aa38f2ca4a6d3d5feb81034a434bac1a34608bd42ed7 height=419925 version=0x20000000 log2_work=84.958981 tx=141295635 date='2016-07-09 04:23:30' progress=0.536754 cache=11.1MiB(84343txo)
2017-10-15 17:10:46 socket send error Broken pipe (32)
2017-10-15 17:14:38 UpdateTip: new best=000000000000000002c7e69779885266cd1b2dc030136a2290fdfaa1cab0005f height=419926 version=0x20000000 log2_work=84.959016 tx=141296534 date='2016-07-09 04:30:43' progress=0.536756 cache=11.3MiB(86422txo)
2017-10-15 17:23:41 UpdateTip: new best=000000000000000002312db5a9f72790a5a8e9b727919a5318d2ae5cb16c1cb9 height=419927 version=0x20000000 log2_work=84.959051 tx=141298327 date='2016-07-09 04:51:04' progress=0.536759 cache=12.4MiB(95388txo)
2017-10-15 17:34:08 UpdateTip: new best=000000000000000001539c8a13df6b59f32126ecbdda1b3c4e196b94b3ad0fc7 height=419928 version=0x20000000 log2_work=84.959086 tx=141299117 date='2016-07-09 04:54:39' progress=0.536758 cache=12.8MiB(98034txo)
2017-10-15 17:44:15 UpdateTip: new best=0000000000000000013b82458134052e35b5fbd36407e23d8ce8d2daadd0c1c0 height=419929 version=0x20000000 log2_work=84.959121 tx=141301297 date='2016-07-09 05:19:32' progress=0.536762 cache=14.3MiB(104346txo)
2017-10-15 17:44:16 socket send error Broken pipe (32)
2017-10-15 17:54:08 UpdateTip: new best=000000000000000004464ce087b303398a989638632f9c312e546894c995ebc8 height=419930 version=0x20000000 log2_work=84.959157 tx=141303641 date='2016-07-09 05:42:09' progress=0.536768 cache=14.9MiB(109222txo)
2017-10-15 17:54:08 socket send error Broken pipe (32)
2017-10-15 18:04:06 Pre-allocating up to position 0x300000 in rev00567.dat
2017-10-15 18:04:08 UpdateTip: new best=000000000000000001abdf3f3409bc7395e4670c20e00bcfb50b51765a264a46 height=419931 version=0x20000000 log2_work=84.959192 tx=141305093 date='2016-07-09 05:52:11' progress=0.536769 cache=15.3MiB(112514txo)
2017-10-15 18:05:44 UpdateTip: new best=0000000000000000024b93dda0eff52ad8a067a1677c7fe8d5676380d983b01f height=419932 version=0x30000000 log2_work=84.959227 tx=141305669 date='2016-07-09 05:57:44' progress=0.536771 cache=15.2MiB(111340txo)
2017-10-15 20:29:12 UpdateTip: new best=000000000000000001d95511ea25b8ab356fc1a6b23494e50a78f80e7626d505 height=419933 version=0x20000000 log2_work=84.959262 tx=141305933 date='2016-07-09 05:58:57' progress=0.536717 cache=15.5MiB(114343txo)
2017-10-15 20:29:12 socket send error Can't assign requested address (49)
2017-10-15 20:30:37 UpdateTip: new best=0000000000000000010196cc1c18dcd0539f66e4a1007d490d82b8fff0057af3 height=419934 version=0x20000000 log2_work=84.959297 tx=141306650 date='2016-07-09 06:04:44' progress=0.536720 cache=15.6MiB(115287txo)
2017-10-15 20:37:34 Pre-allocating up to position 0x900000 in rev00566.dat
2017-10-15 20:37:36 UpdateTip: new best=00000000000000000404ec1560bb47f6eeebf1cbadc56708b1b0b813f4f7e847 height=419935 version=0x20000000 log2_work=84.959332 tx=141309010 date='2016-07-09 06:27:29' progress=0.536726 cache=16.2MiB(120144txo)
2017-10-16 00:39:41 UpdateTip: new best=000000000000000001189bd7b09173688c011ba286b50ec67efc92c315d9e962 height=419936 version=0x20000000 log2_work=84.959368 tx=141309299 date='2016-07-09 06:29:03' progress=0.536635 cache=16.3MiB(120970txo)
2017-10-16 02:40:57 UpdateTip: new best=00000000000000000107d32430a9641b8cdbecc6a1255a62a79bdcb1bc6baf61 height=419937 version=0x20000000 log2_work=84.959403 tx=141309633 date='2016-07-09 06:31:47' progress=0.536591 cache=16.4MiB(121299txo)
2017-10-16 02:41:30 UpdateTip: new best=000000000000000002afeb0b29b01eb1105b884cc2445aa8d9adc7e5e4d46974 height=419938 version=0x20000000 log2_work=84.959438 tx=141309770 date='2016-07-09 06:32:51' progress=0.536591 cache=16.4MiB(121509txo)
2017-10-16 04:41:26 socket sending timeout: 7195s
2017-10-16 06:42:59 UpdateTip: new best=000000000000000004cac714180f6f74014fee97cc231e819bb4bd7b97f8f1b4 height=419939 version=0x30000000 log2_work=84.959473 tx=141310230 date='2016-07-09 06:37:24' progress=0.536501 cache=16.5MiB(122227txo)
2017-10-16 06:42:59 receive version message: /Satoshi:0.15.0/: version 70015, blocks=490064, us=[2a00:23c3:511a:301:5077:1f2b:5bc5:73cf]:51953, peer=35
2017-10-16 08:44:30 UpdateTip: new best=0000000000000000032e23d4d243a0317f2b388dcb0f377f730e5014a9d2f6aa height=419940 version=0x20000000 log2_work=84.959508 tx=141310615 date='2016-07-09 06:40:31' progress=0.536457 cache=16.6MiB(122759txo)
2017-10-16 08:44:32 UpdateTip: new best=000000000000000003be49f71fd1fc8d069573cec191ca3bbff3f25360c6c3ee height=419941 version=0x20000000 log2_work=84.959543 tx=141310635 date='2016-07-09 06:40:45' progress=0.536457 cache=16.6MiB(122819txo)
2017-10-16 09:48:58 UpdateTip: new best=00000000000000000083b01dcd7f9cbfc835822fc4ece136820a06ea0c43d8cd height=419942 version=0x20000000 log2_work=84.959578 tx=141311018 date='2016-07-09 06:44:59' progress=0.536434 cache=16.6MiB(123534txo)
2017-10-16 09:48:58 socket send error Can't assign requested address (49)
2017-10-16 09:49:14 tor: Thread interrupt
2017-10-16 09:49:14 addcon thread exit
2017-10-16 09:49:14 torcontrol thread exit
2017-10-16 09:49:14 scheduler thread interrupt
2017-10-16 09:49:14 msghand thread exit
2017-10-16 09:52:56 UpdateTip: new best=000000000000000000d318dbee04919f46922522a0f5b651fd8b8745ef28c01b height=419943 version=0x20000000 log2_work=84.959614 tx=141312038 date='2016-07-09 06:55:36' progress=0.536436 cache=16.9MiB(125618txo)
2017-10-16 09:52:56 opencon thread exit
2017-10-16 09:52:56 net thread exit
2017-10-16 09:52:57 Shutdown: In progress...
2017-10-16 09:53:19 Shutdown: done
2017-10-16 09:54:20 



















2017-10-16 09:54:20 Bitcoin version v0.15.0.1
2017-10-16 09:54:20 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2017-10-16 09:54:22 Assuming ancestors of block 0000000000000000003b9ce759c2a087d52abc4266f8f4ebd6d768b89defa50a have valid signatures.
2017-10-16 09:54:22 Using the 'standard' SHA256 implementation
2017-10-16 09:54:22 Default data directory /Users/ms/Library/Application Support/Bitcoin
2017-10-16 09:54:22 Using data directory /Volumes/Seagate Backup Plus Drive/Blockchain/Bitcoin
2017-10-16 09:54:22 Using config file /Volumes/Seagate Backup Plus Drive/Blockchain/Bitcoin/bitcoin.conf
2017-10-16 09:54:22 Using at most 125 automatic connections (2560 file descriptors available)
2017-10-16 09:54:22 Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
2017-10-16 09:54:22 Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
2017-10-16 09:54:22 Using 2 threads for script verification
2017-10-16 09:54:22 scheduler thread start
2017-10-16 09:54:22 init message: Verifying wallet(s)...
2017-10-16 09:54:22 Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2017-10-16 09:54:22 Using wallet wallet.dat
2017-10-16 09:54:22 CDBEnv::Open: LogDir=/Volumes/Seagate Backup Plus Drive/Blockchain/Bitcoin/database ErrorFile=/Volumes/Seagate Backup Plus Drive/Blockchain/Bitcoin/db.log
2017-10-16 09:54:23 Cache configuration:
2017-10-16 09:54:23 * Using 2.0MiB for block index database
2017-10-16 09:54:23 * Using 8.0MiB for chain state database
2017-10-16 09:54:23 * Using 440.0MiB for in-memory UTXO set (plus up to 286.1MiB of unused mempool space)
2017-10-16 09:54:23 init message: Loading block index...
2017-10-16 09:54:23 Opening LevelDB in /Volumes/Seagate Backup Plus Drive/Blockchain/Bitcoin/blocks/index
2017-10-16 09:54:24 Opened LevelDB successfully
2017-10-16 09:54:24 Using obfuscation key for /Volumes/Seagate Backup Plus Drive/Blockchain/Bitcoin/blocks/index: 0000000000000000
2017-10-16 09:55:51 LoadBlockIndexDB: last block file = 567
2017-10-16 09:55:51 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=216, size=131646696, heights=419841...420247, time=2016-07-08...2016-07-11)
2017-10-16 09:55:51 Checking all blk files are present...
2017-10-16 09:56:02 LoadBlockIndexDB: transaction index disabled
2017-10-16 09:56:02 Opening LevelDB in /Volumes/Seagate Backup Plus Drive/Blockchain/Bitcoin/chainstate
2017-10-16 09:56:25 Opened LevelDB successfully
2017-10-16 09:56:26 Using obfuscation key for /Volumes/Seagate Backup Plus Drive/Blockchain/Bitcoin/chainstate: c4fea897cb7ade4c
2017-10-16 09:56:27 Loaded best chain: hashBestChain=000000000000000000d318dbee04919f46922522a0f5b651fd8b8745ef28c01b height=419943 date=2016-07-09 06:55:36 progress=0.536435
2017-10-16 09:56:27 init message: Rewinding blocks...
2017-10-16 09:56:32 init message: Verifying blocks...
2017-10-16 09:56:32 Verifying last 6 blocks at level 3
2017-10-16 09:56:32 [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
2017-10-16 10:14:56 No coin database inconsistencies in last 7 blocks (2739 transactions)
2017-10-16 10:14:56  block index         1233764ms
2017-10-16 10:14:57 init message: Loading wallet...
2017-10-16 10:15:12 nFileVersion = 150001
2017-10-16 10:15:12 Keys: 2002 plaintext, 0 encrypted, 2002 w/ metadata, 2002 total
2017-10-16 10:15:13  wallet                15800ms
2017-10-16 10:15:13 setKeyPool.size() = 2000
2017-10-16 10:15:13 mapWallet.size() = 0
2017-10-16 10:15:13 mapAddressBook.size() = 1
2017-10-16 10:15:13 mapBlockIndex.size() = 489839
2017-10-16 10:15:13 nBestHeight = 419943
2017-10-16 10:15:13 torcontrol thread start
2017-10-16 10:15:13 AddLocal([2a00:23c3:511c:3a01:6b:b7fa:61e5:3015]:8333,1)
2017-10-16 10:15:13 Discover: IPv6 en0: 2a00:23c3:511c:3a01:6b:b7fa:61e5:3015
2017-10-16 10:15:13 AddLocal([2a00:23c3:511c:3a01:89b0:28d0:52c3:db96]:8333,1)
2017-10-16 10:15:13 Discover: IPv6 en0: 2a00:23c3:511c:3a01:89b0:28d0:52c3:db96
2017-10-16 10:15:13 Bound to [::]:8333
2017-10-16 10:15:13 Bound to 0.0.0.0:8333
2017-10-16 10:15:13 init message: Loading P2P addresses...
2017-10-16 10:15:13 Loaded 203 addresses from peers.dat  390ms
2017-10-16 10:15:13 init message: Loading banlist...
2017-10-16 10:15:13 init message: Starting network threads...
2017-10-16 10:15:13 net thread start
2017-10-16 10:15:13 dnsseed thread start
2017-10-16 10:15:13 addcon thread start
2017-10-16 10:15:13 opencon thread start
2017-10-16 10:15:13 msghand thread start
2017-10-16 10:15:13 init message: Done loading
2017-10-16 10:15:24 Loading addresses from DNS seeds (could take a while)
2017-10-16 10:15:30 210 addresses found from DNS seeds
2017-10-16 10:15:30 dnsseed thread exit
2017-10-16 10:18:26 UpdateTip: new best=00000000000000000220befcf0111c6374e2e9a332f70e77a0d35faa68fe2994 height=419944 version=0x20000000 log2_work=84.959649 tx=141312569 date='2016-07-09 07:00:56' progress=0.536428 cache=0.3MiB(2337txo)
2017-10-16 10:18:26 socket send error Broken pipe (32)
2017-10-16 10:18:26 GUI: Platform customization: "macosx"
2017-10-16 10:18:27 GUI: PaymentServer::LoadRootCAs: Loaded  167  root certificates
2017-10-16 10:32:24 UpdateTip: new best=0000000000000000047923b894fd34a637c60b38addcec851c28d4d5ca0ec480 height=419945 version=0x20000000 log2_work=84.959684 tx=141314874 date='2016-07-09 07:25:02' progress=0.536432 cache=1.4MiB(10797txo)
2017-10-16 10:44:14 UpdateTip: new best=0000000000000000012fb9ca0cf3947b388970a0c84ed6951880342a214e6f9b height=419946 version=0x20000000 log2_work=84.959719 tx=141316963 date='2016-07-09 07:48:47' progress=0.536435 cache=2.6MiB(19700txo)
2017-10-16 11:05:59 UpdateTip: new best=000000000000000003039fd384e5ad48e36545d8756776d0cb09df6ab35a9d1e height=419947 version=0x20000000 log2_work=84.959754 tx=141317550 date='2016-07-09 07:50:50' progress=0.536429 cache=3.7MiB(26894txo)
2017-10-16 11:05:59 socket send error Broken pipe (32)
2017-10-16 11:23:08 UpdateTip: new best=000000000000000000ea0a0e8338c986fe62d6010ff6ad62752439c30d745a5f height=419948 version=0x20000000 log2_work=84.959789 tx=141319922 date='2016-07-09 08:13:22' progress=0.536432 cache=4.5MiB(33669txo)
2017-10-16 11:38:53 UpdateTip: new best=0000000000000000025f2df6c3344a619dc390682e214c86be2f59170e9fbaec height=419949 version=0x20000000 log2_work=84.959825 tx=141320989 date='2016-07-09 08:17:06' progress=0.536430 cache=5.0MiB(37965txo)
2017-10-16 11:47:18 UpdateTip: new best=0000000000000000013df13c7a3fff96c179932c17762adbd46715de3f4dc868 height=419950 version=0x20000000 log2_work=84.95986 tx=141321254 date='2016-07-09 08:18:27' progress=0.536428 cache=5.2MiB(39568txo)
2017-10-16 12:03:04 UpdateTip: new best=0000000000000000000702c5db0137feb07167463a09165fa4556f5507eb713d height=419951 version=0x20000000 log2_work=84.959895 tx=141323445 date='2016-07-09 08:39:27' progress=0.536430 cache=6.0MiB(46327txo)
2017-10-16 12:19:22 Pre-allocating up to position 0xa00000 in rev00566.dat
2017-10-16 12:19:24 UpdateTip: new best=000000000000000000796894825c09c7f2caf5c7e37c329dc21d977a91247f4c height=419952 version=0x20000000 log2_work=84.95993 tx=141326282 date='2016-07-09 09:15:42' progress=0.536435 cache=7.3MiB(53107txo)
2017-10-16 12:30:52 UpdateTip: new best=000000000000000002d3015a0d3586e8bf4100cd471e572452a70f872335030f height=419953 version=0x20000000 log2_work=84.959965 tx=141328391 date='2016-07-09 09:35:19' progress=0.536438 cache=8.0MiB(58734txo)
2017-10-16 12:34:26 tor: Thread interrupt
2017-10-16 12:34:26 addcon thread exit
2017-10-16 12:34:26 torcontrol thread exit
2017-10-16 12:34:26 scheduler thread interrupt
2017-10-16 12:34:26 msghand thread exit
2017-10-16 12:41:00 UpdateTip: new best=0000000000000000003609b3fe92ccdaabd2ab3c272da4efef42d37a74ec0357 height=419954 version=0x30000000 log2_work=84.96 tx=141330348 date='2016-07-09 09:46:16' progress=0.536442 cache=8.5MiB(63067txo)
2017-10-16 12:41:00 opencon thread exit
2017-10-16 12:41:00 Shutdown: In progress...
2017-10-16 12:41:00 net thread exit
2017-10-16 12:41:15 Shutdown: done
```

**Comment by stefek99** [comment] 2017-10-18 14:47
I'd happily download pre-compiled 150GB via Torrent and then allow core client to catchup last couple of weeks...

_(it's been taking forever, properly)_

![screen shot 2017-10-18 at 15 45 48](https://user-images.githubusercontent.com/249703/31725168-8e1e9884-b41b-11e7-922f-fca8f88661c1.png)
