### ISSUE TITLE
Windows client launch inconsistency

### ISSUE THREAD

**Issue by ajp8164** [bitcoin/bitcoin#5663] opened 2015-01-14 23:23 UTC
When launching Bitcoin Core from a BIP21 (or comparable) URL the app opens up connected to live net (without -testnet parameter) when it sees the address starting with 'n'.  The app does, however, open up connected to testnet if the address starts with 'm' (with -testnet parameter).  This behavior is inconsistent and should be corrected to be consistent across all valid testnet (and live net) addresses.

**Comment by Diapolo** [comment] 2015-01-16 12:29
I don't understand the problem, you click a link containing mainnet address and it opens mainnet, you click a link containing a testnet address and it opens testnet, whats wrong here?

**Comment by laanwj** [comment] 2015-01-16 12:32
@Diapolo He implies that there is a difference in handling testnet addresses starting with 'm' and starting with 'n' in the URIs. It's curious as AFAIK there is no code that looks at the first letter to determine what kind of address it is.

**Comment by alexchan69** [comment] 2015-02-05 20:08
So how does the client app (bitcoin-qt.exe) know to open up testnet when the addresses start with 'm' meaning they are testnet addresses?

The issue is that strangely the logic works for addresses starting with 'm' but not those starting with 'n'.

**Comment by laanwj** [comment] 2015-02-06 10:02
This is where the logic is where the client's network is selected based on the address passed in, thus would be a good starting point: https://github.com/bitcoin/bitcoin/blob/master/src/qt/paymentserver.cpp#L207

So on line 216 it first checks if the address is valid for mainnet, if so, it selects mainnet. Then it checks if the address is valid for testnet, if so, it selects testnet. If neither it justs falls through, as an 'invalid address' error will be shown later after client start-up finished.

There is no 'address starts with X' heuristic anywhere, just full address decodes+checks, so that's why I'm spooked as to why this may happen.

**Comment by Diapolo** [comment] 2015-02-06 10:09
I still think the initial issue description is unclear... he writes ``The app does ... open up connected to testnet if the address starts with 'm' (with -testnet parameter)``. Is that a running instance with -testnet supplied or what does that mean?

**Comment by alexchan69** [comment] 2015-02-12 00:03
I think he meant to say that the app does open up connected to testnet fresh (and not a running instance) correctly if the address starts with 'm', *as if* it runs with -testnet parameter. However, if the address starts with 'n', then the app opens up connected to the live net, which is incorrect.

I was able to repro it on my machine before that whenever the address starts with 'n' like n379DyezL6xbcrR71V1iWfxjicT4t16RmQ, the app opens up connecting to the live net, even though I expect it to connect to testnet.

I checked the code. I understand that it does not check for the 'm' or 'n' character directly, but could the CBitcoinAddress::IsValid() function have some bug that incorrectly treats an address starting with 'n' as a live net address?

**Comment by jonasschnelli** [comment] 2015-11-30 14:02
Tested again with current master (Windows / OSX).
Both platforms handles address/network mapping correct.
bitcoin:n379DyezL6xbcrR71V1iWfxjicT4t16RmQ did successfully open bitcoin-qt with testnet on both platforms. Closing.

<img width="849" alt="bildschirmfoto 2015-11-30 um 15 00 57" src="https://cloud.githubusercontent.com/assets/178464/11473555/560fa6ca-9773-11e5-8f06-9d1301311349.png">

**Closed by jonasschnelli** 2015-11-30 14:02 UTC
Labels: GUI, Priority Low
