### ISSUE TITLE
i2pacceptincoming isn't set default to 0

### ISSUE THREAD

**Issue by clayop** [bitcoin/bitcoin#22983] opened 2021-09-15 15:33 UTC
On Windows, if I put `i2psam=localhost:7656` and `i2pacceptincoming` in `bitcoin.conf` Bitcoin core should run without errors.

But `i2pacceptincoming` leads to an error. I have to put `i2pacceptincoming=1`

As documented, default value of `i2pacceptincoming` should set to 1 so that `i2pacceptincoming` works alone.

**Comment by prayank23** [comment] 2021-09-15 16:16
> On Windows, if I put i2psam=localhost:7656 and i2pacceptincoming in bitcoin.conf Bitcoin core should run without errors.

You should use nothing or `i2pacceptincoming=N` where N=0 to disable and N=1 to enable

> As documented, default value of i2pacceptincoming should set to 1 so that i2pacceptincoming works alone.

It is set to 1 by default if you don't use that option in config.

Try running with these config:

1. Check default behaviour
```
i2psam=127.0.0.1:7656
```

2. Disable i2p incoming and only use i2p for outgoing

```
i2psam=127.0.0.1:7656
i2pacceptincoming=0
```


Also the documentation is correct in [doc/i2p.md](https://github.com/bitcoin/bitcoin/blob/master/doc/i2p.md), maybe there is some misunderstanding.

https://github.com/bitcoin/bitcoin/blob/053a5fc7d912d597cd6dc7376b479420d1eae1c0/src/init.cpp#L439

**Comment by fanquake** [comment] 2022-08-08 16:16
cc @vasild

**Comment by vasild** [comment] 2022-08-12 16:30
@clayop, If you put `i2pacceptincoming` in `bitcoin.conf`, you need to put either `i2pacceptincoming=1` or `i2pacceptincoming=0`. Without `=N` this error is produced:

```sh
./src/bitcoind 
Error: Error reading configuration file: parse error on line 35: i2pacceptincoming
```

That is the same for other options as well, e.g. `logips` or `listen`:

```sh
./src/bitcoind 
Error: Error reading configuration file: parse error on line 20: listen
```

**Comment by mzumsande** [comment] 2022-09-20 17:32
Seems like there is nothing wrong here (and nothing specific to i2pacceptincoming, all boolean command args work that way), so that this could be closed?

**Comment by vasild** [comment] 2022-11-23 09:15
I guess this should be closed as "not a bug".

**Closed** 2022-11-23 09:22 UTC
Labels: Bug, P2P
