### ISSUE TITLE
v0.12  Assertion `onlyMaybeDeadlock' failed.

### ISSUE THREAD

**Issue by themighty1** [bitcoin/bitcoin#7578] opened 2016-02-22 14:44 UTC
running the latest v0.12 bitcoin-qt, got a coredump and a console message

2016-02-22 13:33:47 POTENTIAL DEADLOCK DETECTED
2016-02-22 13:33:47 Previous lock order was:
2016-02-22 13:33:47  pnode->cs_vSend  net.cpp:1755 (TRY)
2016-02-22 13:33:47  (1) cs_main  main.cpp:5347 (TRY)
2016-02-22 13:33:47  (2) pto->cs_inventory  main.cpp:5447
2016-02-22 13:33:47 Current lock order is:
2016-02-22 13:33:47  (2) pnode->cs_vRecvMsg  net.cpp:1736 (TRY)
2016-02-22 13:33:47  (1) cs_main  main.cpp:1377
bitcoin-qt: sync.cpp:112: void potential_deadlock_detected(const std::pair<void*, void*>&, const LockStack&, const LockStack&): Assertion `onlyMaybeDeadlock' failed.

What's exactly is this deadlock?
Is it worth building a debug build over? Does this have to be investigated?

**Comment by laanwj** [comment] 2016-02-23 11:52
This is a duplicate of: Potential deadlock assertion in net code on 0.12RC3 #7470

Should be investigated but could be a false positive, it will only appear if you build with -DDEBUG_LOCKORDER. The release executables don't have this problem.

**Closed by laanwj** 2016-02-23 11:52 UTC
