### ISSUE TITLE
dumpprivkey error

### ISSUE THREAD

**Issue by lctteam** [bitcoin/bitcoin#30124] opened 2024-05-16 15:07 UTC
bitcoin-core version: 27.0

I execute: `bitcoin-cli getnewaddress`
and
`bitcoin-cli dumpprivkey "address"`

report an error:
```
error code: -4
error message:
Only legacy wallets are supported by this command
```

I need to export the private key of the address, is there any way to do that?
If I want to use dumpprivkey which version of bitcoin core should I use?

thanks.

**Comment by willcl-ark** [comment] 2024-05-16 15:21
You should be able to get the info you need using `bitcoin-cli listdescriptors true`, to include private descriptors.

If that doesn't work for you, you can create a legacy BDB wallet (using a newer version of the software) by following the v26.0 wallet [release notes](https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-26.0.md#wallet). Of particular importance is use of the `-deprecatedrpc=create_bdb` option to `bitcoind`, before running `bitcoin-cli createwallet ...` with the `descriptors` argument set to false.

Of the two approaches I'd recommend the first, as BDB wallet functionality is being actively deprecated in this project.

I'm going to close this now as there's no action for this project to take. But if you have any more general bitcoin questions and/or support requests, these are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com/) or the #bitcoin IRC channel on the [Libera Chat](https://libera.chat/) network.

**Closed by willcl-ark** 2024-05-16 15:21 UTC

**Comment by edilmedeiros** [comment] 2024-05-17 14:21
Duplicate of #30129 which has a working solution.
