### ISSUE TITLE
If both options "onion" and "proxy" are unset, no outbound Onion connections should be made

### ISSUE THREAD

**Issue by wodry** [bitcoin/bitcoin#22647] opened 2021-08-06 09:33 UTC
bitcoind 22.0rc2

Having the following `bitcoin.conf`
```
upnp=0
debug=i2p
shrinkdebugfile=1
onlynet=i2p
listen=1
timeout=20000
server=1
maxtxfee=0.001
i2psam=127.0.0.1:7656
addnode=72l3ucjkuscrbiiepoehuwqgknyzgo7zuix5ty4puwrkyhtmnsga.b32.i2p:0
addnode=c4gfnttsuwqomiygupdqqqyy5y5emnk5c73hrfvatri67prd7vyq.b32.i2p:0
addnode=gehtac45oaghz54ypyopim64mql7oad2bqclla74l6tfeolzmodq.b32.i2p:0
addnode=h3r6bkn46qxftwja53pxiykntegfyfjqtnzbm6iv6r5mungmqgmq.b32.i2p:0
addnode=hnbbyjpxx54623l555sta7pocy3se4sdgmuebi5k6reesz5rjp6q.b32.i2p:0
addnode=pjs7or2ctvteeo5tu4bwyrtydeuhqhvdprtujn4daxr75jpebjxa.b32.i2p:0
addnode=wwbw7nqr3ahkqv62cuqfwgtneekvvpnuc4i4f6yo7tpoqjswvcwa.b32.i2p:0
addnode=zsxwyo6qcn3chqzwxnseusqgsnuw3maqnztkiypyfxtya4snkoka.b32.i2p:0
```
Makes bitcoind connect outgoing to Onion network.
`bitcoind --help` says for option `onlynet`:
_"if it is used with non-onion networks and the -onion or -proxy option is set, then outbound onion connections will still be made; use -noonion or -onion=0 to disable outbound onion connections in this case."_

But as you can see, neither `onion` nor `proxy` is set. `proxy` defaults to "disabled" (=0 ?), and `onion` defaults to value of `proxy`, so if `proxy` is unset=disabled, `onion` should be disabled(=0), too. There should be no need for setting `onion=0` in this case.

The above sentence would be clearer like so: _"use -noonion or -onion=0 to disable outbound onion connections if proxy is set"_

**Expected behavior**

No outgoing connections to Onion network, only to I2P network.

**Actual behavior**

Outgoing connections to both Onion and I2P network.

**To reproduce**

Use above bitcoin.conf.

**System information**

Debian Buster amd_64

**Comment by jonatack** [comment] 2021-08-06 09:49
#22648

**Comment by jonatack** [comment] 2021-08-06 09:51
Opened a draft at #22648 and will look into addressing your comments.

**Comment by vasild** [comment] 2021-08-06 13:18
This looks like a bug or at least some serious violation of the [Principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

I wonder how did `bitcoind` find the Tor socks5 proxy if none of `-proxy` or `-onion` is specified? Can you post the full `debug.log` and the output of `bitcoin-cli getnetworkinfo`. I could not reproduce it.

**Comment by wodry** [comment] 2021-08-06 13:46
debug.log. The last line was the first outbound connection, which was of type Onion.
```
2021-08-06T13:27:10Z Bitcoin Core version v22.0.0-g873fbc745d037ad43570f81e58334c397bc95477 (release build)
2021-08-06T13:27:10Z Qt 5.12.11 (static), plugin=xcb (static)
2021-08-06T13:27:10Z Static plugins:
2021-08-06T13:27:10Z  QXcbIntegrationPlugin, version 330752
2021-08-06T13:27:10Z Style: fusion / QFusionStyle
2021-08-06T13:27:10Z System: Debian GNU/Linux 10 (buster), x86_64-little_endian-lp64
2021-08-06T13:27:10Z Screen: Virtual-1 1600x900, pixel ratio=1.0
2021-08-06T13:27:10Z Assuming ancestors of block 00000000000000000008a89e854d57e5667df88f1cdef6fde2fbca1de5b639ad have valid signatures.
2021-08-06T13:27:10Z Setting nMinimumChainWork=00000000000000000000000000000000000000001fa4663bbbe19f82de910280
2021-08-06T13:27:10Z Using the 'sse4(1way),sse41(4way)' SHA256 implementation
2021-08-06T13:27:10Z Using RdSeed as additional entropy source
2021-08-06T13:27:10Z Using RdRand as an additional entropy source
2021-08-06T13:27:10Z Default data directory /home/user/.bitcoin
2021-08-06T13:27:10Z Using data directory /home/user/.bitcoin
2021-08-06T13:27:10Z Config file: /home/user/.bitcoin/bitcoin.conf
2021-08-06T13:27:10Z Config file arg: addnode="72l3ucjkuscrbiiepoehuwqgknyzgo7zuix5ty4puwrkyhtmnsga.b32.i2p:0"
2021-08-06T13:27:10Z Config file arg: addnode="c4gfnttsuwqomiygupdqqqyy5y5emnk5c73hrfvatri67prd7vyq.b32.i2p:0"
2021-08-06T13:27:10Z Config file arg: addnode="gehtac45oaghz54ypyopim64mql7oad2bqclla74l6tfeolzmodq.b32.i2p:0"
2021-08-06T13:27:10Z Config file arg: addnode="h3r6bkn46qxftwja53pxiykntegfyfjqtnzbm6iv6r5mungmqgmq.b32.i2p:0"
2021-08-06T13:27:10Z Config file arg: addnode="hnbbyjpxx54623l555sta7pocy3se4sdgmuebi5k6reesz5rjp6q.b32.i2p:0"
2021-08-06T13:27:10Z Config file arg: addnode="pjs7or2ctvteeo5tu4bwyrtydeuhqhvdprtujn4daxr75jpebjxa.b32.i2p:0"
2021-08-06T13:27:10Z Config file arg: addnode="wwbw7nqr3ahkqv62cuqfwgtneekvvpnuc4i4f6yo7tpoqjswvcwa.b32.i2p:0"
2021-08-06T13:27:10Z Config file arg: addnode="zsxwyo6qcn3chqzwxnseusqgsnuw3maqnztkiypyfxtya4snkoka.b32.i2p:0"
2021-08-06T13:27:10Z Config file arg: debug="i2p"
2021-08-06T13:27:10Z Config file arg: i2psam="127.0.0.1:7656"
2021-08-06T13:27:10Z Config file arg: listen="1"
2021-08-06T13:27:10Z Config file arg: maxtxfee="0.001"
2021-08-06T13:27:10Z Config file arg: onlynet="i2p"
2021-08-06T13:27:10Z Config file arg: server="1"
2021-08-06T13:27:10Z Config file arg: shrinkdebugfile="1"
2021-08-06T13:27:10Z Config file arg: timeout="20000"
2021-08-06T13:27:10Z Config file arg: upnp="0"
2021-08-06T13:27:10Z Using at most 125 automatic connections (1024 file descriptors available)
2021-08-06T13:27:10Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
2021-08-06T13:27:10Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
2021-08-06T13:27:10Z Script verification uses 1 additional threads
2021-08-06T13:27:10Z scheduler thread start
2021-08-06T13:27:10Z HTTP: creating work queue of depth 16
2021-08-06T13:27:10Z Using random cookie authentication.
2021-08-06T13:27:10Z Generated RPC authentication cookie /home/user/.bitcoin/.cookie
2021-08-06T13:27:10Z HTTP: starting 4 worker threads
2021-08-06T13:27:10Z Using wallet directory /home/user/.bitcoin
2021-08-06T13:27:10Z init message: Überprüfe Wallet(s)...
2021-08-06T13:27:10Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2021-08-06T13:27:10Z Using wallet /home/user/.bitcoin/wallet.dat
2021-08-06T13:27:10Z BerkeleyEnvironment::Open: LogDir=/home/user/.bitcoin/database ErrorFile=/home/user/.bitcoin/db.log
2021-08-06T13:27:10Z init message: Lade Bannliste…
2021-08-06T13:27:10Z SetNetworkActive: true
2021-08-06T13:27:10Z Using /16 prefix for IP bucketing
2021-08-06T13:27:10Z Cache configuration:
2021-08-06T13:27:10Z * Using 2.0 MiB for block index database
2021-08-06T13:27:10Z * Using 8.0 MiB for chain state database
2021-08-06T13:27:10Z * Using 290.0 MiB for in-memory UTXO set (plus up to 286.1 MiB of unused mempool space)
2021-08-06T13:27:10Z init message: Lade Block-Index...
2021-08-06T13:27:10Z Switching active chainstate to Chainstate [ibd] @ height -1 (null)
2021-08-06T13:27:10Z Opening LevelDB in /home/user/.bitcoin/blocks/index
2021-08-06T13:27:10Z Opened LevelDB successfully
2021-08-06T13:27:10Z Using obfuscation key for /home/user/.bitcoin/blocks/index: 0000000000000000
2021-08-06T13:27:16Z LoadBlockIndexDB: last block file = 2679
2021-08-06T13:27:16Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=126, size=115009652, heights=694332...694480, time=2021-08-05...2021-08-06)
2021-08-06T13:27:16Z Checking all blk files are present...
2021-08-06T13:27:16Z Opening LevelDB in /home/user/.bitcoin/chainstate
2021-08-06T13:27:17Z Opened LevelDB successfully
2021-08-06T13:27:17Z Using obfuscation key for /home/user/.bitcoin/chainstate: 0000000000000000
2021-08-06T13:27:17Z Loaded best chain: hashBestChain=00000000000000000003bfbfaf2b79a93047a1d82b00ca70a727135956e3f11b height=694480 date=2021-08-06T13:21:10Z progress=0.999999
2021-08-06T13:27:17Z init message: Überprüfe Blöcke...
2021-08-06T13:27:17Z Verifying last 6 blocks at level 3
2021-08-06T13:27:17Z [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
2021-08-06T13:27:18Z No coin database inconsistencies in last 6 blocks (6887 transactions)
2021-08-06T13:27:18Z  block index            7426ms
2021-08-06T13:27:18Z init message: Lade Wallet...
2021-08-06T13:27:18Z BerkeleyEnvironment::Open: LogDir=/home/user/.bitcoin/database ErrorFile=/home/user/.bitcoin/db.log
2021-08-06T13:27:18Z [default wallet] Wallet File Version = 169900
2021-08-06T13:27:18Z [default wallet] Keys: 0 plaintext, 4012 encrypted, 4012 w/ metadata, 4012 total. Unknown wallet records: 0
2021-08-06T13:27:18Z [default wallet] Wallet completed loading in              53ms
2021-08-06T13:27:18Z [default wallet] setKeyPool.size() = 1999
2021-08-06T13:27:18Z [default wallet] mapWallet.size() = 9
2021-08-06T13:27:18Z [default wallet] m_address_book.size() = 11
2021-08-06T13:27:18Z block tree size = 694695
2021-08-06T13:27:18Z nBestHeight = 694480
2021-08-06T13:27:18Z loadblk thread start
2021-08-06T13:27:18Z torcontrol thread start
2021-08-06T13:27:18Z Bound to 127.0.0.1:8334
2021-08-06T13:27:18Z Bound to [::]:8333
2021-08-06T13:27:18Z Bound to 0.0.0.0:8333
2021-08-06T13:27:18Z init message: Lade P2P-Adressen...
2021-08-06T13:27:18Z Leaving InitialBlockDownload (latching to false)
2021-08-06T13:27:18Z tor: Got service ID ........................................................, advertising service .........................................................onion:8333
2021-08-06T13:27:18Z AddLocal(.........................................................onion:8333,4)
2021-08-06T13:27:18Z Loaded 57329 addresses from peers.dat  343ms
2021-08-06T13:27:18Z Loaded 0 addresses from "anchors.dat"
2021-08-06T13:27:18Z 0 block-relay-only anchors will be tried for connections.
2021-08-06T13:27:18Z init message: Starte Netzwerk-Threads...
2021-08-06T13:27:18Z init message: Laden abgeschlossen
2021-08-06T13:27:18Z i2paccept thread start
2021-08-06T13:27:18Z I2P: Creating SAM session with 127.0.0.1:7656
2021-08-06T13:27:18Z opencon thread start
2021-08-06T13:27:18Z dnsseed thread start
2021-08-06T13:27:18Z Waiting 300 seconds before querying DNS seeds.
2021-08-06T13:27:18Z addcon thread start
2021-08-06T13:27:18Z net thread start
2021-08-06T13:27:18Z msghand thread start
2021-08-06T13:27:18Z GUI: Platform customization: "other"
2021-08-06T13:27:19Z Imported mempool transactions from disk: 1080 succeeded, 0 failed, 0 expired, 0 already there, 0 waiting for initial broadcast
2021-08-06T13:27:19Z loadblk thread exit
2021-08-06T13:27:21Z New outbound peer connected: version: 70016, blocks=694480, peer=0 (outbound-full-relay)
```
Output of `bitcoin-cli getnetworkinfo`
```
{
  "version": 220000,
  "subversion": "/Satoshi:22.0.0/",
  "protocolversion": 70016,
  "localservices": "0000000000000409",
  "localservicesnames": [
    "NETWORK",
    "WITNESS",
    "NETWORK_LIMITED"
  ],
  "localrelay": true,
  "timeoffset": -3,
  "networkactive": true,
  "connections": 15,
  "connections_in": 0,
  "connections_out": 15,
  "networks": [
    {
      "name": "ipv4",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": false,
      "reachable": true,
      "proxy": "127.0.0.1:9050",
      "proxy_randomize_credentials": true
    },
    {
      "name": "i2p",
      "limited": false,
      "reachable": true,
      "proxy": "127.0.0.1:7656",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00001000,
  "incrementalfee": 0.00001000,
  "localaddresses": [
    {
      "address": "....................................onion",
      "port": 8333,
      "score": 4
    },
    {
      "address": ".....................................b32.i2p",
      "port": 0,
      "score": 4
    }
  ],
  "warnings": ""
}
```
```

**Comment by jonatack** [comment] 2021-08-06 13:50
I've reproduced the issue with the 22.0rc2 binary (debian), the above config (and i2pd 2.38.0).

**Comment by wodry** [comment] 2021-08-06 13:54
With added `debug=tor` there are those additional log lines:
```
2021-08-06T13:49:46Z Leaving InitialBlockDownload (latching to false)
2021-08-06T13:49:46Z torcontrol thread start
2021-08-06T13:49:46Z tor: Reading cached private key from /home/user/.bitcoin/onion_v3_private_key
2021-08-06T13:49:46Z tor: Successfully connected!
2021-08-06T13:49:46Z tor: Connected to Tor version 0.3.5.15
2021-08-06T13:49:46Z tor: Supported authentication method: COOKIE
2021-08-06T13:49:46Z tor: Supported authentication method: HASHEDPASSWORD
2021-08-06T13:49:46Z tor: Supported authentication method: SAFECOOKIE
2021-08-06T13:49:46Z tor: Using SAFECOOKIE authentication, reading cookie authentication from /run/tor/control.authcookie
2021-08-06T13:49:46Z tor: SAFECOOKIE authentication challenge successful
2021-08-06T13:49:46Z tor: AUTHCHALLENGE ServerHash ........................... ServerNonce ...............................
2021-08-06T13:49:46Z tor: Authentication successful
2021-08-06T13:49:46Z tor: ADD_ONION successful
2021-08-06T13:49:46Z tor: Got service ID ..................., advertising service ....................................onion:8333
2021-08-06T13:49:46Z tor: Cached service private key to /home/user/.bitcoin/onion_v3_private_key
2021-08-06T13:49:46Z AddLocal(...............................onion:8333,4)
```

**Comment by jonatack** [comment] 2021-08-06 14:06
Same config with `onion=0` blocks outbound onion connections, I2P outbound connections only.

**Comment by vasild** [comment] 2021-08-06 15:20
Thanks for the debug info!

> I wonder how did bitcoind find the Tor socks5 proxy if none of -proxy or -onion is specified?

It just defaults to `127.0.0.1:9050`, disrespecting `-onlynet`:

https://github.com/bitcoin/bitcoin/blob/d67330d11245b11fbdd5e2dd5343ee451186931e/src/torcontrol.cpp#L378-L383

Fixed in https://github.com/bitcoin/bitcoin/pull/22651

**Comment by wodry** [comment] 2021-08-06 20:06
> Current solution is to add `onion=0`: this blocks outbound onion connections, I2P outbound connections only.

Do you really in fact get I2P outbound connections with `onion=0` and `onlynet=i2p` ? I did not on a 3h test, see my addition to comment in https://github.com/bitcoin/bitcoin/issues/22634#issuecomment-894073027

**Comment by jonatack** [comment] 2021-08-06 20:32
Yes. 

Also, i2pd 2.23.0 (an old version currently still shipped with Debian stable), while a bit funky at first, worked for me across more than a dozen restarts and configurations. I'm running a production node with it now to test it over more time.

**Comment by jonatack** [comment] 2021-08-06 20:39
Also:

> I see many log lines Error connecting to xxx.b32.i2p:0: Unexpected reply to "NAMING LOOKUP NAME=xxx.b32.i2p": "NAMING REPLY RESULT=INVALID_KEY NAME=xxx.b32.i2p"

With i2pd 2.23, this is one of the errors when a peer isn't online. It's normal when some of the addnode peers in your conf file aren't up.

**Comment by Rspigler** [comment] 2021-08-06 21:33
Are there possible tests that could be added to catch errors like this?

**Comment by wodry** [comment] 2021-08-06 22:27
@jonatak On a second I2P-only test, I get now I2P connections, so pure I2P now works for me too, very nice.

**Comment by ljkt7334** [comment] 2021-08-12 03:03
> bitcoind 22.0rc2
> 
> Having the following `bitcoin.conf`
> 
> ```
> upnp=0
> debug=i2p
> shrinkdebugfile=1
> onlynet=i2p
> listen=1
> timeout=20000
> server=1
> maxtxfee=0.001
> i2psam=127.0.0.1:7656
> addnode=72l3ucjkuscrbiiepoehuwqgknyzgo7zuix5ty4puwrkyhtmnsga.b32.i2p:0
> addnode=c4gfnttsuwqomiygupdqqqyy5y5emnk5c73hrfvatri67prd7vyq.b32.i2p:0
> addnode=gehtac45oaghz54ypyopim64mql7oad2bqclla74l6tfeolzmodq.b32.i2p:0
> addnode=h3r6bkn46qxftwja53pxiykntegfyfjqtnzbm6iv6r5mungmqgmq.b32.i2p:0
> addnode=hnbbyjpxx54623l555sta7pocy3se4sdgmuebi5k6reesz5rjp6q.b32.i2p:0
> addnode=pjs7or2ctvteeo5tu4bwyrtydeuhqhvdprtujn4daxr75jpebjxa.b32.i2p:0
> addnode=wwbw7nqr3ahkqv62cuqfwgtneekvvpnuc4i4f6yo7tpoqjswvcwa.b32.i2p:0
> addnode=zsxwyo6qcn3chqzwxnseusqgsnuw3maqnztkiypyfxtya4snkoka.b32.i2p:0
> ```
> 
> Makes bitcoind connect outgoing to Onion network.
> `bitcoind --help` says for option `onlynet`:
> _"if it is used with non-onion networks and the -onion or -proxy option is set, then outbound onion connections will still be made; use -noonion or -onion=0 to disable outbound onion connections in this case."_
> 
> But as you can see, neither `onion` nor `proxy` is set. `proxy` defaults to "disabled" (=0 ?), and `onion` defaults to value of `proxy`, so if `proxy` is unset=disabled, `onion` should be disabled(=0), too. There should be no need for setting `onion=0` in this case.
> 
> The above sentence would be clearer like so: _"use -noonion or -onion=0 to disable outbound onion connections if proxy is set"_
> 
> **Expected behavior**
> 
> No outgoing connections to Onion network, only to I2P network.
> 
> **Actual behavior**
> 
> Outgoing connections to both Onion and I2P network.
> 
> **To reproduce**
> 
> Use above bitcoin.conf.
> 
> **System information**
> 
> Debian Buster amd_64

**Closed** 2022-03-01 17:32 UTC
Labels: Bug
