### ISSUE TITLE
Misattributed authorship in commit log here on Github

### ISSUE THREAD

**Issue by awemany** [bitcoin/bitcoin#7512] opened 2016-02-11 08:32 UTC
If you look here (current page for earliest commits in Bitcoin),

https://github.com/bitcoin/bitcoin/commits/master?page=289

you can see that commits done by sirius-m are attributed to Greg Maxwell.

This does not seem to be a problem with the import from SVN, as the committers show up correctly in a 'git log'. This also matches the info in the old SVN (still available on sourceforge).

Rather, it seems to be an issue or a misconfiguration on github.

I didn't check whether there are more issues like this.

**Comment by laanwj** [comment] 2016-02-11 08:46
The only way to solve this is to contact github. The problem is that anyone can claim ownership of any mail address. At the repository level there's no way to remove that. Those people are not on github, so I think this remain a problem forever.

**Comment by laanwj** [comment] 2016-02-11 08:48
It's very possible that @gmaxwell claimed those addresses to prevent them from being claimed by someone else.
Maybe we could set up a dummy account and move them there...

**Comment by gmaxwell** [comment] 2016-02-11 08:48
Yep, this happened while trying to figure how "saracen" was being attributed all s_nakamoto commits and reproducing them. It was reported to github and discussed in the #bitcoin-dev logs a while back.

**Comment by laanwj** [comment] 2016-02-11 08:58
> It looks like github fixed the one set and not the other.

I only reported the s_nakamoto one. I'm not sure how they resolved it. But it is a losing battle if anyone that wants to troll can just go re-claim them.

**Comment by awemany** [comment] 2016-02-11 09:33
A better solution might be to create a github user like  'Bitcoin Unknown Author' and attribute all commits resp. email addresses that are not from the the team on github to him.

**Comment by ftrader** [comment] 2016-02-11 12:02
'Non-Github Bitcoin author' would be a more suitable name, since some like Martti Malmi are known.

**Comment by laanwj** [comment] 2016-02-11 12:03
What did github assign s_nakamoto to? or is it free to claim again?

**Comment by gmaxwell** [comment] 2016-02-12 02:32
it's fixed, github has now made them nonassignable.

**Comment by laanwj** [comment] 2016-02-12 12:16
Awesome.

**Comment by awemany** [comment] 2016-02-12 18:30
There is more:

https://archive.is/4KW50
https://archive.is/SQs6o

This is all I could find in the early history.

**Comment by gmaxwell** [comment] 2016-02-12 19:31
I have no clue-- I'll have to re-nag github; unless it's just caching. None of them are configured in my account.

**Comment by laanwj** [comment] 2017-02-16 08:09
Re-opening this issue as it was messed up again recently.

**Comment by awemany** [comment] 2017-02-20 09:35
What is the problem this time?

**Comment by laanwj** [comment] 2017-02-20 15:45
Same as before, old Satoshi commits are misattributed to saracen: https://github.com/bitcoin/bitcoin/commit/f1e1fb4bdef878c8fc1564fa418d44e7541a7e83 

I've written Github twice about this, but it's taking long to fix this time.

**Comment by saracen** [comment] 2017-04-02 14:05
The first time I did this I remember notifying somebody. I can't find the chat transcript now, I thought it happened in the bitcoin dev IRC channel, but maybe not? I also reported the problem to Github, although it may have been specifically to a developer I know that works there.

At some point, the problem appeared fixed, I was no longer the author. A few weeks/months ago I was able to attribute myself again as the author, using exactly the same method as the first time.

What you want to do about this is up to you. You could create a new account, or assign it to one of your own accounts. Or wait for Github to fix the issue.

**Comment by MarcoFalke** [comment] 2017-04-02 14:55
I think github fixed it. They attribute all commits with an invalid email
address to https://github.com/invalid-email-address

**Comment by saracen** [comment] 2017-04-02 15:00
@MarcoFalke It's still an issue: https://github.com/bitcoin/bitcoin/commits?author=saracen

**Comment by achow101** [comment] 2017-04-02 15:00
@MarcoFalke No, they didn't. The earliest commits made by sirius-m are still misattributed: https://github.com/bitcoin/bitcoin/commits/master?after=6d97df0e992dc5015b5327935ab89923d2dc0ba9+0

It seems that they have only marked satoshi's commits as invalid-email-address, not sirius's

**Comment by saracen** [comment] 2017-04-02 15:11
The invalid-email-address account is pretty interesting. Has Github just attributed it to this account in the same way I have? I guess that's a manual process, rather than them automatically assigning invalid email addresses.

https://github.com/bitcoin/bitcoin/commits?author=invalid-email-address

**Comment by achow101** [comment] 2017-04-02 22:31
@saracen I made @non-github-bitcoin so that we can attribute those commits to that account. Could you please unassociate those email addresses from your account so that I can add them to the dummy account?

I also contacted github support to see if they can/will do anything about it.

**Comment by saracen** [comment] 2017-04-03 03:52
@achow101 I'm not really sure that fixes the issue.

I'll wait for a member of the bitcoin repo to reply here or for Github to assign it to the `invalid-email-address` account.

**Comment by laanwj** [comment] 2017-04-03 11:50
> The invalid-email-address account is pretty interesting. Has Github just attributed it to this account in the same way I have?

I think they did. It's not something we can do ourselves at least, so would need to contact them with a list. It seems like a nice solution from them though.

**Comment by achow101** [comment] 2017-04-24 18:41
Github allowed me to add all three of the emails (s_nakamoto, sirius-m, laszloh) to the @non-github-bitcoin dummy account so now those commits are properly attributed. Control of the account has been handed over to @laanwj. This issue can now be closed.

**Comment by saracen** [comment] 2017-04-24 21:48
It's a shame this is Github's solution, I don't think it's ideal.

Now I just need to add those emails to another repository and then message Github in a month's time telling them they've been assigned to the wrong user "non-github-bitcoin", and whether they'd be able to reassign them for me.

Maybe they should only link to an account for verified email addresses. Anyway, I guess that's beyond the scope of the issue here :).

**Comment by laanwj** [comment] 2017-04-25 05:21
The real shame is that people abuse the attribution mechanism in this way, no matter whether it is possible or not.

> Maybe they should only link to an account for verified email addresses. Anyway, I guess that's beyond the scope of the issue here :).

This seems the simplest solution. On the other hand, what if you committed something using an old email that you no longer have (e.g. at a company where you used to work).

**Closed** 2017-04-25 05:22 UTC

**Comment by saracen** [comment] 2017-04-25 12:33
> The real shame is that people abuse the attribution mechanism in this way, no matter whether it is possible or not.

I can't help but feel this was a little bit of a dig at me :) Probably correctly so... but, for what it's worth, I did reach out to Github about this and have been up front about the issue when people have mistakenly pointed out that I might be the author.

It sucks that this was/is an issue at all. I apologise that it took up time.

**Comment by laanwj** [comment] 2017-04-25 13:21
> I did reach out to Github about this and have been up front about the issue when people have mistakenly pointed out that I might be the author.

Right, seems mostly a miscommunication issue, I was not aware that you were communicating with Github about the same thing. I complained to them so many times, I couldn't help becoming a bit annoyed to see your name associated with the commits time after time. Anyhow let's be happy it's solved.
