### ISSUE TITLE
GUI: missing translations for some buttons

### ISSUE THREAD

**Issue by GChuf** [bitcoin/bitcoin#17092] opened 2019-10-09 23:27 UTC
While testing 0.19.0.rc1 I stumbled upon missing translations for some buttons.
After finding one button was missing a translation I kept digging and found some more ...

**Close button:**
This window opens when the user clicks "_Create new receiving address_" or clicks on an existing address and clicks "_Show_" under the "_Receive_" tab.

**Yes/Cancel buttons:**
When clicking "_Close wallet_" from dropdown menu AND "_Open URI_" from "_File_" dropdown menu

**OK/Cancel buttons:**
"_Encrypt Wallet_" from "_Settings_" drop down menu

**OK button:**
all three "_Help_" dropdown menu items

**Cancel button:**
"_Create Wallet..._" from "_File_" drop down menu

Some screenshots below:
![Screenshot_83](https://user-images.githubusercontent.com/42591821/66527089-5d4bb400-eaea-11e9-99e1-409664e2bb4e.png)

![Screenshot_92](https://user-images.githubusercontent.com/42591821/66527452-c67ff700-eaeb-11e9-8a1e-4bd92212e7fe.png)

**Comment by laanwj** [comment] 2019-10-10 12:06
Seems a duplicate of #1137?

**Comment by GChuf** [comment] 2019-10-10 16:28
That's correct. I wasn't aware that this issue was already mentioned.

**Closed** 2019-10-10 16:46 UTC
Labels: Bug, GUI
