### ISSUE TITLE
Unable to open wallet UI with ubuntu 23.10

### ISSUE THREAD

**Issue by mmaryo** [bitcoin/bitcoin#29311] opened 2024-01-25 09:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Hello, 
I noticed that the UI does not open.

### Expected behaviour

to open the UI

### Steps to reproduce

I copy past the command of the shortcut 
`env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/bitcoin-core_bitcoin-qt.desktop /snap/bin/bitcoin-core.qt %u`
in a terminal 

The terminal output of the command line
`Fontconfig warning: FcPattern object weight does not accept value [0 205)
[1]    824648 segmentation fault (core dumped)  env  /snap/bin/bitcoin-core.qt %u`

I installed Bitcoin Core with Snap this summer. 
Then, I upgraded the system from Ubuntu 23.04 to 23.10 
I have not open Bitcoin Core since the upgrade 

Also I follow this https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#dependency-build-instructions
And install every dependency I see in this page 

### How did you obtain Bitcoin Core

Package manager

### What version of Bitcoin Core are you using?

v26.0.0

### Operating system and version

Ubuntu 23.10

### Machine specifications

Asus laptop Zenbook

**Comment by fanquake** [comment] 2024-01-25 10:34
Close or move to GUI repo? cc @hebasto

**Comment by mmaryo** [comment] 2024-01-25 10:51
Hello 
Thank you 
this command line works 
https://github.com/keshavbhatt/olivia/issues/95#issuecomment-774747492

But my wallet is empty?
![image](https://github.com/bitcoin/bitcoin/assets/1669985/ea4f2af4-dadb-4281-9b24-055fce2d7fa9)


May I find it somewhere else?
Are there logs?

**Comment by hebasto** [comment] 2024-01-25 16:16
On Ubuntu 23.10, I've installed the Bitcoin Core 26.0 from the "latest/stable" Snap channel. 

> The terminal output of the command line
> `Fontconfig warning: FcPattern object weight does not accept value [0 205) [1] 824648 segmentation fault (core dumped) env /snap/bin/bitcoin-core.qt %u`

Cannot reproduce it.

> Hello Thank you this command line works [keshavbhatt/olivia#95 (comment)](https://github.com/keshavbhatt/olivia/issues/95#issuecomment-774747492)

Indeed.

> Close or move to GUI repo?

It does not look like a GUI issue now.

**Comment by willcl-ark** [comment] 2024-01-29 09:42
I think we can close this out for now as it appears to have been a `fontconfig` issue which is now resolved.

**Closed by willcl-ark** 2024-01-29 09:42 UTC
Labels: GUI, Wallet, Questions and Help
