### ISSUE TITLE
Resize "Open Configuration File" box in Bitcoin Core Wallet

### ISSUE THREAD

**Issue by matikwin** [bitcoin/bitcoin#17348] opened 2019-11-01 19:56 UTC
The box can be found under 'settings>options' 

<img width="576" alt="Opnconffi" src="https://user-images.githubusercontent.com/57270843/68052446-8faf9200-fce1-11e9-911e-31ba01365d8f.png">

**Comment by emilengler** [comment] 2019-11-01 22:01
See  #16971
Maybe this will help in this frame as well

**Comment by matikwin** [comment] 2019-11-01 22:21
I'm sure it's an easy fix for someone. 

Me however 😕.

**Comment by hebasto** [comment] 2019-11-02 07:19
@matikwin 

Tested on Linux Mint 19.2: and Windows 10 v1903. Failed to reproduce the issue.
Also different languages were tried, that implies different button text lengths. Works as expected.

**Linux Mint 19.2**:
![Screenshot from 2019-11-02 08-33-08](https://user-images.githubusercontent.com/32963518/68067550-40a14580-fd51-11e9-954a-8e7b0d4c1aa7.png)
![Screenshot from 2019-11-02 08-32-15](https://user-images.githubusercontent.com/32963518/68067572-a1c91900-fd51-11e9-9afa-f1ae75977a39.png)

**Windows 10 v1903**:
![Screenshot from 2019-11-02 09-15-44](https://user-images.githubusercontent.com/32963518/68067564-8fe77600-fd51-11e9-9ab5-635a7380a7a8.png)
![Screenshot from 2019-11-02 09-14-22](https://user-images.githubusercontent.com/32963518/68067565-92e26680-fd51-11e9-8cd6-17077c21f979.png)


Could you provide more details about OS, Qt and Bitcoin binary versions?

**Comment by laanwj** [comment] 2019-11-02 10:36
No problem here either on Ubuntu, even when making the window as small as it can.

Might be related to #17153 though. Assuming this is some Linux (next time when you report an issue, mention OS details) Can you try running `QT_SCREEN_SCALE_FACTORS=1 bitcoin-qt`?

**Comment by matikwin** [comment] 2019-11-12 17:27
Sorry for the delay.

- Windows 10 v1903
- 1920x1080
- Bitcoin Core version v0.18.1 (64-bit)
- Qt v5.9.7

Problem persists regardless of window resizing.

**Comment by hebasto** [comment] 2019-11-13 14:25
> Sorry for the delay @hebasto @laanwj
> 
>     * Windows 10, v1903
> 
>     * 1920x1080
> 
>     * Bitcoin Core version v0.18.1 (64-bit)
> 
>     * Qt v5.9.7
> 
> 
> Problem persists regardless of window resizing.

@matikwin 
Tested on the same configuration and Bitcoin Core version:
![Screenshot from 2019-11-13 16-24-04](https://user-images.githubusercontent.com/32963518/68772228-20676580-0632-11ea-98af-0f0cb0a4b228.png)

**Comment by matikwin** [comment] 2019-11-13 15:03
Hmmm... 🤔 

Anything else I can do to help?

**Comment by hebasto** [comment] 2019-11-13 15:14
@matikwin 

Could you check Bitcoin Core 0.19.0?

**Comment by matikwin** [comment] 2019-11-13 15:23
Do you mean review the code or something? If so, I'm afraid not.

If you mean downloading and running some beta version or something, I can certainly try. Apologies for the lack of understanding.

**Comment by hebasto** [comment] 2020-01-15 08:59
> Do you mean review the code or something? If so, I'm afraid not.
> 
> If you mean downloading and running some beta version or something, I can certainly try. Apologies for the lack of understanding.

I mean to [download](https://bitcoincore.org/en/download/) and try to run v0.19.0.1.

**Comment by messymatt** [comment] 2020-01-15 09:18
Yeah, recently updated software to 0.19.0.1

Problem persists im afraid.

**Comment by hebasto** [comment] 2020-01-15 12:32
I've managed to reproduce an issue by setting "Change the size..." to 150%:
![Screenshot from 2020-01-15 14-27-23](https://user-images.githubusercontent.com/32963518/72433965-2e0ca900-37a3-11ea-8e68-92fa0d37439a.png)

The result is:
![Screenshot from 2020-01-15 14-12-39](https://user-images.githubusercontent.com/32963518/72433988-3e248880-37a3-11ea-952c-3ac0eb52726b.png)

@messymatt 
Could you try to reset your "Ease of Access" -> "Display" settings?

**Comment by matikwin** [comment] 2020-02-04 18:58
Hey @hebasto 

My Ease of access display settings were at 150%. I adjusted the setting to 100% and the box displays correctly, after a software restart. My machine does recommend using 150% rather than 100% for some reason. Using the machine at 100% is uncomfortable.

**Comment by MarcoFalke** [comment] 2020-04-26 17:21
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.

**Closed by MarcoFalke** 2020-04-26 17:21 UTC
Labels: GUI
