### ISSUE TITLE
RPC: add/remove -rpcallowip and -rpcauth options without restart

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#16543] opened 2019-08-03 07:37 UTC
Running the Bitcoin Core at a university for research purposes. Researchers use RPC to have an access to the Bitcoin Core via a LAN. Their credentials are stored in the `bitcoin.conf` file as pairs of `rpcallowip=<ip>` and `rpcauth=<userpw>` options.

From the Core operator's point of view, it seems ~~two features are~~ a feature is missing:
- an ability to add/remove `-rpcallowip` and `-rpcauth` options without the Bitcoin Core restart
- ~~preventing to stop the Bitcoin Core from a remote machine by `bitcoin-cli stop` (a special case of a more general #12248)~~

**Comment by emilengler** [comment] 2019-08-04 01:23
For your second point, are you thinking of adding a separate config parameter for disabling an rpc shutdown?

**Comment by emilengler** [comment] 2019-08-04 05:32
See #16544. This could fix your second point

**Comment by hebasto** [comment] 2019-08-04 14:00
Could be related: #12248

**Comment by benthecarman** [comment] 2019-08-07 14:54
I have a project that does something similar to this, it can be configured to fit your use case I believe.

https://github.com/benthecarman/Lightning-Rod

**Comment by MarcoFalke** [comment] 2019-08-07 16:54
This is a duplicate of #12248? If not, it should specify how this feature request is different.

**Comment by hebasto** [comment] 2019-08-10 09:45
@MarcoFalke 
> This is a duplicate of #12248? If not, it should specify how this feature request is different.

An ability to add/remove `-rpcallowip` and `-rpcauth` options without the Bitcoin Core restart is not covered by #12248.

**Comment by MarcoFalke** [comment] 2019-08-10 13:16
Ok, maybe create a separate issue for that? A title of "feature request" with two features in the comment body isn't helpful to keep track of issues.

**Comment by hebasto** [comment] 2019-08-10 13:36
@MarcoFalke 
> Ok, maybe create a separate issue for that? A title of "feature request" with two features in the comment body isn't helpful to keep track of issues.

OP has been updated.

**Closed** 2022-08-05 08:49 UTC
Labels: RPC/REST/ZMQ
