### ISSUE TITLE
Closing a wallet using the fa46088440 28.x QT client segfaults

### ISSUE THREAD

**Issue by katesalazar** [bitcoin/bitcoin#30887] opened 2024-09-12 17:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Closing a descriptor wallet using the fa46088440 28.x QT client segfaults.
Closing a descriptor wallet using the fa46088440 28.x console client works fine.

### Expected behaviour

Not a crash.

### Steps to reproduce

--enable-wallet --disable-shared --with-pic --no-create --no-recursion

### Relevant log output

standard segfault line

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

28.x@fa46088440

### Operating system and version

Debian GNU/Linux 12 (bookworm)

### Machine specifications

x86_64 GNU/Linux

**Comment by furszy** [comment] 2024-09-12 21:19
Replicated. It happens closing it through the GUI toolbar button. Not the command-line. Will investigate it.

**Comment by furszy** [comment] 2024-09-12 21:35
The issue is we are calling `removeAndDeleteWallet` twice for the same wallet model. The first time inside `WalletController::closeWallet` and a second time when the backend emits the wallet `unload` signal. Preparing the PR..

**Comment by furszy** [comment] 2024-09-12 22:02
See https://github.com/bitcoin-core/gui/pull/835

**Closed** 2024-09-13 10:28 UTC
Labels: Bug, GUI, Wallet
