### ISSUE TITLE
Allow groups of accounts to access the RPC cookie file

### ISSUE THREAD

**Issue by alevchuk** [bitcoin/bitcoin#25270] opened 2022-06-02 23:44 UTC
**Context**
I have multiple accounts on the same box that need to run clients of bitcoind. In particular it's LND and electrs. Bitcoind itself runs in a separate account. I have other accounts that I don't want to have access to bitcoin: e.g. Grafana (graphs/charts web UI). So, the cookie file can be shared amount the relevant accounts via a group. On the file system a group read permissions can be set on each file.  I call the group "bitcoinclients". I setup a directory where new files will inherit the bitcoinclients group and will be created with the u=rw,g=r,o= permission. This means bticoin account can write the file, bitcoinclinets group can read it, and no one else has access.

**Is your feature request related to a problem? Please describe.**
The problem is that when `bitcoind` is restarted it drops the group read permission on the cookie file so clients in other unix accounts can't read the file.
 
**Describe the solution you'd like**
There should be a config that allows controlling permissions of the cookie file. Just a boolean that sets the read permissions on the group would be sufficient.

**Describe alternatives you've considered**
I setup a [chronos workaround](https://github.com/alevchuk/minibank/blob/first/bitcoin/README.md#bitcoin-cookie) but I bet more people will have to re-invent this wheel as the cookie file gets wider adoption.

**Additional context**
[Cookie file](https://github.com/bitcoin/bitcoin/blob/25ad2c623af30056ffb36dcd203a52edda2b170f/src/httprpc.cpp#L252) has [more security](https://github.com/Kixunil/security_writings/blob/master/cookie_files.md) over user+password auth. User+password auth is being deprecated in favor of the cookie file.

**Comment by 1440000bytes** [comment] 2022-06-03 02:12
Have you tried RPC whitelists? https://github.com/bitcoin/bitcoin/pull/12763

**Comment by alevchuk** [comment] 2022-06-03 05:07
> Have you tried RPC whitelists? #12763

Whitelists use rpcauth which sends the password in clear text to the server https://github.com/bitcoin/bitcoin/blob/0de36941eca1bff91420dd878eb097db2b1a596c/src/httprpc.cpp#L130

This unlike the cookie file is not resilient to [server spoofing attack](https://github.com/Kixunil/security_writings/blob/master/cookie_files.md). Basically if my grafana user gets compromised then it can get the password for any other user. 


In my case both users have a wide variety of methods that need to be used, so locking down with rpc whitelists would not help much. I would not choose that over not letting random users in.

**Comment by ryanofsky** [comment] 2022-06-03 17:12
Agree it would be useful to set permissions on the cookie file, and this would be a simple feature to implement. But I don't think it would be right to say rpcauth is less secure than cookie auth.

The main advantage cookies have over RPC passwords is just their convenience. Other than being generated randomly each restart, they don't provide extra security. You could write a script to randomly generate new passwords for grafana each time bitcoin is restarted to get the same effect as using a cookie.

RPC passwords also have an advantage over cookies because they are hashed. So if an attacker manages to get read access to the bitcoin directory, they can't easily use password hashes to connect to the server, while they could straightforwardly use the cookie file to connect.

Also it looks like depending on your setup you may be able control permissions of the cookie file in current versions of bitcoind by running `umask 0027` and passing `-sysperms` argument.

**Comment by darosior** [comment] 2022-06-06 12:25
I agree this would be nice to have. I personally use ACLs to achieve the same.

**Comment by Adminsupportteam** [comment] 2022-06-07 15:11
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam 

https://direct.lc.chat/14201763/

**Comment by kristapsk** [comment] 2022-06-08 15:10
In RaspiBolt we use `-startupnotify="chmod g+r /home/bitcoin/.bitcoin/.cookie"`, to add group permission after RPC cookie file is created. https://github.com/raspibolt/raspibolt/pull/846

**Comment by lsunsi** [comment] 2022-07-25 12:13
I'll be using the @kristapsk solution as well, but I'd love for a 'cookie_umask' option or something to be added.

**Comment by willcl-ark** [comment] 2023-03-15 17:05
Am I wrong in thinking that there is probably still demand for this, even though #26088 was closed (because #17127 was merged, which does not address this issue), and we have an number of currently-working alternatives:

1. The raspiblitz startupnotify script: `-startupnotify="chmod g+r /home/bitcoin/.bitcoin/.cookie"` 
2. With user+password by using `stunnel` to situate the RPC port behind ssl: `stunnel -d 8332 -r 127.0.0.1:8332 -p /path/to/your/certificate.pem -k /path/to/your/key.pem -o /var/log/stunnel.log` (cleaner with a config file + service).
3. Cronjobs or similar...

It seems to me that we should either make the cookie group-readable by default, or provide an option to enable that (preferred).

**Comment by pinheadmz** [comment] 2023-04-27 14:40
This issue is unlikely to be fixed in Bitcoin Core. We'll close for now, but feel free to open another issue or pull request with a fix.

**Closed by pinheadmz** 2023-04-27 14:40 UTC
Labels: Feature, RPC/REST/ZMQ

**Comment by AndySchroder** [comment] 2024-02-24 01:52
> Am I wrong in thinking that there is probably still demand for this, even though #26088 was closed (because #17127 was merged, which does not address this issue), and we have an number of currently-working alternatives:
> 
>     1. The raspiblitz startupnotify script: `-startupnotify="chmod g+r /home/bitcoin/.bitcoin/.cookie"`
> 
>     2. With user+password by using `stunnel` to situate the RPC port behind ssl: `stunnel -d 8332 -r 127.0.0.1:8332 -p /path/to/your/certificate.pem -k /path/to/your/key.pem -o /var/log/stunnel.log` (cleaner with a config file + service).
> 
>     3. Cronjobs or similar...
> 
> 
> It seems to me that we should either make the cookie group-readable by default, or provide an option to enable that (preferred).


Note:

`-startupnotify="chmod g+r /home/bitcoin/.bitcoin/.cookie"` works on the command line, but `startupnotify="chmod g+r /home/bitcoin/.bitcoin/.cookie"` inside bitcoin.conf does not.

I am not sure why the two ways behave differently, but debug.log says it is executing it with either approach, even though passing it on the command line is the only one that actually seems to change the permissions of the .cookie file.

**Comment by willcl-ark** [comment] 2024-02-29 19:57
> 
> Note:
> 
> `-startupnotify="chmod g+r /home/bitcoin/.bitcoin/.cookie"` works on the command line, but `startupnotify="chmod g+r /home/bitcoin/.bitcoin/.cookie"` inside bitcoin.conf does not.
> 
> I am not sure why the two ways behave differently, but debug.log says it is executing it with either approach, even though passing it on the command line is the only one that actually seems to change the permissions of the .cookie file.

@AndySchroder 

I think the issue is coming from your use of `" "` surrounding the command inside bitcoin.conf. Try like this (which works for me):

_bitcoin.conf_:
```txt
startupnotify=chmod g+r /home/bitcoin/.bitcoin/.cookie
```
