### ISSUE TITLE
RPC field to indicate which of the conflicted wallet transactions is in the mempool

### ISSUE THREAD

**Issue by shesek** [bitcoin/bitcoin#21018] opened 2021-01-27 20:43 UTC
`listtransactions`/`listsinceblock` don't currently indicate which of the conflicted unconfirmed wallet transactions are considered 'active' (in the node's mempool) and which aren't.

To determine this, one currently has to issue an additional `getmempoolentry` rpc call and check if that fails or not. It would be useful if this information was more readily available, without requiring additional calls.

~~Additionally, it appears that there's an inconsistency between `gettransaction` and `listtransactions`. Normally, `listtransactions` returns a flattened concatenated list of the `details` for all the wallet transactions, with one entry per `detail` entry. But in this case, `gettransaction` returns an empty `details` array for 'non active' transactions, which should to my understanding translate to the transaction not showing up in `listtransactions` at all, yet it does.~~ (this is wrong, it was a PEBMAC)

My preference would be for 'non active' unconfirmed transactions to show up in both, but with a flag that indicates their status (similarly to `confirmations < 0` for transactions that conflict with confirmed transactions).

**Comment by jonatack** [comment] 2021-01-27 20:58
IRC discussion: http://www.erisian.com.au/bitcoin-core-dev/log-2021-01-27.html#l-464

**Comment by danben** [comment] 2021-02-20 23:24
Hi - I started trying to write a functional test to demonstrate this behavior, but I realized I don't quite understand what's going on here. How does it happen that a transaction (the "non active" one) is hanging out in the wallet but not in the mempool?

**Comment by shesek** [comment] 2021-02-20 23:28
@danben The typical case where this would happen is RBF.

**Comment by danben** [comment] 2021-02-22 17:24
@shesek I can't reproduce the behavior you're seeing re: gettransaction. For me, the details field is identical (and nonempty) when I call gettransaction on the transaction before and after it is evicted from the mempool. Can you provide more information so I can figure out where the discrepancy is coming from?

**Comment by shesek** [comment] 2021-02-23 12:28
@danben I tried again and oddly enough can't seem to reproduce the empty `details` array anymore. I'm fairly certain that I saw this behavior before, not sure what changed.

**Comment by adamjonas** [comment] 2023-03-09 20:33
This hasn't seen any activity for a few years and doesn't seem to be making forward progress. Closing for now.

**Closed by adamjonas** 2023-03-09 20:33 UTC
Labels: Feature, Wallet
