### ISSUE TITLE
Strange state (Timestamps wrong) after importing a priv key.

### ISSUE THREAD

**Issue by kollokollo** [bitcoin/bitcoin#11703] opened 2017-11-16 07:19 UTC
### Describe the issue
After importing a private key from an old wallet, the rescan tool a long time, but after completion all Timestams belonging to transactions related to the newly imported key are wrong.
#### What behavior did you expect?
Show the correct timestamps of all trasactions, corresponding to the block the transaction took place.
#### What was the actual behavior (provide screenshots if the issue is GUI-related)?
see screenshots. The newly imported key has the label "ehemals", The big number for confirmations (in the tooltip) seems to be correct, but the timestamps all show the time of the latest transaction (lieferando) which was there at the time of import.
#### How reliably can you reproduce the issue, what are the steps to do so?
Have not reproduced this issue yet (because it takes sooo long). But I have observed other strange things before (data curruption, see: Issue https://github.com/bitcoin/bitcoin/issues/11627).
### What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)?
Bitcoin core from the ppa used on Ubuntu 17.4 (most recent, I think) Bitcoin core version: v0.15.0.0-g3751912e8e (64-Bit)
### What type of machine are you observing the error on (OS/CPU and disk type)?
Ubuntu 17.04 64 bit, Quadcore CPU, 2GB RAM, HDD and SSD (for chainstate).
### Any extra information that might be useful in the debugging process.
Everything else seems normal. The blockchain was freshly reindexed the 3 days before the import.(to cure the data corruption). The former issue "data corruption" was observed on a different computer, I then used a desktop computer. But I use the same (extermal) HDD.

**Comment by kollokollo** [comment] 2017-11-16 07:21
Uploading the screenshots failed: "Something went really wrong, and we can't process that file."
What did I make wrong?

**Comment by kollokollo** [comment] 2017-11-16 07:57
You may also want to know, that I have spent a part of the the bitcoins imported with the key already (transaction dated 2017-11-14) and that worked.

**Comment by Popkultur** [comment] 2017-11-17 15:00
one might want to try to change your OS time from DST to non-DST or something to reproduce these errors.

**Comment by MarcoFalke** [comment] 2017-11-27 19:07
@kollokollo Are all those 6 transactions included in the same block

**Comment by kollokollo** [comment] 2017-11-27 21:44
No, they are all in different blocks. As the number of confirmations say.
e.g. 
1836
367187, (ehemals)
365876 (ehemals)
2145 (lieferando)
366627 (ehemals)
358927(ehemals)
365017(ehemals)
365967 (n/a)

Not even the order is chronological.

**Comment by kollokollo** [comment] 2017-12-05 06:50
I have reproduced this one other time with a different wallet:
My diagnosis is: New Entries in the list of transactions are made always with a timestamp not older than the last transaction which was really send (or received) from the client. So all transactions which are recognized during a rescan  (due to wallet change or import of a priv key) will not get their real timestamp if they are older than the latest transaction sent by the core client. However, if you have not (yet) send or received any transaction with the running core client so far, private keys are imported correctly. Also exchanging wallet.dat woked without noticable problems.  The problem starts with the first transaction send. I hope this observation helps fixing it.

**Comment by MarcoFalke** [comment] 2017-12-15 20:58
Link to presumably related issue: #6662

**Comment by BashCo** [comment] 2017-12-17 23:25
I'm experiencing the same issue with v0.15.1 on Mac OS X. 

Perhaps coincidentally, the incorrect dates on my imported addresses are the same as @kollokollo, although the times are different: `2017-12-11T21:49:20`

All the transactions associated with those imported addresses were confirmed in blocks prior to 2017-12-11. Any suggestions on how to mitigate or work around this issue would be appreciated.

**Comment by achow101** [comment] 2017-12-25 20:26
The issue looks like it is with this case:

https://github.com/bitcoin/bitcoin/blob/df91e11ae1e9d7af55a549b597a73d01e3a646c7/src/wallet/wallet.cpp#L3652-L3655

**Comment by achow101** [comment] 2017-12-26 01:02
So investigating this issue a bit more shows that the reason this happens is because of the way that the smart time works and this is intended behavior. As explained in #1393 (which added this behavior) the reason for having new transactions always have the same timestamp or later of the last transaction in the wallet is to preserve the order of `listtransactions`. But I'm sure there is some way we can keep that ordering but preserve the time of a transaction.

**Comment by luke-jr** [comment] 2017-12-26 03:33
Rather, to keep time monotonic. Ordering is separate from time already.

**Comment by achow101** [comment] 2017-12-26 03:43
Does time need to be monotonic though? For what reasons?

**Comment by Nargren** [comment] 2018-01-06 11:25
I am also having this issue with v0.15.1 on both Windows and Ubuntu. 

I share the observation of @kollokollo, where a recent transaction causes false timestamps for (some) older transactions.

**Comment by jb55** [comment] 2020-11-27 18:11
![Nov27-100942](https://user-images.githubusercontent.com/45598/100475722-b254db80-3098-11eb-8dda-23763372760b.png)

I think I'm hitting this issue? or is this something else? I just did a rescan on latest master as of yesterday and the dates seem wrong at a certain point (after 2017). this is a descriptor wallet.

**Comment by kouloumos** [comment] 2022-08-04 19:50
[As has already pointed out](https://github.com/bitcoin/bitcoin/issues/11703#issuecomment-353899561), this issue is related specifically to this logic
https://github.com/bitcoin/bitcoin/blob/df91e11ae1e9d7af55a549b597a73d01e3a646c7/src/wallet/wallet.cpp#L3652-L3655
https://github.com/bitcoin/bitcoin/pull/20591 has since added this additional logic to fix this issue
_*"receiving a transaction" is probably a typo, it should say "receiving a block"._
https://github.com/bitcoin/bitcoin/blob/2c3115d4f568b2719daa44d8eb2504a8cd7691fe/src/wallet/wallet.cpp#L2604-L2605
 The wording is like this because block rescan processing and realtime processing share the same logic ([see caller graph of `ComputeTimeSmart`](https://doxygen.bitcoincore.org/classwallet_1_1_c_wallet.html#ac27826a974c5b281d866caf09a37eebd)). The `rescanning_old_block` flag is what now differentiates between the two processes
https://github.com/bitcoin/bitcoin/blob/2c3115d4f568b2719daa44d8eb2504a8cd7691fe/src/wallet/wallet.cpp#L2633-L2635

[`wallet_transactiontime_rescan.py`](https://github.com/bitcoin/bitcoin/blob/master/test/functional/wallet_transactiontime_rescan.py) is also testing against this scenario.

**Comment by willcl-ark** [comment] 2022-11-22 22:09
Should this also be closed by #20591 like #6662 was? The fixed `true` value during `ScanForWalletTransactions()` here: https://github.com/bitcoin/bitcoin/blob/38d06e1561013f4ca845fd5ba6ffcc64de67f9c0/src/wallet/wallet.cpp#L1887 ... would apply equally to privkeys imported to legacy wallets too.

**Closed** 2022-11-22 22:32 UTC
Labels: Wallet
