### ISSUE TITLE
File|Sign Message fails for Segwit addresses (3, bc1)

### ISSUE THREAD

**Issue by HamishMacEwan** [bitcoin/bitcoin#15256] opened 2019-01-25 05:32 UTC
Creating a labelled bitcoin address on the Receive tab (32hCAqWGcA85Ge9kMV2YpFoRyAuChvF6oN)  and selecting it from File|Sign Message results in an error when the "Sign Message" button is pressed: 

"The entered address does not refer to a key.  Please check the address and try again."

That the message would be signed and a Signature created.
 

The error message as described.

Everytime I use an address that doesn't start with 1.

v0.17.1 (64bit)

Windows 10

**Comment by fanquake** [comment] 2019-01-25 05:34
Duplicate of #10542, see that issue for discussion.

**Closed by fanquake** 2019-01-25 05:34 UTC

**Comment by HamishMacEwan** [comment] 2019-01-25 05:38
Thanks!

Cryptographic signatures and private keys.  The discussion seems to see little or no value.  A signature proves possession of the private key.  It may be the application requires nothing else, certainly nothing to do with Bitcoin or balances.
