### ISSUE TITLE
Cannot change Date display format from US-style

### ISSUE THREAD

**Issue by njbartlett** [bitcoin/bitcoin#2790] opened 2013-06-24 19:43 UTC
Dates in the UI are displayed in US-style format (month/day/year), which is confusing for British and other non-US English speakers who expect day/month/year.

 I expected to be able to change this via the User Interface Language settings, but there is no option for British English (en_GB).

**Comment by jonasschnelli** [comment] 2015-11-30 14:12
The language/regional formatting will be chosen by the system locale or could be overwritten by the `-lang=<ISO_LANG>` argument or over the GUI settings panel. Closing.

**Closed by jonasschnelli** 2015-11-30 14:12 UTC
Labels: GUI, Refactoring

**Comment by MarcoFalke** [comment] 2015-11-30 14:31
@jonasschnelli Does `-lang=` also overwrite the Dates? For me it does not, so I think that's what the bug was reporting.

**Comment by jonasschnelli** [comment] 2015-11-30 14:40
Sorry. Your right. `-lang` keeps the locale.
But IMO the application behavior is correct. It uses the system wide locale settings to chose the date formatting pattern. I can't remember seeing an application that allowed users to override the date format in per-application settings.

**Comment by MarcoFalke** [comment] 2015-11-30 14:44
Right, but what about GB locale vs US locale? Is qt indeed displaying US locale when the system is running GB? (Haven't yet checked myself)

**Comment by MarcoFalke** [comment] 2015-12-15 15:58
Couldn't reproduce the issue here. Thanks for closing.
