### ISSUE TITLE
bitcoin-tx.exe isn't shipped as part of the NSIS installers on Windows

### ISSUE THREAD

**Issue by Michagogo** [bitcoin/bitcoin#5605] opened 2015-01-06 12:25 UTC

**Comment by laanwj** [comment] 2015-01-06 16:25
Ping @theuni

Maybe we need a discussion about what to in include in the installer versus the .zip. I'd imagine that by far most people that download the installer only use bitcoin-qt. This would be analogous to the default download (.dmg) for MacOSX, which always only included the graphical client.

**Comment by jgarzik** [comment] 2015-01-06 16:27
+1 @laanwj 

I would prefer to keep the installer-shipped contents consistent across platforms.

**Comment by luke-jr** [comment] 2015-01-06 16:39
NSIS supports a nice "select what to install" step that would be appropriate IMO.

**Comment by Michagogo** [comment] 2015-01-06 16:39
I can't disagree with consistency. The question is, would it be better to add the other stuff to OS X, or remove it from Windows? The thing is that the two systems have very different install paradigms. OS X is "drag (what looks like) this one file/blob into place", while Windows is "run this installer, it puts everything in the right place, updates it if needed, and registers with the system". I would personally think that adding it to OS X (if that's possible, I don't know much about OS X's apps-that-are-really-directories-but-pretend-to-be-files-in-Finder-and-magically-start-the-right-executable structure) would be preferable to removing them from Windows, because for Windows users like myself, having the exe be in a specific place and auto-updated is nice, and I assume that it would be the same for OS X users, with the ability to have a single update action that updates everything in place, with all paths remaining as-is. So from that standpoint, I think I would vote for adding the extras to OS X rather than dropping them from Windows. But I don't know if this kind of change is too big to go in between RCs. If so, I would say that we should add bitcoin-tx.exe for now, sticking with the current practice of shipping all the bins (other than the tests) in the installer.

**Comment by Michagogo** [comment] 2015-01-06 16:40
Oh, that's a good point -- why aren't we using the feature selector?

**Comment by theuni** [comment] 2015-01-07 02:13
Either way is fine by me. For OSX, we could add a "utils" folder inside the dmg, although there's no obvious/standard way to install them. Instead, the user would just keep the dmg around, or drag the folder somewhere.

If we went that route, we could add the libs and includes as well. And do the same for windows, with options for each. In doing so, we'd negate the need for separate tarballs/zips.

Sounds very reasonable to me, though I'd much prefer to wait until after 0.10 to do it.

**Comment by Michagogo** [comment] 2015-01-07 09:56
Is it considered a bad thing to have other executables inside a .app
bundle/directory? I was thinking they could go in there, picturing it as
"somewhere out of the way, where a slightly more advanced user can look if
they want to, that won't be in the way and confusing to more basic users".
But I don't actively use a Mac nor am I familiar with its development
practices, so there may be a good reason not to. I don't know.

**Comment by laanwj** [comment] 2015-01-07 11:24
What I would like to avoid is including more than necessary, increasing the sizes of the popular downloads. Due to our reliance on static linking, every additional executable, even simple utilities add a lot of weight.

In all the time we've shipped MacOSX releases, almost one ever complained about there not being a separate bitcoind/bitcoin-cli. The few people I know that need them (such as @rktoomey) prefer them as separate executables in a  .zip, because they can be easier integrated into scripting/testing workflows. So I'd argue against including them in the dmg. 99% of users won't even realize they are there and they're just dead-weight.

I'm not against adding bitcoin-tx to the Windows installer, but my experience is that most windows users won't be using command line utilities, because they prefer clicking but also because the windows cmd.exe is terrible to use as a shell.

**Comment by theuni** [comment] 2015-01-08 20:13
As a data point: For OSX, adding bitcoind, bitcoin-cli, and bitcoin-tx to the dmg adds ~5 megs to the total size. 11Mb -> 16Mb. The 0.9.3 dmg is already 16Mb, due to the shared Qt.

I still really don't care either way, just providing real numbers.

**Comment by laanwj** [comment] 2016-02-16 15:33
Closing this, "works as intended". If you need the utilities, there is the zip archive which has them all.

**Closed by laanwj** 2016-02-16 15:33 UTC
Labels: Build system
