### ISSUE TITLE
contrib/signet/getcoins.py no longer useable

### ISSUE THREAD

**Issue by weirdwhala** [bitcoin/bitcoin#29679] opened 2024-03-20 01:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

got Unexpected error when contacting faucet: 403 Client Error: Forbidden for url: https://signetfaucet.com/captcha
seems because the captcha itself add some anti-bot framework

### Expected behaviour

successfully run

### Steps to reproduce

just run ./getcoins.py --cmd ../../src/bitcoin-cli

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

latest

### Operating system and version

macos

**Comment by willcl-ark** [comment] 2024-03-20 14:14
Thanks for the report.

I think thic could be a result of cloudflare implementing anti-bot JS checks. I am able to retrieve the captcha using `curl -v  https://signetfaucet.com/captcha`, also using HTTP1.1 (which I think `requests` is limited to?), but unable using python.

Perhaps @kallewoof can shed some light on whether using Cloudflare is new to this site and if it therefore is what's caused the breakage?

It seems that even other [options](https://github.com/kaliiiiiiiiii/Selenium-Driverless) would provide only intermittent results at best (until Cloudflare changes blocking heuristics)...

**Comment by kallewoof** [comment] 2024-03-23 15:08
I believe this is due to the "under attack" mode I enabled when the faucet was pummeled back a while ago. I dropped to "high security" level. Does this fix the issue?

**Comment by willcl-ark** [comment] 2024-04-04 09:27
Thanks @kallewoof, I can confirm that the script is now working again as expected:

![image](https://github.com/bitcoin/bitcoin/assets/6606587/1c0372c1-f36a-4682-91b3-e59bd981896b)

Hopefully "attack mode" is not needed again :)

Closing for now.

**Closed by willcl-ark** 2024-04-04 09:27 UTC
Labels: Scripts and tools

**Comment by sutt0n** [comment] 2024-07-13 21:11
@willcl-ark @kallewoof It seems that this issue is still occurring, or at least there's another issue related to this one with the Signet faucet -- is the faucet drained, or non-functioning at the moment? I've failed to get _any_ transactions to go through whenever it says "A pay-out has been queued"
