### ISSUE TITLE
Qt: If you reindex a black bar shows up on the bottom of the window when the sync overlay is hidden

### ISSUE THREAD

**Issue by CryptAxe** [bitcoin/bitcoin#17269] opened 2019-10-27 00:52 UTC
I was testing from commit be50469217bd775c4305938634c32e5932f47841 and noticed that the "out of sync" overlay went away correctly after mining blocks, but then after restarting with --reindex this black bar shows up after the overlay is hidden. I've only tested this in regtest mode. I'm not sure that the issue is related to the overlay but it seems to show up right when the overlay is hidden. 

![Screenshot_20191026_171200](https://user-images.githubusercontent.com/8107318/67627655-16153100-f815-11e9-967a-d5ea0a254965.png)

On another system:

Before reindex
![Screenshot_20191026_174635](https://user-images.githubusercontent.com/8107318/67627854-3515c200-f819-11e9-87b2-c6f8172480fd.png)

After reindex 
![Screenshot_20191026_174657](https://user-images.githubusercontent.com/8107318/67627855-38a94900-f819-11e9-87c1-c5296c1a2636.png)

**Comment by fanquake** [comment] 2020-04-27 05:56
Going to close this a duplicate of #17967. Will likely be fixed by #17968.

**Closed by fanquake** 2020-04-27 05:56 UTC
Labels: GUI
