### ISSUE TITLE
Problem upgrading to 0.17.0 on macOS High Sierra 10.13.6

### ISSUE THREAD

**Issue by pierrenoizat** [bitcoin/bitcoin#14414] opened 2018-10-06 09:59 UTC
Double clicking on the bitcoin-0.17.0-osx.dmg file does not yield the expected result (Finder cannot open the volume).

**Comment by jonasschnelli** [comment] 2018-10-06 12:46
I can confirm the issue (tested on 10.12 and 10.14). Somehow no-one found this bug during the RCs (it seems that all testers preferred the .tar.gz version).

Removing the .DS_Store fixes the issue (https://github.com/bitcoin/bitcoin/pull/14416/files), but obviously it removes the window size, arrangement and the background.

Very likely it's an upstream bug in https://github.com/al45tair/ds_store where it leads to incompatibility with newer macOS versions.

Either we roll back to manual .DS_Store creation (IMO preferred) or trying to find the difference in the proprietary .DS_Store file format that makes newer macOS version crash.

**Comment by fanquake** [comment] 2018-10-08 01:55
@jonasschnelli I'm not able to recreate this on macOS 10.14, using this .dmg: https://bitcoincore.org/bin/bitcoin-core-0.17.0/bitcoin-0.17.0-osx.dmg.

However the opening behaviour has changed. The `0.17.0` dmg no longer opens a Finder window (just mounts), compared to `0.16.3`. i.e:
![0 17 0](https://user-images.githubusercontent.com/863730/46589737-24988980-cae8-11e8-9964-ffbfd8d58aef.png)

0.16.3:
![0 16 3](https://user-images.githubusercontent.com/863730/46589735-22362f80-cae8-11e8-9ecf-ac2acdff0a3a.png)

**Comment by jonasschnelli** [comment] 2018-10-08 07:30
On my 10.14 system(s) (tested two) it also mounts,... but clicking on the disk image on the desktop doesn't open a window (I also had a crash).

**Comment by rex4539** [comment] 2018-10-08 11:41
I can reproduce the bug too. Attempting to mount the image, crashes the Finder.

macOS 10.13.6

**Comment by rex4539** [comment] 2018-10-11 19:45
Here is the reason for the Finder crash:

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFData getCString:maxLength:encoding:]:`

**Comment by Stoner19** [comment] 2018-10-14 02:38
I too have had the same issue with 0.17.0

**Comment by Ykid** [comment] 2018-10-19 10:06
build failed on Mojave 10.14

********* Finished testing of WalletTests *********
2018-10-19 18:02:19.070 test_bitcoin-qt[42036:38468132] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber addSubview:]: unrecognized selector sent to instance 0x1'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3b03343d __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff66f40720 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3b0b0255 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff3afd2ad0 ___forwarding___ + 1486
	4   CoreFoundation                      0x00007fff3afd2478 _CF_forwarding_prep_0 + 120
	5   libqmacstyle.dylib                  0x000000010dbc3e6b qt_plugin_instance + 18539
	6   libqmacstyle.dylib                  0x000000010dbcd15c qt_plugin_instance + 56156
	7   QtWidgets                           0x000000010c96502d _ZNK12QCommonStyle11drawControlEN6QStyle14ControlElementEPK12QStyleOptionP8QPainterPK7QWidget + 893
	8   libqmacstyle.dylib                  0x000000010dbc9b95 qt_plugin_instance + 42389
	9   QtWidgets                           0x000000010ca71c35 _ZN11QPushButton10paintEventEP11QPaintEvent + 117
	10  QtWidgets                           0x000000010c92192b _ZN7QWidget5eventEP6QEvent + 1131
	11  QtWidgets                           0x000000010c8e66ad _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 269
	12  QtWidgets                           0x000000010c8e7afc _ZN12QApplication6notifyEP7QObjectP6QEvent + 540
	13  QtCore                              0x000000010c3741b8 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 168
	14  QtWidgets                           0x000000010c919f5a _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 2474
	15  QtWidgets                           0x000000010c91a8b1 _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 1121
	16  QtWidgets                           0x000000010c91a74d _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 765
	17  QtWidgets                           0x000000010c91a2f7 _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 3399
	18  QtWidgets                           0x000000010c91a8b1 _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 1121
	19  QtWidgets                           0x000000010c91a2f7 _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 3399
	20  QtWidgets                           0x000000010c8f3adb _ZN14QWidgetPrivate10scrollRectERK5QRectii + 8251
	21  QtWidgets                           0x000000010c8f26a7 _ZN14QWidgetPrivate10scrollRectERK5QRectii + 3079
	22  QtWidgets                           0x000000010c942efa _ZN14QDesktopWidget11qt_metacallEN11QMetaObject4CallEiPPv + 15994
	23  QtWidgets                           0x000000010c940538 _ZN14QDesktopWidget11qt_metacallEN11QMetaObject4CallEiPPv + 5304
	24  QtWidgets                           0x000000010c8e66ad _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 269
	25  QtWidgets                           0x000000010c8e7afc _ZN12QApplication6notifyEP7QObjectP6QEvent + 540
	26  QtCore                              0x000000010c3741b8 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 168
	27  QtGui                               0x000000010cea12d4 _ZN22QGuiApplicationPrivate18processExposeEventEPN29QWindowSystemInterfacePrivate11ExposeEventE + 308
	28  QtGui                               0x000000010ce85acb _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 171
	29  QtGui                               0x000000010ce815b0 _ZN22QWindowSystemInterface23flushWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 576
	30  QtGui                               0x000000010ce926b8 _ZN15QPlatformWindow10setVisibleEb + 120
	31  QtGui                               0x000000010cea7b89 _ZN14QWindowPrivate10setVisibleEb + 1161
	32  QtWidgets                           0x000000010c91e6d8 _ZN14QWidgetPrivate8show_sysEv + 904
	33  QtWidgets                           0x000000010c920701 _ZN14QWidgetPrivate11show_helperEv + 401
	34  QtWidgets                           0x000000010c921303 _ZN7QWidget10setVisibleEb + 947
	35  QtWidgets                           0x000000010cadf48d _ZN7QDialog10setVisibleEb + 125
	36  QtWidgets                           0x000000010cadebb3 _ZN7QDialog4execEv + 243
	37  test_bitcoin-qt                     0x000000010b6892ce _ZN15SendCoinsDialog21on_sendButton_clickedEv + 7262
	38  QtCore                              0x000000010c37e1bc _ZNK11QMetaMethod6invokeEP7QObjectN2Qt14ConnectionTypeE22QGenericReturnArgument16QGenericArgumentS5_S5_S5_S5_S5_S5_S5_S5_S5_ + 1308
	39  QtCore                              0x000000010c37d7e9 _ZN11QMetaObject12invokeMethodEP7QObjectPKcN2Qt14ConnectionTypeE22QGenericReturnArgument16QGenericArgumentS7_S7_S7_S7_S7_S7_S7_S7_S7_ + 2089
	40  test_bitcoin-qt                     0x000000010b63be30 _ZN12_GLOBAL__N_19SendCoinsER7CWalletR15SendCoinsDialogRKN5boost7variantI14CNoDestinationJ6CKeyID9CScriptID19WitnessV0ScriptHash16WitnessV0KeyHash14WitnessUnknownEEExb + 1664
	41  test_bitcoin-qt                     0x000000010b639845 _ZN12_GLOBAL__N_17TestGUIEv + 1893
	42  QtCore                              0x000000010c37e1bc _ZNK11QMetaMethod6invokeEP7QObjectN2Qt14ConnectionTypeE22QGenericReturnArgument16QGenericArgumentS5_S5_S5_S5_S5_S5_S5_S5_S5_ + 1308
	43  QtTest                              0x000000010c742991 _ZN5QTest16qtest_qParseArgsEiPPcb + 7585
	44  QtTest                              0x000000010c743673 _ZN5QTest16qtest_qParseArgsEiPPcb + 10883
	45  QtTest                              0x000000010c744587 _ZN5QTest15toPrettyUnicodeE11QStringView + 1447
	46  QtTest                              0x000000010c745147 _ZN5QTest4qRunEv + 247
	47  QtTest                              0x000000010c744e00 _ZN5QTest5qExecEP7QObjectiPPc + 16
	48  test_bitcoin-qt                     0x000000010b619c59 main + 729
	49  libdyld.dylib                       0x00007fff6800e085 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
FAIL qt/test/test_bitcoin-qt (exit status: 134)

**Comment by fanquake** [comment] 2018-10-20 00:16
@Ykid That error is different to this issue, however should be fixed with #14011.

**Comment by Sjors** [comment] 2018-10-23 04:31
#14416 seems to fix this

**Comment by fanquake** [comment] 2018-10-26 01:11
This has been fixed in #14416, and should be available in a release shortly https://github.com/bitcoin/bitcoin/pull/14576.

**Closed by fanquake** 2018-10-26 01:11 UTC
Labels: macOS
