### ISSUE TITLE
bitcoind using wrong IP instead of -bind

### ISSUE THREAD

**Issue by Mellnik** [bitcoin/bitcoin#6698] opened 2015-09-19 09:10 UTC
I told bitcoin.conf to use 5.135.180.85 but now bitcoind makes connections on a totally other IP-Address.

![screen](http://puu.sh/kgwaY/aba79d2e9e.png)

I don't want bitcoind to use IPs other than 5.135.180.85.

Is that on purpose?

**Comment by abitfan** [comment] 2015-09-19 10:24
The bind option specifies the ip bitcoind listen's on and according to your screenshot it works as expected. The ip address that is used for outgoing connections is your primary ip address, again, as expected.  You can change that with some linux magic.

**Comment by Mellnik** [comment] 2015-09-20 17:17
Nothing works as expected here. 91.121... is not my primary IP and now bitcoind even uses 5.135... for outgoing connections.

**Comment by laanwj** [comment] 2015-09-22 17:48
`-bind` does not affect outgoing connections. Would be OK with adding an option to set the outgoing bind for ipv4/ipv6.
Duplicate of #6476

**Closed by laanwj** 2015-09-22 17:48 UTC
