### ISSUE TITLE
Transaction creation failed

### ISSUE THREAD

**Issue by ptschip** [bitcoin/bitcoin#6522] opened 2015-08-05 18:53 UTC
Testing on Windows 7, both 32 and 64 bit versions. Bitcoin v.0.11.0

To re-create this issue 

1)  create a new empty wallet
2)  send 700 (yes 700) transactions to a single address in your new wallet from step 1.  In my test
I sent 1500 satoshi's for each of the 700.
3) From your new wallet send out a 2000 satoshi transaction and clck send (you will get the proper send confirmation dialog)
4) Close the dialog and send another 50 transactions into your wallet. Now you should have 750 outputs in your wallet all under one single address.
5) Now try to send the same 2000 satoshi transaction:  you will receive a "Transaction too large"  dialog.  Click OK on this and you will now receive the "Transaction creation failed!"  dialog.

Note: if you use the coin control feature you can select a couple of the outputs and then send correctly it`s only when coin control is not used that this issue happens.

**Comment by MarcoFalke** [comment] 2015-08-11 14:40
The client creates a transaction which is over 100,000 bytes, thus non-standard, and rejects it.

As you can't get 2000 satoshis by combining the existing (1500-satoshi-sized) outputs, the transaction is created using "random" outputs, which usually works...

I tried to find the cause for this problem, but it is unclear to me why ```CENT``` is used in [wallet.cpp](https://github.com/bitcoin/bitcoin/blob/3eaaf71fe76b659d8ed40fdf88ce1ba18b62cc36/src/wallet/wallet.cpp#L1655). Is this some left over from days where bitcoin was < 10 $ or does this have some actual meaning?

**Comment by MarcoFalke** [comment] 2015-09-01 22:28
Maybe even a duplicate of #1643.

**Comment by laanwj** [comment] 2016-02-16 16:58
Yes, this seems #1643.

**Closed by laanwj** 2016-02-16 16:58 UTC
Labels: Wallet
