### ISSUE TITLE
"abandon transaction" only removed tx from display until client restart

### ISSUE THREAD

**Issue by dooglus** [bitcoin/bitcoin#12179] opened 2018-01-14 00:38 UTC
commit 45cf8a03cb57b8639a8d47323bde46ba22d9eeaf

I recently made a transaction with too-low fees. I was in a hurry to get it confirmed, so I clicked "increase transaction fee" a bunch of times. Each time I clicked it, it added an extra transaction to the transactions tab.

Eventually one of the transactions confirmed, and all the others were marked as "conflicted". I right-clicked each of the conflicted transactions in turn and selected "abandon transaction". That caused them to disappear from the transactions tab.

When I restarted the client, all the conflicted transactions reappeared. I was hoping they would be gone permanently.

Am I misunderstanding what "abandon transaction" should do, or is it not working correctly?

Edit: two related points from this experience:

1) I wanted to double the fee, but "increase transaction fee" didn't give me any way to say how much to increase it by, so I had to click it maybe 20 times to get to the fee I wanted.

2) I was able to select all the conflicted transactions at once, and right-click the group. When I selected "abandon transaction" on the group, it only deleted one transaction from the display, not all of them. Why let me select multiple transactions if the right-click menu only operates on one of them anyway?

**Comment by MarcoFalke** [comment] 2018-01-16 17:08
> That caused them to disappear from the transactions tab.

That sounds like a bug. The rpc help for abandontransaction says that "It has no effect on transactions which are already conflicted". So the only thing that should happen on abandoning rbfed txes is that a trash icon is shown in the gui.

> I wanted to double the fee, but "increase transaction fee" didn't give me any way to say how much to increase it by, so I had to click it maybe 20 times to get to the fee I wanted.
 
You might want to use the bumpfee rpc, which should support that, IIRC. Pull requests welcome, though.

>  I was able to select all the conflicted transactions at once, and right-click the group. When I selected "abandon transaction" on the group, it only deleted one transaction from the display, not all of them. Why let me select multiple transactions if the right-click menu only operates on one of them anyway?

Pull request welcome

**Comment by MarcoFalke** [comment] 2018-01-16 17:45
> commit 45cf8a0

Couldn't reproduce on this commit either. Mind to share steps-to-reproduce, potentially with screenshots?

**Comment by dooglus** [comment] 2018-01-20 21:13
I tried reproducing on testnet, using the same git commit as before.

I sent a transaction to myself:

![01](https://user-images.githubusercontent.com/573356/35187946-2b7ae1c2-fde2-11e7-9771-5ef7a5f7a811.png)

![02](https://user-images.githubusercontent.com/573356/35187952-3e905ee0-fde2-11e7-8618-969cc4717247.png)

![03](https://user-images.githubusercontent.com/573356/35187954-42560836-fde2-11e7-8e93-722aeeb3131a.png)

I bumped the fee on it:

![04](https://user-images.githubusercontent.com/573356/35187957-4b3663e2-fde2-11e7-86eb-c441470d2314.png)

![05](https://user-images.githubusercontent.com/573356/35187960-561fb2ae-fde2-11e7-8ffa-84abe095faa8.png)

I tried abandoning the old transaction before either had confirmed. It got a trashcan icon next to it:

![06](https://user-images.githubusercontent.com/573356/35187966-6b3464e6-fde2-11e7-9f11-006ba9da8f7d.png)

I restarted the client. Nothing changed. I bumped the fee on the new transaction again:

![07](https://user-images.githubusercontent.com/573356/35187977-8247acf6-fde2-11e7-9427-8707f05aa089.png)

![08](https://user-images.githubusercontent.com/573356/35187981-864dec48-fde2-11e7-9b68-e1039602e350.png)

I waited for the newest transaction to confirm. It marked the other two as conflicted:

![09](https://user-images.githubusercontent.com/573356/35187988-9e66ec62-fde2-11e7-973d-acd0ed419685.png)

I abandoned the two conflicted transactions, one at a time. They disappeared from view:

![10](https://user-images.githubusercontent.com/573356/35188000-b5430ae2-fde2-11e7-8971-826133ae5ea0.png)

![11](https://user-images.githubusercontent.com/573356/35188001-bae7db6c-fde2-11e7-80e4-264db65623dd.png)

I restarted the client. The abandoned transactions were back again and showing up as conflicted:

![12](https://user-images.githubusercontent.com/573356/35188008-d29e7cfc-fde2-11e7-9085-c2da47ec4c90.png)

What is the expected behavior here? When I bump a transaction's fee am I meant to still see the old transaction in the list? Is it meant to stay there in conflicted state forever once the bumped transaction has confirmed?

It is making my non-testnet Bitcoin wallet look find of ugly with all the bumped transactions hanging around in conflicted state:

![13](https://user-images.githubusercontent.com/573356/35188052-9a46b076-fde3-11e7-8d7c-ea7a3aad562e.png)

I would use the `-zapwallettxes` flag to remove them but unfortunately I don't have a non-pruned node locally and don't see any way of 'zapping' transactions without a full copy of the blockchain.

**Comment by MarcoFalke** [comment] 2018-01-20 23:16
It should not be possible to abandon conflicted txes. They are already
conflicted, so no need to abandon

**Comment by MarcoFalke** [comment] 2018-01-27 22:16
See #12282

**Comment by Empact** [comment] 2018-02-16 07:08
FYI #12282 is now merged.

**Comment by MarcoFalke** [comment] 2018-02-16 16:38
Would still be interesting to figure out why qt behaves so strangely, i.e. remove the row...

**Comment by hebasto** [comment] 2022-12-05 11:55
> Eventually one of the transactions confirmed, and all the others were marked as "conflicted". I right-clicked each of the conflicted transactions in turn and selected "abandon transaction".

That issue looks outdated as it describes behavior no longer possible on the master branch, for example, a user's ability to abandon of a conflicted transaction (see https://github.com/bitcoin/bitcoin/pull/12282).

Suggesting to close this issue for now. If other mentioned points are still considered, maybe open a separated issues in the https://github.com/bitcoin-core/gui ?

**Comment by MarcoFalke** [comment] 2022-12-05 11:58
Yes, if this is still an issue with a recent version of Bitcoin Core, it might be good to share steps to reproduce in https://github.com/bitcoin-core/gui?

**Closed by MarcoFalke** 2022-12-05 11:58 UTC
Labels: Bug, GUI, Wallet
