### ISSUE TITLE
Listunspent does not return proper set of transactions

### ISSUE THREAD

**Issue by ThePiachu** [bitcoin/bitcoin#2846] opened 2013-07-23 03:38 UTC
I ran into issue with listunspent API call. 

getaddressesbyaccount("account") returns ['n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'] - my account has only 1 address.

I call getbalance("account", 6), I get a value of 2203.46345285 - I have 2K testnet Bitcoins in that address, that looks like a plenty of transactions to spent. 

I call listunspent(1, 999999, ["n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe"]) and get [] - nothing.

I did not use "move" command, just a lot of non-standard calls for creating new transactions and sending them (createraw, signraw, sendraw).

I check BTCLook and see plenty of unspent transactions - http://testnet.btclook.com/addr/n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe .

Similarly, calling listtransactions("Holding", 10, 0) returns:

[
   {
      'category':'receive',
      'account':'Holding',
      'blockhash':'000000007ba218fe3bbb3784b8d695cc986e5e466fa7c00f419678f0c9c4fd4e',
      'blockindex':56,
      'time':1374478540,
      'txid':'1941fd5935391114ed63a0ac1bd346b95f97730be8c33c1077b95cea39246006',
      'blocktime':1374478752,
      'amount':0.09989999,
      'confirmations':92,
      'timereceived':1374478540,
      'address':'n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'
   },
   {
      'category':'receive',
      'account':'Holding',
      'blockhash':'000000007ba218fe3bbb3784b8d695cc986e5e466fa7c00f419678f0c9c4fd4e',
      'blockindex':51,
      'time':1374478542,
      'txid':'0785d7b2ffc886deec34b31abdd4e25dff087d188a36384962536258c36096e0',
      'blocktime':1374478752,
      'amount':0.09989999,
      'confirmations':92,
      'timereceived':1374478542,
      'address':'n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'
   },
   {
      'category':'receive',
      'account':'Holding',
      'blockhash':'000000007ba218fe3bbb3784b8d695cc986e5e466fa7c00f419678f0c9c4fd4e',
      'blockindex':58,
      'time':1374478543,
      'txid':'df46e6639cbe58ba6e68edf89b9bd1ea0ebf1736902fe6a844efac6aeabc100f',
      'blocktime':1374478752,
      'amount':0.09989999,
      'confirmations':92,
      'timereceived':1374478543,
      'address':'n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'
   },
   {
      'category':'receive',
      'account':'Holding',
      'blockhash':'000000007ba218fe3bbb3784b8d695cc986e5e466fa7c00f419678f0c9c4fd4e',
      'blockindex':60,
      'time':1374478544,
      'txid':'0446b87eee83469d91b102c0cc39cef71f403a07e20997af0ce28371b3b9356c',
      'blocktime':1374478752,
      'amount':0.09989999,
      'confirmations':92,
      'timereceived':1374478544,
      'address':'n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'
   },
   {
      'category':'receive',
      'account':'Holding',
      'blockhash':'000000007ba218fe3bbb3784b8d695cc986e5e466fa7c00f419678f0c9c4fd4e',
      'blockindex':44,
      'time':1374478545,
      'txid':'6efbbd3fa826d23cece4107b2de6fc16b30792b261a5971974d63ee7ac35bd66',
      'blocktime':1374478752,
      'amount':0.09989999,
      'confirmations':92,
      'timereceived':1374478545,
      'address':'n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'
   },
   {
      'category':'receive',
      'account':'Holding',
      'blockhash':'000000007ba218fe3bbb3784b8d695cc986e5e466fa7c00f419678f0c9c4fd4e',
      'blockindex':62,
      'time':1374478547,
      'txid':'c398670415396795ef8d5a1577268d948d707d680679a70bdf00175f221ed6b3',
      'blocktime':1374478752,
      'amount':0.09989999,
      'confirmations':92,
      'timereceived':1374478547,
      'address':'n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'
   },
   {
      'category':'receive',
      'account':'Holding',
      'blockhash':'000000007ba218fe3bbb3784b8d695cc986e5e466fa7c00f419678f0c9c4fd4e',
      'blockindex':64,
      'time':1374478548,
      'txid':'acd1fb20bffc40e40da52256c53d3093429e5d19cc2682764a31c83818e9ad59',
      'blocktime':1374478752,
      'amount':0.09989999,
      'confirmations':92,
      'timereceived':1374478548,
      'address':'n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'
   },
   {
      'category':'receive',
      'account':'Holding',
      'blockhash':'000000007ba218fe3bbb3784b8d695cc986e5e466fa7c00f419678f0c9c4fd4e',
      'blockindex':17,
      'time':1374478549,
      'txid':'dd0edeaa84267baad818f127836ed8b4892a70f9a5bb99d9479cd4fb062c5a0b',
      'blocktime':1374478752,
      'amount':0.09989999,
      'confirmations':92,
      'timereceived':1374478549,
      'address':'n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'
   },
   {
      'category':'receive',
      'account':'Holding',
      'blockhash':'000000007ba218fe3bbb3784b8d695cc986e5e466fa7c00f419678f0c9c4fd4e',
      'blockindex':18,
      'time':1374478550,
      'txid':'584973a9f5ebb987311323f65786279c64fa000e9fdc371dbbcbc089a77dbb51',
      'blocktime':1374478752,
      'amount':0.09989999,
      'confirmations':92,
      'timereceived':1374478550,
      'address':'n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'
   },
   {
      'category':'receive',
      'account':'Holding',
      'time':1374549589,
      'txid':'a8c18f467d960e7304b77bc428e6e06308628c6d3ab777ec425d503561228108',
      'amount':99.99980234,
      'confirmations':0,
      'timereceived':1374549589,
      'address':'n1az1tf4FozhBRVG7Ab43e2iLGPPBasXbe'
   }
]

This is why I think that there is some bug in listunspent that makes this API call not return proper values.

**Comment by MeshCollider** [comment] 2018-03-07 14:51
I can't reproduce the issue in the OP, and there has been no further reports or discussion around this since 2013, so closing now

**Closed by MeshCollider** 2018-03-07 14:51 UTC
Labels: Bug, Wallet

**Comment by vtosev** [comment] 2018-04-26 13:54
I have a same problem. I am not using accounts and my node is 0.16.
Rescan didn't help.
I described it here: https://bitcoin.stackexchange.com/questions/73820/problem-with-balance-of-my-address
