### ISSUE TITLE
GUI shows generic out of sync warning when the clock is wrong.

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin/bitcoin#2001] opened 2012-11-11 02:12 UTC
I found user on IRC  getting the generic out of sync report and being told to try all manner of cargo cult repairs (e.g. resync).  Debug log showed his clock was exactly 24 hours fast.

This is probably unoptimal.  Showing out of sync when the last block is old makes sense, but there should probably be some additional text about your clock being wrong when your peers all say you're 1440 minutes off.

**Comment by hebasto** [comment] 2021-03-25 15:53
Cannot reproduce this issue on master (9217f9fe7351d9c36803456f88ae561e23f17ac9):

![DeepinScreenshot_select-area_20210326172200](https://user-images.githubusercontent.com/32963518/112502718-f92ab780-8d92-11eb-90db-075bb705ca87.png)

**Comment by laanwj** [comment] 2021-03-29 10:58
Looks like we can close this then. Thanks for checking @hebasto

**Closed by laanwj** 2021-03-29 10:58 UTC
Labels: GUI
