### ISSUE TITLE
Linter fixes

### ISSUE THREAD

**Issue by kallewoof** [bitcoin/bitcoin#14041] opened 2018-08-24 02:01 UTC
The linters are apparently breaking left and right on local machines and need to be disabled by developers. Ping @practicalswift et al.

I haven't seen any information on this except a mention in IRC, so any hints or error logs on this would be appreciated.

**Comment by kallewoof** [comment] 2018-08-24 03:04
"A new circular dependency in the form of "policy/policy -> validation -> pow -> policy/policy" appears to have been introduced.
^---- failure generated from test/lint/lint-circular-dependencies.sh
The command "test/lint/lint-all.sh" exited with 1."

```
$ git diff master src/policy 
$
```

**Comment by AkioNak** [comment] 2018-08-24 07:06
@kallewoof You can check whether ```policy.cpp``` does not include ```policy/policy.h``` .
I think that the linter(lint-circular-dependencies.sh and circular-dependencies.py) treats *.cpp and *.h in the same way, and sometimes make a miss-judgement.

**Comment by AkioNak** [comment] 2018-08-24 07:09
@kallewoof  I'm sorry, not ```policy.cpp``` but ```pow.cpp```.  I fixed previous message .

**Comment by kallewoof** [comment] 2018-08-24 07:28
@AkioNak I haven't touched the files. The linters should only tell me about new issues, not old ones that I didn't introduce.

**Comment by AkioNak** [comment] 2018-08-24 07:51
@kallewoof Oh, I see. That linter do not filter the result whether you touched any file or not.

**Comment by practicalswift** [comment] 2018-08-24 07:56
@kallewoof Thanks for the ping! Sounds bad. Let’s try to resolve that quickly!

Pinging in @Empact who wrote the linter for circular dependencies and @sipa who wrote the original Python script that the linter uses.

Please report any linter issues here!

**Comment by practicalswift** [comment] 2018-08-24 08:00
@kallewoof Do you know which linters that were causing problems and for whom? :-)

**Comment by Empact** [comment] 2018-08-24 16:42
@kallewoof can you point to a branch where the issue exists?

**Comment by ryanofsky** [comment] 2018-08-24 18:12
> I think that the linter(lint-circular-dependencies.sh and circular-dependencies.py) treats *.cpp and *.h in the same way, and sometimes make a miss-judgement.

This is true and I added an escape hatch for it here: cbbb1d5cfb5fc47b84d6992aa6996b56f4b38a0d

**Comment by kallewoof** [comment] 2018-08-27 05:05
@Empact https://github.com/kallewoof/bitcoin/tree/signet

**Comment by kallewoof** [comment] 2018-08-27 07:29
FWIW @AkioNak identified the problem in the above case to be https://github.com/kallewoof/bitcoin/commit/5143d5ddc73ac5d456cd4718cdca66fdc951b218#diff-ba91592f703a9d0badf94e67144bc0aaR13

**Comment by Empact** [comment] 2018-08-28 00:58
I take it it was a circular dependency then?

**Comment by AkioNak** [comment] 2018-08-28 02:13
@Empact This is not a circular inclusion.
I reproduced this error by specifying 3 **cpp** filenames to ```circular-dependencies.py```  on @kallewoof 's ```signet``` branch as following:

```bash
$ cd src
$ ../contrib/devtools/circular-dependencies.py policy/policy.cpp validation.cpp pow.cpp
```

**Comment by practicalswift** [comment] 2018-08-29 08:33
Was this issue limited to circular dependencies?

If so the statement "linters are apparently breaking left and right on local machines and need to be disabled by developers" was a false alarm? :-)

If there are any linter issues beyond the circular dependencies stuff I'd like to know and fix them! :-)

**Comment by kallewoof** [comment] 2018-08-29 09:44
@practicalswift No, the statement stands. I was just posting a case of my own, but the reports were from other people.

**Comment by practicalswift** [comment] 2018-08-29 10:47
@kallewoof Are there any bug reporters from IRC that we can ping in to this GitHub conversation to get clarification on the specifics? :-)

**Comment by MarcoFalke** [comment] 2018-08-29 11:00
Closing for now, we can create a new issue or fix issues as they come up.

**Closed by MarcoFalke** 2018-08-29 11:00 UTC
Labels: Tests

**Comment by ryanofsky** [comment] 2018-08-29 11:51
I've had to work around issues in my prs as new linters have been added. 

It would be nice if before adding a new linter, you tested it on open PRs that have been updated recently, and notified failing PR authors so they could look into errors and fix things or report problems with the linter.

**Comment by practicalswift** [comment] 2018-08-29 11:56
@ryanofsky Ah, just to clarify – so these were issues discovered by the linters rather than problems in the linters? :-)  Have you encountered any issues in the linters themselves?

**Comment by ryanofsky** [comment] 2018-08-29 12:56
> @ryanofsky Ah, just to clarify – so these were issues discovered by the linters rather than problems in the linters? :-) Have you encountered any issues in the linters themselves?

Yes, there is the bug in the circular dependencies linter described above: https://github.com/bitcoin/bitcoin/issues/14041#issuecomment-415839441, a bug in the format-strings linter fixed in #10443 (61ab4c17eebf9b73267c992fb664d603620f9e81), and a bug in include-guards linter fixed in #10102 (0f956d6b0d26c92a1656976b0518e0a469033e47).

But to me it is irrelevant whether bug is in the linter or not. For example, the linter bugs I found were pretty easy to fix, but I spent hours refactoring code and introducing a callback mechanism in [pr/fee.18](https://github.com/ryanofsky/bitcoin/commits/pr/fee.18) to avoid referencing CTxMemPoolEntry in fees_input.h and introducing a new circular dependency.

It would be nice to get warnings when a new linter is added that breaks PRs, so issues can be fixed in advance and don't result in PRs being left conflicted while lint issues are debugged. Since linters are fast to run and don't require building, it seems like it would be very easy to write a script that would check a new linter against a list of PRs and capture all the errors, so PR authors could have advance warning about problems.

**Comment by practicalswift** [comment] 2018-08-29 13:16
@ryanofsky Yes, that would be the ideal way to do it when introducing new linters! I'll look what I can do to make that happen :-)

**Comment by practicalswift** [comment] 2018-08-30 23:17
Fixes to macOS linter issues can be found in PR #14115. Please review :-)

**Comment by practicalswift** [comment] 2018-09-05 07:44
This seemed urgent - please review #14115 to get this fixed :-)

**Comment by kallewoof** [comment] 2018-09-10 00:51
You're being incessant. People will review things as time permits.
