### ISSUE TITLE
SendMoney() : Signing transaction failed

### ISSUE THREAD

**Issue by mohamedfarrag** [bitcoin/bitcoin#5828] opened 2015-02-25 07:42 UTC
Sometimes I got this error message when I try to send bitcoins , I don't understand why ? 
PS: this happened after I encrypted my wallet , is it related ?

**Comment by paveljanik** [comment] 2015-02-25 08:05
Yes. Try it on a testnet wallet first. Read `bitcoin-cli help encryptwallet`.

**Comment by paveljanik** [comment] 2015-02-25 08:12
Please close this issue as this is not real issue in Bitcoin Core.

**Comment by mohamedfarrag** [comment] 2015-02-25 08:25
I did it in test net , and I'm providing the passphrase of course before sending bitcoins

**Comment by paveljanik** [comment] 2015-02-25 08:30
So please write here, what are you doing, show us utxos etc.

**Comment by mohamedfarrag** [comment] 2015-02-25 08:49
I just send bitcoin :
walletpassphrase ******* 5  
sendtoaddress "bitcoinaddress" amount

That's it and received the error that I wrote.

**Comment by paveljanik** [comment] 2015-02-25 09:02
I just did this:
```
bitcoin-cli sendtoaddress ...address... amount
error: {"code":-13,"message":"Error: Please enter the wallet passphrase with walletpassphrase first."}

bitcoin-cli walletpassphrase ...password... 5 

bitcoin-cli sendtoaddress ...address... ...amount...
...tx id...
```

**Comment by paveljanik** [comment] 2015-02-25 10:01
I can't reproduce here. If the wallet is encrypted, I get either
```
error: {"code":-13,"message":"Error: Please enter the wallet passphrase with walletpassphrase first."}
```
when the wallet is not unlocked or
```
txid
```
when the wallet is unlocked at the time of the action. But this is in clean wallet with one unspent transaction output. You have to investigate which outputs you have to spent.
What is special about your testnet wallet?

**Comment by mohamedfarrag** [comment] 2015-02-25 11:27
I don't know maybe something went wrong to this wallet , I tried it in a new one and it works !

**Closed** 2015-02-25 13:40 UTC
