### ISSUE TITLE
Enhancement - Build in coins mixing "CoinJoin"

### ISSUE THREAD

**Issue by karek314** [bitcoin/bitcoin#7571] opened 2016-02-21 08:33 UTC
Build in coins mixing "CoinJoin" into bitcoin full nodes, which will allow anonymous transactions like in dash/dark coin or monero.

**Comment by fanquake** [comment] 2016-02-21 08:41
This is a duplicate of #3226

**Closed** 2016-02-21 10:38 UTC
