### ISSUE TITLE
Still possible to set mintxtfee to 0?

### ISSUE THREAD

**Issue by kevinmartinmauro** [bitcoin/bitcoin#5746] opened 2015-02-03 21:11 UTC
Is it still possible to set the mintxfee to zero? 

I set my bitcoin.conf to
mintxfee=0
and I get
: Invalid amount for -mintxfee=<amount>:'0'

version 0.9.2

I have a small number of low-byte transactions I would like to send across the network. I understand they might never be relayed but I would still like to try.

**Comment by kevinmartinmauro** [comment] 2015-02-03 21:15
problem is somewhat solved by setting 
mintxfee=0.00000001
minrelaytxfee=0.00000001

**Comment by paveljanik** [comment] 2015-02-06 11:07
If the problem is solved, please close the issue.

mintxfee logic is:

``` c
        CAmount n = 0;
        if (ParseMoney(mapArgs["-mintxfee"], n) && n > 0)
            CWallet::minTxFee = CFeeRate(n);
        else
            return InitError(strprintf(_("Invalid amount for -mintxfee=<amount>: '%s'"), mapArgs["-mintxfee"]));
```
so the behaviour is as coded.

**Comment by MarkusTeufelberger** [comment] 2015-02-13 19:58
The issue seems to be that a mintxfee of 0 is a potentially valid setting that can not be validly set with that code. Fees can be 0.

**Comment by gavinandresen** [comment] 2015-02-16 15:12
The reference implementation wallet won't allow you to create transactions that the reference implementation will not relay or mine.

I would strongly advise you to NOT set -minrelaytxfee and -mintxfee to very small values, because sooner or later one or more of your transactions will not get relayed/mined and your wallet will get 'stuck' with coins that it thinks are already spent.

**Closed** 2015-02-16 22:02 UTC
