### ISSUE TITLE
`libbitcoinkernel`: Building `mingw-w64` dll's broken

### ISSUE THREAD

**Issue by dongcarl** [bitcoin/bitcoin#25008] opened 2022-04-27 15:58 UTC
We're unable to build a `dll` for `libbitcoinkernel` right now because of unique problems arising out of the combination of `mingw-w64` + `winpthread` + `libtool` + `dll's`

https://github.com/bitcoin/bitcoin/blob/466c6161505f0c9c68e4c4f41e3e40b8660d3a7a/src/Makefile.am#L816-L822

Various methods have been proposed and we should discuss here.

**Comment by dongcarl** [comment] 2022-04-27 16:00
Previous discussion originally found [here](https://github.com/bitcoin/bitcoin/pull/24322#issuecomment-1110016664) by theuni reproduced:

> This commit fixes Windows dll linking for me: https://github.com/theuni/bitcoin/commit/9612f5f0f1e3295065dbd8a0e0f472f8f020bbd9 . Untested, but it now links. I'll be testing it out as a next step.
> 
> Thanks to @dongcarl for pointing out the problem. 
> 
> Edit: I'm unable to find what's actually affected by this define in my local mingw tree and in depends. Maybe gcc does something internally with it or something?
> 
> Edit2: Found it!: https://github.com/mingw-w64/mingw-w64/blob/f79f89f976dc5345090db557fb20d5deba913d9f/mingw-w64-libraries/winpthreads/include/pthread.h#L86
> 
> That seems like heavy-handed behavior for mingw-w64, much more useful would be for them to define and use `PTHREADS_DLL_EXPORT` instead. I'll work to understand this better and upstream a patch if necessary.

**Comment by hebasto** [comment] 2022-04-27 16:06
Could another approach suggested in #24994 be useful (did not test yet)?

**Comment by hebasto** [comment] 2022-04-27 16:35
@theuni 

What are default values of `lt_cv_prog_compiler_pic` and `lt_cv_prog_compiler_pic_CXX` for mingw-w64?

**Comment by theuni** [comment] 2022-04-27 20:52
@hebasto Sorry, that wasn't clear from the change.

Without this hack, they contain:`-DDLL_EXPORT -DPIC`. So the override here simply removes the `DLL_EXPORT` define.

**Comment by hebasto** [comment] 2022-04-28 19:00
I've tested @theuni's [patch](https://github.com/bitcoin/bitcoin/issues/25008#issuecomment-1111207358), and it works for me.

It fixes #19772 and #24972 as well.

Considering this patch as libtool hack, still researching non-hack ways to fix the problem..

**Comment by fanquake** [comment] 2022-04-29 07:51
> I believe that https://github.com/theuni/bitcoin/commit/9612f5f0f1e3295065dbd8a0e0f472f8f020bbd9 is the clean/proper fix for us for the issue. We don't want pthreads symbols exported, and that fixes the specific issue.

ACK https://github.com/theuni/bitcoin/commit/9612f5f0f1e3295065dbd8a0e0f472f8f020bbd9, NACK #24972, #24994 etc.

**Comment by theuni** [comment] 2022-04-29 17:19
I've opened a pull-request upstream to add a fix for this: https://sourceforge.net/p/mingw-w64/mingw-w64/merge-requests/23/

I'll wait a day or two and see if they respond before going any further on this.

**Comment by dongcarl** [comment] 2022-04-29 18:19
I actually think it's entirely possible that building a convenience library and then an actual library out of the convenience library could be the way to do it. We shall see.

Another point of reference here is the libtool manual section about how to handle DLL_EXPORT: https://www.gnu.org/software/libtool/manual/libtool.html#Windows-DLLs

**Comment by fanquake** [comment] 2022-04-29 18:43
> I actually think it's entirely possible that building a convenience library and then an actual library out of the convenience library could be the way to do it like in https://github.com/bitcoin/bitcoin/pull/24994. We shall see.

I don't see why we should be refactoring our code, that works everywhere else, and adding more libraries, to work around a problem that occurs for a single OS, and in some part, only in certain build configurations. Especially if we know that it's libtool that is *broken*, it'd seem better for us to just use a single, well documented, scoped to the Windows use of libtool workaround, as opposed to changing our source code to accommodate its quirkiness.

Note that #24994 alone seemingly doesn't fix all the issues, i.e #24972, so even if we went ahead with either/both changes, we're still going to continue to carry the windows-only libtool workarounds we've already got in our build system, which I'd say is the worst of both worlds (code refactoring + still having windows libtool workarounds). I'd rather add one more (well documented) libtool workaround to the pile, and hope that this may all become a moot point some time into the future (cmake 🦆s). Interested to see what appears on the mailing list upstream.

**Comment by theuni** [comment] 2022-04-29 18:52
I'm not sure I understand the discussion about nested librarries, or avoiding libtool. This problem has nothing to do with libtool except that libtool is the one guilty of adding the problematic define.

Please note also that any library could be causing this problem. It just happens to be libpthread. It could equally be libevent or libzmq.

Also please not that `DLL_EXPORT` is not any kind of magic define or token. It's a convention used by libtool, similar to autoconf's `HAVE_CONFIG_H`. In this case though, there's a clash of uses.

Here's the snippet we're dealing with in pthread.h:

```c++
#if defined DLL_EXPORT
#ifdef IN_WINPTHREAD
#define WINPTHREAD_API __declspec(dllexport)
#else
#define WINPTHREAD_API __declspec(dllimport)
#endif
#else
#define WINPTHREAD_API
#endif
```

Here's part of the explanation I provided in the patch to upstream:

> 
> When building a libtool lib, libtool automatically defines "DLL_EXPORT" for objects intended to be linked into a shared library.
> 
> Applications are then intended to also define "DLL_EXPORT", which has the effect of importing the functions from the exported dll.
> 
> However, this goes bad when a downstream user is itself a libtool lib which is attempting to statically link in libpthread. libtool sets "DLL_EXPORT" for itself as expected, so that the downstream lib can export its own symbols. HOWEVER it also has the effect of trying to _import_ the libpthread symbols, which doesn't work because libpthread is being linked statically rather than as a dll.

So the problem is that we're trying to import when building a dll. [From the Microsoft docs:](https://docs.microsoft.com/en-us/cpp/build/importing-function-calls-using-declspec-dllimport?view=msvc-170)

> You only want to use __declspec(dllimport) when calling DLL functions from outside the DLL itself. Don't use __declspec(dllimport) on functions inside a DLL when building that DLL.

The fix is thus to avoid doing the dllimport when building our own dll.  The nice way would be to have a define that could be set to avoid it. This is the [fix I've proposed upstream.](https://sourceforge.net/u/theuni2/mingw-w64/ci/cf09b48dae24316b06fee83b23eb0af574bb5f14/)

Barring that, we just need to avoid having `DLL_EXPORT` defined in any file that ends up including pthread.h. Libtool appends this by default. The configure change I've proposed above prevents libtool from doing that, thereby fixing the problem.

Another solution might be to add `-UEXPORT_DLL` to AM_CPPFLAGS, overriding libtool's define.

**Comment by dongcarl** [comment] 2022-04-29 18:58
Ah! The upstream explanation is very clear indeed. Makes sense!

**Comment by ryanofsky** [comment] 2022-04-29 19:25
> Another solution might be to add -UDLL_EXPORT to AM_CPPFLAGS, overriding libtool's define.

Another option might be linking against the pthread library dynamically instead of statically when building a dynamic library, in which case mingw's `__declspec(dllimport)` annotations would be correctly applied.

I think linking dependencies of a dynamic library into it dynamically is more typical if you are using dynamic libraries to begin with. Linking dependencies of a dynamic library into it statically can also make sense, but can cause problems because this can leave you with multiple instances of the same static library having to coexist inside the same process, each with their own separate global variables, and possibly inconsistent function definitions. This is ok if libraries are high level, and you aren't trying to share pointers or handles between the different library instances. I don't think we know if this applies to pthreads, but Cory's upstream patch should let us find out.

**Comment by theuni** [comment] 2022-04-29 19:42
ACK. I explored this a little bit today because I agree a single dll may or may not be how we want to ship in the end.

In fact, to your point, libstdc++ currently still gets linked dynamically. This can be fixed as usual (I did a quick check) by adding `-static-libstdc++` to the dll link flags, but it definitely begs the question: do we want to ship a few dll's instead?

I think at least in the beginning we should try to lump everything into a single dll. By controlling our exports (I think) we should be able to avoid leaking out symbols like `pthread_create` which would obviously be problematic.

But I agree it's very possible we run into startup problems or handle collisions or something that forces us to switch to multiple dll's. Something like an app  interacting with `thread_local` vars on a thread spawned by the dll... I could see that going sideways.

**Comment by hebasto** [comment] 2022-04-30 09:50
> I'd rather add one more (well documented) libtool workaround to the pile...

Just a reminder, that this will be the 4th Windows-related Libtool hack in our build system.

[First](https://github.com/bitcoin/bitcoin/commit/1723862e82926ef24ccf1d098dc02933f893cf48) is: https://github.com/bitcoin/bitcoin/blob/23daa86ec132cf1208b8c1b13463e58e57a26a20/configure.ac#L61-L68

[Second](https://github.com/bitcoin/bitcoin/commit/575e70c0c6c14058e4fc6c37f4e4d52399b69432): https://github.com/bitcoin/bitcoin/blob/23daa86ec132cf1208b8c1b13463e58e57a26a20/configure.ac#L696-L698

**Comment by hebasto** [comment] 2022-04-30 10:23
> I'd rather add one more (well documented) libtool workaround to the pile...

Just a reminder, that this will be the 4th Windows-related Libtool hack in our build system (sorry if it looks like or is off-topic).

[First](https://github.com/bitcoin/bitcoin/commit/575e70c0c6c14058e4fc6c37f4e4d52399b69432) is: https://github.com/bitcoin/bitcoin/blob/23daa86ec132cf1208b8c1b13463e58e57a26a20/configure.ac#L696-L698

[Second](https://github.com/bitcoin/bitcoin/commit/1723862e82926ef24ccf1d098dc02933f893cf48): https://github.com/bitcoin/bitcoin/blob/23daa86ec132cf1208b8c1b13463e58e57a26a20/configure.ac#L61-L68

[Third](https://github.com/bitcoin/bitcoin/commit/9ed8979e294fb7a42e26a6b6541f614554663bea): https://github.com/bitcoin/bitcoin/blob/23daa86ec132cf1208b8c1b13463e58e57a26a20/configure.ac#L712-L718

Btw, the [third](https://github.com/bitcoin/bitcoin/commit/9ed8979e294fb7a42e26a6b6541f614554663bea) Libtool hack did actually cause the #19772 bug.

**Comment by theuni** [comment] 2022-05-02 17:22
Upstream acknowledged the problem and committed a fix that goes even further than my proposed patch: https://sourceforge.net/p/mingw-w64/mingw-w64/ci/489520900fb6853c8be97e9d0214f39a77c846d9/

(Funny enough, they went back and forth a few times to arrive at that fix, so I suppose this is quite subtle indeed)

So the good news is: this is now fixed upstream and we don't have to opt-in, it'll just work when building against the next release.
The bad news is: we'll have to carry a work-around until this trickles down to the majority of mingw toolchains, which will take several years.

**Comment by theuni** [comment] 2022-05-04 21:15
libsecp256k1 actually has the opposite problem: leaking exported symbols into static libraries.

I've PR'd a fix for that upstream: https://github.com/bitcoin-core/secp256k1/pull/1105

Without that fix, the windows dll links successfully, but exports **_only_** the libsecp symbols due to ld's behavior (emphasis mine):

> 
> --export-all-symbols
>            If given, all global symbols in the objects used to build a DLL will be exported by the DLL.  **Note that this is the default if there otherwise wouldn't be any exported symbols**.

So basically, because libsecp256k1's symbols are exported, nothing else gets exported. By fixing that leak we get back to the default of all exports, which is what we're after (for now).

**Comment by TheCharlatan** [comment] 2023-02-21 09:22
> I believe that https://github.com/theuni/bitcoin/commit/9612f5f0f1e3295065dbd8a0e0f472f8f020bbd9 is the clean/proper fix for us for the issue. We don't want pthreads symbols exported, and that fixes the specific issue.

Also tested this. Has this been PR'ed?

**Comment by theuni** [comment] 2023-02-21 21:54
@TheCharlatan I just rebased and pushed up a branch with a combo for dll's that seems to work.

Mind testing https://github.com/theuni/bitcoin/commits/fix-dll-exports ? I'll PR if it works for you.

Symbol visibility can be tested by marking a random function as dllexport. When dumped with `objdump -p`, you should see _only_ your selected exported symbols.

**Comment by TheCharlatan** [comment] 2023-02-22 12:40
> Mind testing https://github.com/theuni/bitcoin/commits/fix-dll-exports ? I'll PR if it works for you.

Mmh, I'm surprised that secp needs to be linked as well by the final binary and I'm not quite following why. What's different between the visibility of say linking leveldb and linking libsecp in libbitcoinkernel so these symbols end up undefined in the bitcoin-chainstate binary?

**Closed** 2023-02-27 14:41 UTC
