### ISSUE TITLE
test: failure in interface_rest.py

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#26440] opened 2022-11-01 16:51 UTC
https://cirrus-ci.com/task/4924805592907776?logs=functional_tests#L2972
```bash
 test  2022-11-01T13:38:30.771000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 133, in main
                                       self.run_test()
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\interface_rest.py", line 103, in run_test
                                       self.sync_all()
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 715, in sync_all
                                       self.sync_mempools(nodes)
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 708, in sync_mempools
                                       raise AssertionError("Mempool sync timed out after {}s:{}".format(
                                   AssertionError: Mempool sync timed out after 480s:
                                     {'cbd1d27c4d06b4dfd479c34aef4b57d3be14dfc20ccc74f2699fde370f17d1d3'}
                                     set()
 test  2022-11-01T13:38:30.771000Z TestFramework (DEBUG): Closing down network thread 
```

**Comment by brunoerg** [comment] 2022-11-03 12:58
I think this issue is related to `interface_rest.py`, isn't it?

**Comment by aureleoules** [comment] 2022-11-03 13:16
https://cirrus-ci.com/task/6319943846199296
https://cirrus-ci.com/task/5934934255206400

**Comment by mzumsande** [comment] 2022-11-07 16:49
The issue in https://cirrus-ci.com/task/4924805592907776?logs=functional_tests#L2972 seems to be that the nodes aren't connected yet at the time the tx is added (and, therefore, the tx is not propagated and mempool sync fails):
```
 test  2022-11-01T13:30:30.622000Z TestFramework (INFO): Broadcast test transaction and sync nodes
(...)
 node0 2022-11-01T13:30:30.648282Z [C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\src\validationinterface.cpp:211] [operator ()] [validation] TransactionAddedToMempool: txid=cbd1d27c4d06b4dfd479c34aef4b57d3be14dfc20ccc74f2699fde370f17d1d3 wtxid=a0693a39de8466f542ef40b30e3fe1a391b2863927c5a28838ed65a3f3e84177 
(...)
 node0 2022-11-01T13:30:30.704227Z [C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\src\net_processing.cpp:3149] [ProcessMessage] [net] received: verack (0 bytes) peer=0 
```
I don't understand how this is possible, `setup()` should wait for the verack, so that `run_test()` is not called before the two nodes are successfully connected.

**Comment by MarcoFalke** [comment] 2023-01-11 17:03
Closing as presumed duplicate of #26852 (same underlying cause)

**Closed by MarcoFalke** 2023-01-11 17:03 UTC
Labels: Bug
