### ISSUE TITLE
RPC Connection error after upgaring to version 17

### ISSUE THREAD

**Issue by ghanavati27** [bitcoin/bitcoin#14420] opened 2018-10-07 02:04 UTC
I upgraded my bitcoin core to version 17
Now my application can't call methods via RPC commands.
Seems , BitcoinCore does not listen to RPC port.

Error message: "connect ECONNREFUSED 127.0.0.1:8332"
Is any new configuration for RPC in version17

My OS is windows server 2016 

When i downgrade my core to version 16.3 , everything will be fine.

**Comment by MarcoFalke** [comment] 2018-10-08 09:06
Please check your debug.log for possible causes; Alternatively you can upload it here.

You can find the debug.log in your [data dir](https://en.bitcoin.it/wiki/Data_directory#Default_Location).

**Comment by fanquake** [comment] 2018-10-20 13:51
Closing after no followup.

**Closed by fanquake** 2018-10-20 13:51 UTC
Labels: RPC/REST/ZMQ

**Comment by MarcoFalke** [comment] 2018-11-01 14:05
Could be a duplicate of  #14627?
