### ISSUE TITLE
Error during compiling Bitcoin on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by tkaczorro** [bitcoin/bitcoin#11093] opened 2017-08-19 05:56 UTC
Hi,
I am trying to compile Bitcoin Core on Windows Subsystem for Linux and I am stuck at the following step:

cd depends
make HOST=x86_64-w64-mingw32

I got the error message:

: not foundess: 4: ./config.guess:
: not foundess: 6: ./config.guess:
: not foundess: 33: ./config.guess:
: not foundess: 34: ./config.guess:
: not foundess: 36: ./config.guess:
: not foundess: 48: ./config.guess:
: not foundess: 57: ./config.guess:
: not foundess: 60: ./config.guess:
./config.guess: 63: ./config.guess: Syntax error: word unexpected (expecting "in")
: not foundb: 4: ./config.sub:
: not foundb: 6: ./config.sub:
: not foundb: 26: ./config.sub:
: not foundb: 27: ./config.sub:
: not foundb: 34: ./config.sub:
: not foundb: 37: ./config.sub:
: not foundb: 45: ./config.sub:
: not foundb: 52: ./config.sub:
: not foundb: 54: ./config.sub:
: not foundb: 66: ./config.sub:
: not foundb: 74: ./config.sub:
: not foundb: 77: ./config.sub:
./config.sub: 80: ./config.sub: Syntax error: word unexpected (expecting "in")
: not foundess: 4: ./config.guess:
: not foundess: 6: ./config.guess:
: not foundess: 33: ./config.guess:
: not foundess: 34: ./config.guess:
: not foundess: 36: ./config.guess:
: not foundess: 48: ./config.guess:
: not foundess: 57: ./config.guess:
: not foundess: 60: ./config.guess:
./config.guess: 63: ./config.guess: Syntax error: word unexpected (expecting "in")
: not foundb: 4: ./config.sub:
: not foundb: 6: ./config.sub:
: not foundb: 26: ./config.sub:
: not foundb: 27: ./config.sub:
: not foundb: 34: ./config.sub:
: not foundb: 37: ./config.sub:
: not foundb: 45: ./config.sub:
: not foundb: 52: ./config.sub:
: not foundb: 54: ./config.sub:
: not foundb: 66: ./config.sub:
: not foundb: 74: ./config.sub:
: not foundb: 77: ./config.sub:
./config.sub: 80: ./config.sub: Syntax error: word unexpected (expecting "in")
Makefile:72: hosts/.mk: No such file or directory
Makefile:74: builders/.mk: No such file or directory
/bin/sh: 1: Makefile: not found
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Makefile: not found
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Makefile: not found
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Makefile: not found
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Makefile: not found
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Makefile: not found
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Makefile: not found
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Makefile: not found
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Makefile: not found
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Makefile: not found
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Makefile: not found
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Syntax error: "|" unexpected
make: config.site.in: Command not found
/bin/sh: 1: Syntax error: "|" unexpected
make: config.site.in: Command not found
/bin/sh: 1: Syntax error: "|" unexpected
make: *** No rule to make target 'builders/.mk'.  Stop.

I am not a Linux user nor developer so I don't know what this means. I just want to run Bitcoin Core to learn raw Bitcoin protocol. 

Thanks in advance for any help.

### Expected behaviour
Should not return error.

### What version of bitcoin-core are you using?
0.14.2

### Machine specs:
- OS: Windows 10
- CPU: Intel i7-6800K
- RAM: 16 GB
- Disk size: 1 TB
- Disk Type (HD/SDD): SSD

**Comment by fanquake** [comment] 2017-08-19 06:09
Looks like a duplicate of #10269, see that issue for a possible fix.

**Closed by fanquake** 2017-08-19 06:09 UTC
Labels: Windows

**Comment by scubaMaster** [comment] 2017-09-15 07:28
The same error still occurs - #10269 is not really a duplicate, but even with the updated path variable and updated and upgraded apt-get it still generates the errors tkaczorro described (with a download from today). 
What is the suggested fix?

**Comment by LordYikmo** [comment] 2017-09-26 19:18
same here, still got this error

**Comment by jonasschnelli** [comment] 2017-09-28 02:46
Have you followed our guide?
https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md#compiling-with-windows-subsystem-for-linux

**Comment by res-Q** [comment] 2017-09-28 05:12
I am also receiving this error when attempting to compile version 0.15.0. I have followed the guide for compiling with windows subsystem for linux. I have performed the suggested PATH command in https://github.com/bitcoin/bitcoin/pull/10884 - now my path is as follows:

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

**Comment by novatia** [comment] 2017-10-13 08:35
Hi, same problem here.
Resolved removing \r char from each file in the source folder like this.

find ./bitcoin -type f | xargs -Ix sed -i.bak -r 's/\r//g' x

**Comment by rafawo** [comment] 2017-11-20 08:58
I was having this same problem, but got it resolved by re cloning the bitcoin git repository directly from the bash window in the Ubuntu ecosystem.

I originally cloned the repository from within Windows, then read the instructions on **doc/build-windows.cmd** and got stuck in the same step. After trying different approaches, I realized it would be easier to just reclone again from within Ubuntu ecosystem, just in case it had to do with git setting up things differently because of OS file system differences. Like paths or something. Seemed to work for me.

**Comment by mfarnoosh** [comment] 2018-02-04 09:53
Hi, Same problem here,
The problem is because of difference between EOF in Windows and Linux.
do not copy the source from Windows to WSL. clone it in Linux directly from git, or copy the zip file and extract it in Linux.
thanks @novatia

**Comment by leegod** [comment] 2019-04-11 11:21
really hard to  know... I need step by step guide.
