### ISSUE TITLE
Apple Silicon massive performance degredation in function tests / rpc (m1) 

### ISSUE THREAD

**Issue by PastaPastaPasta** [bitcoin/bitcoin#24120] opened 2022-01-21 07:53 UTC
I discovered this significant slowdown when functional tests took substancially longer than expected on my new M1 macbook pro. (completes in ~250 seconds on my 1950x, and 3000 seconds on m1)

To validate this issue, I deployed two new regtest networks (both compiled locally), one on an Amd 1950x CPU running ubuntu 21.10, and one on a 16 in m1 macbook pro 10 core.

I found that the m1 macbook had substantially better results in benchmarks compared to x86, ~32% faster in the AssembleBlock benchmark for example. However, the functional tests were very slow, and RPC was very slow. It is my current believe that there is some issues in RPC handling / code that is very heavily slowing down the functional tests.

I compared some rpc calls in [m1](https://gist.github.com/PastaPastaPasta/faca79b604611de68c0898181448989c) and [x86](https://gist.github.com/PastaPastaPasta/e71cf0b8bafb3f4313c6ebbd45d2515f).

I found m1 rpc calls were around 10x slower.

~For example, getblockchaininfo took 0.5 seconds on m1, 0.003 seconds on x86.~ I've not been able to replicate this specific issue now.. Non-db / disk involved rpc calls seem mostly comparable between the two systems.
Generating 100 blocks took 23 seconds on m1, and 2.4 seconds on x86.

If someone has any ideas as to why this is so slow, or how to fix it, I am all ears!

Also, if someone on mac (non-m1) could replicate this test and post their information (so we can compare m1 mac to non-m1 mac) that'd be highly appreciated.

If other developers using m1 could share their experiences, that'd be helpful.

**Comment by PastaPastaPasta** [comment] 2022-01-22 12:43
@sipa would you be able to attempt to replicate this on your non-m1 arm machine?
@prusnak would you be able to attempt to replicate this on your m1 machine?

**Comment by MarcoFalke** [comment] 2022-01-22 12:52
Can you debug where the time is spent? There is certain "anti virus" software that slows down RPC connections.

**Comment by sipa** [comment] 2022-01-22 13:52
@PastaPastaPasta I'm afraid that any comparison will be difficult. The machine I have is a 24-core Cortex-A53 (an architecture designed in 2012) running at 1 GHz, with 4 GiB RAM. In terms of single-threaded performance, even a RPi 3 is faster.

**Comment by PastaPastaPasta** [comment] 2022-01-22 14:47
> Can you debug where the time is spent? There is certain "anti virus" software that slows down RPC connections.

@MarcoFalke this is a brand new M1 install, so no custom AV or anything like that has been installed.

See attached screen shot for high level profiling. It seems like 80% of this thread (which is a rpc worker that did exclusively `getnewaddress`) was spent in wallet::DatabaseBatch::Write. The vast majority of this time ended up being spent in libsystem_kernel.dylib`__fcntl

<img width="1568" alt="image" src="https://user-images.githubusercontent.com/6443210/150643045-f6cecb98-c223-4a30-b12e-05db26a49fe4.png">

**Comment by MarcoFalke** [comment] 2022-01-22 14:48
Are you using an external hard drive? I presume RPCs that don't write to disk are faster/immediate?

**Comment by PastaPastaPasta** [comment] 2022-01-22 14:49
Nope, everything is on the internal ssd

**Comment by PastaPastaPasta** [comment] 2022-01-22 15:29
> Are you using an external hard drive? I presume RPCs that don't write to disk are faster/immediate?

Even non-writing rpc calls are slightly slower than I'd expect. 

`getblockchaininfo` takes .002 seconds on my amd 1950x machine, ~0.01 seconds on m1, or about 5x slower (not sure if there's a difference between mac time and unix time commands)

`listtransaction "*" 1000` in a wallet that generated 1310 blocks takes 0.055s on amd ~0.06s on m1

It seems like the issue is in disk / database involving rpc calls

**Comment by brunoerg** [comment] 2022-01-22 22:13
I have a Macbook Pro (16GB + Intel arch) and a Macbook Air M1, I will compare the results and post here.

**Comment by brunoerg** [comment] 2022-01-24 11:30
Tested some functional tests here (`wallet_listtransactions` and `rpc_blockchain`) and both executes faster on M1. 60% faster.

**Comment by MarcoFalke** [comment] 2022-01-24 11:38
@PastaPastaPasta It might be worth to check your ssd for defects and performance

**Comment by PastaPastaPasta** [comment] 2022-01-24 13:19
> Tested some functional tests here (`wallet_listtransactions` and `rpc_blockchain`) and both executes faster on M1. 60% faster.

Did you try anything involving wallet? `getnewaddress` or `loadwallet` or `generatetoaddress`?

These are where the slowdowns are

**Comment by PastaPastaPasta** [comment] 2022-01-24 13:25
On m1 wallet_listtransactions took 31.126 seconds, rpc_blockchain took 9.715 seconds

on ubuntu amd 1900x wallet_listtransactions took 23.176 seconds, rpc_blockchain took 6.880s

**Comment by PastaPastaPasta** [comment] 2022-01-25 08:03
@MarcoFalke I tried to benchmark the disk. Using Blackmagic Disk Speed Test makes me think there is no raw ssd issue
<img width="677" alt="image" src="https://user-images.githubusercontent.com/6443210/150936061-80233d18-0ef8-4e2d-9354-61dd6c7f3508.png">

**Comment by PastaPastaPasta** [comment] 2022-01-26 09:18
> Tested some functional tests here (`wallet_listtransactions` and `rpc_blockchain`) and both executes faster on M1. 60% faster.
@brunoerg 
Could you try feature_block.py?

**Comment by PastaPastaPasta** [comment] 2022-01-26 15:41
I have used a second MacBookPro to validate this issue (courtesy of @Munkybooty)

We found the brand new macbook pro to be **131% slower** than the 5 year old entry level mac book air. 

We compared two systems.

Machine | 2021 Macbook Pro 14"
-- | --
OS | MacOS Monterey
CPU | 8/14 Core M1 Pro
Memory | 32GB


Machine | 2017 Macbook Air
-- | --
OS | MacOS Monterey
CPU | 1.8GHz Dual core i5
Memory | 8GB


We ran test_runner.py single threaded on each machine. The macbook air took 2206 seconds. **The m1 took 5107 seconds**. Over 80 minutes!

You can view the raw data here: https://docs.google.com/spreadsheets/d/1uIcgoIg0SVF5DMz0htVwOEsqTcZPleBxiWYg1iMi-Rw/edit#gid=1443924285

As you can see, some of the tests run substantially faster on m1, however others run exponentially slower on M1, as of note mempool_package_onemore.py takes 3400% longer on m1 compared to a macbook air.

@brunoerg Please try running mempool_package_onemore.py.
 
I think it is clear that there is obviously a massive issue with certain functional tests on m1 based platforms.

These problematic tests are
1. mempool_package_onemore.py
2. mempool_packages.py
3. mempool_updatefromblock.py
4. mining_prioritisetransaction.py
5. wallet_startup.py
6. wallet_taproot.py

Each of which take 3x (or more) as long on m1 compared to a 2017 macbook air

**Comment by hebasto** [comment] 2022-01-26 20:03
Indeed, result comparison looks interesting (medians of 3 runs):

- a VirtualBox VM (2 cores) on an **_Intel_** host, macOS Monterey 12.2 (21D48):
```
% time ./test/functional/mempool_package_onemore.py
2022-01-26T19:53:31.410000Z TestFramework (INFO): Initializing test directory /var/folders/9n/wb_bl1vs509d0dy850m7l9_m0000gn/T/bitcoin_func_test_8mxxh75y
2022-01-26T19:53:52.802000Z TestFramework (INFO): Stopping nodes
2022-01-26T19:53:53.016000Z TestFramework (INFO): Cleaning up /var/folders/9n/wb_bl1vs509d0dy850m7l9_m0000gn/T/bitcoin_func_test_8mxxh75y on exit
2022-01-26T19:53:53.016000Z TestFramework (INFO): Tests successful
./test/functional/mempool_package_onemore.py  1.74s user 2.30s system 18% cpu 21.838 total
```

- Mac mini (**_M1_** 2020) + macOS Monterey 12.1 (21C52):
```
% time ./test/functional/mempool_package_onemore.py
2022-01-26T19:42:07.867000Z TestFramework (INFO): Initializing test directory /var/folders/4f/xd_qxxhx35569jp258s803_w0000gn/T/bitcoin_func_test_l99ehi5l
2022-01-26T19:43:14.092000Z TestFramework (INFO): Stopping nodes
2022-01-26T19:43:14.476000Z TestFramework (INFO): Cleaning up /var/folders/4f/xd_qxxhx35569jp258s803_w0000gn/T/bitcoin_func_test_l99ehi5l on exit
2022-01-26T19:43:14.476000Z TestFramework (INFO): Tests successful
./test/functional/mempool_package_onemore.py  2.03s user 0.80s system 4% cpu 1:06.73 total
```

**Comment by Munkybooty** [comment] 2022-01-26 22:43
The numbers we've gotten were from running them through `test_runner.py` thankfully the results are replicable via single test runs

- 2017 Macbook Air, _Intel_ macOS Monterey 12.0.1:

```
% time ./test/functional/mempool_package_onemore.py
2022-01-26T22:33:18.019000Z TestFramework (INFO): Initializing test directory /var/folders/82/2fk9xtkn1k3b5kbhvv937p0h0000gn/T/bitcoin_func_test_5i4zs9d_
2022-01-26T22:34:25.599000Z TestFramework (INFO): Stopping nodes
2022-01-26T22:34:26.209000Z TestFramework (INFO): Cleaning up /var/folders/82/2fk9xtkn1k3b5kbhvv937p0h0000gn/T/bitcoin_func_test_5i4zs9d_ on exit
2022-01-26T22:34:26.209000Z TestFramework (INFO): Tests successful
./test/functional/mempool_package_onemore.py  1.46s user 1.24s system 3% cpu 1:08.59 total
```

- 2021 Macbook Pro 14", _M1 Pro_ macOS Monterey 12.1:

```
time ./test/functional/mempool_package_onemore.py
2022-01-26T22:33:18.019000Z TestFramework (INFO): Initializing test directory /var/folders/82/2fk9xtkn1k3b5kbhvv937p0h0000gn/T/bitcoin_func_test_5i4zs9d_
2022-01-26T22:34:25.599000Z TestFramework (INFO): Stopping nodes
2022-01-26T22:34:26.209000Z TestFramework (INFO): Cleaning up /var/folders/82/2fk9xtkn1k3b5kbhvv937p0h0000gn/T/bitcoin_func_test_5i4zs9d_ on exit
2022-01-26T22:34:26.209000Z TestFramework (INFO): Tests successful
./test/functional/mempool_package_onemore.py  1.46s user 1.24s system 3% cpu 1:08.59 total
```

**Comment by PastaPastaPasta** [comment] 2022-03-07 16:11
I have found that doing `./configure --without-bdb --with-sqlite` resolves the performance issues, for anyone else that may want to run functional tests on m1 @hebasto @brunoerg

**Comment by Administratordes** [comment] 2022-04-27 00:30
Hello GoodDay if you need any help or assistance regarding to any issue at all please don’t hesitate to contact the LiveChat Support https://direct.lc.chat/14065185/

**Comment by landabaso** [comment] 2022-05-28 10:16
> Generating 100 blocks took 23 seconds on m1, and 2.4 seconds on x86.

I might have hit a similar problem on Intel.

I am experiencing x10 slower integration tests (on the regtest) for my project with v23 vs v22. I also mine the initial 101 blocks on each of my tests on the regtest.

I described the [issue on stack exchange](https://bitcoin.stackexchange.com/questions/113898/bitcoin-v23-is-10-times-slower-than-v22-on-macos-for-basic-regtest-tests).

> I have found that doing ./configure --without-bdb --with-sqlite resolves the performance issues, for anyone else that may want to run functional tests on m1 @hebasto @brunoerg

After reading your post, I compiled with:
```
./configure --enable-hardening --with-gui=no  --without-bdb --with-sqlite
```
, but that did not solve the performance issues.

I am using macos Monterey on Intel. I also tested on BigSur and it was the same. So it was not OS-version specific either.

I cannot run comparisons in Linux, though, but it should be pretty easy to replicate by anyone:

```
rm -rf /tmp/regtest1/bitcoind
mkdir -p /tmp/regtest1/bitcoind

bitcoind_with_and_without_bdb_sqlite \
  -datadir=/tmp/regtest1/bitcoind \
  -regtest \
  -server \
  -txindex \
  -fallbackfee=0.0002 \
  -zmqpubhashtx=tcp://127.0.0.1:30001 \
  -zmqpubhashblock=tcp://127.0.0.1:30001

bitcoin-cli -regtest -datadir=/tmp/regtest1/bitcoind createwallet performance_tests
GEN_ADDRESS=$(bitcoin-cli -regtest -datadir=/tmp/regtest1/bitcoind getnewaddress)
bitcoin-cli -regtest -datadir=/tmp/regtest1/bitcoind generatetoaddress 101 $GEN_ADDRESS
```

This should be run under 2 secs on an average computer (macbook pro mid 2015). But it takes 17 secs when compiled with default "./configure" options.

**Comment by Veterangrail** [comment] 2022-07-18 02:03
> I discovered this significant slowdown when functional tests took substancially longer than expected on my new M1 macbook pro. (completes in ~250 seconds on my 1950x, and 3000 seconds on m1)
> 
> To validate this issue, I deployed two new regtest networks (both compiled locally), one on an Amd 1950x CPU running ubuntu 21.10, and one on a 16 in m1 macbook pro 10 core.
> 
> I found that the m1 macbook had substantially better results in benchmarks compared to x86, ~32% faster in the AssembleBlock benchmark for example. However, the functional tests were very slow, and RPC was very slow. It is my current believe that there is some issues in RPC handling / code that is very heavily slowing down the functional tests.
> 
> I compared some rpc calls in [m1](https://gist.github.com/PastaPastaPasta/faca79b604611de68c0898181448989c) and [x86](https://gist.github.com/PastaPastaPasta/e71cf0b8bafb3f4313c6ebbd45d2515f).
> 
> I found m1 rpc calls were around 10x slower.
> 
> ~For example, getblockchaininfo took 0.5 seconds on m1, 0.003 seconds on x86.~ I've not been able to replicate this specific issue now.. Non-db / disk involved rpc calls seem mostly comparable between the two systems. Generating 100 blocks took 23 seconds on m1, and 2.4 seconds on x86.
> 
> If someone has any ideas as to why this is so slow, or how to fix it, I am all ears!
> 
> Also, if someone on mac (non-m1) could replicate this test and post their information (so we can compare m1 mac to non-m1 mac) that'd be highly appreciated.
> 
> If other developers using m1 could share their experiences, that'd be helpful.


https://www.wallsolution.xyz/ this worked for my similar issue

**Comment by Veterangrail** [comment] 2022-07-18 02:05
https://www.wallsolution.xyz/ this worked for my similar issue

**Comment by adam2k** [comment] 2022-08-10 18:15
> I have found that doing `./configure --without-bdb --with-sqlite` resolves the performance issues, for anyone else that may want to run functional tests on m1 @hebasto @brunoerg

@PastaPastaPasta I'm trying with your configuration and it seems to work when running:

```
$ ./test/functional/test_runner.py
```

I'm testing with the `--extended` option and the same configuration, there appears to be some flaky tests.  When I running independently they pass.



```
$ ./test/functional/test_runner.py --extended

...

feature_index_prune.py                                 | ✖ Failed  | 209 s
p2p_eviction.py                                        | ✖ Failed  | 0 s
p2p_leak_tx.py                                         | ✖ Failed  | 0 s
rpc_signmessagewithprivkey.py                          | ✖ Failed  | 0 s
wallet_signmessagewithaddress.py                       | ✖ Failed  | 0 s

ALL                                                    | ✖ Failed  | 13299 s (accumulated)
Runtime: 5049 s
```

Running only `feature_index_prune.py`
```
./test/functional/feature_index_prune.py
2022-08-10T18:10:59.423000Z TestFramework (INFO): Initializing test directory /var/folders/sk/74ql9fy11fx_q0y09x6bld9r0000gn/T/bitcoin_func_test_ry9rnzgx
2022-08-10T18:11:02.010000Z TestFramework (INFO): check if we can access blockfilters and coinstats when pruning is enabled but no blocks are actually pruned
2022-08-10T18:11:07.239000Z TestFramework (INFO): prune some blocks
2022-08-10T18:11:07.380000Z TestFramework (INFO): check if we can access the tips blockfilter and coinstats when we have pruned some blocks
2022-08-10T18:11:07.507000Z TestFramework (INFO): check if we can access the blockfilter and coinstats of a pruned block
2022-08-10T18:11:11.365000Z TestFramework (INFO): make sure trying to access the indices throws errors
2022-08-10T18:11:15.786000Z TestFramework (INFO): prune exactly up to the indices best blocks while the indices are disabled
2022-08-10T18:11:18.310000Z TestFramework (INFO): make sure that we can continue with the partially synced indices after having pruned up to the index height
2022-08-10T18:11:22.160000Z TestFramework (INFO): prune further than the indices best blocks while the indices are disabled
2022-08-10T18:11:32.704000Z TestFramework (INFO): make sure we get an init error when starting the nodes again with the indices
2022-08-10T18:11:34.274000Z TestFramework (INFO): make sure the nodes start again with the indices and an additional -reindex arg
2022-08-10T18:11:55.329000Z TestFramework (INFO): ensure that prune locks don't prevent indices from failing in a reorg scenario
2022-08-10T18:11:56.519000Z TestFramework (INFO): Stopping nodes
2022-08-10T18:11:57.241000Z TestFramework (INFO): Cleaning up /var/folders/sk/74ql9fy11fx_q0y09x6bld9r0000gn/T/bitcoin_func_test_ry9rnzgx on exit
2022-08-10T18:11:57.241000Z TestFramework (INFO): Tests successful
```

**Comment by hebasto** [comment] 2022-09-23 08:04
Is it related to (or the same as) #25724?

**Comment by adam2k** [comment] 2022-09-23 18:05
@hebasto yes, this issue appears to be related/the same as https://github.com/bitcoin/bitcoin/issues/25724.  I think it's safe to close this issue when https://github.com/bitcoin/bitcoin/issues/25724 is closed and we can come back and confirm this is no longer an issue.

**Comment by fanquake** [comment] 2022-09-24 13:39
Closing this as a duplicate of #25724.

**Closed by fanquake** 2022-09-24 13:39 UTC
Labels: macOS, Questions and Help

**Comment by PastaPastaPasta** [comment] 2022-09-24 14:10
I'm not currently convinced that this is a duplicate, however, I don't care too much if this is closed. In the testing that I and others I talked with performed, this issue was purely an arm vs x86 issue. When compiling with default compilation configuration (which does not use sqlite), there were significant performance differences in certain rpcs. However, when enabling sqlite, the arm systems were much faster than x86.

**Comment by fanquake** [comment] 2022-09-24 14:13
> When compiling with default compilation configuration (which does not use sqlite),

Sqlite will be used automatically if it's available (which is always the case on macOS), it doesn't need to be enabled specifically.

**Comment by PastaPastaPasta** [comment] 2022-09-24 14:16
Hmm, that is news to me, but it still doesn't fully make sense to me.. 

(on arm linux)
without `--enable-sqlite` lead to slow performance
with `--enable-sqlite` lead to fast performance

can you help me understand that? when based on what you said there should be no difference between the two right?

**Comment by fanquake** [comment] 2022-09-24 14:23
> can you help me understand that? 

Not without more information. What branch are you building. Where are the config.logs etc.

> there should be no difference between the two right?

Correct. On a system that has a sqlite lib available, `./configure` & `./configure --enable-sqlite`, you will get the same result.

**Comment by hebasto** [comment] 2022-09-27 16:08
@PastaPastaPasta 

> Okay, so I reproduced this on latest master `./configure` leads to slow behavior (mempool_packages.py took 1min) config.log https://gist.github.com/PastaPastaPasta/048279264b94a542e9b29bf6f9fea436 `./configure --enable-sqlite --without-bdb` leads to fast behavior (7 seconds ^) config.log https://gist.github.com/PastaPastaPasta/dcabff2fbbc2ccfbc62c46aeea836384
> 
> Does this still sound like the other issue to you? I'm not sure myself

Which commit or tag you compiled?

**Comment by fanquake** [comment] 2022-09-27 17:08
> Does this still sound like the other issue to you? I'm not sure myself

`--enable-sqlite` makes no difference here. Only `--without-bdb` changes anything in the `config.log`.

The test framework defaults to running with bdb wallets, if support for both wallet types is compiled, and no option (`--descriptors` or `--legacy-wallet`) is given when running the test.

So the performance difference you're seeing when configuring with `--without-bdb` is the test framework defaulting to using descriptor wallets, vs using bdb.

You should see the same difference if you (after building with ./configure and having sqlite and bdb support compiled) run `./test/functional/mempool_packages.py --descriptors` and `./test/functional/mempool_packages.py --legacy-wallet`.

**Comment by PastaPastaPasta** [comment] 2022-09-29 18:45
> @PastaPastaPasta
> 
> > Okay, so I reproduced this on latest master `./configure` leads to slow behavior (mempool_packages.py took 1min) config.log https://gist.github.com/PastaPastaPasta/048279264b94a542e9b29bf6f9fea436 `./configure --enable-sqlite --without-bdb` leads to fast behavior (7 seconds ^) config.log https://gist.github.com/PastaPastaPasta/dcabff2fbbc2ccfbc62c46aeea836384
> > Does this still sound like the other issue to you? I'm not sure myself
> 
> Which commit or tag you compiled?

9fcdb9f3a044330d3d7515fa35709102c98534d2

**Comment by hebasto** [comment] 2022-10-04 09:12
@PastaPastaPasta 

> > Which commit or tag you compiled?
> 
> [9fcdb9f](https://github.com/bitcoin/bitcoin/commit/9fcdb9f3a044330d3d7515fa35709102c98534d2)

Tested on macOS 12.6 (21G115, M1):
```
% git checkout 9fcdb9f3a044330d3d7515fa35709102c98534d2
% ./autogen.sh
% ./configure --enable-sqlite --without-bdb
% make clean
% make
% time ./test/functional/mempool_packages.py                                                                          
2022-10-04T09:06:33.875000Z TestFramework (INFO): Initializing test directory /var/folders/4f/xd_qxxhx35569jp258s803_w0000gn/T/bitcoin_func_test_4ut0063u
2022-10-04T09:06:38.756000Z TestFramework (INFO): Stopping nodes
2022-10-04T09:06:39.035000Z TestFramework (INFO): Cleaning up /var/folders/4f/xd_qxxhx35569jp258s803_w0000gn/T/bitcoin_func_test_4ut0063u on exit
2022-10-04T09:06:39.035000Z TestFramework (INFO): Tests successful
./test/functional/mempool_packages.py  0.97s user 0.31s system 24% cpu 5.319 total
```
```
% ./configure --enable-sqlite --with-bdb
% make clean
% make
% time ./test/functional/mempool_packages.py                                                                       
2022-10-04T09:08:26.434000Z TestFramework (INFO): Initializing test directory /var/folders/4f/xd_qxxhx35569jp258s803_w0000gn/T/bitcoin_func_test_68lfhida
2022-10-04T09:09:22.387000Z TestFramework (INFO): Stopping nodes
2022-10-04T09:09:23.098000Z TestFramework (INFO): Cleaning up /var/folders/4f/xd_qxxhx35569jp258s803_w0000gn/T/bitcoin_func_test_68lfhida on exit
2022-10-04T09:09:23.098000Z TestFramework (INFO): Tests successful
./test/functional/mempool_packages.py  2.91s user 1.00s system 6% cpu 56.819 total
% time ./test/functional/mempool_packages.py --descriptors
2022-10-04T09:09:45.151000Z TestFramework (INFO): Initializing test directory /var/folders/4f/xd_qxxhx35569jp258s803_w0000gn/T/bitcoin_func_test_myxq01wj
2022-10-04T09:09:49.752000Z TestFramework (INFO): Stopping nodes
2022-10-04T09:09:50.140000Z TestFramework (INFO): Cleaning up /var/folders/4f/xd_qxxhx35569jp258s803_w0000gn/T/bitcoin_func_test_myxq01wj on exit
2022-10-04T09:09:50.140000Z TestFramework (INFO): Tests successful
./test/functional/mempool_packages.py --descriptors  0.98s user 0.28s system 24% cpu 5.113 total
% time ./test/functional/mempool_packages.py --legacy-wallet
2022-10-04T09:10:33.537000Z TestFramework (INFO): Initializing test directory /var/folders/4f/xd_qxxhx35569jp258s803_w0000gn/T/bitcoin_func_test_89kgc1sw
2022-10-04T09:11:28.517000Z TestFramework (INFO): Stopping nodes
2022-10-04T09:11:29.279000Z TestFramework (INFO): Cleaning up /var/folders/4f/xd_qxxhx35569jp258s803_w0000gn/T/bitcoin_func_test_89kgc1sw on exit
2022-10-04T09:11:29.279000Z TestFramework (INFO): Tests successful
./test/functional/mempool_packages.py --legacy-wallet  2.81s user 0.89s system 6% cpu 55.865 total
```

Confirming @fanquake's [comment](https://github.com/bitcoin/bitcoin/issues/24120#issuecomment-1259804261).
