### ISSUE TITLE
Error compiling bitcoin core from master branch

### ISSUE THREAD

**Issue by cflrcore** [bitcoin/bitcoin#14570] opened 2018-10-25 13:15 UTC
I just download the zip file of bitcoin core from the master branch. I am getting the following error:

```
wallet/walletutil.cpp: In function ‘std::vector<boost::filesystem::path> ListWalletDir()’:
wallet/walletutil.cpp:57:78: error: ‘end’ was not declared in this scope
     for (auto it = fs::recursive_directory_iterator(wallet_dir); it != end(it); ++it) {
                                                                              ^
wallet/walletutil.cpp:57:78: note: suggested alternative:
In file included from /usr/include/c++/4.9/bits/basic_string.h:42:0,
                 from /usr/include/c++/4.9/string:52,
                 from ./fs.h:9,
                 from ./wallet/walletutil.h:8,
                 from wallet/walletutil.cpp:5:
/usr/include/c++/4.9/initializer_list:99:5: note:   ‘std::end’
     end(initializer_list<_Tp> __ils) noexcept
     ^
wallet/walletutil.cpp:60:32: error: ‘relative’ is not a member of ‘fs’
             paths.emplace_back(fs::relative(it->path(), wallet_dir));
                                ^
wallet/walletutil.cpp:71:36: error: ‘relative’ is not a member of ‘fs’
                 paths.emplace_back(fs::relative(it->path(), wallet_dir));
                                    ^
Makefile:6898: recipe for target 'wallet/libbitcoin_wallet_a-walletutil.o' failed
make[2]: *** [wallet/libbitcoin_wallet_a-walletutil.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/df/bitcoin/src'
Makefile:10236: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/df/bitcoin/src'
Makefile:762: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

```
I am compiling it on Debian Jessie using gcc 4.9 and boost 1.58. Any hints please.

**Comment by fanquake** [comment] 2018-10-25 13:17
Duplicate of https://github.com/bitcoin/bitcoin/issues/14535, see that issue for the PR which should fix your problem.

**Comment by fanquake** [comment] 2018-10-25 13:18
For reference that fix is now in https://github.com/bitcoin/bitcoin/pull/14561.

**Closed by fanquake** 2018-10-25 13:17 UTC
