### ISSUE TITLE
Issue compiling v0.11.0 on Windows

### ISSUE THREAD

**Issue by ptschip** [bitcoin/bitcoin#6458] opened 2015-07-18 17:24 UTC
The configure script wouldn't finish when trying to run in mingw32.   I'm running on Windows 7, 64 bit but compiling a 32 bit v0.11.0.

Was finally able to configure and run make successfully by doing the following.   

Added the following back into the v0.11.0  "configure.ac" script:  
      
       m4_include([pkg.m4])

put the above line just before

      dnl pkg-config check.
      PKG_PROG_PKG_CONFIG

and then copied the "pkg.m4" macro, from v0.10.2, back into the /c/bitcoin folder of v0.11.0.

compiling works fine with this workaround

**Comment by ptschip** [comment] 2015-07-18 17:28
oops sorry about the formatting, the bold lettering was unintentional, those lines should have had a "pound" sign in front of them but they seem to have been interpreted differently.  The main line there is 

m4_include([pkg.m4])   

which should be added to the configure.ac script.

**Comment by ptschip** [comment] 2015-07-19 13:07
Seems to be a problem with "pkg-config".  Seems to be a few people out there complaining about issues compiling 32 bit apps with pkg-config.  I have it installed correctly and can find it in the PATH but I still can't get it to compile v0.11.0 without the above workaround.

**Comment by laanwj** [comment] 2015-07-21 09:54
Looks like a duplicate of #6432, although more information in this one.

**Comment by theuni** [comment] 2015-07-22 22:28
yea, the issue here is the unchecked usage of pkg-config in the qt macros. I'll fix it up.

**Comment by lamar8** [comment] 2015-07-27 05:53
I got the same problem while compling 0.11.0 on windows 7:
...
checking QtDBus presence... no
checking for QtDBus... no
./configure: line 21363: syntax error near unexpected token `QTPLATFORM,'
./configure: line 21363: `        PKG_CHECK_MODULES(QTPLATFORM, Qt5PlatformSuppo
rt, QT_LIBS="$QTPLATFORM_LIBS $QT_LIBS")'

can anyone help me ,thanks very much!

**Comment by ptschip** [comment] 2015-07-27 12:22
just follow the instructions in the bug report

Add the following back into the v0.11.0 "configure.ac" script:

|    m4_include([pkg.m4])
|

put the above line just before

|   dnl pkg-config check.
   PKG_PROG_PKG_CONFIG
|

and then copied the "pkg.m4" macro, from v0.10.2, back into the 
/c/bitcoin folder of v0.11.0.

compiling works fine with this workaround


I got the same problem while compling 0.11.0 on windows 7:

**Comment by laanwj** [comment] 2016-04-28 11:16
Should be  fixed by #6501

**Closed by laanwj** 2016-04-28 11:16 UTC
Labels: Build system, Windows
