### ISSUE TITLE
Regression introduced today with p2p_filter.py?

### ISSUE THREAD

**Issue by jonatack** [bitcoin/bitcoin#18711] opened 2020-04-20 16:58 UTC
in #18544 it seems:
```
TestFramework (INFO): Check that sending "filteradd" if no filter is set is treated as misbehavior (+100)
TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/travis/build/jonatack/bitcoin/build/bitcoin-s390x-linux-gnu/test/functional/test_framework/test_framework.py", line 112, in main
    self.run_test()
  File "/home/travis/build/jonatack/bitcoin/build/bitcoin-s390x-linux-gnu/test/functional/p2p_filter.py", line 120, in run_test
    assert_equal(self.nodes[0].getpeerinfo()[0]['banscore'], 0)
  File "/home/travis/build/jonatack/bitcoin/build/bitcoin-s390x-linux-gnu/test/functional/test_framework/util.py", line 46, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(100 == 0)
```

**Comment by jonatack** [comment] 2020-04-20 16:58
Seeing this in the travis ci builds.

**Comment by jonatack** [comment] 2020-04-20 17:00
Seeing this in the travis ci builds; pinging @theStack.

**Comment by jonatack** [comment] 2020-04-20 17:02
See https://travis-ci.org/github/bitcoin/bitcoin/jobs/677193293#L3665

**Comment by theStack** [comment] 2020-04-20 17:15
Yes, I can confirm that it fails on master -- that was apparently introduced through merging of #18544. The problem is that the "misbehaviour" check in #18544 uses the method of checking banscore via `getpeerinfo()` and assumes a banscore of 0 near the end of the test:
https://github.com/bitcoin/bitcoin/blob/56d2ff8a8fc52676a22163f804a9f1a5415b4b71/test/functional/p2p_filter.py#L120-L122
while another commit merged in-between introduced misbehaviour before, increasing the banscore:
https://github.com/bitcoin/bitcoin/blob/56d2ff8a8fc52676a22163f804a9f1a5415b4b71/test/functional/p2p_filter.py#L68-L70

PR #18672 includes a fix for the problem, by simply also using `assert_debug_log` for detecting misbehaviour.

**Comment by brakmic** [comment] 2020-04-21 10:07
Same problem with my PR: https://travis-ci.org/github/bitcoin/bitcoin/builds/677464990

Thanks for fixing it, @theStack

**Closed** 2020-04-21 11:28 UTC
Labels: Bug
