### ISSUE TITLE
Change handling of "h" versus "'" marker for hardened derivation in descriptors

### ISSUE THREAD

**Issue by gwillen** [bitcoin/bitcoin#15740] opened 2019-04-03 23:16 UTC
Per some discussion in #bitcoin-core-dev -- getdescriptorinfo should probably not canonicalize the descriptor given, but return it exactly as provided. This is because it is the easiest way to get a checksum for a descriptor written by hand, and it's profoundly annoying that there's no way to get a checksum for a non-canonical descriptor right now (one containing the "h" marker for hardened, or containing a private key.)

Also discussed was the possibility of switching the default marker from "'" to "h". The apostrophe is very annoying to work with over RPC because of quoting problems, which is why "h" is accepted. Better to just use "h" everywhere for the same reason.

**Comment by myveryown** [comment] 2019-05-06 17:15
HWI supplies descriptors that include the non-canonical descriptor with the h for hardened and are converted when ran through getdescriptorinfo

It would be nice if getdescriptorinfo would not change what is provided to it and provides a checksum for what was the input

**Comment by harding** [comment] 2019-05-06 17:57
I was working with @myveryown earlier today on debugging a difficulty using descriptors and I found it very unintuitive that this command returns not just an obvious checksum (which is appreciated) but also converts `h` to `'` in origin info in a way that's not immediately obvious:

```bash
$ bitcoin-cli getdescriptorinfo "wpkh([f6bb4c63/0h/0h/30h]028429a37c3f09c8c5cc1fab58df32d1a7da7616c748a40eeb1aae1d64acb9c5cc)" | jq -r .descriptor
wpkh([f6bb4c63/0'/0'/30']028429a37c3f09c8c5cc1fab58df32d1a7da7616c748a40eeb1aae1d64acb9c5cc)#5wdxpxcx
```

It wasn't until @gwillen pointed out this substitution of `h` with `'` that I realized what was going wrong with my attempts to troubleshoot @myveryown's problem.  I'm in agreement with the OP on both points:

1. getdescriptorinfo should provide a way to get the checksum for a non-canonical descriptor
2. Paths using hardened derivation should preferentially be indicated by an `h` rather than a `'`

I think the output should probably look something like this:

```text
$ bitcoin-cli getdescriptorinfo "wpkh([f6bb4c63/0h/0h/30h]028429a37c3f09c8c5cc1fab58df32d1a7da7616c748a40eeb1aae1d64acb9c5cc)"
{
  "descriptor": "wpkh([f6bb4c63/0h/0h/30h]028429a37c3f09c8c5cc1fab58df32d1a7da7616c748a40eeb1aae1d64acb9c5cc)#vk9vfu0h"
  "normalized": "wpkh([f6bb4c63/0'/0'/30']028429a37c3f09c8c5cc1fab58df32d1a7da7616c748a40eeb1aae1d64acb9c5cc)#5wdxpxcx",
  "isrange": false,
  "issolvable": true,
  "hasprivatekeys": false
}
```

(Instead of "canonical", I use "normalized" because it has the same number of letters as "descriptor" and so aligns well in fixed-width displays.  Also canonical seems more ambiguous than normalized in this context.)

**Comment by gwillen** [comment] 2019-05-06 18:26
I'm going to take a crack at this today -- I'm going to both switch the default marker to "h", and have getaddressinfo return the same descriptor provided, rather than alter it. Then people can bikeshed the result. ;-)

**Comment by Sjors** [comment] 2019-05-07 10:17
Concept ACK on making descriptor checksum based on `h` or `'` given by the user, rather than canonical form. But let's add an error for mixed usage.

I don't think the `normalized` field is useful.

I'm fine with switching the default to `h`. In addition to RPC usage, it's probably also less susceptible to graphical operating systems messing with quote marks.

I'm on the fence regarding private keys. At least our RPC should not echo private keys, so it would have to return the checksum without the rest of the descriptor. There could be a separate checksum_private return field for this case.

Can you update the PR description to say `getdescriptorinfo` instead of `getaddressinfo` (assuming that's what you meant)?

**Comment by gwillen** [comment] 2019-05-07 20:35
Sorry yes, that is what I meant, fixed.

**Comment by gwillen** [comment] 2019-05-08 01:45
Ok, it seems like changing the default character from "'" to "h" is a one-line change, whereas preserving the user's original usage BUT still stripping private keys is going to be a hugely-invasive change to descriptor parsing (since we parse and deparse completely in order to print right now, and do not track which spelling was used), and giving a sensible error message for mixed usage is a different hugely-invasive change (since we do not currently have any way of returning error codes from parsing, so they would have to be added.)

So I'm going to PR the one-line change as "hopefully the best use of time right now", since I'm not aware of anybody clamoring to use "'" instead of "h", and everyone seems to prefer the opposite.

**Comment by sipa** [comment] 2019-05-08 02:08
The original reason to make ' the default was because of consistency with decodepsbt (which uses the ' in derivation paths).

It's not too hard to make the parsing/serializing just roundtrip what was provided, if that's desirable.

**Comment by gwillen** [comment] 2019-05-08 03:00
Hmm, can we get away with changing decodepsbt also? Otherwise we end up with two inconsistent "canonical" forms, which isn't great either.

**Comment by Sjors** [comment] 2019-05-08 15:01
Paging PSBT-guy: @achow101

**Comment by achow101** [comment] 2019-05-08 17:46
> Hmm, can we get away with changing decodepsbt also?

Yes.

IMO we should change this everywhere, including its use in wallet metadata (but that may not be possible/necessary). The only reason `'` was being used was because that was the the derivation path that the wallet stored for each key. However since derivation paths are now stored as integer values, it should be fine and safe to change everywhere it is displayed to use `h`. Note that we still may need to have the wallet continue to write out `'` in the derivation path string in `CKeyMetaData` for backwards compatibility reasons, but that string shouldn't be displayed anymore so it doesn't really matter.

**Comment by gwillen** [comment] 2019-05-08 21:29
I would be in favor of changing the default to "h" everywhere (pieter's PR, which I just linked, doesn't change the default but only makes it possible to get the original descriptor echoed back unmodified with checksum.)

Note that the easiest way to change the default in getdescriptorinfo requires changing it in bip32.cpp in FormatHDKeypath, which (if I'm not mistaken) also changes it in CKeyMetaData. But as long as ParseHDKeypath is changed to accept both, there's no back-compat issue, so I don't expect it should be a problem. I'm happy to continue with that PR if people are comfortable with that.

**Comment by achow101** [comment] 2019-05-08 22:41
> which (if I'm not mistaken) also changes it in CKeyMetaData.

Only for imported keys.

I don't think there's actually a backwards compatibility issue since it's just a string that's only used to be displayed to users.

> I'm happy to continue with that PR if people are comfortable with that.

ACK.

Also, there's a redundant `WriteHDKeypath` function in `rpc/rawtransaction.cpp` which can be removed and the thing that uses it can use the `WriteHDKeypath` in `utils/bip32.cpp`.

**Comment by gwillen** [comment] 2020-09-09 18:12
I guess I let this drop after we started echoing the checksum for the original version, without going all the way to switching the default to "h"?

The user ghost43 on IRC just hit a shell-quoting issue related to this, reported in ##hwi on Freenode: https://gist.github.com/SomberNight/8d7b065e74449a8716da9a98cac3cae2

If you wrap the descriptor in single-quotes in the shell, and it happens to have an even number of ' in it (and the contents of the descriptor happens to not actually need quoting), the shell will just silently remove them as valid-but-useless quotes. This transforms the descriptor into one with public derivation everywhere, which is scary.

So I guess this should be a vote in favor of reviving the idea to just force everything to be 'h' instead of ' by default.

**Comment by harding** [comment] 2020-09-20 16:10
I would very much prefer to have `h` everywhere by default.  I don't work with descriptors often, but dealing with the quoting issues annoys me every time.

**Comment by sipa** [comment] 2020-09-20 16:55
No strong opinion here. Descriptors can also contain `[` and `]`. Can't those pose problems in shells as well?

**Comment by harding** [comment] 2020-09-20 17:48
@sipa certainly `[]()/*'` all have special meaning in bash, but only one of them can't be made literal by encapsulating it in single quotes and can't even be escaped by simply prefixing it with a backslash within single quotes.

The challenge I often have is that I need to use one set of quotes to escape a string from the shell and a different set of quotes to indicate a string to the JSON parser; this is most easily done using double quotes for one string and single quotes for the other string, e.g. I want to do something like this:

    bitcoin-cli scantxoutset start '[{"desc": "pkh([d34db33f/44'/0'/0']xpub6ERApfZwUNrhLCkDtcHTcxd75RbzS1ed54G1LkBUHQVHQKqhMkhgbmJbZRkrgZw4koxb5JaHWkY4ALHY2grBGRjaDMzQLcgJvLJuZZvRcEL/1/*)"}]'

But instead I have to add three escape characters per single quote in the BIP32 path:

    bitcoin-cli scantxoutset start '[{"desc": "pkh([d34db33f/44'\''/0'\''/0'\'']xpub6ERApfZwUNrhLCkDtcHTcxd75RbzS1ed54G1LkBUHQVHQKqhMkhgbmJbZRkrgZw4koxb5JaHWkY4ALHY2grBGRjaDMzQLcgJvLJuZZvRcEL/1/*)"}]'

The extra effort is annoying, but I think it's also a challenging problem for users who are less experienced at the shell.  If you run the first command above, the error you get is:

    bash: syntax error near unexpected token `)'

That's not very useful to an inexperienced user---they may think they need to escape the parens at the end of the string rather than noticing the problem with the single quotes near the beginning of the string.  And, as @gwillen noted, it's easy for a user to get the escaping wrong and not notice the shell submitted a different descriptor than they expected, e.g.:

    $ set -x
    $ bitcoin-cli scantxoutset start '[{"desc": "pkh([d34db33f/44'/0'/0]xpub6ERApfZwUNrhLCkDtcHTcxd75RbzS1ed54G1LkBUHQVHQKqhMkhgbmJbZRkrgZw4koxb5JaHWkY4ALHY2grBGRjaDMzQLcgJvLJuZZvRcEL/1/*)"}]'
    + bitcoin-cli scantxoutset start '[{"desc": "pkh([d34db33f/44/0/0]xpub6ERApfZwUNrhLCkDtcHTcxd75RbzS1ed54G1LkBUHQVHQKqhMkhgbmJbZRkrgZw4koxb5JaHWkY4ALHY2grBGRjaDMzQLcgJvLJuZZvRcEL/1/*)"}]'

I think users are a lot less likely to encounter problems with the other special characters, since those characters will probably be escaped normally and so interpreted literally.

**Comment by sipa** [comment] 2020-09-20 18:03
@harding Yeah, that sounds reasonable.

**Comment by 6102bitcoin** [comment] 2020-11-17 20:03
As an inexperienced user I just came up against this issue. 

Is there a way to force the use of h? 

_Background

My wallet provided me with a descriptor (including checksum) using h in indicate hardened address derivation (rather than '). 

When I compared this to the descriptor I built (using bitcoin-cli getdescriptorinfo) I noticed that the checksums did not match, and that regardless of whether I set the hardened path with ' or h in my code, getdescriptorinfo is always sanitised this to '._

**Comment by gwillen** [comment] 2020-11-17 20:13
@6102bitcoin I believe that, when you run getdescriptorinfo, it should now show you TWO checksums -- one corresponding to the exact descriptor you provided, and one as part of the "sanitized" version with the ' characters. Does that seem to be the case?

**Comment by 6102bitcoin** [comment] 2020-11-17 21:32
Ah yes that is the case. (perhaps) confusingly the checksum provided in the checksum field does not match that at the end of the end of the descriptor field.

bitcoin-cli getdescriptorinfo "wpkh([fingerprint/84h/0h/0h]xpub/0/*)"
{
  "descriptor": "wpkh([fingerprint/84'/0'/0']xpub/0/*)#**checksum1**",
  "checksum": "**checksum2**",
  "isrange": true,
  "issolvable": true,
  "hasprivatekeys": false
}

**Comment by 6102bitcoin** [comment] 2020-11-18 07:41
On further reading of the [pull](https://github.com/bitcoin/bitcoin/pull/15986) linked above this appears to be the expected behaviour.

**Comment by gwillen** [comment] 2020-11-24 23:19
I took a quick look at what it would take to change the default from `'` to `h`. (Considering in particular whether it makes more sense to try to change it only at the interface, or also internally.) Here's what I found:

* 10 functional tests (plus `psbt_wallet_tests.cpp`) have `'` hardcoded in various places that I could find. (Generally found by grepping for roughly `44'|49'|84'|/0'|/1'`). The functional tests would need to be changed no matter what, insofar as they are parsing RPC output and looking for `'` and not `h`.
* In `descriptor.cpp`:
  * `BIP32PubkeyProvider::ToString` and `::ToPrivateString` emit `'`.
  * `ParseKeyPath` accepts either `'` or `h`, so that's no problem. 
* In `bip32.cpp`:
  * `FormatHDKeypath emits `'`.
  * `ParseHDKeypath` does a string search for `'`. I think this would be safe to change to 'h' because it only operates on path components, which otherwise are purely numeric (and it checks this.)
* In `scriptpubkeyman.cpp`:
  * `LegacyScriptPubKeyMan::DeriveNewChildKey` and `DescriptorScriptPubKeyMan::SetupDescriptorGeneration` both have a bunch of hardcoded keypath fragments with apostrophes in them.
* In `descriptor_tests.cpp`:
  * There is a function `UseHInsteadOfApostrophe` which is used to turn descriptors with `'` into descriptors with `h` to ensure that both formats are tested. Since that direction is easily done with a character substitution, but the reverse is not, it would seem necessary to keep these testcases formatted with an apostrophe to easily test parsing of both styles.

I get the impression that internally, descriptors are stored at least sometimes as strings with `'`, and `ParseHDKeyPath` is used for parsing these (and only accepts `'`, never 'h'). However, it seems that (outside of tests), this is only used:
* When the key origin (with pre-parsed path) is missing (`walletdb.cpp:463`); or
* When upgrading a wallet without the flag `WALLET_FLAG_KEY_ORIGIN_METADATA` (`scriptpubkeyman.cpp:392`).

So I assume a newly-created wallet will store a non-string key origin, and this codepath will not be used. All other parsing of keypaths appears(?) to go through `descriptor.cpp`'s `ParseKeyPath` function, which accepts both.

So with all that out of the way:

* Which of these functions are used for stuff we get from / write to the walletdb, and which for RPCs and other UI uses? Is it strictly split between `bip32.cpp` for the former, and everything else is the latter?
* Is it okay to just let `ParseHDKeyPath` accept both formats, or is this undesirable?
* Is it okay for descriptors stored in the wallet to switch from `'` to `h` going forward? Does this break compatibility in a way that requires some kind of flag or version bump? (I'm not super familiar with wallet versioning stuff, but keep in mind that the wallet -- at least the CURRENT wallet -- does not ever parse this unless the key origin metadata is missing. If it is the case that NO version of Core (which is willing to read a modern wallet file) will do so, then this may be compatible.)
* Have I gone too far, and should I just be looking at doing this for descriptors that are presented to the user (e.g. via RPC)? This is tricky because `'` and `h` give different checksums, so this change has to happen before the checksum is added. (Are descriptors in the wallet stored with checksums, or without?)

**Comment by Sjors** [comment] 2022-09-13 08:26
It's been a few years, and the use of `'` instead `h` has been consistently driving me nuts, e.g. when trying to import something from `listdescriptors` with `importdescriptors` or test the new scanblocks RPC in #23549.

**Comment by pinheadmz** [comment] 2023-05-17 13:58
Closing as completed by #26076

**Closed by pinheadmz** 2023-05-17 13:58 UTC
Labels: RPC/REST/ZMQ
