### ISSUE TITLE
[Qt] built-in message texts untranslated in gitian build

### ISSUE THREAD

**Issue by Diapolo** [bitcoin/bitcoin#1137] opened 2012-04-22 15:15 UTC
Currently the buttons like QMessageBox::Abort or QMessageBox::Cancel are english and are untranslatable, this should be changed for a even better UX.

I only found this one: http://www.qtcentre.org/threads/10210-how-to-use-tr%28%29-for-QMessageBox
Is there any possibility to do this globally?

Edit @laanwj: clarified title, title was "untranslated Qt message box button texts (not displayed in selected language)"

**Comment by Leviathn** [comment] 2017-09-05 14:54
@diapolo is this still an issue with .14+?

**Comment by MarcoFalke** [comment] 2017-09-05 17:54
I can't remember this was fixed. One could try with the nightly gitian builds: https://bitcoin.jonasschnelli.ch/?show=nightly#nighly

**Comment by Sjors** [comment] 2018-01-15 18:00
I don't need Gitian builds to reproduce. Simply compiling master does the trick for me on OSX with Dutch as system language and wallet set to Dutch. The Send confirmation dialog is a funny example:

![ja1](https://user-images.githubusercontent.com/10217/34955204-4e411656-fa1b-11e7-85f5-103dfea78b35.png)

![schermafbeelding 2018-01-15 om 17 37 43](https://user-images.githubusercontent.com/10217/34955077-d2fd6648-fa1a-11e7-8278-f97c8ac30b9d.png)

Although both buttons start out as `QMessageBox::...` the YES button is overwritten by the code later with a translated string.

![schermafbeelding 2018-01-15 om 17 40 21](https://user-images.githubusercontent.com/10217/34955191-3ee47392-fa1b-11e7-9aa1-4d7e436d1f57.png)

![yes](https://user-images.githubusercontent.com/10217/34955159-20263904-fa1b-11e7-9fff-97b9cacd4299.png)

We could just replace all occurrences of `QMessageBox::...` with a translatable string, but that seems like a hack.

IMO the system buttons should use the language selected by the user, not the OS language. Otherwise it looks weird if a user switches the wallet to some other language (e.g. I prefer the English version).

**Comment by thijstriemstra** [comment] 2018-01-31 17:36
Here's a pull request that deals with the same issue: https://github.com/keepassxreboot/keepassxc/pull/1307. Looks like the solution is to 'bundle qtbase translations with builds'.

**Comment by MarcoFalke** [comment] 2020-04-29 17:24
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.

**Closed by MarcoFalke** 2020-04-29 17:24 UTC
Labels: GUI
