### ISSUE TITLE
debug option to control flushing (lax/normal/agressive)

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#8021] opened 2016-05-08 03:18 UTC
Arguably, there's a rationale, perhaps optionally so, for flushing to disk more aggressively on regtest. Otherwise, we're losing state between, say, debug sessions, at least after an ungraceful exit. Must this be so?

**Comment by jonasschnelli** [comment] 2016-05-08 19:54
The regtest FlushStateToDisk() is currently not optimized because no-one has tried to accomplish this (IIRC). I agree that it would sometimes be nice to have the wallet and the blocks/index in the same state after a ungraceful shutdown.

**Comment by laanwj** [comment] 2016-05-09 06:56
regtest is used for the regression (qa) tests, where performance does matter, and persistence doesn't matter at all (data is discarded anyway). So I don't think this is a good idea, as-is. 

However I think a debug option to control flushing (lax/normal/agressive) could be useful, independent of the chain used.

**Comment by 21E14** [comment] 2016-05-09 12:34
Agreed. No reason to single out regtest.

**Comment by MarcoFalke** [comment] 2020-04-26 21:01
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.

**Closed by MarcoFalke** 2020-04-26 21:01 UTC
Labels: Brainstorming, UTXO Db and Indexes
