### ISSUE TITLE
gui: MacOS Spotlight doesn't show as 'Bitcoin Core'

### ISSUE THREAD

**Issue by dannmat** [bitcoin/bitcoin#17201] opened 2019-10-20 16:34 UTC
**Expected Behaviour**
When searching for 'Bitcoin Core' on MacOS Spotlight, it should show as 'Bitcoin Core'. 'Bitcoin Core' is the name of the executable in the directory and under Applications, so this should replicate through search.

**Actual Behaviour**
Searching for 'Bitcoin Core' on MacOS spotlight shows as 'Bitcoin-QT', which may be confusing to users and could cause concern for a fraudulent application.

Here is a screenshot showing the wrong name: 
![Bitcoin-Qt](https://user-images.githubusercontent.com/9567098/67162766-54b37300-f35f-11e9-9f3e-f402d06a0221.png)

**System information**
MacBook Pro (Retina, 15-inch, Mid 2015)
2.2 GHz Quad-Core Intel Core i7
16 GB 1600 MHz DDR3
macOS Catalina 10.15 Beta

I'm running a self-compiled version, running master as of 20/10/2019.

**Comment by dannmat** [comment] 2019-10-20 16:41
I've [read](https://apple.stackexchange.com/questions/65036/why-do-some-app-spotlight-results-show-the-app-extension-but-not-all) that MacOS uses the `CFBundleName` and `CFBundleDisplayName` when searching applications.

https://github.com/bitcoin/bitcoin/blob/b8f041af2d2c89afdc14f8c632dfb7fecb535cb5/share/qt/Info.plist.in#L34-L35

As you can see here, this is listed as Bitcoin-Qt.

Is this something we can change? Or is anything relying on this?

**Comment by fanquake** [comment] 2019-10-20 16:59
This is a duplicate of #6463.

**Closed by fanquake** 2019-10-20 16:59 UTC
Labels: Bug, macOS
