### ISSUE TITLE
Why was the 'getinfo' command removed?

### ISSUE THREAD

**Issue by ilsawa** [bitcoin/bitcoin#11671] opened 2017-11-12 17:15 UTC
It seems some bright spark has decided that getinfo command is not needed in new versions of the daemons, and removed it.
Now you need one command to see the amount of blocks, another one to see the amount of connections, and one more to see the balance.
But now there are:
getblockchaininfo
getmempoolinfo
gettxoutsetinfo
getmemoryinfo ("mode")
getmininginfo
getaddednodeinfo ( "node" )
getnetworkinfo
getpeerinfo
getwalletinfo
which individually do not provide general information.
Thank you developers. Remove this command in your own wallets. But take getinfo back to me, leave the possibility to compile with this command.

I do not understand the meaning of your innovation if it deprives the user of convenience.

**Comment by cedenday** [comment] 2017-11-12 21:35
Write a SH script that runs the "get*info" commands and formats the results however you like.

At some point there was talk about including something like that in `bitcoin-cli`, but I'm not sure what happened to it.

**Comment by luke-jr** [comment] 2017-11-12 21:36
`bitcoin-cli -getinfo` will be in 0.16. You can get it early in [Knots](http://bitcoinknots.org/).

**Comment by fanquake** [comment] 2017-11-13 07:34
Duplicate of #11382. See discussion in #8780 and #10871.

**Closed by fanquake** 2017-11-13 07:34 UTC

**Comment by Crypto2** [comment] 2017-12-25 02:07
tbh it should be left in just for reasons of compatibility with other coins so providers don't have to write extra code when supporting multiple Bitcoin-based coins. Even though it isn't a position Bitcoin may want being the 1st it kind of sets a core amount of basic functions that all Bitcoin RPC-compatible coins should have and getinfo is a major one of of those. Plus it isn't a large function and making 1 RPC call instead of 2-3 is always preferred.

**Comment by kangasbros** [comment] 2018-01-31 12:25
I think also that getinfo should be preserved. It can be a parent call which collects the information using the new calls. There is lots of code around using this command and removing it makes lots of peoples lives worse.

**Comment by jnewbery** [comment] 2018-01-31 14:31
@kangasbros, you've already made your opinion known in #11382 . This has been discussed multiple times in multiple venues.

Fundamentally, getinfo requires information from multiple subsystems. The implementation is messy, and the locks all over the place make it difficult and expensive to maintain. Keeping it would mean we can't do refactors to clean up wallet and rpc code, burdening the project with long-term technical debt.

Bitcoin Core is an open source project. You are completely free to fork the code and do the work necessary to maintain this code. Complaining that other people aren't doing that work for you achieves nothing.
