### ISSUE TITLE
[Windows] GUI window can still appear off screen.

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#11207] opened 2017-08-31 19:35 UTC
The GUI does not appear on windows if the last position of the window is off screen, as would be with multiple monitors and then subsequently disconnecting one monitor. I believe this is related to #7869 and #11171. It seems that e9ff818b69c2f8ce4a151d1a81a3e22a4319c93d did not fix this problem.

This is easy to replicate; open regedit.exe (windows registry editor), find the registry keys in `HKEY_CURRENT_USER\Software\Bitcoin\Bitcoin-Qt`. Edit the `nWindowPos` entry to be a point that is off screen. The next start of Bitcoin Core will result in the window being off screen and there is no way to get it back without doing `-resetguisettings`

**Comment by achow101** [comment] 2017-08-31 23:08
According to the discussion in #11171, it seems that the problem there was not an off screen issue but a memory access violation. So any fixes for an off screen issue (#11208) may not fix that problem.

**Comment by AllanDoensen** [comment] 2017-09-01 11:01
try the fix in #10156

**Comment by MarcoFalke** [comment] 2017-09-01 11:14
@AllanDoensen The fix you mentioned is already merged via https://github.com/bitcoin/bitcoin/commit/51833a17347fdc3615afb693e4ff8d347fc2eda2

**Comment by jonasschnelli** [comment] 2017-09-03 17:18
Agree that we should fix this.
I assume it's a simple one to fix.
Similar to https://github.com/bitcoin/bitcoin/commit/51833a17347fdc3615afb693e4ff8d347fc2eda2, we need to check if the upper left corner of the GUI window is outside of the current, displayed screen bounds (maybe with some 20px padding). If the window is outside the bounds, relocate it to the default position (centre on screen 0).

**Comment by mb300sd** [comment] 2017-09-04 16:43
Fixed in BTC, but a trick for this is to select the window from the task bar, and then hit Alt+Space. Then use the keyboard to select Move. Then the window will stick to your mouse pointer.

**Comment by jonasschnelli** [comment] 2017-09-05 21:26
I just tried to reproduce this issue on Windows 8.1 by manipulating the window position with RedEdit. Could not reproduce with 0.15.0rc2 gitian build (moved the window pos to >x2000,y2000 and the window relocated correctly at the right bottom border).

Could it be that this is a QT issue?
@achow101: did you use a self-compiled Bitcoin-Qt? Can you reproduce it with the "official" 0.15.0rcs?

**Comment by achow101** [comment] 2017-09-05 21:44
@jonasschnelli Hmm. I think I may have been using either an older version or a custom build. Testing with 0.15.0rc3 doesn't seem to be having this problem for me.

**Comment by jonasschnelli** [comment] 2017-09-05 21:45
Tested also on Window 7 and Windows 10.
has the issue with 0.14.0, ... though I could not reproduce this issue in 0.15.0rc2.
Either we have fixed this already in our codebase or the upgrade of our dependencies to Qt5.7 did fix it.

**Closed** 2017-09-25 11:17 UTC
Labels: Windows
