### ISSUE TITLE
Bitcoin Core does not display properly on High-DPI Windows 10 systems

### ISSUE THREAD

**Issue by cosmicvibe** [bitcoin/bitcoin#7341] opened 2016-01-14 02:20 UTC
![Bitcoin Core High-DPI bug](http://i.imgur.com/FKLpTtj.png)

The text is unreadable to the point where I can't even see my balance.

I have a 4K display, that is set to 200% scaling. Which means it's effectively behaving like a regular 1080p monitor, but it's lovely to read on as text is much cleaner.

**Comment by CryptAxe** [comment] 2016-02-01 19:59
Does windows 10 have DPI settings like 7 did? If so, try increasing the DPI-adjustment or whatever it is named now all the way up and make sure that doesn't fix it. Qt attempts to be as friendly (camouflaged) to the host environment as possible but sometimes strange things happen with weird resolutions I have noticed.

**Comment by tdaede** [comment] 2016-02-11 21:39
This problem can be reproduced under Linux by launching bitcoin-qt with QT_DEVICE_PIXEL_RATIO=2.

**Comment by CryptAxe** [comment] 2016-02-11 21:42
Thank you

**Comment by laanwj** [comment] 2016-02-16 15:23
Looks like a bug in the upstream Qt library.
See also issue #6472.

**Comment by jonasschnelli** [comment] 2016-02-19 16:35
Qt's <=5.5 HiDPI support only works properly on MacOSX. Qt 5.6 Beta looks promising (check: http://blog.qt.io/blog/2015/12/18/qt-5-6-beta-released/).

**Comment by cosmicvibe** [comment] 2016-02-22 03:08
Thanks for the information jonas. Does this require rebuilding Bitcoin Core against QT 5.6 beta, or is there some way to have the v0.11.2 client use 5.6 beta given that it's installed? I'm just a user and not a QT or Bitcoin developer.

**Comment by jonasschnelli** [comment] 2016-02-22 09:20
@cosmicvibe: Yes. It needs a build of BitcoinQt against Qt5.6 beta. You can download Qt5.6 beta from here: https://download.qt.io/development_releases/qt/5.6/5.6.0-beta/

**Comment by cosmicvibe** [comment] 2016-04-19 01:29
Thank you, that helped a lot!

**Comment by jonasschnelli** [comment] 2016-06-21 09:13
Should be much better now when compiled against Qt5.6.1 (which is now our depends default QT version).

<img width="1440" alt="bildschirmfoto 2016-06-20 um 11 20 08" src="https://cloud.githubusercontent.com/assets/178464/16224153/2598836c-37a1-11e6-9797-d3a2df5df7b6.png">

**Comment by laanwj** [comment] 2016-06-22 11:47
Closing due to Qt 5.6.1 switch which addresses this (#8210).

**Closed by laanwj** 2016-06-22 11:47 UTC
Labels: GUI, Upstream, Windows
