### ISSUE TITLE
[Request] Delete Address 

### ISSUE THREAD

**Issue by LaudaM** [bitcoin/bitcoin#5563] opened 2014-12-29 19:20 UTC
Hopefully this is the correct way of making a request. A good and useful feature would be an option to delete an address from your wallet.
It wouldn't even be hard to implement.

**Comment by cossacksson** [comment] 2015-01-01 05:11
I don't think that deleting private keys is a very good idea for the end user. If anything, there should be an archive of used addresses, or "soft deleting" of the private keys (keeping them in wallet.dat, but ignoring them in the ui).

**Comment by luke-jr** [comment] 2015-01-01 05:31
I suppose it does make sense to stop scanning them for new transactions, at least. Maybe an option to automatically do so when a transaction is confirmed to them... :)

**Comment by LaudaM** [comment] 2015-01-01 10:37
Well indeed, maybe an option/tab where you could check your addresses which are 'on pause'/'deleted'. I mean I myself didn't generate many addresses (as people tend to), but there is already a ton of clutter in my wallet.

**Comment by laanwj** [comment] 2015-01-01 10:55
This is a duplicate of #2710

**Closed by laanwj** 2015-01-01 10:55 UTC
