### ISSUE TITLE
p2p_compactblocks.py failing occasionally on master

### ISSUE THREAD

**Issue by sdaftuar** [bitcoin/bitcoin#12978] opened 2018-04-13 15:47 UTC
Reported here https://github.com/bitcoin/bitcoin/pull/12629#issuecomment-381095603 by @Empact.  I've seen it now in a few different travis jobs, including:

https://travis-ci.org/bitcoin/bitcoin/jobs/366157920
https://travis-ci.org/bitcoin/bitcoin/jobs/366139851

From my initial investigation it seems like there may be an actual bug in block announcement, so I'm  opening this issue to track.

**Comment by sdaftuar** [comment] 2018-04-13 17:10
I haven't yet been able to reproduce.  What I find most disturbing from staring at the debug logs in the travis failure (eg around here: https://travis-ci.org/bitcoin/bitcoin/jobs/366157920#L6672) is that the latest block generated on the node isn't being relayed to any peers -- neither the python mininode peers, nor the other bitcoind peer.  

Not really sure how that can be happening (and only in this particular test?  seems like a block relay problem of this sort would cause widespread testing failures).  So hopefully I'm somehow just overlooking a particular quirk of the testing setup here.

**Comment by jnewbery** [comment] 2018-04-13 18:40
I think I see what's going on here. There are two nodes under test:
- node0
- node1

and three connections to those nodes:
- self.test_node (connects to node0)
- self.segwit_node (connects to node1 and signals NODE_NETWORK|NODE_WITNESS)
- self.old_node (connects to node1 and signals NODE_NETWORK)

The test is failing in the call to `self.test_sendcmpct()` on line 807. Before that:

1. The call to `self.test_sendcmpct()` on line 805 is generating blocks on node0 and checking that they're received by `self.test_node`.
2. `sync_blocks(self.nodes)` on line 806 ensures that node1 is at the same tip as node0
3. `self.test_sendcmpct()` on line generates blocks on node1 and checks that they're received by `self.segwit_node`.

Note that the call to `sync_blocks` on 806 has not ensured that the blocks have been propagated to `self.segwit_node or `self.old_node`. The test fails because it drops into `self.test_sendcmpct()`, and calls generate on node1 *before* node1 has propagated the block from node0 to `self.segwit_node`. After generate is called, the test is waiting for node1 to send the newly generated block to `self.segwit_node`, but the next inv from node1 to `self.segwit_node` is for the block previously generated by node0:

```
node0 2018-04-13T13:07:45.809404Z ThreadRPCServer method=generate user=__cookie__               <--------- generate to node0 from self.test_sendcmpct() on line 805
[...]
 node0 2018-04-13T13:07:45.812956Z CreateNewBlock(): block weight: 716 txs: 0 fees: 0 sigops 400 
[...]
 node0 2018-04-13T13:07:45.815971Z UpdateTip: new best=23eb17fb1f4805b7c4adb768c250ff07a16aa16759839dc87c5ac98bd686705b height=111 version=0x20000000 log2_work=7.8073549 tx=113 date='2018-04-13T13:08:03Z' progress=1.000000 cache=0.0MiB(121txo) 
[...]
 node0 2018-04-13T13:07:45.816646Z sending headers (82 bytes) peer=0 
[...]
 node1 2018-04-13T13:07:45.817742Z received: headers (82 bytes) peer=0    <---- node1 receives block
[...]
 node1 2018-04-13T13:07:45.825341Z UpdateTip: new                         <--- node1 synced
[...]
 node1 2018-04-13T13:07:45.827344Z ThreadRPCServer method=generate user=__cookie__              <--------- generate to node1 from self.test_sendcmpct() on line 807
[...]
 node1 2018-04-13T13:07:45.830472Z UpdateTip: new best=7bfef9174d2d8c9bf165ce690b6eca7c2567fa52f3e6d9cb3d98d14327e87d33 height=112 version=0x20000000 log2_work=7.820179 tx=114 date='2018-04-13T13:08:03Z' progress=1.000000 cache=0.0MiB(122txo)                        <----------------- node1 tip advances. Test now waits for notification of block (check_announcement_of_new_block() on line 172)
[...]
 node1 2018-04-13T13:07:45.831909Z SendMessages: sending inv peer=2 hash=23eb17fb1f4805b7c4adb768c250ff07a16aa16759839dc87c5ac98bd686705b            <---------- node1 sends the blockhash for the *old block* to segwit_node
 node1 2018-04-13T13:07:45.831954Z sending inv (37 bytes) peer=2 
 test  2018-04-13T13:07:45.832000Z TestFramework.mininode (DEBUG): Received message from 127.0.0.1:11458: msg_inv(inv=[CInv(type=Block hash=23eb17fb1f4805b7c4adb768c250ff07a16aa16759839dc87c5ac98bd686705b)]) 
[...]
 test  2018-04-13T13:08:15.877000Z TestFramework.utils (ERROR): wait_until() failed. Predicate: (['        def received_hash():\n', '            return (block_hash in self.announced_blockhashes)\n'], 79)    <-------- test times out waiting for new block
```

compare this with a passing case where the block from node0 is propagated to `self.segwit_node` *before* the `generate` call to node1.

It'd be nice to rewrite this test to not have so much state between the different nodes-under-test and test connections. If we fix this one timing issue, there's no guarantee that there aren't other similar issues that will be hit by travis.

**Comment by jnewbery** [comment] 2018-04-13 20:03
I've spoken to @sdaftuar - we think this may be a race in the validationinterface callbacks around `vBlockHashesToAnnounce`. Still investigating.

**Comment by jnewbery** [comment] 2018-04-13 21:31
Caught it! https://travis-ci.org/jnewbery/bitcoin/jobs/366281859

Looks like `UpdatedBlockTip()` is called in the wrong order:

```
node1 2018-04-13T21:03:36.950443Z UpdateTip: new best=74fa99e8f6767f817000b9ddb050bb2fc53d329203d63f3a084d37300be894e9 height=111 version=0x20000000 log2_work=7.8073549 tx=113 date='2018-04-13T21:03:54Z' progress=1.000000 cache=0.0MiB(121txo) 
[...]
 node1 2018-04-13T21:03:36.955464Z UpdateTip: new best=57a644748fb3e38c225972bd2e3b0fd45e7665498ebd1fcaf8e37aa6c07ac886 height=112 version=0x20000000 log2_work=7.820179 tx=114 date='2018-04-13T21:03:54Z' progress=1.000000 cache=0.0MiB(122txo) 
```

but:

```
node1 2018-04-13T21:03:36.955924Z UpdatedBlockTip callback: new block hash: 57a644748fb3e38c225972bd2e3b0fd45e7665498ebd1fcaf8e37aa6c07ac886 
[...]
node1 2018-04-13T21:03:36.956569Z UpdatedBlockTip callback: new block hash: 74fa99e8f6767f817000b9ddb050bb2fc53d329203d63f3a084d37300be894e9 
```

**Comment by skeees** [comment] 2018-04-14 15:17
Had some offline conversations regarding this too. After @jnewbery's insights above and a bit of reading - I think what's happening is that cs_main is released in ActivateBestChain() between ActivateBestChainStep but before the UpdatedBlockTip callback has been enqueued. 

In this particular case there are two threads now racing to enqueue an UpdatedBlockTip signal (the thread processing the block received over p2p and the thread which generated the block via rpc).

After adding a randomized sleep (see below) you can reproduce this issue a bit more reliably:

```
        }
        // When we reach this point, we switched to a new tip (stored in pindexNewTip).

        // Notifications/callbacks that can run without cs_main
        MilliSleep(GetRand(500));

        // Notify external listeners about the new tip.
        GetMainSignals().UpdatedBlockTip(pindexNewTip, pindexFork, fInitialDownload);
```

I think a potential fix is to hold cs_main until the UpdatedBlockTip signals are enqueued? Once safely enqueued they should be processed in correct order by the scheduler thread.

**Comment by TheBlueMatt** [comment] 2018-04-14 15:40
Yea, should just hold cs_main there. I'd like to also fix the bug where we generate callbacks if a block connection failed ala https://github.com/bitcoin/bitcoin/pull/12138/commits/a9db3dada0119c183d16627805e90c4dbca05c6a but its somewhat tangential.

**Comment by skeees** [comment] 2018-04-15 15:34
#12988 is a minimal fix that should resolve this specific test failure
Will also spend some time going through other signals to see if there are any analogous situations that should be proactively addressed

**Comment by promag** [comment] 2018-04-16 15:15
Couldn't we add logic to `PeerLogicValidation::UpdatedBlockTip` so that it would't rewind? It could ignore out of order notifications if it's not a reorg? It already handles blocks in between:
https://github.com/bitcoin/bitcoin/blob/0d6992168c2bda85b18fda8f6dea08da433a0dc9/src/net_processing.cpp#L923-L934

**Comment by sdaftuar** [comment] 2018-04-16 15:44
I think requiring that UpdatedBlockTip callbacks happen in order is a far better design in the long run; being resilient to these happening out of order adds a level of complexity to the listeners that isn't necessary at all, especially now that the callbacks are actually happening in a separate thread.

**Comment by promag** [comment] 2018-04-16 20:53
@sdaftuar @skeees makes sense.

**Comment by practicalswift** [comment] 2018-04-17 11:39
Should we add thread-safety analysis annotations to make sure the locking requirement is fulfilled going forward?

Are these the locks we want to be held?

```
boost::signals2::signal<void (bool, const CBlockIndex *)> NotifyBlockTip
    GUARDED_BY(cs_main);

void UpdatedBlockTip(const CBlockIndex *, const CBlockIndex *, bool fInitialDownload) 
    EXCLUSIVE_LOCKS_REQUIRED(cs_main);
```

**Comment by skeees** [comment] 2018-04-17 13:26
Apart from the test we have now which fails (but only sporadically) - I'm struggling a bit to think about what sort of test to add that would positively identify this if it broke again - what did you have in mind?

I agree that adding a lock assert doesnt say much about what happened before the lock was acquired so doesn't really guarantee anything about atomicity from chain update to event invocation. I think a different solution is to lock down event generation to certain paths (e.g. in this case ActivateBestChain) - I don't think that breaks cleanliness of the interface - the interface is more to make it easy and generalized for subscribers, but event generation is still very context dependent. I don't know of any way to accomplish this easily in c++ though - anything  obvious come to mind?

**Comment by skeees** [comment] 2018-04-17 13:39
Oh, also - I guess I should mention/shill this WIP pr https://github.com/bitcoin/bitcoin/pull/12934 I have out currently - its related. It creates a separate Validation thread and instead of threads calling directly into the validation layer - they just push messages onto a queue that the validation thread pulls from and processes completely and in order. 

In addition to more cleanly defining the interfaces into validation paths - it also makes it a lot easier to reason about concurrency and parallelism because block validation paths become single threaded and well ordered. You also get the added benefit that you can more easily parallelize stuff that happens outside of validation by explicitly making validation interfaces asynchronous - but the main goal is to better define interfaces and simplify the concurrency model in the most logically complex validation paths.

**Comment by sdaftuar** [comment] 2018-04-17 14:00
> Apart from the test we have now which fails (but only sporadically) - I'm struggling a bit to think about what sort of test to add that would positively identify this if it broke again - what did you have in mind?

I haven't worked this out yet, but I was thinking that if we could mock out the scheduler that is used by the validationinterface, then we could play around with delays in callback enqueuing time to see if that breaks ordering when generating events from multiple threads?

**Closed** 2018-04-17 14:02 UTC
Labels: Tests
