### ISSUE TITLE
Getrawtransaction working partially without -txindex is confusing

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#3220] opened 2013-11-07 16:26 UTC
I think we should make getrawtransaction fail entirely if no txindex is enabled, instead of only working on not-fully-spent transactions, with a confusing error message otherwise.

**Comment by promag** [comment] 2017-12-07 00:13
With the new deprecation mechanism we could mark it deprecated if `-txindex` is not set in 0.16 and make it available only if `-txindex`in 0.17?

**Comment by Sjors** [comment] 2017-12-28 15:54
Rather than deprecating, why not make it work without `-txindex`, albeit slow? As I suggested in https://github.com/bitcoin/bitcoin/issues/10609#issuecomment-354278198 we could add `since` argument which would specify how far to look back. In addition there could be a `timeout` argument with some sane default, after which it will give up with an error.

**Comment by sipa** [comment] 2017-12-28 15:56
I don't think that's really a good approach. If people have needs to index transactions in the chain, there should be better other projects for that.

**Comment by Sjors** [comment] 2017-12-28 16:59
@sipa what are your thoughts on a partial index through `-txindex=SOME_MIN_HEIGHT`? Or a rolling index down to the prune height?

It doesn't seem ideal having to install some middleware app in order to use second layer stuff, nor does it seem ideal for this second layer software to worry about such a basic feature as checking if a transaction is known. I'm not proposing a complete overhaul, but some sort of low hanging fruit compromise would be useful.

**Comment by sipa** [comment] 2017-12-28 17:25
@Sjors I don't think this is really needed. If you need to watch for a certain txid, you can add one of its output addressed to a watch-only wallet or so, rather than relying on full indexing of the chain.

**Comment by promag** [comment] 2018-02-22 01:41
> If we're going to deprecate getrawtransaction let's not make it more powerful first :)

@laanwj for reference `getrawtransaction` was improved in #10275.

If the goal is to "force" `getrawtransaction` to work only with `-txindex` then we could make `getrawtransaction` only available if:
 1. `-txindex` is set; or
 2. `-txindex` is not set but `-deprecatedrpc=getrawtransaction` is set.

**Comment by jimpo** [comment] 2018-03-30 06:39
I'd be in favor of dropping the coins view cache check because it is not reliable and confusing. The remaining behavior would be:

- If `block_hash` argument is set, check only that block, and error if not found
- Otherwise
  - Check the mempool and return if tx is found
  - If txindex is enabled and up to date (see https://github.com/bitcoin/bitcoin/pull/11857), check it and conclusively return tx or "Not found"
  - If txindex is disabled, error with "No such mempool transaction. Use -txindex to enable blockchain transaction queries"

**Comment by promag** [comment] 2018-03-30 08:15
> Check the mempool and return if tx is found

There is `getmempoolentry` for this so we could also drop that check from `getrawtransaction`.

**Comment by vengat90** [comment] 2018-08-08 08:15
How to get receive from an address in the transaction, which command used in http://chainquery.com site?

**Comment by Sjors** [comment] 2018-08-08 10:17
I'd rather have this feature work partially, with clear documentation and error codes, than to make it conditional on a full `txindex`. That's because `getrawtransaction` can be quite useful to lightning nodes and perhaps even lightweight wallets, that need to occasionally fetch historical stuff (not just monitor new transactions).

I think the feature can be made complete in the longer run without `txindex`.

@promag wrote:

> @laanwj for reference getrawtransaction was improved in #10275.

I.e. it can now take a `blockhash` hint.

In addition, we could build on top of #10794 to allow `getrawtransaction` to work even if that block is pruned, by fetching it from the network if needed.

Perhaps a future `txindex light` feature could use Compact Block Filter (BIP-158 style), so that we can very quickly scan all blocks, which would return a bunch of false positives that are then searched brute-force.

**Comment by sipa** [comment] 2018-08-08 17:58
@Sjors Elsewhere I have suggested splitting the feature up into separate RPCs; for example `txindexgetrawtransaction` (which only works when `-txindex` is enabled) and `mempoolgetrawtransaction` (which always works, but only for unspent transactions). Support for the it-works-for-transactions-which-have-at-least-one-unspent-output-but-very-slowly feature would only remain in the deprecated `getrawtransaction` RPC, as I don't think there is much use for it, and its conditions are too obscure to explain.

**Comment by sipa** [comment] 2018-08-08 18:02
I like @jimpo's suggested above.

**Comment by MarcoFalke** [comment] 2018-08-08 19:37
So how would removing the txout check play with races, where a tx leaves the mempool right when `mempoolgetrawtransaction` or `getrawtransaction` is called?

Also mentioned earlier https://github.com/bitcoin/bitcoin/issues/3220#issuecomment-42652492 by @sipa.

**Comment by MarcoFalke** [comment] 2018-08-08 19:42
I think the current documentation is quite clear, and there is no pressing need to change the logic right now. Also note the issue is about 5 years old and most of the discussion no longer apply to the code in master. I suggest closing it.

documentation on current master for reference:

```
NOTE: By default this function only works for mempool transactions. If the -txindex option is
enabled, it also works for blockchain transactions. If the block which contains the transaction
is known, its hash can be provided even for nodes without -txindex....

**Comment by jimpo** [comment] 2018-08-09 00:06
@MarcoFalke The documentation at the end says "DEPRECATED: for now, it also works for transactions with unspent outputs.\n" I propose fully removing support for that because it is confusing, deprecated, and slow.

**Comment by MarcoFalke** [comment] 2018-08-09 00:37
> I'm not in favor of changing getrawtransaction to stop returning mempool txs.

If you do the step and remove the utxo lookup, you might as well remove the mempool lookup and make it explicit that the interface was changed for txes that recently moved from the mempool to the utxo set. (Tell users to use `getmempoolentry`, after adding a rawtx key to the returned dict.)

**Closed** 2019-02-12 23:33 UTC
Labels: Brainstorming
