### ISSUE TITLE
Runaway exception when trying to open a wallet

### ISSUE THREAD

**Issue by GChuf** [bitcoin/bitcoin#18435] opened 2020-03-26 07:41 UTC
This happens when I click File and go over "Open Wallet ..." with my mouse. I don't even have the time to actually click it. Using Bitcoin Core version v0.19.1 (64-bit) on WIndows 10.

I chose a custom directory for blockchain data, and there was no wallet there beforehand. It did get generated though. Everything else seems to work.

![bitcoin1](https://user-images.githubusercontent.com/42591821/77621825-797aca80-6f3d-11ea-9bab-6c540c00a8d7.png)
![bitcoin3](https://user-images.githubusercontent.com/42591821/77622206-235a5700-6f3e-11ea-9e0d-04b14a07509b.png)

**Comment by brakmic** [comment] 2020-03-26 10:36
Hi @GChuf ,

I just compiled a v0.19.1 on my Windows 10 x64 Build 18363.719 and could not reproduce the error you mentioned.

This is what I did:

* started Qt Wallet
* unloaded default wallet
* tried to load wallet (via menu, also *hovered* over the menu)

![bitcoin_open_wallet](https://raw.githubusercontent.com/brakmic/bazaar/master/images/random/bitcoin_qt_open_wallet.png)

My wallet's about window:

![bitcoin_version](https://raw.githubusercontent.com/brakmic/bazaar/master/images/random/bitcoin_qt_v0.19.1.png)

But I couldn't provoke the error. Maybe I missed a step?

**Comment by GChuf** [comment] 2020-03-26 12:30
I didn't compile the binaries myself. Nor did I unload the wallet. I didn't even see the "[default wallet]" before the crash happened.
I now tried deleting some blockchain data and restarting the bitcoin-qt. It informed me that the database should be rebuilt - and now everything works as expected, no errors ...

**Comment by brakmic** [comment] 2020-03-26 12:39
> I didn't compile the binaries myself. Nor did I unload the wallet. I didn't even see the "[default wallet]" before the crash happened.

I understand. I checked out the v0.19.1 so it must be the same binary like the one you use.  Regarding the default wallet: it gets created automatically. Now I also removed all the blockchain data and created bitcoin dir in an alternative location. Still no errors.

![create_dir](https://raw.githubusercontent.com/brakmic/bazaar/master/images/random/bitcoin_qt_create_dir.png)

> I now tried deleting some blockchain data and restarting the bitcoin-qt. It informed me that the database should be rebuilt - and now everything works as expected, no errors ...

Maybe you could check the contents of your debug.log (if you haven't deleted the already). Many errors aren't visible via GUI, but debug.log often helps locating them.

**Comment by GChuf** [comment] 2020-03-27 18:32
It looks like bitcoin-qt is trying to access some files in some unrelated folders.
```

2020-03-26T07:37:49Z Synchronizing blockheaders, height: 4000 (~0.68%)
2020-03-26T07:37:52Z GUI: Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.

2020-03-26T07:37:52Z 

************************
EXCEPTION: N5boost10filesystem16filesystem_errorE       
boost::filesystem::status: The file cannot be accessed by the system: "F:\nttemp\NLTmpMount01\Program Files\Common Files\microsoft shared\ink\Alphabet.xml"       
C:\Program Files\Bitcoin\bitcoin-qt.exe in Runaway exception      
```

**Comment by brakmic** [comment] 2020-03-27 18:49
@GChuf 

Thanks for the debug.log.

So far, the only entries I was able to find regarding the file **Alphabet.xml**...

> nttemp\NLTmpMount01\Program Files\Common Files\microsoft shared\ink\Alphabet.xml

are texts on malware, ransomware and similar software. I could not find anything related **Alphabet.xml** file in Bitcoin's source code. 

My first thought was that it was related to translation files, because those are structurally XML files as well.

I don't know for sure and I don't want to raise a false alarm, but maybe these two links can help you further investigate the issue.

https://totalhash.cymru.com/analysis/?bf1a848c6540b21d46e222cb054cae36adb639b3
https://www.trendmicro.com/vinfo/us/threat-encyclopedia/malware/ransom.win32.friedex.smthb

It seems that ransomware described in these articles explicitly creates this file, among others.

However, this is only a speculation without much evidence.

Regards,

**Comment by hebasto** [comment] 2020-03-27 19:23
@GChuf 
> I didn't compile the binaries myself.

What site your binaries are downloaded from?

**Comment by GChuf** [comment] 2020-03-28 08:53
I downloaded the binaries here:
https://bitcoincore.org/bin/bitcoin-core-0.19.1/

I know where the alphabet.xml file comes from. The "nttemp" folder is created by one of the programs that I use. 
However, I myself cannot open the file. I get the following error when trying to edit it with notepad:
`The file cannot be accessed by the system.`

**Comment by adamjonas** [comment] 2020-12-23 21:41
@GChuf have you had continued difficulty with newer releases or otherwise seen this bug persistent? Given that we haven't seen similar reports, I'm wondering if this is a local issue.

**Comment by GChuf** [comment] 2020-12-27 20:16
@adamjonas I don't know how to reproduce the issue - I would need a file that "cannot be accessed by the system" to test it again.
But I'm not sure why bitcoin was looking at that folder/file anyway.

**Comment by adamjonas** [comment] 2021-01-19 22:45
Closing since there aren't steps to reproduce or other similar reports.

**Closed by adamjonas** 2021-01-19 22:45 UTC
Labels: Bug
