### ISSUE TITLE
cyrillic/unicode issue requires daemon/QT to be run as admin.

### ISSUE THREAD

**Issue by xaya** [bitcoin/bitcoin#15092] opened 2019-01-03 22:02 UTC
After this fix is applied: https://github.com/bitcoin/bitcoin/commit/5bb0164ceecc2e61f1839b482e821909e05a736e which fixes /issues/15089

there is another problem that prevents windows users with usernames that are cyrillic/unicode using bitcoin core:

> 2019-01-03T21:42:16Z * Using 2.0MiB for block index database
> 2019-01-03T21:42:16Z * Using 8.0MiB for chain state database
> 2019-01-03T21:42:16Z * Using 440.0MiB for in-memory UTXO set (plus up to 286.1MiB of unused mempool space)
> 2019-01-03T21:42:16Z init message: Loading block index...
> 2019-01-03T21:42:16Z Opening LevelDB in C:\Users\Даниелька\AppData\Roaming\Bitcoin\blocks\index
> 2019-01-03T21:42:16Z Fatal LevelDB error: IO error: C:\Users\Даниелька\AppData\Roaming\Bitcoin\blocks\index\LOCK: Could not lock file.
> 2019-01-03T21:42:16Z You can use -debug=leveldb to get more complete diagnostic messages
> 2019-01-03T21:42:16Z Fatal LevelDB error: IO error: C:\Users\Даниелька\AppData\Roaming\Bitcoin\blocks\index\LOCK: Could not lock file.
> 2019-01-03T21:42:16Z : Error opening block database.
> Please restart with -reindex or -reindex-chainstate to recover.
> 

Running bitcoind.exe and bitcoin-qt.exe as administrator fixes this issue but this should not be required - it's like having to run something as root on linux.

Running the same bitcoind.exe and bitcoin-qt.exe on windows with a standard windows username (no special characters) works fine without having to run as administrator.

Tested using Windows 10 64bit and the latest Master branch using the cross compile guide with the patch https://github.com/bitcoin/bitcoin/commit/5bb0164ceecc2e61f1839b482e821909e05a736e

You can test on windows by just creating a new user called "Даниелька" (copy and paste it).

The prebuilt binaries [https://bitcoin.org/bin/bitcoin-core-0.17.1/bitcoin-0.17.1-win64.zip] work without having to run as admin.

**Comment by fanquake** [comment] 2019-01-04 04:49
Confirmed the issue by creating a new user `bitcoin-Даниелька`, building from depends (using WSL) and running `bitcoin-qt`:

![windows-installing](https://user-images.githubusercontent.com/863730/50674053-c06d5f00-101d-11e9-8805-54c7ff3a12d9.png)
![windows error](https://user-images.githubusercontent.com/863730/50674056-c3684f80-101d-11e9-9b75-b89674ae297a.png)

As suggested, running as administrator (right-click `Run as Administrator`), runs the binary, however, that's because Bitcoin Core will be using the administrator data directory (i.e `\IEUser\AppData\Roaming\Bitcoin` on my VM), so you wont see any unicode issues.

@xaya I assume your admin username doesn't contain any unicode characters?

**Comment by xaya** [comment] 2019-01-04 09:40
Hi. You also need to make the "Даниелька" user an adminstrator (log in and out as well).

When you run as an administrator with an admnistrator account it will user that users "userdata" directories.

**Comment by xaya** [comment] 2019-01-04 23:04
this updated referenced by @ken2812221
https://github.com/bitcoin-core/leveldb/pull/18

fixes this issue

**Comment by fanquake** [comment] 2019-05-28 20:33
Closing this, as it should have been solved by https://github.com/bitcoin-core/leveldb/pull/18 which was pulled into Core via #15270 and released as part of `v0.18.0`.

**Closed by fanquake** 2019-05-28 20:33 UTC
Labels: Windows
