### ISSUE TITLE
Depends' makefiles do not like paths with spaces

### ISSUE THREAD

**Issue by sinetek** [bitcoin/bitcoin#23895] opened 2021-12-29 15:54 UTC
Hi there, issue with the depends makefiles is that they bomb out when invoked within a path with spaces.

$ git clone https://github.com/bitcoin/bitcoin bitcoin\ upstream
$ cd bitcoin\ upstream/depends
$ make download-win

```
[phil@ depends]$ make download-win
sha256sum: /home/phil/work/bitcoin: No such file or directory
sha256sum: upstream/depends/patches/qt/qt.pro: No such file or directory
sha256sum: /home/phil/work/bitcoin: No such file or directory
sha256sum: upstream/depends/patches/qt/qttools_src.pro: No such file or directory
sha256sum: /home/phil/work/bitcoin: No such file or directory
sha256sum: upstream/depends/patches/qt/fix_qt_pkgconfig.patch: No such file or directory
sha256sum: /home/phil/work/bitcoin: No such file or directory
sha256sum: upstream/depends/patches/qt/mac-qmake.conf: No such file or directory
sha256sum: /home/phil/work/bitcoin: No such file or directory
sha256sum: upstream/depends/patches/qt/fix_no_printer.patch: No such file or directory
sha256sum: /home/phil/work/bitcoin: No such file or directory
sha256sum: upstream/depends/patches/qt/no-xlib.patch: No such file or directory
sha256sum: /home/phil/work/bitcoin: No such file or directory
sha256sum: upstream/depends/patches/qt/dont_hardcode_x86_64.patch: No such file or directory
sha256sum: /home/phil/work/bitcoin: No such file or directory
sha256sum: upstream/depends/patches/qt/fix_montery_include.patch: No such file or directory
sha256sum: /home/phil/work/bitcoin: No such file or directory
sha256sum: upstream/depends/patches/qt/fix_android_jni_static.patch: No such file or directory
sha256sum: /home/phil/work/bitcoin: No such file or directory
```

Expected behavior: Make downloads the files and doesn't crash uselessly.

**Comment by sinetek** [comment] 2021-12-29 15:56
I am trying to fix this myself but the Makefiles are pretty obfuscated, I don't understand much.

**Comment by hebasto** [comment] 2021-12-29 16:10
Also https://github.com/bitcoin/bitcoin/issues/12528.

I don't think it is ever possible to use spaces in development environment paths with our current set of building tools.

**Comment by sinetek** [comment] 2021-12-29 16:17
> Also #12528.
> 
> I don't think it is ever possible to use spaces in development environment paths with our current set of building tools.

Certainly works for the main build.

**Comment by hebasto** [comment] 2021-12-29 17:06
> > Also #12528.
> > I don't think it is ever possible to use spaces in development environment paths with our current set of building tools.
> 
> Certainly works for the main build.

> $ cd bitcoin\ upstream/depends
> $ make download-win

I mean, using `depends` as it is assumed from your example in the OP.

If this assumption is correct, this issue is a duplicate of #12528.

**Comment by fanquake** [comment] 2021-12-30 00:50
This is not a problem we can / are going to solve. It's an underlying limitation of the tools we use in our build system. I'd suggest renaming your directory to anything other than a name with a space in it. i.e `bitcoin_upstream`, `bitcoin-upstream` etc.

**Closed by fanquake** 2021-12-30 00:50 UTC
Labels: Bug

**Comment by sinetek** [comment] 2021-12-31 13:39
Not going to reopen this issue, but the solution I found is to use a different space character that is not meaningful to Make, such as the following.
https://www.compart.com/en/unicode/U+2005
It is a hack, but I really want spaces in this folder name.
