### ISSUE TITLE
Can't build qt 5.7.1 for windows

### ISSUE THREAD

**Issue by PwnK** [bitcoin/bitcoin#9585] opened 2017-01-19 18:27 UTC
### Describe the issue
After the qt 5.7.1 update i haven't been able to build gui for windows. Im using ubuntu 14.04 vm and I had no issues building qt 5.6.1.
#### If so, please list the steps to reproduce below:
1. I follow the windows build notes.

```
checking for main in -lQt5Core   ... yes
checking for main in -lQt5Gui    ... yes
checking for main in -lQt5Network... yes
checking for main in -lQt5Widgets... yes
checking for main in -lQt5Test... yes
checking QTest usability... yes
checking QTest presence... yes
checking for QTest... yes
checking for main in -lQt5DBus... yes
checking QtDBus usability... yes
checking QtDBus presence... yes
checking for QtDBus... yes
checking for static Qt... yes
checking for Qt >= 5.6... yes
checking for main in -lQt5PlatformSupport... yes
checking for Qt < 5.4... no
checking for static Qt plugins: -lqwindows... no
configure: WARNING: Could not resolve: -lqwindows; bitcoin-qt frontend will not be built
checking whether to build Bitcoin Core GUI... no (Qt5)
```
Is there some extra package you now have to install? I have installed these: libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler
- OS: Windows 10 x64

**Comment by theuni** [comment] 2017-01-19 18:58
Are you using our depends? If so, there's no need to install any of the qt tools/libs, they're all built internally.

Can you please (via pastebin.com or so) paste your config.log?

**Comment by MarcoFalke** [comment] 2017-01-19 19:03
This seems to affect gitian, so I assigned it 0.14 and medium priority.

**Comment by PwnK** [comment] 2017-01-19 19:58
http://pastebin.com/d1wdaRwP
Here is the config.log

**Comment by theuni** [comment] 2017-01-19 21:07
Thanks, reproduced. Working on a fix.

**Comment by theuni** [comment] 2017-01-25 15:59
Still working on this off-and-on. There are a few separate issues, some harder to solve than others. I think I may go ahead and PR a few fixes that get us closer to building, even if it doesn't get us all the way there yet.

**Comment by MarcoFalke** [comment] 2017-01-25 20:08
Good to hear. In case this turns out to be too tricky to get right for
0.14, we can always revert the bump, which buys us some time to fix it in
0.15.

**Comment by laanwj** [comment] 2017-01-26 08:54
One thing I don't understand here: Why did the bump pass travis, if it breaks the windows build?

**Comment by MarcoFalke** [comment] 2017-01-26 19:49
@laanwj It should, but qt is disabled for most entries in the travis matrix right now.

**Closed** 2017-01-30 08:16 UTC
Labels: Build system, Priority Medium
