### ISSUE TITLE
RPC `getblock` resulted in 500 and ReadBlockFromDisk: OpenBlockFile failed for FlatFilePos(nFile=-1, nPos=0)

### ISSUE THREAD

**Issue by arcivanov** [bitcoin/bitcoin#20978] opened 2021-01-21 17:47 UTC
Invoking HTTP RPC  `getblock` resulted in the following failure: 

```
status_code: 500 status: Internal Server Error response_body: {"result":null,"error":{"code":-1,"message":"Block not found on disk"}
```

The logs have shown:

```
2021-01-21T16:48:53Z Pre-allocating up to position 0x400000 in rev02417.dat
2021-01-21T16:48:53Z UpdateTip: new best=00000000000000000005656edcf6fb5cea1d2fe392841a9bdaa8b1fa821df661 height=667046 version=0x20004000 log2_work=92.608345 tx=608416058 date='2021-01-21T16:48:23Z' progress=1.000000 cache=95.6MiB(725599txo) warning='73 of last 100 blocks have unexpected version'
2021-01-21T16:59:14Z UpdateTip: new best=0000000000000000000383edc4ee51e5e55000c85ae844899e582aedc6d0cb2f height=667047 version=0x2000e000 log2_work=92.608362 tx=608418465 date='2021-01-21T16:58:42Z' progress=1.000000 cache=96.9MiB(735971txo) warning='73 of last 100 blocks have unexpected version'

2021-01-21T17:13:25Z ERROR: ReadBlockFromDisk: OpenBlockFile failed for FlatFilePos(nFile=-1, nPos=0)

2021-01-21T17:13:25Z UpdateTip: new best=0000000000000000000bc7c177f0ef9fa47492beb5c14250c6d412b12997a56b height=667048 version=0x20000000 log2_work=92.608379 tx=608421018 date='2021-01-21T17:13:24Z' progress=1.000000 cache=98.4MiB(747960txo) warning='72 of last 100 blocks have unexpected version'
2021-01-21T17:16:06Z UpdateTip: new best=000000000000000000034359728a89d359e6859f6908145594888c26f952dcb7 height=667049 version=0x20600000 log2_work=92.608396 tx=608423202 date='2021-01-21T17:15:51Z' progress=1.000000 cache=99.2MiB(754485txo) warning='73 of last 100 blocks have unexpected version'
```

**Expected behavior**

No error

**Actual behavior**

RPC 500 error returned and ReadBlockFromDisk ERROR logged.

**To reproduce**

Unknown.

**System information**

AWS K8S 4 CPUs/8Gi RAM, GP3 EBS 3000 IOPS/125Mips 

```
2021-01-21T15:30:54Z Bitcoin Core version v0.20.1 (release build)
2021-01-21T15:30:54Z Assuming ancestors of block 0000000000000000000f2adce67e49b0b6bdeb9de8b7c3d7e93b21e7fc1e819d have valid signatures.
2021-01-21T15:30:54Z Setting nMinimumChainWork=00000000000000000000000000000000000000000e1ab5ec9348e9f4b8eb8154
2021-01-21T15:30:54Z Using the 'shani(1way,2way)' SHA256 implementation
2021-01-21T15:30:54Z Using RdSeed as additional entropy source
2021-01-21T15:30:54Z Using RdRand as an additional entropy source
2021-01-21T15:30:54Z Default data directory /root/.bitcoin
2021-01-21T15:30:54Z Using data directory /home/bitcoin/.bitcoin
2021-01-21T15:30:54Z Config file: /home/bitcoin/.bitcoin/bitcoin.conf (not found, skipping)
2021-01-21T15:30:54Z Command-line arg: datadir="/home/bitcoin/.bitcoin"
2021-01-21T15:30:54Z Command-line arg: rpcallowip="100.64.0.0/10"
2021-01-21T15:30:54Z Command-line arg: rpcbind=****
2021-01-21T15:30:54Z Command-line arg: rpcpassword=****
2021-01-21T15:30:54Z Command-line arg: rpcport="18332"
2021-01-21T15:30:54Z Command-line arg: rpcuser=****
2021-01-21T15:30:54Z Command-line arg: rpcworkqueue="4096"
2021-01-21T15:30:54Z Command-line arg: server=""
2021-01-21T15:30:54Z Command-line arg: txindex="1"
2021-01-21T15:30:54Z Using at most 125 automatic connections (1048576 file descriptors available)
2021-01-21T15:30:54Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
2021-01-21T15:30:54Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
2021-01-21T15:30:54Z Script verification uses 7 additional threads
2021-01-21T15:30:54Z scheduler thread start
2021-01-21T15:30:54Z WARNING: the RPC server is not safe to expose to untrusted networks such as the public internet
2021-01-21T15:30:54Z HTTP: creating work queue of depth 4096
2021-01-21T15:30:54Z Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcauth for rpcauth auth generation.
2021-01-21T15:30:54Z HTTP: starting 4 worker threads
2021-01-21T15:30:54Z Using wallet directory /home/bitcoin/.bitcoin
2021-01-21T15:30:54Z init message: Verifying wallet(s)...
2021-01-21T15:30:54Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2021-01-21T15:30:54Z Using wallet /home/bitcoin/.bitcoin
2021-01-21T15:30:54Z BerkeleyEnvironment::Open: LogDir=/home/bitcoin/.bitcoin/database ErrorFile=/home/bitcoin/.bitcoin/db.log
2021-01-21T15:30:54Z init message: Loading banlist...
2021-01-21T15:30:54Z Using /16 prefix for IP bucketing
2021-01-21T15:30:54Z Cache configuration:
2021-01-21T15:30:54Z * Using 2.0 MiB for block index database
2021-01-21T15:30:54Z * Using 56.0 MiB for transaction index database
2021-01-21T15:30:54Z * Using 8.0 MiB for chain state database
2021-01-21T15:30:54Z * Using 384.0 MiB for in-memory UTXO set (plus up to 286.1 MiB of unused mempool space)
2021-01-21T15:30:54Z init message: Loading block index...
2021-01-21T15:30:54Z Opening LevelDB in /home/bitcoin/.bitcoin/blocks/index
2021-01-21T15:30:54Z Opened LevelDB successfully
2021-01-21T15:30:54Z Using obfuscation key for /home/bitcoin/.bitcoin/blocks/index: 0000000000000000
2021-01-21T15:30:58Z LoadBlockIndexDB: last block file = 2417
2021-01-21T15:30:58Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=6, size=8006735, heights=667029...667034, time=2021-01-21...2021-01-21)
2021-01-21T15:30:58Z Checking all blk files are present...
2021-01-21T15:30:58Z Opening LevelDB in /home/bitcoin/.bitcoin/chainstate
2021-01-21T15:30:58Z Opened LevelDB successfully
2021-01-21T15:30:58Z Using obfuscation key for /home/bitcoin/.bitcoin/chainstate: 8d04dcac7c5beaa0
2021-01-21T15:30:58Z Loaded best chain: hashBestChain=000000000000000000029ce801aba0474f571370c0f12808bae6501cf9ca1cec height=667034 date=2021-01-21T15:13:02Z progress=0.999994
2021-01-21T15:30:58Z init message: Rewinding blocks...
2021-01-21T15:30:58Z FlushStateToDisk: write coins cache to disk (0 coins, 0kB) started
2021-01-21T15:30:58Z FlushStateToDisk: write coins cache to disk (0 coins, 0kB) completed (0.00s)
2021-01-21T15:30:58Z init message: Verifying blocks...
2021-01-21T15:30:58Z Verifying last 6 blocks at level 3
2021-01-21T15:30:58Z [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
2021-01-21T15:31:03Z No coin database inconsistencies in last 6 blocks (11765 transactions)
2021-01-21T15:31:03Z  block index            9520ms
2021-01-21T15:31:03Z Opening LevelDB in /home/bitcoin/.bitcoin/indexes/txindex
2021-01-21T15:31:03Z Opened LevelDB successfully
2021-01-21T15:31:03Z Using obfuscation key for /home/bitcoin/.bitcoin/indexes/txindex: 0000000000000000
2021-01-21T15:31:03Z init message: Loading wallet...
2021-01-21T15:31:03Z txindex thread start
2021-01-21T15:31:03Z txindex is enabled at height 667034
2021-01-21T15:31:03Z txindex thread exit
2021-01-21T15:31:03Z BerkeleyEnvironment::Open: LogDir=/home/bitcoin/.bitcoin/database ErrorFile=/home/bitcoin/.bitcoin/db.log
2021-01-21T15:31:03Z [default wallet] Wallet File Version = 169900
2021-01-21T15:31:03Z [default wallet] Keys: 2001 plaintext, 0 encrypted, 2001 w/ metadata, 2001 total. Unknown wallet records: 0
2021-01-21T15:31:03Z [default wallet] Wallet completed loading in              35ms
2021-01-21T15:31:03Z [default wallet] setKeyPool.size() = 2000
2021-01-21T15:31:03Z [default wallet] mapWallet.size() = 0
2021-01-21T15:31:03Z [default wallet] m_address_book.size() = 0
2021-01-21T15:31:03Z block tree size = 667038
2021-01-21T15:31:03Z nBestHeight = 667034
2021-01-21T15:31:03Z torcontrol thread start
2021-01-21T15:31:03Z Bound to [::]:8333
2021-01-21T15:31:03Z Bound to 0.0.0.0:8333
2021-01-21T15:31:03Z init message: Loading P2P addresses...
```

**Comment by MarcoFalke** [comment] 2021-01-21 17:50
What was the argument passed to `getblock`?

**Comment by arcivanov** [comment] 2021-01-21 17:53
Can't tell you, not in the logs. I have a theory, because we have N load-balanced BTC nodes and it may have learned about the block from one of the nodes that had it but then requested it from the other that hasn't yet had it.

But in that case it shouldn't be 500, more like 400 Bad Request - it's not the user that failed, it's the client that requested a non-existing block. But again, it's only a theory.

**Comment by arcivanov** [comment] 2021-01-21 17:54
Let me check other logs to see if I can find the block in question.

**Comment by arcivanov** [comment] 2021-01-21 18:17
```
2021-01-21 16:59:18.661  INFO 1   btc.state: {"current_block":667047}
2021-01-21 17:13:30.565  INFO 1   btc.state: {"current_block":667048}
```
So I suspect current block was 667048.

**Comment by sipa** [comment] 2021-01-21 18:18
Do you have pruning enabled?

**Comment by arcivanov** [comment] 2021-01-21 18:20
```
2021-01-21T15:30:54Z Config file: /home/bitcoin/.bitcoin/bitcoin.conf (not found, skipping)
2021-01-21T15:30:54Z Command-line arg: datadir="/home/bitcoin/.bitcoin"
2021-01-21T15:30:54Z Command-line arg: rpcallowip="100.64.0.0/10"
2021-01-21T15:30:54Z Command-line arg: rpcbind=****
2021-01-21T15:30:54Z Command-line arg: rpcpassword=****
2021-01-21T15:30:54Z Command-line arg: rpcport="18332"
2021-01-21T15:30:54Z Command-line arg: rpcuser=****
2021-01-21T15:30:54Z Command-line arg: rpcworkqueue="4096"
2021-01-21T15:30:54Z Command-line arg: server=""
2021-01-21T15:30:54Z Command-line arg: txindex="1"
```

Nope.

**Comment by sipa** [comment] 2021-01-21 18:21
Did you ever manually delete a blocks/blk*.dat file?

**Comment by arcivanov** [comment] 2021-01-21 18:22
Nope. This is a sealed container with and EBS volume mounted. Nobody touches the container or volume by hand.

**Comment by MarcoFalke** [comment] 2021-01-21 18:23
* 2021-01-21 17:13:30.565  INFO 1   btc.state: {"current_block":667048}
* 2021-01-21T17:13:25Z ERROR: ReadBlockFromDisk: OpenBlockFile failed for FlatFilePos(nFile=-1, nPos=0)
* 2021-01-21T17:13:25Z UpdateTip: new best=0000000000000000000bc7c177f0ef9fa47492beb5c14250c6d412b12997a56b height=667048 version=0x20000000 log2_work=92.608379 tx=608421018 date='2021-01-21T17:13:24Z' progress=1.000000 cache=98.4MiB(747960txo) warning='72 of last 100 blocks have unexpected version'


Looks like a race on your side

**Comment by arcivanov** [comment] 2021-01-21 18:23
As I mentioned in https://github.com/bitcoin/bitcoin/issues/20978#issuecomment-764828079 I suspect we learned about the block from one node and requested it from another node via transparent loadbalancing.

**Comment by arcivanov** [comment] 2021-01-21 18:24
> Looks like a race on your side

Entirely possible but then the error should be 400 not 500 - the server didn't fail, the user did.

**Comment by sipa** [comment] 2021-01-21 18:25
I suspect that there was a race on our end too... the node probably had started processing the block when the RPC request came in, and it tried to look for something that it knew about but wasn't on disk yet.

**Comment by arcivanov** [comment] 2021-01-21 18:27
> I suspect that there was a race on our end too..
Also possible, hence I filed.

**Comment by adamjonas** [comment] 2023-03-09 20:26
@arcivanov any chance you'd be willing to attempt to reproduce with an updated release?

**Comment by arcivanov** [comment] 2023-03-10 03:23
I could check the logs to see if it's still the case.

**Comment by willcl-ark** [comment] 2023-04-05 20:46
> But in that case it shouldn't be 500, more like 400 Bad Request - it's not the user that failed, it's the client that requested a non-existing block. But again, it's only a theory.
This looks to me like it will be fixed by https://github.com/bitcoin/bitcoin/pull/27101 if requesting using json 2.0 spec, where we will return status code `200` (and only an `error` field). @pinheadmz might be able to confirm?

**Comment by pinheadmz** [comment] 2023-04-06 10:48
Indeed, #27101 will return `200` in this case, if the block is *simply* missing (see below). However there is also a log message in OP from `ReadBlockFromDisk()` which was passed a flat file position it was unable to read from (which is a server error, and should be 500 IMO)

```
--> curl -v  http://__cookie__:55e80812a35493cac882b0737da870ae44621120d9dcc0793382bd779b9dba80@127.0.0.1:18443 --data '{"method":"getblock", "params": ["00000000c937983704a73af28acdec37b049d214adbda81d7e2a3dd146f6ed09"], "jsonrpc": "2.0"}'
*   Trying 127.0.0.1:18443...
* Connected to 127.0.0.1 (127.0.0.1) port 18443 (#0)
* Server auth using Basic with user '__cookie__'
> POST / HTTP/1.1
> Host: 127.0.0.1:18443
> Authorization: Basic X19jb29raWVfXzo1NWU4MDgxMmEzNTQ5M2NhYzg4MmIwNzM3ZGE4NzBhZTQ0NjIxMTIwZDlkY2MwNzkzMzgyYmQ3NzliOWRiYTgw
> User-Agent: curl/7.79.1
> Accept: */*
> Content-Length: 119
> Content-Type: application/x-www-form-urlencoded
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Thu, 06 Apr 2023 10:44:27 GMT
< Content-Length: 76
<
{"jsonrpc":"2.0","error":{"code":-5,"message":"Block not found"},"id":null}
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by fanquake** [comment] 2024-07-04 09:25
@willcl-ark was this fixed by #27101 ?

**Comment by mzumsande** [comment] 2024-07-08 18:18
If the block is not available anymore, we already throw a specific error: "Block not available (pruned data)": [rpc](https://github.com/bitcoin/bitcoin/blob/1f9d30744d32d24ad3128721cf5bd65a3f1543e8/src/rpc/blockchain.cpp#L586-L588) / [rest](https://github.com/bitcoin/bitcoin/blob/1f9d30744d32d24ad3128721cf5bd65a3f1543e8/src/rest.cpp#L310-L312)

So I think it would only be consistent to add a check for `BLOCK_HAVE_DATA`, not call `ReadRawBlockFromDisk`  and return a similar error (e.g. "Block not available (not fully downloaded yet") when the block is not available yet.

**Comment by mzumsande** [comment] 2024-07-09 04:00
see #30410

**Closed** 2024-09-16 20:18 UTC
Labels: Bug, RPC/REST/ZMQ
