### ISSUE TITLE
Script decode not decoding 0x21

### ISSUE THREAD

**Issue by 0xfff** [bitcoin/bitcoin#8770] opened 2016-09-21 00:07 UTC
bitcoin core v0.13.0.0 decodes the following tx as follows
tx hash: c49b3c445c89d832289de0fd3b0281efdcce418333dacd028061e8de9f0a6f10

```
decoderawtransaction 0100000001dbb3197449c0ede76729d75fdf845d1b4e367770211a0b30305e17ba7fa57f41010000006b483045022100b6db6e71652d2dcaa818c24d7dcba0ddca9a9a09f45a5a8b175784dde494d78602204e4b1042564da546b032f09eb02d2211f9e8fa3aeb3c987a28962a0a7a6d312b0121037a380cf3628417c275e9010eea2d7b2a05337d38af25054675e3441a43aa4565ffffffff01a0bb0d0000000000fd1901514c78ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff4c78ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2102323c909b017748294c1d1fb82648b2c2905cd941d9a863e036b3157e8aa85dd353ae00000000

{
  "txid": "c49b3c445c89d832289de0fd3b0281efdcce418333dacd028061e8de9f0a6f10",
  "hash": "c49b3c445c89d832289de0fd3b0281efdcce418333dacd028061e8de9f0a6f10",
  "size": 450,
  "vsize": 450,
  "version": 1,
  "locktime": 0,
  "vin": [
    {
      "txid": "417fa57fba175e30300b1a217077364e1b5d84df5fd72967e7edc0497419b3db",
      "vout": 1,
      "scriptSig": {
        "asm": "3045022100b6db6e71652d2dcaa818c24d7dcba0ddca9a9a09f45a5a8b175784dde494d78602204e4b1042564da546b032f09eb02d2211f9e8fa3aeb3c987a28962a0a7a6d312b[ALL] 037a380cf3628417c275e9010eea2d7b2a05337d38af25054675e3441a43aa4565",
        "hex": "483045022100b6db6e71652d2dcaa818c24d7dcba0ddca9a9a09f45a5a8b175784dde494d78602204e4b1042564da546b032f09eb02d2211f9e8fa3aeb3c987a28962a0a7a6d312b0121037a380cf3628417c275e9010eea2d7b2a05337d38af25054675e3441a43aa4565"
      },
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 0.00900000,
      "n": 0,
      "scriptPubKey": {
        "asm": "1 ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 02323c909b017748294c1d1fb82648b2c2905cd941d9a863e036b3157e8aa85dd3 3 OP_CHECKMULTISIG",
        "hex": "514c78ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff4c78ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2102323c909b017748294c1d1fb82648b2c2905cd941d9a863e036b3157e8aa85dd353ae",
        "type": "nonstandard"
      }
    }
  ]
}

decodescript 514c78ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff4c78ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2102323c909b017748294c1d1fb82648b2c2905cd941d9a863e036b3157e8aa85dd353ae

{
  "asm": "1 ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 02323c909b017748294c1d1fb82648b2c2905cd941d9a863e036b3157e8aa85dd3 3 OP_CHECKMULTISIG",
  "type": "nonstandard",
  "p2sh": "3Pr9qaUxaHFZbbdojAZFozH34dEqjpe4dU"
}
```

but decoding it manually we have:

```
51  OP_1
4c  Push data
78  Push 120 decimal  = 78 hex bytes
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
4c  Push data
78  Push 120 decimal  = 78 hex bytes
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
21  Push 33 dec = 21 hex: 
02323c909b017748294c1d1fb82648b2c2905cd941d9a863e036b3157e8aa85dd3
53  OP_3
ae  OP_CHECKMULTISIG
```

`02323c909b017748294c1d1fb82648b2c2905cd941d9a863e036b3157e8aa85dd3` translates to: `1AqLAdfMzfVpdCAtk4rMCUCK6vvNUkGBdm`

It seems like core does not see the 33 byte compressed key as valid, or is it not recognizing 0x21? opcode (quick search of 0x21 in script.h comes up empty)

**Comment by achow101** [comment] 2016-09-21 02:23
What's the problem here? 0x21 isn't an OP code, its a size identifier. Are you suggesting that it is supposed to interpret your bare multisig (non standard BTW) as just a normal p2pkh address? Because it doesn't and it won't, it will assume that the data you are pushing are blobs of data (not any sort of key, that comes later). Because this is some script, it will interpret the address as a p2sh address.

**Comment by 0xfff** [comment] 2016-09-21 03:59
Well the script appears to be valid (and it isn't mine btw) so I thought core should be able to parse it. It does specify 1 of 3 multisig, and it does provide 3 keys (albeit in a non-standard way)

**Comment by achow101** [comment] 2016-09-21 04:01
Core is able to parse the script. What exactly is the issue here?

**Comment by 0xfff** [comment] 2016-09-21 04:03
it is not showing the addresses that are eligible signatures

**Comment by davecgh** [comment] 2016-09-21 05:00
Addresses are only shown for **standard** multisig scripts.  That is not a standard multisig script since it does not consist of valid public keys which are either 33 bytes (for compressed) or 65 bytes (for uncompressed).

As an additional reference point, `btcd` produces the same output, for the same reason:

```
$ btcctl decodescript 514c78ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff4c78ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2102323c909b017748294c1d1fb82648b2c2905cd941d9a863e036b3157e8aa85dd353ae
{
  "asm": "1 ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 02323c909b017748294c1d1fb82648b2c2905cd941d9a863e036b3157e8aa85dd3 3 OP_CHECKMULTISIG",
  "type": "nonstandard",
  "p2sh": "3Pr9qaUxaHFZbbdojAZFozH34dEqjpe4dU"
}

```

**Comment by laanwj** [comment] 2016-12-08 11:49
Closing as "works as intended", could be improved in the documentation I suppose.

**Closed by laanwj** 2016-12-08 11:49 UTC
Labels: RPC/REST/ZMQ
