### ISSUE TITLE
Fix for #7080 breaks LibreSSL ???

### ISSUE THREAD

**Issue by AliceWonderMiscreations** [bitcoin/bitcoin#7580] opened 2016-02-23 13:07 UTC
LibreSSL 2.3.2 on CentOS 7 (x86_64) - 0.11.2 builds just dandy and even works. 0.12.0 fails to build.

    In file included from addrman.h:13:0,
                     from init.cpp:12:
    init.cpp: In function 'bool AppInit2(boost::thread_group&, CScheduler&)':
    init.cpp:1081:61: error: 'OPENSSL_VERSION' was not declared in this scope
         LogPrintf("Using OpenSSL version %s\n", OpenSSL_version(OPENSSL_VERSION));
                                                                 ^
    util.h:77:39: note: in definition of macro 'LogPrintf'
     #define LogPrintf(...) LogPrint(NULL, __VA_ARGS__)
                                       ^
    init.cpp:1081:76: error: 'OpenSSL_version' was not declared in this scope
         LogPrintf("Using OpenSSL version %s\n", OpenSSL_version(OPENSSL_VERSION));

It looks like that might be caused by the fix for issue #7080 ??

**Comment by jonasschnelli** [comment] 2016-02-23 13:19
Agree. Maybe we should do the [#ifdef introduced in 7083](https://github.com/bitcoin/bitcoin/pull/7083/files#diff-c865a8939105e6350a50af02766291b7R1029) the "opposite way". If OPENSSL_VERSION_NUMBER >= 0x10100000L use `OpenSSL_version(OPENSSL_VERSION)` if not use `SSLeay_version(SSLEAY_VERSION)` by default...

**Comment by sthen** [comment] 2016-02-23 13:31
LibreSSL has these defines,

```
#define LIBRESSL_VERSION_NUMBER	0x2030200fL
#define LIBRESSL_VERSION_TEXT	"LibreSSL 2.3.2"
#define OPENSSL_VERSION_NUMBER	0x20000000L
#define OPENSSL_VERSION_TEXT	LIBRESSL_VERSION_TEXT
```

so currently it would need to be something like "if defined(LIBRESSL_VERSION_NUMBER) || (OPENSSL_VERSION_NUMBER < 0x10100000L)".

**Comment by paveljanik** [comment] 2016-02-23 13:55
#7520?

**Comment by AliceWonderMiscreations** [comment] 2016-02-23 14:10
I can confirm sthen's suggestion fixes the issue.

**Comment by paveljanik** [comment] 2016-02-23 14:15
@AliceWonderMiscreations can you please check #7520?

**Comment by laanwj** [comment] 2016-02-23 14:20
Duplicate of #7515 and #7447
This was fixed in #7520, which should be backported to 0.12.1.

**Closed by laanwj** 2016-02-23 14:20 UTC
Labels: Bug

**Comment by AliceWonderMiscreations** [comment] 2016-02-23 23:17
Same issue exists in
    src/qt/rpcconsole.cpp

**Comment by paveljanik** [comment] 2016-02-24 06:07
@AliceWonderMiscreations you can PR the similar fix :-) Will you try to contribute?

**Comment by AliceWonderMiscreations** [comment] 2016-02-24 06:31
@paveljanik done - sometimes I forget how easy github makes it to do those things.
