### ISSUE TITLE
Bitcoind paytxfee

### ISSUE THREAD

**Issue by BitWaspBitWasp** [bitcoin/bitcoin#8217] opened 2016-06-18 08:13 UTC
why paytxfee and settxfee  don't work on the bitcoind latest version ?
how can I set it ?

**Comment by MarcoFalke** [comment] 2016-06-18 08:35
Can you explain what and how you tried to set them?

What does getwalletinfo return?

**Comment by BitWaspBitWasp** [comment] 2016-06-18 08:58
getwalletinfo:
  
"version": 120100,
  "protocolversion": 70012,
  "paytxfee": 0.00010000,
  "relayfee": 0.00001000,

but when I send btc I can see:  "fee": -0.00002250 .
The fee is smaller and my transaction receive "confirmations" only  in some days

**Comment by MarcoFalke** [comment] 2016-06-18 09:16
The help text for settxfee:

```
settxfee amount

Set the transaction fee per kB. Overwrites the paytxfee parameter.

Arguments:
1. amount         (numeric or string, required) The transaction fee in BTC/kB
```

So if you set to 0.0001 BTC and your transaction is 225 bytes, the fee will be 0.0000225 BTC.

**Comment by BitWaspBitWasp** [comment] 2016-06-18 10:14
yes I know it and did it(you can see: I have "paytxfee": 0.00010000,)
but in new version bitcoind  it doesn't work

**Comment by BitWaspBitWasp** [comment] 2016-06-18 10:21
sorry I understood and checked - it works - thank you very much

but in previous versions i had  "paytxfee": 0.0001 and the same  "fee": -0.0001 .

**Comment by MarcoFalke** [comment] 2016-06-18 10:27
Duplicate of #7633

**Closed by MarcoFalke** 2016-06-18 10:27 UTC
