### ISSUE TITLE
fundrawtransaction JSON value is not a string as expected 

### ISSUE THREAD

**Issue by diadal** [bitcoin/bitcoin#21858] opened 2021-05-04 19:18 UTC
unable to add the option data  to fundrawtransaction in `Bitcoin Core version v0.21.1`

**Comment by jonatack** [comment] 2021-05-04 19:25
Hi @diadal, can you provide the OS platform and rpc calls or cli commands made to reproduce your issue?

**Comment by diadal** [comment] 2021-05-04 19:27
key and value must be double quote 

```
$options = [
            "changeAddress" => "" . $adr,
            "estimate_mode" => "ECONOMICAL"
        ];
```

this work before I want using single quote without any issue 

Mac Catalina and Big Sur ` rpc calls`

**Comment by jonatack** [comment] 2021-05-04 19:47
The options are a JSON object. I don't know what language you are using (PHP?) but as a guess, for a JSON object it might need to be in curly braces, e.g. `options = {'changeAddress' => "" . $adr, 'estimate_mode' => 'ECONOMICAL'}` and so on.

**Comment by diadal** [comment] 2021-05-04 19:48
yes php it working now 

with this `$options = [
            "changeAddress" => "" . $adr,
            "estimate_mode" => "ECONOMICAL"
        ];`

**Comment by diadal** [comment] 2021-05-04 19:50
this `{'changeAddress' => "" . $adr, 'estimate_mode' => 'ECONOMICAL'}` will give error php 7.4 above no longer support `{}`

**Comment by diadal** [comment] 2021-05-04 19:52
both Object `key` and `value` must be `double quote` for `Bitcoin Core version v0.21.1` while `fundrawtransaction`

**Comment by jonatack** [comment] 2021-05-04 19:58
Are you saying that the quote-handling behavior of the Bitcoin Core fundraw RPC changed in 0.21.1 since a previous version, with the same environment and code on your side? If yes, what was the previous version of Bitcoin Core?

**Comment by diadal** [comment] 2021-05-04 20:07
the issue only occurs on this `0.21.1` 0.21.0 below never give me this issue I user single quote `''` before but I have to change to double `""` only on `fundrawtransaction` other RPC still work fine with a single quote

**Comment by diadal** [comment] 2021-05-04 20:09
am using php 8

**Comment by sipa** [comment] 2021-05-04 20:27
That is very surprising. Those single or double quotes aren't even sent to Bitcoin Core.

**Comment by diadal** [comment] 2021-05-04 20:45
well have tried again mac book Catalina and Mac mini Big Sur same issue working only with double quotes due both pc are PHP 8 maybe but 0.21.0 works

**Comment by jonatack** [comment] 2021-05-04 20:57
Could be a good idea to re-verify that something else didn't change or get updated in your development environment, e.g. language version or other libraries or dependencies.

**Comment by MarcoFalke** [comment] 2021-05-05 05:12
Which php library are you using?

**Comment by diadal** [comment] 2021-05-05 06:22
laravel 8

**Comment by MarcoFalke** [comment] 2021-05-05 06:53
Is this https://github.com/denpamusic/laravel-bitcoinrpc ? If yes, they might be able to help you, since none of us know anything about PHP and this looks like an issue unrelated to Bitcoin Core at first.

**Comment by diadal** [comment] 2021-05-05 06:56
> Is this https://github.com/denpamusic/laravel-bitcoinrpc ? If yes, they might be able to help you, since none of us know anything about PHP and this looks like an issue unrelated to Bitcoin Core at first.

no don't stress yourself already fix this I said it before that using double quotes fixed this issue 

> yes php it working now
> 
> with this `$options = [ "changeAddress" => "" . $adr, "estimate_mode" => "ECONOMICAL" ];`

**Comment by MarcoFalke** [comment] 2021-05-05 07:05
Again, none of us know any PHP and without a dump of the serialized data that triggers the bug, there is nothing we can do. Alternatively, if you can reproduce the bug with `bitcoin-cli`, it would help us.

**Comment by MarcoFalke** [comment] 2021-05-05 07:06
Closing for now until we have more info

**Comment by diadal** [comment] 2021-05-05 07:06
alright

**Closed by MarcoFalke** 2021-05-05 07:06 UTC
Labels: Bug
