### ISSUE TITLE
Compile error when using boost-1.66.0

### ISSUE THREAD

**Issue by carlocapocasa** [bitcoin/bitcoin#12116] opened 2018-01-08 18:07 UTC
I built bitcoin using the normal commands while having boost-1.66.0 installed on my arch linux system.

./autogen.sh
./configure
make

The build should complete and let me run bitcoind and bitcoin-cli

Instead, the build terminates with an error:

```
/usr/include/boost/multi_index/detail/ord_index_impl.hpp:1181:7: error: no match for call to ‘(const key_compare {aka const CompareModifiedEntry}) (const CTxMemPoolModifiedEntry&, CTxMemPoolModifiedEntry&)’
       if(comp_(key(v),key(y->value())))return false;
```

Full outbut below.

Always happens.

Build error happens with 0.15.0 and 0.15.0.1

Intel Core i7 with SSD and Arch Linux

The issue is no longer present when downgrading to boost-1.65.1.

The issue is present regardless of which additional arguments are given to `./configure`

Full output from `./configure` and `make` : 

https://gist.github.com/carlocapocasa/5f31ac2bd7c1ce3f09f4fc1474ad2cb3

**Comment by sipa** [comment] 2018-01-16 06:41
Closing as duplicate of #11837

**Closed** 2018-01-16 06:41 UTC
Labels: Linux/Unix
