### ISSUE TITLE
Connection eviction logic (AttemptToEvictConnection) is not covered by our test suite

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#16660] opened 2019-08-19 20:14 UTC
From what I can tell the connection eviction logic is not covered by our test suite (functional and unit tests).

More specifically the following is never executed with `nInbound >= nMaxInbound`:

https://github.com/bitcoin/bitcoin/blob/ed9a2a37c1878ba6b75c39b7cb263dc16c52a295/src/net.cpp#L962-L970

Context:

https://github.com/bitcoin/bitcoin/blob/ed9a2a37c1878ba6b75c39b7cb263dc16c52a295/src/net.cpp#L800-L808

A test would be nice here :-)

Due to `AttemptToEvictConnection` not being tested the following `net.cpp` functions -- which are only called directly or indirectly via `AttemptToEvictConnection` -- are currently untested:

```
static bool ReverseCompareNodeMinPingTime(const NodeEvictionCandidate& a, const NodeEvictionCandidate& b)
static bool ReverseCompareNodeTimeConnected(const NodeEvictionCandidate& a, const NodeEvictionCandidate& b)
static bool CompareNetGroupKeyed(const NodeEvictionCandidate& a, const NodeEvictionCandidate& b)
static bool CompareNodeBlockTime(const NodeEvictionCandidate& a, const NodeEvictionCandidate& b)
static bool CompareNodeTXTime(const NodeEvictionCandidate& a, const NodeEvictionCandidate& b)
static void EraseLastKElements(std::vector<T>& elements, Comparator comparator, size_t k)
```

**Comment by MarcoFalke** [comment] 2019-08-21 14:54
Closing as duplicate of #14210

**Comment by practicalswift** [comment] 2019-08-21 15:21
@MarcoFalke 

Do you know if we have any tests for the eviction logic? Perhaps my measurements are incorrect.

AFAICT the eviction logic is by far the most critical code path not covered at all by any test. I mean "at all" in the most literal sense: the code path it isn't even entered (if my measurements are correct) when running the full test suite :-)

I'm not super convinced that this very specific observation/issue is a duplicate of the general observation/issue "we could do better network testing in general" (#14210). Fixing the former can be done quickly - fixing the latter will take quite some time. Don't you think? :-)

**Comment by MarcoFalke** [comment] 2019-08-21 16:00
Fixing #14210 is a requirement for fixing this issue. This issue is also mentioned as motivating example in #14210.

**Comment by practicalswift** [comment] 2019-08-21 16:15
I can see the dependency on #14210 for functional testing, but unit testing could easily be written cover these functions AFAICT:

```
static bool ReverseCompareNodeMinPingTime(const NodeEvictionCandidate& a, const NodeEvictionCandidate& b)
static bool ReverseCompareNodeTimeConnected(const NodeEvictionCandidate& a, const NodeEvictionCandidate& b)
static bool CompareNetGroupKeyed(const NodeEvictionCandidate& a, const NodeEvictionCandidate& b)
static bool CompareNodeBlockTime(const NodeEvictionCandidate& a, const NodeEvictionCandidate& b)
static bool CompareNodeTXTime(const NodeEvictionCandidate& a, const NodeEvictionCandidate& b)
static void EraseLastKElements(std::vector<T>& elements, Comparator comparator, size_t k)
```

That would be good even if #14210 takes time to resolve :-)

**Comment by mzumsande** [comment] 2019-08-23 01:06
I think that parts of the eviction logic could be tested in a functional test also prior to #14210 being solved.

The eviction logic applies to inbound peers and ignores outbound peers - we can simulate inbound connections with `P2PInterface`, and don't need outbound peers to actually exist.

I don't see how we the logic based on address/netgroup could be tested, but other parts can.
There is a draft version of a functional test that partially covers the logic of  `CConnman::AttemptToEvictConnection`  in mzumsande@56d38d05c922ec37cae7ca957ad230a1dfbc4e96

I intend to open a PR based on this in the next days, but for that PR I will also add a commit with unit tests (unless @practicalswift you are working on that?).

**Comment by practicalswift** [comment] 2019-08-23 04:36
@mzumsande Oh, that's excellent news! Very glad to hear that you're working on this! Thanks!

> […] (unless @practicalswift you are working on that?).

No, I'm just sharing my observation: I was quite surprised to see that the code eviction code path wasn't exercised at all when running the full test suite given how important it is that we get this logic correct. An error in this code could lead to attacker triggered network partitioning.

@MarcoFalke Would you mind re-opening this ticket?

**Comment by practicalswift** [comment] 2020-05-19 11:28
Closing due to lack of progress/interest :)

**Comment by jnewbery** [comment] 2020-05-31 20:17
> Closing due to lack of progress/interest :)

https://github.com/bitcoin/bitcoin/pull/16756 has received some good review over the last two weeks, and we're covering it in review club next week (https://bitcoincore.reviews/16756.html)

I don't think we need to re-open this issue, but it's certainly not true that there isn't progress/interest in this :)

**Comment by practicalswift** [comment] 2020-05-31 20:18
Great news! :)

**Closed** 2020-06-12 18:50 UTC
Labels: P2P, Tests
