### ISSUE TITLE
error: no matching function for call to 'upnpDiscover'

### ISSUE THREAD

**Issue by mohamedfawzy96** [bitcoin/bitcoin#8967] opened 2016-10-18 18:04 UTC
net.cpp:1066:15: error: no matching function for call to 'upnpDiscover'
    devlist = upnpDiscover(2000, multicastif, minissdpdpath, 0, 0, &error);
              ^~~~~~~~~~~~
/usr/local/include/miniupnpc/miniupnpc.h:62:1: note: candidate function not
      viable: requires 7 arguments, but 6 were provided
upnpDiscover(int delay, const char * multicastif,

This error appears when i try to compile the source code

**Comment by MarcoFalke** [comment] 2016-10-18 19:09
Please provide exact steps to reproduce. Including the hardware you are running on.

**Comment by paveljanik** [comment] 2016-10-18 19:28
... especially the version of miniupnpc...

**Comment by laanwj** [comment] 2016-10-19 08:33
Yes, looks like an UPNP version conflict.
They like to just slap on arguments sometimes.
If you don't feel like debugging this I'd suggest configuring with `--without-miniupnpc`.

**Comment by mohamedfawzy96** [comment] 2016-10-19 08:43
I'm using mac OS X and I'm trying to compile the source code and every time I "make"... this error pops up.I don't really know which version i'm using.

**Comment by mohamedfawzy96** [comment] 2016-10-19 08:44
@laanwj  would this effect any of my work flow in the future ?

**Comment by mohamedfawzy96** [comment] 2016-10-19 12:54
Version 2.0

**Comment by laanwj** [comment] 2016-10-19 15:12
Version 2.0 is the same one as used in gitian, so that should work. Strange. This is the code in question:

```
#ifndef UPNPDISCOVER_SUCCESS
    /* miniupnpc 1.5 */
    devlist = upnpDiscover(2000, multicastif, minissdpdpath, 0);
#elif MINIUPNPC_API_VERSION < 14
    /* miniupnpc 1.6 */
    int error = 0;
    devlist = upnpDiscover(2000, multicastif, minissdpdpath, 0, 0, &error);
#else
    /* miniupnpc 1.9.20150730 */
    int error = 0;
    devlist = upnpDiscover(2000, multicastif, minissdpdpath, 0, 0, 2, &error);
#endif
```
It should only be trying to pass 6 arguments if MINIUPNPC_API_VERSION, which is a long time ago.

What version of bitcoin core are you trying to compile?

**Comment by mohamedfawzy96** [comment] 2016-10-19 15:25
@laanwj I'm using version 0.9.5 of bitcoin core.

should i try another version of bitcoin core ?

**Comment by laanwj** [comment] 2016-10-19 15:26
0.9.5 is *old*. You should use 0.13.0.

**Comment by laanwj** [comment] 2016-10-19 15:27
Closing, build issues with old versions are not supported...

**Closed by laanwj** 2016-10-19 15:27 UTC
Labels: Build system

**Comment by mohamedfawzy96** [comment] 2016-10-19 15:31
Thank you so much @laanwj

**Comment by MarcoFalke** [comment] 2016-10-19 18:13
@mohamedfawzy96 I am interested in your rationale in choosing 0.9.5. Did someone recommend it to you?

**Comment by jackson-sandland** [comment] 2017-10-29 19:18
v0.9.5 is the latest stable version that is not labeled as a release candidate in the output from `git tag ` That is still the case today...

**Comment by laanwj** [comment] 2017-10-29 19:22
That's because it sorts alphabetically not numerically.

**Comment by luoxing91** [comment] 2018-01-12 05:16
thanks
