### ISSUE TITLE
Breking in Mac OS

### ISSUE THREAD

**Issue by mateusgalasso** [bitcoin/bitcoin#26530] opened 2022-11-18 14:05 UTC
I'm trying to use bitcoin core on mac OS
I want to record on an external hd

but i get the following error all the time

2022-11-17T22:07:44Z msghand thread exit
2022-11-17T22:07:44Z net thread exit
2022-11-17T22:07:44Z opencon thread exit
2022-11-17T22:07:44Z FileCommit: fcntl F_FULLFSYNC failed: 25
2022-11-17T22:07:44Z ERROR: SerializeFileDB: Failed to flush file /Volumes/Extreme SSD/bitcoin_core/peers.8611
2022-11-17T22:07:44Z DumpAnchors: Flush 2 outbound block-relay-only peer addresses to anchors.dat started
2022-11-17T22:07:44Z FileCommit: fcntl F_FULLFSYNC failed: 25
2022-11-17T22:07:44Z ERROR: SerializeFileDB: Failed to flush file /Volumes/Extreme SSD/bitcoin_core/anchors.ceb3
2022-11-17T22:07:44Z DumpAnchors: Flush 2 outbound block-relay-only peer addresses to anchors.dat completed (0.01s)
2022-11-17T22:07:44Z scheduler thread exit
2022-11-17T22:07:44Z Writing 0 unbroadcast transactions to disk.
2022-11-17T22:07:44Z FileCommit: fcntl F_FULLFSYNC failed: 25
2022-11-17T22:07:44Z Failed to dump mempool: FileCommit failed. Continuing anyway.
2022-11-17T22:07:45Z FileCommit: fcntl F_FULLFSYNC failed: 25
2022-11-17T22:07:45Z ERROR: Flush: failed to commit file 1
2022-11-17T22:07:45Z *** Flushing block file to disk failed. This is likely the result of an I/O error.
2022-11-17T22:07:45Z Error: A fatal internal error occurred, see debug.log for details
2022-11-17T22:07:45Z FileCommit: fcntl F_FULLFSYNC failed: 25
2022-11-17T22:07:45Z ERROR: Flush: failed to commit file 1
2022-11-17T22:07:45Z *** Flushing undo file to disk failed. This is likely the result of an I/O error.
2022-11-17T22:07:45Z Error: A fatal internal error occurred, see debug.log for details
2022-11-17T22:07:46Z FileCommit: fcntl F_FULLFSYNC failed: 25
2022-11-17T22:07:46Z ERROR: Flush: failed to commit file 1
2022-11-17T22:07:46Z *** Flushing block file to disk failed. This is likely the result of an I/O error.
2022-11-17T22:07:46Z Error: A fatal internal error occurred, see debug.log for details
2022-11-17T22:07:46Z FileCommit: fcntl F_FULLFSYNC failed: 25
2022-11-17T22:07:46Z ERROR: Flush: failed to commit file 1
2022-11-17T22:07:46Z *** Flushing undo file to disk failed. This is likely the result of an I/O error.
2022-11-17T22:07:46Z Error: A fatal internal error occurred, see debug.log for details
2022-11-17T22:07:46Z Shutdown: done

**Comment by hebasto** [comment] 2022-11-18 15:03
@mateusgalasso 

Considering your previous https://github.com/bitcoin/bitcoin/issues/26490#issuecomment-1319226675 and https://github.com/bitcoin/bitcoin/issues/26490#issuecomment-1319255210, is it correct that an error happens on macOS Ventura?

If so, please see https://github.com/bitcoin/bitcoin/issues/26400#issuecomment-1294866176 and https://github.com/bitcoin/bitcoin/issues/26397#issuecomment-1292300303.

**Comment by john-moffett** [comment] 2022-11-18 15:07
Likely duplicate of #26455

I think this is a MacOS 13 (Ventura) specific bug for `fcntl` that occurs when using certain external drives. Are you running Ventura? If so, do you have Apple silicon (eg - M1 or M2)? 

Other projects [seem to have the same or substantially similar issue](https://groups.google.com/g/rocksdb/c/ryYJO5ZXUF0/m/MC8Aw2hoBgAJ).

A *possible* temporary and ugly workaround may be to delete or comment out the following lines and compile from source:

https://github.com/bitcoin/bitcoin/blob/6d4048468430d9d1fe5e7c5fcda13708879d1083/src/util/system.cpp#L1187-L1191

**Comment by hebasto** [comment] 2022-11-18 15:14
> Likely duplicate of #26455

Agree. Closing this one.

Let's keep discussion in #26455.

**Closed** 2022-11-18 15:14 UTC
Labels: Bug, macOS
