### ISSUE TITLE
bitcoin-cli usage issue after installation

### ISSUE THREAD

**Issue by jns4u** [bitcoin/bitcoin#8496] opened 2016-08-10 20:29 UTC
Hi

I am using linux ubuntu 32 bit system. I installed bitcoin-cli and when i tried to execute an rpc call based on chainquery api, i got following below error.

error: Could not locate RPC credentials. No authentication cookie could be found, and no rpcpassword is set in the configuration file (/home/computer/.bitcoin/bitcoin.conf)

when i open bitcoin.conf file i found it's complete blank.

What's the issue with rpc, i am also running a service named iguana that utilizes coinbase functionality.

**Comment by sipa** [comment] 2016-08-10 20:36
Is bitcoind running?

**Comment by mcccs** [comment] 2016-08-11 14:55
I don't know if adding those to `bitcoin.conf` will work, but give this a try:
```java
server=1
rpcuser=someuser
rpcpassword=someREALLYLONGpassword
```

**Comment by laanwj** [comment] 2016-08-13 13:47
Also: make sure that the datadir you provide to bitcoind matches that provided to bitcoin-cli.

**Comment by jns4u** [comment] 2016-08-15 03:11
I tried option suggested by you but same issue, now i am running bitcoin rpc using supernet iguana infrastructure. It's working fine as i wanted was to execute bitcoin rpc

I am not using bitcoin-cli method. 

thanks for help

**Comment by unsystemizer** [comment] 2016-08-16 07:04
As far as I can tell "bitcoin-cli usage" is not a bug or undocumented feature that would qualify as issue.

> I am not using bitcoin-cli method.

But in Issue title you said you are. You can get online help with `bitcoin-cli --help` or in many guides and examples online, including /docs in this repo.

If you don't know how to use 3rd party s/w, refer to the s/w documentation (`-userpass|-O <arg> Username:Password pair for bitcoin JSON-RPC server` or whatever it is for ChainQuery).  Of course it'd help to set Username and Password in bitcoin.conf (or bitcoind startup command) so that you know what they are. Not a bitcoin issue, though.

**Comment by laanwj** [comment] 2016-08-16 09:22
Closing this as it is unclear to me that this is a Bitcoin Core issue.

**Closed by laanwj** 2016-08-16 09:22 UTC
Labels: RPC/REST/ZMQ

**Comment by monkeyDemon** [comment] 2018-07-20 03:02
This error is very troublesome for me because I am sure I have used the configuration file bitcoin.conf
I didn’t receive any inspiration until I saw @sipa's comments.
Maybe Bitcoin Core had unexpectedly shuts down for some reason, this can also cause the error.

**Comment by softwareguycoder** [comment] 2018-09-13 15:34
I am puzzled about something, how would I know what user/pass to supply for the RPC?  Do I just use my user account's credentials?  And what if I am on a Windows machine and not Linux?  Thanks.
