### ISSUE TITLE
whitelisting fails for nodes added with addnode

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#26464] opened 2022-11-06 16:02 UTC
Whitelisting works for subnets for outgoing and incoming connections, unless the node has been added using addnode, in which case the permissions are always "N/A" in the GUI and the node is disconnected as if there is no whitelisting (e.g. when historical block download is reached, or a mempool request comes in, etc).

**Comment by jonatack** [comment] 2022-11-06 16:18
Regarding the GUI showing permissions of "N/A" when getpeerinfo returns ` "permissions": []` you may want to review https://github.com/bitcoin-core/gui/pull/677, in which the last commit proposes to change "N/A" to "None".

**Comment by MarcoFalke** [comment] 2022-11-07 08:56
Duplicate of #9923?

**Comment by rebroad** [comment] 2022-12-10 21:09
looks like #9923 already exists for this

**Closed** 2022-12-10 21:09 UTC
Labels: Bug
