### ISSUE TITLE
--conf confused by relative path

### ISSUE THREAD

**Issue by unsystemizer** [bitcoin/bitcoin#6506] opened 2015-08-03 10:30 UTC
```
rippler@ubuntu:~$ bitcoin-0.10.2/bin/bitcoind --conf=.bitcoin/bitcoin.testnet.conf
Error: To use bitcoind, or the -server option to bitcoin-qt, you must set an rpcpassword in the configuration file:
/home/rippler/.bitcoin/.bitcoin/bitcoin.testnet.conf <=====  !!!
It is recommended you use the following random password:
rpcuser=bitcoinrpc
rpcpassword=CW3JUTEkBSzuFj2RGHuFtWsSkfuB23RoNGHBp6woQ9oe
(you do not need to remember this password)
The username and password MUST NOT be the same.
If the file does not exist, create it with owner-readable-only file permissions.
It is also recommended to set alertnotify so you are notified of problems;
for example: alertnotify=echo %s | mail -s "Bitcoin Alert" admin@foo.com

rippler@ubuntu:~$ ll .bitcoin/bitcoin.testnet.conf
-rw------- 1 rippler rippler 102 Aug  3 03:21 .bitcoin/bitcoin.testnet.conf
rippler@ubuntu:~$ pwd
/home/rippler
```
Note that my config file isn't under `/home/rippler/.bitcoin/.bitcoin/`, but rather under `/home/rippler/.bitcoin/`.
`$ bitcoin-0.10.2/bin/bitcoind --conf=/home/rippler/.bitcoin/bitcoin.testnet.conf` works fine.

**Comment by laanwj** [comment] 2015-08-03 17:46
Only absolute paths are supported for configuration options. Probably needs a check.

**Comment by casey** [comment] 2015-08-03 18:12
Actually it looks like relatives paths are supported for configuration options. -conf, -pid, and -wallet accept relative paths which are interpreted as relative to the data directory. (-wallet only supports relative paths)

So the current behavior seems to be consistent. It would be nice if it was documented somewhere that relative paths are interpreted as relative to the data directory, but I'm not sure where the best place to put that would be.

**Comment by laanwj** [comment] 2015-08-03 18:56
Oops, `-wallet` is not supposed to accept paths at all (the database must be in the 'database environment', which is always the data dir), just file names.

For `-conf` and `-pid` you are right, `GetConfigFile` and `GetPidFile` has explicit code to prepend the datadir.
Could be better documented. I wasn't aware either.
In a way this makes sense, it makes it easy to specify an alternative config file within the datadir. 
Though the interaction is a bit convoluted: the configuration file specified using -conf can in turn override `-datadir` :-)

Closing as expected behavior, then.

**Closed by laanwj** 2015-08-03 18:56 UTC
Labels: Bug, Priority Low

**Comment by unsystemizer** [comment] 2015-08-04 06:11
Created https://github.com/bitcoin/bitcoin/pull/6512
