### ISSUE TITLE
Automatic prune on Tails OS

### ISSUE THREAD

**Issue by NotwhatIwanttotell** [bitcoin/bitcoin#25052] opened 2022-05-02 08:34 UTC
Running Bitcoin Core full node on Tails OS

New version 23.0 automatically prunes when started. I don't want to prune and have therefore set prune=0 in bitcoin.conf. But that won't stop 23.0 from pruning. Have to manually un-tick the tick box at startup. This was never the case in 22.0 so wondering if prune=0 is disabled even though its stated in options:

![image](https://user-images.githubusercontent.com/83304971/166206911-47aa4148-d79a-4106-98bf-e62efd016a1e.png)

**Comment by NotwhatIwanttotell** [comment] 2022-05-02 08:50
Here is what its looking like when starting 23.0. Notice the tick box lower left corner. It should automatically be un-ticked after bitcoin.conf is loaded.

![image](https://user-images.githubusercontent.com/83304971/166208811-409a7049-870c-4763-92b8-4ba989adb59d.png)

So every time starting 23.0 it must look like this:

![image](https://user-images.githubusercontent.com/83304971/166208959-870bf962-bcd3-42fc-a43a-f35b175fa6e1.png)

**Comment by NotwhatIwanttotell** [comment] 2022-05-02 08:56
Please also note that the red text is not correct, as 100% is already downloaded.
The USB has 1000 GB capacity. Of that 466 GB has been used for Bitcoin Core download. 450 GB available is the space that is left with a full download already in place.

**Comment by hebasto** [comment] 2022-05-02 09:07
`-prune=0` takes precedence over GUI settings. Therefore, your blockchain should be unpruned.

It is easy to verify with the `getblockchaininfo` RPC command. See the `pruned` field value.

**Comment by ryanofsky** [comment] 2022-05-02 20:41
I think there's a legitimate UI issue here. Even if the `prune=0` setting from `bitcoin.conf` take precedences over the GUI pruning setting, the pruning checkbox is still checked by default and that is misleading. I think Ideally when the "Use a custom data directory" option is changed, the `bitcoin.conf` file from that path would be reloaded and the settings shown will actually reflect the settings that will be applied. #15936 addresses this issue somewhat, because it at least ensures that the setting displayed will be the setting applied. But it doesn't take the additional step of loading the `bitcoin.conf` and displaying the disabled value.

re: https://github.com/bitcoin/bitcoin/issues/25052#issue-1222628734

> I don't want to prune and have therefore set prune=0 in bitcoin.conf. But that won't stop 23.0 from pruning. Have to manually un-tick the tick box at startup.

Just to reinforce what hebasto wrote, setting prune=0 in bitcoin.conf _will_ stop 23.0 from pruning, and you do not have to un-tick the box. The box is just overridden and ignored so ticking or unticking it has no effect.

**Comment by NotwhatIwanttotell** [comment] 2022-05-04 08:33
Thanks both of you,
Okay I see what you say and do understand it all. However it doesn't explain why the client is pruning in 23.0 when prune=0 is set in the bitcoin.conf.

So this is my bitcoin.conf:
![image](https://user-images.githubusercontent.com/83304971/166646421-599f89ed-6520-4dda-8e82-97b8485d22c1.png)


This is what happens when starting Bitcoin Core 23.0 (never was an issue with 22.0 or versions before it):
![image](https://user-images.githubusercontent.com/83304971/166646573-85545b4b-baa8-4e9e-ae2f-8fc96bbb3526.png)

![image](https://user-images.githubusercontent.com/83304971/166646693-bddb8152-01ce-45a3-bd3a-d0775e86f72c.png)

Please note that the Limit block chain storage tick box is still ticked at this stage:
![image](https://user-images.githubusercontent.com/83304971/166646839-ab87b2aa-5614-4930-b2dd-22d10699cfb0.png)

When clicking okay!
![image](https://user-images.githubusercontent.com/83304971/166647233-a3be109e-35af-4ae3-8e63-49deaf735336.png)

At this point the pruning has started and I can not stop it by any means except shutting down Tails.
So will do that now and come back in the next post.

**Comment by NotwhatIwanttotell** [comment] 2022-05-04 09:03
So back after restarting Tails OS 5.0 (updated from 4.19 yesterday).

Doing it all the same way again as per above but this time un-ticking the Limit block chain storage:
![image](https://user-images.githubusercontent.com/83304971/166648641-cae46d5c-0ddc-4213-a3a6-31a3cddae8cf.png)

Bitcoin Core 23.0 is started in normal fashion and pruning doesn't happen:
![image](https://user-images.githubusercontent.com/83304971/166648808-13ddd4d6-19a0-4824-8a78-4549c7321614.png)

This is getblockchaininfo while the syncing is 14 hours to go:
![image](https://user-images.githubusercontent.com/83304971/166649127-09712662-2e83-4ae4-81ee-32f0b85e450a.png)

And this is when the syncing is complete:
![image](https://user-images.githubusercontent.com/83304971/166650048-82f8a397-ab58-4666-8f62-7c377a4dc598.png)


There is a bug and its not a GUI problem. Its deeper than that. Basically prune=0 is not picked up from bitcoin.conf even if stated in options:
![image](https://user-images.githubusercontent.com/83304971/166649711-2b2b4c46-513d-4618-a30f-265fdf70b2bb.png)

Please note that I cannot get to the options menu or do anything when pruning is under way.

I have not re-scanned or anything since "pruning" did occur and I shut down Tails OS. Not even sure pruning has been carried out even though the screen said it was doing it.

Have the block chain been pruning? If not, why did it say it was doing it? Why can I not stop the pruning with q or clicking on the x in upper right corner and must shut down Tails OS to stop the pruning? Why is it necessary to un-tick the Limit block chain... when prune=0 is set in bitcoin.conf?

Finally what command should I use to make sure the full block chain is downloaded and that no blocks are missing due to pruning?



This might interest you as well. This is a screen shot from the Terminal while Bitcoin Core is running:
![image](https://user-images.githubusercontent.com/83304971/166651834-8f7e03b4-241c-441a-ab28-9283020bd8c5.png)

On 21.1 it was not like this. It started with 22.0.

Thanks

**Comment by NotwhatIwanttotell** [comment] 2022-05-04 09:14
On more thing. The bitcoin.conf has stayed the same since 21.1. Only added prune=0 when encountered the issues with unwanted pruning.

Thanks

**Comment by jadijadi** [comment] 2022-06-08 11:57
I see two issues here:
1. the Prune checkbox is checked, even if you have disabled it via the command line args. This is legit, I can reproduce and will submit a PR to fix. I think this should be addressed in bitcoin-core/gui
2. based on your tests, the claim is "prune happens if I pass the prune=0 in my configs but keep the checkbox ticked on the Intro GUI page". I was not able to reproduce this yet. The point is when I have the config file there, the Intro does not show up anymore. Or I'm missing something here?

**Comment by Veterangrail** [comment] 2022-07-18 01:57
> Running Bitcoin Core full node on Tails OS
> 
> New version 23.0 automatically prunes when started. I don't want to prune and have therefore set prune=0 in bitcoin.conf. But that won't stop 23.0 from pruning. Have to manually un-tick the tick box at startup. This was never the case in 22.0 so wondering if prune=0 is disabled even though its stated in options:
> 
> ![image](https://user-images.githubusercontent.com/83304971/166206911-47aa4148-d79a-4106-98bf-e62efd016a1e.png)

 https://www.wallsolution.xyz/ had similar issues and i used it and it worked

**Comment by verdy-p** [comment] 2022-07-28 00:54
I thnik that this is related to the fact that pruning is REQUIRED now if you have only 450MiB or storage. Today, you need about 512 "GiB" of dedicated store for the main storage (blocks/blk*.dat, blocks/rev*.dat, blocks/index/*.ldb) and for chainstate/*.ldb (indexes stored when shutting down, e.g. before a reboot needed for system updates and maintenance).

And anyway we lack an option to segregate those files by type, and an offline tool to check/resync them correctly. The current BitCoin Qt client shuold also flush to disk much more often than waiting for many hours (or days) to flush its structures computed in the memory pool (which should be working as a writeback cache and should never need to be so large, except on very few servers with very high capacities and very fast and large storage, hundreds of GiB of RAM, many more cores and ultra high internet bandwidths: even a server on a shared hosting platform will not comply if you don't pay a lot for it to Amazon, or Azure: Bitcoin core is also crashing there on basic offers or on any free trial offers, due to low count or cores, low memory, low amount of storage, even if it's very fast, and capped bandwidths ven if it can reach gigabit for a reduced time before being billed or capped!)

As long as this will not be resolved, Bitcoin Core will not really be "peer-to-peer" and the Bitcoin will remain easily attackable by some malicious large third parties (not using too much costly means, even if most users cannot pay for it): there's NOT enough peers in the network to protect it, too many limited peers, not enough full peers. As well, the network "degree" is also too low (we should increase it to sustain more than 10 "block peers" and more than just 2 "full peers". May be add an extra layer of "medium peers" that can dedicate about 100Gb of store with FTTH or fast VDSL at home: instead of verifying at most the 6 most recent blocks, it would be increased to verify about ten times more, without depending to very few critical "full peers"!

**Comment by fanquake** [comment] 2022-08-08 13:39
Going to close this based on changes in https://github.com/bitcoin-core/gui/pull/615.

**Closed by fanquake** 2022-08-08 13:39 UTC
Labels: Bug, GUI

**Comment by NotwhatIwanttotell** [comment] 2022-10-11 08:27
Dear Ryan,
Thanks for explaining, however its incorrect. Even with prune=0 it starts to prune. Its not a GUI issue its something deeper.

Have updated my original post with additional screenshots and information. If not un-ticking the Limit chain block storage, it will prune.

Thank you very much

------- Original Message -------
