### ISSUE TITLE
generate RPC call leaves reservekey in keypool

### ISSUE THREAD

**Issue by gavinandresen** [bitcoin/bitcoin#6268] opened 2015-06-10 19:15 UTC
A regression test I'm writing failed because I was using invalidateblock() and then re-generating another chain.

But I got an identical block hash, so the newly-generated block was immediately rejected.
I believe the root cause is the generate RPC call not calling reservekey.keepKey() to remove it from the keypool.

I'm opening this issue in case I missed some discussion when generate was implemented, and this is the intended behavior. Fixing it will slow down regression tests that call generate repeatedly (because new keys will be created instead of the same key being used repeatedly).

**Comment by jonasschnelli** [comment] 2015-06-10 19:33
Just checked and right: `generate` does not use `keepKey()`.
PR #5994 would fix this (next to decoupling wallet / miner). I'm also happy to write a standalone-fix for this issue if no one already started.

**Comment by laanwj** [comment] 2015-06-11 08:29
I think this was done on purpose, to avoid having to generate a new key for each block and thus speed up generation. @sipa do you remember?

**Comment by dexX7** [comment] 2015-06-13 23:56
If I'm not mistaken, then this was introduced by https://github.com/bitcoin/bitcoin/commit/18379875bf7dd91637e4a206db58cd0968b5d47f.

For me this was pretty confusing, because it has an impact on `"getnewaddress"`, and the "new" address may already have received mined coins. To reproduce in regtest mode, starting from scratch:
```shell
./src/bitcoin-cli "generate" 101
[
  # block hashes
]
./src/bitcoin-cli "listunspent"
[
  {
    "txid": "b148b7d13c3351875d070d0567855bce47fcc797b3504247c4fcd68d902523ab",
    "vout": 0,
    "address": "mu1ZwmfRH4HHowDrrjSTsqSfMKLBeZkn2a",
    "scriptPubKey": "2103ad57ff9cd560507938698630455ab926b070add217a3b30aead57cd578b935feac",
    "amount": 50.00000000,
    "confirmations": 101,
    "spendable": true
  }
]
./src/bitcoin-cli "getnewaddress"   # ... or "getrawchangeaddress"
mu1ZwmfRH4HHowDrrjSTsqSfMKLBeZkn2a  # the new address isn't empty, but has 50.0 BTC
```

Additional coins will be mined to that address, too, if `"generate"` is used again.

**Comment by sipa** [comment] 2015-06-14 12:03
Using the same key for multiple blocks was intentional afaik, not marking it as used at all is not. I'll have a look later.

**Comment by TheBlueMatt** [comment] 2015-06-15 08:28
Heh, I ran into this exact same bug the other day writing a unit test as well :). Anyway, yea, we should use the same key for multiple blocks since they won't be the same anyway, but we should be keeping the key, otherwise things break :).

**Comment by TheBlueMatt** [comment] 2015-06-15 08:28
(Also, I have a fix for this coming in the next frt pull, soon)

**Comment by TheBlueMatt** [comment] 2015-07-17 23:10
This was fixed in https://github.com/bitcoin/bitcoin/commit/5496253966abec287ea61a648cb518d14903f91f#diff-c2c990fee1c3381462640e80ae7db0d0L168

**Comment by laanwj** [comment] 2015-07-21 10:48
Thanks for noticing @TheBlueMatt

**Closed** 2015-07-21 10:48 UTC
Labels: RPC, Tests
