### ISSUE TITLE
Consider building with -flto

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#10616] opened 2017-06-16 22:16 UTC
GCC since version 4.5 has supporting LTO building. In this mode, compiling cpp files to object files does not emit the final assembly code yet, but an intermediate representation which is used to produce the assembly at link time. This allows the compiler to perform inter-module optimizations; most notably it permits inlining across module boundaries.

Advantages:
* Smaller binaries (code from headers does not get duplicated into multiple objects anymore).
* Faster code (more optimization opportunities)
* Lower build-time memory requirements

Downsides:
* Slower building
* Requires modern compilers
* Debugging sometimes gets harder
* Before GCC 4.8: double size object files

I believe we should consider producing release binaries created using LTO, if the compiler is sufficiently modern. It categorically removes the concern about whether code should go in header files or not (before, moving implementations to .h files would sometimes be needed for performance reasons - with LTO that is not a good reason anymore).

Opinions?

**Comment by luke-jr** [comment] 2017-06-16 22:24
I think using dynamic libraries would be better *unless* there's a significant performance improvement from LTO...

**Comment by gmaxwell** [comment] 2017-06-17 00:26
@luke-jr this more or less completely orthogonal from dynamic libraries.

**Comment by luke-jr** [comment] 2017-06-17 00:50
I was under the impression LTO was fundamentally incompatible with dynamic libraries, due to its optimisation methods?

**Comment by sipa** [comment] 2017-06-17 00:52
LTO code can statically or dynamically link non-LTO code.

**Comment by laanwj** [comment] 2017-06-29 12:28
Seems like a good idea to me.

Static/dynamc linking is orthogonal, although one option would be to build the depends with LTO as well, then with static linking the entire executable can be optimized by the linker, also calls crossing library boundaries. But I"m not sure this is worth the extra build time - the important dependencies from a performance point of view are secp256k1 and leveldb and those are already internal.

**Comment by gmaxwell** [comment] 2017-07-06 00:52
@theuni Is there anything special in the build scripts that would get in the way of this?

**Comment by theuni** [comment] 2017-07-06 17:03
@gmaxwell It depends on what the definition of LTO is here. As @laanwj said, taking this as far as possible, the dependencies can also be built with LTO, which ends in one final massive link. There were a few issues with that last I tried, most having to do with ODR violations (bdb and qt, iirc).

For just LTO'ing our own builds, I think it should just work if the compiler is capable.

We could start by adding an "--enable-lto" configure option and letting people take it for a spin.

**Comment by TheBlueMatt** [comment] 2017-07-06 17:12
Yes, we really should have a configure option, it would be so much easier than manually overriding all of the various wrappers that we have to do now. Still, I dont think we can enable this for a while, eg debian jessie still fails to build with LTO without manually compiling util.cpp without LTO (something to do with header-defined destructors being lost during link, specifically in boost::filesystem).

**Comment by laanwj** [comment] 2017-07-06 17:29
>  Still, I dont think we can enable this for a while, eg debian jessie still fails to build with LTO without manually compiling util.cpp without LTO

It should definitely not be enabled by default! Programs usually shouldn't add non-standard compilation flags by default unless necessary.

AFAIK the only thing being discussed here is whether to enable it for the gitian build, and thus the distributed executables.

**Comment by theuni** [comment] 2017-07-06 20:38
Well if we're going to do it for the Gitian builds, we want a trivial way to reproduce that outside of Gitian so that we're not surprised by any odd effects. So I think a configure option (which Gitian and maybe Travis) use, would be the way to go.

@laanwj I'm unsure from your last comment if you'd be opposed to that?

**Comment by laanwj** [comment] 2017-07-06 21:14
Yes configure option is a good idea of it is disabled by default like the
glibc compat option.

**Comment by sipa** [comment] 2017-07-16 21:57
Benchmarks show that at least for me (gcc 6.3, with otherwise normal build options), -flto significantly slows down IBD.

**Comment by laanwj** [comment] 2017-07-20 15:36
Slower?!? that's curious.

**Comment by eklitzke** [comment] 2018-03-10 07:14
My experience with -flto is that it's often broken on GCC 4.x, and it can confuse GDB (especially on older versions of GDB). I am against this unless there's a clearly demonstrated performance improvement.

**Comment by laanwj** [comment] 2018-03-10 12:46
>  I am against this unless there's a clearly demonstrated performance improvement.

I don't think it's possible to disagree with that. If there is no demonstrated performance improvement, why would one enable an optimization, just for extra fun untangling the assembly at debugging time? :-)

**Comment by MarcoFalke** [comment] 2018-06-24 18:49
Should this issue be kept open in light of the above comments? (no apparent improvement gains)

**Comment by laanwj** [comment] 2018-06-24 19:05
I think it's fine to close it. This might change with a newer or different compiler, but I don't think it warrants having an issue open.

**Closed by laanwj** 2018-06-24 19:05 UTC
Labels: Brainstorming, Build system

**Comment by practicalswift** [comment] 2018-09-20 15:06
Some LTO results in #14277.
