### ISSUE TITLE
Unclear error when starting Bitcoin Core (bug)

### ISSUE THREAD

**Issue by GSPP** [bitcoin/bitcoin#7249] opened 2015-12-23 14:51 UTC
I just received this error message when starting Bitcoin Core:

![drhytrjsrtj](https://cloud.githubusercontent.com/assets/12032350/11978490/42eb89f8-a98c-11e5-88ba-48739fea8638.PNG)

I think the bad error is a bug already so I want to report it.

How can I help diagnose this issue? Here's the tail of the `debug.log`:

2015-12-23 14:44:15 Bitcoin version v0.11.2 (2015-11-10 14:46:18 +0100)
2015-12-23 14:44:15 Using OpenSSL version OpenSSL 1.0.1k 8 Jan 2015
2015-12-23 14:44:15 Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2015-12-23 14:44:15 Default data directory C:\Users\x\AppData\Roaming\Bitcoin
2015-12-23 14:44:15 Using data directory C:\Users\x\AppData\Roaming\Bitcoin
2015-12-23 14:44:15 Using config file C:\Users\x\AppData\Roaming\Bitcoin\bitcoin.conf
2015-12-23 14:44:15 Using at most 125 connections (2048 file descriptors available)
2015-12-23 14:44:15 Using 4 threads for script verification
2015-12-23 14:44:16 Using wallet wallet.dat
2015-12-23 14:44:16 scheduler thread start
2015-12-23 14:44:16 init message: Verifying wallet...
2015-12-23 14:44:16 CDBEnv::Open: LogDir=C:\Users\x\AppData\Roaming\Bitcoin\database ErrorFile=C:\Users\x\AppData\Roaming\Bitcoin\db.log
2015-12-23 14:44:16 Failed to rename wallet.dat to wallet.1450881856.bak

A procmon.exe trace does not show any path with "bak" in it. It's like Bitcoin Core did not even access the file system when this error occurred.

**Comment by GSPP** [comment] 2015-12-23 14:56
This is Windows 10 x64. Running as Administrator does not help.

**Comment by jonasschnelli** [comment] 2015-12-23 16:14
Can you retest with the current master (compile or use a nightly build:https://bitcoin.jonasschnelli.ch/nightlybuilds/)?

**Comment by MarcoFalke** [comment] 2015-12-23 16:45
Are you trying to do a `-salvagewallet`? Otherwise, it appears your `wallet.dat` may be corrupted. Do you have backups?

**Comment by MarcoFalke** [comment] 2015-12-23 16:45
In any case, the error message should not be empty.

**Comment by MarcoFalke** [comment] 2015-12-23 17:58
Seems this is just a duplicate of #7247

**Comment by GSPP** [comment] 2015-12-23 18:17
I was not trying to salvage a wallet but it turns out the wallet file is all zeroes.

Looks like the following issues are present:

1. The message is not there
2. Nothing useful happens in case of a corrupted wallet. Probably this should be reported and the user asked to create a new one
3. The log has a misleading/false message ("Failed to rename wallet.dat to wallet.1450881856.bak"). Or, was this supposed to be done and failed? That also would be a bug.

**Comment by tulip0** [comment] 2015-12-24 05:53
![morespecific](https://cloud.githubusercontent.com/assets/15009664/11990236/bbbf1980-aa5e-11e5-84f4-1ac8518b7563.png)

Null wallet in master is fine, that should be fixed in 0.12 releases. 

How did you end up with a zeroed file?

**Comment by GSPP** [comment] 2015-12-24 11:02
Not sure. It was not important, though.

**Comment by louzada1** [comment] 2015-12-25 07:15
> Not sure. It was not important, though.
It would be good if you could identify how it happened, maybe some prevention code could be added.

**Comment by MarcoFalke** [comment] 2015-12-25 10:59
> It would be good if you could identify how it happened

This happens every time you load a  corrupt wallet with  0.11.2.

**Comment by louzada1** [comment] 2015-12-25 16:54
> This happens every time you load a corrupt wallet with 0.11.2.
i mean, how the wallet got corrupted?

**Comment by GSPP** [comment] 2015-12-25 18:17
I have no theory how that happened at the moment but I'll let you know.

**Comment by GSPP** [comment] 2016-01-22 18:24
A theory for how this could have happened: Maybe the wallet file was not flushed to disk and the VM that I ran this in was not cleanly shut down.

How is the wallet file written? If it is overwritten no guarantees can be made in case of power loss. This might result in a Frankenstein wallet with mixed data from the old and the new version of the file. Also, with NTFS and without WRITE_THROUGH writing a zeroes file might easily result.

**Comment by laanwj** [comment] 2016-02-16 11:58
> Null wallet in master is fine, that should be fixed in 0.12 releases.

Great. Closing, then.

> How is the wallet file written? If it is overwritten no guarantees can be made in case of power loss. 

There is the `ThreadFlushWalletDB` which periodically pokes BerkeleyDB to compact its write log into `wallet.dat`. If this gets interrupted at the wrong time it may result in a broken intermediate state.

Cannot say this enough: Always make backups of your wallet!

**Closed by laanwj** 2016-02-16 11:58 UTC
Labels: Wallet
