### ISSUE TITLE
Whitelisting outgoing connections

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#9923] opened 2017-03-05 15:51 UTC
I think it should be possible to optionally whitelist outgoing connections - specifically those that are explicitly created through connect, addnode.
Context: I regularly need to bypass this code in testing setups to be able to sync non-internet connected nodes: https://github.com/bitcoin/bitcoin/blob/master/src/net_processing.cpp#L1720

Also in the interest of symmetry I don't see why whitelisting would only apply to incoming connections.

**Comment by jnewbery** [comment] 2017-03-06 20:55
As it happens, I have a branch that allows nodes to be whitelisted through an RPC: https://github.com/jnewbery/bitcoin/tree/updatenode .

Context: the RPC is called updatenode so that it can be extended in future, eg to update the banscore for a node, or disconnect a node based on node id (at the moment, nodes can only be disconnected based on ip address).

I haven't written any testcases for this yet, but feel free to take it if it's helpful for your testing.

**Comment by laanwj** [comment] 2017-03-07 07:12
That seems useful in general.

I'm a little afraid that won't work for my use-case because of the race between toggling 'whitelist' to 1 and making the connection. The other side will immediately send a `getheaders`, which could get ignored if it's not in time (and IIRC it won't send any, ever again, after that).

**Comment by laanwj** [comment] 2017-03-07 08:13
Another option here would be to make the `-whitelist` netmask apply to outgoing connections as well. It seems straightforward but that may be an unexpected change of behavior.

**Comment by Sjors** [comment] 2019-08-06 10:32
Duplicate of #4565

**Closed** 2024-03-12 16:59 UTC
Labels: P2P
