### ISSUE TITLE
Cannot obtain a lock on data directory

### ISSUE THREAD

**Issue by fgc92** [bitcoin/bitcoin#11801] opened 2017-11-30 16:16 UTC
macOS 10.13.1
bitcoinCore 0.15.1 downloaded from bitcoin.org
Synology DSM 6.1.4-15217 Update 2

When I first start bitcoinCore , I select a folder on my Synology NAS.

When I validate, an error message pops up:
"Cannot brain a lock on data directory / Volumes/home. Bitcoin Core is probably already running. Operation not supported"

After I acknowledge by clicking on the OK button, the application closes. 

If I start the application again, the same error message appears without prompting me for a new folder. 
 
This is reproducible 100% of the time. 

The only error message I found was in /var/log/syslog:
iMac com.apple.xpc.launchd[1] (org.bitcoinfoundation.Bitcoin-Qt.22648[7797]): Service exited with abnormal code: 1

**Comment by laanwj** [comment] 2017-11-30 16:55
Seems a duplicate of #10787

**Comment by fgc92** [comment] 2017-11-30 18:39
I'm going to try [this solution](https://github.com/jimhashhq/bitcoin/blob/3c0377db483c50c5a9aecfc4684d6329951a1c7c/doc/file-partition.md) and will update this ticket.

**Comment by fgc92** [comment] 2017-11-30 19:11
It worked, but I had to do it a different way. Shall I create a new file specific for macOS ?

**Closed** 2017-12-07 22:29 UTC
