### ISSUE TITLE
Please split the `-msghand` thread into multiple threads.

### ISSUE THREAD

**Issue by ytrezq** [bitcoin/bitcoin#20547] opened 2020-12-02 17:32 UTC
It seems when using good storage that this thread act as bottleneck in a way that other threads are waiting completion from it a the cpu level when performing initial full node synchronisation.

As a result, Bitcoin is mostly single threaded in that case (the `-msghand` thread take 100% of a single core leaving other cores idle even on a core duo cpu).

This what currently prevents syncing a full node with `-txindex` in less than 1 hour.

**Comment by denis2342** [comment] 2021-04-21 04:58
I have the same problem on my four core machine. the msghand thread is running at 100% and not much else happens.

**Comment by fanquake** [comment] 2022-08-13 15:21
Closing for now given this is a general ask and not a bug.

**Closed by fanquake** 2022-08-13 15:21 UTC
Labels: Feature

**Comment by ytrezq** [comment] 2022-08-13 15:26
@fanquake no, this is a real performance issue as the database grow.
**Please remove this bottleneck**.

**Comment by 1440000bytes** [comment] 2022-08-13 15:59
@ytrezq more than 100 issues have been closed in last 2 weeks `is:issue is:closed sort:updated-desc` which includes some that were not resolved although I fail to see what would this improve.

You could comment in https://github.com/bitcoin/bitcoin/issues/25823 or everyone could consider issues have 2 tabs: [open](https://github.com/bitcoin/bitcoin/issues) (less important) and [closed but not resolved](https://github.com/bitcoin/bitcoin/issues?q=is%3Aissue+is%3Aclosed) (more important) and keep a track of all the issues.

**Comment by ytrezq** [comment] 2022-08-13 18:11
@1440000bytes because msghand is single threaded, parallelism is limited in a way more cores don t means faster.

But yes, if this should be closed, this should be done as uncompleted.
