### ISSUE TITLE
0.13.1 reported down after Internet reconnect

### ISSUE THREAD

**Issue by Real-Duke** [bitcoin/bitcoin#9056] opened 2016-11-01 08:20 UTC
### Describe the issue
There seems to be a bug if you have a disconnect from the internet.
Most of the german internet providers have an automatic 24h disconnect. Im running on 0.13.1 for three days now and after every reconnect it stucks with 8 connections and on bitnodes the node is showed open on check but on activation reported as down.
Restarting core solves the problem until the next reconnect.

### Machine specs:
- OS: Bananian
Banana PI M1

### Any extra information that might be useful in the debugging process.
I can provide the debug.log for help after working day is done

**Comment by joshafest** [comment] 2016-11-01 15:31
Can you gave debug.log , you can upload on Google drive.

**Comment by Real-Duke** [comment] 2016-11-01 17:10
Here is the debug.log
The disconnect/reconnect was at 2.39am in the log
https://drive.google.com/file/d/0B_Fj9N7chEgaQVJCSEVndGZWMTA/view?usp=sharing

**Comment by Real-Duke** [comment] 2016-11-01 17:38
Found one more thing!
The Problem seems to be the peers.dat
After round about 24h runtime it has a size of 2.333KB
I didn't delete the file before the last restart some minutes ago and now core stucks again with 8 connections and "down" on Bitnodes

Here is the actual debug.log:




2016-11-01 17:20:02 Bitcoin version v0.13.1
2016-11-01 17:20:02 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2016-11-01 17:20:03 Default data directory /root/.bitcoin
2016-11-01 17:20:03 Using data directory /hdd
2016-11-01 17:20:03 Using config file /hdd/bitcoin.conf
2016-11-01 17:20:03 Using at most 50 connections (1024 file descriptors available)
2016-11-01 17:20:03 Using 2 threads for script verification
2016-11-01 17:20:03 scheduler thread start
2016-11-01 17:20:03 HTTP: creating work queue of depth 16
2016-11-01 17:20:03 Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcuser for rpcauth auth generation.
2016-11-01 17:20:03 HTTP: starting 4 worker threads
2016-11-01 17:20:03 Bound to [::]:8333
2016-11-01 17:20:03 Bound to 0.0.0.0:8333
2016-11-01 17:20:03 Cache configuration:
2016-11-01 17:20:03 * Using 2.0MiB for block index database
2016-11-01 17:20:03 * Using 8.0MiB for chain state database
2016-11-01 17:20:03 * Using 290.0MiB for in-memory UTXO set
2016-11-01 17:20:03 init message: Loading block index...
2016-11-01 17:20:03 Opening LevelDB in /hdd/blocks/index
2016-11-01 17:20:04 Opened LevelDB successfully
2016-11-01 17:20:04 Using obfuscation key for /hdd/blocks/index: 0000000000000000
2016-11-01 17:20:04 Opening LevelDB in /hdd/chainstate
2016-11-01 17:20:26 Opened LevelDB successfully
2016-11-01 17:20:26 Using obfuscation key for /hdd/chainstate: dc59fd8c13db5ebb
2016-11-01 17:23:19 LoadBlockIndexDB: last block file = 668
2016-11-01 17:23:19 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=86, size=71647400, heights=436852...436937, time=2016-11-01...2016-11-01)
2016-11-01 17:23:19 Checking all blk files are present...
2016-11-01 17:23:21 LoadBlockIndexDB: transaction index disabled
2016-11-01 17:23:23 LoadBlockIndexDB: hashBestChain=0000000000000000025a02228a74611a02950af9df1bc86be9e540b82ed992dc height=436937 date=2016-11-01 17:11:49 progress=0.999997
2016-11-01 17:23:23 init message: Rewinding blocks...
2016-11-01 17:23:56 init message: Verifying blocks...
2016-11-01 17:23:56 Verifying last 6 blocks at level 3
2016-11-01 17:23:56 [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
2016-11-01 17:25:19 No coin database inconsistencies in last 7 blocks (16392 transactions)
2016-11-01 17:25:23  block index          319820ms
2016-11-01 17:25:23 No wallet support compiled in!
2016-11-01 17:25:23 mapBlockIndex.size() = 437278
2016-11-01 17:25:23 nBestHeight = 436937
2016-11-01 17:25:23 torcontrol thread start
2016-11-01 17:25:23 init message: Loading addresses...
2016-11-01 17:25:31 Loaded 35998 addresses from peers.dat  7819ms
2016-11-01 17:25:31 init message: Loading banlist...
2016-11-01 17:25:31 init message: Starting network threads...
2016-11-01 17:25:31 addcon thread start
2016-11-01 17:25:31 init message: Done loading
2016-11-01 17:25:31 dnsseed thread start
2016-11-01 17:25:31 net thread start
2016-11-01 17:25:31 msghand thread start
2016-11-01 17:25:31 opencon thread start
2016-11-01 17:25:31 ProcessMessages: advertising address 46.59.196.252:8333
2016-11-01 17:25:31 receive version message: /Satoshi:0.13.0/: version 70014, blocks=436937, us=46.59.196.252:35742, peer=1
2016-11-01 17:25:31 AdvertiseLocal: advertising address 46.59.196.252:8333
2016-11-01 17:25:39 connect() to 41.170.5.30:8333 failed after select(): No route to host (113)
2016-11-01 17:25:40 ProcessMessages: advertising address 46.59.196.252:8333
2016-11-01 17:25:40 receive version message: /Satoshi:0.13.1/: version 70014, blocks=436937, us=46.59.196.252:51020, peer=2
2016-11-01 17:25:40 AdvertiseLocal: advertising address 46.59.196.252:8333
2016-11-01 17:25:41 ProcessMessages: advertising address 46.59.196.252:8333
2016-11-01 17:25:41 receive version message: /Satoshi:0.13.1/: version 70014, blocks=436937, us=46.59.196.252:35558, peer=3
2016-11-01 17:25:41 AdvertiseLocal: advertising address 46.59.196.252:8333
2016-11-01 17:25:41 ProcessMessages: advertising address 46.59.196.252:8333
2016-11-01 17:25:41 receive version message: /Satoshi:0.13.1/: version 70014, blocks=436937, us=46.59.196.252:53317, peer=4
2016-11-01 17:25:41 AdvertiseLocal: advertising address 46.59.196.252:8333
2016-11-01 17:25:42 ProcessMessages: advertising address 46.59.196.252:8333
2016-11-01 17:25:42 receive version message: /Satoshi:0.13.1/: version 70014, blocks=436937, us=46.59.196.252:36812, peer=5
2016-11-01 17:25:42 AdvertiseLocal: advertising address 46.59.196.252:8333
2016-11-01 17:25:42 P2P peers available. Skipped DNS seeding.
2016-11-01 17:25:42 dnsseed thread exit
2016-11-01 17:25:43 ProcessMessages: advertising address 46.59.196.252:8333
2016-11-01 17:25:43 receive version message: /Satoshi:0.13.1/: version 70014, blocks=436937, us=46.59.196.252:33369, peer=6
2016-11-01 17:25:43 AdvertiseLocal: advertising address 46.59.196.252:8333
2016-11-01 17:25:45 ProcessMessages: advertising address 46.59.196.252:8333
2016-11-01 17:25:45 receive version message: /Satoshi:0.13.1/: version 70014, blocks=436937, us=46.59.196.252:51060, peer=7
2016-11-01 17:25:45 AdvertiseLocal: advertising address 46.59.196.252:8333
2016-11-01 17:25:46 ProcessMessages: advertising address 46.59.196.252:8333
2016-11-01 17:25:46 receive version message: /Satoshi:0.13.1/Knots:20161027/: version 70014, blocks=436937, us=46.59.196.252:45250, peer=8
2016-11-01 17:25:46 AdvertiseLocal: advertising address 46.59.196.252:8333
2016-11-01 17:26:08 ProcessMessages: advertising address 46.59.196.252:8333
2016-11-01 17:26:08 receive version message: /Satoshi:0.13.1/: version 70014, blocks=436937, us=46.59.196.252:43785, peer=10
2016-11-01 17:26:08 AdvertiseLocal: advertising address 46.59.196.252:8333
2016-11-01 17:26:42 receive version message: /bitnodes.21.co:0.1/: version 70002, blocks=0, us=46.59.196.252:8333, peer=11
2016-11-01 17:26:42 AdvertiseLocal: advertising address 46.59.196.252:8333
2016-11-01 17:26:47 connect() to 99.240.229.161:8333 failed after select(): Connection refused (111)
2016-11-01 17:27:31 UpdateTip: new best=000000000000000003f2931efaa940f3664e4510099d509042fb1ed2a2973d1d height=436938 version=0x20000000 log2_work=85.486213 tx=167306651 date='2016-11-01 17:26:11' progress=1.000000 cache=11.9MiB(6243tx) warning='2 of last 100 blocks have unexpected version'
2016-11-01 17:27:32 connect() to [2001:14ba:7f8:9700::]:8333 failed: Network is unreachable (101)
2016-11-01 17:27:34 ProcessMessages: advertising address 46.59.196.252:8333
2016-11-01 17:27:34 receive version message: /Satoshi:0.13.1/: version 70014, blocks=436939, us=46.59.196.252:39528, peer=12
2016-11-01 17:27:34 AdvertiseLocal: advertising address 46.59.196.252:8333
2016-11-01 17:28:29 UpdateTip: new best=0000000000000000003a3f00c885cf5120a5ea025358c6ba507e8ffc16c5236f height=436939 version=0x20000000 log2_work=85.486242 tx=167308591 date='2016-11-01 17:26:41' progress=0.999999 cache=19.3MiB(11911tx) warning='2 of last 100 blocks have unexpected version'
2016-11-01 17:28:51 ProcessMessages: advertising address 46.59.196.252:8333
2016-11-01 17:28:51 receive version message: /Satoshi:0.13.1/: version 70014, blocks=436939, us=46.59.196.252:40723, peer=13
2016-11-01 17:28:51 AdvertiseLocal: advertising address 46.59.196.252:8333
2016-11-01 17:28:51 socket send error Bad file descriptor (9)
2016-11-01 17:30:35 receive version message: /bitnodes.21.co:0.1/: version 70002, blocks=436939, us=46.59.196.252:8333, peer=14
2016-11-01 17:30:35 AdvertiseLocal: advertising address 46.59.196.252:8333
2016-11-01 17:31:47 connect() to [2001:0:9d38:90d7:2c21:e29:e7fb:34bc]:8333 failed: Network is unreachable (101)
2016-11-01 17:33:21 receive version message: /bitnodes.21.co:0.1/: version 70002, blocks=0, us=46.59.196.252:8333, peer=15
2016-11-01 17:33:21 AdvertiseLocal: advertising address 46.59.196.252:8333

**Comment by Real-Duke** [comment] 2016-11-02 09:25
Update
Tonight after the reconnect my node seems to be down again with 8 connections. Now 6 hours later I check manually on bitnodes my node and after activating "Node Status" my connections start to grow from 8 to 21 within 15min! 
Something else I notice yesterday evening, after ~24 hours my peer.dat has a size of 2.333KB
Is it possible that the node "lost" all peers after a disconnect and use the dns-seed only if I do a fresh restart with deleted peers.dat?

**Comment by fanquake** [comment] 2016-11-11 11:21
Closing this as I'm not exactly sure what the issue is. The default max number of outbound connections is [8](https://github.com/bitcoin/bitcoin/blob/master/src/net.h#L59), so having 8 connection is perfectly fine.

**Closed by fanquake** 2016-11-11 11:21 UTC
Labels: P2P
