### ISSUE TITLE
test_bitcoin hangs in test case "manythreads"

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#6711] opened 2015-09-22 14:25 UTC
I think this sometimes happens in travis. I can reproduce locally as follows:

```
$ for i in {0..1000}; do echo "Test run: $i"; src/test/test_bitcoin --log_level=ALL --run_test=scheduler_tests;done
```

Output:

```
[...]
Test run: 7
Running 1 test case...
Entering test suite "Bitcoin Test Suite"
Entering test suite "scheduler_tests"
Entering test case "manythreads"
test/scheduler_tests.cpp(70): info: check nTasks == 0 passed
test/scheduler_tests.cpp(82): info: check nTasks == 100 passed
test/scheduler_tests.cpp(83): info: check first < last passed
test/scheduler_tests.cpp(84): info: check last > now passed
test/scheduler_tests.cpp(113): info: check counter[i] != 0 passed
test/scheduler_tests.cpp(113): info: check counter[i] != 0 passed
test/scheduler_tests.cpp(113): info: check counter[i] != 0 passed
test/scheduler_tests.cpp(113): info: check counter[i] != 0 passed
test/scheduler_tests.cpp(113): info: check counter[i] != 0 passed
test/scheduler_tests.cpp(113): info: check counter[i] != 0 passed
test/scheduler_tests.cpp(113): info: check counter[i] != 0 passed
test/scheduler_tests.cpp(113): info: check counter[i] != 0 passed
test/scheduler_tests.cpp(113): info: check counter[i] != 0 passed
test/scheduler_tests.cpp(113): info: check counter[i] != 0 passed
test/scheduler_tests.cpp(116): info: check counterSum == 200 passed
Leaving test case "manythreads"; testing time: 4653mks
Leaving test suite "scheduler_tests"
Leaving test suite "Bitcoin Test Suite"

*** No errors detected
Test run: 8
Running 1 test case...
Entering test suite "Bitcoin Test Suite"
Entering test suite "scheduler_tests"
Entering test case "manythreads"
test/scheduler_tests.cpp(70): info: check nTasks == 0 passed
test/scheduler_tests.cpp(82): info: check nTasks == 100 passed
test/scheduler_tests.cpp(83): info: check first < last passed
test/scheduler_tests.cpp(84): info: check last > now passed
^C

```

**Comment by laanwj** [comment] 2015-09-22 17:49
Unfortunately, this is a known issue.
Duplicate of #6540

**Closed by laanwj** 2015-09-22 17:49 UTC
