### ISSUE TITLE
./contrib/guix/guix-build does not work on riscv64

### ISSUE THREAD

**Issue by maflcko** [bitcoin/bitcoin#29020] opened 2023-12-07 10:35 UTC
Steps to reproduce:

```
# dpkg --print-architecture && HOSTS="arm64-apple-darwin" V=1 VERBOSE=1 MAX_JOBS=$(nproc) ./contrib/guix/guix-build 
riscv64
Found macOS SDK at '/bitcoin-core/depends/SDKs/Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers', using...
Checking that we can connect to the guix-daemon...

Hint: If this hangs, you may want to try turning your guix-daemon off and on
      again.

accepted connection from pid 2870003, user root
make: Entering directory '/bitcoin-core/depends'
make[1]: Entering directory '/bitcoin-core/depends'
make[1]: Leaving directory '/bitcoin-core/depends'
make: Leaving directory '/bitcoin-core/depends'
INFO: Building 92d12f1c8903 for platform triple arm64-apple-darwin:
      ...using reference timestamp: 1696409041
      ...running at most 4 jobs
      ...from worktree directory: '/bitcoin-core'
          ...bind-mounted in container to: '/bitcoin'
      ...in build directory: '/bitcoin-core/guix-build-92d12f1c8903/distsrc-92d12f1c8903-arm64-apple-darwin'
          ...bind-mounted in container to: '/distsrc-base/distsrc-92d12f1c8903-arm64-apple-darwin'
      ...outputting in: '/bitcoin-core/guix-build-92d12f1c8903/output/arm64-apple-darwin'
          ...bind-mounted in container to: '/outdir-base/arm64-apple-darwin'
accepted connection from pid 2872281, user root
accepted connection from pid 2872281, user root
Backtrace:
          18 (primitive-load "/root/.cache/guix/inferiors/4wrulds2lx?")
In guix/ui.scm:
   2324:7 17 (run-guix . _)
  2287:10 16 (run-guix-command _ . _)
In ice-9/boot-9.scm:
  1752:10 15 (with-exception-handler _ _ #:unwind? _ # _)
In guix/store.scm:
    672:3 14 (guix-environment* _)
In ice-9/boot-9.scm:
  1752:10 13 (with-exception-handler _ _ #:unwind? _ # _)
In guix/store.scm:
   659:37 12 (thunk)
   1298:8 11 (call-with-build-handler _ _)
   1298:8 10 (call-with-build-handler #<procedure 3f812c0ea0 at gui?> ?)
In guix/status.scm:
    839:4  9 (call-with-status-report _ _)
In guix/scripts/environment.scm:
  1158:11  8 (_)
In guix/store.scm:
  2168:25  7 (run-with-store #<store-connection 256.99 3f851f2af0> _ ?)
In guix/scripts/environment.scm:
    869:8  6 (_ _)
In gnu/build/linux-container.scm:
   397:16  5 (call-with-container (#<<file-system> device: "none?> ?) ?)
   239:15  4 (run-container "/tmp/guix-directory.GcTuOV" (#<<fil?> ?) ?)
In guix/build/syscalls.scm:
  1114:21  3 (_ 2114060305)
In unknown file:
Exception thrown while printing backtrace:
In procedure primitive-call-ip: Wrong type argument in position 1 (expecting PRIMITIVE_P): #<procedure 3f82490420 (_ _ _ _ _ _)>

ice-9/boot-9.scm:1685:16: In procedure raise-exception:
Wrong type (expecting exact integer): #f
```

**Comment by fanquake** [comment] 2023-12-07 10:38
Is it only the apple cross-compiles that aren't working, or all builds? I assume it's only the apple cross-compiles given that is what is being shown here.

> guix itself seems to be working:

What is the Guix version?

**Comment by fanquake** [comment] 2023-12-07 11:10
> The guix version is 1.4, but that shouldn't matter, because of the time-machine.

I'm not sure we should make that assumption here. If the version of Guix (1.4), can't properly setup containers on the system (which looks like it could be the issue), and the fixes only landed after 1.4, then builds will still fail. It would be good to get a smaller reproducer of the issue. Does something like `guix shell --container --pure some_package` work?

**Comment by fanquake** [comment] 2023-12-07 11:23
>  then there is a bug in the time-machine, which seems unlikely.

I don't follow. This is failing in the same way, because time-machine is trying to use a container. So it is the same issue.

**Comment by fanquake** [comment] 2023-12-07 11:27
> I could simply use the time-machine to run that version of guix

You can't though. Because the guix binary itself, that is trying to run the container, for the time-machine, doesn't have the bug fixes from the future.

**Comment by fanquake** [comment] 2023-12-07 11:57
Ok, so then this seems to be a bug with just the usage `--container`, (on riscv64 hardware?) that likely still exists in Guix. We should report the minimal reproducer upstream.

**Comment by fanquake** [comment] 2023-12-12 14:25
> https://debbugs.gnu.org/cgi/bugreport.cgi?bug=67697

Apparently the fix has now landed, but I don't yet see it in https://git.savannah.gnu.org/cgit/guix.git/log/ (or core-updates).

**Comment by fanquake** [comment] 2023-12-13 15:10
Guess it's time to guix pull and find the next bug.

**Closed** 2023-12-18 12:54 UTC
Labels: Build system
