### ISSUE TITLE
v0.11.0 - Activating best chain... - kill -9

### ISSUE THREAD

**Issue by isghe** [bitcoin/bitcoin#6459] opened 2015-07-18 19:33 UTC
After starting from command line bitocoind, it can require minutes to have bitocoind to be real responsive, for example:
`$ ./bitcoin-cli stop`
`error: {"code":-28,"message":"Activating best chain..."}`

In such situation, I had sometimes to "kill -9" bitcoind to stop it.
I would like to be able to stop bitcoind in clean way.

p.s.:
`$ uname -a`
`Darwin isghe.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64`

**Comment by sime** [comment] 2015-07-19 13:56
I too have just experienced this, though my node is pruned as well.

**Comment by laanwj** [comment] 2015-07-21 09:31
#5851 is related

**Comment by laanwj** [comment] 2016-02-09 16:05
Closing as duplicate of #7038

**Closed by laanwj** 2016-02-09 16:05 UTC
Labels: Validation
