### ISSUE TITLE
Inconsistent RPC error handling

### ISSUE THREAD

**Issue by Kixunil** [bitcoin/bitcoin#19087] opened 2020-05-28 07:18 UTC
**Expected behavior**

The behavior of returning error from RPC call should be consistent between these cases:

* Single RPC call fails
* Single forbidden RPC call
* Batched failed RPC call
* One (or more) method of the batched call is forbidden

**Actual behavior**

* Single failed RPC call returns HTTP error code
* Single forbidden RPC call returns HTTP error code - `HTTP_FORBIDDEN` (`403`)
* Batched failed RPC call [leaks](https://github.com/bitcoin/bitcoin/blob/25ad2c623af30056ffb36dcd203a52edda2b170f/src/httprpc.cpp#L79) an [internal error code](https://github.com/bitcoin/bitcoin/blob/99813a9745fe10a58bedd7a4cb721faf14f907a4/src/rpc/protocol.h#L29)
* [Batched call](https://github.com/bitcoin/bitcoin/blob/25ad2c623af30056ffb36dcd203a52edda2b170f/src/httprpc.cpp#L213) containing a forbidden method [returns](https://github.com/bitcoin/bitcoin/blob/25ad2c623af30056ffb36dcd203a52edda2b170f/src/httprpc.cpp#L224) `HTTP_FORBIDDEN` (`403`) for the whole batch.

**To reproduce**

Disclaimer: the bug was discovered by code analysis when trying to come up with a correct solution to https://github.com/MetacoSA/NBitcoin/issues/864 I'm fairly confident that using `curl` to call methods and then observing output would reproduce the issue.

Another way to see a problem might be running BTCPayServer/NBXplorer with the bitcoind version from master with some users restricted. (Example: restrict `getpeerinfo` and see that Payjoin stops working.) I didn't try this with newest Core, but I hit it with [btc-rpc-proxy](https://github.com/Kixunil/btc-rpc-proxy), which returns HTTP errors for authentication just like what `bitcoind` does according to the code.

**System information**

Not relevant.

**Discussion**

I'm opening this issue in order to decide on proper handling of RPC errors. I see these possible approaches:

* `RPC_METHOD_NOT_FOUND` becomes public, [the comment](https://github.com/bitcoin/bitcoin/blob/99813a9745fe10a58bedd7a4cb721faf14f907a4/src/rpc/protocol.h#L29) is removed and the rest of the code stays the same, the behavior doesn't change.
* [`JSONErrorReply`](https://github.com/bitcoin/bitcoin/blob/99813a9745fe10a58bedd7a4cb721faf14f907a4/src/rpc/protocol.h#L29) function is modified to return HTTP errors for batched calls too.
* New public error codes are defined and used for every method independently, the mapping to HTTP codes is removed (at least for batched calls)

I personally like the last one because it allows efficient inspection of node capabilities, but I'm worried that it might break some clients. I'd love to hear arguments from people who are more experienced in this area.

**Comment by NicolasDorier** [comment] 2020-05-28 15:16
I think the current behavior should be kept: If any or all of the batched request fails, the batch result should still be HTTP 200. This was the behavior before.

On top of this, it seems that if you do batched requests and one of the request is denied, then the caller will not receive ANY of the other results.

**Comment by Kixunil** [comment] 2020-05-28 17:49
Yeah, keeping a bit strange behavior is backwards compatible. Changing authentication to return errors individually would help with batched requests - this shouldn't be a backwards-compatibility hazard, as no code probably uses unreleased API yet.

In case that this is the accepted solution, the comment about internal error code should be removed and the value should become public.

**Comment by NicolasDorier** [comment] 2020-05-28 23:57
ping @JeremyRubin

**Comment by JeremyRubin** [comment] 2020-05-29 03:37
I don't have an opinion here sorry for breaking compat. I think that we should change batching to scan if any are not whitelisted and reject the whole batch.

**Comment by Kixunil** [comment] 2020-05-29 13:09
> we should change batching to scan if any are not whitelisted and reject the whole batch

You mean change that behavior to something else? Because that's the current behavior.

**Comment by JeremyRubin** [comment] 2020-05-30 08:16
It sounds like in the current behavior some RPCs are running in the batch and some are failing and that hides the output. I think that we should pre-scan before running any

**Comment by Kixunil** [comment] 2020-05-30 18:41
So pre-scan missing methods too?

**Comment by JeremyRubin** [comment] 2020-05-30 18:47
Yeah I think so. If there are missing methods or non-whitelisted methods it sounds like failing the whole batch is a bit of a better API.

The behavior of the whitelists is such that it should be roughly identical to what happens if the RPC doesn't exist at all.

**Comment by Kixunil** [comment] 2020-05-31 09:12
Why exactly do you consider it a better API? FYI, it'd break NBitcoin.

> The behavior of the whitelists is such that it should be roughly identical to what happens if the RPC doesn't exist at all.

I agree with this.

**Comment by JeremyRubin** [comment] 2020-05-31 18:57
How would it break NBitcoin? Does NBitcoin send missing methods in a batch?

**Comment by Kixunil** [comment] 2020-06-01 14:11
Yes, it sends various methods in batch, some of which are missing and then detects the features based on the responses. Making it return 404 would make it think none of the methods is available. It could be changed to not batch, but that'd lead to a (small?) loss of performance.

**Comment by JeremyRubin** [comment] 2020-06-01 16:44
Ok, the right thing to do is to to add a feature detection RPC rather than guess by firing RPCs off and seeing what fails (RPCs may not be 'safe' or wise to call).

Mind reviewing https://github.com/bitcoin/bitcoin/pull/19117?

**Comment by Kixunil** [comment] 2020-06-05 07:58
I agree that official feature detection would be better. I wonder how NBitcoin will cope with the complexity:

* Versions before 0.20 can't disable calls (except if using [`btc-rpc-proxy`](https://github.com/Kixunil/btc-rpc-proxy))
* 0.20 can disable calls, but can't list them
* 0.20 + epsilon may be able to list them but block all of them

It seems to me that if @NicolasDorier wants to keep his sanity, he'll probably have to remove batching during detection. But maybe it's not too bad? Try to get the list first and if it returns RPC method not found, then unbatched (slower) discovery continues. If it returns success, then the information is available and no further calls are needed. The policy could become "if you need fast discovery, use bitcoind >0.20". What do you think Nicolas?

**Comment by NicolasDorier** [comment] 2020-08-09 04:22
The only way to work around this problem is to try batching first, then fallback to sending requests one by one if 403 is sent.

This however is dangerous if the RPC requests are not idempotent, as some requests could be executed twice. (once in the failing batch, and one in the retry) for scanning, this is fine.

**Comment by NicolasDorier** [comment] 2020-08-09 04:57
btw, the only way to fix this problem cleanly is to have a dedicated RPC code for forbidden exception instead of relying on HTTP status code. And keep using HTTP 200.

That way people can see which RPC request failed in the lot.

**Comment by Kixunil** [comment] 2020-08-09 05:35
> This however is dangerous if the RPC requests are not idempotent, as some requests could be executed twice.

Not really because the requests are scanned before they are executed so either all of them fail all of them are executed. Both in Bitcoin Core and my proxy. Therefore error 403 is fine. It'd only be a problem if someone wrote their own RPC proxy with different behavior (which is their bug).

**Comment by JeremyRubin** [comment] 2020-08-09 05:59
https://github.com/bitcoin/bitcoin/pull/12763/files#diff-744201ccb403526a4b5bf52d6e5367deR216-R219

Oh, I thought it was a worse issue than it is! Yes, the code rejects the entire batch if any are not permitted. This is by design; if you have a random failure in the middle of your batch that would be potentially bad. It's better to reject the whole batch if the user is trying *any* unpermitted action.

How many RPCs do you actually need to detect? Maybe what I'd suggest is structuring your test-packet as:

Test Packet 1: All Mandatory RPCs
Test Packet 2: All Optional RPCs
If 2 fails: Test RPCs one-by-one

**Comment by Kixunil** [comment] 2020-08-09 06:33
> If 2 fails: Test RPCs one-by-one

That's exactly what he did recently. :)

You have a good point about failing the whole batch. I guess that's better than (likely negligible) performance issues of scanning. Scanning RPCs should probably be done with a special method anyway.

So what do you think about publishing `RPC_METHOD_NOT_FOUND`?

**Comment by JeremyRubin** [comment] 2020-08-09 17:12
That should be fine to do. It might be nice to differentiate RPC_METHOD_NOT_FOUND and RPC_METHOD_NOT_ALLOWED. Right now the code does not make a distinction, but you could make RPC_METHOD_NOT_ALLOWED be the error as the precheck, and RPC_METHOD_NOT_FOUND as the one once you try to run it and it's not there (but may also be nice to make that a pre-checked thing IMO)

**Comment by pinheadmz** [comment] 2023-03-27 14:34
The inconsistencies between single / batch RPCs are addressed in https://github.com/bitcoin/bitcoin/pull/27101 which adds a stricter jsonrpc 2.0 behavior when requested by the client (by adding `"jsonrpc": "2.0"` to the request object). In particular, we try to always return `HTTP 200 OK` unless there actually is a server error.

That PR does not affect the whitelist / authorization processing which looks like, in this discussion, is decidedly  acceptable. 

@Kixunil and @JeremyRubin are you able to review and feed back on #27101 ? We might be able to close this issue as duplicate of https://github.com/bitcoin/bitcoin/issues/2960

**Comment by willcl-ark** [comment] 2024-10-14 15:18
Going to close since #27101 was merged.

Please open a new issue if there is something outstanding.

**Closed by willcl-ark** 2024-10-14 15:18 UTC
Labels: Bug, RPC/REST/ZMQ
