### ISSUE TITLE
send BTC is very slow with huge wallet

### ISSUE THREAD

**Issue by JokerCatz** [bitcoin/bitcoin#7475] opened 2016-02-06 17:12 UTC
my wallet.dat size : 358M
and debug.log

```
2016-02-06 17:03:09 keypool added key 54799, size=301
2016-02-06 17:03:09 keypool reserve 54499
2016-02-06 17:03:19 CommitTransaction:
CTransaction(hash=3dc010c216, ver=1, vin.size=1, vout.size=2, nLockTime=397048)
    CTxIn(COutPoint(5fc29785f4, 41), scriptSig={{hash}}, nSequence=4294967294)
    CTxOut(nValue=3.37993552, scriptPubKey=OP_DUP OP_HASH160 {{hash}})
    CTxOut(nValue=0.68241470, scriptPubKey=OP_DUP OP_HASH160 {{hash}})
2016-02-06 17:03:19 keypool keep 54499
2016-02-06 17:03:19 AddToWallet {{hash}}  new
2016-02-06 17:03:19 AddToWallet {{hash}}
2016-02-06 17:03:19 Relaying wtx {{hash}}
2016-02-06 17:03:37 keypool added key 54800, size=301
2016-02-06 17:03:37 keypool reserve 54500
2016-02-06 17:03:47 CommitTransaction:
    CTransaction(hash={{hash}}, ver=1, vin.size=1, vout.size=2, nLockTime=397048)
    CTxIn(COutPoint({{hash}}, 1), scriptSig={{hash}}, nSequence=4294967294)
    CTxOut(nValue=6.11253197, scriptPubKey=OP_DUP OP_HASH160 {{hash}})
    CTxOut(nValue=0.61373803, scriptPubKey=OP_DUP OP_HASH160 {{hash}})
```

I need more fast to send BTC(now 1 send be ~30sec) , but...I don't know how to fix it

the CUP usage always 100%+ , and my bitcoin.conf

```
upnp=0
maxconnections = 128
server=1
rpcthreads=8
rpckeepalive=false
rpctimeout=30
rpcallowip=127.0.0.1
rpcport=8332
keypool=300
paytxfee=0.0001
```

and getinfo

```
{
"version" : 110200,
"protocolversion" : 70002,
"walletversion" : 60000,
"balance" : {{skip}},
"blocks" : 397059,
"timeoffset" : -14,
"connections" : 14,
"proxy" : "",
"difficulty" : 120033340651.23696899,
"testnet" : false,
"keypoololdest" : 1454771625,
"keypoolsize" : 301,
"paytxfee" : 0.00010000,
"relayfee" : 0.00005000,
"errors" : ""
}
```

please help me to fix it....many thanx...

**Comment by MarcoFalke** [comment] 2016-02-06 17:55
Unless you get an exact match, the coin selection algorithm will iterate over the whole unspent coin set at least once.

You can get the size of the coin set with `$ src/bitcoin-cli  listunspent 0 | grep -c spendable`. Also, you can `grep ` for the `amount` and see if there is a bunch of small coins.

Could you share the output of `$ src/bitcoin-cli  listunspent 0 | grep -c spendable`? (Make sure you don't post any amounts or txids to the public if you care about privacy)

**Comment by JokerCatz** [comment] 2016-02-06 18:14
$ bitcoin-cli listunspent 0 | grep -c spendable
412

**Comment by MarcoFalke** [comment] 2016-02-07 23:03
Iterating over 412 coins is done in less than a second. This sounds more like #2511

You can add the `-debug=db` option to see how long it takes to flush the wallet.

```
2016-02-07 23:00:17 Flushing wallet.dat
2016-02-07 23:00:17 Flushed wallet.dat 8ms

**Comment by JokerCatz** [comment] 2016-02-08 04:07
2016-02-08 03:52:41 Flushing wallet.dat
    2016-02-08 03:52:50 Flushed wallet.dat 9252ms

... 7xxx ~ 93xx ms
and another logs

    2016-02-08 03:58:40 AddToWallet {{hash}}  new
    2016-02-08 03:58:42 Flushing wallet.dat
    2016-02-08 03:58:50 Flushed wallet.dat 7960ms
    2016-02-08 03:59:30 keypool added key 57748, size=301
    2016-02-08 03:59:30 keypool reserve 57448
    2016-02-08 03:59:32 Flushing wallet.dat
    2016-02-08 03:59:40 Flushed wallet.dat 7964ms
    ...

and

    bitcoin-cli listunspent 0 | grep -c spendable
    534

okay...so? how to fix this? like change to non-BDB ? or just loading balance add more node ? I think I can use docker to loading balance it ... (NFS share old blk00xxx.dat to save hd space , all node keep last 2 blk00xxx.dat file , and export / import wallet to another node......)

**Comment by MarcoFalke** [comment] 2016-02-08 12:23
> how to fix this?

* You could switch to a SSD (replacing your HDD) to reduce the time of a flush to about one second
* You could generate a new wallet if you don't reuse your addresses:

The steps could be roughly like this:

```
ADD=getnewaddress
sendtoadderess $ADD $balance
KEY=dumpprivkey $ADD
[stop node]
mv wallet.dat wallet.dat_2016_02_08
[restart node]
importprivkey $KEY

**Comment by JokerCatz** [comment] 2016-02-08 17:27
I know how to export and import keys , but customer use our wallet solution & has (user <=> wallet) relation in DB , so I can't change/cancel customer wallet , so I will make more node to loading balance it (export / import wallets to 2+ nodes) & split receive and sender wallet be different node , daily transfer receive node BTCs to sender node , I think will be okay for this (( and sorry my poor english...:x , and Happy Chinese New Year , Dev team : )

**Comment by pstratem** [comment] 2016-02-08 19:48
@JokerCatz are you using the "account" functions?

Note that they are deprecated and will be removed in a future release.

**Comment by JokerCatz** [comment] 2016-02-09 14:03
^ you mean `bitcoin-cli` like `sendfrom` or like `listaccounts` , the "account" command will be remove?
& we use JSON-RPC to call node command...

**Comment by pstratem** [comment] 2016-02-10 04:13
@JokerCatz https://github.com/bitcoin/bitcoin/pull/5575

**Comment by JokerCatz** [comment] 2016-02-10 09:05
okay~ I got it , thanx : )

**Comment by GamerSg** [comment] 2016-02-27 07:17
@JokerCatz I previously encountered the same issue.
What i did was dump all needed private keys to a text file, create new wallet, import needed private keys, rescan. 

This got rid of a ton of change addresses.

**Comment by sipa** [comment] 2016-02-27 07:25
I wonder if, for wallets with very large numbers of UTXOs, we can't just
take a random subset of them to fund with...

**Comment by MarcoFalke** [comment] 2016-02-27 08:39
@sipa I think this issue is more about the delay caused by flushing the wallet after using a change address for creating the transaction and less about the performance of the coin selection code.

**Comment by JokerCatz** [comment] 2016-02-27 08:50
yep , I dump and import all customer address private key ...... wallet.dat from 480 MB change to 12 MB ,  and very fast to send BTC now :)

but I miss some txid between old and new node (old can be find) , but it's okay , just report my env and many thanx dev team : )

**Comment by Jsying** [comment] 2016-06-03 17:37
Flushing wallet take a long time when the wallet is large.
It seems like BerkeIeyDB lsn_reset function will rewrite the whole `wallet.dat`.
I wonder why we need to call `dbenv->lsn_reset(strFile.c_str(), 0);` in `ThreadFlushWalletDB`.
Is there any concern?
Why not call `lsn_reset` when shutting down bitcoind or reduce the frenquency.

**Comment by pstratem** [comment] 2016-06-03 17:48
@Jsying I'm working on significantly improving the wallet performance, but it's going to take some time.

**Comment by GSPP** [comment] 2016-06-03 19:20
Rewriting the entire wallet *certainly* is not crash consistent. I really doubt a database engine would do such a thing.

You can use procmon on Windows to see what exactly is being written.

**Comment by sipa** [comment] 2016-06-03 19:21
I think @pstratem is working on this.

**Comment by Jsying** [comment] 2016-06-05 10:06
@GSPP 
I have used strace to see the write_bytes before and after flushing db (lsn_reset) and It's seems like it really rewrite the whole wallet.dat
According to BDB docs:
> Because database pages contain references to the database environment log records (LSNs), databases cannot be copied or moved from one transactional database environment to another without first clearing the LSNs. Note that this is not a concern for non-transactional database environments and applications, and can be ignored if the database is not being used transactionally.

and the comment `// Flush wallet file so it's self contained` https://github.com/bitcoin/bitcoin/blob/master/src/wallet/walletdb.cpp#L893

I guess lsn_reset will rewrite the whole wallet.dat so that it can be moved to other environment.
But I curious why so frequently...

@pstratem @sipa 
Thanks. I am not going to duplicate your works. I just observe the phenomenon and very curious about the reason...

**Comment by gmaxwell** [comment] 2016-07-14 01:51
@pstratem Can you confirm you thing you fixed this?

**Comment by pstratem** [comment] 2016-07-14 03:51
@gmaxwell 
I've been working my way towards improving wallet performance in general.

Unfortunately to do so safely requires a number of re-factors on the way the wallet accesses the database.

These have been merged:
https://github.com/bitcoin/bitcoin/pull/8137
https://github.com/bitcoin/bitcoin/pull/8142

Waiting for this one before doing the final pass:
https://github.com/bitcoin/bitcoin/pull/8152

**Comment by denravonska** [comment] 2018-03-09 13:26
Is there a reason why `lsn_reset` was called inside `CDBEnv::CheckpointLSN`? It increases the risk window in case of a crash and calling it while flushing manually (IE not via the old flush thread) when exiting should be enough, no?

**Comment by BrannonKing** [comment] 2019-12-26 17:12
@pstratem , #8152 has been merged. Can this be closed?

**Comment by Aimeelu668** [comment] 2020-04-09 14:55
自己开发的钱包都是热钱包机制，节点同步慢，归集非常麻烦，最重要的是这些私钥存在服务器上很危险，天天被黑客盯着。当时我们平台有50多万会员，为了解决钱包问题折腾了一年，最终放弃了，选择了优盾钱包 https://www.uduncloud.com  。通过API直接接入就行，有独立客户端操作审核、归集等，私钥也是自己在客户端上管理，服务器上不存。用了快一年，没有出现安全问题，财务都反馈说体验很好。我们也终于可以专注于业务开发了。推荐试试

**Comment by jonathanliles487455** [comment] 2021-01-29 09:31
I've been working my way towards improving wallet performance in general.

Unfortunately to do so safely requires a number of re-factors on the way the wallet accesses the database.

**Comment by willcl-ark** [comment] 2022-11-23 11:28
I wonder if this is another issue which should be closed as the BDB wallet is unlikely to see this periodic flushing performance issue patched now that we have [sqlite wallets](https://github.com/bitcoin/bitcoin/pull/19077) as default wallet type moving forward?

**Comment by MarcoFalke** [comment] 2022-11-23 11:34
Closing per previous comment and  https://github.com/bitcoin/bitcoin/pull/18904#issuecomment-1276702310

**Closed by MarcoFalke** 2022-11-23 11:34 UTC
Labels: Wallet, Resource usage
