### ISSUE TITLE
Docs: testnet onion seeds are outdated

### ISSUE THREAD

**Issue by ghost** [bitcoin/bitcoin#13550] opened 2018-06-27 17:04 UTC
`contrib/seeds/nodes_test.txt` seems to be completely outdated.

I get not one outgoing onion connection using the following `bitcoin.conf` in which the testnet onion nodes are added with `addnode=` option (assuming Tor listening on `127.0.0.1:9050`):
```
testnet=1
onion=127.0.0.1:9050
listen=1
discover=1
onlynet=onion
# contrib/seeds/nodes_test.txt
addnode=thfsmmn2jbitcoin.onion
addnode=it2pj4f7657g3rhi.onion
addnode=nkf5e6b7pl4jfd4a.onion
addnode=4zhkir2ofl7orfom.onion
addnode=t6xj6wilh4ytvcs7.onion
addnode=i6y6ivorwakd7nw3.onion
addnode=ubqj4rsu3nqtxmtp.onion
```

**Comment by wodry** [comment] 2018-07-04 03:58
With the following command one gets the testnet onion seed node list from Bitnodes:
`dig +short txt testnet-seed.bitnodes.io | tr --delete '"'`
I tried with these in bitcoin.conf, instead the ones in contrib/seeds/nodes_test.txt.
```
addnode=ocasutxnvl4lwegq.onion
addnode=cu6octp6yo754wda.onion
addnode=lkiggf5esgs7d5z6.onion
addnode=rhcv7q2quqn74zlr.onion
addnode=nq7cak6pufzs2ou2.onion
addnode=nec4kn4ghql7p7an.onion
addnode=qlllezfaif5cscnx.onion
addnode=zmtr2di735ngxpcl.onion
addnode=4syvownyxejvqbzn.onion
```
But in the first ten minutes no connection. Then unexpected (in the mean time I did something other) one connection to `nkf5e6b7pl4jfd4a.onion`, which had not been added in bitcoin.conf but is listed in contrib/seeds/nodes_test.txt. At least that one is up.

**Comment by Sjors** [comment] 2019-05-15 14:02
See also #15791. I recently configured my DNS seed to crawl onion nodes. Here's the dump: [](url)
[dnsseed.dump.gz](https://github.com/bitcoin/bitcoin/files/3182825/dnsseed.dump.gz)

There's only 120 that are marked as "good", and the 30 day uptime is abysmal. It suggests onion nodes move quite often?

<details>
 <summary>Expand list</summary>
```
# address                                        good  lastSuccess    %(2h)   %(8h)   %(1d)   %(7d)  %(30d)  blocks      svcs  version
nwky3wd3ihoidvb5.onion:8333                         1   1555532203   98.82%  67.08%  36.10%  28.50%  10.12%  572069  0000040d  70015 "/Satoshi:0.17.1/"
ydscw35avlov5j7h.onion:8333                         1   1555033295   98.62%  68.66%  32.59%   5.52%   1.32%  571267  0000040d  70015 "/Satoshi:0.17.1/"
5skhwiwyqdmex273.onion:8333                         1   1555534684   98.87%  67.36%  31.27%   5.42%   1.31%  572071  0000040d  70015 "/Satoshi:0.17.0.1/"
4kth2vosmtfjb57r.onion:8333                         1   1556104103   89.37%  56.08%  26.02%   5.18%   1.30%  573014  0000040d  70015 "/Satoshi:0.17.1/"
yipvf7na66z5u3bw.onion:8333                         1   1555054775   98.63%  67.56%  31.64%   5.32%   1.27%  571296  0000040d  70015 "/Satoshi:0.17.1/"
xhmice6ajwwcwfij.onion:8333                         1   1555037582   98.91%  67.67%  31.36%   5.23%   1.25%  571270  0000040d  70015 "/Satoshi:0.17.1/"
uzdt3ddmyxebukyy.onion:8333                         1   1555034337   98.50%  66.94%  31.15%   5.22%   1.24%  571267  0000040d  70015 "/Satoshi:0.17.1/"
onlzo775ogdpjn5x.onion:8333                         1   1555036855   98.89%  67.56%  31.29%   5.22%   1.24%  571268  0000040d  70015 "/Satoshi:0.16.0/"
dvu6dlar6ezc6xen.onion:8333                         1   1555036877   98.89%  67.56%  31.29%   5.22%   1.24%  571268  0000040d  70015 "/Satoshi:0.17.1/"
2zgnfq3c7devw2ec.onion:8333                         1   1555036641   98.72%  67.23%  31.20%   5.21%   1.24%  571268  0000040d  70015 "/Satoshi:0.17.0.1/"
j2ehpso7ngkscjrm.onion:8333                         1   1555036824   98.89%  67.52%  31.26%   5.21%   1.24%  571268  0000040d  70015 "/Satoshi:0.17.1(UASF-SegWit-BIP148)/"
i4x66albngo3sg3w.onion:8333                         1   1555036965   98.89%  67.51%  31.25%   5.21%   1.24%  571268  0000040d  70015 "/Satoshi:0.17.1/"
yuebvwxr3fwgty55.onion:8333                         1   1555037553   98.88%  67.49%  31.24%   5.21%   1.24%  571270  0000040d  70015 "/Satoshi:0.17.1/"
2zdgmicx7obtivug.onion:8333                         1   1555036216   98.70%  67.12%  31.12%   5.20%   1.24%  571268  0000040d  70015 "/Satoshi:0.17.1/"
gfvnnnwcddfzosav.onion:8333                         1   1555037433   98.87%  67.40%  31.18%   5.20%   1.24%  571270  0000040d  70015 "/Satoshi:0.17.1/"
qftnpmsxn2xqikmg.onion:8333                         1   1555037494   98.87%  67.40%  31.18%   5.20%   1.24%  571270  0000040d  70015 "/Satoshi:0.17.1/"
ezjy6vcbldavkgg6.onion:8333                         1   1555036685   98.87%  67.40%  31.17%   5.20%   1.24%  571268  0000040d  70015 "/Satoshi:0.17.0.1/"
jlfkhuearld6kfvu.onion:8333                         1   1555036730   98.87%  67.40%  31.17%   5.20%   1.24%  571268  0000040d  70015 "/Satoshi:0.17.1/"
tftjfuyjr3au3zpq.onion:8333                         1   1555036710   98.87%  67.39%  31.17%   5.20%   1.24%  571268  0000040d  70015 "/Satoshi:0.17.1/"
vuia3j4jnqtd6ng5.onion:8333                         1   1555036218   98.71%  67.10%  31.10%   5.19%   1.24%  571268  0000040d  70015 "/Satoshi:0.17.1/"
ff4z4lurl5it6246.onion:8333                         1   1555037496   98.87%  67.37%  31.15%   5.19%   1.24%  571270  0000040d  70015 "/Satoshi:0.16.3/"
h6bg73bqlybfrvyq.onion:8333                         1   1555036351   98.68%  67.04%  31.08%   5.19%   1.24%  571268  0000040d  70015 "/Satoshi:0.17.1/"
fno4aakpl6sg6y47.onion:8333                         1   1555036353   98.70%  67.06%  31.07%   5.19%   1.24%  571268  0000040d  70015 "/Satoshi:0.17.0/"
4rnzfqkmoqi7so6c.onion:8333                         1   1555037694   98.86%  67.34%  31.14%   5.19%   1.24%  571270  0000040d  70015 "/Satoshi:0.17.1/"
ap4zz4imxbdl6plr.onion:8333                         1   1555037509   98.86%  67.34%  31.13%   5.19%   1.24%  571270  0000040d  70015 "/Satoshi:0.17.0/"
c5aourpwazvoxrqd.onion:8333                         1   1555036219   98.70%  67.04%  31.06%   5.19%   1.24%  571268  0000000d  70015 "/Satoshi:0.13.2/"
lcu6fkg27ubzrssj.onion:8333                         1   1555037284   98.86%  67.33%  31.13%   5.19%   1.24%  571270  0000040d  70015 "/Satoshi:0.17.1/"
godfxzfs63mwxdfn.onion:8333                         1   1555037554   98.86%  67.32%  31.12%   5.19%   1.23%  571270  0000040d  70015 "/Satoshi:0.17.1/"
fwnq4qmhuwgh2kdf.onion:8333                         1   1555036319   98.70%  67.02%  31.05%   5.18%   1.23%  571268  0000040d  70015 "/Satoshi:0.17.1/"
lpwixhkj46pg6jky.onion:8333                         1   1555036379   98.69%  67.01%  31.04%   5.18%   1.23%  571268  0000040d  70015 "/Satoshi:0.17.1/"
j7jji2z35b3enrab.onion:8333                         1   1555036433   98.69%  67.01%  31.04%   5.18%   1.23%  571268  0000040d  70015 "/Satoshi:0.17.1(my-bitcoin-node)/"
bk7yp6epnmcllq72.onion:8333                         1   1555036677   98.68%  66.98%  31.03%   5.18%   1.23%  571268  0000040d  70015 "/Satoshi:0.17.1(BTC)/"
4iogxfitcp55kafm.onion:8333                         1   1555036634   98.68%  66.98%  31.03%   5.18%   1.23%  571268  0000040d  70015 "/Satoshi:0.17.1/"
pe3ctc5oirnkb7hy.onion:8333                         1   1555036224   98.68%  66.98%  31.02%   5.18%   1.23%  571268  0000040d  70015 "/Satoshi:0.17.1/"
kmorzrtgbqrc6oat.onion:8333                         1   1555036500   98.67%  66.95%  31.01%   5.18%   1.23%  571268  0000040d  70015 "/Satoshi:0.17.1/"
ihfgsiuulcnbuzy2.onion:8333                         1   1555036591   98.68%  66.96%  31.01%   5.18%   1.23%  571268  0000040d  70015 "/Satoshi:0.17.0.1/"
oxciy3larfnnqvsa.onion:8333                         1   1555036525   98.68%  66.96%  31.01%   5.18%   1.23%  571268  0000000d  70015 "/Satoshi:0.15.0.1/"
zzwepx6slqzm6ndq.onion:8333                         1   1555037392   98.85%  67.26%  31.08%   5.18%   1.23%  571270  0000040d  70015 "/Satoshi:0.17.0.1/"
trevzf6wmdptyqfs.onion:8333                         1   1555037573   98.85%  67.26%  31.08%   5.18%   1.23%  571270  0000040d  70015 "/Satoshi:0.17.0.1/"
w4yimpywyhue75ww.onion:8333                         1   1555036415   98.68%  66.96%  31.00%   5.18%   1.23%  571268  0000040d  70015 "/Satoshi:0.17.1/"
xu47bf37wttxnxd5.onion:8333                         1   1555036583   98.67%  66.92%  30.99%   5.17%   1.23%  571268  0000040d  70015 "/Satoshi:0.17.1/"
27et4tn3kmxim7lf.onion:8333                         1   1555036435   98.67%  66.90%  30.97%   5.17%   1.23%  571268  0000040d  70015 "/Satoshi:0.16.3/"
2qudbhlnvqpli3sz.onion:8333                         1   1555037303   98.84%  67.17%  31.01%   5.17%   1.23%  571270  0000040d  70015 "/Satoshi:0.18.0/"
vhdoxqq63xr53ol7.onion:8333                         1   1555036351   98.67%  66.87%  30.95%   5.16%   1.23%  571268  0800040d  70015 "/Satoshi:0.17.1/Knots:20181229/"
iy2jghv2paznxuor.onion:8333                         1   1555036548   98.66%  66.85%  30.93%   5.16%   1.23%  571268  0000040d  70015 "/Satoshi:0.17.0.1/"
uzbrujjemdvsyqxz.onion:8333                         1   1555036197   98.66%  66.84%  30.92%   5.16%   1.23%  571268  0000040d  70015 "/Satoshi:0.17.1/"
eaxjuhvexjomn3pv.onion:8333                         1   1555036527   98.66%  66.83%  30.92%   5.16%   1.23%  571268  0000040d  70015 "/Satoshi:0.17.1/"
g3xgqirastjhpsn6.onion:8333                         1   1555036573   98.66%  66.79%  30.89%   5.15%   1.23%  571268  0000040d  70015 "/Satoshi:0.16.2/"
fscb2bbkargtesw7.onion:8333                         1   1555033907   98.13%  65.64%  30.56%   5.13%   1.22%  571267  0000040d  70015 "/Satoshi:0.17.1/"
rcmaeequa3tmtwxm.onion:8333                         1   1555036516   98.64%  66.67%  30.80%   5.14%   1.22%  571268  0000040d  70015 "/Satoshi:0.17.1/"
2cg5rn5ke5sf4gye.onion:8333                         1   1555033712   98.14%  65.62%  30.52%   5.12%   1.22%  571267  0000040d  70015 "/Satoshi:0.17.1/"
ep2mjzox3kvb6ax4.onion:8333                         1   1555034224   98.17%  65.58%  30.49%   5.11%   1.22%  571267  0000040d  70015 "/Satoshi:0.16.3/"
dklandizmv6vaq7x.onion:8333                         1   1555033527   98.15%  65.60%  30.49%   5.11%   1.22%  571267  0000000d  70015 "/Satoshi:0.15.2/"
6r3sudkqzpc2o44n.onion:8333                         1   1555033960   98.11%  65.49%  30.45%   5.11%   1.22%  571267  0000040d  70015 "/Satoshi:0.17.0.1/"
jtnyfhltcd5smcap.onion:8333                         1   1555033590   98.15%  65.57%  30.47%   5.11%   1.22%  571267  0000040d  70015 "/Satoshi:0.17.0.1/"
al35fqhuabzkbxfm.onion:8333                         1   1555033263   98.18%  65.60%  30.46%   5.10%   1.22%  571267  0000040d  70015 "/Satoshi:0.17.1/"
tzcr2zenmwb4zhla.onion:8333                         1   1555033327   98.16%  65.54%  30.44%   5.10%   1.22%  571267  0000040d  70015 "/Satoshi:0.17.1/"
uftbw4zi5wlzcwho.onion:8333                         1   1555033429   98.15%  65.51%  30.41%   5.10%   1.21%  571267  0000040d  70015 "/Satoshi:0.17.0/"
4glotrrcfhsch3uu.onion:8333                         1   1555033231   98.16%  65.50%  30.39%   5.09%   1.21%  571267  0000040d  70015 "/Satoshi:0.17.1/"
plnw7dfsj5giflll.onion:8333                         1   1555033384   98.14%  65.41%  30.34%   5.08%   1.21%  571267  0000040d  70015 "/Satoshi:0.17.1/"
e43o4jwihcucf2ts.onion:8333                         1   1555032945   98.52%  65.95%  30.31%   5.04%   1.20%  571265  0000040d  70015 "/Satoshi:0.17.1/"
2vggzxkut5ab4ddf.onion:8333                         1   1555035672   97.95%  64.68%  29.98%   5.03%   1.20%  571268  0000040d  70015 "/Satoshi:0.17.1/"
fgbss353vsvandn7.onion:8333                         1   1555030100   98.67%  66.04%  30.23%   5.01%   1.19%  571260  0000040d  70015 "/Satoshi:0.16.3/"
u7evgt3w7yr3fmvn.onion:8333                         1   1555030445   98.65%  65.93%  30.16%   5.00%   1.19%  571261  0000040d  70015 "/Satoshi:0.17.0.1/"
lvqv5nehy7q472kl.onion:8333                         1   1555030479   98.64%  65.88%  30.12%   4.99%   1.19%  571261  0000040d  70015 "/Satoshi:0.18.99(Medea)/"
5qdxswcgigxilqin.onion:8333                         1   1555030503   98.64%  65.87%  30.12%   4.99%   1.19%  571261  0000040d  70015 "/Satoshi:0.17.0/"
5nir6d6nd5bolrkv.onion:8333                         1   1555032726   98.64%  65.86%  30.11%   4.99%   1.19%  571265  0800042d  70015 "/Satoshi:0.16.3/"
sza5dkccqm5egqgq.onion:8333                         1   1555030365   98.63%  65.78%  30.05%   4.98%   1.18%  571261  0000040d  70015 "/Satoshi:0.17.1/"
57acrug2miefbr2r.onion:8333                         1   1555032039   98.61%  65.65%  29.97%   4.96%   1.18%  571263  0000040d  70015 "/Satoshi:0.17.1/"
zsenp64lsvvdroig.onion:8333                         1   1555032319   98.60%  65.63%  29.95%   4.96%   1.18%  571263  0000040d  70015 "/Satoshi:0.17.0.1/"
uaai3tsown6v3f3v.onion:8333                         1   1555032277   98.59%  65.55%  29.90%   4.95%   1.18%  571263  0000040d  70015 "/Satoshi:0.17.1/"
pg2jeh62fkq3byps.onion:8333                         1   1555233636   98.59%  65.53%  29.88%   4.94%   1.18%  571590  0000040d  70015 "/Satoshi:0.17.1/"
ghuegyqyc7sbmt6l.onion:8333                         1   1555032594   98.40%  65.23%  29.81%   4.94%   1.18%  571264  0000040d  70015 "/Satoshi:0.16.2/"
cqoenl4w6r3pcz5c.onion:8333                         1   1555032889   98.39%  65.21%  29.80%   4.94%   1.18%  571266  0000040d  70015 "/Satoshi:0.17.0/"
5lnynttfbehexe6b.onion:8333                         1   1555032356   98.58%  65.46%  29.84%   4.94%   1.17%  571263  0000040d  70015 "/Satoshi:0.17.1/"
lgkvbvro67jomosw.onion:8333                         1   1555032298   98.56%  65.38%  29.78%   4.93%   1.17%  571263  0000040d  70015 "/Satoshi:0.17.0/"
f6kzyiyaasb5ae6t.onion:8333                         1   1555032157   98.56%  65.36%  29.77%   4.92%   1.17%  571263  0000040d  70015 "/Satoshi:0.17.1/"
5wnkqzjzjehmq7hn.onion:8333                         1   1555032856   98.36%  65.06%  29.70%   4.92%   1.17%  571266  0000040d  70015 "/Satoshi:0.17.0/"
j5jfrdthqt5g25xz.onion:8333                         1   1555032531   98.37%  65.07%  29.70%   4.92%   1.17%  571264  0000040d  70015 "/Satoshi:0.17.99/"
xbr267gnzmybwguk.onion:8333                         1   1555032370   98.36%  65.03%  29.67%   4.92%   1.17%  571263  0000040d  70015 "/Satoshi:0.17.0.1/"
t4fbovvgzpnimd2p.onion:8333                         1   1555032507   98.34%  65.00%  29.66%   4.91%   1.17%  571263  0000040d  70015 "/Satoshi:0.17.1/"
vomeacttinx3mpml.onion:8333                         1   1555032129   98.55%  65.29%  29.72%   4.91%   1.17%  571263  0000049d  70015 "/Satoshi:0.17.1/"
ckdcaofvfv73dja5.onion:8333                         1   1555032553   98.35%  64.99%  29.65%   4.91%   1.17%  571264  0000040d  70015 "/Satoshi:0.17.0.1/"
gripl5xjwy2dcr6c.onion:8333                         1   1555032713   98.35%  64.98%  29.65%   4.91%   1.17%  571265  0000040d  70015 "/Satoshi:0.17.1/"
n73steqcmjz5hwni.onion:8333                         1   1555032391   98.35%  64.99%  29.65%   4.91%   1.17%  571263  0000040d  70015 "/Satoshi:0.18.0/"
5m55grwuuggp5jrb.onion:8333                         1   1555032472   98.35%  64.99%  29.65%   4.91%   1.17%  571263  0000040d  70015 "/Satoshi:0.17.1/"
w25o5aow4gt2lufk.onion:8333                         1   1555032366   98.35%  64.98%  29.64%   4.91%   1.17%  571263  0000040d  70015 "/Satoshi:0.17.1/"
7a744wgfanb6i425.onion:8333                         1   1555032715   98.33%  64.91%  29.60%   4.90%   1.17%  571265  0000040d  70015 "/Satoshi:0.17.0.1/"
o2tku2dbsd6iumch.onion:8333                         1   1555032193   98.53%  65.21%  29.67%   4.90%   1.17%  571263  0000040d  70015 "/Satoshi:0.17.0/"
epwl4h7uukxhkank.onion:8333                         1   1555032322   98.34%  64.91%  29.59%   4.90%   1.17%  571263  0000040d  70015 "/Satoshi:0.17.0.1/"
5jyfzhwksb6urrp2.onion:8333                         1   1555032505   98.34%  64.91%  29.59%   4.90%   1.17%  571263  0000040d  70015 "/Satoshi:0.17.1/"
vlf5i3grro3wux24.onion:8333                         1   1555032465   98.34%  64.89%  29.58%   4.90%   1.16%  571263  0000040d  70015 "/Satoshi:0.16.3/"
oecairbqdj2rkoov.onion:8333                         1   1555032449   98.33%  64.87%  29.57%   4.89%   1.16%  571263  0000040d  70015 "/Satoshi:0.17.1/"
6ymgbvnn6d5nfmv4.onion:8333                         1   1555036216   98.47%  64.83%  29.41%   4.85%   1.15%  571268  0800000d  70015 "/Satoshi:0.14.2/UASF-Segwit:1.0(BIP148)/"
bdkqtnjhjtjmvdch.onion:8333                         1   1555028908   97.48%  63.52%  29.09%   4.84%   1.15%  571257  0000048d  70015 "/Satoshi:0.17.1(14xJWEEGAx88)/"
stejqfcoqi47kjzb.onion:8333                         1   1555036496   98.44%  64.68%  29.32%   4.84%   1.15%  571268  0000040d  70015 "/Satoshi:0.17.0.1/"
ezkr7stq4w7ohjrt.onion:8333                         1   1555034355   98.20%  64.32%  29.22%   4.83%   1.15%  571267  0000040d  70015 "/Satoshi:0.17.1/"
f3mtmawnshqczdeb.onion:8333                         1   1555036481   98.43%  64.62%  29.27%   4.83%   1.15%  571268  0000000d  70015 "/Satoshi:0.15.1/"
kedn3x6peubcwlqm.onion:8333                         1   1555035375   98.42%  64.54%  29.22%   4.82%   1.15%  571267  0000040d  70015 "/Satoshi:0.17.99/"
r7fnzfv3on6pzfr4.onion:8333                         1   1555035870   98.41%  64.50%  29.19%   4.81%   1.14%  571268  0000040d  70015 "/Satoshi:0.17.0.1/"
7u3dlwlrnz4fr2f6.onion:8333                         1   1555036011   98.41%  64.47%  29.17%   4.81%   1.14%  571268  0000040d  70015 "/Satoshi:0.17.0.1/"
pwa4uc7qfhbbxbdl.onion:8333                         1   1555036068   98.40%  64.43%  29.15%   4.80%   1.14%  571268  0000040d  70015 "/Satoshi:0.17.1/"
jkdzluvkxl5o4uhs.onion:8333                         1   1555036363   98.39%  64.40%  29.13%   4.80%   1.14%  571268  0000040d  70015 "/Satoshi:0.17.1/Knots:20181229/"
n237rnuu734cldk2.onion:8333                         1   1555036104   98.39%  64.39%  29.12%   4.80%   1.14%  571268  0000040d  70015 "/Satoshi:0.17.1(This-is-my-node-and-I-choose-what-is-bitcoin)/"
2inspd2pqalt5cfi.onion:8333                         1   1555035620   98.39%  64.39%  29.12%   4.80%   1.14%  571268  0000040d  70015 "/Satoshi:0.17.0.1/"
2bfsxzluysybysnr.onion:8333                         1   1555035956   98.39%  64.36%  29.10%   4.79%   1.14%  571268  0000040d  70015 "/Satoshi:0.17.1/"
erv2hf4dslr7sfa5.onion:8333                         1   1555035898   98.38%  64.34%  29.09%   4.79%   1.14%  571268  0000040d  70015 "/Satoshi:0.17.0.1/"
cowghyhicrgn5szh.onion:8333                         1   1555036063   98.38%  64.34%  29.09%   4.79%   1.14%  571268  0000040d  70015 "/Satoshi:0.17.0.1(; )/"
226eupdnaouu4h2v.onion:8333                         1   1555035928   98.38%  64.32%  29.08%   4.79%   1.14%  571268  0000040d  70015 "/Satoshi:0.16.2/"
74k54a55qbo2t34y.onion:8333                         1   1555035752   98.38%  64.31%  29.07%   4.79%   1.14%  571268  0000000d  70015 "/Satoshi:0.15.1/"
qpwocpl77ksa5ozs.onion:8333                         1   1555035718   98.38%  64.31%  29.06%   4.79%   1.14%  571268  0000000d  70015 "/Satoshi:0.13.2/"
kkdas3qebkosygu5.onion:8333                         1   1555036004   98.38%  64.30%  29.06%   4.79%   1.14%  571268  0000040d  70015 "/Satoshi:0.18.0/"
ba4vmd2seysfkfsz.onion:8333                         1   1555036391   98.37%  64.29%  29.06%   4.79%   1.14%  571268  0000040d  70015 "/Satoshi:0.17.1/"
n4m32zcp5hvomkt4.onion:8333                         1   1555036070   98.37%  64.29%  29.05%   4.78%   1.14%  571268  0000040d  70015 "/Satoshi:0.17.1/"
hwo2biyndrrvpl6f.onion:8333                         1   1555036105   98.37%  64.26%  29.03%   4.78%   1.14%  571268  0000040d  70015 "/Satoshi:0.17.1/"
ble7kgm3gim6e5si.onion:8333                         1   1555035899   98.33%  64.04%  28.89%   4.75%   1.13%  571268  0000040d  70015 "/Satoshi:0.17.0.1/"
6fp3i7f2pbie7w7t.onion:8333                         1   1555055086   95.03%  58.65%  27.52%   4.71%   1.13%  571296  0800040d  70015 "/Satoshi:0.17.0/"
7rr4gwgh3cuq2srm.onion:8333                         1   1555033501   97.91%  61.97%  27.55%   4.50%   1.07%  571267  0000040d  70015 "/Satoshi:0.17.1/"
alhlegtjkdmbqsvt.onion:8333                         1   1555026818   96.55%  60.61%  27.27%   4.49%   1.07%  571256  0000040d  70015 "/Satoshi:0.17.1/"
y5majqt7ihgzo7aw.onion:8333                         1   1555032563   93.87%  55.97%  24.86%   4.08%   0.97%  571264  0000040d  70015 "/Satoshi:0.17.1/"
```
</details>

cc @laanwj @Emzy

**Comment by Sjors** [comment] 2019-05-15 14:07
The above is mainnet. Is there much point in trying to update testnet given the above?

**Comment by pinheadmz** [comment] 2020-03-12 15:23
Of the 7 onion URLs hard-coded in https://github.com/bitcoin/bitcoin/blob/master/contrib/seeds/nodes_test.txt, only one address is responsive at this time: `nkf5e6b7pl4jfd4a.onion:18333`

To reproduce:

1. `bitcoind -testnet -debug=1 -proxy=127.0.0.1:9050 -onlynet=onion`

2. For each in `nodes_test.txt`:
`bitcoin-cli -testnet addnode <....onion> add`

3. `cat .../debug.log | grep "SOCKS5 connected"`

I also recompiled with the testnet DNS seeds in `chainparams.cpp` removed to force bitcoind to use the hard-coded seeds list before manually double checking with `addnode`

Is there a reason why the only hard-coded testnet seeds are these 7 onion URLs?

**Comment by MarcoFalke** [comment] 2022-08-11 15:20
The feature request didn't seem to attract much attention in the past. Also, the issue seems not important enough right now to keep it sitting around idle in the list of open issues.

Closing due to lack of interest. Pull requests with improvements are always welcome.

**Closed by MarcoFalke** 2022-08-11 15:20 UTC
Labels: Docs, P2P

**Comment by jonatack** [comment] 2022-08-11 15:37
Those Tor v2 testnet seeds were all updated in May 2021 to Tor v3 ones in https://github.com/bitcoin/bitcoin/pull/22060 (I may have a look at how many of them are up currently).

**Comment by jonatack** [comment] 2022-08-15 13:27
Updated in #25853.
