### ISSUE TITLE
estimateSmartFee error: "Insufficient data or no feerate found"

### ISSUE THREAD

**Issue by ella-quicknode** [bitcoin/bitcoin#31116] opened 2024-10-19 11:00 UTC
I am seeing a couple of issues been raised in the past. We currently experiencing the same issue.  The work around was to delete `fee_estimate.dat` and `mempool.dat` from the node. 

With regards to the below comment from issue 19150 (_Originally posted by @maflcko in https://github.com/bitcoin/bitcoin/issues/19150#issuecomment-638092106_), I would like know what are the recommended config we can apply?  Or is there a better way to manage this error?  

```
It is only possible to estimate fees when you have enough mempool transactions from the outside p2p network
```

If we encounter the error, after deleting the 2 dat files, the nodes will take some time to catch up and fetch new fee.  I would like to check if there will be any alternative fee that user can manually calculate such as using `minRelayTxFee` ?

**Comment by pinheadmz** [comment] 2024-10-19 13:07
Fee rate estimates are only available after the full node has monitored transactions entering the mempool and waiting for confirmation, over a long enough time span. I'm not sure what deleting those files would accomplish besides starting that process over. You can set a hard coded fee, or trust fee rates provide from some other source (like mempool.space)

**Comment by ella-quicknode** [comment] 2024-10-19 13:40
Thanks for the reply @pinheadmz  

We are seeing enough tx entering our infra consistently, but for some reason, the nodes occasionally returns this error `Insufficient data or no feerate found`, this error can't be self subsided unless we manually delete the dat files, then nodes recovered for estmiateSmartFee. 

I was just curious what's the expected behaviour when we see error `Insufficient data or no feerate found`. 🙂

**Comment by pinheadmz** [comment] 2024-10-19 13:52
So the nodes return fee estimates as expected for some time, then just stop for some reason?

**Comment by pinheadmz** [comment] 2024-10-19 13:54
It might be helpful to have version of the affected node and debug log output. You may need to run `bitcoin-cli logging '["estimatefee"]'`

**Comment by qk-santi** [comment] 2024-10-21 09:14
Hey @pinheadmz !

Thanks for answering

Since upgrading to v27 around April, we've been having estimation issues.

Just after upgrade to v27, we had incorrect estimations both on Testnet and Mainnet on all nodes.

On Mainnet, it estimates got stuck to ~300 sats for several days, while network was asking for ~50 sats.
We waited a bit to check if mempool had to refresh and get newer transactions to get the pulse of the network, just in case if it had any improper batch of txs that were skewing the estimates.

We ended up deleting `fee_estimate.dat` and `mempool.dat` to get proper estimates again, which they came eventually after we had enough txs in the mempool again.

After that reset, Mainnet has been behaving correctly.

On the other hand on Testnet, after upgrade we got `Insufficient data or no feerate found` on all nodes.
Which would be expected if mempool was running low on txs, but we were having 4-6k txs on the mempool at that time on the nodes.
We also deleted `fee_estimate.dat` and `mempool.dat` and got back the estimates.

But on Testnet, that error has been coming back several times since then, while the mempool still has multiple thousand transactions, which should be enough to give an estimate.

**Comment by pinheadmz** [comment] 2024-10-21 13:03
@qk-santi ok sounds like you have a clear understanding and the behavior is still unexpected. I would check two more things:
- Check your bitcoin.conf for anything that might be affecting mempool policy (rbf, relayfee, whitelist, etc)
- Enable estimate fee logging `bitcoin-cli logging '["estimatefee"]'` and watch debug.log for `[estiamtefee]` messages

**Comment by willcl-ark** [comment] 2024-11-28 15:02
In the absence of any followup from @ella-quicknode in a few weeks, and no reproduction available (as well as no other reports) I'm going to close this as not reproducible.

If you have an excerpt from a debug.log with the `estimatesmartfee` logging turned on that you could provide, or think this should be re-opened for any other reason, please drop a comment below and we can re-open this.

If this has been continuing it would be good also to know if you see the same behaviour with 28.0.

**Closed by willcl-ark** 2024-11-28 15:02 UTC
Labels: RPC/REST/ZMQ

**Comment by ChayDragan** [comment] 2025-03-31 19:13
@pinheadmz @willcl-ark - 

This issue seems to persist on both testnet3 and testnet4, is there other fixes coming or recommended outside of manually deleting files over and over again? 

We expected that testnet4 would resolve this issue and bring a more stable environment but unfortunately has continued to provide an instable testing environment. Any help would be greatly appreciated.

**Comment by juanmigdr** [comment] 2025-05-22 12:06
I am currently experiencing this same issue again on testnet and testnet4
