### ISSUE TITLE
Pruning code does not currently prune

### ISSUE THREAD

**Issue by BitpopCoin** [bitcoin/bitcoin#6184] opened 2015-05-25 17:25 UTC
This one downloads the entire blockchain before pruning and destroys my vps, debug sees my 25gb limit as usual but it just continues. I can't finish but it does hit 30gb before killing my vps. 

http://builds.jonasschnelli.ch/nightlybuilds/2015-05-17/bitcoin-0.10.99-linux64.tar.gz

**Comment by BitpopCoin** [comment] 2015-05-25 17:28
This one works correctly but is getting old

http://luke.dashjr.org/programs/bitcoin/files/bitcoind/misc/0.10.x/0.10.0rc3.autoprune/

**Comment by jonasschnelli** [comment] 2015-05-25 17:51
@BitpopCoin Can you post your debug.log? What `-prune=`-target  did you set?

**Comment by BitpopCoin** [comment] 2015-05-25 18:55
Bitcoin.conf
prune=25000

I deleted the debug, I can try again if you think it should be working and it's on my end.

**Comment by BitpopCoin** [comment] 2015-05-25 19:23
It had

Autoprune configured to use less than 25000MiB on disk for block files

**Comment by jonasschnelli** [comment] 2015-05-25 19:27
@BitpopCoin you are aware of that the 25GiB are only for the blockstore (not including utxo set which should be around 761MB, etc.)?

**Comment by BitpopCoin** [comment] 2015-05-25 19:49
Yes the working version hits 26gb which is fine.

**Comment by BitpopCoin** [comment] 2015-05-27 17:38
I still have the issue. I tried the latest snapshot.

http://filebin.ca/23C39JXC5ICd/debug.log

**Comment by jonasschnelli** [comment] 2015-05-27 18:08
Thanks for the log.
Could you run again with `-debug=prune` and upload the debug.log again?

**Comment by BitpopCoin** [comment] 2015-05-28 01:46
@jonasschnelli

https://mega.co.nz/#!NB1ExTCK!KZppb-DXY8t6UfrbmZvGXC5BFinQBIgmyhdhg5Td7nI

**Comment by jonasschnelli** [comment] 2015-05-28 10:43
@laanwj i think this should get reopened.
It looks after a real issue:
Found the following in the logs (partial output of `| grep prune`):
```
2015-05-28 01:13:12 Prune: target=2500MiB actual=2462MiB diff=37MiB max_prune_height=197394 removed 0 blk/rev pairs
2015-05-28 01:13:14 Prune: target=2500MiB actual=2463MiB diff=36MiB max_prune_height=197504 removed 0 blk/rev pairs
2015-05-28 01:13:16 Prune: target=2500MiB actual=2470MiB diff=29MiB max_prune_height=197587 removed 0 blk/rev pairs
2015-05-28 01:13:16 Prune: target=2500MiB actual=2471MiB diff=28MiB max_prune_height=197593 removed 0 blk/rev pairs
2015-05-28 01:13:19 Prune: target=2500MiB actual=2486MiB diff=13MiB max_prune_height=197687 removed 0 blk/rev pairs
2015-05-28 01:13:19 Prune: target=2500MiB actual=2487MiB diff=12MiB max_prune_height=197688 removed 0 blk/rev pairs
2015-05-28 01:13:21 Prune: target=2500MiB actual=2503MiB diff=-3MiB max_prune_height=197699 removed 0 blk/rev pairs
2015-05-28 01:13:23 Prune: target=2500MiB actual=2520MiB diff=-20MiB max_prune_height=197744 removed 0 blk/rev pairs
2015-05-28 01:13:24 Prune: target=2500MiB actual=2526MiB diff=-26MiB max_prune_height=197788 removed 0 blk/rev pairs
2015-05-28 01:13:26 Prune: target=2500MiB actual=2527MiB diff=-27MiB max_prune_height=197876 removed 0 blk/rev pairs
2015-05-28 01:13:28 Prune: target=2500MiB actual=2530MiB diff=-30MiB max_prune_height=197967 removed 0 blk/rev pairs
2015-05-28 01:13:29 Prune: target=2500MiB actual=2532MiB diff=-32MiB max_prune_height=198042 removed 0 blk/rev pairs
```

**Comment by laanwj** [comment] 2015-05-28 10:46
@jonasschnelli Fine with reopening, but then the issue should get a relevant title

**Comment by jonasschnelli** [comment] 2015-05-28 10:48
@BitpopCoin: could you rename the issue title? Something that reflects the problem.

**Comment by sdaftuar** [comment] 2015-05-28 13:05
@BitpopCoin Thanks for reporting this; I think I see the problem.

The pruning code enforces a requirement that the block files it keeps be contiguous, so that blockfile N will only be considered for pruning if blockfiles 0, ..., N-1 were already pruned.

There is also a requirement that no block file will be pruned if there's a block in the file with a height that is too close to the height of the tip.  What appears to be happening here is that some peer likely inv'ed you a block at the tip while you were syncing (this is normal behavior); that block was stored in block file 5, and since its height is so large, it effectively stops pruning from taking place.  From the debug.log:

```2015-05-28 01:03:59 Leaving block file 5: CBlockFileInfo(blocks=7446, size=134174305, heights=148758...358316, time=2011-10-10...2015-05-28)```

For what it's worth, if the node were able to fully sync, I believe eventually the pruning targets would be respected again.  This is certainly undesirable behavior though.

I think the best fix may be to relax the restriction that files be contiguous, which will complicate the logic slightly but seems likely to be worth it to avoid this outcome.

**Comment by BitpopCoin** [comment] 2015-05-28 17:59
For what it's worth, I've tried it many times. Last few times I've used 2.5 gb to speed things up. But I've originally used 25gb and it continues past 30gb breaking my droplet.

**Comment by ajweiss** [comment] 2015-05-28 23:19
Indeed, there appears to be a bug here.  Just out of curiosity, are you using the relay network client with your pruned nodes?  I was able to reproduce something similar locally using the relay network during initial sync.

**Comment by BitpopCoin** [comment] 2015-05-29 00:38
Yes the relay node is connected.

addnode=public.us-west.relay.mattcorallo.com:8335

**Comment by ajweiss** [comment] 2015-05-29 01:04
Good.  That makes sense.  I was wondering how a failure like this would have slipped through all the testing that has taken place thus far.  There is definitely a bug here and there are a few routes for fixing it with varying levels of risk.  There will be a patch forthcoming.

In the meantime, if you want to test pruning, disable the relay node during initial sync (and catchup syncs if your nodes go offline, or just altogether).  It's a difficult to trigger corner case if the relay node isn't involved.

Thanks for reporting!

**Comment by BitpopCoin** [comment] 2015-05-29 02:13
I was trying to think of anything odd about my node but I kept only thinking about the permissions. Another Bitcoin created .bitcoin but it ran as root and could write so I ignored the permissions issue, which was correct but I forgot I was using the relay network.

I'll wait to try it again until a possible patch so let me know and I'll test. Thanks.

**Comment by laanwj** [comment] 2015-06-10 10:25
Can you help testing #6221? It should solve this issue by also pruning when blocks are non-contiguous.

**Comment by BitpopCoin** [comment] 2015-06-10 10:34
I tried the nightly on 6-5 which didn't help. Should I try tonight's?

**Comment by BitpopCoin** [comment] 2015-06-10 11:16
Trying http://builds.jonasschnelli.ch/nightlybuilds/2015-06-10/ now

**Comment by sdaftuar** [comment] 2015-06-10 12:07
FYI #6221 hasn't been merged yet, so that build won't help (I believe that's just what was in master).

**Comment by jonasschnelli** [comment] 2015-06-10 12:15
Just started a build for #6221 (https://builds.jonasschnelli.ch/pulls/6221/). @BitpopCoin: you should test this build. It's the master with 6221 on top. Ready in about 30mins.

**Comment by sdaftuar** [comment] 2015-06-10 12:22
@jonasschnelli Thanks! Also if you and @BitpopCoin are up for it, #6224 goes further to make pruning more effective when using the relay node.

**Comment by BitpopCoin** [comment] 2015-06-10 12:54
Ok will both be in today? I already started, I'll stop and wait. Thanks.

**Comment by BitpopCoin** [comment] 2015-06-10 13:08
I'm trying https://builds.jonasschnelli.ch/pulls/6221/bitcoin-0.11.99-linux64.tar.gz

**Comment by BitpopCoin** [comment] 2015-06-11 00:53
It worked! Will you tell me when it's in the nightly then the rc?

**Comment by laanwj** [comment] 2015-06-16 12:55
It has been merged into master so it will be in any nightlies from ~ 5 days ago, and it has been backported to 0.11 so will also be in next rc (rc2).

**Closed by laanwj** 2015-06-16 12:55 UTC
Labels: Bug

**Comment by BitpopCoin** [comment] 2015-06-17 05:30
Thanks guys, great work
