### ISSUE TITLE
[Qt, BIP70] missing detection of existing same payment request

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin/bitcoin#5722] opened 2015-01-29 08:24 UTC
Steps to reproduce:
- Open bitcoin URL with payment request
- = Bitcoin-QT shows yellow payment request infos
- Open same bitcoin URL again
- = Bitcoin-QT shows two yellow payment request infos and would send two times the funds if one would push send

![bildschirmfoto 2015-01-29 um 09 23 45](https://cloud.githubusercontent.com/assets/178464/5954505/893f4440-a798-11e4-9e29-a464928a7efe.png)

**Comment by jonasschnelli** [comment] 2015-01-29 08:57
@Diapolo mind having a look at this?

**Comment by Diapolo** [comment] 2015-01-30 09:30
AFAIK this is also true when using just normal bitcoin: URIs. Did you check it's a BIP requirement to forbid adding/displaying it again? Before doing anything code wise, we should be sure what IS the correct behaviour for this? @laanwj Mind sharing some thoughts here?

**Comment by jonasschnelli** [comment] 2015-01-30 09:32
@Diapolo i just stepped over this issue. I have no plans to dive into BIP70. I just think this is a strange behavior and should be fixed.

**Comment by laanwj** [comment] 2015-05-18 09:26
This is a sort-of duplicate of #2302, which applies the same problem to non-payment request URIs. A solution could take care of both at the same time.

**Closed** 2019-08-06 07:11 UTC
Labels: GUI, Wallet
