### ISSUE TITLE
Improve "mempool min fee not met" error to include information on what the min fee is

### ISSUE THREAD

**Issue by fresheneesz** [bitcoin/bitcoin#11955] opened 2017-12-20 01:14 UTC
When sending a transaction with a low fee, you can sometimes get an error saying "mempool min fee not met". 

I would expect an error like this to include information about what the minimum fee is.

I'm using Electrum 3.0.2 in which you can see the raw error from this when you send a low fee transaction when its relayed to an electrum server.

**Comment by Varunram** [comment] 2017-12-21 14:39
@fresheneesz Could you explain as to where you saw this error? Some more info like logs would be really useful. Thanks!

**Comment by fresheneesz** [comment] 2017-12-21 21:07
There's not much more to explain than is in this issue and the electrum issue. I tried to increase the fee with a replace-by-fee transaction and it popped up a message box with an error that said "mempool min fee not met" with some additional information (none of which looked like it included the min fee).  I can't repro right now and even if I could, electrum displayed the error in a way where the whole thing couldn't be seen fully or copied.

**Comment by spot88** [comment] 2017-12-22 00:02
I get the same message. 
![bitcoin](https://user-images.githubusercontent.com/10884072/34279841-cdf388fa-e6b3-11e7-8d2e-1ab52b74680b.png)

**Comment by 0xB10C** [comment] 2017-12-22 00:10
The amount of system memory allocated for unconfirmed transactions is defined with the option _maxmempool_. _maxmempool_ defaults to 300MB of RAM. Once the _maxmempool_-memory is fully used, the lowest-fee transactions are dropped from the nodes mempool and _mempoolminfee_ is increased to reject lower-fee transactions.

The _mempoolminfee_ thus is dependent on the current memory usage and the configured _maxmempool_. Connecting to another Electrum Server connected to a node with custom (higher) _maxmempool_ could work. However the underlying node might accept the transaction but then failes to broadcast it to  a peer/peers with a default _maxmempool_ of 300MB. The transaction does not meet their min-fee expecations. 

A core node could return it's current _mempoolminfee_ in the error output, but that would not inform about the _mempoolminfee_ of it's peers.

`bitcoin-cli getmempoolinfo`  shows the current _mempoolminfee_.

Q: Why is the _mempoolminfee_ not specifyed as fee-rate (sat/vbyte)?

**Comment by fresheneesz** [comment] 2017-12-22 00:28
@spot88 That's the one that got me...

**Comment by fresheneesz** [comment] 2017-12-22 00:31
> A core node could return it's current mempoolminfee in the error output, but that would not inform about the mempoolminfee of it's peers.

I'd be perfectly happy with that. Nothing's perfect. But if your aim is to submit something at the minimum and you know that risks that the transaction might be evicted, right now I have pretty much no recourse. I have no feedback on what min fee might be accepted. At least if your peer tells you their min fee, you can submit back to them, or it should give you *some* idea of the min fee for other peers (who will then reject you with their own min fee message that you can then use to resubmit with that higher fee). 

> `bitcoin-cli getmempoolinfo` shows the current *mempoolminfee*.

So something like electrum could use this to determine a remote node's minimum fee?

**Comment by Varunram** [comment] 2017-12-22 15:03
@fresheneesz: Yes, electrum could use the call to get the minimum mempool fee or we could edit the error returned. But since that's already there in the logs, I think it would be better if you request the folks over at electrum.

@0xB10C: You could open an issue to change it from btc/KB now :)

**Comment by fresheneesz** [comment] 2017-12-22 19:30
@Varunram Thanks for the info guys! I'll throw that back into the electrum issue.

**Comment by Empact** [comment] 2018-02-16 04:43
Now that #12356 is merged, the error message will include the satoshis per byte for the transaction and the min satoshis per byte of the minpool, e.g.: `mempool min fee not met, 166 < 411 (code 66)`

Seems this can be closed. /cc @laanwj

**Comment by Empact** [comment] 2018-02-16 06:50
Now that #12356 is merged, the error message includes the attempted fee and the minimum fee (both in satoshis), e.g.: `mempool min fee not met, 166 < 411 (code 66)`. I think we can close this. /cc @laanwj

**Comment by fresheneesz** [comment] 2018-02-16 09:23
`166 < 411` ? Units people!

**Closed** 2018-02-16 10:14 UTC
Labels: Mempool, Utils/log/libs, good first issue

**Comment by laanwj** [comment] 2018-02-16 10:16
I agree that specifying units would be nice, but think enough information has been added to close the issue (all the internal low-level stuff uses satoshis.)
