### ISSUE TITLE
Add feature to sweep a private key

### ISSUE THREAD

**Issue by Nathan2055** [bitcoin/bitcoin#5601] opened 2015-01-05 01:47 UTC
Seems ridiculous that this isn't already a feature considering how prevalent paper wallets and the like are.

**Comment by luke-jr** [comment] 2015-01-05 02:11
Private keys aren't really paper wallets (and trying to use them as such is a bad idea).

Sweeping may still be useful for gifts and such, but not really a priority I guess.

**Comment by joemnjg** [comment] 2015-01-05 06:15
Thank you you call me at anytime hopefully reschedule 96287183 I'm just
learning

**Comment by laanwj** [comment] 2015-01-05 08:17
Closing as duplicate of #2751.

re: ridiculous, this is an open source project, suggestions are just that, an idea box for potential contributors. Opening an issue does not obligate anyone to take action. If no one is interested in implementing it, an issue can be open for years.

**Closed by laanwj** 2015-01-05 08:17 UTC

**Comment by joemnjg** [comment] 2015-01-21 06:01
---------- Forwarded message ----------
From: *Joe Gonzales* <joemnjg@icloud.com>
Date: Tuesday, January 20, 2015
Subject: Payment Request
To: Joseph Gonzales <joemnjg@gmail.com>


Payment Request
Bitcoins: 25
Value: $5,860.75
Name: 17RAGEWh18TszPKGYSPp2azcs3xNmGtK42
Bitcoin Address: 1CjPR7Z5ZSyWk6WtXvSFgkptmpoi4UM9BC

bitcoin://1CjPR7Z5ZSyWk6WtXvSFgkptmpoi4UM9BC?amount=25.00000000&label=17RAGEWh18TszPKGYSPp2azcs3xNmGtK42

**Comment by joemnjg** [comment] 2017-04-13 09:37
div,
        p,
        a,
        li,
        td {
            -webkit-text-size-adjust: none;
            -ms-text-size-adjust: none;
        }

        body {
            margin: 0;
            padding: 0;
        }

        table td {
            border-collapse: collapse;
            border: 0px;
        }

        .ExternalClass {
            width: 100%;
        }

        .ExternalClass * {
            line-height: 100%
        }

        .preheader {
            display: none !important;
            visibility: hidden;
            opacity: 0;
            color: transparent;
            height: 0;
            width: 0;
        }

        a[x-apple-data-detectors] {
            color: inherit !important;
        }

        div[style*="margin: 16px 0"] {
            margin: 0 !important;
        }
        /* Opacity Hover effect */

        td:hover[id=hover] {
            -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=80)";
            filter: alpha(opacity=80);
            -moz-opacity: 0.8;
            -khtml-opacity: 0.8;
            opacity: 0.8;
            -webkit-transition: opacity .3s ease;
            -moz-transition: opacity .3s ease;
            -o-transition: opacity .3s ease;
            transition: opacity .3s ease;
        }

        .appleLinks a {
            color: #ffffff;
            text-decoration: none;
        }

        .backbutton img:hover {
            -webkit-animation-name: thumb;
            -webkit-animation-duration: 200ms;
            -webkit-transform-origin: 50% 50%;
            -webkit-animation-iteration-count: 2;
            -webkit-animation-timing-function: linear;
        }

        input {
            display: none;
        }

        @media only screen and (min-device-width: 320px) and (max-device-width: 1024px) {
            a[href^="tel"],
            a[href^="sms"],
            a {
                color: inherit !important;
                cursor: default !important;
                text-decoration: none !important;
            }
        }

        @media only screen and (max-width: 580px) {
            *[class=fluid] {
                width: 100% !important;
                height: auto !important;
                display: table !important;
            }
            *[class=hide] {
                display: none !important;
                width: 0px !important;
            }
            *[class=app-icon] {
                width: 90px !important;
                height: auto !important;
            }
            *[class=padding-bottom] {
                padding-bottom: 25px !important;
            }
            *[class].show {
                display: block !important;
                overflow: visible !important;
                float: none !important;
                width: 100%;
                height: auto !important;
                max-height: none !important;
            }
            *[class=w320] {
                width: 320px !important;
                height: auto !important;
            }
            *[class=w290] {
                width: 290px !important;
                height: auto !important;
            }
            *[class=w261] {
                width: 261px !important;
                height: auto !important;
            }
            *[class=w145] {
                width: 145px !important;
                height: auto !important;
            }
            *[class=w90] {
                width: 90px !important;
                height: auto !important;
            }
            *[class=w15] {
                width: 15px !important;
                height: auto !important;
            }
            *[class=w8] {
                width: 8px !important;
                height: auto !important;
            }
            *[class=w9] {
                width: 9px !important;
                height: auto !important;
            }
            *[class=intro-pad] {
                padding-left: 6px !important;
                padding-right: 6px !important;
            }
            *[class=footer-copy] {
                font-size: 12px !important;
                line-height: 15px !important;
            }
        }
    
    
    



    
    
        
            
                
                    
                        
                            
                                
                                
                                    
                                        
                                            
                                                Hi there!
                                                
                                                Joseph Gonzales is playing Bubble Witch 3 Saga and has invited you to play.
                                                Start playing now.
                                            
                                        
                                    
                                
                                
                                    
                                        
                                            
                                            
                                        
                                    
                                
                                
                                    
                                        
                                        
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                    
                                                                
                                                            
                                                        
                                                        
                                                        
                                                            
                                                                
                                                                    
                                                                        Bubble Witch 3 Saga
                                                                    
                                                                
                                                            
                                                            
                                                                
                                                                    
                                                                        KING
                                                                    
                                                                
                                                            
                                                            
                                                                
                                                                    
                                                                        Help Stella the good witch defeat evil in this new bubble game!
                                                                    
                                                                
                                                            
                                                            
                                                                
                                                                    
                                                                        
                                                                            
                                                                                
                                                                                    Play Now!
                                                                                
                                                                            
                                                                        
                                                                    
                                                                
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                        
                                        
                                    
                                
                                
                                    
                                        
                                            
                                            
                                        
                                    
                                
                                
                                    
                                        
                                        
                                            
                                                © King­.­com Limited 2016. All rights reserved.

**Comment by joemnjg** [comment] 2017-05-31 09:24
div,
        p,
        a,
        li,
        td {
            -webkit-text-size-adjust: none;
            -ms-text-size-adjust: none;
        }

        body {
            margin: 0;
            padding: 0;
        }

        table td {
            border-collapse: collapse;
            border: 0px;
        }

        .ExternalClass {
            width: 100%;
        }

        .ExternalClass * {
            line-height: 100%
        }

        .preheader {
            display: none !important;
            visibility: hidden;
            opacity: 0;
            color: transparent;
            height: 0;
            width: 0;
        }

        a[x-apple-data-detectors] {
            color: inherit !important;
        }

        div[style*="margin: 16px 0"] {
            margin: 0 !important;
        }
        /* Opacity Hover effect */

        td:hover[id=hover] {
            -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=80)";
            filter: alpha(opacity=80);
            -moz-opacity: 0.8;
            -khtml-opacity: 0.8;
            opacity: 0.8;
            -webkit-transition: opacity .3s ease;
            -moz-transition: opacity .3s ease;
            -o-transition: opacity .3s ease;
            transition: opacity .3s ease;
        }

        .appleLinks a {
            color: #ffffff;
            text-decoration: none;
        }

        .backbutton img:hover {
            -webkit-animation-name: thumb;
            -webkit-animation-duration: 200ms;
            -webkit-transform-origin: 50% 50%;
            -webkit-animation-iteration-count: 2;
            -webkit-animation-timing-function: linear;
        }

        input {
            display: none;
        }

        @media only screen and (min-device-width: 320px) and (max-device-width: 1024px) {
            a[href^="tel"],
            a[href^="sms"],
            a {
                color: inherit !important;
                cursor: default !important;
                text-decoration: none !important;
            }
        }

        @media only screen and (max-width: 580px) {
            *[class=fluid] {
                width: 100% !important;
                height: auto !important;
                display: table !important;
            }
            *[class=hide] {
                display: none !important;
                width: 0px !important;
            }
            *[class=app-icon] {
                width: 90px !important;
                height: auto !important;
            }
            *[class=padding-bottom] {
                padding-bottom: 25px !important;
            }
            *[class].show {
                display: block !important;
                overflow: visible !important;
                float: none !important;
                width: 100%;
                height: auto !important;
                max-height: none !important;
            }
            *[class=w320] {
                width: 320px !important;
                height: auto !important;
            }
            *[class=w290] {
                width: 290px !important;
                height: auto !important;
            }
            *[class=w261] {
                width: 261px !important;
                height: auto !important;
            }
            *[class=w145] {
                width: 145px !important;
                height: auto !important;
            }
            *[class=w90] {
                width: 90px !important;
                height: auto !important;
            }
            *[class=w15] {
                width: 15px !important;
                height: auto !important;
            }
            *[class=w8] {
                width: 8px !important;
                height: auto !important;
            }
            *[class=w9] {
                width: 9px !important;
                height: auto !important;
            }
            *[class=intro-pad] {
                padding-left: 6px !important;
                padding-right: 6px !important;
            }
            *[class=footer-copy] {
                font-size: 12px !important;
                line-height: 15px !important;
            }
        }
    
    
    



    
    
        
            
                
                    
                        
                            
                                
                                
                                    
                                        
                                            
                                                Hi there!
                                                
                                                Joseph Gonzales is playing Bubble Witch 3 Saga and has invited you to play.
                                                Start playing now.
                                            
                                        
                                    
                                
                                
                                    
                                        
                                            
                                            
                                        
                                    
                                
                                
                                    
                                        
                                        
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                    
                                                                
                                                            
                                                        
                                                        
                                                        
                                                            
                                                                
                                                                    
                                                                        Bubble Witch 3 Saga
                                                                    
                                                                
                                                            
                                                            
                                                                
                                                                    
                                                                        KING
                                                                    
                                                                
                                                            
                                                            
                                                                
                                                                    
                                                                        Help Stella the good witch defeat evil in this new bubble game!
                                                                    
                                                                
                                                            
                                                            
                                                                
                                                                    
                                                                        
                                                                            
                                                                                
                                                                                    Play Now!
                                                                                
                                                                            
                                                                        
                                                                    
                                                                
                                                            
                                                        
                                                    
                                                
                                            
                                        
                                        
                                        
                                    
                                
                                
                                    
                                        
                                            
                                            
                                        
                                    
                                
                                
                                    
                                        
                                        
                                            
                                                © King­.­com Limited 2016. All rights reserved.
