### ISSUE TITLE
Spurious CI failure of `interface_usdt_validation.py`

### ISSUE THREAD

**Issue by darosior** [bitcoin/bitcoin#25793] opened 2022-08-06 08:26 UTC
```
82/244 - interface_usdt_validation.py failed, Duration: 1 s
stdout:
2022-08-04T10:06:05.298000Z TestFramework (INFO): Initializing test directory /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20220804_095558/interface_usdt_validation_159
2022-08-04T10:06:05.849000Z TestFramework (INFO): hook into the validation:block_connected tracepoint
2022-08-04T10:06:06.358000Z TestFramework (INFO): mine 2 blocks
2022-08-04T10:06:06.374000Z TestFramework (INFO): handle_blockconnected(): ConnectedBlock(hash=740e218334005cfc4c988053083a3d3ba5ba59cd8530030e42a87a4080fbffe8 height=202, transactions=1, inputs=1, sigops=0, duration=319)
2022-08-04T10:06:06.375000Z TestFramework (INFO): handle_blockconnected(): ConnectedBlock(hash=524a502fb9f972c220da42f2658ee2c4e63238a58b2b470505fabbae4482279b height=201, transactions=1, inputs=1, sigops=0, duration=298)
2022-08-04T10:06:06.394000Z TestFramework (INFO): check that we traced 2 blocks
2022-08-04T10:06:06.394000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 133, in main
    self.run_test()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/interface_usdt_validation.py", line 131, in run_test
    assert_equal(BLOCKS_EXPECTED, blocks_checked)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 52, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(2 == 0)
2022-08-04T10:06:06.445000Z TestFramework (INFO): Stopping nodes
2022-08-04T10:06:06.598000Z TestFramework (WARNING): Not cleaning up dir /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20220804_095558/interface_usdt_validation_159
2022-08-04T10:06:06.598000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20220804_095558/interface_usdt_validation_159/test_framework.log
2022-08-04T10:06:06.599000Z TestFramework (ERROR): 
2022-08-04T10:06:06.599000Z TestFramework (ERROR): Hint: Call /tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/combine_logs.py '/tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20220804_095558/interface_usdt_validation_159' to consolidate all logs
2022-08-04T10:06:06.599000Z TestFramework (ERROR): 
2022-08-04T10:06:06.599000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2022-08-04T10:06:06.599000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues
2022-08-04T10:06:06.599000Z TestFramework (ERROR): 
stderr:
Exception ignored on calling ctypes callback function: <function PerfEventArray._open_perf_buffer.<locals>.raw_cb_ at 0x7f9753218430>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcc/table.py", line 982, in raw_cb_
    callback(cpu, data, size)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/interface_usdt_validation.py", line 108, in handle_blockconnected
    assert_equal(block["hash"], bytes(event.hash[::-1]).hex())
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 52, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(524a502fb9f972c220da42f2658ee2c4e63238a58b2b470505fabbae4482279b == 740e218334005cfc4c988053083a3d3ba5ba59cd8530030e42a87a4080fbffe8)
Exception ignored on calling ctypes callback function: <function PerfEventArray._open_perf_buffer.<locals>.raw_cb_ at 0x7f97532184c0>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcc/table.py", line 982, in raw_cb_
    callback(cpu, data, size)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/interface_usdt_validation.py", line 108, in handle_blockconnected
    assert_equal(block["hash"], bytes(event.hash[::-1]).hex())
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 52, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(740e218334005cfc4c988053083a3d3ba5ba59cd8530030e42a87a4080fbffe8 == 524a502fb9f972c220da42f2658ee2c4e63238a58b2b470505fabbae4482279b)
```

Happened on unrelated https://github.com/bitcoin/bitcoin/pull/25642. [Logs](https://cirrus-ci.com/task/5521993490497536).

**Comment by fanquake** [comment] 2022-08-06 08:28
Dupe of #25764.

**Comment by darosior** [comment] 2022-08-06 08:30
Arf, sorry. I had looked up using "`interface_usdt_validation`".
------- Original Message -------

**Closed** 2022-08-06 09:14 UTC
