### ISSUE TITLE
Untranslated strings in GUI

### ISSUE THREAD

**Issue by FabioCarpi** [bitcoin/bitcoin#8900] opened 2016-10-07 14:48 UTC
I'm using the pt-br interface and some texts are appearing in English.
v 0.13

**Comment by MarcoFalke** [comment] 2016-10-07 17:05
According to the [release process](https://github.com/bitcoin/bitcoin/blob/61d191fbf953700ba8aeadc9c8cf4c195efbd10c/doc/release-process.md) we are only syncing translation from [transifex](https://www.transifex.com/bitcoin/bitcoin/) before every rc.

**Comment by FabioCarpi** [comment] 2016-10-07 17:44
But these texts alread translated

**Comment by fanquake** [comment] 2016-10-08 10:36
@FabioCarpi Can you give us some example strings, or screenshots?

**Comment by MarcoFalke** [comment] 2016-10-08 10:46
I think he refers to the recent translations on transifex, which are not yet fetched: https://www.transifex.com/user/profile/FabioCarpi/#activity

**Comment by MarcoFalke** [comment] 2016-10-08 10:49
They are going to be included in https://github.com/bitcoin/bitcoin/releases/tag/v0.13.1rc1 which is not out yet, so closing the issue for now.

**Comment by FabioCarpi** [comment] 2016-10-08 14:33
No @MarcoFalke. Are windows that always have translation, but are not showing translated after the last updates

**Comment by MarcoFalke** [comment] 2016-10-08 14:39
Hmm, in this case I am going to quote @fanquake 

> @FabioCarpi Can you give us some example strings, or screenshots?

**Comment by FabioCarpi** [comment] 2016-10-08 16:57
@MarcoFalke as requested
![capturar](https://cloud.githubusercontent.com/assets/6897978/19214655/1dffd92a-8d5f-11e6-9bf0-f784f696988c.PNG)

**Comment by jonasschnelli** [comment] 2016-10-09 14:16
I can confirm the issue.
Somehow the `tr()`-strings in `AddressBookPage` are not getting translated.

**Comment by laanwj** [comment] 2016-10-11 15:23
Confirmed: The tr() strings in addressbookpage.cpp don't even end up in the translation - not even the English one.
```
$ git grep "Choose the address to send coins to"
src/qt/addressbookpage.cpp:        case SendingTab: setWindowTitle(tr("Choose the address to send coins to")); break;
```

**Comment by laanwj** [comment] 2016-10-11 15:32
Many of the cpp's don't, because of:
```
if ENABLE_WALLET
BITCOIN_QT_CPP += \
  qt/addressbookpage.cpp \
  ...
endif
```
Wallet was disabled. Maybe that is the problem: `make translate` still works when you build without wallet support, however the strings from the .cpp files will not be included. 

It is possible that the system I use for generating the translations to upload doesn't have the wallet enabled. I had some issues here on Xenial and had to fall back to a Trusty VM. This could be the cause of the issue.

**Comment by fanquake** [comment] 2016-10-13 09:51
Should be fixed by #8911

**Closed by fanquake** 2016-10-13 09:51 UTC
Labels: GUI

**Comment by laanwj** [comment] 2016-10-13 10:40
Yes - I've just pushed a commit to 0.13, 633c4a1f3690152bdda4b0ac7bcfde22c237183e, which when picked up by Transifex will enable the wallet messages to be translated again.
Sorry for the mess.

**Comment by MarcoFalke** [comment] 2016-10-15 09:00
I am wondering if it is possible to "translate" those "new" string on transifex by a script.

**Comment by FabioCarpi** [comment] 2016-10-24 17:12
Just saying, in version 0.13.1rc2, the problem continues...

**Comment by MarcoFalke** [comment] 2016-10-24 19:01
@FabioCarpi Unfortunately the translated string "fell out" of the transifex translation system. There may be a way to read them from the transifex cache and submit them via the api in an automated manner.

I am not sure if @luke-jr has some script for the transifex api. (I remember this was up for discussion when changing the [product name](https://github.com/bitcoin/bitcoin/pull/7192#issuecomment-163871818) to as few places as possible, but I don't recall if a script emerged from that...)
