### ISSUE TITLE
Issues in 'make distcheck'

### ISSUE THREAD

**Issue by danra** [bitcoin/bitcoin#11302] opened 2017-09-11 16:47 UTC
### Describe the issue
Encountered a couple of issues encountered running "make distcheck" on my machine:
1) During the build, getting a request to override read-only file attributes of qt/temp_bitcoin_locale.qrc
2) At the end of the build, there's an error because of a leftover ./src/bench/data/block413567.raw.h file.

### Can you reliably reproduce the issue?
Yes

#### If so, please list the steps to reproduce below:
1. Start with a clean master checkout
2. Run ./autogen.sh
3. Run ./configure
4. Run make distcheck

### Expected behaviour
No error at end and no request for manual confirmation of overriding read-only attributes during build

### Actual behaviour
As described above. Output pasted in https://pastebin.com/2YEpeB5y

### What version of bitcoin-core are you using?
ee50c9e48786dea0d9df2e45805c25565c100fe3

### Machine specs:
- OS: macOS 10.12.6

**Comment by fanquake** [comment] 2017-10-07 03:23
Just tested this with https://github.com/bitcoin/bitcoin/commit/17f2acedbe078f179556f4550eca547726f087e1
Seeing the override
```
  GEN      qt/qrc_bitcoin_locale.cpp
override r--r--r--  xxx/staff for qt/temp_bitcoin_locale.qrc?   CXX      qt/test/qt_test_test_bitcoin_qt-compattests.o
  CXX      qt/test/qt_test_test_bitcoin_qt-rpcnestedtests.o
```
but the bench issue(fixed in #11435?) was replaced with:
```
rm -f cscope.out cscope.in.out cscope.po.out cscope.files
test . = "../.." || test -z "contrib/filter-lcov.py test/functional/test_runner.py test/util/bitcoin-util-test.py" || rm -f contrib/filter-lcov.py test/functional/test_runner.py test/util/bitcoin-util-test.py
rm -f config.status config.cache config.log configure.lineno config.status.lineno
rm -f Makefile
ERROR: files left in build directory after distclean:
./src/qt/temp_bitcoin_locale.qrc
make[1]: *** [distcleancheck] Error 1
make: *** [distcheck] Error 1
```

**Comment by jonasschnelli** [comment] 2017-10-07 05:36
Yes. The bench clean issue is fixed in master.
The override is present but not really problematic IMO.

**Comment by himynameisbeni** [comment] 2017-11-06 21:23
I'm getting 
`make: *** No rule to make target `distcheck'.  Stop.`

When trying to run make distcheck, has this been removed?

**Comment by MarcoFalke** [comment] 2017-11-07 17:26
Closing, since the issue is fixed. Please open a new issue if anything needs to be addressed.

**Closed by MarcoFalke** 2017-11-07 17:26 UTC
Labels: MacOSX
