### ISSUE TITLE
Running out of disk space forces pruned node to reindex

### ISSUE THREAD

**Issue by luke-jr** [bitcoin/bitcoin#18301] opened 2020-03-09 16:09 UTC
Was testing on a VM with less space than I expected. Node cleanly shutdown due to disk space low, but after resizing disk larger and restarting, it insisted on a reindex.

`-prune=550`

**Comment by MarcoFalke** [comment] 2020-03-09 16:19
What is the error message that prompts the reindex? `checkblock`, `leveldb`, ... ?

**Comment by emilengler** [comment] 2020-04-01 11:37
I'm currently trying to reproduce, what does prune option mean? Have you executed it after you resized your disk or was your node running the entire time with `-prune=550`?

**Comment by luke-jr** [comment] 2020-04-01 12:32
It was `-prune=550` the entire time. After the clean out-of-space shutdown, the VM itself was rebooted to make the virtual disk larger.

**Comment by MarcoFalke** [comment] 2021-02-08 11:52
Duplicate of #17392 ?

**Comment by fanquake** [comment] 2022-08-09 05:40
> Duplicate of https://github.com/bitcoin/bitcoin/issues/17392 ?

I think so.

**Closed by fanquake** 2022-08-09 05:40 UTC
Labels: Bug
