### ISSUE TITLE
signmessage and verifymessage : "Address does not refer to key"

### ISSUE THREAD

**Issue by tunerji** [bitcoin/bitcoin#26876] opened 2023-01-12 03:44 UTC
sign and verify message functions not working with (probobaly bech32 type addresse like: "bc1qg0kmtkmgf4angrmcr9wz2fslxjj4jzj95tkg6r".

I was able to sign using signmessagewithprivkey "privkey" "my message"  and the result if it is correct : "H+QaukT8FP/TFh3bchd9oRj00S7rzuxzSXNXH10y4tgkWkYmKFsfFxOs50bo9510ngNhgsUbE1yG7bbldc2qVGY="

however using signmessage "bc1qg0kmtkmgf4angrmcr9wz2fslxjj4jzj95tkg6r" "my message" and verifymessage "bc1qg0kmtkmgf4angrmcr9wz2fslxjj4jzj95tkg6r" "signature" "my message" examples gives error : "Address does not refer to key"

**Expected behavior**
Signing and verifying messages using bech32 addresses.

**Actual behavior**
"Address does not refer to key" error

**To reproduce**

**System information**

**Comment by 1440000bytes** [comment] 2023-01-12 03:56
Related issue: https://github.com/bitcoin/bitcoin/issues/10542

Related pull request: https://github.com/bitcoin/bitcoin/pull/24058

**Comment by MarcoFalke** [comment] 2023-01-12 09:05
Closing as duplicate of #https://github.com/bitcoin/bitcoin/issues/10542

**Closed by MarcoFalke** 2023-01-12 09:05 UTC
Labels: Bug
