### ISSUE TITLE
Unknown version bit fork activated warning

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#16697] opened 2019-08-23 15:40 UTC
Using some recent build of master, I noticed that both the GUI and and `getblockchaininfo` is now showing the unknown BIP 9 fork activation warning: `Warning: unknown new rules activated (versionbit 1)`.

`git bisect` tells me that this was introduced in #16060 in commit 1c93b9b31c2ab7358f9d55f52dd46340397c906d.

The warning only shows for the highest activated bit detected. During `git bisect`, I noticed that it would show `versionbit 0` activated after 1c93b9b31c2ab7358f9d55f52dd46340397c906d which then changed to `versionbit 1` after 0328dcdcfcb56dc8918697716d7686be048ad0b3. Some modifications to the logging and warnings indicated that both version bits 0 and 1 were being detected as having activated, just that version bit 1 was checked most recently so that is the one that shows up in the warning.

Looking at the version bits checker, it looks like the issue is caused by having empty `ThresholdConditionCache`s (since these are not saved to disk) which won't have the Segwit or CSV fork conditions cached as their conditions were removed. A fix would be to always load the caches with fixed states that have Segwit and CSV activated, but I don't know how to do that.

**Comment by HashUnlimited** [comment] 2019-09-02 16:32
I have also noticed that if we don't have a start condition, we are literally checking each block 29 times - once for each version bit. Looks kind of overkill to me as everything up to present is buried.

**Comment by MarcoFalke** [comment] 2019-09-27 19:45
Fixed 
6b2210f

**Comment by wodry** [comment] 2019-10-31 08:56
After updating from 0.19.0rc2 to 0.19.0rc3 I get this warning in GUI:
![bildschirmfoto](https://user-images.githubusercontent.com/8447873/67932498-52a1ad80-fbc4-11e9-8a10-ed3d2bf43bae.png)

in English: "Warning: Unknown new rules activated (Versionbit 0)"

**Comment by laanwj** [comment] 2019-10-31 11:25
Yes, this problem is clearly back.

**Comment by Sjors** [comment] 2019-10-31 11:40
Actually no, I'm not seeing this warning on v0.19.0rc3 or on master.

@wodry can you double check that you're running the right version in the About screen?

I do see the `60 of last 100 blocks have unexpected version` in the log, but that particular warning was removed from the UI. It's over-sensitive because if each block signals a different bit it just adds those up.

The warning in the screen shot was about an actual softfork activation (95% signaling for a long enough period of time). We forgot to take the newly burried SegWit deployment into account. But this was fixed.

**Comment by laanwj** [comment] 2019-10-31 12:18
The warning they're seeing is:
```
        const CBlockIndex* pindex = pindexNew;
        for (int bit = 0; bit < VERSIONBITS_NUM_BITS; bit++) {
            WarningBitsConditionChecker checker(bit);
            ThresholdState state = checker.GetStateFor(pindex, chainParams.GetConsensus(), warningcache[bit]);
            if (state == ThresholdState::ACTIVE || state == ThresholdState::LOCKED_IN) {
                const std::string strWarning = strprintf(_("Warning: unknown new rules activated (versionbit %i)").translated, bit);
                if (state == ThresholdState::ACTIVE) {
                    DoWarning(strWarning);
                } else {
                    AppendWarning(warningMessages, strWarning);
                }
            }
        }
```
But it'd be strange to see this at the tip.

**Comment by wodry** [comment] 2019-10-31 14:35
I double checked the version 0.19.0rc3:
![bildschirmfoto](https://user-images.githubusercontent.com/8447873/67955838-7a5c3a00-fbf3-11e9-858c-45830d029175.png)

debug.log
```
2019-10-31T13:37:16Z UpdateTip: new best=000000000000000000136837c0f0fc11c0ed1d46dcb2140fe7836dc525b2f68b height=601794 version=0x20002000 log2_work=91.280515 tx=470228727 date='2019-10-31T13:36:44Z' progress=1.000000 cache=78.9MiB(589007txo) warning='59 der letzten 100 Blöcke haben eine unerwartete Version'
2019-10-31T13:40:05Z UpdateTip: new best=000000000000000000141a48ee74c31499606daabaa01136fc1780e0e966b175 height=601795 version=0x20000000 log2_work=91.280543 tx=470230091 date='2019-10-31T13:38:34Z' progress=0.999999 cache=79.1MiB(590490txo) warning='58 der letzten 100 Blöcke haben eine unerwartete Version'
2019-10-31T13:49:57Z UpdateTip: new best=0000000000000000000f70b94f358e7be3c5f083dde531c7e001ec7b812067bc height=601796 version=0x20000000 log2_work=91.280572 tx=470232220 date='2019-10-31T13:49:08Z' progress=1.000000 cache=79.6MiB(594214txo) warning='57 der letzten 100 Blöcke haben eine unerwartete Version'
2019-10-31T14:00:43Z UpdateTip: new best=0000000000000000000efbd3489fb12055ff48caeecd40cdb000cdf4e211a293 height=601797 version=0x3fff0000 log2_work=91.2806 tx=470234591 date='2019-10-31T14:00:36Z' progress=1.000000 cache=80.2MiB(599152txo) warning='57 der letzten 100 Blöcke haben eine unerwartete Version'
2019-10-31T14:01:08Z UpdateTip: new best=0000000000000000000e3fd8d5559eccf8908c6ec2cf76523ff2852aa108cb87 height=601798 version=0x20000000 log2_work=91.280628 tx=470236221 date='2019-10-31T14:00:59Z' progress=1.000000 cache=80.3MiB(600073txo) warning='56 der letzten 100 Blöcke haben eine unerwartete Version'
```
"unerwartete Version" = "unexpected version"

**Comment by MarcoFalke** [comment] 2019-10-31 16:12
The "n out of 100" check is different from the versionbits check.

How can it be that this was confirmed to be fixed in fdb3e8f8b27e3b0b2f88c32915975c6e4c299b1e and then regressed?

**Comment by Sjors** [comment] 2019-10-31 17:25
Strange indeed. I'm not seeing it on macOS 10.15 (this has running for hours):
<img width="799" alt="Schermafbeelding 2019-10-31 om 18 24 38" src="https://user-images.githubusercontent.com/10217/67970748-c87d3780-fc0b-11e9-97be-455a1a4489d1.png">

**Comment by wodry** [comment] 2019-10-31 18:48
Maybe I have uncommon peers? I am running with `onlynet=onion`, 10 outbound connections, 4 inbound, currently, eleven peers claim to be `0.18.{0|1|99}`

**Comment by laanwj** [comment] 2019-11-01 10:47
It's based on the last N blocks, not on the peers. Unless they were able to feed you a completely different chain. Although `-noonion` isolates your node, in a sense, that would be a scary thought.

**Comment by wodry** [comment] 2019-11-02 08:53
I have corrected my OP, the warning appeared after upgrading from 0.19.0rc**1** (not 2) to 0.19.0rc3. (it seems that I had skipped rc2)

I tested if I could reproduce that, so I stopped rc3 (warning was there since several days uptime), downgraded to rc1, started, let it run for 30 min, there was no warning in GUI.

Then I stopped rc1, upgraded again to rc3, started, and after 10 hours uptime with rc3, I did not see the warning in GUI again.

**Comment by laanwj** [comment] 2019-11-02 10:29
rc2 and rc3 were the same apart from a version bump, so that's ok :smile:

**Comment by MarcoFalke** [comment] 2019-11-12 03:35
The consensus params are read from uninitialized memory. See https://github.com/bitcoin/bitcoin/pull/17448. So this warning might randomly appear or not appear.

**Comment by MarcoFalke** [comment] 2019-11-12 03:39
We should probably not ship 0.19.0 with this bug

**Comment by MarcoFalke** [comment] 2020-02-10 16:35
Backported to 0.19 in 6ec0dc1

**Closed by MarcoFalke** 2020-02-10 16:35 UTC
Labels: Bug, Validation
