### ISSUE TITLE
osx build & windows crash 

### ISSUE THREAD

**Issue by bitcreditscc** [bitcoin/bitcoin#8327] opened 2016-07-10 16:04 UTC
Is it possible to build mac os client in the same was as windows cross compile in ubuntu?

Also building the latest source (windows client compiled in ubuntu) crashes with exception code exception code c0000005 which according to google is an access violation. Could this be the result of a bad compilation or something else ?

**Comment by jonasschnelli** [comment] 2016-07-11 07:35
Can you give us some more information? config.log, shell dumps, etc.?
In general, you can easily cross-compile OSX and windows binaries on ubuntu/linux.
Check https://github.com/bitcoin/bitcoin/tree/master/depends

**Comment by laanwj** [comment] 2016-07-11 10:26
> Also building the latest source (windows client compiled in ubuntu) crashes with exception code exception code c0000005 which according to google is an access violation

That's weird. I've built master for windows and tested it successfully for a while less than a week ago. I'm sure it can be caused by wrong compiler circumstances, but to troubleshoot this we need more information (as @jonasschnelli already says). Note that we use Ubuntu 14.04 for building the windows executable (both on travis as for the gitian release), older or newer mingw-w64 versions aren't regularly tested.

**Comment by laanwj** [comment] 2016-07-11 10:27
> In general, you can easily cross-compile OSX and windows binaries on ubuntu/linux.

For information about OSX building see also:https://github.com/bitcoin/bitcoin/blob/master/doc/README_osx.md

**Comment by fanquake** [comment] 2016-09-02 11:42
Closing as no new information has been posted, and using the depends system was suggested.

**Closed by fanquake** 2016-09-02 11:42 UTC
Labels: Build system
