### ISSUE TITLE
No mempool data display in 0.19.0.1 (64 bits / Windows)

### ISSUE THREAD

**Issue by jpis** [bitcoin/bitcoin#17684] opened 2019-12-06 16:35 UTC
Since I installed **0.19.0.1** (over 0.18.0.1) the number of transactions of the Mempool and corresponding memory now show both N.D. instead of the real values). This is of course in Information Window / Informations.

**Expected behavior**
Values should be displayed as in previous releases

**Actual behavior**

**To reproduce**

**System information**

 0.19.0.1

Windows 4 cores SSD disk

Windows 10 pro. fully patched.

All previous version of bitcoin Core were correctly displaying mempool info

**Comment by fanquake** [comment] 2019-12-06 16:36
Thanks. This is a duplicate of #17576, and will be fixed in 0.19.1.

**Closed by fanquake** 2019-12-06 16:36 UTC
Labels: Bug

**Comment by jpis** [comment] 2019-12-06 16:45
This was indeed a known bug. Thanks to fanquake!
