### ISSUE TITLE
Intermittent CI failure: "Transaction not eligible for abandonment (-5)" when running feature_backwards_compatibility.py --descriptors

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#21352] opened 2021-03-03 16:09 UTC
Intermittent CI failure: "Transaction not eligible for abandonment (-5)" when running `feature_backwards_compatibility.py --descriptors`.

See [Cirrus CI log](https://cirrus-ci.com/task/4642640135192576?command=ci#L1067) for details.

```
…
2021-03-03T15:48:25.376000Z TestFramework (INFO): Test wallet backwards compatibility...
2021-03-03T15:49:20.236000Z TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 128, in main
    self.run_test()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_backwards_compatibility.py", line 109, in run_test
    self.nodes[1].abandontransaction(tx3_id)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/coverage.py", line 47, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/authproxy.py", line 146, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: Transaction not eligible for abandonment (-5)
```

**Comment by fanquake** [comment] 2021-03-03 22:29
Looks like a duplicate of #18831. Can you add any additional info there instead.

**Closed by fanquake** 2021-03-03 22:29 UTC
Labels: Bug
