### ISSUE TITLE
bitcoin.conf assumevalid=0 does not seem to be working

### ISSUE THREAD

**Issue by Linrono** [bitcoin/bitcoin#16268] opened 2019-06-22 15:31 UTC
assumevalid=0 does not seem to work when it is in the bitcoin.conf file but does when set as a cli argument.

I thought setting this in the config file would be enough to set this value.

When set in the config file, the log says it is still using the default hex value. It does work when set as a command line argument. 
![Screenshot from 2019-06-22 11-13-43](https://user-images.githubusercontent.com/24950563/59965734-09d43c80-94e0-11e9-914e-e741cec01a0c.png)
![Screenshot from 2019-06-22 11-13-26](https://user-images.githubusercontent.com/24950563/59965735-148ed180-94e0-11e9-9c90-9e53427b41c3.png)
![Screenshot from 2019-06-22 11-08-37](https://user-images.githubusercontent.com/24950563/59965737-1bb5df80-94e0-11e9-86a5-d0fe63457c4a.png)

Just setting the config option without the command line argument recreates the issue. I did test my config file by removing the dbcache setting and that was reflected in the logs.
![Screenshot from 2019-06-22 11-26-23](https://user-images.githubusercontent.com/24950563/59965803-e65dc180-94e0-11e9-8031-a26d69eb8cca.png)
![Screenshot from 2019-06-22 11-26-32](https://user-images.githubusercontent.com/24950563/59965805-eb227580-94e0-11e9-80ac-323d622d0029.png)

I am using the downloaded release version 18.0.

I am using a laptop with Ubuntu and a platter hard drive.

**Comment by MarcoFalke** [comment] 2019-06-22 15:35
Could just be an issue that might be fixed by moving the print statement after the config files and include files have been parsed?

**Comment by gertjaap** [comment] 2019-06-24 13:00
I have just tried this, and I cannot reproduce it:

```
gertjaap@gjdesktop:~/src/bitcoin$ cat ~/.bitcoin/bitcoin.conf
assumevalid=0
gertjaap@gjdesktop:~/src/bitcoin$ bitcoind
2019-06-24T13:00:03Z Bitcoin Core version v0.18.0.0-g2472733a24a9364e4c6233ccd04166a26a68cc65 (release build)
2019-06-24T13:00:03Z Validating signatures for all blocks.
```

Are you sure the `bitcoin.conf` file is in the correct folder?

**Comment by Linrono** [comment] 2019-06-29 00:38
@MarcoFalke That could fix it, I am not sure. I haven't really dived into the code for this. 

@gertjaap Yes I am sure my bitcoin.conf is in the correct folder, I had tested it with the dbcache setting with my last two screenshots.

**Comment by Linrono** [comment] 2019-06-29 01:22
![Screenshot from 2019-06-28 21-04-50](https://user-images.githubusercontent.com/24950563/60377988-02ce9200-99ea-11e9-8ad3-d8fe1b4eff57.png)

Does this help show my setup?

**Comment by Linrono** [comment] 2019-06-29 02:37
I have been trying to figure this out in the code. 
It looks like bitcoind.cpp calls ReadConfigFiles() which loads the config file before it calls AppInitParameterInteraction() which seems to be where this line in the output comes from so we can't move it after the loading of the config file because it already is.
AppInitParameterInteraton() starts using hashAssumeValid at line 1042 in init.cpp. It calls GetArg with -assumevalid and the default value. It should either return the number 0 or the string 0. Instead, it is pulling the value from chainparams.cpp. 
I can not seem to figure out why.
I do not see any obvious changes to init.cpp since the release I am using that would affect this.

**Comment by gertjaap** [comment] 2019-07-03 12:53
@Linrono tried with the exact same settings, but can't reproduce it. 

```gertjaap@gjdesktop:~$ cat ~/.bitcoin/bitcoin.conf
assumevalid=0
server=1
txindex=1
dbcache=2000
gertjaap@gjdesktop:~$ bitcoind
2019-07-03T12:51:36Z Bitcoin Core version v0.18.0.0-g2472733a24a9364e4c6233ccd04166a26a68cc65 (release build)
2019-07-03T12:51:36Z Validating signatures for all blocks.
2019-07-03T12:51:36Z Setting nMinimumChainWork=0000000000000```

Could you do `hexdump ~/.bitcoin/bitcoin.conf` just to ensure there's nothing funky in the file i'm not reproducing?

**Comment by Linrono** [comment] 2019-07-04 23:51
![Screenshot from 2019-07-04 19-46-09](https://user-images.githubusercontent.com/24950563/60690364-eec8db80-9e94-11e9-92be-9270856436dd.png)
I'm sorry I'm using screenshots, I don't know how to do the horizontal quote boxes.
Is it with the grave marks? (`)

**Comment by hebasto** [comment] 2019-07-05 02:50
@Linrono 

> I'm sorry I'm using screenshots, I don't know how to do the horizontal quote boxes.
> Is it with the grave marks? (`)

https://help.github.com/en/articles/basic-writing-and-formatting-syntax#quoting-code

**Comment by Linrono** [comment] 2019-07-09 04:38
```
linrono@toaster:~$ hexdump /home/linrono/.bitcoin/bitcoin.conf 
0000000 bbef 61bf 7373 6d75 7665 6c61 6469 303d
0000010 730a 7265 6576 3d72 0a31 7874 6e69 6564
0000020 3d78 0a31 6264 6163 6863 3d65 3032 3030
0000030 000a                                   
0000031
linrono@toaster:~$ cat /home/linrono/.bitcoin/bitcoin.conf 
assumevalid=0
server=1
txindex=1
dbcache=2000
linrono@toaster:~$ bitcoind
2019-07-09T04:35:52Z Bitcoin Core version v0.18.0 (release build)
2019-07-09T04:35:52Z Assuming ancestors of block 0000000000000000000f1c54590ee18d15ec70e68c8cd4cfbadb1b4f11697eee have valid signatures.
2019-07-09T04:35:52Z Setting nMinimumChainWork=0000000000000000000000000000000000000000051dc8b82f450202ecb3d471
2019-07-09T04:35:52Z Using the 'sse4(1way),sse41(4way)' SHA256 implementation
2019-07-09T04:35:53Z Default data directory /home/linrono/.bitcoin
2019-07-09T04:35:53Z Using data directory /home/linrono/.bitcoin
2019-07-09T04:35:53Z Config file: /home/linrono/.bitcoin/bitcoin.conf
```
There we go, thanks.

**Comment by Linrono** [comment] 2019-07-09 23:41
@gertjapp
You called it. Ended up being something wrong with the line that caused it to not work. I'm not sure how I did that. 
Thank you for you guys' help.

**Closed** 2019-07-09 23:41 UTC
Labels: Questions and Help
