### ISSUE TITLE
dumpwallet should contain warning texts

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#11294] opened 2017-09-09 21:03 UTC
The `dumpwallet` command currently writes out all keys, including the hd seed. In case there are keys in the wallet that are not derivable from that seed, a warning should be included to explain that that seed on itself is not enough to backup the wallet.

**Comment by MarcoFalke** [comment] 2017-09-09 21:12
Duplicate of #11243

**Closed by MarcoFalke** 2017-09-09 21:12 UTC

**Comment by sipa** [comment] 2017-09-09 22:16
Oops, thanks
