### ISSUE TITLE
Wallet rescan multiple wallets

### ISSUE THREAD

**Issue by muaamen** [bitcoin/bitcoin#23779] opened 2021-12-15 07:24 UTC
Why does rescanblockchain not scan many wallets the same time? It can only scan one (inefficient when requiring to scan multiple wallets).

**Comment by darosior** [comment] 2021-12-15 09:22
Yes, this has been mentioned in #23727. Do we need a separate tracking issue for this specific feature?

**Comment by fanquake** [comment] 2021-12-15 09:24
This is a duplicate of #11756 in any case.

**Closed by fanquake** 2021-12-15 09:24 UTC
Labels: Feature
