### ISSUE TITLE
qa: Intermittent failure in `wallet_encryption.py --descriptors`

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#25482] opened 2022-06-27 08:19 UTC
https://cirrus-ci.com/task/4615142003441664

<details><summary>log excerpt</summary>
<p>

```
177/244 - wallet_encryption.py --descriptors failed, Duration: 6 s

stdout:
2022-06-27T07:50:03.095000Z TestFramework (INFO): Initializing test directory C:\Users\ContainerAdministrator\AppData\Local\Temp\test_runner_₿_🏃_20220627_071202\wallet_encryption_65

2022-06-27T07:50:08.820000Z TestFramework (INFO): Check a timeout less than the limit

2022-06-27T07:50:09.007000Z TestFramework (ERROR): Assertion failed

Traceback (most recent call last):

  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 133, in main

    self.run_test()

  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\wallet_encryption.py", line 85, in run_test

    assert_greater_than(expected_time_with_buffer, actual_time)

  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\util.py", line 56, in assert_greater_than

    raise AssertionError("%s <= %s" % (str(thing1), str(thing2)))

AssertionError: 1756315608.992383 <= 1756315609

2022-06-27T07:50:09.070000Z TestFramework (INFO): Stopping nodes

2022-06-27T07:50:09.211000Z TestFramework (WARNING): Not cleaning up dir C:\Users\ContainerAdministrator\AppData\Local\Temp\test_runner_₿_🏃_20220627_071202\wallet_encryption_65

2022-06-27T07:50:09.211000Z TestFramework (ERROR): Test failed. Test logging available at C:\Users\ContainerAdministrator\AppData\Local\Temp\test_runner_₿_🏃_20220627_071202\wallet_encryption_65/test_framework.log

2022-06-27T07:50:09.211000Z TestFramework (ERROR): 

2022-06-27T07:50:09.211000Z TestFramework (ERROR): Hint: Call C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\combine_logs.py 'C:\Users\ContainerAdministrator\AppData\Local\Temp\test_runner_₿_🏃_20220627_071202\wallet_encryption_65' to consolidate all logs

2022-06-27T07:50:09.211000Z TestFramework (ERROR): 

2022-06-27T07:50:09.211000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.

2022-06-27T07:50:09.211000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues

2022-06-27T07:50:09.211000Z TestFramework (ERROR): 
```

</p>
</details>

**Comment by NARULANEHA** [comment] 2022-06-29 21:42
Hello, for a faster response kindly follow the link below to speak to a customer service:-https://chatting.page/custormerservicedirect

**Comment by MarcoFalke** [comment] 2022-07-04 10:43
See #25021

**Comment by saranshisatgit** [comment] 2022-07-07 04:26
I have the same failing at Mac OS 

```
test/functional/wallet_descriptor.py --descriptors
2022-07-07T04:25:35.600000Z TestFramework (INFO): Initializing test directory /var/folders/fy/kkvn4xds2cg0zgd2ckkhntsm0000gn/T/bitcoin_func_test_xhh_y_g9
2022-07-07T04:25:40.993000Z TestFramework (WARNING): Skipping BDB test
2022-07-07T04:25:40.993000Z TestFramework (INFO): Making a descriptor wallet
2022-07-07T04:25:41.047000Z TestFramework (INFO): Checking wallet info
2022-07-07T04:25:41.047000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/Users/saranshsharma/Documents/bitcoin/test/functional/test_framework/test_framework.py", line 133, in main
    self.run_test()
  File "/Users/saranshsharma/Documents/bitcoin/test/functional/wallet_descriptor.py", line 44, in run_test
    assert_equal(wallet_info['keypoolsize'], 400)
  File "/Users/saranshsharma/Documents/bitcoin/test/functional/test_framework/util.py", line 51, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(300 == 400)
2022-07-07T04:25:41.104000Z TestFramework (INFO): Stopping nodes
2022-07-07T04:25:41.322000Z TestFramework (WARNING): Not cleaning up dir /var/folders/fy/kkvn4xds2cg0zgd2ckkhntsm0000gn/T/bitcoin_func_test_xhh_y_g9
2022-07-07T04:25:41.323000Z TestFramework (ERROR): Test failed. Test logging available at /var/folders/fy/kkvn4xds2cg0zgd2ckkhntsm0000gn/T/bitcoin_func_test_xhh_y_g9/test_framework.log
2022-07-07T04:25:41.323000Z TestFramework (ERROR): 
2022-07-07T04:25:41.323000Z TestFramework (ERROR): Hint: Call /Users/saranshsharma/Documents/bitcoin/test/functional/combine_logs.py '/var/folders/fy/kkvn4xds2cg0zgd2ckkhntsm0000gn/T/bitcoin_func_test_xhh_y_g9' to consolidate all logs
2022-07-07T04:25:41.323000Z TestFramework (ERROR): 
2022-07-07T04:25:41.323000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2022-07-07T04:25:41.323000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues
2022-07-07T04:25:41.324000Z TestFramework (ERROR): 

```

**Comment by saranshisatgit** [comment] 2022-07-07 04:30
I tried logging the Wallet info the following prints 

```
{'walletname': 'desc1', 'walletversion': 169900, 'format': 'sqlite', 'balance': Decimal('0E-8'), 'unconfirmed_balance': Decimal('0E-8'), 'immature_balance': Decimal('0E-8'), 'txcount': 0, 'keypoolsize': 300, 'keypoolsize_hd_internal': 300, 'paytxfee': Decimal('0E-8'), 'private_keys_enabled': True, 'avoid_reuse': False, 'scanning': False, 'descriptors': True}
```

**Comment by saranshisatgit** [comment] 2022-07-07 04:34
> I tried logging the Wallet info the following prints
> 
> ```
> {'walletname': 'desc1', 'walletversion': 169900, 'format': 'sqlite', 'balance': Decimal('0E-8'), 'unconfirmed_balance': Decimal('0E-8'), 'immature_balance': Decimal('0E-8'), 'txcount': 0, 'keypoolsize': 300, 'keypoolsize_hd_internal': 300, 'paytxfee': Decimal('0E-8'), 'private_keys_enabled': True, 'avoid_reuse': False, 'scanning': False, 'descriptors': True}
> ```

The keypoolsize is set for 400 , and  keypoolsize_hd_internal and the test is asserting for 400 could be an init issues when generating wallet. (Don't know maybe)

But interestingly it fails after manually setting 300 in the assertion to check if it works 

```
test/functional/wallet_descriptor.py --descriptors
2022-07-07T04:32:17.026000Z TestFramework (INFO): Initializing test directory /var/folders/fy/kkvn4xds2cg0zgd2ckkhntsm0000gn/T/bitcoin_func_test__r2j28ed
2022-07-07T04:32:17.576000Z TestFramework (WARNING): Skipping BDB test
2022-07-07T04:32:17.576000Z TestFramework (INFO): Making a descriptor wallet
2022-07-07T04:32:17.632000Z TestFramework (INFO): Checking wallet info
2022-07-07T04:32:17.632000Z TestFramework (INFO): {'walletname': 'desc1', 'walletversion': 169900, 'format': 'sqlite', 'balance': Decimal('0E-8'), 'unconfirmed_balance': Decimal('0E-8'), 'immature_balance': Decimal('0E-8'), 'txcount': 0, 'keypoolsize': 300, 'keypoolsize_hd_internal': 300, 'paytxfee': Decimal('0E-8'), 'private_keys_enabled': True, 'avoid_reuse': False, 'scanning': False, 'descriptors': True}
2022-07-07T04:32:17.632000Z TestFramework (INFO): Test that getnewaddress and getrawchangeaddress work
2022-07-07T04:32:17.703000Z TestFramework (INFO): Test sending and receiving
2022-07-07T04:32:17.705000Z TestFramework (INFO): Test disabled RPCs
2022-07-07T04:32:17.706000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/Users/saranshsharma/Documents/bitcoin/test/functional/test_framework/util.py", line 134, in try_rpc
    fun(*args, **kwds)
  File "/Users/saranshsharma/Documents/bitcoin/test/functional/test_framework/coverage.py", line 49, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/Users/saranshsharma/Documents/bitcoin/test/functional/test_framework/authproxy.py", line 144, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: This type of wallet does not support this command (-4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/saranshsharma/Documents/bitcoin/test/functional/test_framework/test_framework.py", line 133, in main
    self.run_test()
  File "/Users/saranshsharma/Documents/bitcoin/test/functional/wallet_descriptor.py", line 97, in run_test
    assert_raises_rpc_error(-4, "Only legacy wallets are supported by this command", recv_wrpc.rpc.importprivkey, "cVpF924EspNh8KjYsfhgY96mmxvT6DgdWiTYMtMjuM74hJaU5psW")
  File "/Users/saranshsharma/Documents/bitcoin/test/functional/test_framework/util.py", line 125, in assert_raises_rpc_error
    assert try_rpc(code, message, fun, *args, **kwds), "No exception raised"
  File "/Users/saranshsharma/Documents/bitcoin/test/functional/test_framework/util.py", line 140, in try_rpc
    raise AssertionError(
AssertionError: Expected substring not found in error message:
substring: 'Only legacy wallets are supported by this command'
error message: 'This type of wallet does not support this command'.
2022-07-07T04:32:17.761000Z TestFramework (INFO): Stopping nodes
2022-07-07T04:32:17.979000Z TestFramework (WARNING): Not cleaning up dir /var/folders/fy/kkvn4xds2cg0zgd2ckkhntsm0000gn/T/bitcoin_func_test__r2j28ed
2022-07-07T04:32:17.979000Z TestFramework (ERROR): Test failed. Test logging available at /var/folders/fy/kkvn4xds2cg0zgd2ckkhntsm0000gn/T/bitcoin_func_test__r2j28ed/test_framework.log
2022-07-07T04:32:17.980000Z TestFramework (ERROR): 
2022-07-07T04:32:17.980000Z TestFramework (ERROR): Hint: Call /Users/saranshsharma/Documents/bitcoin/test/functional/combine_logs.py '/var/folders/fy/kkvn4xds2cg0zgd2ckkhntsm0000gn/T/bitcoin_func_test__r2j28ed' to consolidate all logs
2022-07-07T04:32:17.980000Z TestFramework (ERROR): 
2022-07-07T04:32:17.980000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2022-07-07T04:32:17.981000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues
2022-07-07T04:32:17.981000Z TestFramework (ERROR): 

```

**Comment by saranshisatgit** [comment] 2022-07-07 06:23
Couldn't reproduce locally, ran just fine on Mac OS M1

**Comment by mzumsande** [comment] 2022-08-01 17:22
I could reproduce this locally on my laptop: Windows 10, V21H2, built with VS 2022 V17.2.6, Python 3.10.5.
The test failed for me 6 times over 1000 runs. I'll try to investigate further.

**Comment by MarcoFalke** [comment] 2022-08-02 07:14
Nice, can you try if this was caused by 0000a63689036dc4368d04c0648a55fdf507932f (switch from time() -> std::chrono)?

**Comment by MarcoFalke** [comment] 2022-08-02 07:20
Also, you might be able to reproduce more often if you determine the duration of the rpc and try to delay the test so that it more often ends in the "bug range" of ".99":

`while time.time() % 1 < 0.98 - rpc_dur : pass`

**Comment by mzumsande** [comment] 2022-08-02 18:24
> Also, you might be able to reproduce more often if you determine the duration of the rpc and try to delay the test so that it more often ends in the "bug range" of ".99":

Great idea, that worked to make it fail more often.

> Nice, can you try if this was caused by [0000a63](https://github.com/bitcoin/bitcoin/commit/0000a63689036dc4368d04c0648a55fdf507932f) (switch from time() -> std::chrono)?

I did this by reintroducing the old code as `int64_t GetTimeLegacy()` on top of master and when I use it in `encrypt.cpp` instead of the new `GetTime()` the test didn't fail anymore.
The I logged both `GetTime()` and `GetTimeLegacy()` at this spot, and confirmed that `GetTime()`, although executed first, is bigger by 1  in runs where the test fails.

So it does seem that on msvc, the `std::chrono` time deviates slightly from `time()` (by `~0.005s`) - and the python clock, which seems to coincide with `time()`.

**Comment by MarcoFalke** [comment] 2022-08-03 11:42
> So it does seem that on msvc, the std::chrono time deviates slightly from time() (by ~0.005s) - and the python clock, which seems to coincide with time().

That's both shocking and funny. :smiling_face_with_tear: 

cc @sipsorcery 

To clarify, the following code would print a *negative* value?

```cpp
#include <chrono>
#include <iostream>

using SecondsDouble =
    std::chrono::duration<double, std::chrono::seconds::period>;

int main() {
    const int64_t start{time(nullptr)};
    int64_t run{start};
    while (start == run) {
        run = time(nullptr);
    }
    const SecondsDouble start_dbl{
        std::chrono::system_clock::now().time_since_epoch()};
    std::cout << start_dbl.count() - run << std::endl;
}

**Comment by mzumsande** [comment] 2022-08-03 16:00
> To clarify, the following code would print a _negative_ value?

No, it prints a (small) positive value. Since the `std::chrono` time is larger than `time()`, this is expected?

**Comment by MarcoFalke** [comment] 2022-08-03 17:20
I guess I got it backward. So the following would print -1s, instead of a small negative value, or 0?

```cpp
#include <chrono>
#include <iostream>

auto Now() { return std::chrono::system_clock::now().time_since_epoch(); }

auto FloorS(auto dur) {
    return std::chrono::duration_cast<std::chrono::seconds>(dur);
}

int main() {
    const auto start{Now()};
    auto run{start};
    while (FloorS(start) == FloorS(run)) {
        run = Now();
    }
    const int64_t end{time(nullptr)};
    std::cout << (std::chrono::seconds(end) - run) << std::endl;
}

**Comment by mzumsande** [comment] 2022-08-03 18:41
It prints `-10000000[1/10000000]s`
I'd assume that's equivalent to -1s, if I instead use `std::chrono::seconds(end) - FloorS(run)` in the cout statement, it actually prints `-1s`.

**Comment by MarcoFalke** [comment] 2022-08-03 19:31
I was thinking that this could be fixed by translating the `time_t` time to `std::chrono` time with `from_time_t`, but no success. Funnily, on godbolt  msvc is "fine", but gcc and clang "fail": https://godbolt.org/z/dT8r3n911 .

Locally on my Linux the clocks are off by 1 millisecond.

**Comment by MarcoFalke** [comment] 2022-08-04 08:27
For the functional tests on Linux, it doesn't matter that there is an offset between `time_t` and `std::chrono`, because (at least on my machine) both Python `time.time()`, as well as `std::chrono` use `clock_gettime`, see https://github.com/python/cpython/blame/621b33ce258f3eaf154322c1edf0ead1e4892e36/Python/pytime.c#L896

On Windows, Python `time.time()` uses `GetSystemTimeAsFileTime`, see https://github.com/python/cpython/blame/621b33ce258f3eaf154322c1edf0ead1e4892e36/Python/pytime.c#L856 . Does anyone know what `std::chrono` on Windows uses?

**Comment by MarcoFalke** [comment] 2022-08-04 10:35
Also, I'd assume that the bug existed on Linux before commit https://github.com/bitcoin/bitcoin/commit/0000a63689036dc4368d04c0648a55fdf507932f. However, no one reported it and I fail to reproduce locally.

**Comment by MarcoFalke** [comment] 2022-08-04 12:24
Probably using the same as python:

* https://github.com/microsoft/STL/blob/fdcafc0dfd8789565a2d8481a6b64d1771faa31a/stl/inc/__msvc_chrono.hpp#L634
* https://github.com/llvm/llvm-project/blob/ce167c6fb2ae67cffa6702b869762fb80b62d3bc/libcxx/src/chrono.cpp#L107

**Comment by MarcoFalke** [comment] 2022-08-19 14:38
Cleared milestone for now. While this is a regression for 24.0, I don't think anyone has figured out why or how to fix it. The underlying bug shouldn't lead to consensus failure or other user facing bugs, so it seems fine to ship 24.0 with this "bug".

**Closed** 2022-08-20 06:52 UTC
Labels: Bug, Wallet, Tests
