### ISSUE TITLE
Installation issue with make

### ISSUE THREAD

**Issue by jeremyreikes** [bitcoin/bitcoin#9546] opened 2017-01-13 20:01 UTC
When I do make I get the following error.  Any idea what the issue is?

make
Making all in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in .
  CXX      net.o
net.cpp:1066:15: error: no matching function for call to 'upnpDiscover'
    devlist = upnpDiscover(2000, multicastif, minissdpdpath, 0, 0, &error);
              ^~~~~~~~~~~~
/usr/local/include/miniupnpc/miniupnpc.h:62:1: note: candidate function not
      viable: requires 7 arguments, but 6 were provided
upnpDiscover(int delay, const char * multicastif,
^
1 error generated.
make[3]: *** [net.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

**Comment by paveljanik** [comment] 2017-01-13 20:30
Duplicate of https://github.com/bitcoin/bitcoin/issues/8967?

**Comment by theuni** [comment] 2017-01-13 20:36
Yes. @jeremyreikes why building such an old version? This has been unsupported for a long time.

For reference: the line number matches up with 0.9: https://github.com/bitcoin/bitcoin/blob/0.9/src/net.cpp#L1066

**Comment by jeremyreikes** [comment] 2017-01-13 20:39
I am building the newest version, so that cannot be the issue.

**Comment by sipa** [comment] 2017-01-13 20:48
The line your compiler complains about is net.cpp:1066 with a call to `upnpDiscover`. Neither in master, nor 0.13.2, nor any of the 0.13, 0.12, 0.11, 0.10 branches does such a call appear on that line. You're most definitely not building the latest version.

**Closed** 2017-02-07 12:28 UTC
Labels: Questions and Help
