### ISSUE TITLE
Manual coin control dialog interacts badly with multiple wallets

### ISSUE THREAD

**Issue by gwillen** [bitcoin/bitcoin#15725] opened 2019-04-03 08:24 UTC
The coin control dialog has a single static CCoinControl object (declared in CoinControlDialog::coinControl) that it uses for all purposes.

This causes an inappropriate mixing of state between different wallets, when multiple are loaded at the same time and you flip back and forth between them while using coin control on the sending page.

For example, pick a wallet, use coin control to select a UTXO, hit OK. Then switch to a different wallet -- so far nothing will be wrong -- but now open coin control again. The UTXO in the other wallet is still selected (it will show in the summary at the top), but is not visible and can't be unselected. If you now click 'ok', the main send pane will show that there is a UTXO (from the other wallet) selected.

I can't reproduce this 100% reliably, but if I have several wallets open I can reliably make "weird broken shit" happen with a few tries.

When I try to perform a send in this state (having selected a UTXO that does not belong to the current wallet) I get an insufficient balance error (even though both the current wallet and the selected UTXO have sufficient balance.)

I think the only reasonable and correct way to fix this is to rip out the static CCoinControl object, and replace it with a per-wallet one. I am happy to do this ... at some point.

**Comment by promag** [comment] 2019-04-03 08:32
Thanks for the report, I can take a look too.

**Comment by gwillen** [comment] 2019-04-04 19:24
Suggested "known issue" text for 0.18 release: something like the following.

"For advanced users who BOTH (1) have enabled coin control features, and (2) are using multiple wallets: The coin control input selection dialog can erroneously retain wrong-wallet state when switching wallets. For now, it is recommended not to use coin control features with multiple wallets loaded."

**Comment by MarcoFalke** [comment] 2019-04-04 21:05
See https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.18.0-Release-Notes-Draft#known-issues

**Comment by gwillen** [comment] 2019-04-04 21:18
Should I link the issue in the release notes? Is just "See #15725" sufficient, or how is that normally done?

**Comment by promag** [comment] 2019-04-05 22:03
I can't reproduce at all.

Sometimes, maybe with a specific Qt version (IDK), some widgets fail to refresh when, for instance, the current wallet is changed. In those cases usually resizing the window causes the repaint.

So, if you manage to reproduce:
 1. share the steps
 2. check if it isn't a Qt problem.

BTW, agree that this could be improved (even if it's not the cause of your issue): https://github.com/bitcoin/bitcoin/blob/35991b162fd142d76d83e672002846c8a40eb794/src/qt/coincontroldialog.h#L55

**Comment by gwillen** [comment] 2019-04-05 22:25
I do get the Qt widget refresh problem on this machine (I filed a bug report about it at one point, and I was not aware then of anybody else ever seeing it; perhaps I'm the only one?)

I'm pretty sure this is not that, though. Resizing the window doesn't make any difference, and the issue is not purely visual (i.e. when I'm in the state where zero of three UTXOs displayed are checked, and the top of the window says "Quantity: 1", I can check all three and get the window to read "Quantity: 4" with all three boxes checked.)

**Comment by promag** [comment] 2019-04-14 14:19
@gwillen thanks, I'll try to reproduce that.

**Comment by promag** [comment] 2019-11-12 00:17
Can I get this assigned to me?

**Comment by Sjors** [comment] 2019-11-19 18:59
I'm able to reproduce "weird" behavior, i.e. coins selected in one wallet showing up in another. Will look at the fix PR.

**Comment by hebasto** [comment] 2020-05-06 02:20
I can reliably reproduce the issue:

![DeepinScreenshot_bitcoin-qt_20200506051916](https://user-images.githubusercontent.com/32963518/81133075-3870cf80-8f59-11ea-93bc-0ab56bfc1b95.png)

**Closed** 2020-05-13 08:15 UTC
Labels: GUI, Wallet
