### ISSUE TITLE
Failed loading mempool when restarting bitcoind

### ISSUE THREAD

**Issue by dev7ba** [bitcoin/bitcoin#29193] opened 2024-01-06 10:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

After a clean shutdown, bitcoind failed to load the majority of mempool transactions from mempool.dat. I keep a node up for months for webpage mempoolexplorer.com with options:
maxmempool=2000
mempoolfullrbf=1
mempoolexpiry=999999
to maximize the number of txs in my mempool.
The node is currently loading and saving mempool txs when shutdown ok (but with only a small number of them instead of a fully synchronized mempool). So I think It could be related to the currently mempool size spike. (larger than ever according [jochen-hoenicke](https://jochen-hoenicke.de/queue/#BTC,all,weight) )

### Expected behaviour

The expected behavior is to save/load all the transactions again no matter the size of the mempool

### Steps to reproduce

It's a issue difficult to reproduce, because I have no access to a node syncronized with "the full mempool" since mine failed.

In order to reproduce the issue you must have access to a big mempool and try to start/stop bitcoind and monitor mempool.dat. (Mine is currenty erased and only with a few transactions)

Not sure if the problem was writing the txs into mempool.dat or reading them.

Maybe this utility I created can help copying a live mempool from one node to another:

https://github.com/dev7ba/mempoolcp

### Relevant log output

I did not copy the debug.log line (currently erased) but it was something like this:

Imported mempool transactions from disk: (small number here) succeeded, (big number here) failed, 0 expired, 0 already there, 0 waiting for initial broadcast

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

v24.0.0

### Operating system and version

Ubuntu 20.04.6 LTS

### Machine specifications

Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz 16GB RAM

**Comment by glozow** [comment] 2024-01-06 10:32
Hard to guess without logs (which would tell us why transactions failed). How much time elapsed between saving the mempool.dat and loading it? Mempool transactions that had confirmed during that time would be marked as "failed."

And to clarify, are you restarting with the same config? What are mempoolexpiry and maxmempool now? (Is it possible you have less space or expired old transactions?)

> Not sure if the problem was writing the txs into mempool.dat or reading them.

Must be loading given the "X failed" log line.

> v24.0.0

Maybe try upgrading to a newer version?

**Comment by dev7ba** [comment] 2024-01-06 10:46
> How much time elapsed between saving the mempool.dat and loading it?
Only a few minutes.

> And to clarify, are you restarting with the same config? What are mempoolexpiry and maxmempool now?

I restarted with the same config. Checked I have enough disk space.

> Must be loading given the "X failed" log line.
Yes, I see.
> Maybe try upgrading to a newer version?
I can't test it anyway, I'm trying to contact people with a "full mempool", And asking them to restart the node and see what happens.

**Comment by deyw-bit** [comment] 2024-01-11 10:14
I can confirm a similar issue in a node running Bitcoin Core 25.1, as detailed below:

Config options:
- maxmempool=2000
- mempoolexpiry=720
- mempoolfullrbf=1

Prior to the node's restart, the mempool size was approximately 1.14 GB, which filled up over roughly 26 hours of uptime since the last node restart.

After initiating the shutdown, the node restarted immediately. According to the logs, the mempool was dumped ("Dumped mempool: 1.0479s to copy, 10.5051s to dump"). However, there are no subsequent details indicating that the mempool data was reloaded post-restart. 

Three minutes following the restart, the mempool size was merely 1MB. Ten minutes later, it increased to 18MB and continued to grow gradually, accumulating unconfirmed transactions. After one hour of uptime, the mempool size reached 110MB, with approximately 18,000 pending transactions. 

How did you obtain Bitcoin Core
Pre-built binaries: (https://bitcoincore.org/bin/bitcoin-core-25.1/bitcoin-25.1-x86_64-linux-gnu.tar.gz)

What version of Bitcoin Core are you using?
v25.1

Operating system and version
Debian GNU/Linux 12 (bookworm)

Machine specifications
Synology NAS (node running in Docker)

debug.log (for the one hour starting with the node shutdown): 

2024-01-11T08:47:38Z [net] Saw new cmpctblock header hash=00000000000000000000f180479aa02c5d3f955360d63bf891378571a6c5db8f peer=26749
2024-01-11T08:47:39Z UpdateTip: new best=00000000000000000000f180479aa02c5d3f955360d63bf891378571a6c5db8f height=825273 version=0x30000000 log2_work=94.658974 tx=950494268 date='2024-01-11T08:47:22Z' progress=1.000000 cache=193.5MiB(1114879txo)
2024-01-11T08:55:47Z tor: Thread interrupt
2024-01-11T08:55:47Z Shutdown: In progress...
2024-01-11T08:55:47Z addcon thread exit
2024-01-11T08:55:47Z torcontrol thread exit
2024-01-11T08:55:47Z opencon thread exit
2024-01-11T08:55:47Z msghand thread exit
2024-01-11T08:55:47Z net thread exit
2024-01-11T08:55:47Z DumpAnchors: Flush 2 outbound block-relay-only peer addresses to anchors.dat started
2024-01-11T08:55:48Z DumpAnchors: Flush 2 outbound block-relay-only peer addresses to anchors.dat completed (0.40s)
2024-01-11T08:55:48Z scheduler thread exit
2024-01-11T08:55:51Z Writing 0 unbroadcast transactions to disk.
2024-01-11T08:55:57Z Dumped mempool: 0.643629s to copy, 8.92166s to dump
2024-01-11T08:55:57Z Flushed fee estimates to fee_estimates.dat.
2024-01-11T08:56:11Z Shutdown: done

>>> RESTART

2024-01-11T08:56:21Z Bitcoin Core version v25.1.0 (release build)
2024-01-11T08:56:21Z Using the 'sse4(1way),sse41(4way)' SHA256 implementation
2024-01-11T08:56:21Z Using RdRand as an additional entropy source
2024-01-11T08:56:21Z Default data directory /root/.bitcoin
2024-01-11T08:56:21Z Using data directory /root/.bitcoin
2024-01-11T08:56:21Z Config file: /root/.bitcoin/bitcoin.conf
2024-01-11T08:56:21Z Config file arg: blockfilterindex="1"
2024-01-11T08:56:21Z Config file arg: coinstatsindex="1"
2024-01-11T08:56:21Z Config file arg: disablewallet="1"
2024-01-11T08:56:21Z Config file arg: listen="1"
2024-01-11T08:56:21Z Config file arg: maxconnections="200"
2024-01-11T08:56:21Z Config file arg: maxmempool="2000"
2024-01-11T08:56:21Z Config file arg: mempoolexpiry="720"
2024-01-11T08:56:21Z Config file arg: mempoolfullrbf="1"
2024-01-11T08:56:21Z Config file arg: peerblockfilters="1"
2024-01-11T08:56:21Z Config file arg: peerbloomfilters="1"
2024-01-11T08:56:21Z Config file arg: port="8333"
2024-01-11T08:56:21Z Config file arg: printtoconsole="1"
2024-01-11T08:56:21Z Config file arg: rest="1"
2024-01-11T08:56:21Z Config file arg: rpcallowip="0.0.0.0/0"
2024-01-11T08:56:21Z Config file arg: rpcauth=****
2024-01-11T08:56:21Z Config file arg: rpcbind="127.0.0.1:8332"
2024-01-11T08:56:21Z Config file arg: rpcbind="172.17.0.2:8332"
2024-01-11T08:56:21Z Config file arg: rpcport="8332"
2024-01-11T08:56:21Z Config file arg: server="1"
2024-01-11T08:56:21Z Config file arg: testnet="0"
2024-01-11T08:56:21Z Config file arg: txindex="1"
2024-01-11T08:56:21Z Using at most 200 automatic connections (1048576 file descriptors available)
2024-01-11T08:56:21Z Using 16 MiB out of 16 MiB requested for signature cache, able to store 524288 elements
2024-01-11T08:56:21Z Using 16 MiB out of 16 MiB requested for script execution cache, able to store 524288 elements
2024-01-11T08:56:22Z Script verification uses 1 additional threads
2024-01-11T08:56:22Z Wallet disabled!
2024-01-11T08:56:22Z scheduler thread start
2024-01-11T08:56:22Z Binding RPC on address 127.0.0.1 port 8332
2024-01-11T08:56:22Z Binding RPC on address 172.17.0.2 port 8332
2024-01-11T08:56:22Z [http] creating work queue of depth 16
2024-01-11T08:56:22Z Using random cookie authentication.
2024-01-11T08:56:22Z Generated RPC authentication cookie /root/.bitcoin/.cookie
2024-01-11T08:56:22Z Using rpcauth authentication.
2024-01-11T08:56:22Z [http] starting 4 worker threads
2024-01-11T08:56:22Z Using /16 prefix for IP bucketing
2024-01-11T08:56:22Z init message: Loading P2P addresses…
2024-01-11T08:56:23Z Loaded 72251 addresses from peers.dat  858ms
2024-01-11T08:56:23Z init message: Loading banlist…
2024-01-11T08:56:23Z SetNetworkActive: true
2024-01-11T08:56:23Z Cache configuration:
2024-01-11T08:56:23Z * Using 2.0 MiB for block index database
2024-01-11T08:56:23Z * Using 56.0 MiB for transaction index database
2024-01-11T08:56:23Z * Using 49.0 MiB for basic block filter index database
2024-01-11T08:56:23Z * Using 8.0 MiB for chain state database
2024-01-11T08:56:23Z * Using 335.0 MiB for in-memory UTXO set (plus up to 1907.3 MiB of unused mempool space)
2024-01-11T08:56:23Z init message: Loading block index…
2024-01-11T08:56:23Z Assuming ancestors of block 000000000000000000035c3f0d31e71a5ee24c5aaf3354689f65bd7b07dee632 have valid signatures.
2024-01-11T08:56:23Z Setting nMinimumChainWork=000000000000000000000000000000000000000044a50fe819c39ad624021859
2024-01-11T08:56:23Z Opening LevelDB in /root/.bitcoin/blocks/index
2024-01-11T08:56:24Z Opened LevelDB successfully
2024-01-11T08:56:24Z Using obfuscation key for /root/.bitcoin/blocks/index: 0000000000000000
2024-01-11T08:56:39Z LoadBlockIndexDB: last block file = 4047
2024-01-11T08:56:39Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=33, size=48170530, heights=825241...825273, time=2024-01-11...2024-01-11)
2024-01-11T08:56:39Z Checking all blk files are present...
2024-01-11T08:57:13Z Initializing chainstate Chainstate [ibd] @ height -1 (null)
2024-01-11T08:57:13Z Opening LevelDB in /root/.bitcoin/chainstate
2024-01-11T08:57:14Z Opened LevelDB successfully
2024-01-11T08:57:14Z Using obfuscation key for /root/.bitcoin/chainstate: a419b5abf6f4408e
2024-01-11T08:57:15Z Loaded best chain: hashBestChain=00000000000000000000f180479aa02c5d3f955360d63bf891378571a6c5db8f height=825273 date=2024-01-11T08:47:22Z progress=0.999998
2024-01-11T08:57:15Z [snapshot] allocating all cache to the IBD chainstate
2024-01-11T08:57:17Z Opening LevelDB in /root/.bitcoin/chainstate
2024-01-11T08:57:17Z Opened LevelDB successfully
2024-01-11T08:57:17Z Using obfuscation key for /root/.bitcoin/chainstate: a419b5abf6f4408e
2024-01-11T08:57:17Z [Chainstate [ibd] @ height 825273 (00000000000000000000f180479aa02c5d3f955360d63bf891378571a6c5db8f)] resized coinsdb cache to 8.0 MiB
2024-01-11T08:57:17Z [Chainstate [ibd] @ height 825273 (00000000000000000000f180479aa02c5d3f955360d63bf891378571a6c5db8f)] resized coinstip cache to 335.0 MiB
2024-01-11T08:57:17Z init message: Verifying blocks…
2024-01-11T08:57:17Z Verifying last 6 blocks at level 3
2024-01-11T08:57:17Z Verification progress: 0%
2024-01-11T08:57:37Z Verification progress: 16%
2024-01-11T08:57:53Z Verification progress: 33%
2024-01-11T08:58:01Z Verification progress: 50%
2024-01-11T08:58:05Z Verification progress: 66%
2024-01-11T08:58:09Z Verification progress: 83%
2024-01-11T08:58:12Z Verification progress: 99%
2024-01-11T08:58:12Z Verification: No coin database inconsistencies in last 6 blocks (13042 transactions)
2024-01-11T08:58:12Z  block index          109189ms
2024-01-11T08:58:12Z Opening LevelDB in /root/.bitcoin/indexes/txindex
2024-01-11T08:58:16Z Opened LevelDB successfully
2024-01-11T08:58:16Z Using obfuscation key for /root/.bitcoin/indexes/txindex: 0000000000000000
2024-01-11T08:58:16Z Opening LevelDB in /root/.bitcoin/indexes/blockfilter/basic/db
2024-01-11T08:58:16Z txindex thread start
2024-01-11T08:58:16Z txindex is enabled at height 825273
2024-01-11T08:58:16Z txindex thread exit
2024-01-11T08:58:17Z Opened LevelDB successfully
2024-01-11T08:58:17Z Using obfuscation key for /root/.bitcoin/indexes/blockfilter/basic/db: 0000000000000000
2024-01-11T08:58:17Z Opening LevelDB in /root/.bitcoin/indexes/coinstats/db
2024-01-11T08:58:17Z basic block filter index thread start
2024-01-11T08:58:17Z basic block filter index is enabled at height 825273
2024-01-11T08:58:17Z basic block filter index thread exit
2024-01-11T08:58:18Z Opened LevelDB successfully
2024-01-11T08:58:18Z Using obfuscation key for /root/.bitcoin/indexes/coinstats/db: 0000000000000000
2024-01-11T08:58:18Z Setting NODE_NETWORK on non-prune mode
2024-01-11T08:58:18Z block tree size = 825336
2024-01-11T08:58:18Z nBestHeight = 825273
2024-01-11T08:58:18Z Bound to 127.0.0.1:8334
2024-01-11T08:58:18Z Bound to [::]:8333
2024-01-11T08:58:18Z torcontrol thread start
2024-01-11T08:58:18Z loadblk thread start
2024-01-11T08:58:18Z coinstatsindex thread start
2024-01-11T08:58:18Z coinstatsindex is enabled at height 825273
2024-01-11T08:58:18Z coinstatsindex thread exit
2024-01-11T08:58:18Z Bound to 0.0.0.0:8333
2024-01-11T08:58:18Z Loaded 2 addresses from "anchors.dat"
2024-01-11T08:58:18Z Leaving InitialBlockDownload (latching to false)
2024-01-11T08:58:18Z 2 block-relay-only anchors will be tried for connections.
2024-01-11T08:58:18Z init message: Starting network threads…
2024-01-11T08:58:18Z init message: Done loading
2024-01-11T08:58:18Z net thread start
2024-01-11T08:58:18Z msghand thread start
2024-01-11T08:58:18Z dnsseed thread start
2024-01-11T08:58:18Z opencon thread start
2024-01-11T08:58:18Z addcon thread start
2024-01-11T08:58:18Z Waiting 300 seconds before querying DNS seeds.
2024-01-11T08:58:19Z New outbound peer connected: version: 70016, blocks=825274, peer=4 (block-relay-only)
2024-01-11T08:58:20Z Saw new header hash=00000000000000000003a11c275888851b31265c3f428b110ea7992b808e8ed0 height=825274
2024-01-11T08:59:12Z UpdateTip: new best=00000000000000000003a11c275888851b31265c3f428b110ea7992b808e8ed0 height=825274 version=0x28000000 log2_work=94.658989 tx=950496799 date='2024-01-11T08:55:37Z' progress=0.999999 cache=1.9MiB(12874txo)
2024-01-11T08:59:13Z New outbound peer connected: version: 70016, blocks=825274, peer=16 (outbound-full-relay)
2024-01-11T08:59:13Z New outbound peer connected: version: 70016, blocks=825274, peer=42 (outbound-full-relay)
2024-01-11T08:59:30Z New outbound peer connected: version: 70016, blocks=825274, peer=61 (outbound-full-relay)
2024-01-11T08:59:35Z P2P peers available. Skipped DNS seeding.
2024-01-11T08:59:35Z dnsseed thread exit
2024-01-11T08:59:56Z New outbound peer connected: version: 70015, blocks=825274, peer=87 (outbound-full-relay)
2024-01-11T09:00:06Z New outbound peer connected: version: 70016, blocks=825273, peer=96 (outbound-full-relay)
2024-01-11T09:00:12Z New outbound peer connected: version: 70016, blocks=825274, peer=103 (outbound-full-relay)
2024-01-11T09:00:12Z New outbound peer connected: version: 70016, blocks=825274, peer=105 (outbound-full-relay)
2024-01-11T09:00:23Z New outbound peer connected: version: 70015, blocks=825274, peer=116 (outbound-full-relay)
2024-01-11T09:00:26Z New outbound peer connected: version: 70015, blocks=825274, peer=124 (block-relay-only)
2024-01-11T09:00:27Z New outbound peer connected: version: 70016, blocks=825274, peer=123 (outbound-full-relay)
2024-01-11T09:00:48Z New outbound peer connected: version: 70016, blocks=825274, peer=138 (block-relay-only)
2024-01-11T09:09:30Z New outbound peer connected: version: 70016, blocks=825274, peer=520 (outbound-full-relay)
2024-01-11T09:11:47Z New outbound peer connected: version: 70016, blocks=825274, peer=623 (block-relay-only)
2024-01-11T09:14:05Z Saw new header hash=0000000000000000000074a2e0f71da48dbb78d52b3781e08bbfc1956d178338 height=825275
2024-01-11T09:15:19Z UpdateTip: new best=0000000000000000000074a2e0f71da48dbb78d52b3781e08bbfc1956d178338 height=825275 version=0x24b78000 log2_work=94.659003 tx=950499597 date='2024-01-11T09:13:08Z' progress=0.999999 cache=17.0MiB(125928txo)
2024-01-11T09:22:08Z Disconnecting outbound peer 96 for old chain, best known block = <none>
2024-01-11T09:22:35Z New outbound peer connected: version: 70016, blocks=825275, peer=988 (outbound-full-relay)
2024-01-11T09:22:47Z Saw new header hash=00000000000000000000c3fab0e543137958749bb1b0eb172b89ec959770c85b height=825276
2024-01-11T09:23:51Z UpdateTip: new best=00000000000000000000c3fab0e543137958749bb1b0eb172b89ec959770c85b height=825276 version=0x25994000 log2_work=94.659018 tx=950502892 date='2024-01-11T09:22:26Z' progress=1.000000 cache=25.7MiB(185576txo)
2024-01-11T09:35:23Z Saw new header hash=00000000000000000000ef5607cffa1a956daae585f5c1fea81422f9ec265de8 height=825277
2024-01-11T09:35:23Z [net] Saw new cmpctblock header hash=00000000000000000000ef5607cffa1a956daae585f5c1fea81422f9ec265de8 peer=4
2024-01-11T09:36:17Z UpdateTip: new best=00000000000000000000ef5607cffa1a956daae585f5c1fea81422f9ec265de8 height=825277 version=0x310da000 log2_work=94.659032 tx=950505745 date='2024-01-11T09:35:19Z' progress=1.000000 cache=34.3MiB(254401txo)
2024-01-11T09:38:41Z Saw new header hash=00000000000000000003050b2e299a9c901df3052366b3274d8aac27fb6b0749 height=825278
2024-01-11T09:39:31Z UpdateTip: new best=00000000000000000003050b2e299a9c901df3052366b3274d8aac27fb6b0749 height=825278 version=0x289b8000 log2_work=94.659047 tx=950507484 date='2024-01-11T09:38:19Z' progress=1.000000 cache=36.5MiB(272338txo)
2024-01-11T09:39:40Z New outbound peer connected: version: 70016, blocks=825278, peer=1592 (outbound-full-relay)
2024-01-11T09:42:19Z New outbound peer connected: version: 70016, blocks=825278, peer=1687 (outbound-full-relay)
2024-01-11T09:56:02Z New outbound peer connected: version: 70016, blocks=825278, peer=2304 (block-relay-only)
2024-01-11T09:56:23Z Flushed fee estimates to fee_estimates.dat.

**Comment by deyw-bit** [comment] 2024-01-11 13:05
Upon examining the entire debug.log, which includes log entries from the past few months - it occasionally took up to nine hours to fully load the mempool on my node. 

It's plausible that the mempool.dat could potentially be overwritten by the limited contents of the mempool if a shutdown is initiated before the loading of the mempool is completed.

`grep -E 'Shutdown|mempool|Bitcoin Core version v' /volume1/docker/bitcoin/debug.log`

2023-10-23T11:24:47Z Bitcoin Core version v25.0.0 (release build)
2023-10-23T11:24:47Z Config file arg: mempoolfullrbf="1"
2023-10-23T11:24:48Z * Using 335.0 MiB for in-memory UTXO set (plus up to 286.1 MiB of unused mempool space)
2023-10-23T13:26:39Z Imported mempool transactions from disk: 1131 succeeded, 1655 failed, 0 expired, 0 already there, 0 waiting for initial broadcast
2023-10-23T13:50:54Z Shutdown: In progress...
2023-10-23T13:50:57Z Dumped mempool: 0.0389276s to copy, 1.94065s to dump
2023-10-23T13:51:02Z Shutdown: done
2023-10-23T13:51:09Z Bitcoin Core version v25.0.0 (release build)
2023-10-23T13:51:09Z Config file arg: maxmempool="2000"
2023-10-23T13:51:09Z Config file arg: mempoolexpiry="720"
2023-10-23T13:51:09Z Config file arg: mempoolfullrbf="1"
2023-10-23T13:51:11Z * Using 335.0 MiB for in-memory UTXO set (plus up to 1907.3 MiB of unused mempool space)
2023-10-23T15:32:53Z Imported mempool transactions from disk: 3139 succeeded, 305 failed, 0 expired, 1 already there, 0 waiting for initial broadcast
2023-11-06T17:51:37Z Shutdown: In progress...
2023-11-06T17:51:46Z Dumped mempool: 0.867882s to copy, 7.10853s to dump
2023-11-06T17:56:22Z Bitcoin Core version v25.1.0 (release build)
2023-11-06T17:56:24Z Config file arg: maxmempool="2000"
2023-11-06T17:56:24Z Config file arg: mempoolexpiry="720"
2023-11-06T17:56:24Z Config file arg: mempoolfullrbf="1"
2023-11-06T17:56:25Z * Using 335.0 MiB for in-memory UTXO set (plus up to 1907.3 MiB of unused mempool space)
2023-11-06T18:03:58Z Shutdown: In progress...
2023-11-06T18:03:59Z Shutdown: done
2023-11-06T18:04:15Z Bitcoin Core version v25.1.0 (release build)
2023-11-06T18:04:15Z Config file arg: maxmempool="2000"
2023-11-06T18:04:15Z Config file arg: mempoolexpiry="720"
2023-11-06T18:04:15Z Config file arg: mempoolfullrbf="1"
2023-11-06T18:04:16Z * Using 335.0 MiB for in-memory UTXO set (plus up to 1907.3 MiB of unused mempool space)
2023-11-06T18:07:56Z Shutdown: In progress...
2023-11-06T18:07:57Z Shutdown: done
2023-11-06T18:08:04Z Bitcoin Core version v25.1.0 (release build)
2023-11-06T18:08:04Z Config file arg: maxmempool="2000"
2023-11-06T18:08:04Z Config file arg: mempoolexpiry="720"
2023-11-06T18:08:04Z Config file arg: mempoolfullrbf="1"
2023-11-06T18:08:05Z * Using 335.0 MiB for in-memory UTXO set (plus up to 1907.3 MiB of unused mempool space)
2023-11-06T18:08:05Z Shutdown requested. Exiting.
2023-11-06T18:08:05Z Shutdown: In progress...
2023-11-06T18:08:05Z Shutdown: done
2023-11-06T18:10:26Z Bitcoin Core version v25.1.0 (release build)
2023-11-06T18:10:26Z Config file arg: maxmempool="2000"
2023-11-06T18:10:26Z Config file arg: mempoolexpiry="720"
2023-11-06T18:10:26Z Config file arg: mempoolfullrbf="1"
2023-11-06T18:10:27Z * Using 335.0 MiB for in-memory UTXO set (plus up to 1907.3 MiB of unused mempool space)
2023-11-06T23:22:15Z Imported mempool transactions from disk: 144452 succeeded, 7354 failed, 0 expired, 369 already there, 0 waiting for initial broadcast
2023-12-06T15:31:53Z Shutdown: In progress...
2023-12-06T15:32:06Z Dumped mempool: 1.15567s to copy, 10.5175s to dump
2023-12-06T15:32:26Z Shutdown: done
2023-12-06T15:32:35Z Bitcoin Core version v25.1.0 (release build)
2023-12-06T15:32:45Z Config file arg: maxmempool="2000"
2023-12-06T15:32:45Z Config file arg: mempoolexpiry="720"
2023-12-06T15:32:45Z Config file arg: mempoolfullrbf="1"
2023-12-06T15:32:46Z * Using 335.0 MiB for in-memory UTXO set (plus up to 1907.3 MiB of unused mempool space)
2023-12-06T15:35:10Z Shutdown requested. Exiting.
2023-12-06T15:35:10Z Shutdown: In progress...
2023-12-06T15:35:11Z Shutdown: done
2023-12-06T15:46:49Z Bitcoin Core version v25.1.0 (release build)
2023-12-06T15:46:49Z Config file arg: maxmempool="2000"
2023-12-06T15:46:49Z Config file arg: mempoolexpiry="720"
2023-12-06T15:46:49Z Config file arg: mempoolfullrbf="1"
2023-12-06T15:46:50Z * Using 335.0 MiB for in-memory UTXO set (plus up to 1907.3 MiB of unused mempool space)
2023-12-06T15:49:07Z Shutdown: In progress...
2023-12-06T15:49:44Z Shutdown: done
2023-12-06T15:49:49Z Bitcoin Core version v25.1.0 (release build)
2023-12-06T15:49:49Z Config file arg: maxmempool="2000"
2023-12-06T15:49:49Z Config file arg: mempoolexpiry="720"
2023-12-06T15:49:49Z Config file arg: mempoolfullrbf="1"
2023-12-06T15:49:50Z * Using 335.0 MiB for in-memory UTXO set (plus up to 1907.3 MiB of unused mempool space)
2023-12-06T15:51:21Z Bitcoin Core version v25.1.0 (release build)
2023-12-06T15:51:21Z Config file arg: maxmempool="2000"
2023-12-06T15:51:21Z Config file arg: mempoolexpiry="720"
2023-12-06T15:51:21Z Config file arg: mempoolfullrbf="1"
2023-12-06T15:51:22Z * Using 335.0 MiB for in-memory UTXO set (plus up to 1907.3 MiB of unused mempool space)
2023-12-06T15:53:42Z Shutdown: In progress...
2023-12-06T15:55:04Z Bitcoin Core version v25.1.0 (release build)
2023-12-06T15:55:04Z Config file arg: maxmempool="2000"
2023-12-06T15:55:04Z Config file arg: mempoolexpiry="720"
2023-12-06T15:55:04Z Config file arg: mempoolfullrbf="1"
2023-12-06T15:55:05Z * Using 335.0 MiB for in-memory UTXO set (plus up to 1907.3 MiB of unused mempool space)
2023-12-06T23:49:10Z Imported mempool transactions from disk: 176381 succeeded, 23591 failed, 91 expired, 2853 already there, 0 waiting for initial broadcast
2024-01-09T15:29:21Z Shutdown: In progress...
2024-01-09T15:29:34Z Dumped mempool: 1.0479s to copy, 10.5051s to dump
2024-01-09T15:29:54Z Shutdown: done
2024-01-09T15:30:03Z Bitcoin Core version v25.1.0 (release build)
2024-01-09T15:30:11Z Config file arg: maxmempool="2000"
2024-01-09T15:30:11Z Config file arg: mempoolexpiry="720"
2024-01-09T15:30:11Z Config file arg: mempoolfullrbf="1"
2024-01-09T15:30:12Z * Using 335.0 MiB for in-memory UTXO set (plus up to 1907.3 MiB of unused mempool space)
2024-01-10T01:47:06Z Imported mempool transactions from disk: 155031 succeeded, 6745 failed, 4 expired, 1946 already there, 0 waiting for initial broadcast
2024-01-11T08:55:47Z Shutdown: In progress...
2024-01-11T08:55:57Z Dumped mempool: 0.643629s to copy, 8.92166s to dump
2024-01-11T08:56:11Z Shutdown: done
2024-01-11T08:56:21Z Bitcoin Core version v25.1.0 (release build)
2024-01-11T08:56:21Z Config file arg: maxmempool="2000"
2024-01-11T08:56:21Z Config file arg: mempoolexpiry="720"
2024-01-11T08:56:21Z Config file arg: mempoolfullrbf="1"
2024-01-11T08:56:23Z * Using 335.0 MiB for in-memory UTXO set (plus up to 1907.3 MiB of unused mempool space)

**Comment by glozow** [comment] 2024-01-11 13:21
@deyw-bit can you tell us the specs of your machine?

**Comment by deyw-bit** [comment] 2024-01-11 13:37
> @deyw-bit can you tell us the specs of your machine?

I am running the Bitcoin Core v25.1 node in Docker on Synology NAS DS216+II (with 8GB RAM). 
The node runs in a docker container with OS Debian GNU/Linux 12 (bookworm) with CPU priority set to low and memory limit set to 7 GB.

The Dockerfile contains following: 

***
FROM debian:bookworm-slim
RUN apt-get update -y && apt-get upgrade -y && apt-get install apt -y
RUN apt-get install wget sudo vim gpg curl bash -y
RUN wget https://bitcoincore.org/bin/bitcoin-core-25.1/bitcoin-25.1-x86_64-linux-gnu.tar.gz
RUN wget https://bitcoincore.org/bin/bitcoin-core-25.1/SHA256SUMS.asc
RUN wget https://bitcoincore.org/bin/bitcoin-core-25.1/SHA256SUMS
RUN sha256sum --ignore-missing --check SHA256SUMS
RUN tar xzvf bitcoin-25.1-x86_64-linux-gnu.tar.gz
RUN cd bitcoin-25.1 && ls -al; cp bin/* /bin/;
RUN /bin/bitcoind --version
***

**Comment by glozow** [comment] 2024-01-11 13:43
@deyw-bit How long did IBD take on your machine?

**Comment by deyw-bit** [comment] 2024-01-11 13:51
> How long did IBD take on your machine?

To the best of my recollection, the IBD took approx. 10 days. However, this was a few years ago. I guess last time I triggered IBD was with bitcoin-core-0.21.

**Comment by willcl-ark** [comment] 2024-01-17 10:10
Is there anything actionable left here to be done or can we close this out?

IIUC this mempool was not given enough time to load after restart, but now in addition to `getmempoolinfo` we have logging from #29227.

I have increased my `maxmempoolsize` to see if I can try and re-create the issue, but have only tried loading a 600MB one so far, which was successful and took < 6 minutes:

```log
$ grep mempool debug.log
2024-01-17T09:57:40Z Config file arg: [main] maxmempool="2000"
2024-01-17T09:57:40Z Config file arg: [main] mempoolfullrbf="1"
2024-01-17T09:57:41Z * Using 14326.0 MiB for in-memory UTXO set (plus up to 1907.3 MiB of unused mempool space)
2024-01-17T09:58:04Z Loading 103539 mempool transactions from disk...
2024-01-17T09:58:11Z Progress loading mempool transactions from disk: 10% (tried 10354, 93185 remaining)
2024-01-17T09:58:19Z Progress loading mempool transactions from disk: 20% (tried 20708, 82831 remaining)
2024-01-17T09:58:46Z Progress loading mempool transactions from disk: 30% (tried 31062, 72477 remaining)
2024-01-17T09:59:02Z Progress loading mempool transactions from disk: 40% (tried 41416, 62123 remaining)
2024-01-17T10:01:13Z Progress loading mempool transactions from disk: 50% (tried 51770, 51769 remaining)
2024-01-17T10:01:45Z Progress loading mempool transactions from disk: 60% (tried 62124, 41415 remaining)
2024-01-17T10:02:18Z Progress loading mempool transactions from disk: 70% (tried 72478, 31061 remaining)
2024-01-17T10:02:44Z Progress loading mempool transactions from disk: 80% (tried 82832, 20707 remaining)
2024-01-17T10:03:00Z Progress loading mempool transactions from disk: 90% (tried 93186, 10353 remaining)
2024-01-17T10:03:05Z Imported mempool transactions from disk: 102354 succeeded, 1121 failed, 0 expired, 64 already there, 0 waiting for initial broadcast
```

Extrapolating[^1] says that importing a 2GB mempool should take ~< 30 minutes. With low RAM and CPU priority in a container, as described above, I can see this inflating a fair bit.

> Maybe this utility I created can help copying a live mempool from one node to another

FYI there are `savemempool` and `importmempool` RPCs which can dump and load a `mempool.dat` file too :)

[^1]: https://m.xkcd.com/605/

**Comment by willcl-ark** [comment] 2024-01-17 10:47
OK let's close for now then.

@dev7ba feel free to ping me in here, or open a new issue if this happens again or you have new information.

**Closed by willcl-ark** 2024-01-17 10:47 UTC
Labels: Mempool
